### ISSUE TITLE
Do not Force Auto Increment

### ISSUE THREAD

**Issue by Shelnutt2** [jinzhu/gorm#1002]
If a field is a primary key and a int, gorm forces the field to be a auto_increment field. This breaks down when you have multiple primary keys, or simply the int field is not suppose to be auto_incrementing.

Since gorm has support for the AUTO_INCREMENT tag, it is not needed to be forced.

**Comment by jinzhu** [comment]
Still prefer it is auto increment. and auto incrementing multiple primary keys is supported by some databases, but not mysql.

**Comment by Shelnutt2** [comment]
In this case though it is impossible to use gorm on tables that have multiple integer primary keys. Making it optional would solve it and allow flexibility. The default gorm.Model was modified so existing behavior would be unchanged.

As an alternative implementation, would you be apposed to a patch set that implements an opt-out tag? Something like NO_AUTO_INCREMENT ? Then the existing behavior does not change but someone could opt-out of forcing auto increment keys, especially where things like mariadb/mysql don't support it.

**Comment by jinzhu** [comment]
Hi @Shelnutt2 

You could set the sql type with tag for multiple integer primary keys.

**Comment by Shelnutt2** [comment]
@jinzhu That works well and is a good workaround. Thanks for the support.

**Comment by liaoliaopro** [comment]
You could set the sql type with tag for multiple integer primary keys.
==================================================
@jinzhu Got same trouble. Could you show how to do this?

**Comment by liaoliaopro** [comment]
Got it. thanks.

**Comment by corlinp** [comment]
@liaoliaopro Can you tell us what your solution was?
