### ISSUE TITLE
Composite Field to Json store support

### ISSUE THREAD

**Issue by spacexnice** [jinzhu/gorm#1005]
does gorm support store a composite Field to database by using its json format?

something like below:

type A struct {
        x   string 
        y   string
}

type BTable struct {
        id   int  `gorm:"primary_key"`
        name       A
}

then b_table datatable  will insert a record like below:

("1","{name:{x:"firstname",y:"second_name"}}")

i mean struct A was marshal into a json string and stored ?

is this way supported ,  this could simply my app in some cases. 

thanks ,best regards!

**Comment by jinzhu** [comment]
use `Scaner` , `Valuer`
