### ISSUE TITLE
How Do I Set Timeout?

### ISSUE THREAD

**Issue by JesusIslam** [jinzhu/gorm#1009]
How do I set timeout for a request to the database? I didn't find any explanation in the database.

**Comment by pjebs** [comment]
you do it through the driver - not gorm.

**Comment by pjebs** [comment]
`database/sql`

**Comment by JesusIslam** [comment]
What is the best practice to do it if I am using the built-in dialects?

**Comment by pjebs** [comment]
`.Open` can accept a `database/sql` object created outside of Gorm.

**Comment by JesusIslam** [comment]
Yeah, you are right. It turns out I could change it from the DSN.

Thanks.
