### ISSUE TITLE
CreateTable Not Working

### ISSUE THREAD

**Issue by brandonecraig** [jinzhu/gorm#1016]
struct defined here:
```
type Business struct {
	gorm.Model
	name string
	status string
	public_name string
}
```

and db setup:
```
func setupDB() {
	var err error
	db, err = gorm.Open("postgres", "host=localhost user=gorm dbname=gorm sslmode=disable password=mypassword")
	if err != nil {
		log.Fatal("DB error:", err)
	}
	db.LogMode(true)
	db.CreateTable(&Business{})
}
```

Here is the generated query:
```CREATE TABLE "buinesses" ("id" serial,"created_at" timestamp with time zone,"updated_at" timestamp with time zone,"deleted_at" timestamp with time zone , PRIMARY KEY ("id")) ```

Why is it completely ignoring name, status and public_name?

**Comment by pedromorgan** [comment]
@brandonecraig  trying to help here with a spare hour... and not familaiar with postgres...

What is the problem exactly, is it potgres specific etc.. ? 

and triaging to help jinzhu, who up go.mountains of stuff..

**Comment by brandonecraig** [comment]
My issue is that when creating a table off of a struct none of my fields are being added to the table. Just id, created_at, updated_at, deleted_at. 

My configuration appears to be correct according to the docs yet create table is not including any of my fields.

**Comment by brandonecraig** [comment]
...its because my structs are lower case. Womp, womp.
Nothing to see here.

**Comment by pedromorgan** [comment]
he he .. need that gotcha ;-)
