### ISSUE TITLE
[Proposal] Support for encryption and validations via sql.Scanner and driver.Valuer

### ISSUE THREAD

**Issue by ricochet2200** [jinzhu/gorm#1017]
[This post](https://www.vividcortex.com/blog/2014/11/11/encrypting-data-in-mysql-with-go/) explains how to implement [sql.Scanner and driver.Valuer](http://jmoiron.net/blog/built-in-interfaces/) to provide encryption.  As a bonus, it also creates hooks to allow custom validation (see #984). 

It involves the user creating a custom type that has a function that implements `Value()`:

    type EncryptedString string
    func (e EncryptedString) Value() (driver.Value, error) {
        encrypted := FunctionToEncryptString(e)
        return driver.Value(encrypted), nil
    }

Go's underlying sql code already calls `Value()` and so gorm may already do everything it needs to use this (see #993).  However, this may interfere with gorm's using reflection to infer types.  I'm not familiar enough with gorm nor the reflect package to know if gorm could realize that EncryptedString is a string.  

Other types could be created that implement `Value()` to do validation.  gorm just needs to return the error if it one exists (or store it in gorm.DB.Error).

Decrypting the field would just require adding an additional function to EncryptedString:

func (e *EncryptedString) Scan(src interface{}) error {
    *e = FunctionToDecryptString(b)
    return nil
}

Being able to do this is mostly just dependent on gorm being able to use the custom type and returning the error if needed.

I'm curious for any feedback for this proposal, as well as some direction on how one could proceed with this (code that needs to be changed etc.).

**Comment by Tobiasartz** [comment]
I replied to #984 
There are some validation libraries out there already that anyone can implement themselves.
I feel it's not gorm's responsibility to handle validation

**Comment by ricochet2200** [comment]
I have verified that this feature already works in gorm as is.  It would be good if this feature were documented as it provides fantastic hooks for allowing for custom validation.
