### ISSUE TITLE
Mysql Count Query with gorm internally running two diffrent queries.

### ISSUE THREAD

**Issue by roshan3133** [jinzhu/gorm#1018]
When i am counting number of records for select * its internally running two queries.
dbConn.Find(&s).Count(&count).Error and because of this its increasing my response time on fronted.
this is running below mysql queries
```
[3177.30ms] SELECT  * FROM `TABLE`
[479.35ms] SELECT  count(*) FROM `TABLE`
```

**Comment by pjebs** [comment]
That's by design. Perhaps do a raw query instead.

**Comment by KyleBanks** [comment]
@roshan3133 I also ran into this issue, I think perhaps the documentation isn't 100% clear on how to just do a count. I did find that by doing the following, it reduces it to just the one, correct, count query:

```
db.Model(&model).Count(&count)
```

**Comment by roshan3133** [comment]
thanks its working now
