### ISSUE TITLE
Error type of duplicate unique key

### ISSUE THREAD

**Issue by JesusIslam** [jinzhu/gorm#1019]
Like the title says, I want to catch the error if a user is sending already taken email. Is there any easy function like `mgo.IsDup()` from mgo?

**Comment by pjebs** [comment]
Yes check the error string returned when there is an constraint violation and do a `strings.contain(` foe the error code and the name of violated constraint.

**Comment by JesusIslam** [comment]
Ah, nice insight. Thank you again.
