### ISSUE TITLE
Cannot have unused column named DeletedAt

### ISSUE THREAD

**Issue by snikch** [jinzhu/gorm#102]
I'm currently working with a struct that has a field `DeletedAt` that doesn't exist in the database. Due to the way that the soft delete stuff works, the conditions are added without any checks to see if the DeletedAt column is ignored.

I tried using `scope.FieldByName` however this doesn't return the field definition but the value, so I created a func that actually returns the field object and added a conditional - this sorted it but I wanted to bring it up here to see what the best solution. Perhaps renaming `FieldByName` to `FieldValueByName`?

```go
// scope_private.go : 143
	if !scope.Search.Unscope && scope.HasColumn("DeletedAt") {

		field := scope.FieldByName2("DeletedAt")
		if !field.IsIgnored {
			primaryCondiations = append(primaryCondiations, "(deleted_at IS NULL OR deleted_at <= '0001-01-02')")
		}
	}
```

**Comment by jinzhu** [comment]
Hi @snikch 

Sorry for the delay, just fixed this issue.

**Comment by snikch** [comment]
Cheers, no problem.
