### ISSUE TITLE
Add support for check constraints

### ISSUE THREAD

**Issue by ababo** [jinzhu/gorm#1020]
As far as I know currently we cannot simply add check constraints without using raw SQL. I would like GORM to support that capability.

**Comment by hugows** [comment]
+1. My use case specifically is the "singleton row" like http://stackoverflow.com/questions/33104101/ensure-sqlite-table-only-has-one-row

**Comment by jinzhu** [comment]
There is a `AddForeignKey` method, for auto migrate the constraints, it is duplicated with https://github.com/jinzhu/gorm/issues/450

**Comment by andreynering** [comment]
I opened a PR which adds support to check contraints, but unfortuanaly not for SQLite:

https://github.com/jinzhu/gorm/pull/1452
