### ISSUE TITLE
Confusion about polymorphism in documentation

### ISSUE THREAD

**Issue by benguild** [jinzhu/gorm#1022]
Hi,
I just wanted to write in because I find the current state of the documentation about polymorphism in structs/models to be a bit hard to understand.

```
  type Cat struct {
    Id    int
    Name  string
    Toy   Toy `gorm:"polymorphic:Owner;"`
  }

  type Dog struct {
    Id   int
    Name string
    Toy  Toy `gorm:"polymorphic:Owner;"`
  }

  type Toy struct {
    Id        int
    Name      string
    OwnerId   int
    OwnerType string
  }
```

From: http://jinzhu.me/gorm/associations.html#polymorphism

... What exactly is this doing? There's no "Owner" struct anywhere, so I don't understand what its intended functionality is from the documentation. I get that the cat/dog become owners of the toy but the mixing and matching of strings here is a bit vague with no other explanation.

I'd like to help clear up this documentation if possible, but I need to discuss how this actually works first and how it's intended to work. :)

**Comment by benguild** [comment]
For the record, this did not work:

```
type CreditCard struct {
    Id         uint
    Expiration string
    Pan        string
    Name       string
}
type VisaCreditCard struct {
    CreditCard
    Id         uint
    SomeVisaOption bool
}
```

Running this only created the `SomeVisaOption` column in the database... not the others:

```
database.AutoMigrate(&VisaCreditCard);
```

:\

**Comment by benguild** [comment]
Yet, this works...

```
// Base Model's definition
type Model struct {
  ID        uint `gorm:"primary_key"`
  CreatedAt time.Time
  UpdatedAt time.Time
  DeletedAt *time.Time
}

// Add fields `ID`, `CreatedAt`, `UpdatedAt`, `DeletedAt`
type User struct {
  gorm.Model
  Name string
}
```

```
database.AutoMigrate(&User);
```

... Why?

**Comment by benguild** [comment]
For the record I've cleared up replies in this issue regarding the inheriting of "abstract table" structs, as the issue turned out to simply be the ID column being in both the parent and child struct and therefore causing a collision.

**Comment by benguild** [comment]
From the code:
> // Cat has one toy, tag polymorphic is Owner, then associationType is Owner
> // Toy use OwnerID, OwnerType ('cats') as foreign key

Can't this be explained better?

**Comment by stroborobo** [comment]
The "polymorphic" tag tells Gorm the prefix of the field in Toy for loading. So no extra struct, it's just a string for building the SQL.

**Comment by benguild** [comment]
So it maps Dog.Id to Owner.Id in "Toy"? I don't get it, still.... How would that help? Can you give a better example, or explain how exactly the polymorphism is interpreted or opens a door to some other functionality?

**Comment by stroborobo** [comment]
When you load that association Gorm builds a WHERE based on the type of relationship it inherits from the field and struct tag (if given). If you have a "normal" has-many relationship it'll assume the foreign key has the name of the "parent" struct (e.g. `DogId` in the Toy struct). If it's a polymorphic relationship (or in other words a relationship you don't know the exact parent type of) you have to specify the name of that foreign key.

That means `gorm"polymorphic:Owner"` will make Gorm assume the field is called `OwnerId` or `owner_id` (in the DB). But to differentiate you'll need another field for the parent type's name, that's `OwnerType`.

Load the association *without* polymorphism:

```sql
SELECT * FROM "toys" WHERE ("dog_id" IN (1)) ORDER BY "toys"."id" ASC
```

Load the association *with* polymorphism named "Owner":

```sql
SELECT * FROM "toys" WHERE ("owner_id" IN (1) AND "owner_type" = 'dog') ORDER BY "toys"."id" ASC
```

**Comment by benguild** [comment]
So this literally only applies to cases where you wouldn't manually specify the foreign key?

**Comment by stroborobo** [comment]
That's what an ORM is for, not doing thing manually. I thing I don't really understand the question.

You're loading things based on object of the language (Go) you're using, and if you need to have a thing that is owned by other things of different types, that is a polymorphic relationship.

**Comment by benguild** [comment]
So, in this case, this is a middleware alternative to having separate ID columns for Dog_ID and Cat_ID on the Toy table, with a shared UNIQUE index?

**Comment by stroborobo** [comment]
It's a different use case. Do you want this Toy to be owned exclusively by cats or dogs and possibly by one of each at the same time? Or do you want this to have a single owner of any type? (You might add `Piglet` in the future, who knows)

**Comment by benguild** [comment]
So what behavior is this offering? Is it converting the possible types to like its own bitwise relationships?

**Comment by stroborobo** [comment]
Just try it, you'll see how it works. It's not that fancy, [all it does it building strings from struct names, field names and struct tags][s].

[s]: https://github.com/jinzhu/gorm/blob/master/callback_query_preload.go#L112

**Comment by benguild** [comment]
Right but with the documentation the way it is, I still don't really understand what I'm trying... ha. Does it create a SQL-side relationship for the row? Or, is it just the software equivalent and storing it in a single column for multiple tables?

Is the "type" column sort of an index of possible types? That's sort of making sense to me now, if so. I thought that was just another column that the developer created.

-------------

**To clarify,** does this `gorm:"polymorphic:Owner;"` specifically tell GORM to look for "OwnerId" and "OwnerType" columns, and handle them intelligently? Does GORM then create its own index in "OwnerType"?

**Comment by jinzhu** [comment]
maybe you can refer some rails document to understand it better https://launchschool.com/blog/understanding-polymorphic-associations-in-rails
