### ISSUE TITLE
gorm support `on update` `on delete` `cascade` etc...

### ISSUE THREAD

**Issue by DevSpouk** [jinzhu/gorm#1023]
CREATE TABLE invoice (
        inv_id  INT AUTO_INCREMENT NOT NULL,
        usr_id  INT NOT NULL,
        prod_id  INT NOT NULL,
        quantity INT NOT NULL,
        PRIMARY KEY(inv_id),
        FOREIGN KEY (usr_id) REFERENCES usr(usr_id)
          ON UPDATE CASCADE
          ON DELETE RESTRICT,
        FOREIGN KEY (prod_id) REFERENCES product(prod_id)
          ON UPDATE CASCADE
          ON DELETE RESTRICT
      ) ENGINE=InnoDB CHARACTER SET=UTF8;

in gorm example plx

**Comment by iu0v1** [comment]
[RTFM](http://jinzhu.me/gorm/database.html#add-foreign-key)? :)

**Comment by DevSpouk** [comment]
already :)

**Comment by Tarasovych** [comment]
What about sqlite? It's impossible to [add `ONDELETE` behavior after table was created](https://stackoverflow.com/a/13154958/9506712).

**Comment by MohitKS5** [comment]
Can't this be done using tags ?

**Comment by jon4hz** [comment]
> Can't this be done using tags ?

Yes, it can! But you'll need to add something like `db.Exec("PRAGMA foreign_keys = ON;")` in your init function or at least before you start doing transactions. Otherwise the constraints with sqlite wont work.
