### ISSUE TITLE
migration transactions rollback not work

### ISSUE THREAD

**Issue by zyanho** [jinzhu/gorm#1025]
transactions rollback when i test it with migration, exclude vars lifttime or wrong vars problem.

my system env :
mac osx
mysql---5.7.11
golang---1.6.2

The First Question

user struct -- users tables

```
type User struct {
    UserId    int64  
    UserName  string 
    Pid       string 
    CreatedAt int64  
}
```

my run code:

```
db, _ := gorm.Open("mysql", "user:password@/db?charset=utf8mb4&parseTime=True&loc=Local")

tx := db.Begin()

if err := tx.CreateTable(&User{}).Error; err != nil {
    tx.Rollback()
    return err
}
if err := tx.CreateTable(&User{}).Error; err != nil {
    tx.Rollback()
    return err
}
tx.Commit()
```

when run in second CreateTable statement, it got err msg

```
(Error 1050: Table 'users' already exists)
```

It is expected to rollback and quit, but i check the database table, and users table created without rollback. what's wrong with this?.

The Second Question

```
db, _ := gorm.Open("mysql", "user:password@/db?charset=utf8mb4&parseTime=True&loc=Local")

tx := db.Begin()

if err := tx.CreateTable(&User{}).Error; err != nil {
    tx.Rollback()
    return err
}
if err := tx.Exec("some panic sql").Error; err != nil {
    tx.Rollback()
    return err
}
tx.Commit()
```

if some panic throws in the transactions,  other sql exec before panic. should auto commit. how avoid commit when panic.

thanks for help.

**Comment by pjebs** [comment]
Q1 seems like a MYSQL issue rather than gorm issue. Check mysql docs on how transactions behave when you create a table.

Maybe also Q2.
