### ISSUE TITLE
is it possible that we thread-safely dynamically change gorm logger's level?

### ISSUE THREAD

**Issue by bruceauyeung** [jinzhu/gorm#1027]
this is my scene:

my application is running, then one day my customer told me there is something wrong with database operations. now i'd like to change gorm logger's level dynamically without restarting my application, so i can get more detailed database operation logs.

i checked `SetLogger` function in https://github.com/jinzhu/gorm/blob/master/main.go , it seems not to be thread-safe (goroutine-safe)

**Comment by pjebs** [comment]
You are right.
You'll have to fork the library or lobby to get a mutex lock around the logger variable of DB struct.

**Comment by pjebs** [comment]
Alternatively keep a reference to the original `Logger` that you created for `setLogger` and then change the configuration dynamically (but not the logger itself since no mutex lock).

**Comment by jinzhu** [comment]
Suggest you enable `Debug` mode in your request's middleware
