### ISSUE TITLE
Syntax for ignoring column doesn't work

### ISSUE THREAD

**Issue by randomandy** [jinzhu/gorm#1041]
Using the [syntax to ignore a specific column](http://jinzhu.me/gorm/models.html#model-definition) `gorm:"-"` doesn't work.
Let's assume we have something like this:

	CREATE TABLE public.call
		(
		  id serial NOT NULL,
		  foo varchar(5) NOT NULL,
		  created_at date,
		  updated_at date,
		  deleted_at date,
		  CONSTRAINT call_pkey PRIMARY KEY (id)
		);

	type Call struct {
		gorm.Model
		Foo string
		Bar bool `gorm:"-"`
	}

	var call Call
	if err := db.Create(&call).Error; err != nil {
		fmt.Println(err)
	}

Which would throw an error like:
`pq: column "bar" of relation "call" does not exist`

Tested with Postgres

**Comment by egv** [comment]
use `sql:"-"` for this, it works, although it is not documented

**Comment by randomandy** [comment]
Thanks @egv , I've updated the docs and created a PR
