### ISSUE TITLE
Limit(0) causes all records to be returned

### ISSUE THREAD

**Issue by cbelsole** [jinzhu/gorm#1042]
I edited the limit test to look up users with the limit of `0`. This returns all records. When running directly on a PG database `SELECT * FROM table LIMIT 0;` returns `0` rows.

``` go
func TestLimit(t *testing.T) {
    user1 := User{Name: "LimitUser1", Age: 1}
    user2 := User{Name: "LimitUser2", Age: 10}
    user3 := User{Name: "LimitUser3", Age: 20}
    user4 := User{Name: "LimitUser4", Age: 10}
    user5 := User{Name: "LimitUser5", Age: 20}
    DB.Save(&user1).Save(&user2).Save(&user3).Save(&user4).Save(&user5)

    var users1 []User
    DB.Limit(0).Find(&users1)

    if len(users1) != 0 {
        t.Errorf("Limit should work")
    }
}
```

```
--- FAIL: TestLimit (0.01s)
    query_test.go:354: Limit should work
```

**Comment by benguild** [comment]
A lot of Golang code treats `false` or `0` as like a "cancelled" or "nil" state. In this case, you shouldn't be preparing and calling a function if you want zero rows. That's inefficient because there is latency to/from the database just to prepare and call the query even for 0 rows. You should instead catch this on the client side of things.

**Comment by cbelsole** [comment]
So there are two issues:
1. 0 is a valid limit and the documentation does not mention 0 to cancel out the limit. It only mentions -1.
2. Golang functions that return 0 on an invalid number usually return an error as well. Such as in the case of [stringcovAtoi](https://golang.org/pkg/strconv/#Atoi). If you are looking for an invalid integer you should not check for 0 as 0 is a valid integer. You should check the error.

**Comment by benguild** [comment]
@cbelsole I agree that 0 is a valid limit in many cases but I'm guessing this hasn't been fixed because nobody in their right mind would prepare a query just to fetch 0 rows.

**Comment by cbelsole** [comment]
@benguild That could be. So I see two possible solutions to this:
1. Fix it so that 0 is passed and acts as it does with plain SQL.
2. Call it out in the docs just like you call out -1.

Personally I'd go with 1 since that is the behavior you are expecting to happen when you call something with a limit of 0.

**Comment by jinzhu** [comment]
Fixed that.
