### ISSUE TITLE
Support nested query

### ISSUE THREAD

**Issue by bigdrum** [jinzhu/gorm#1043]
It would be nice if gorm can provide nested query support, such as:

```
db.Select(...).From(db.Select(...).Where(...))
```

I've seen people were asking for features like getting the raw query from Scope, so they can construct the nested query by hand. Such requests were turned down for obvious reason, I think the proper solution is to provide the nested query support directly so people wouldn't try to work around that.

**Comment by jinzhu** [comment]
Sounds tricky to support this...

**Comment by sungwoncho** [comment]
This is supported now using `.QueryExpr`. See the answer by @jinzhu https://stackoverflow.com/questions/46807891/using-a-subquery-in-from
