### ISSUE TITLE
db.NewRecord() return false when I insert something first time

### ISSUE THREAD

**Issue by smartczy** [jinzhu/gorm#1044]
``` go
type Ip_distribution struct {
    Ip          string `gorm:"primary_key"`
}
type Ip struct {
    Ip     string
}

func (i *Ip_distribution) TableName() string {
    return "ip_distribution"
}

func main() {
    db, _ := gorm.Open("mysql", "abc:123@tcp(10.10.10.10:3306)/ramos?charset=utf8&loc=Local")
    item := Ip_distribution{Ip: "1.1.1.1"} 
    fmt.Println(db.NewRecord(item))
    db.Create(&item)
    fmt.Println(db.NewRecord(item))
```

The `1.1.1.1` doesn't exist in mysql before run this function. But the result is : 

```
false
false
```

You know, it should return true when we execute `db.NewRecord(item)` first time. Is this a bug or I misused this function?

**Comment by adriendomoison** [comment]
+1 I have the same problem with object having string as primary_key !

**Comment by cage1016** [comment]
same issue +1

**Comment by jinzhu** [comment]
The `NewRecord` method only check if current value has primary key or not.

If you want to ensure this primary key exists in database, you need to query that like:

`db.First(&Ip_distribution{}, "ip = ?", "1.1.1.1").RecordNotFound()`

**Comment by SirWaithaka** [comment]
The comment on the method was confusing me too, thank you for clearing that out @jinzhu
