### ISSUE TITLE
What is the correct way to read binary for LineString?

### ISSUE THREAD

**Issue by kyawmyintthein** [jinzhu/gorm#1049]
I have following struct:

type GeoLine struct {
    Points [2]GeoPoint `json:"points"`
}

func (p *GeoLine) Scan(val interface{}) error {
    b, err := hex.DecodeString(string(val.([]uint8)))
    if err != nil {
        return err
    }
    r := bytes.NewReader(b)
    var wkbByteOrder uint8
    if err := binary.Read(r, binary.LittleEndian, &wkbByteOrder); err != nil {
        return err
    }

```
var byteOrder binary.ByteOrder
switch wkbByteOrder {
case 0:
    byteOrder = binary.BigEndian
case 1:
    byteOrder = binary.LittleEndian
default:
    return fmt.Errorf("Invalid byte order %d", wkbByteOrder)
}

var wkbGeometryType uint64
if err := binary.Read(r, byteOrder, &wkbGeometryType); err != nil {
    return err
}

if err := binary.Read(r, byteOrder, p); err != nil {
    return err
}

return nil
```

}

The above code is not correct binary scanning. How can I read the binary?

**Comment by jinzhu** [comment]
not a gorm related question.
