### ISSUE TITLE
"too many SQL variables" error when using Preload

### ISSUE THREAD

**Issue by jchavannes** [jinzhu/gorm#1054]
When using `Preload`, e.g.:

```
db.Preload("Teams").Find(&users)
```

I'm getting the following error:

```
too many SQL variables
```

The main issue is that there's no way (or at least I'm not aware of a way) to split into multiple queries based on the limit of variables per query and sqlite3 doesn't have any way to increase the maximum.

Additionally, when outputting queries, I saw that it was not de-duping the preload items.  For example, using just a couple users/teams w/ preload it'll use this query:

```
SELECT * FROM "teams"  WHERE ("id" IN ('1','1','1','1','1','1','1','2','2','2'))
```

You can see it's trying to find the same team multiple times.  I assume this is contributing to the issue.

**Comment by ernestas-poskus** [comment]
> sqlite3 doesn't have any way to increase the maximum

maybe use MySQL / PostgreSQL ?

**Comment by jchavannes** [comment]
> maybe use MySQL / PostgreSQL ?

Yeah, that's a potential workaround.  The workaround I'm doing is to just load manually instead of using `Preload`.

Figured it was worth filing an issue though since it would be easier/convenient to use `Preload` and it looked like there was some room for optimization :)

**Comment by jinzhu** [comment]
We have did some work to remove some duplicated values in the where, hope could avoid this issue.

**Comment by jonrzhang** [comment]
Hi, @jinzhu Thanks for your great work.

I didn't find any solution if I want to use Preload to distinct the where assumption. It still had duplicated values in the where.
I would ask if there was any way to avoid the problem during using Preload()?
I still met the __"too many SQL variables"__ issue.

**Comment by paolobarbolini** [comment]
Hi, I just encountered this problem myself.

From what I'm reading from previous comments this doesn't seem to happen with MySQL and PostgreSQL, so being this an ORM library I think the issue should be addressed in the library, while manually preloading as @jchavannes suggested should only have been a temporary workaround while a proper fix gets implemented.
