### ISSUE TITLE
How to support master slave and multiple database?

### ISSUE THREAD

**Issue by kumarsiva07** [jinzhu/gorm#1055]
How to support master slave and multiple database?

@levinalex Can you add file config for database connection open with multi shard and master/slave?
like active_record sharding [https://github.com/zendesk/active_record_shards](url)

**Comment by jinzhu** [comment]
you could have a load balancer, and make gorm connect the load balancer

**Comment by d4l3k** [comment]
Just for future reference in case anyone else stumbles upon this issue, for master slave topologies you can use https://github.com/tsenart/nap to add client side load balancing. For multi-master topologies like CockroachDB I wrote a library https://github.com/d4l3k/go-lbsql.

There's also https://github.com/benthor/clustersql but it seems to have some issues and not be thread safe.

**Comment by majuansari** [comment]
@d4l3k Could you please share an example with gorm and [tsenart/nap](https://github.com/tsenart/nap) ?
