### ISSUE TITLE
[CRITICAL] Transactions are not automatically rolled back nor database connections closed following panic or unrecoverable error.

### ISSUE THREAD

**Issue by benguild** [jinzhu/gorm#1056]
I've noticed that if there's a panic, any open database transaction is not rolled back automatically nor is that database connection closed. Without doing either, the connection will still remain in the pool but blocked... resulting in lock timeouts elsewhere.

This could be detrimental to a live application containing a bug, and must be resolved.

**Comment by benguild** [comment]
One way to resolve this is to perhaps call "defer" on an anonymous function that checks if commit/rollback has already been called, but this seems kind of silly considering this would need to be included everywhere. Thoughts?

**Comment by benguild** [comment]
Attempting to solve this locally with:

```
		tx := db.Begin();
		finished := false;

		defer func() {
			if (!finished) {
				tx.Rollback();

			}

		}();
```

Then setting `finished` to **true** immediately before calling `Rollback()` or `Commit()` on the transaction.

**Comment by jinzhu** [comment]
Maybe you can write a wrapper to recover possible panics in a transaction.

But better a avoid panics...

**Comment by reinerRubin** [comment]
@benguild 

Have you find any solutions?  Because 
`
defer func {  !finished rollback }
`

looks very impractically. But the basic example is still the same (without a defer structure).
