### ISSUE TITLE
Need `gorm:"nullable"` field attribute

### ISSUE THREAD

**Issue by corvinusy** [jinzhu/gorm#1057]
Hey.
There is some inconvinience while working with NULL values in database.
Using of sql.NullString or sql.NullInt64 requires extra mapping layer between struct-to-store an struct-to-send (json), because direct marshaling NullString/NullInt64 to json is insane.

All that I need is **`gorm:"nullable"`** that will convert 0 and "" to NULL in SQL string before execution.

**Comment by jinzhu** [comment]
Use pointer of a type to be nullable. like use `*string`

**Comment by tjgillies** [comment]
Why use sql.Null* in docs? Anyone have a link to pros/con of using pointer vs sql.Null?

**Comment by anagha-todalbagi** [comment]
@tjgillies https://www.reddit.com/r/golang/comments/5vil0v/use_sqlnullsring_or_string_to_handle_database/
