### ISSUE TITLE
Documentation. Need a digest of all of `gorm:"..."` modifiers.

### ISSUE THREAD

**Issue by corvinusy** [jinzhu/gorm#1058]
Hey.
It would be great if any digest of available modifiers **`gorm:"modifier"`** be presented in documentation.

**Comment by danhardman** [comment]
Was trying to find this earlier. Should definitely be documented

**Comment by JesusIslam** [comment]
+1

**Comment by jinzhu** [comment]
please only use those documented tags from http://jinzhu.me/gorm , only those are considered as stable...
