### ISSUE TITLE
Does it support `optional where sentence`?

### ISSUE THREAD

**Issue by yzprofile** [jinzhu/gorm#1060]
For example:

```go
db.Table("users").Select(*).Where("id > ?", 10).Where("create_at between ? AND ?", nil, nil)
```
the generated sql will be:
```sql
select * from users where id > 10;
```

and 
```go
db.Table("users").Select(*).Where("id > ?", 10).Where("create_at between ? AND ?", 1, 100)
```
the generated sql will be:
```sql
select * from users where id > 10 and create_at between 1 and 100;
```

Thanks.

**Comment by hondrus** [comment]
My solution:
`
        var data Data
	if keys, ok := request.URL.Query()["key"]; ok {
		db = db.Where("username in (?)", keys)
	}
	db = db.Limit(100)
	db.Find(&data) //if keys not exists -> select * from data 
`
