### ISSUE TITLE
Appending association of field on model causes duplicates on model

### ISSUE THREAD

**Issue by danhardman** [jinzhu/gorm#1061]
Sorry for the weird sounding issue title, I'll change it (providing that's possible) if there's a better way to explain this.

I want to create a `User` with a `user.Roles` field of type `[]Role`. Where a `Role` is uniquely identified by its `role.Name` field.

I want to be able to do this by creating a single `User` struct containing all of its information, including roles and passing it to a function that creates all the necessary new records and creates the associations between `User` and `Role`.

The problem occurs when I use the `Append(user.Roles)` method to add the associations. Not only does it add a record in `user_roles`, but it also appends the `[]Role` passed to it onto `user.Roles` causing duplicates on the user struct when I do: `db.Model(&user).Association("Roles").Append(user.Roles)`

The current solution would be to provide the `User` and `[]Role` arguments separately to the function, but what's the point in an ORM if I have to break the relation to make this work...

``` go
package main

import (
    "fmt"

    _ "github.com/go-sql-driver/mysql"
    "github.com/jinzhu/gorm"
    _ "github.com/lib/pq"
    _ "github.com/mattn/go-sqlite3"
)

var db *gorm.DB

type User struct {
    Name  string
    Roles []Role
}

type Role struct {
    Name string `sql:"unique;"`
}

func init() {
    var err error
    db, err = gorm.Open("sqlite3", "test.db")
    // db, err := gorm.Open("postgres", "user=username dbname=password sslmode=disable")
    // db, err := gorm.Open("mysql", "user:password@/dbname?charset=utf8&parseTime=True")
    if err != nil {
        panic(err)
    }
    db.LogMode(true)
}

func main() {
    db.CreateTable(&User{})
    db.CreateTable(&Role{})
    user := User{
        Name:  "Test user",
        Roles: []Role{{Name: "Administrator"}},
    }

    //Create user
    if err := db.Set("gorm:save_associations", false).Create(&user).Error; err != nil {
        panic(err)
    }

    //Create new or find existing roles
    for i := range user.Roles {
        if db.Where("name = ?", user.Roles[i].Name).First(&user.Roles[i]).RecordNotFound() {
            if err := db.Create(&user.Roles[i]).Error; err != nil {
                panic(err)
            }
        }
    }

    //Add relation between user and roles
    if err := db.Model(&user).Association("Roles").Append(user.Roles).Error; err != nil {
        panic(err)
    }

    fmt.Println(len(user.Roles)) //Should be one
}

```

**Comment by danhardman** [comment]
Have you had a chance to take a look at this yet @jinzhu?

**Comment by alejandrorangel** [comment]
I'm Having the same problem

**Comment by zardak** [comment]
Have you tried defining `Role.Name` as a primary key?

**Comment by danhardman** [comment]
I haven't but what's your thinking behind that? Not sure how that would work

**Comment by zardak** [comment]
`.Append`'s behaviour of saving or updating associations lies in calling `.saveAssociations`.

`.saveAssociations` in turn creates a new row if primary key field is not set, or attempts to update existing row otherwise.

**Comment by danhardman** [comment]
The problem isn't duplicates being created in the database, it's that `.Append` adds an extra item on the `User.Roles` field.

**Comment by cad** [comment]
Is this still the case?

**Comment by danhardman** [comment]
@cad I haven't used GORM in a while, try the test script?

**Comment by jinzhu** [comment]
User, Roles are not valid relations, no foreign key defined.
