### ISSUE TITLE
Why was `.CurrentDatabase()' removed?

### ISSUE THREAD

**Issue by jaytaylor** [jinzhu/gorm#1065]
Hi @jinzhu,

I pulled the latest gorm today and was surprised to find that `.CurrentDatabase()` has been removed back in January 2016 in commit [e159ca1914e74d9fdbbac34274472a65ea3576f2](https://github.com/jinzhu/gorm/commit/e159ca1914e74d9fdbbac34274472a65ea3576f2).

Can you please explain why this functionality was eliminated? My app depends on it being available for automatic database table management, so it is pretty inconvenient for it to disappear.

Is the functionality available somewhere else now? Or am I required to hand-implement this for each type DB?

**Comment by jinzhu** [comment]
Hi @jaytaylor 

Would like to reduce exposed first-class API, but you still could get its value with `db.Dialect().CurrentDatabase()`

**Comment by jaytaylor** [comment]
Excellent, thank you for the followup Jinzhu!
