### ISSUE TITLE
mssql Dialect - Create populates an incorrect id field.

### ISSUE THREAD

**Issue by euforia** [jinzhu/gorm#1068]
When performing a `Create` or any insert operation,  the id populated in the data structure is not correct.  In my particular case it populates the field with the id of a pre-existing row rather than the newly generated one.

The simple fix is to add the following `SELECT SCOPE_IDENTITY()` to the `LastInsertIDReturningSuffix` function which currently returns an empty string.  Here's the patch which seems to resolve the issue  - https://github.com/jinzhu/gorm/commit/f2e0e54823966b31c7c487c6bb7407959ed983f1

**Comment by jinzhu** [comment]
We should fixed all issues for mssql, if you still have any problem, please create a new issue.

Thank you.
