### ISSUE TITLE
Preload documentation refers to structs/tables that aren't defined in documentation

### ISSUE THREAD

**Issue by nojo** [jinzhu/gorm#1069]
The documentation for Preloading (http://jinzhu.me/gorm/curd.html#preloading-eager-loading) shows how to preload "Orders" (has many), "Profile" (has one), "Role" (belongs to), but doesn't show the structs or tags that create the appropriate relationships to make preloading work for these.

**Comment by jinzhu** [comment]
Refer http://jinzhu.me/gorm/associations.html
