### ISSUE TITLE
'Scan error on column index' error suppression causes incomplete data loads

### ISSUE THREAD

**Issue by iwilkes** [jinzhu/gorm#108]
In main_private.go line 34, gorm explicitly silences this error. However, when this error is emitted it means that sql stopped processing the row when it hit the problem column. See http://golang.org/src/pkg/database/sql/sql.go line 1564. What this means is that the output structure will have uninitialized values for all columns after the one which generated the error (a clear failure scenario), but Error() returns nil anyway.

**Comment by jinzhu** [comment]
Hi @iwilkes 

This issue have been fixed, sorry for the problem.
