### ISSUE TITLE
Passing data to callbacks

### ISSUE THREAD

**Issue by Guiguillermo** [jinzhu/gorm#1084]
Hello,

I would like to use callbacks to validate my models and to do other stuff (like calling other web services for example).
To do this, I need some configuration information, I currently handle the configuration by passing a struct to the functions which need these configuration data.
My problem is that I can't pass any variable to the callback method (because I don't directly call it). I don't really want to use a global variable to get the configuration because I think it's not a good practice.

So my question is : Is there a way to access to "global app data" from gorm callbacks ?

Thanks in advance

**Comment by jinzhu** [comment]
You could set with `Set` get with `Get`, https://github.com/jinzhu/gorm/blob/master/main.go#L598-L613

Seems like forgot to document it in the README, will add it later.

btw, you might want to check this  out. https://github.com/qor/validations

**Comment by Guiguillermo** [comment]
This is exactly what I was looking for.
Thank you very much.
