### ISSUE TITLE
Add option to use Unix Timestamp for default record.

### ISSUE THREAD

**Issue by timakin** [jinzhu/gorm#1086]
gorm looks like that it supports only `time.Time` instance for `gorm.Model` timestamps.
But `time.Time().Unix()` maybe better to compare each records, data amount will be smaller, and it remove disturbance of the difference of timezone.
gorm.Model should provide unix timestamp option.

**Comment by sdbaiguanghe** [comment]
@timakin  agree!

**Comment by solarhell** [comment]
+1

**Comment by jinzhu** [comment]
You can write a callback for this easily to set its value. refer how GORM set `CreatedAt`, `UpdatedAt`'s value.
