### ISSUE TITLE
no %v.deleted_at <= '0001-01-02' any more? Is this intended?

### ISSUE THREAD

**Issue by maxsonic** [jinzhu/gorm#1090]
hi,

We have been using gorm for a long time on an old version. However, when we change it to a newer version, the deleted_at is not working anymore. After digging in the code for a while, it seems that it is intended to remove %v.deleted_at <= '0001-01-02' from the code?

https://github.com/jinzhu/gorm/compare/50fe6719286b76863fcd9b3498612caae92f7fb8...c1c4f9f86e732a042aac9f37e025893d6d6cabec#files_bucket

![image](https://cloud.githubusercontent.com/assets/1520489/16405478/95962112-3d3a-11e6-8a51-2dc4a2e659aa.png)
![image](https://cloud.githubusercontent.com/assets/1520489/16405486/a681ae60-3d3a-11e6-8d39-3fa6dc0adb14.png)

**Comment by maxsonic** [comment]
found the migrate scripts:)

**Comment by Fyb3roptik** [comment]
Care to link to these migrate scripts?
