### ISSUE TITLE
Search and limit the companies allowed for an account

### ISSUE THREAD

**Issue by cristian-sima** [jinzhu/gorm#1091]
I have 2 structs: Account and Company

I have this relation:

```
type Account struct {
	gorm.Model
	Companies     []business.Company `gorm:"many2many:account_company;"`
}


type Company struct {
	gorm.Model

	Name         string `sql:"size:100"`
        IsActive      bool
}

```

I am using this code to get **all** the companies:

`db.Model(&account).Association("Companies").Find(&companies)`

That is good, and it works. But I want to get the first 10 companies, which their `Name` starts with `N` and are active?

How do I do?

**Comment by danhardman** [comment]
`db.Model(&account).Association("Companies").Find(&companies).WHERE("name LIKE ? AND active = ?", "N%", true).Order("id asc").Limit(10)`

How about that?

**Comment by cristian-sima** [comment]
It is not working.

The `Find` method does not have the `Where`

![image](https://cloud.githubusercontent.com/assets/12199042/16449232/d82ca6e4-3dfe-11e6-992a-cf981eca2e99.png)

@jinzhu Any idea?

**Comment by cristian-sima** [comment]
Neither this way:

![image](https://cloud.githubusercontent.com/assets/12199042/16449276/22a1e338-3dff-11e6-8b25-6778ace06cc4.png)

**Comment by cristian-sima** [comment]
I got is

```
if err := general.Model(&account).Order("name ASC").Where(whereString, likeSearch).Offset(from).Limit(number).Association("Companies").Find(&response.Companies).Error; err != nil {
	controller.CustomAbort(503, "something-wrong")
}
```

Gorm is pretty awesome!!!

**Comment by danhardman** [comment]
Oh yeah sorry, wrote that on here so I couldn't see. Glad you got it working!
