### ISSUE TITLE
Inconsistent Field Names mapping Column Names

### ISSUE THREAD

**Issue by hbfs** [jinzhu/gorm#1093]
Mapping golang struct fields to column names:

```
Ex:
    ID => "id"
    Id => "id"
    MD5 => "m_d5"
    Md5 => "md5"
```

These seems to be converting camelCase to snake_case improperly.

From http://stackoverflow.com/questions/1175208/elegant-python-function-to-convert-camelcase-to-snake-case

```
def convert(name):
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()
Works with all these (and doesn't harm already-un-cameled versions):

>>> convert('CamelCase')
'camel_case'
>>> convert('CamelCamelCase')
'camel_camel_case'
>>> convert('Camel2Camel2Case')
'camel2_camel2_case'
>>> convert('getHTTPResponseCode')
'get_http_response_code'
>>> convert('get2HTTPResponseCode')
'get2_http_response_code'
>>> convert('HTTPResponseCode')
'http_response_code'
>>> convert('HTTPResponseCodeXYZ')
'http_response_code_xyz'
```

Multiple sequential capitals like HTTP should not be translated to H_T_T_P.

**Comment by hbfs** [comment]
HTTPaaBBccDDD => "httpaa_b_bcc_ddd"
I would expect "http_aa_bb_cc_ddd"

Happy to submit a pull request but i cant seem to find where this translation function exists.

**Comment by hbfs** [comment]
Found it here: https://github.com/jinzhu/gorm/blob/021d7b33143de37b743d1cf660974e9c8d3f80ea/utils.go#L68 Not even sure how this test case passes:
https://github.com/jinzhu/gorm/blob/021d7b33143de37b743d1cf660974e9c8d3f80ea/utils_test.go#L18
 is ID a special token?

**Comment by jinzhu** [comment]
Hello @hbfs 

A pull request about this would be helpful, thank you.
