### ISSUE TITLE
How to debug raw statements

### ISSUE THREAD

**Issue by hbfs** [jinzhu/gorm#1094]
For example, if comparing the output via an orm vs raw_sql to see if they match or testing sql features, how is it possible to get the output?
```
db.Table("test").Debug().Raw(PRAGMA table_info(test)")
```
yields nothing. It is possible to use Scan() but the output format is not know beforehand. Using generic map[string]interface{} results in `unsupported destination, should be slice or struct`

**Comment by jinzhu** [comment]
You need to write a `Scanner` interface for scan.

**Comment by hbfs** [comment]
What if I just want the raw string output?
