### ISSUE TITLE
How do I omit attributes in callbacks

### ISSUE THREAD

**Issue by talbright** [jinzhu/gorm#1100]
Tried all the following, nothing worked:

```go
func (t *TwitterBox) BeforeUpdate(db *gorm.DB) (err error) {
  db.Omit("oauth_token", "oauth_secret")
  return
}

func (t *TwitterBox) BeforeUpdate(scope *gorm.Scope) (err error) {
  scope.Search.Omit("oauth_token", "oauth_secret")
  return
}

func (t *TwitterBox) BeforeUpdate(scope *gorm.Scope) (err error) {
  attrs, _ := scope.InstanceGet("gorm:update_interface")
  attrsMap, _ := attrs.(map[string]interface{})
  delete(attrsMap, "oauth_token")
  delete(attrsMap, "oauth_secret")
  scope.InstanceSet("gorm:update_interface", attrsMap)
  return
}
```

Any help appreciated.

**Comment by jinzhu** [comment]
It won't works as the callback will be run after get those fields need to be update.

But I think scopes would be helpful for you.

https://github.com/jinzhu/gorm/blob/master/main.go#L203

**Comment by talbright** [comment]
Yeah I just ended up having to add ``Omit`` anyplace I did an ``Update``, but I can see that scopes would be a more elegant way to accomplish that. Thanks!
