### ISSUE TITLE
Update an empty entity user{} omit the where condition, is that a feature ?

### ISSUE THREAD

**Issue by YanshuoH** [jinzhu/gorm#1112]
Hello,

Sorry to bother. 

Recently I use `db.model(&user).Updates(...)`, in which `user` is an empty object. According to the logs, this will build a SQL without any `where` condition. 

This results to a fully update of the related table.

Is that a desired feature? It just seems quite dangerous.

Thanks.

**Comment by unipolac** [comment]
Yes this is the behaviour, in my code I had to put some checks if the PK was set before calling this function

**Comment by alecha** [comment]
I've encountered the same behaviour, and I've solved checking if the user_id is not 0 before calling all this kind of function :/

**Comment by YanshuoH** [comment]
@pedromorgan I don't know if it's really a bug. When I look in to : https://github.com/jinzhu/gorm/blob/master/scope.go#L675, there's a check for primary key and I thought it is a desired feature.

@alecha Thanks for reply. I've done the same thing :)

**Comment by danhardman** [comment]
This is intended. In some instances, you may want to update a field on all records, where would specifically not provide a primary key.

You simply need to treat GORM as you would a standard SQL statement.

**Comment by YanshuoH** [comment]
@danhardman Thank you. One time I encountered a sql-sever-level errror (I guess I was trying to read a table while there's a lock on it), the surly found object returned an empty entity, so that's where this issue about.

Now every check before `update`. We may close this issue.
