### ISSUE TITLE
Cannot SELECT additional columns using multiple scopes. — Suggesting `.AndSelect()` addition?

### ISSUE THREAD

**Issue by benguild** [jinzhu/gorm#1116]
This seems like more of a design issue here, but:
**If including a bunch of scopes in a query, there's no way to "append" additional `.Select()` calls without replacing the previous one...** as far as I can tell.

It'd be nice to have something like this when building a query to fetch multiple columns using several additional scopes.

---

The only workaround I've found is to build the query using external function calls and pass back SELECT columns that can be joined together with string concatenation, but this seems a bit manual and could definitely be cleaner.

**Comment by jinzhu** [comment]
Maybe better to combine selected attrs before pass to `DB`?
