### ISSUE TITLE
Broken edge(?) case in column mapping

### ISSUE THREAD

**Issue by rtfb** [jinzhu/gorm#1117]
I have recently updated to the tip and the following code stopped working.

I have a table with a string column `body`, which holds markdown. And I map it to a struct like this:

``` go
type EntryTable struct {
	// other fields...
	Body     template.HTML `sql:"-"`
	RawBody  string        `gorm:"column:body"`
}
```

As you see, I map the `body` column to the `RawBody` field, but at the same time, there's a `Body` field in the struct, which should be ignored by Gorm. This used to work fine earlier. But now with the tip, I'm getting this error: `"sql: Scan error on column index 4: unsupported driver -> Scan pair: []uint8 -> *template.HTML"`.

I have renamed my field from `Body` to `HTML` and the error went away, so I'm pretty sure this has something to do with column mapping.

**Comment by jinzhu** [comment]
Hi @rtfb 

Thank you for your report.
