### ISSUE TITLE
deleted_at is not a good design for soft delete!!!!

### ISSUE THREAD

**Issue by cocotyty** [jinzhu/gorm#1121]
It is not good for table that has unique index.

please change deleted_at from timestamp to int.
soft delete like this:
```sql
update table set deleted_at = id where id = 1
```
query like this:
```sql
select * from table where deleted_at=0
```
unique key:
(uni,deleted_at)

**Comment by cocotyty** [comment]
please do not use timestamp !

**Comment by jinzhu** [comment]
You could do use that.

Sometime you want to keep multiple versions of deleted data, could create unique index with id, deleted_at
