### ISSUE TITLE
关于关联表问题

### ISSUE THREAD

**Issue by eaglewu** [jinzhu/gorm#1124]
目前看到支持  A B 表关联 Join 操作

支持通过第三张关系映射表操作吗？

例如  a -> m <-b
Table a
id, ...

Table  m
a_id, b_id

Table b
id, ....

生成 SQL：

```sql
SELECT a.*, b.* FROM a 
JOIN m ON m.a_id = a.id 
JOIN b ON m.b_id = b.id
```

（除了手写 SQL 的方式）

**Comment by owengaozhen** [comment]
preload

**Comment by jinzhu** [comment]
可以的, Joins

**Comment by sgon00** [comment]
This can not be done with a single sql query in GORM up to now (1.9.10). Because if you want to get `b.*`, you have to use Preload. And if you use Preload, you will end up using more than 1 SQL query. Refer to https://github.com/jinzhu/gorm/issues/1436
