### ISSUE TITLE
Is there any idea setting both 'has one' and 'belongs to' relation?

### ISSUE THREAD

**Issue by yoshiya0503** [jinzhu/gorm#1125]
For example, see follow code.

```
// User has one credit card.
type User struct {
    gorm.model
    Email string `gorm:"not null;type:text"`
    CreditCard CreditCard
}

// Credit card belongs to user.
type CreditCard struct {
    gorm.model
    Number int `gorm:"not null;type:int"`
    User User
}
```
Of corse, recursive type error has occurred.

is there any other way to set both has_one and belongs_to.
(ActiveRecord(RoR) can resolve the problem so simple way.  set both has_one, belongs_to to each model.)

or...

which should we set foreign key, 'CreditCard has user_id' or 'User has creditcard_id'.(both?)

**Comment by zardak** [comment]
Use pointers to structs instead
```
// User has one credit card.
type User struct {
    Email string `gorm:"not null;type:text"`
    CreditCard *CreditCard
}

// Credit card belongs to user.
type CreditCard struct {
    Number int `gorm:"not null;type:int"`
    User *User
}
```
https://play.golang.org/p/fIfXKml6rD

**Comment by danhardman** [comment]
Pretty sure you need `CreditCard` to have a foreign key column for belongsTo.

```
type CreditCard struct {
  Number int ...
  User User
  UserID uint
}
```

**Comment by yoshiya0503** [comment]
Oh, good solution. 

thank you!!
