### ISSUE TITLE
How to 'force' ignore the model default fields created_at , deleted_at , updated_up 

### ISSUE THREAD

**Issue by cloudtrends** [jinzhu/gorm#1126]
hi all ,

How to 'force' ignore the model default fields created_at , deleted_at , updated_up 

(Error 1054: Unknown column 'deleted_at' in 'field list') 
(Error 1054: Unknown column 'created_at' in 'field list') 

cause I have my own version of created_at ,deleted_at , updated_at fields.

thanks.

**Comment by cloudtrends** [comment]
I removed the gorm.Model  solved this.

**Comment by mtatarau90** [comment]
After you removed gorm.Model  the relations (has many/ many to many) still works ?

**Comment by slaveofcode** [comment]
Are there any other solution than removing `gorm.Model` ?
