### ISSUE TITLE
created_at,update_at not same as my local time. 

### ISSUE THREAD

**Issue by vutung7193** [jinzhu/gorm#1130]
When I update record, the update_at time is not same my local time server. 
How i solve it??

**Comment by vutung7193** [comment]
I found my issue. When connect to database, i miss "&loc=Local" parameter. And it causes my above problem. Thanks for watching!

**Comment by guptamisha** [comment]
Is there any similar parameter for postgres? Since loc=Local doesnt work in case of postgres.
