### ISSUE TITLE
http://gorm.jinzhu.me

### ISSUE THREAD

**Issue by danhardman** [jinzhu/gorm#1133]
Any way you can add a gorm subdomain to `jinzhu.me` instead of using `/gorm`?

It's a mild inconvenience typing gorm into the browser address bar and not being suggested `http://jinzhu.me/gorm` and instead being suggested `https://github.com/jinzhu/gorm`.

Thank you!

**Comment by jinzhu** [comment]
the `jinzhu.me` is hosted by github, so the name has to follow its rule.
