### ISSUE TITLE
Non-unique many-to-many relationship?

### ISSUE THREAD

**Issue by danhardman** [jinzhu/gorm#1135]
I have two models, **Cart** and **Product**. I want products to be able to belong to many **Carts**, and **Carts** to have many **Products**, including potentially multiple of the same **Product** (think quantities).

The standard method of decorating the field with `gorm:"many2many:cart_products;"` only allows the **Cart** model to contain unique **Product** relationships.

Is there any way I can allow duplicates?

**Comment by danhardman** [comment]
Is there any way I can do this or am I going to have to handle the relationship manually?

**Comment by rpoletaev** [comment]
i think you should use linktable like:
```
type CartProducts struct {
    CartID uint `gorm:"primary_key:true"`
    ProductID uint `gorm:"primary_key:true"`
    Quantity uint
    Price, ...Amount, etc
}
```

**Comment by danhardman** [comment]
@rpoletaev I suppose. I think that might work better for what I'm doing actually.

Even so, non-unique many-to-many would be kind of useful. Would just need to add a primary key column to the pivot table
