### ISSUE TITLE
How should wordk relation Many To Many?

### ISSUE THREAD

**Issue by rpoletaev** [jinzhu/gorm#1136]
I'm trying to use this guide [Many To Many](http://jinzhu.me/gorm/associations.html#many-to-many)

`package main

import (
	"fmt"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
)

type Rl struct {
	gorm.Model
	Name string
}

type Accnt struct {
	gorm.Model
	Email string
	Roles []Rl `gorm:"many2many:accnt_rls"`
}

func main() {
	db, _ := gorm.Open("postgres", "user=postgres password=pass dbname=postgres sslmode=disable")

	db.CreateTable(&Rl{}, &Accnt{})

	admRole := &Rl{Name: "Admin"}
	db.Create(admRole)

	acc := &Accnt{Email: "some@some.email"}
	db.Create(acc)
	acc.Roles = []Rl{*admRole}
	db.Save(acc)

	account := &Accnt{}
	db.First(account)
	fmt.Println("first account is ", account.ID, " ", account.Email) //first account is  some@some.email

	role := &Rl{}
	db.First(role)
	fmt.Println("first role is ", role.ID, " ", role.Name) //first role is  1 Admin

	relatedRoles := []Rl{}
	db.Model(account).Related(&relatedRoles)

	fmt.Println(len(relatedRoles))  //0 but i expected 1
}`

![account_roles](https://cloud.githubusercontent.com/assets/5208802/17439251/dd41017c-5b2f-11e6-8c9b-d170fea555fe.jpg)

What am i doing wrong?

**Comment by rpoletaev** [comment]
i was able to get related data with Association(), but why do not work Related()?

**Comment by zardak** [comment]
It's not possible to deduce the field so you have to specify it explicitly.
```
db.Model(account).Related(&relatedRoles, "Roles")
```
