### ISSUE TITLE
is it possible .Row return nil

### ISSUE THREAD

**Issue by prima101112** [jinzhu/gorm#1143]
i have different argument with my friend and he was said we should do `defer rows.Close() ` when rows is not nil. 
```
 rows, rowerr := db.Db.Table("table").Select("row").Where("id = ?", val).Rows()
    if rows != nil {
        defer rows.Close()
    }
```

just asking you is that necessary ?
and is it any condition that rows will return nil ?

thanks and hope for your replay

**Comment by dmeijboom** [comment]
Since ```rows``` is a pointer it can always be nil. Looking at the sqlite3 package for example (see: https://github.com/mattn/go-sqlite3/blob/e118d4451349065b8e7ce0f0af32e033995363f8/sqlite3.go#L563) is does return nil when there is an error. So yes, it's possible!
