### ISSUE TITLE
Open retries/reattemps

### ISSUE THREAD

**Issue by leocavalcante** [jinzhu/gorm#1145]
Hi,
I'm having problems with Docker, MySQL container isn't ready by time Golang container tries to open a connection. This is stated by Docker in: https://docs.docker.com/compose/startup-order/

As they say in the doc, the best solution is to handle in the application. Does gorm have something to handle retries after a failed `Open` call?

Or does someone have hints on this?

Thanks.

**Comment by pjebs** [comment]
If it fails, put the goroutine to sleep and try again. Put it in an infinite loop until it finally connects.

**Comment by prima101112** [comment]
i think gorm dont have that yet, and yes you must put connection to infinite loop until finaly connects

**Comment by leocavalcante** [comment]
Thanks.
I added a `time.Sleep(time.Duration(3) * time.Second)` just before the `gorm.Open()` to make it work.

Will try something w/ goroutines.
