### ISSUE TITLE
Error 1075 occurs when one of composite primary key is int

### ISSUE THREAD

**Issue by seaguest** [jinzhu/gorm#1147]
Hello,

I have a struct which has a composite primary key, but when one of them is int type, I got thsi error:
`_(Error 1075: Incorrect table definition; there can be only one auto column and it must be defined as a key)_ 
`

Here is my struct:
```
type WatchHistory struct {
    UserId    []byte `gorm:"primary_key;size:16"`
    VideoId   uint64 `gorm:"primary_key"`
    CreatedAt time.Time
    UpdatedAt time.Time
}

```

It seems when a int type is primary key, then it becomes auto_increment, but I think here it should be an exception because it is part of composition primary key, right?

Is there any solution?

best regards

**Comment by prima101112** [comment]
this issue is don't have correlation with autoinc 
you should not have 2 primary key in one table.

could you please explaint what you are trying to do

**Comment by seaguest** [comment]
@prima101112 ,the composite primary key is quite often, and GORM does support it except the case mentioned here.
The composition primary key means only the combination of the two key can identify the record.

**Comment by jinzhu** [comment]
Seems like you have to define your struct like that. notice the order of fields have been changed, seems funny ;)

```go
type WatchHistory struct {
	VideoId   uint64 `gorm:"primary_key"`
	UserId    []byte `gorm:"primary_key;size:16"`
	CreatedAt time.Time
	UpdatedAt time.Time
}

```
