### ISSUE TITLE
deleted_at not null issue

### ISSUE THREAD

**Issue by Fyb3roptik** [jinzhu/gorm#1149]
I have been using revel and gorm for a while with no issues. Now I am seeing this database issue. When I create anything in any table it adds info to the deleted_at field but is then doing this to find it

SELECT * FROM "developers"  WHERE "developers".deleted_at IS NULL AND ((auth_key = '21f0835e-7bd5-4246-9df6-19c2a0e60c98'))

so obviously it will return no results. It appears that sometime ago the other deleted_at check was taken out. Can we please get this resolved ASAP

**Comment by zardak** [comment]
Currently running it in production without issues.
If you're using soft delete without `gorm.Model`, then be sure to use not the plain `time.Time` field, but a pointer to it:
```
type User struct {
    Id         int
    Username   string
    ...
    CreatedAt  time.Time
    UpdatedAt  time.Time
    DeletedAt  *time.Time
}
```

**Comment by Fyb3roptik** [comment]
I am not sure. I know I havent updated since March and now that I have it is not working for me. I dont feel comfortable editing a godep, since it would get overwritten anyways. Not sure if that is what you meant.

**Comment by zardak** [comment]
If you expect help, don't make me pull all the details out of you.
Your embedded `BaseModel` struct must contain the `DeletedAt` field, make sure its type is actually a pointer, like `DeletedAt *time.Time`

**Comment by Fyb3roptik** [comment]
Yeah nevermind I went full retard =)

**Comment by zardak** [comment]
No problems.
Consider using stackoverflow for questions next time. And, please, close the issue if its resolved.
