### ISSUE TITLE
Too easy to DELETE entire tables!

### ISSUE THREAD

**Issue by zwass** [jinzhu/gorm#1152]
I noticed in [the documentation](http://jinzhu.me/gorm/curd.html#delete) that if a primary key is not specified in a `db.Delete` call, all of the columns are deleted.

This is truly scary. It seems like it would be incredibly easy to write code that accidentally wipes an entire table when attempting to delete a single row.

```
func deleteUser(db *gorm.DB) {
	// Whoops, this function accidentally doesn't specify the primary key
	user := getUserToDelete()

	db.Delete(&user)
	// And now everything is gone
}
```

Is there a way to change this behavior to cause an error, do nothing, or almost anything else besides deleting the entire users table?

**Comment by danhardman** [comment]
Agreed, although it would be a breaking change and therefore even if an update were to be made, it wouldn't be implemented until the next major release.

**Comment by zwass** [comment]
It is also astonishingly easy to cause the equivalent problem with UPDATEs, and this doesn't even seem to be documented.

Perhaps there could be a configuration option (defaulting to off) to prevent this kind of behavior unless it is explicitly asked for. At the major version the default could be changed to on so that everyone benefits by default.

**Comment by danhardman** [comment]
@zwass Doesn't update always use the primary key? I.e. It will look for a record with the primary key of 0?

**Comment by jinzhu** [comment]
Hi All,

I think what you need to do if add error check, to check the user is valid or not before delete it.

**Comment by zwass** [comment]
@jinzhu Of course an error check would be appropriate. The problem here is what if this is forgotten and code makes it into production without this check? Is it reasonable to you that a small bug in code like that could have consequences as extreme as deleting an entire database table?

**Comment by danhardman** [comment]
I definitely don't think relying on the developer to do `db.NewRecord(value)` each time is a good way to do things. Unfortunately, as @jinzhu pointed out in my PR, it's hard to determine whether or not the developer wants to delete everything.

Say you want to delete all users with an empty name (just go with it)

```go
db.Delete(&User{Name:""})
```

That wouldn't have a primary key, so we can't only make **Delete** work if a primary key is set.

As string types have a "zero-value" of "", and we're not setting any other field on User, it would be totally "zero-valued", so we can't make **Delete** only work if we're not passing it a non "zero-valued" struct.

Not even sure this example is good tbh, but the point is, it's hard to determine whether it's intentional or not.

**Comment by zwass** [comment]
For this and many other reasons (such as https://github.com/jinzhu/gorm/pull/805) we are moving off Gorm as soon as we can. It seemed convenient at first, but it looks likely to cause serious pain as our application grows.

**Comment by jinzhu** [comment]
Tell me with which ORM or how to write RAW SQL you don't need to check your argument is valid or not?

And you could write `Delete` like that: `db.Delete(&User{}, "id = ?", id)` when you are not sure about your data, just don't use the dangerous way.

**Comment by win5do** [comment]
```
db.Delete(&User{
    name: "xxx"
})
```
delete all rows of the tabel, what the fuck!

**Comment by jinzhu** [comment]
@win5do  https://godoc.org/github.com/jinzhu/gorm?hide=1&import-graph=#DB.BlockGlobalUpdate

Are you using soft delete? which can save your life in many cases.

**Comment by win5do** [comment]
@jinzhu  
thanks for provide solution, recommend  enabled by default and put  in a prominent place at docs

this table create by others,  don't use soft dele o(╥﹏╥)o
