### ISSUE TITLE
Defining multiple indexes? "unique_index:ui1,ui2" and "unique_index:ui1:unique_index:ui2" don't seem to work.

### ISSUE THREAD

**Issue by benguild** [jinzhu/gorm#1153]
Consider this example:

```go

type BaseObject struct {
  ID uint64
  SomeID uint64 `gorm:"unique_index:ui1"`
}

type SpecificObject struct {
  BaseObject
  SomeOtherID uint64 `gorm:"unique_index:ui1,ui2"`
  YetAnotherID uint64 `gorm:"unique_index:ui2"`
}
```

... This doesn't seem to work. The `unique_index` is omitted entirely for me on the `SomeOtherID` column since it has multiple indexes defined. Swapping this with `unique_index:ui1:unique_index:ui2` of course only does one of them as one configuration supersedes the other.

**Comment by jinzhu** [comment]
refer https://github.com/jinzhu/gorm/blob/master/migration_test.go#L372-L380
