### ISSUE TITLE
How to define jsonb on model?

### ISSUE THREAD

**Issue by rafaeljesus** [jinzhu/gorm#1155]
Hi brothers,

I am stuck with a error `(sql: converting Exec argument #5's type: unsupported type map[string]interface {}, a map)`

I don't know how to properly handle jsonb on models,

Basically I have a router:
```go
func Create(c echo.Context) error {
  event := &models.Event{}

  if err := c.Bind(event); err != nil {
    return err
  }

  db.Repo.Create(&event)

  return c.JSON(http.StatusOK, &event)
}
```

And my model defined as:
```go
type Event struct {
  gorm.Model
  Name string
  Status string
  Payload map[string]interface{} `type: jsonb not null default '{}'::jsonb`
}
```

Yes I do know that `map[string]interface` is no supported, but I need this type so `c.Bind(event)` works properly,

Any suggestions to handle that?

**Comment by pedromorgan** [comment]
I take it that this is a postgres issue right ? 

big.syster :-)

**Comment by rafaeljesus** [comment]
Yes it seems to be. It does not accept `map[string]interface{}` for maps structure and I have no ideia how to handle that on a clean fashion, any suggestion mate?

**Comment by jinzhu** [comment]
@rafaeljesus you should defined a `Scanner`, `Valuer`, refer `sql.NullString`

**Comment by rafaeljesus** [comment]
@jinzhu Perfect, I will look for this stuff, so far I've found [this](http://coussej.github.io/2016/02/16/Handling-JSONB-in-Go-Structs)

**Comment by pedromorgan** [comment]
So this need to go in the Docs can we do that??

**Comment by rafaeljesus** [comment]
Done :laughing:

models/event.go
```go
package models

import (
  "github.com/jinzhu/gorm"
)

type Event struct {
  gorm.Model
  Name string
  Status string
  Payload PropertyMap `type: jsonb not null default '{}'::jsonb`
}
```

models/property_map.go
```go
package models

import (
  "encoding/json"
  "database/sql/driver"
  "errors"
)

type PropertyMap map[string]interface{}

func (p PropertyMap) Value() (driver.Value, error) {
  j, err := json.Marshal(p)
  return j, err
}

func (p *PropertyMap) Scan(src interface{}) error {
  source, ok := src.([]byte)
  if !ok {
    return errors.New("Type assertion .([]byte) failed.")
  }

  var i interface{}
  if err := json.Unmarshal(source, &i); err != nil {
    return err
  }

  *p, ok = i.(map[string]interface{})
  if !ok {
    return errors.New("Type assertion .(map[string]interface{}) failed.")
  }

  return nil
}```

**Comment by jinzhu** [comment]
> So this need to go in the Docs can we do that??

FAQ would be helpful.

**Comment by Abhisek1994Roy** [comment]
invalid type assertion: kycData.Input.(map[string]<inter>) (non-interface type InputMap on left)
Getting this error on running the code. Any ideas?

**Comment by yonasstephen** [comment]
@mattshma @rafaeljesus does the default tag work for you? I tried both of y'all approaches and it still writes null into the DB. The only way I can write default `{}` is if I do the following:
```
func (p PropertyMap) Value() (driver.Value, error) {
  // check if map is empty
  if len(p) == 0 {
    return []byte("{}"), nil
  }
  return json.Marshal(p)
}
```
