### ISSUE TITLE
How to get float values in gorm query

### ISSUE THREAD

**Issue by amaendeepm** [jinzhu/gorm#1157]
I am using below query using db.Raw construct and always get 0 back as float value returned by GORM, but standalone query execution provided me correct float value

(1) Here is Query
-------------------------

select( select count(adults.id) from adults, invitations where adults.email = invitations.invited_email AND invitations.status = 'Accepted')  *100/ (select count(DISTINCT adults.email) from adults) as growth_value

(2) Here is GORM Code:
-------------------------------

	type OrgGrowth struct {
		Growth		float64	`json:"growth_value"`
	}

	var orgGrowth []OrgGrowth

	err := h.db.Raw("select( select count(adults.id) from adults, invitations where adults.email = invitations.invited_email AND invitations.status = 'Accepted')  *100/ (select count(DISTINCT adults.email) from adults) as growth_value").Scan(&orgGrowth).Error

	if err != nil {
		replyErrorMsg(h, rw, req, http.StatusNotFound, err)
		return
	}
	rec := orgGrowth[0]
	ctx := appengine.NewContext(req)
	ctx.Infof("Growth returned as: %f", rec.Growth) //Always returning ZERO ???

**Comment by danhardman** [comment]
Have you checked the query works in your client? You're not performing a `JOIN` between adults and invitations so that may screw things up.

I think the main problem is you're trying to assign a float type to a OrgGrowth type.

```go
var growth float64
db.Raw(...).Scan(&growth)
```

**Comment by andyjeffries** [comment]
I'm still seeing this problem?  My code:

```go
var averageTime float64
gorm.Raw("SELECT AVG(TIME_TO_SEC(TIMEDIFF(built_at, created_at))) as AverageTime FROM instances WHERE TIME_TO_SEC(TIMEDIFF(built_at, created_at)) > 0 AND TIME_TO_SEC(TIMEDIFF(built_at, created_at)) < 180 AND deleted_at IS NULL").Scan(&averageTime)
fmt.Println("Average build time is", averageTime)
```

Outputs `0` as the averageTime (actually I've changed the logging code above, but it returns 0 in a JSON structure as well as through our customer logger).

The same executed in MySQL:

```
mysql> SELECT AVG(TIME_TO_SEC(TIMEDIFF(built_at, created_at))) as AverageTime FROM instances WHERE TIME_TO_SEC(TIMEDIFF(built_at, created_at)) > 0 AND TIME_TO_SEC(TIMEDIFF(built_at, created_at)) < 180 AND deleted_at IS NULL;
+-------------+
| AverageTime |
+-------------+
|     92.5000 |
+-------------+
1 row in set, 20 warnings (0.00 sec)
```

So I know the SQL works.

**Comment by andyjeffries** [comment]
BUMP

**Comment by danhardman** [comment]
Turn log mode on and run that query again. Show me what the output is.

Have you tried doing

```go
type Result struct {
 AverageTime float64
}

var result Result
gorm.Raw("SELECT AVG(TIME_TO_SEC(TIMEDIFF(built_at, created_at))) as AverageTime FROM instances WHERE TIME_TO_SEC(TIMEDIFF(built_at, created_at)) > 0 AND TIME_TO_SEC(TIMEDIFF(built_at, created_at)) < 1800 AND deleted_at IS NULL").Scan(&result)
```
