### ISSUE TITLE
BeforeFind callback to chain Preload()s?

### ISSUE THREAD

**Issue by danhardman** [jinzhu/gorm#1159]
Is there any way to create a `BeforeFind` callback so I can chain `Preload()` calls onto the request?

There are a few instances where I have to do `db.Preload("Roles")....First(&user, id)`, where the **User** model has a lot of related models. Obviously I've defined a function `GetUser(id)` that does all that for me, but there's other areas where it doesn't make sense to use that function. 

It would be nice if I could define a callback on **User** to always chain on the necessary `Preload()` calls so that any query for a **User** has all its relations.

**Comment by jinzhu** [comment]
Hi @danhardman 

You could write a callback for this. http://jinzhu.me/gorm/development.html#write-plugins

**Comment by danhardman** [comment]
Can I get a hand doing it? This is what I've got so far.

```go
package main

import (
	"fmt"

	_ "github.com/go-sql-driver/mysql"
	"github.com/jinzhu/gorm"
	_ "github.com/lib/pq"
	_ "github.com/mattn/go-sqlite3"
)

var db *gorm.DB

//User ...
type User struct {
	gorm.Model
	Name    string
	Address Address `gorm:"polymorphic:Entity;"`
}

//BeforeQuery ...
func (m *User) BeforeQuery(scope *gorm.Scope) error {
	fmt.Println("Preloading Address")
	scope.DB().Model(m).Preload("Address")
	return nil
}

//Address ...
type Address struct {
	gorm.Model
	Address1   string
	EntityID   uint
	EntityType string
}

func init() {
	var err error
	// db, err = gorm.Open("sqlite3", "test.db")
	// db, err = gorm.Open("postgres", "user=username dbname=password sslmode=disable")
	db, err = gorm.Open("mysql", "root:@/testdb?charset=utf8&parseTime=True")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

func beforeQueryCallback(scope *gorm.Scope) {
	if !scope.HasError() {
		scope.CallMethod("BeforeQuery")
	}
}

func main() {
	db.DropTableIfExists(&User{}, &Address{})
	db.AutoMigrate(&User{}, &Address{})

	db.Callback().Query().Before("gorm:query").Register("ltc:before_query", beforeQueryCallback)

	user := User{
		Name: "Dan Hardman",
		Address: Address{
			Address1: "101 Street Name",
		},
	}

	if err := db.Create(&user).Error; err != nil {
		panic(err)
	}

	var queryUser User
	if err := db.First(&queryUser, 1).Error; err != nil {
		panic(err)
	}

	//Should have address populated
	fmt.Printf("%+v\n", queryUser)
}
```

**Comment by jinzhu** [comment]
@danhardman yes, write the BeforeQuery method like:

```go
func (m *User) BeforeQuery(scope *gorm.Scope) error {
	fmt.Println("Preloading Address")
	scope.Search.Preload("Address")
	return nil
}
```

**Comment by danhardman** [comment]
Absolutely brilliant. Perfect for models with lots of relationships. I've been running into issues where I've forgotten to preload relationships in some queries (unable to reuse). This solves this perfectly!

**Comment by danhardman** [comment]
@jinzhu I've found this doesn't work when calling `db.Find()`, but it does work on `db.First()`.

**Comment by danhardman** [comment]
@jinzhu Fixed this by updating:

```go
db.Callback().Query().Before("gorm:query").Register("ltc:before_query", beforeQueryCallback)
```

To:

```go
db.Callback().Query().After("gorm:query").Register("ltc:chain_query", chainQueryCallback)
```

I found that the `AfterFind` doesn't work for this use case, it specifically has to be `After("gorm:query")`

**Comment by jugglinmike** [comment]
`Scope.Search` is only mentioned once in the project's API documentation. Is it considered a public API?

**Comment by danhardman** [comment]
@jugglinmike It could definitely do with being better described in the Write Plugins section of the documentation.
