### ISSUE TITLE
how to get last_insert_id  

### ISSUE THREAD

**Issue by webluoye** [jinzhu/gorm#1160]
type BusStatusTable struct {
	B_id          int32  `gorm:primary_key;column:b_id`
	B_class       int32  `gorm:column:b_class`
}

bsTable := BusStatusTable{}
bsTable.B_class = 1
bsTable.B_class_small = 2
err := DB.Table("business_status").Save(&bsTable).Error
if err == nil {
	fmt.Printf("%+v", bsTable)
}

{B_id:0 B_class:1 B_class_small:2}

bsTable.B_ID return 0  how to get last insert id

**Comment by danhardman** [comment]
I think you want to be using the `db.Create(value)` method instead of `db.Save(value)`.

**Comment by webluoye** [comment]
use err := DB.Table("business_status").Create(&bsTable).Error

same as  Save(&bsTable)  ,return 0

**Comment by danhardman** [comment]
Have you created a `business_status` table? I think you either should be using `bus_status_table`, or simply do: `err := DB.Create(&bsTable).Error` and use default table names.

**Comment by webluoye** [comment]
yes,have this table  business_status ,and create is successful
err := DB.Create(&bsTable).Error == nil

mysql> show tables;
+---------------------------+
| Tables_in_ename_analytics |
+---------------------------+
| business_status           |

mysql> select count(*) from business_status;
+----------+
| count(*) |
+----------+
|       13 |
+----------+
1 row in set (0.00 sec)

**Comment by webluoye** [comment]
sql statement
[2016-08-17 17:51:44]  [3.58ms]  INSERT INTO `business_status` (`b_id`,`b_class`,`b_class_small`) VALUES ('0','1','2')

**Comment by danhardman** [comment]
It'd be easier if you created the table through **Gorm** and used `DB.AutoMigrate()`.

Is the `b_id` column set to auto increment?

**Comment by webluoye** [comment]
I am not sure how to use AutoMigrate is seem not work

**Comment by webluoye** [comment]
problem resolved

type BusStatusTable struct {
	ID            int32  `gorm:primary_key;column:b_id`
	B_class       int32  `gorm:column:b_class`
}

then call err := DB.Create(&bsTable).Error 
bsTable.ID  return last insert id

**Comment by webluoye** [comment]
but I found another bug for .Last() function
DB.Table("business_status").Where("B_class = ?", class).Last(&bsTable).Error

sql statement
SELECT * FROM `business_status`  WHERE (B_class = '1') ORDER BY `business_status`.`id` DESC LIMIT 1

is seem "gorm:primary_key;column:b_id"   not work

**Comment by jinzhu** [comment]
Hi @webluoye 

Please open another issue and following this guide https://github.com/jinzhu/gorm/blob/master/CONTRIBUTING.md

**Comment by pennkao** [comment]
please write it into doc
