### ISSUE TITLE
Disable special orm fields

### ISSUE THREAD

**Issue by genofire** [jinzhu/gorm#1163]
It would be cool, if gorm would not change the schema with adding and using:
- CreatedAt
- UpdatedAt
- DeletedAt <- and switch to hard deleting

(A option to change the fieldname, would be also okay)
Example: user.UpdatedAt -> user.lastloginat

**Comment by zardak** [comment]
You can disable existing behaviour by removing corresponding callbacks.
However, things are a bit complicated with soft-delete.
```
// Will not set CreatedAt and UpdatedAt on .Create() call
db.Callback().Create().Remove("gorm:update_time_stamp")

// Will not update UpdatedAt on .Save() call
db.Callback().Update().Remove("gorm:update_time_stamp")
```

Likewise, add custom behaviour by registering your own callbacks http://jinzhu.me/gorm/development.html#write-plugins

**Comment by genofire** [comment]
Hi, thanks for the fast answer.
Whats happen during migrate? Whould the fields are created?

**Comment by zardak** [comment]
No fields are created by default. Those fields are defined in `gorm.Model`.
https://github.com/jinzhu/gorm/blob/master/model.go
So, don't embedd it into your model structs.

This will create `Id`, `CreatedAt`, `UpdatedAt`, `DeletedAt` and `Username` fields:
```
type User struct {
    gorm.Model // Note the embedding
    Username string
}
```

And this will only create `Id` and `Username`:
```
type User struct {
  Id uint
  Username string
}
```

**Comment by genofire** [comment]
Okay, Delete works with: `dbUnscoped().Delete(*ModelObj)` so i am happy :)

Maybe some doku for it?

**Comment by zardak** [comment]
All parts of the solution are already documented, albeit not in single place.
IMO this belongs to some sort of `Recipes` wiki page.

**Comment by genofire** [comment]
Thats what i mean.
(Or i would close this issue now)
