### ISSUE TITLE
primaryField not being in the SELECT to read back the record after an INSERT

### ISSUE THREAD

**Issue by fobispo-link** [jinzhu/gorm#1166]
I sent this via a private email, but thought it would be better to document here:

While creating a record I noticed that the WHERE condition in the forceReloadAfterCreateCallback() was not being added.

It turns out that the primary key (coming from Postgres on the ‘RETURNING id’ suffix), was being correctly read into the primaryField but is not setting the field.IsBlank to false.

To fix just need to:

in: callback_create.go

was:

120            if err := scope.SQLDB().QueryRow(scope.SQL, scope.SQLVars...).Scan(primaryField.Field.Addr().Interface()); scope.Err(err) == nil {
121                scope.db.RowsAffected = 1
122            }

needs to be:

120            if err := scope.SQLDB().QueryRow(scope.SQL, scope.SQLVars...).Scan(primaryField.Field.Addr().Interface()); scope.Err(err) == nil {
121                scope.db.RowsAffected = 1
122                primaryField.IsBlank = false
123            }

The bug causes the table where the insert is happening to be fully read/scanned on each INSERT which is less than optimal.

**Comment by fobispo-link** [comment]
```
diff --git a/callback_create.go b/callback_create.go
index 14b8204..2308e1f 100644
--- a/callback_create.go
+++ b/callback_create.go
@@ -119,6 +119,7 @@ func createCallback(scope *Scope) {
                } else {
                        if err := scope.SQLDB().QueryRow(scope.SQL, scope.SQLVars...).Scan(primaryField.Field.Addr().Interface()); scope.Err(err) == nil {
                                scope.db.RowsAffected = 1
+                               primaryField.IsBlank = false
                        }
                }
        }
```

**Comment by jinzhu** [comment]
Thank you for your report, and solution, just fixed that. https://github.com/jinzhu/gorm/commit/3425c1d38d18375cc3e27d0c3a8c0e7907eb1b3e
