### ISSUE TITLE
How would I scan results into a map[string]string/interface{}

### ISSUE THREAD

**Issue by danhardman** [jinzhu/gorm#1167]
I want to create an options/settings table that's a simple Key/Value table to make it easier to add/remove options rather than having to update the table structure each time.

Can I simply do:

Options Table:
```
| key      | value  |
|----------|--------|
| sitename | google |
```

```go
results := make(map[string]string)
if err := db.Table("options")...Scan(&results).Error; err != nil {
 panic(err)
}
```

Or do I need to iterate over `Rows()` and manually populate a map?

**Comment by Raggaer** [comment]
So what is the answer? Did you figure? I am also interested

**Comment by pedromorgan** [comment]
You need to iterate over rows to populate map

**Comment by danhardman** [comment]
Yep, just iterated over `Rows()`. I decided not to embed `gorm.Model` onto the struct and just set the `key` field as the primary key

**Comment by tedli** [comment]
@Raggaer @ecast040 
Hi,

```golang

# so the table could be a variable
rows, err := driver.Query(fmt.Sprintf("select * from %s", table))
if err != nil {
	panic(err)
}
columns, err := rows.Columns()
if err != nil {
	panic(err)
}
length := len(columns)
result := make([]map[string]interface{}, 0)
for rows.Next() {
	current := makeResultReceiver(length)
	if err := rows.Scan(current...); err != nil {
		panic(err)
	}
	value := make(map[string]interface{})
	for i := 0; i < length; i++ {
		k := columns[i]
		v := current[i]
		value[k] = v
	}
	result = append(result, value)
}

func makeResultReceiver(length int) []interface{} {
	result := make([]interface{}, 0, length)
	for i := 0; i < length; i++ {
		var current interface{}
		current = struct{}{}
		result = append(result, &current)
	}
	return result
}

```

This worked, hope helps.

**Comment by Turing-Chu** [comment]
@tedli then how to convert this pointer to string or other type? it always tell me the following error:

```
panic: interface conversion: interface {} is *interface {}, not *string

```

**Comment by tedli** [comment]
> @tedli then how to convert this pointer to string or other type? it always tell me the following error:
> 
> ```
> panic: interface conversion: interface {} is *interface {}, not *string
> ```

I didn't play with the code to confirm, but I think you can try with

```golang
v := value.(*interface{})
s := v.(*string) // maybe v.(string)
```

to see if there is any luck.

**Comment by Turing-Chu** [comment]
@

> > @tedli then how to convert this pointer to string or other type? it always tell me the following error:
> > ```
> > panic: interface conversion: interface {} is *interface {}, not *string
> > ```
> 
> I didn't play with the code to confirm, but I think you can try with
> 
> ```go
> v := value.(*interface{})
> s := v.(*string) // maybe v.(string)
> ```
> 
> to see if there is any luck.

I have resolved this problem by myself, thank you for your code:

```go
	for rows.Next() {
		current := makeResultReceiver(length)
		if err := rows.Scan(current...); err != nil {
			panic(err)
		}
		value := make(map[string]interface{})
		for i := 0; i < length; i++ {
			key := columns[i]
			v := *(current[i]).(*interface{})
			vType := reflect.TypeOf(v)
			switch vType.Name() {
			case "int64":
				value[key] = v.(int64)
			case "string":
				value[key] = v.(string)
			case "Time":
				value[key] = v.(time.Time)
			default:
				// TODO remember add other data type
				value[key] = v.(string)
			}
		}
	}

```

**Comment by tedli** [comment]
@Turing-Chu

golang has a builtin switch/case for type at language level. Using reflect package is OK, but comes with little downside that,
1. you need to import the reflect package,
2. your cases based on string that the compiler won't give you any help, this will be error prone if you type is not a basic type (I mean something like `"daas/rabbitmq.(*RabbitmqClusterController)"`).

So by using native golang type switch/case, code looks like this:

```golang
func lalala(v interface{}) {
	switch v.(type) {
	case int:
		// do something with int
	case string:
		// do something with string
	case *net.IP:
		// do something with complicated types
	}
}
```

**Comment by Turing-Chu** [comment]
@tedli  very perfect!!! It's better than reflect.TypeOf using golang builtin switch&case of type

**Comment by iesreza** [comment]
> @Raggaer @ecast040
> Hi,
> 
> ```go
> // so the table could be a variable
> rows, err := driver.Query(fmt.Sprintf("select * from %s", table))
> 
> // the driver above, is the return value of sql.Open, the golang original sql package
> 
> if err != nil {
> 	panic(err)
> }
> columns, err := rows.Columns()
> if err != nil {
> 	panic(err)
> }
> length := len(columns)
> result := make([]map[string]interface{}, 0)
> for rows.Next() {
> 	current := makeResultReceiver(length)
> 	if err := rows.Scan(current...); err != nil {
> 		panic(err)
> 	}
> 	value := make(map[string]interface{})
> 	for i := 0; i < length; i++ {
> 		k := columns[i]
> 		v := current[i]
> 		value[k] = v
> 	}
> 	result = append(result, value)
> }
> 
> // then the result is what you want, keep in mind that the value of the map is always pointer, since the value may be sql null
> 
> func makeResultReceiver(length int) []interface{} {
> 	result := make([]interface{}, 0, length)
> 	for i := 0; i < length; i++ {
> 		var current interface{}
> 		current = struct{}{}
> 		result = append(result, &current)
> 	}
> 	return result
> }
> ```
> 
> This worked, hope helps.

Due problem with pointers i replaced:
```go
v := current[i]
```
to
```go
v := reflect.ValueOf(current[i]).Elem().Interface()
```
This return direct access to value.
