### ISSUE TITLE
Create Unique constraint for column

### ISSUE THREAD

**Issue by Niondir** [jinzhu/gorm#1169]
Hi,
I can declare my column as `gorm:"unique"` and the unique constraint is created during auto migrate. But when I add the qunique constraint later it is not added and I can not find any function to simply do it my self. With the unique_index everything works as expected.

Any thoughts about this? Probably I go with unique indexes for now ;)

**Comment by ruslanfedoseenko** [comment]
As sayed here 
http://jinzhu.me/gorm/database.html#migration

> AutoMigrate will ONLY create tables, missing columns and missing indexes, and **WON'T change existing column's type or delete unused columns to protect your data**.

Any way you can create unique index like this `db.Model(&User{}).AddUniqueIndex("idx_user_name", "name")`

**Comment by Niondir** [comment]
But a unique index is a unique constraint + index. I do not see how adding just a unique constraint could damage my data? 

Sure, the creation of the constraint could fail, but then AddUniqueIndex would also fail.

If you don't want the automigration to add the unique constraint, than we should at least add a method like `db.Model(&User{}).AddUniqueConstraint("key_user_name", "name")` - now the only way is to write the SQL my self.

**Comment by jinzhu** [comment]
```go
db.Model(&User{}).AddUniqueIndex("idx_user_name", "name")
```

**Comment by Niondir** [comment]
`AddUniqueIndex` does add an Index, not only a constraint. That's a different thing :)

**Comment by xmh19936688** [comment]
> `AddUniqueIndex` does add an Index, not only a constraint. That's a different thing :)

Yeah. I think we need [this feature](http://www.w3school.com.cn/sql/sql_unique.asp)
