### ISSUE TITLE
Undefined columns in the model struct were also updated by create/update operations.

### ISSUE THREAD

**Issue by yafngzh** [jinzhu/gorm#1170]
My model is like this:
type Order struct {
    OrderId      string `gorm:"primary_key;column:orderId"`
    StockCode    string `gorm:"column:stockCode"`
    Type         string `gorm:"column:type"`
    PriceE2      int64  `gorm:"column:priceE2"`
    PriceDate    string `gorm:"column:priceDate"`
    Amount       int 
    State        int 
    RemainAmount int `gorm:"column:remainAmount"`
}

the table defined like this:

CREATE TABLE `user_order` (
  `orderId` varchar(64) NOT NULL DEFAULT '',
  `stockCode` varchar(32) NOT NULL DEFAULT '' COMMENT '产品编码',
  `type` varchar(32) DEFAULT NULL,
  `amount` int(11) DEFAULT NULL,
  `remainAmount` int(11) DEFAULT NULL,
  `priceE2` bigint(20) DEFAULT NULL COMMENT '产品价格',
  `priceDate` varchar(32) DEFAULT NULL COMMENT '该价格对应的日期',
  `created_at` varchar(32) DEFAULT NULL,
  `updated_at` varchar(32) DEFAULT NULL,
  `deleted_at` varchar(32) DEFAULT NULL,
  `state` int(11) DEFAULT '0' COMMENT '',
  `lastModTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`orderId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 

The result after creation of one row is this:
*************************** 48. row ***************************
     orderId: edf03454-67ac-11e6-a99a-000c291f2af4
   stockCode: WSCN
        type: sell
      amount: 1000
remainAmount: 1000
     priceE2: 10000
   priceDate: 
  created_at: NULL
  updated_at: NULL
  deleted_at: NULL
       state: 0
 lastModTime: 0000-00-00 00:00:00

**The lastModTime was 0000-00-00 00:00:00, not the 'CURRENT_TIMESTAMP'.** 
So I guess all the columns have default values, how can I exclude lastModTime from this?

**Comment by jinzhu** [comment]
doesn't saw the `lastModTime` field in your model struct definition?

**Comment by yafngzh** [comment]
@jinzhu  as you said, the lastModTime field was not in my model struct, so it should not be set as '0000-00-00 00:00:00'. In contrast, it should be updated by mysql.

**Comment by jinzhu** [comment]
@yafngzh could you create another issue include runnable script to explain your issue? seems I don't really get it.
