### ISSUE TITLE
How insert time type value with gorm

### ISSUE THREAD

**Issue by chen-tam** [jinzhu/gorm#1172]
```
type JSONTime time.Time

type User struct{
     Birthday  JSONTime `json:"birthday"`
}
```
account := User{Birthday: JSONTime(time.Now())}
db.NewRecord(account)
db.Create(&account)

It does not work

**Comment by danhardman** [comment]
See issue #47

You need to implement a scanner interface for `JSONTime`, https://golang.org/pkg/database/sql/#Scanner

**Comment by chen-tam** [comment]
thanks very much
