### ISSUE TITLE
How to update a struct's blank fields by db.Where(...).Update(&obj)?

### ISSUE THREAD

**Issue by liaoliaopro** [jinzhu/gorm#1173]
> // WARNING when update with struct, GORM will only update those fields that with non blank value
> // For below Update, nothing will be updated as "", 0, false are blank values of their types
> db.Model(&user).Updates(User{Name: "", Age: 0, Actived: false})

踩在这个坑里了。如果db中原来的数据是是User{Name:"blabla", Age: 28, Actived:true}，我现在要将其Actived字段更为false，应该如何处理？ 这是很常见的场景。go语言中的blank feild不能当做NULL处理，Age=0, Actived=false是可能有业务意义的。

db.Save不能满足需求，因为其只能根据primary id匹配来更新。我需要db.Where(...).Update()，根据Where条件过滤后在更新。可否考虑增加一个flag来标记是全部更新或只更新non blank fields.

不知是我理解不对还是有正确的做法可以做到这一点，盼复，感谢。

**Comment by liaoliaopro** [comment]
```
// force update indicated columns by Cols
affected, err := engine.Id(1).Cols("age").Update(&User{Name:name, Age: 12})
// UPDATE user SET age = ?, updated=? Where id = ?

affected, err := engine.Id(1).AllCols().Update(&user)
// UPDATE user SET name=?,age=?,salt=?,passwd=?,updated=? Where id = ?
```

可否考虑实现xorm中的Cols/AllCols接口？ AllCols完美的解决我的需求场景。

**Comment by mikunalpha** [comment]
My solution is to use ptr of bool or integer when I need to assign a zero value.
```Go
Active *bool
```

**Comment by jinzhu** [comment]
![Uploading image.png…]()

**Comment by jinzhu** [comment]
或者可以用 Save, 你可以保存所有的值.

db.Save(&user)

**Comment by aetherwu** [comment]
> 或者可以用 Save, 你可以保存所有的值.
> 
> db.Save(&user)

Save 的话似乎意味着需要先 query 一次，而无法按照 Where 直接 Update. 这样是不是效率不够高？（而且意味着需要拼接一些内容 a.X = b.X 这样。）

所以请问现在版本（201911）中，支持强制在 Update 中重写所有或者指定的 empty/default 字段吗？
