### ISSUE TITLE
DropTable fails when tables are passed by in arbitrary order

### ISSUE THREAD

**Issue by dylanninin** [jinzhu/gorm#1174]
Reviewing the code, gorm's `DropTable` is implemented  with plain  `for range`, there's no topological-sort like algorithms to determine which tables should be dropped first, and then the other tables.  Error occurs when tables are being dropped in arbitrary order.

Example follows here. 

underlying dialect: postgresql, 9.5+

model definition

``` go

package models

type Account struct {
    ID        int64     `json:"id" gorm:"primary_key"`
    Username      string `json:"tel" gorm:"not null; unique;"`
    Password string `json:"-" gorm:"not null;"`

    Profile Profile `json:"profile"`
}

type Profile struct {
    ID        int64     `json:"id" gorm:"primary_key"`
    Name     string  `json:"name" gorm:"not null;"`
    Gender   int     `json:"gender" gorm:"not null;"`

    // TODO SQL: Should add foreign key when create table
    // Reference https://github.com/jinzhu/gorm/issues/450
    AccountId int `json:"account_id" gorm:"not null; unique; index"`
}
```

when `InitSchema`, I have to manually add foreign key for this unsolved issue https://github.com/jinzhu/gorm/issues/450

``` go
func (db *DB) InitSchema() {
    db.AutoMigrate(&Account{}, &Profile{})

    // FIXME Manually add foreign key
    db.Model(&Profile{}).AddForeignKey("account_id", "accounts(id)", "restrict", "restrict")
}
```

when `DropSchema`,  you must specify the order of input models, or you'll get error.

``` go
func (db *DB) DropSchema() {
    // FIXME The order of input tables matters, for they may have foreign key constraints.
    // If they're populated with data, they must be dropped in specified orders:
    // - tables with no extra dependencies are dropped first
    // - then the dependent tables
    // db.DropTableIfExists(&Account{}, &Profile{}) // error occurs for table `accounts` cannot be dropped before `profiles`, there are some rows referencing `accounts(id)`
    db.DropTableIfExists(&Profile{}, &Account{})
}
```

If you do `db.DropTableIfExists(&Account{}, &Profile{})`,  error occurs for there are some rows referencing `accounts(id)`, and `accounts` can not be dropped before `profiles`.

Just a week ago, we're hit by another similar issue in SQLAlchemy, and here's related resources http://bit.ly/2bZMqMd.

I'll try submit a PR in few days, hope to solve this issue.

**Comment by jinzhu** [comment]
I remember there is a mode could skip the check, maybe should turn that mode on before delete those tables?
