### ISSUE TITLE
[bug] Index key name too long!

### ISSUE THREAD

**Issue by benguild** [jinzhu/gorm#1177]
Similar to #882, a formula is missing for index keys being too long and during `AutoMigrate()` it can appear if the table name is long. — MySQL Error # 1059

**Comment by natsukagami** [comment]
Can reproduce on latest with mysql dialect.

**Comment by natsukagami** [comment]
Can reproduce on latest.

**Comment by jinzhu** [comment]
Should be fixed, thank you for your report.
