### ISSUE TITLE
能否支持upsert？？

### ISSUE THREAD

**Issue by wencan** [jinzhu/gorm#1179]
mongodb创造了upsert，即：
如果_id存在，更新
否则，插入

从我的测试结果来看，
save仅限于，更新一个first后修改的对象

**Comment by cch123** [comment]
mysql里不是也有replace么。。

**Comment by jinzhu** [comment]
Save 没有 id的话会创建的

**Comment by mcandre** [comment]
Could we please add a note in the documentation for the `Save()` method to include the keyword "UPSERT"? That word is how people will be searching for this feature.
