### ISSUE TITLE
Support Postgres jsonb columns

### ISSUE THREAD

**Issue by Niondir** [jinzhu/gorm#1183]
Hi I'm interested in parsing jsonb columns from postgres. currently I do the following:

```
type MyData struct {
    Model
    JsonData    string `gorm:"type:jsonb;not null"`
}
```

But serializing the struct again would lead to an escaped json string in the JsonData field. I would prefer something like this:

```
type MyData struct {
    Model
    JsonData    interface{} `gorm:"type:jsonb;not null"`
}
```

Where the data gets automatically parsed on query.

I'm not familiar with the callbacks. Is there a way I could add the type conversion my self? Any hint's would be helpful.

**Comment by danhardman** [comment]
Would it be more suitable for `MyData.JsonData` to be of type [json.RawMessage](https://golang.org/pkg/encoding/json/#RawMessage)? I think you'd have to implement the [sql.Scanner](https://golang.org/pkg/database/sql/#Scanner) interface but I think it'd be worth it.

**Comment by Niondir** [comment]
yes json.RawMessage might be the right way. When I implement sqlScanner on a custom type that embeds json.RawMessage it just works? I will try it.

**Comment by danhardman** [comment]
@Niondir Hmm good point... Is it possible to do:

```go
func (json *json.RawMessage) Value() (driver.Value, error) {
 //code
}
```

**Comment by Niondir** [comment]
This seems to work <3

```
type PostgresJson struct {
	json.RawMessage
}

func (j PostgresJson) Value() (driver.Value, error) {
	return j.MarshalJSON()
}

func (j *PostgresJson) Scan(src interface{}) error {
	if bytes, ok := src.([]byte); ok {
		return json.Unmarshal(bytes, j)

	}
	return errors.New(fmt.Sprint("Failed to unmarshal JSON from DB", src))
}
```

Maybe add this to the pg driver?

**Comment by antonypp** [comment]
@Niondir Yes, it`s cool feature.

**Comment by MaerF0x0** [comment]
@jinzhu  would you accept a PR for @Niondir 's method? If so I can prep it.

**Comment by jinzhu** [comment]
@MaerF0x0 yes, would accept it if put it into there. https://github.com/jinzhu/gorm/blob/master/dialects/postgres/postgres.go

**Comment by Depado** [comment]
Hello 👋 
Now that this has been merged, is there any way you could show me an example on how to use this ? 👍 

Thanks a lot

**Comment by Aetheus** [comment]
Not sure if you still need this given that it's been a few months, @Depado , but for all the other folks who are curious:

Assuming you have a "documents" table, and in that documents you have a "metadata" jsonb column, your resulting model struct definition may look something like this:

````
package yourPackageName

import (
	"time"
	"github.com/jinzhu/gorm/dialects/postgres"
)

type Document struct {
	Metadata postgres.Jsonb		`json:"requirements"`
	Body string				        `json:"body"`

	//housekeeping attributes
	ID        int					        `json:"id"`
	CreatedAt time.Time			`json:"created_at"`
	UpdatedAt time.Time			`json:"updated_at"`
}

````

Assuming you wanted to access the value of "Metadata" in a specific "Document" as a string ... 

````
func GetMetadataOfDocument(dbConn *gorm.DB, documentId int) string {
    doc := Document{}
    dbConn.Where("id = ?", documentId).First(&doc)

    stringVal := string(doc.Metadata.RawMessage)
    return stringVal;
}
````

**Comment by Depado** [comment]
@Aetheus thanks a lot !
I managed to get it to work on my own but that's a great example for the documentation 👍

**Comment by buildscientist** [comment]
@Aetheus thanks for the code snippet. I've pulled gorm from master and when I run your example code I end up with a metadata field that's typed to a byteA instead of jsonB. 

I'm running the following: 

- PostgreSQL v9.6.6 in a Docker container - (postgres:9.6-alpine)
- Go v1.9.3
- latest from gorm (master)

```go 
sampleDoc := Document{}
sampleDoc.Body = "buildscientist"

dbHandle.CreateTable(Document{})
dbHandle.Create(&sampleDoc)

doc := Document{}
dbHandle.Where("id = ?", 1).First(&doc)
stringVal := string(doc.Metadata.RawMessage) //this is set to null
```

Stepping through gorm scope.createTable() executes a raw SQL statement of the following: 

```sql
CREATE TABLE "documents" ("metadata" bytea,"body" text,"id" serial,"created_at" timestamp with time zone,"updated_at" timestamp with time zone , PRIMARY KEY ("id")) 
```

**Comment by buildscientist** [comment]
@Aetheus 

I think I figured out what the issue is - have a look at: 

[Line 68](https://github.com/jinzhu/gorm/blob/master/dialect_postgres.go#L68) of dialect_postgres.DateTypeOf()

Looks like jsonB isn't a case in that switch statement so it's automatically defaulting to byteA.

**Comment by Aetheus** [comment]
@buildscientist - actually, I think that your original suggestion was a good one. In fact, ````dialect_postgres.go```` already has a check in the ````DataTypeOf```` method for the "Hstore" type (which is also defined in ````dialects/postgres.go````), so there is precedence for expecting the provided "loader" structs to actually be able to be used for other purposes. 

Thanks for bringing it up! I haven't been using gorm for database migrations, so the thought of how the "loader" types would interact with it never crossed my mind.  I'm not sure if I should open another issue for it, but I'll do a PR regardless and see where it goes from there.

**Comment by genieplus** [comment]
I still think the original suggestion is a very good one.
I would prefer that `gorm` automatically marshal/unmarshal struct field tagged as `type:jsonb`.
I am ready to dig into this if it is possible from design/architecture point.

**Comment by buildscientist** [comment]
+1 for this feature but this would be specific to PgSQL right? Unless you maintain a map of other DB vendors JSONB (or JSON) types.

**Comment by roychowdhuryrohit-dev** [comment]
`CourseInfoB []postgres.Jsonb `gorm:"type:jsonb[]"``

Is this possible in gorm ?

**Comment by ilzheev** [comment]
> I still think the original suggestion is a very good one.
> I would prefer that `gorm` automatically marshal/unmarshal struct field tagged as `type:jsonb`.
> I am ready to dig into this if it is possible from design/architecture point.

Any updates on this?

**Comment by willolisp** [comment]
+1 for the original suggestion.
I like the idea of leaving the model as agnostic as possible to the underlying db impl.
It'd be nice if we could model all db specificities as tags that gorm could interpret, but leave field types as being as db-agnostic as possible, just so business layers wouldn't need to be aware of any db details when manipulating the model.
