### ISSUE TITLE
documentation does not contain field options and how write them 

### ISSUE THREAD

**Issue by hishamwaleed** [jinzhu/gorm#1184]
documentation does not contain field options and how write them  i.e 

```
type User struct {
    ....
    IsAdmin   bool `sql:"DEFAULT:0"`
    .....
}
```

like `sql:"DEFAULT:0"` is there a dictionary or mapping for these options or any doc page

**Comment by hishamwaleed** [comment]
@jinzhu

**Comment by alapini** [comment]
@jinzhu

**Comment by jinzhu** [comment]
Please only use those documented tags in http://jinzhu.me/gorm
