### ISSUE TITLE
How to insert or update

### ISSUE THREAD

**Issue by wencan** [jinzhu/gorm#1188]
How to execute insert when primary key does not exist, or execute update when primary key exists？？

like upsert on mongodb

**Comment by danhardman** [comment]
```go
if db.NewRecord(value) {
...
} else {
...
}
```

**Comment by jrletosa** [comment]
This does not work. If you need to do that you need to do https://github.com/jinzhu/gorm/issues/1044

**Comment by jinzhu** [comment]
use `Assign` with `FirstOrCreate`

**Comment by myles-mcdonnell** [comment]
It's not clear to me how to use `Assign` with `FirstOrCreate`..is there an example somewhere? And is this operation atomic?

**Comment by LucasDove** [comment]
// Unfound
db.Where(User{Name: "non_existing"}).Assign(User{Age: 20}).FirstOrCreate(&user)
//// SELECT * FROM users WHERE name = 'non_existing';
//// INSERT INTO "users" (name, age) VALUES ("non_existing", 20);
//// user -> User{Id: 112, Name: "non_existing", Age: 20}

// Found
db.Where(User{Name: "jinzhu"}).Assign(User{Age: 30}).FirstOrCreate(&user)
//// SELECT * FROM users WHERE name = 'jinzhu';
//// UPDATE users SET age=30 WHERE id = 111;
//// user -> User{Id: 111, Name: "jinzhu", Age: 30}

the Assign and FirstOrCreate  examples are as above, it seems that this operation is not atomic?

**Comment by Djolivald** [comment]
It does not seem like this issue should be closed. Any plan for upsert support?

**Comment by ecbaldwin** [comment]
Please reopen this issue. The proposed solution is not acceptable.

The comment above by @LucasDove shows that Assign with FirstOrCreate executes two independent SQL commands. When run inside of a transaction, these should be run atomically. However, even if that is the case, the decision whether to insert or update is done on the client side which adds latency to the transaction. In an upsert, the decision whether to insert a new record or update as existing one is done on the server side.

Please support upsert directly.
