### ISSUE TITLE
Many to many table with self referencing field

### ISSUE THREAD

**Issue by iyedg** [jinzhu/gorm#1194]
I have this model that represents a course, which might have many courses as prerequisites and be a prerequisite of many courses

```
type Course struct {
    gorm.Model
    Name          string
    Prerequisites []Course `gorm:"many2many:course_prerequisite"`
}
```

this code raises an error

`duplicate column name: course_id`

the logger shows that the generated SQL is as follows:

`CREATE TABLE "course_prerequisite" ("course_id" integer,"course_id" integer, PRIMARY KEY ("course_id","course_id"))`

Is there a way to rename one of the columns or any other way around this error ?

**Comment by danhardman** [comment]
Seems like a very bad data structure. Obviously I'm not sure on the contract, but could `Prerequisites` be a different type? For example, `Qualification` instead of `Course`?

**Comment by iyedg** [comment]
I figured it is bad data structure, but I could not come up with a logical way to model this relationship. It is a tree where all the nodes have the same type, therefore `Prerequisites` must be of type `Course`

**Comment by rajan61005co** [comment]
Its definitely not a bad data structure. In database you can reference own table as many to many relationship. I am pretty surprised that this library does not address critical like this. This should have been escalated and fixed long time back. Similar issue has made me stuck as well and I definitely don't want to fix this in hacky way.

**Comment by alapini** [comment]
@jinzhu

**Comment by Arman92** [comment]
Any fix to this issue? I definitely need many to many with self entity!
I tried this [http://stackoverflow.com/a/28189798/1420189](url) but does not work

**Comment by nathan-osman** [comment]
Good news - I think I have found a way to fix this without breaking anything else. Please see the pull request immediately above this comment.

**Comment by jinzhu** [comment]
Hi All,

Thanks @nathan-osman 's works, we have this feature now, please refer http://gorm.io/associations.html#self-referencing-many-to-many-relationship for usage.

**Comment by nekketsuuu** [comment]
New URL: http://gorm.io/docs/many_to_many.html#Self-Referencing

**Comment by brunoro** [comment]
Is there any easy way to make symmetrical self-referencing associations? I have a `Post` model that could have many references to other duplicate `Post` entries, using a `post_duplicates` table with two columns, `post_a` and `post_b`.
For now I'm manually adding rows for each post added, so if post X and post Y are duplicates, there'll be two entries in `post_duplicates`: [(X, Y), (Y, X)], and those have to be managed at every insert/delete/update. Can GORM handle it in such a way that the many-to-many relationships will query for rows where `post_a = post.id OR post_b = post.id`?

**Comment by pcc1650** [comment]
Do we support adding extra field in the join table for a many to many self reference relationship?
