### ISSUE TITLE
gorm update all records when I has set the primary key value

### ISSUE THREAD

**Issue by llhhbc** [jinzhu/gorm#1195]
My table has three primary_keys, they are int, varchar, varchar type.

When I select by those primary_keys in value (0, "a", "b") , no problems.
and then I update , all records are updates.

The code is :
`err =tx.Set("gorm:query_option", "FOR UPDATE").`
`Where(" level = ? and key  = ? and  id = ? ", 0,`
`"a", "b").Find(&pa).Error`
`pa.Value= "1"`
`err = tx.Model(&pa).Update("value", pa.Value).Error`

I have fixed this problem by not use level = 0, start with 1.  
I think is a problem that level can't be set to 0.

**Comment by jinzhu** [comment]
http://jinzhu.me/gorm/crud.html#delete

When primary key is blank value, it will be ignored
