### ISSUE TITLE
Batch update

### ISSUE THREAD

**Issue by Raggaer** [jinzhu/gorm#1196]
I am trying to make a batch update. here is how the code looks like

```
items := []models.Item{}
if err := json.Unmarshal([]byte(r.Params.Get("inventory")), &items); err != nil {
	revel.ERROR.Println("Error while unmarshaling inventory", err)
}
if err := app.DB.Table("items").Updates(&items).Error; err != nil {
	revel.ERROR.Println("Error while saving inventory priority", err)
}
```

items is correctly populated. and Im not getting any error from the query however no field is beeing updated expect for updated_at. Is there any way I can see what query is gorm trying to execute or why is no field changing (there is one field that should changing)

I also tried with no success

if err := app.DB.Model(models.Item{}).Updates(&items).Error; err != nil {
	revel.ERROR.Println("Error while saving inventory priority", err)
}

**Comment by danhardman** [comment]
```go
if err := app.DB.Debug().Table("items").Updates(&items).Error; err != nil {
    revel.ERROR.Println("Error while saving inventory priority", err)
}
```

Note the `Debug()` function added to the chain. This will print out all SQL queries to the console

**Comment by Raggaer** [comment]
Turned out I was missing some struct fields. Thanks for the debug tip.
