### ISSUE TITLE
[Bug] Schemas PostgreSQL

### ISSUE THREAD

**Issue by pcariel** [jinzhu/gorm#1197]
Hi, Friends.

``` go
type User struct {
  ID uint
  gorm.model
}
func (User) TableName() string {
  return "audit.users"
}
```

the model runs completely without schemas.

migration run for the first time, it works.
migration run for the second time, error: Table pq users exists, every time I run "Migrate".

Thank you.

**Comment by danhardman** [comment]
Show your migration code

**Comment by PabloCariel** [comment]
```go
db.LogMode(true)
db.AutoMigrate(&User{})
```
When I run the migration without schema, it works. when the table exists does not create, but shows nothing in log.

When the migration Schema runs, when the table does not exist creates, when there always shows "pq Table users exists" and shows SQL Insert

**Comment by PabloCariel** [comment]
@danhardman 
Go 1.7
PostgreSQL 9.5
Database: gorm, Schema: asd

file: dialect_postgres.go in HasTable, does not validate schemes.
SQL, with schema: ```sql 
SELECT count(*) FROM INFORMATION_SCHEMA.tables WHERE table_name = 'usuarios' AND table_type = 'BASE TABLE' ```  == 2
SQL dont schema: ```sql SELECT count(*) FROM INFORMATION_SCHEMA.tables WHERE table_name = 'asd.usuarios' AND table_type = 'BASE TABLE' ```   == 0

**Comment by danhardman** [comment]
Why are you specifying the schema? Aren't you specifying schema on connection? 

I'm sorry, I've never worked with PostgreSQL

**Comment by PabloCariel** [comment]
@danhardman 
```go
type User struct {
	ID           uint
	Name     string
}
func (User) TableName() string {
	return  "audit.users"
}

db.Exec("SET SEARCH_PATH to audit")
db.LogMode(true)
db.AutoMigrate(&User{})
```

Debug: Run
```log
CREATE TABLE "audit"."users" ("id" serial , PRIMARY KEY ("id"))
```
Debug: Run again
```log
pq: Relation «users» exists
CREATE TABLE "audit"."users" ("id" serial , PRIMARY KEY ("id"))
```

The problem is, "dialect postgres.go" where verify whether the relationship exists "HasTable".

```
SELECT count(*) FROM INFORMATION_SCHEMA.tables 
WHERE table_name ='asd.users' AND table_type = 'BASE TABLE' result == 0
```

suggestion

```
SELECT count(*) FROM INFORMATION_SCHEMA.tables 
WHERE table_name = 'users' AND table_schema = 'audit' AND table_type = 'BASE TABLE' result == 1

or

SELECT 'audit.users'::regclass

```

**Comment by Archie1978** [comment]
I was going to start migrating and saw this bug.
Is it resolved?

**Comment by jinzhu** [comment]
This should been fixed, please reopen it if still doesn't work.

**Comment by leopay** [comment]
I find this issues is still existed.

**Comment by timeloveboy** [comment]
code:

`package bixin

import (
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/lib/pq"

)

type Video struct {
	ID uint
}

server.AutoMigrate(&pq.Video{})
`
output:
[2017-09-13 11:07:25]  pq: zero-length delimited identifier at or near """"

**Comment by timeloveboy** [comment]
@jinzhu  but  is still exist.

**Comment by thanos** [comment]
I do something like

```
func  setSchema(dbconn*gorm.DB, schema string) {
	dbconn.Exec(fmt.Sprintf("CREATE  SCHEMA IF NOT EXISTS %s;", schema))
	dbconn.Exec(fmt.Sprintf("SET search_path TO %s;", schema))
}

func ScrubDownDB(dbconn*gorm.DB, schema string)  {
	dbconn.Exec(fmt.Sprintf("DROP SCHEMA IF EXISTS %s CASCADE;", dbconn.schema))
}
```

so when I test

```
func TestSubscriptionCreate(t *testing.T) {
	dbconn := DbConnection()
        setSchema(dbconn, "TestSubscriptionCreate")
	defer ScrubDownDB(dbconn, "TestSubscriptionCreate")
      // etc, etc, etc.
}
```
BUT its postgres only :(

**Comment by dmitriyminer** [comment]
Issue still exist, service works about three minutes and raise error 
`(pq: relation "alert" does not exist)`
