### ISSUE TITLE
json/jsonb build where condition = operator does not exist

### ISSUE THREAD

**Issue by smacker** [jinzhu/gorm#1200]
I have model:

```
type MyModel struct {
   myField MyJsonField `gorm:"type:json"`
   ...
} 
```

And I want to get id of such record exists in DB:

```
m := &MyModel{...}
db.Table("table_name").Select("id").Where(m).Row().Scan(&id)
```

Sadly postgres says me `operator does not exist: json =`.
Because for json/jsonb type casting is mandatory.
So instead of
`select id from table_name where my_json_field = "{...}"`
orm should generate sql
`select id from table_name where my_json_field::jsonb = "{...}"::jsonb`

But I don't see how I can extend whereBuilder to support casting https://github.com/jinzhu/gorm/blob/master/scope.go#L533 :(

**Comment by jinzhu** [comment]
I think you have to write the query with raw sql, like `Where('my_json_field::jsonb = "{...}"::jsonb')` for now, hope we could find some solution in GORM2

**Comment by huanghantao** [comment]
Can we now implement the function of this equivalent query without using the raw sql statement?

**Comment by huanghantao** [comment]
@jinzhu 
Can we now implement the function of this equivalent query without using the raw sql statement?
