### ISSUE TITLE
[BUG] Incorrect SQL generated

### ISSUE THREAD

**Issue by bonivi** [jinzhu/gorm#1204]
db.Raw("SELECT sqlite_version() AS version").First(&result) generates 
SELECT sqlite_version AS version) LIMIT 1
Note the bracket symbol after "AS version". 
Code to reproduce the bug is attached.
[err.txt](https://github.com/jinzhu/gorm/files/502339/err.txt)
`
package main

import (
	"fmt"
	"github.com/jinzhu/gorm"
	_ "github.com/mattn/go-sqlite3"
)

func main() {
	db, err := gorm.Open("sqlite3", "/tmp/sqlite2.db")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer db.Close()
	db.LogMode(true)
	type Result struct {
		Version string
	}
	var result Result
	if err = db.Raw("SELECT sqlite_version() AS version").First(&result).Error; err != nil {
		fmt.Println(err) // prints near ")": syntax error
		return
	}
	fmt.Printf(result.Version)
}
`

**Comment by danhardman** [comment]
@bonivi This is github, it's kinda happy for you to paste code in it. Don't make us download files

**Comment by jinzhu** [comment]
You should use`Scan` like `db.Raw("SELECT sqlite_version() AS version").Scan(&result)`
