### ISSUE TITLE
mssql: Invalid usage of the option NEXT in the FETCH statement

### ISSUE THREAD

**Issue by dipbhi** [jinzhu/gorm#1205]
When executing First or Limit + Find with mssql, a sql server error is generated

Error

> mssql: Invalid usage of the option NEXT in the FETCH statement.

In these cases sql query being executed is invalid
Query

> SELECT \* FROM "users"  WHERE "users".deleted_at IS NULL AND (("users"."id" = '1')) ORDER BY "users"."id" ASC FETCH NEXT 1 ROWS ONLY

Basically the query needs to have "OFFSET 0 ROWS FETCH NEXT 1 ROW ONLY", or the FETCH statement should be removed all together.

Environment: Windows 10, MS Sql Server Express 2016

Here is the sample code:

```
package main

import (
    "log"

    "github.com/jinzhu/gorm"

    _ "github.com/jinzhu/gorm/dialects/mssql"
)

type User struct {
    gorm.Model
    Email     string
    Firstname string
    Lastname  string
}

func main() {
    // db connection code goes here
    db, err := gorm.Open("mssql", /*conn string*/)
    if err != nil {
        log.Panic(err)
        return
    }
    defer db.Close()

    db.LogMode(true)

    id := 1
    var e1 User
    db.First(&e1, id) // generates error
    log.Println("user id: ", e1.ID)

    var e2 User
    db.Offset(0).Limit(1).Find(&e2, id) // genertes error
    log.Println("user id: ", e2.ID)
}
```

**Comment by jacobmarshall** [comment]
I'm getting the same exact issue. It would be great to have this fixed.

**Comment by dipbhi** [comment]
As a workaround, this works

```
id := 1
var e1 User
db.Find(&e1, id)
```

**Comment by jacobmarshall** [comment]
Cheers.

A bit off topic, but I have a question about the MSSQL driver in general. Is it stable? Because I've tried using a simple Has One example and I just can't get that working either.

I'm going to do some more tests and probably file an issue if I can confirm something is acting strange.

**Comment by dipbhi** [comment]
IMO, mssql dialect does seem buggy at multiple places. However gorm provides some basic working functionality which should be enough for most of the cases.

**Comment by dipbhi** [comment]
The fix is very simple, LimitAndOffsetSQL function should be replaced with below. That should take care of errors generated by multiple functions.

```
func (mssql) LimitAndOffsetSQL(limit, offset interface{}) (sql string) {
	if offset != nil && limit != nil {
		if parsedOffset, err := strconv.ParseInt(fmt.Sprint(offset), 0, 0); err == nil && parsedOffset > 0 {
			sql += fmt.Sprintf(" OFFSET %d ROWS", parsedOffset)
		}
		if parsedLimit, err := strconv.ParseInt(fmt.Sprint(limit), 0, 0); err == nil && parsedLimit > 0 {
			sql += fmt.Sprintf(" FETCH NEXT %d ROWS ONLY", parsedLimit)
		}
	}
	return
}
```

**Comment by dipbhi** [comment]
Below updated function should take care of syntax error when offset is zero

```
func (mssql) LimitAndOffsetSQL(limit, offset interface{}) (sql string) {
	if offset != nil {
		if parsedOffset, err := strconv.ParseInt(fmt.Sprint(offset), 0, 0); err == nil && parsedOffset > 0 {
			sql += fmt.Sprintf(" OFFSET %d ROWS", parsedOffset)
		}
	}
	if limit != nil {
		if parsedLimit, err := strconv.ParseInt(fmt.Sprint(limit), 0, 0); err == nil && parsedLimit > 0 {
			if sql == "" {
				// add default zero offset
				sql += " OFFSET 0 ROWS"
			}
			sql += fmt.Sprintf(" FETCH NEXT %d ROWS ONLY", parsedLimit)
		}
	}
	return
}
```

**Comment by lessthanthree** [comment]
Add a merge request to this @dipbhi

**Comment by lyquocnam** [comment]
Still not work with SQLServer 2008 R2

**Comment by mosleim** [comment]
Still not working. 2019/12/01.
error message is:
`"mssql: Invalid usage of the option NEXT in the FETCH statement."`

**Comment by bluebrown** [comment]
Same issue. How can this basic function left broken for 3 years+ ? Why did I make myself the work yesterday using sqlite, thinking I can swap easily to sqlserver (as advertised by gorm) and now it's not "simply" working.

**Comment by PaulCombal** [comment]
The issue for me was that I was missing `AUTO_INCREMENT;PRIMARY_KEY` after my Id column in my model
