### ISSUE TITLE
Add database backend support for TiDB

### ISSUE THREAD

**Issue by insionng** [jinzhu/gorm#1207]
https://github.com/pingcap/tidb

**Comment by JackDrogon** [comment]
Tidb support mysql protocol. Choosing mysql is ok.

**Comment by insionng** [comment]
MySQL protocol only support in tidb server mode ,but not in the single application mode (tidb /goleveldb backend). Maybe.
See:https://github.com/go-xorm/tidb

**Comment by insionng** [comment]
Maybe I'm not quite right, but I would like to use tidb embedded inside the application.(via tidb/goleveldb)

**Comment by sebastianmacias** [comment]
Same here, I would love to be able to embed tidb inside the application, have a single bin deployment

**Comment by gregwebs** [comment]
What problem did you encounter with using TiDB as MySQL? The compatibility should be the same regardless of the backend (goleveldb or TiKV).
