### ISSUE TITLE
unsupported destination, should be slice or struct

### ISSUE THREAD

**Issue by Khusbu** [jinzhu/gorm#1208]
I get this error in db log when I am trying to insert a child record using update operation for the parent table.  The child table has default values for some of its columns. The child record is successfully inserted but the default values are not updated for the same. It was working fine but after I updated the library its not working anymore. For example:

type Child struct {
  CID string
  field string `gorm:"default:'something'"`
}
type Parent struct {
  ParentID string
  desc string `gorm:"default:'description'"`
  Child *Child `gorm:"ForeignKey:ParentID;AssociationForeignKey:ParentID"`
}
parent = &Parent{ParentID: "P123"}
parent.Child = &Child{CID: "123"} 

db.Model(parent).Update(parent)
fmt.Println(parent.Child.field) //Expected: "something", Actual: "" 

Do let me know if any further information is required. @jinzhu @sunfmin @levinalex @trevrosen @rubysolo @huacnlee

**Comment by danhardman** [comment]
You haven't specified the primary key on the structs. Might wanna do that.

Also, how did you add the defaults? AutoMigrate? I don't believe AutoMigrate will update default values. Might wanna check in your database that the columns actually have defaults set.

**Comment by Khusbu** [comment]
@danhardman Thanks for replying. I am using primary key for my structs. The problem is the defaults are getting updated in the db but those values are not reflecting in the child struct variable after firing update operation. Previously it was working fine.

**Comment by Achillesss** [comment]
I've just solved this problem.
my previous code:
`type Challenge struct {
	gorm.Model
	ChallengeTemplateID uint    `gorm:"not null"`
	ChallengerCount      int32                  `gorm:"not null;size:4"`
	ChallengeTemplate    *ChallengeTemplate     `gorm:"ForeignKey:ChallengeTemplateID"`
	ChallengerChallenges []*ChallengerChallenge `gorm:"ForeignKey:ChallengeID"`
}
func (a *Challenge) updateChallengerCount(d *gorm.DB) (res error) {
	if a != nil {
		var count int32
                a.QueryChallengerChallenges(d)
                // assigning count ...
		res = d.Model(a).Update("challenger_count", count).Error
	} else {
		res = log.FError(fmt.Errorf("nil receiver"))
	}
	return
}`
when I change `res = d.Model(a).Update("challenger_count", count).Error` to `res = d.Model(a).Set("gorm:save_associations", false).Update("challenger_count", count).Error`, the code runs without problem

**Comment by jinzhu** [comment]
`gorm:"ForeignKey:ParentID;AssociationForeignKey:ParentID"` 

`Child` doesn't have the `ParentID` field?
