### ISSUE TITLE
sqlite3 migration fails: duplicate column name: id

### ISSUE THREAD

**Issue by uovobw** [jinzhu/gorm#1209]
I am trying to migrate a schema by only adding columns and, even though sqlitebrowser and the python equivalent are working correctly, i get an error during db.AutoMigrate and the migration fails.
i have added the LogMode() calls to inspect the error, what i am getting is:

> (<autogenerated>:119) 
> [2016-10-06 15:25:47]  [0.23ms]  SELECT count(*) FROM sqlite_master WHERE tbl_name = 'mappings' > AND (sql LIKE '%!((MISSING)"id" %!'(MISSING) OR sql LIKE '%!,(MISSING)"id" %!'(MISSING) OR sql LIKE > '%!((MISSING) id %!'(MISSING) OR sql LIKE '%!,(MISSING) id %!'(MISSING));

I think this might be a different appearance of https://github.com/jinzhu/gorm/issues/865 . 

I will send a wiped database, the schema definitions and all the code to reproduce the error via email to the address in the contacts page, i am very sorry for this overhead but i have not been authorized to post the schema on a public bug tracker.

**Comment by uovobw** [comment]
email with wiped database copy, models.go definition file and main to reproduce the bug sent to the email address. many thanks

**Comment by uovobw** [comment]
@jinzhu you could not reproduce the data? why has this been closed? in my experience it's still there if i run with the db i sent you...can i help triage this more in any way? let me know! thanks

**Comment by jinzhu** [comment]
Hello @uovobw 

I checked the email you send to me, the `test.go` is not runnable as it lacks of some structs definitions, `models.go` doesn't seems right, `blog.db` that used in this script in not included in the email's attachment.

If it still doesn't works for you, please post a complete runnable script to github, so others also possible check your issues when I don't have time.

Thank you.

**Comment by XANi** [comment]
@uovobw It is possible to trigger it easily but I would not call it a bug,it happens when composing structs that have same field names:

```go
package main
import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
	"fmt"
	"time"
)

type Message struct {
	Content string
	CreatedAt time.Time
}

type Queue struct {
	Message
	QueueId string
	CreatedAt time.Time
}

func main() {
	db, err := gorm.Open("sqlite3", `test.db`)
	if err != nil { fmt.Println(err)}
	defer db.Close()
	db.LogMode(true)
	db.AutoMigrate(&Queue{}, &Message{})
}
```
it will try to create column created_at twice, once for composed `Message` and once for `Queue`:

    [2017-04-19 18:23:55]  [0.84ms]  CREATE TABLE "queues" ("content" varchar(255),"created_at" datetime,"queue_id" varchar(255),"created_at" datetime )

**Comment by uovobw** [comment]
@jinzhu hello, thanks for the reply, you are absolutely right! i tested it _now_ using `go version go1.8 linux/amd64` and it indeed errors out. I have replied to that first email with the correct code and file names. sorry for wasting your time with the previous report.

**Comment by uovobw** [comment]
@XANi i'm not sure you are seeing the same issue i am seeing, i was referring to the

> [2017-04-19 18:48:28]  duplicate column name: id

you get when running the automigrate.

**Comment by XANi** [comment]
@uovobw it's different issue triggering same error message. That's how I found this bug page, google found it when I searched for what that error means :)

full log:

    (/tmp/z/main.go:25)
    [2017-04-20 00:13:37]  duplicate column name: created_at
    (/tmp/z/main.go:25)
    [2017-04-20 00:13:37]  [0.41ms]  CREATE TABLE "queues" ("content" varchar(255),"created_at" datetime,"queue_id" varchar(255),"created_at" datetime )
    (/tmp/z/main.go:25)
    [2017-04-20 00:13:37]  [0.01ms]  CREATE TABLE "messages" ("content" varchar(255),"created_at" datetime )
