### ISSUE TITLE
Asterisk (*) selector return empty struct [mssql]

### ISSUE THREAD

**Issue by souzadevinicius** [jinzhu/gorm#1211]
When I'm executing a query with \* selector the Find method doesn't fill struct with the values.
But, when I select a specific field, this field value is filled in struct.

PS: I'm using mssql in compatibility mode.

**Comment by jinzhu** [comment]
We should fixed all issues for mssql, if you still have any problem, please create a new issue.

Thank you.

**Comment by souzadevinicius** [comment]
Doesn't fix.

It returns a struct with default values. Like this example below:

{0    false 0 0 0 0  0001-01-01 00:00:00 +0000 UTC 0 0 0 0}

**Comment by rafael84** [comment]
I'm facing the same issue.

However when I specify something like `db.Select("id, field1, field2, fieldN")`, it works.

**Comment by RedEars** [comment]
Same problem here!

**Comment by petrogdev** [comment]
Not sure if anyone still experiencing this issue. 
For me, using a plain (*) asterisk as a selector wouldn't work either. I had to append the model name in front.
`r.db.Table("invite").
Select("invite.*").
Where("id = ?", id).
Scan(&invite)`
