### ISSUE TITLE
postgres NOTIFY in scope?

### ISSUE THREAD

**Issue by brasilikum** [jinzhu/gorm#1221]
Hi, 
I would be interested in a using the NOTIFY feature of postgres. [lib/pq has implemented this](https://godoc.org/github.com/lib/pq#Notification). I could try to implement this in gorm, but the question is, if it is even in scope, as it is very specific for postgres. 
Opinions on this one?
Is there any previous work/thoughts about this topic in this project that I have not discovered?

**Comment by jinzhu** [comment]
Maybe better to just `lib/pg` to do the job?
