### ISSUE TITLE
Support MySQL 5.7 generated columns

### ISSUE THREAD

**Issue by applee** [jinzhu/gorm#1229]
As of MySQL 5.7, it supports the generated columns, as below:

```
CREATE TABLE `servers` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `hostname` varchar(64) NOT NULL DEFAULT '',
  `info` json  COMMENT,
  `memory_size` int(11) GENERATED ALWAYS AS (json_extract(`info`,'$.Memory.Size')) VIRTUAL,
  `cpu_num` tinyint(3) GENERATED ALWAYS AS (json_length(json_extract(`info`,'$.CPU'))) VIRTUAL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
```

According the manual, "For INSERT, REPLACE, and UPDATE, if a generated column is inserted into, replaced, or updated explicitly, the only permitted value is DEFAULT.". 
The correct insert SQL is `insert into servers (hostname) values ('test')` or `insert into servers (hostname, cpu_num) values ('test', DEFAULT)`, but how can I insert a record with gorm? I can't find any way to use `gorm.Expr` in `goorm.Create` method and also can't omit some column to insert.

**Comment by jinzhu** [comment]
I don't get what's the problem, could you please follow https://github.com/jinzhu/gorm/blob/master/.github/ISSUE_TEMPLATE.md to reopen another issue if it is still a problem for you.

Thank you.
