### ISSUE TITLE
表级联后怎么输出级联表的相关字段值？

### ISSUE THREAD

**Issue by lijunfeng** [jinzhu/gorm#1232]
ORM里这样写
DB.Debug().Select("article._,node._").Joins("LEFT JOIN node ON node.id = article.node_id").Find(&articles)
输出的是正确的
SELECT article.*,node.* FROM `article` LEFT JOIN node ON node.id = article.node_id 
但是我怎么拿到node 相关字段的值呢？

**Comment by lijunfeng** [comment]
/***************************************************
  信息内容表结构
***************************************************/
type Article struct {
	ID               string `gorm:"primary_key:yes; type:varchar(48)"`
	Node             Node   `gorm:"ForeignKey:NodeID;"`
	NodeID           string `gorm:"type:varchar(48)"`
	Topic            string
}

/***************************************************
  目录表结构
***************************************************/
type Node struct {
	ID              string `gorm:"primary_key:yes; type:varchar(48)"`
	Topic           string
}

DB.Preload("Node").Find(&articles)

搞定，但是NODE的值全输出来了，怎么只输入其中topic的值？

**Comment by owengaozhen** [comment]
scan
