### ISSUE TITLE
gorm how to foreign self

### ISSUE THREAD

**Issue by kker** [jinzhu/gorm#1233]
for example:

type User struct {
    gorm.Model
    BestFriend User
}

I want BestFriend field foreign the same User model,How to define this with golang gorm package.

Thanks.

**Comment by kira8565** [comment]
i have this question too......

**Comment by Allendar** [comment]
This might help: http://jinzhu.me/gorm/associations.html#polymorphism

**Comment by jinzhu** [comment]
`*User`
