### ISSUE TITLE
How do I query Microsoft SQL Server correctly?

### ISSUE THREAD

**Issue by ecast040** [jinzhu/gorm#1234]
I ran the code below
var variableName models.SomeModel
db.LogMode(true)
db.Debug().First(&variableName , [entered id that exists])

and all I got was  {0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0} and I know this entry isn't empty. Did I do something wrong? I tried using a slice instead of my gorm object but it still had the same result and the SQL query spat out by debug works correctly when executed inside MSSQL so I'm not sure what's going on. Anyone have any ideas?

**Comment by coderabsolute** [comment]
Does it support Microsoft Sql Server?

**Comment by danhardman** [comment]
Can you create an executable script: https://github.com/jinzhu/gorm/blob/master/CONTRIBUTING.md#executable-script-template please.

GORM does work for MSSQL, it must be something you're doing your end. Happy to help if you provide a few more details! Displaying the full connection, migration and logs would be helpful

**Comment by jinzhu** [comment]
All GORM tests passed for mssql, if you still have the same issue, please create a new issue.

Thank you.
