### ISSUE TITLE
gorm如何一次插入多条数据？

### ISSUE THREAD

**Issue by owengaozhen** [jinzhu/gorm#1241]
db.create([]user).err会出现错误。应该如何批量插入数据

**Comment by u0x01** [comment]
批量插入数据需要自己写sql。或者这样可以提高速度：

    tx := DB.Begin()
    tx.create(&user)
    tx.commit()

**Comment by owengaozhen** [comment]
这样开销太大。我插入100条数据这样插我要循环100次。。这样不行的。。。我现在直接sql插入的。。有没有什么方法可以不写sql呢

**Comment by xiaopengzhang** [comment]
自己写sql语句，拼接多个用户数据，然后插入

**Comment by lpckkx** [comment]
请问下连接mysql时候，执行操作，表名最后必须加上s才正常 要不然就报找不到表，是什么原因呢？

**Comment by owengaozhen** [comment]
@lpckkx  可以自定义表名
func (s 结构体)TableName() string {
	return "表名"
}

**Comment by owengaozhen** [comment]
@lpckkx  可以自定义表名
func (s 结构体)TableName() string {
	return "表名"
}

**Comment by owengaozhen** [comment]
@lpckkx  可以自定义表名
func (s 结构体)TableName() string {
	return "表名"
}

**Comment by owengaozhen** [comment]
@lpckkx  可以自定义表名
func (s 结构体)TableName() string {
	return "表名"
}

**Comment by owengaozhen** [comment]
@lpckkx  可以自定义表名
func (s 结构体)TableName() string {
	return "表名"
}

**Comment by lpckkx** [comment]
/*
 用户
*/
type loguser struct {
	ID   int `gorm:"primary_key"`
	name string
}

var user loguser

	//1:first
	db.First(&user)

	fmt.Printf("user.name=%2s", user.name)

获取不到name的值 请问是哪里不对吗？  数据库 字段和接口构体一样 ， 

非常感谢~

**Comment by lpckkx** [comment]
@owengaozhen  麻烦给看下，上面的问题  谢谢哈

**Comment by owengaozhen** [comment]
@lpckkx  结构体name要大写

**Comment by happyEgg** [comment]
@owengaozhen 
你批量插入怎么解决的呀？手写吗

**Comment by hairichuhe** [comment]
我建了个群，我们一起讨论，287376123

**Comment by PegasusWang** [comment]
Any solutions yet ?
