### ISSUE TITLE
invalid sql type StringArray (slice) for postgres

### ISSUE THREAD

**Issue by mehdy** [jinzhu/gorm#1248]
I want to use the postgres array and I'm using the `pq.StringArray` as a type for may array which I know and expect that it has implemented the `Scanner` interface but when I use `AutoMigrate(&Post)` for example I still get this error:
`invalid sql type StringArray (slice) for postgres`

```
import "github.com/lib/pq"
...
type Post struct {
    ...
    Tags        pq.StringArray
}
```

**Comment by mehdy** [comment]
I solved it by using the `gorm` tag like this:
```
import "github.com/lib/pq"
...
type Post struct {
    ...
    Tags        pq.StringArray `gorm:"type:varchar(64)[]`
}
```
I tried it the first time too but there was an accidental space after the `gorm:` and it wasn't working without any errors like this:
```
Tags        pq.StringArray `gorm: "type:varchar(64)[]`
```
anyway it's working now

**Comment by nri-pl** [comment]
```
package main

import (
	"github.com/jinzhu/gorm"
	"github.com/lib/pq"
	"log"
)

func main() {
	db, err := gorm.Open("postgres", "user=lw dbname=kk sslmode=disable")
	if err != nil {
		log.Panic(err)
	}
	db.AutoMigrate(&Test{})
}

type Test struct {
	ID   uint64         `gorm:"primary_key"`
	Tags pq.StringArray `gorm:"type:varchar(100)[]`
}

```
Output:
```
panic: invalid sql type StringArray (slice) for postgres

goroutine 1 [running]:
github.com/jinzhu/gorm.(*postgres).DataTypeOf(0xc420139e40, 0xc420070ea0, 0x0, 0x0)
	/go/src/github.com/jinzhu/gorm/dialect_postgres.go:77 +0x425
github.com/jinzhu/gorm.(*Scope).createTable(0xc420141500, 0xc420143180)
	/go/src/github.com/jinzhu/gorm/scope.go:1097 +0x2e2
github.com/jinzhu/gorm.(*Scope).autoMigrate(0xc420141500, 0x695ee0)
	/go/src/github.com/jinzhu/gorm/scope.go:1176 +0x3e4
github.com/jinzhu/gorm.(*DB).AutoMigrate(0xc42016a000, 0xc42014bf48, 0x1, 0x1, 0x1)
	/go/src/github.com/jinzhu/gorm/main.go:557 +0x77
main.main()
	/main.go:14 +0x198

```
Hi,
It seems to me that it should work.
What am I doing wrong?

**Comment by MarkPochert** [comment]
@mehdy Thanks for your solution. I found a small typo in your snippet

`import "github.com/lib/pq"
...
type Post struct {
    ...
    Tags        pq.StringArray `gorm:"type:varchar(64)[]**"**`
}`

(Missing " at the end)

**Comment by wenweih** [comment]
@mehdy no space work for me

**Comment by gocs** [comment]
I used `gorm: "type:text[]"`

anything wrong with that?

**Comment by charlesgreen** [comment]
It would be great if there was an example in the docs. 
This was very helpful.
