### ISSUE TITLE
Unable to get data from associated table of has_many

### ISSUE THREAD

**Issue by VenkyMadgundi** [jinzhu/gorm#1253]
Tables:
CREATE TABLE `events` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `program_id` int(11) DEFAULT NULL,
  `account_id` int(11) DEFAULT NULL,
  `manager_id` int(11) DEFAULT NULL,
  `start_at` datetime DEFAULT NULL,
  `end_at` datetime DEFAULT NULL,
  `notes` text,
  PRIMARY KEY (`id`),
  KEY `index_events_on_program_id` (`program_id`),
  KEY `index_events_on_account_id` (`account_id`),
  KEY `index_events_on_manager_id` (`manager_id`),
  KEY `index_events_on_start_at` (`start_at`),
  KEY `index_events_on_end_at` (`end_at`),
) ENGINE=InnoDB AUTO_INCREMENT=58857 DEFAULT CHARSET=latin1;

CREATE TABLE `programs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `brand_id` int(11) DEFAULT NULL,
  `active` tinyint(1) DEFAULT '1',,
  PRIMARY KEY (`id`),
  KEY `index_programs_on_brand_id` (`brand_id`),
  KEY `index_programs_on_active` (`active`),
) ENGINE=InnoDB AUTO_INCREMENT=493 DEFAULT CHARSET=latin1;

Types:
type Event struct {
  ID                   int
  ProgramID            int
  AccountId            int
  ManagerId            int
  StartAt              time.Time
  EndAt                time.Time
  Notes                string
}

type Program struct {
  ID            int
  Name          string
  BrandId       int
  Active        int8
  Events        []Event `gorm:"ForeignKey:ProgramID"`
}

All tables have many records, I want to Access program name from events. Is it possible?
I tried with following:
db.Limit(10).Order("id asc").Find(&events).Preload("Programs")

Is any quick way to access program name from event model like Event.first.Program.name?

**Comment by jinzhu** [comment]
order is wrong `Preload().Find()`
