### ISSUE TITLE
Add support for different field name casing

### ISSUE THREAD

**Issue by fieryorc** [jinzhu/gorm#1254]
I use existing DB that uses camel case for field names and snake case for table names. Gorm seems to have hardcoded ToDBName() function that is not customizable. 

our table looks like this:

product_skus {
 skuId string
}

**Comment by jinzhu** [comment]
refer　http://jinzhu.me/gorm/models.html#conventions

**Comment by fieryorc** [comment]
Here are the problems with the current approach:

1. The relationships don't still maps (many2many doesn't work).. Check my stackoverflow question here. http://stackoverflow.com/questions/40094666/gorm-many2many-mapping-to-custom-field-names
2. With large no. of tables, I want to be able to define my casing logic in 10 lines instead of writing metadata on 100s of columns.. This is both painful and error prone.

**Comment by sjdweb** [comment]
For google users, this can be done now, PR here: https://github.com/jinzhu/gorm/pull/2040
