### ISSUE TITLE
can't insert data into greenpulm based on postgres

### ISSUE THREAD

**Issue by wiyr** [jinzhu/gorm#1255]
When i insert data to greenpulm db by `db.Save`, i meet this error `The RETURNING clause of the INSERT statement is not supported in this version of Greenplum Database`, but i can do it through `db.Exec`.  postgres version  8.2+

**Comment by jinzhu** [comment]
Seems like it doesn't support the `RETURNING` syntax that postgres support, maybe you could try the mysql dialect or write a new one?
