### ISSUE TITLE
Has One Create with anonymous field

### ISSUE THREAD

**Issue by Guiguillermo** [jinzhu/gorm#1260]
Hello,

I have a User structure which Has One Association.
```
type User struct {
	ID       int
	...
}
```
```
type Association struct {
	ID       int
	UserID   int
}
```

I also have an AssoUser structure, which is composed of a anonymous field User, and has a pointer to Assocation.

```
type AssoUser struct {
	User
	Asso *Association
}
```

When I run 
```
var assoUser AssoUser
db.Debug().Create(&assoUser)
```
I expect it to create the User AND the Association, but it only creates the User.

Hoping you could help.

**Comment by jinzhu** [comment]
`Association` is not a valid association of `AssoUser`, change the `userID` to `AssoUserID`
