### ISSUE TITLE
MySQL Error 1040: Too many connections

### ISSUE THREAD

**Issue by danhardman** [jinzhu/gorm#1271]
I've just started getting this error on my web app, only when it's gone live (presumably putting it under load). I'm guessing this error is coming further down the line, but GORM is the only way I interface with the DB so this is a good starting point.

Is there anything I could be doing wrong with GORM to be causing this error? I've already declared: 

```go
db, err := gorm.Open("mysql", connectionString)
utils.PanicOnErr(err)

err = db.DB().Ping()
utils.PanicOnErr(err)

db.DB().SetMaxIdleConns(10)
db.DB().SetMaxOpenConns(100)
```

In hopes that setting max connections would fix this issue. Now instead of panicking, the app just stays on hold. Presumably waiting for a connection to close.

I see: https://github.com/jinzhu/gorm/blob/master/callback_query.go#L59 that queries are closed properly here. Just wondering if I could be missing something anywhere else?

**Comment by danhardman** [comment]
I think my issue may have been with how I was using Transactions. As I wasn't using them to update records, but simply to query for them, I didn't feel the need to Commit once they were complete. I think this is what left the connections open.

Still testing but from tests on my dev machine, that seems to have fixed it.

**Comment by danhardman** [comment]
Still getting the issue, even with all transactions committed. Just noticed a massive jump in connections upon doing a Find(), no idea why those connections haven't been closed.

**Comment by jinzhu** [comment]
Could you write a script that reproduce the issue?

**Comment by danhardman** [comment]
@jinzhu I'll give it a go. I've found it in other areas where lots of connections are made very quickly. Will try reproduce in the morning.

**Comment by jinzhu** [comment]
Going to close this issue, please reopen it if could reproduce it as a GORM issue.

**Comment by SiLingTan** [comment]
Hi @jinzhu , I have a similar issue related to this. 

Encountered error: 
`Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)` (and `Too many connections` from mysql database once). 

For the `max_prepared_stmt_count` statement error, I have checked that `Com_stmt_prepare` (5161395) is close to `Com_stmt_close`(5126388) and don't think it is an application leak. 

- Does gorm maintain one connection to the db for each AWS instance?  The first error happens suddenly and dies down within an hour. 
- Do I need to set `SetMaxIdleConns`, `SetMaxOpenConns` for the connection pool?

Sample code I did to call db: 
```var foos []*Foo
err := t.db.Unscoped().Where("<myqueryparameters> ", <myqueryvalues>).Find(&foos).Error```

System version:
```Gorm: jinzhu/gorm v1.9.1
Go:  go1.11 darwin/amd64
MySQL: 5.7.21```

Thank you so much for your help!

**Comment by madiazp** [comment]
Hi, same issue here.

You can reproduce it with a k6.io script that iterate requests to an endpoint that use a transaction. I made this with my api and a aws-rds instance and the connections to the db won't close.

**Comment by helperShang** [comment]
Hi, same issue here.

**Comment by inluxc** [comment]
I also have the same problem. In sync script.

**Comment by tenfyzhong** [comment]
https://github.com/jinzhu/gorm/blob/179760d8343ed15cbb9f071ca824bc35ee7784bb/callback_create.go#L162
