### ISSUE TITLE
Add comment to column

### ISSUE THREAD

**Issue by inoc603** [jinzhu/gorm#1273]
Hi, I'm wondering how to add comment to each column. I tried to add `COMMENT:'my comment'` in the `gorm` tag, and it didn't work.

Does gorm support adding comment?

THX

**Comment by CharlieGlass** [comment]
We focus on providing our customers with only the best customer service as well as top-notch mobile glass repair work, from home to auto to commercial, and as a result our rating with the Better Business Bureau continues to be an A+. 

Visit us at <a href="http://www.reliableglassaz.com">Reliable Glass</a>

**Comment by jinzhu** [comment]
No, GORM doesn't support that yet.
