### ISSUE TITLE
Implementing INSERT IGNORE with gorm, public access to logger?

### ISSUE THREAD

**Issue by nsf** [jinzhu/gorm#1275]
Hi, I'm trying to implement a nice version of INSERT IGNORE (I think it's mysql specific) in gorm. And here's what I got:

```go
func DBInsertIgnore(dbq *gorm.DB, obj interface{}) int64 {
	scope := dbq.NewScope(obj)
	fields := scope.Fields()
	quoted := make([]string, 0, len(fields))
	placeholders := make([]string, 0, len(fields))
	for i := range fields {
		if fields[i].IsPrimaryKey && fields[i].IsBlank {
			continue
		}
		quoted = append(quoted, scope.Quote(fields[i].DBName))
		placeholders = append(placeholders, scope.AddToVars(fields[i].Field.Interface()))
	}

	scope.Raw(fmt.Sprintf("INSERT IGNORE INTO %s (%s) VALUES (%s)",
		scope.QuotedTableName(),
		strings.Join(quoted, ", "),
		strings.Join(placeholders, ", ")))

	result, err := scope.SQLDB().Exec(scope.SQL, scope.SQLVars...)
	if err != nil {
		InternalServerErrorMessage(err.Error())
	}

	id, err := result.LastInsertId()
	if err != nil {
		InternalServerErrorMessage(err.Error())
	}

	return id
}
```

And everything is great, except I can't get access to gorm's logger. And I can't use scope's Exec(), because it doesn't give me the result back and I would like to be able to get the LastInsertId here.

Maybe there is a different way to achieve what I want? Or perhaps it's worth exposing logger interface? I mean the interface itself is kind of exposed already, because apps are supposed to override the logger for their own needs, so why hiding it?

**Comment by jinzhu** [comment]
get the logger from db, then use its `Print(v...)` method

**Comment by nsf** [comment]
How? It's unexported: https://github.com/jinzhu/gorm/blob/master/main.go#L22

There are no getters for it.

**Comment by jinzhu** [comment]
Do it like this?

```go
myLogger := gorm.Logger{log.New(os.Stdout, "\r\n", 0)}
db.SetLogger(myLogger)
```

**Comment by nsf** [comment]
I know how to set it, I need to **get** an existing one. Because this function uses Raw queries which are not logged. And I want to log it. Currently I have to pass my current logger around to do so, despite the fact that gorm context already has it.

**Comment by jinzhu** [comment]
GORM's DefaultLogger is same as `gorm.Logger{log.New(os.Stdout, "\r\n", 0)}` , so I think it is not necessary to add a getter. https://github.com/jinzhu/gorm/blob/master/logger.go#L15
