### ISSUE TITLE
Dynamic column name

### ISSUE THREAD

**Issue by nbochenko** [jinzhu/gorm#1277]
Hi everyone,
I was wondering if there is a way to create dynamic tags, for column mappings.
Or something like tagSettings Callback function.

For example, it would be something like :

```
type Property struct {
	ID        int    `gorm:"column:property_id;primary_key"`
	Reference string `gorm:"column_callback:property_reference"`
}
```
then I'd register this "column_callback", that would make an operation on "property_reference".
```
gorm.customTags.addMapping("column_callback", function(value string) string {
    return value + "_anything" // would return "property_reference_anything"
})
```
Or is there a way to define the column name of a struct property, without tags, in a function?

**Comment by jinzhu** [comment]
No, we doesn't support that.
