### ISSUE TITLE
json of json not work

### ISSUE THREAD

**Issue by anphung** [jinzhu/gorm#1279]
Sample:
```
{
  "id": 1
  "data": {1: 2}
}
```
Struct definition:
```
type Item struct {
  id int `json:"id"`
  data interface{} `json:"data"`
}
```
I need to parse the payload from a http post, so I used `interface{}` for `data`, `json.Unmarshal()` is successful, but gorm produces error while calling `db.Create(item)`:
```
(sql: converting Exec argument #5's type: unsupported type map[string]interface {}, a map)
```

Instead, I change from `interface{}` to `string`, calling `json.Unmarshal()` to parse json POST payload produces error.
```
unmarshal type error: expected=string, got=object
```
Basically, one requires `interface{}`, one requires `string`.

Anyone encountered this?

**Comment by zardak** [comment]
I'd really suggest to use separate types for GORM model and request data.

But, if you absolutely want it to be the same type, you can define custom type for your field, which implements `sql.Valuer`, `sql.Scanner`, `json.Marshaler` and `json.Unmarshaler` interfaces.

**Comment by anphung** [comment]
Thanks, I will try defining custom field.

About using separate types for GORM, and request data, I'm currently using it. The thing is when converting (I assign field to field) from `GORMItem` to `RequestItem`, it is ok in case there are 2 fields in this case (2 assignment), but gets messy when there are lots of fields.
