### ISSUE TITLE
How to do a select random ? type:question

### ISSUE THREAD

**Issue by gmolveau** [jinzhu/gorm#1282]
Hi ! Thank you for you work !

I'd like to know if it's possible to do a random select without using RAW SQL ?

For example, in MySQL I would to use " ORDER BY RAND() " 
and in Postgres " ORDER BY RANDOM() ".

Thank you for your help !

**Comment by jinzhu** [comment]
`Order(gorm.Expr("rand()"))` or `Order(gorm.Expr("random()"))`

**Comment by yreme** [comment]
Thanks @jinzhu , It works for me!

Use `rand()`  or  `random()`  depend on  the database type  . For example , 

-  use `rand()`  or `Order(gorm.Expr("rand()")) `  in `MySQL`  , 
-  use   `random()` or `Order(gorm.Expr("random()"))` in  `PostgreSQL` or  `sqlite` 

More database type can find solution from this answer:
https://stackoverflow.com/questions/580639/how-to-randomly-select-rows-in-sql/1209946#1209946

**Comment by MrWormHole** [comment]
Order(gorm.Expr("random()")) no longer works in gorm.io/gorm versions, it prints ORDER BY {"random()" nil false} inside the raw query.

Use Order("random()") if you are using gorm v2 which is hosted on gorm.io

**Comment by jinzhu** [comment]
@MrWormHole also refer https://gorm.io/docs/query.html#Order
