### ISSUE TITLE
Using Associations

### ISSUE THREAD

**Issue by goelpriyanka21** [jinzhu/gorm#1283]
Hi, 
Thanks for your work.

At http://jinzhu.me/gorm/crud.html#associations
user := User{
    Name:            "jinzhu",
    BillingAddress:  Address{Address1: "Billing Address - Address 1"},
    ShippingAddress: Address{Address1: "Shipping Address - Address 1"},
    Emails:          []Email{{Email: "jinzhu@example.com"}, {Email: "jinzhu-2@example@example.com"}},
    Languages:       []Language{{Name: "ZH"}, {Name: "EN"}},
}

db.Create(&user)
////INSERT INTO "languages" ("name") VALUES ('ZH');
//// INSERT INTO user_languages ("user_id","language_id") VALUES (111, 1);
//// INSERT INTO "languages" ("name") VALUES ('EN');
//// INSERT INTO user_languages ("user_id","language_id") VALUES (111, 2);

Since, I already have records in "languages",
 I want to skip:
INSERT INTO "languages" ("name") VALUES ('ZH');
INSERT INTO "languages" ("name") VALUES ('EN');
& give:
 Languages: []Language{{ID: 1}, {ID:2}}

Is it possible? Or Any other method to do this.
Kindly reply.

**Comment by jinzhu** [comment]
`db.Set("gorm:save_associations", false).Save(&user)`
