### ISSUE TITLE
incorrect table name

### ISSUE THREAD

**Issue by timeloveboy** [jinzhu/gorm#1285]
incorrect table name

sSELECT * FROM ``   ORDER BY `mid` LIMIT 100[]" 

model struct is 
type MemberInfo struct {
	Mid         int    `json:"id"  gorm:"primary_key"`
	Exist       bool `json:"exist"`
}

**Comment by wilsontamarozzi** [comment]
Specifying The Table Name

```golang
// Create `deleted_users` table with struct User's definition
db.Table("deleted_users").CreateTable(&User{})

var deleted_users []User
db.Table("deleted_users").Find(&deleted_users)
//// SELECT * FROM deleted_users;

db.Table("deleted_users").Where("name = ?", "jinzhu").Delete()
//// DELETE FROM deleted_users WHERE name = 'jinzhu';
```

**Comment by jinzhu** [comment]
@timeloveboy please refer document, for your problem, I think you are not using correctly, maybe using double pointer like:

`db.First(&&User{})`

**Comment by robbbsen** [comment]
Happens to me aswell.

```go
var items []Item
d := DbLocal.Find(&items)
// [2018-12-17 16:59:14]  [601.47ms]  SELECT * FROM `items`  WHERE `items`.`deleted_at` IS NULL
// [14551 rows affected or returned ] 

if d.Error != nil {
	log.Fatal(d.Error)
}

for _, item := range items {
	// doing some calculations on existing variables
	item.Value *= 100 

	d := DbLocal.Update(&item)
	if d.Error != nil {
		log.Fatal(d.Error) 
		// [2018-12-17 16:59:17]  [23.64ms]  UPDATE `` SET ` ....
		// [0 rows affected or returned ] 
		// Error 1103: Incorrect table name ''
	}
}
```

As you can see I query the db right before updating it on the SAME table. I get results, change values, want to update and get an error about an `incorrect table name ''`.

I've not used the `TableName()` function in this example. Either way I HAVE tried setting it explicitly. Same story: Query works, update fails.

### Something else that could point into a direction:
I'm using `DbLocal.AutoMigrate(&Item{})` to ensure the existance of all columns. I've added an extra test-column to my struct and it got inserted! After that my code (see above) got executed and raised the error about the table-name being ''.

So everything falls back to the update. Everything else is working.

**Comment by wilsontamarozzi** [comment]
What is the complete output of the Update command?

What may be happening is that some of your fields have become primary keys, and when gorm does the query, it places the field as a condition (where).

I made a new project this week using Gorm and here everything is normal. Do you have your code on Github?

Pardon my English.

**Comment by robbbsen** [comment]
> 
> 
> What is the complete output of the Update command?
> 
> What may be happening is that some of your fields have become primary keys, and when gorm does the query, it places the field as a condition (where).
> 
> I made a new project this week using Gorm and here everything is normal. Do you have your code on Github?
> 
> Pardon my English.

Hey. The problem is this project is to 100% non-public as its being used commercial. I'll do my best to help finding the problem.

In my struct I havent used `gorm.Model`. I have inserted all fields manually like so:
```go
type Item struct {
	ID               uint `gorm:"primary_key"`
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        *time.Time `form:"-"`
        Field1
        Field2
        ...
}
```
Writing it down and declaring `form:"-"` is needed because of a bug in [gin](https://github.com/gin-gonic/gin).

### Workflow:

```go
db.Where("field > 60").Find(&items)
for _, item := range items {
	item.Field1 += 1
	db.Update(&item) // Gives the following query and error
}
```

(C:/Go/projects/src/bitbucket.org/project1/main.go:171) 
[2018-12-21 11:01:21]  [25.10ms]  UPDATE `` SET `field1` = '7631', `field2` = 'some text inside', `created_at` = '2018-12-17 12:31:39', `field3` = 'texttt', `field4` = 'ml', `field5` = 'some more text here', `field6` = '1337', `id` = '50', `field7` = '56151651', `updated_at` = '2018-12-17 17:07:59'
[0 rows affected or returned ] 
Error 1103: Incorrect table name ''
