### ISSUE TITLE
Why does the DISTINCT keyword ignore ORDER BY?

### ISSUE THREAD

**Issue by Cosebe** [jinzhu/gorm#1291]
I can not understand the eb06255 commit.
Why does the DISTINCT keyword ignore ORDER BY?
There is no way to use a query that contains both DISTINCT and ORDER BY.

For example.

```
SELECT DISTINCT books.*  
	FROM `books` LEFT JOIN book_categories ON books.id = book_categories.book_id  
	WHERE `books`.deleted_at IS NULL AND ((category_id >= '100' and category_id < '200'))  
	ORDER BY books.publish_date DESC, books.id DESC LIMIT 21
```

**Comment by jinzhu** [comment]
Hi @Cosebe 

Postgres doesn't work with DISTINCT with ORDER BY together, so made that change.

**Comment by Cosebe** [comment]
In MYSQL, there is no problem. Should not the code be executed only when using Postgres driver?

There is no problem in MYSQL, and the SQL syntax itself is fine.

**Comment by Cosebe** [comment]
I really like GORM.
I would like to be able to use "DISTINCT + ORDER BY" in GORM + MYSQL. Please! @jinzhu

**Comment by ivpusic** [comment]
@jinzhu could you provise some resource where you got this conclusion? `Postgres doesn't work with DISTINCT with ORDER BY together, so made that change.`. I am using pg 9.6 with distinct and order by and it works.

**Comment by jinzhu** [comment]
@ivpusic I found this issue when using `DISTINCT` with `ORDER BY` together with postgres, also I found some similar issues with Google...

**Comment by KlausVii** [comment]
@jinzhu Could gorm at least return an Error in this case, since at the moment gorm lets me use DISTINCT and ORDER BY in the same query, just to have the ORDER BY silently disappear from my query.

Also what's the best way to work around this for now? Do I need to revert to a full Raw() query?

**Comment by meh-** [comment]
@jinzhu postgres perfectly works with `DISTINCT ON (column1) ... ORDER BY column1, ...`. but since this commit [eb06255](https://github.com/jinzhu/gorm/commit/eb06255b667da417d982c6412c4602e932cc5283) it's not possible.
I could fix current regex for distinct search or add dialect specific expressions. Is it ok?

**Comment by rohansb** [comment]
@jinzhu @meh- running into same issue getting syntax error due to `DISTINCT ON` clause. Even with `db.Raw` query. Its a perfectly valid Postgres query that does not work with gorm. Please fix

**Comment by jinzhu** [comment]
This should be fixed, thank you for your report.
