### ISSUE TITLE
Postgresql timestamp is not as precise as golang's time.Time 

### ISSUE THREAD

**Issue by mehdy** [jinzhu/gorm#1292]
I'm using `reflect.DeepEqual` for the inserted object and retrieved object (by query) in my tests. it was failing and after some struggling with the problem I figured it out that Postgres timestamp is precise by microsecond and time.Time is precise by nanosecond.

p.s I've tested SQLite and it's okay and I haven't tested mysql

**Comment by jinzhu** [comment]
MySQL also won't store the nanosecond even the microsecond won't be saved if you haven't configured it...

So you can't really use `reflect.DeepEqual`, maybe write another method to check it.

@jspc this sounds like a bug from the database driver

**Comment by jspc** [comment]
@jinzhu ah- I thought it was the same problem. Thanks.

**Comment by varunrau** [comment]
@jinzhu where can I configure that?

**Comment by SamuelTissot** [comment]
I wrote a custom type to handle those situations. It makes it possible to use `reflect.DeepEqual` with it.

https://github.com/SamuelTissot/sqltime
