### ISSUE TITLE
db.Find(&user) to json with gin

### ISSUE THREAD

**Issue by Gnadi** [jinzhu/gorm#1297]
Hey 
I am programming a rest service with gorm so I want to GET all users as JSON.
`var users = db.Find(&models.Person{})`
`c.JSON(200, users)`

All I get with this code is a json with only one user.

Thank you

**Comment by Gnadi** [comment]
My fault right code:
`users := []models.Person{}
	db.Find(&users)
	c.JSON(200, users)`

**Comment by wilsontamarozzi** [comment]
Try this

`c.JSON(200, gin.H{"person": person})`
