### ISSUE TITLE
how to get the id of new record

### ISSUE THREAD

**Issue by pathbox** [jinzhu/gorm#1298]
Hi, guys~
When I code in ruby , I use ActiveRecord. I can do this:

```ruby

user = User.create(name: "Tom")
id = user.id
```
Then, I get the id of new user record.

I want to konw how I can do this  when I use gorm to code in Go.

**Comment by pathbox** [comment]
I find a simple way ～
links: http://stackoverflow.com/questions/28773963/golang-gorm-and-mysql-how-can-i-retrieve-instance-of-last-added-item

[links](http://stackoverflow.com/questions/28773963/golang-gorm-and-mysql-how-can-i-retrieve-instance-of-last-added-item)

**Comment by petrogdev** [comment]
This doesn't work.
The result does get saved into db, but no id is ever returned.
However, that being said, I am using mssql.uniqueIdentifier.
