### ISSUE TITLE
Get raw sql from builder?

### ISSUE THREAD

**Issue by bwiggs** [jinzhu/gorm#1302]
How can I get the generated SQL string from a SQL Builder? 

example:
```go
q := db.Model(&User{}).Where("name = ?", "jinzhu").Select("name, age, email")
// fmt.Println(q.sql) anything like this?
```

**Comment by pfzero** [comment]
I'm not sure you can see the raw string at this point, but if you're looking for debugging the queries made by gorm you can set the `DEBUG=true` env variable before starting your go program. Example as follows:

`dev_run.sh`
```shell
# enable debugging
export DEBUG=true;

# run go program by passing arguments
go run main.go $1
```

And you would start the program with `bash dev_run.sh` or `bash dev_run.sh --race`

**Comment by jinzhu** [comment]
GORM can't return the finally SQL, as GORM is using standard `sql/database` package to prevent  SQL injection, so GORM itself can't generate safe SQLs that you could use.

**Comment by oulaly** [comment]
``` go
db.Callback().Query().Register("query_scope_sql_vars", scopeStoreSqlAndVars)

func scopeStoreSqlAndVars(scope *gorm.Scope) {
	scope.DB().InstantSet("sql", scope.SQL)
	scope.DB().InstantSet("sqlVars", scope.SQLVars)
}
```

**Comment by wisecsj** [comment]
> ```go
> func scopeStoreSqlAndVars(scope *gorm.Scope) {
> 	scope.DB().InstantSet("sql", scope.SQL)
> 	scope.DB().InstantSet("sqlVars", scope.SQLVars)
> }
> 
> db.Callback().Query().Register("query_scope_sql_vars", scopeStoreSqlAndVars)
> 
> sql, ok := db.Get("sql")
> ```

not work for me ... so sad 

it returns <nil>,false

**Comment by labulaka521** [comment]
@wisecsj this code worker for me 
```go
func scopeStoreSqlAndVars(scope *gorm.Scope) {
	scope.DB().InstantSet("sql", scope.SQL)
	scope.DB().InstantSet("sqlVars", scope.SQLVars)
}
db.Callback().Query().Register("query_scope_sql_vars", scopeStoreSqlAndVars)
newdb := db.First(&product, "code = ?", "L1212")
fmt.Println(newdb.Get("sql"))
fmt.Println(newdb.Get("sqlVars"))
```
because the query callback will copy db when run execute sql
like this in source code
```go
// NewScope create a scope for current operation
func (s *DB) NewScope(value interface{}) *Scope {
	dbClone := s.clone()
        
}
````

**Comment by oulaly** [comment]
> > ```go
> > func scopeStoreSqlAndVars(scope *gorm.Scope) {
> > 	scope.DB().InstantSet("sql", scope.SQL)
> > 	scope.DB().InstantSet("sqlVars", scope.SQLVars)
> > }
> > 
> > db.Callback().Query().Register("query_scope_sql_vars", scopeStoreSqlAndVars)
> > 
> > sql, ok := db.Get("sql")
> > ```
> 
> @oulaly
> not work for me ... so sad
> 
> it returns nil,false

```go

func scopeStoreSqlAndVars(scope *gorm.Scope) {
	scope.DB().InstantSet("sql", scope.SQL)
	scope.DB().InstantSet("sqlVars", scope.SQLVars)
}

db.Callback().Create().Register("create_scope_sql_vars", scopeStoreSqlAndVars)
db.Callback().Query().Register("query_scope_sql_vars", scopeStoreSqlAndVars)
db.Callback().Update().Register("update_scope_sql_vars", scopeStoreSqlAndVars)
db.Callback().Delete().Register("delete_scope_sql_vars", scopeStoreSqlAndVars)
db.Callback().RowQuery().Register("row_query_scope_sql_vars", scopeStoreSqlAndVars)

// execute biz logic example
tempDb := db.Where('...').Find(&OneStruct)

sql, ok := tempDb.Get("sql")
```
