### ISSUE TITLE
A suggestion about document of “Model Definition”

### ISSUE THREAD

**Issue by pathbox** [jinzhu/gorm#1306]
For example:

```
type Email struct {
    ID      int
    UserID  int     `gorm:"index"` 
    Email   string  `gorm:"type:varchar(100);unique_index"` 
}

email := Email{ID: 1, UserID: 1, Email: "xxx@gmail.com"}

rs, _ := json.Marshal(email)

fmt.Println(string(rs))

the result:

{
 "ID": 1,
 "UserID": 1,
 "Emaill: "xxx@gmail.com",
}
```

But I want to get the lower case key for the json result，I need to do this:

```
type Email struct {
    ID      int        `json:"id"`
    UserID  int     `gorm:"index"json:"user_id"` 
    Email   string  `gorm:"type:varchar(100);unique_index"json:"email"` 
}

```

Then the result:

```
{
 "id": 1,
 "user_id": 1,
 "email": "xxx@gmail.com",
}
```

I try some times to find the right way, because I want the lower case key for the response json.
You can add a simple example to the document of "Model Definition", if you think it is good and useful.
It is just a suggestion.

**Comment by jinzhu** [comment]
this is related to json but not gorm.

**Comment by wk3368** [comment]
this is helpful for me.
have the  same requirement  and google a a lot to find this post.
same suggestion for add  a sample example to the document of "Model Definition" , which illustrate how gorm and json tag works together.
