### ISSUE TITLE
Eager loading of objects?

### ISSUE THREAD

**Issue by MendelGusmao** [jinzhu/gorm#131]
```go
struct Foo {
   Id    int
   Bar   Bar
   BarId int
}

struct Bar {
   Id int
}

bar := Bar{}
db.Save(&bar)

foo := Foo{Bar: bar}
db.Save(&foo)

anotherFoo := Foo{}
db.Where(&Foo{Id: foo.Id}).Find(&anotherFoo)
// anotherFoo.Bar is uninitialized
```
Is there any way to eager load a Bar when loading a Foo?
(I mean, without having to explicitly do another db.Find() for a Bar.)

Thanks!

**Comment by jinzhu** [comment]
Hi All,

We have the eager loading feature already, please checkout https://github.com/jinzhu/gorm#preloading-eager-loading

**Comment by MendelGusmao** [comment]
Great! Thanks!

**Comment by ottokart** [comment]
Does this also solve the problem, where after Save the related objects are not loaded? I'm currently using AfterCreate and AfterUpdate to solve this.
