### ISSUE TITLE
Mysql: json field automigrate not working when embedding model

### ISSUE THREAD

**Issue by rightjoin** [jinzhu/gorm#1320]
Declare a model:

```
type Address struct {
	Street string `sql:"TYPE:varchar(24)"`
}
```

Now make Address implemnet Scanner (Value and Scan) method.

Now declare another model, when stores Address in embedded json field

```
type SalesOrder struct {
      Field1 int
      ShipTo *Address `sql:"TYPE:json"`
      FieldN int
}
```

When I run automigrage to create these tables, I find that datatype of ShipTo field in SalesOrder table is varchar(24) [it should be json]

I figured it down to model_struct.go, line number 195 where it is picking the TagSetting from the last embedded field. However, why this loop was written (@ line 193), I am unable to gather.

**Comment by 0xdeafcafe** [comment]
+1

**Comment by jinzhu** [comment]
Fixed, Thank you for your report.
