### ISSUE TITLE
Foerign key by annotations vs Foerign key by "AddForeignKey"

### ISSUE THREAD

**Issue by rennanfelipe** [jinzhu/gorm#1322]
Hello everyone!

What's the difference between use annotations and use the method "AddForeignKey"?

By annotation example: 
```golang
type User struct {
  gorm.Model
  Profile   Profile `gorm:"ForeignKey:ProfileID"`
  ProfileID int
}

type Profile struct {
  gorm.Model
  Name string
}
```

By method example:
```golang
db.Model(&User{}).AddForeignKey("profile_id", "profiles(id)", "RESTRICT", "RESTRICT")
```

**Comment by zardak** [comment]
Tags affect query construction, processing of associated models and auto-migrations, while method does only what it states.
