### ISSUE TITLE
Models + Relationships not behaving as expected

### ISSUE THREAD

**Issue by JoeFerrucci** [jinzhu/gorm#1323]
I've tried several variations of these 3 structs, but nothing is working. 
I want to be able to get a Contact with all of it's Emails and PhoneNumbers.
Or, give me all Emails for this Contact.

```go 
type Contact struct {
	gorm.Model
	Emails       []Email
	PhoneNumbers []PhoneNumber
}
 
type PhoneNumber struct {
	gorm.Model
	ContactID uint
	Label     string
	Value     string
}
 
type Email struct {
	gorm.Model
	ContactID uint
	Label     string
	Value     string
}
```

Also, I followed along with this by @svett : http://blog.ralch.com/tutorial/golang-object-relation-mapping-with-gorm/ … but `db.Create(&sampleCompany)` only creates a row in companies tables, but nothing in employees or companies. 

What am I doing wrong?

**Comment by jinzhu** [comment]
Could submit a executable script that could reproduce your issue by following https://github.com/jinzhu/gorm/blob/master/CONTRIBUTING.md#executable-script-template ?

**Comment by JoeFerrucci** [comment]
The issues is: the tables being created by GORM are not correct -- for instance, `contacts` table corresponding to the `Contact` struct. 

Surely I am doing something wrong. 

```go
package main

import (
    _ "github.com/go-sql-driver/mysql"
    "github.com/jinzhu/gorm"
)

var db *gorm.DB

type Contact struct {
	gorm.Model
	Emails       []Email
	PhoneNumbers []PhoneNumber
}
 
type PhoneNumber struct {
	gorm.Model
	ContactID uint
	Label     string
	Value     string
}
 
type Email struct {
	gorm.Model
	ContactID uint
	Label     string
	Value     string
}

func init() {
    var err error
    db, err = gorm.Open("mysql", "user:password@/dbname?charset=utf8&parseTime=True")
    if err != nil {
        panic(err)
    }
    db.LogMode(true)

    db.CreateTable(&Address{})
    db.CreateTable(&Company{})
    db.CreateTable(&Employee{})
}

func main() {
    init()
	
	// Phone
	phone1 := PhoneNumber{
		Label: "Home",
		Value: "505-555-1212",
	}
	db.Save(&phone1)

	// Phone
	phone2 := PhoneNumber{
		Label: "Work",
		Value: "515-444-9090",
	}
	db.Save(&phone2)

	// Email
	email1 := Email{
		Label: "Home",
		Value: "lucy@gmail.com",
	}
	db.Save(&email1)

	// Email2
	email2 := Email{
		Label: "Work",
		Value: "gee@gmail.com",
	}
	db.Save(&email2)

	// Contact
	contact := Contact{
		Emails:       []Email{email1, email2},
		PhoneNumbers: []PhoneNumber{phone1, phone2},
	}
	db.Save(&contact)

	// Find Contacts
	contacts := []Contact{}

	// Results
	fmt.Println("\ncontacts:\n", db.Find(&contacts))
}

```

**Comment by zardak** [comment]
Data persisted to the DB looks correct. Your record fetching code has some mistakes:
First, gorm won't fetch associations by default, instead you have to specify needed associations when querying for records ([docs on preloading](http://jinzhu.me/gorm/crud.html#preloading-eager-loading)).
Second is that `db.Find(&contacts)` returns `*gorm.DB` instance, not the records themselves.

So, you need to change this line
```go
fmt.Println("\ncontacts:\n", db.Find(&contacts))
```
To
```go
// Fetch all contacts together with their associated records
db.Preload("Emails").Preload("PhoneNumbers").Find(&contacts)
// Print contacts, not the database instance
fmt.Println("\ncontacts:\n", contacts)
```
Lastly, get a habit of checking for errors in Go and consider using stackoverflow for usage questions next time.

**Comment by JoeFerrucci** [comment]
Why don't the tables show the relations? Also, what would happen if I didn't have `ContactID` in `Email` and `PhoneNumber`? In what way can I accomplish the same effect but without `ContactID`?

Re SO: will do next time! Thanks for taking the time to help me here though.
