### ISSUE TITLE
Why is there no error returned in functions such as CreateTable/Create?

### ISSUE THREAD

**Issue by t57root** [jinzhu/gorm#1329]
If there's an error encountered while executing these functions, the code couldn't tell if there's such  situation happened:
1. make the database unwritable:
shell# chattr +i test.db
2. and then all the operations on this database won't be successful. How could I get the error with the following code?
gorm.Open("sqlite3", "test.db")
db.AutoMigrate(&Product{})
db.CreateTable(&Product{})
db.Create(&Product{Code: "L1212", Price: 1000})

**Comment by TeemoWan** [comment]
+1

**Comment by zardak** [comment]
Due to chaining nature of gorm api, the error is always stored in `Err` field  of `gorm.DB` instance.
https://github.com/jinzhu/gorm/blob/45fc640bf3042a9b424f7cd00ec096d919b2009f/main_test.go#L194-L196
