### ISSUE TITLE
Regression handling blank values

### ISSUE THREAD

**Issue by flebel** [jinzhu/gorm#1330]
89f6d74b5ebab61a964b7a69c865a16cf9f24821 introduces a regression.

`db.Debug().Where("id = ?", id).First(u)`, generates this SQL:
```
SELECT * FROM "users"  WHERE "users"."id" = '00000000-0000-0000-0000-000000000000' AND ((id = '27768944-9d9b-4fd2-8950-a1158391f76d')) ORDER BY "users"."id" ASC LIMIT 1
```
given the `id` field defined as:
```
ID                            uuid.UUID       `gorm:"primary_key;type:uuid;default:uuid_generate_v4()" json:"id"`
```

Reverting to its parent commit fixes the regression and generates the expected SQL statement:
```
SELECT * FROM "users"  WHERE (id = '27768944-9d9b-4fd2-8950-a1158391f76d') ORDER BY "users"."id" ASC LIMIT 1
```

**Comment by jinzhu** [comment]
Hi @flebel 

Sorry for the problem, just fixed that.

**Comment by jinzhu** [comment]
Thank you for your report.
