### ISSUE TITLE
Documentation on how the database pool works?

### ISSUE THREAD

**Issue by ivoras** [jinzhu/gorm#1334]
Hi,

What happens if the connection pool is overloaded? E.g. I set the maximum size of the pool to 10 with        `db.DB().SetMaxOpenConns(10)` but the web site gets 100 simultaneous users?

Will it delay all operations which cannot get a working connection? Will it return an error? Will it crash?

**Comment by jinzhu** [comment]
Hello, 

GORM is using golang's standard database lib's db pool, so works exactly like how the standard lib works. (Will it delay all operations which cannot get a working connection)
