### ISSUE TITLE
[Question]: How deal with updating circular belongs-to relations.

### ISSUE THREAD

**Issue by matsch01** [jinzhu/gorm#1337]
Below Account has a belongs-to relationship to Manager and SubManager. In addition, SubManager also has a belongs-to relationship to Manager.

The issue I'm having is that when trying to update Manager through the Account using 'save_associations', the change is reverted when the Account and SubManager reference same Manager. First a Manager update is issued via the Account with the new value(s), but it's reverted when Manager is updated a second time for the SubManager with the original values.

Is this expected behavior?  How can I avoid this?

```
type Account struct {
	AccountId                int                 `json:"account_id" gorm:"primary_key"`
	Manager                  Manager             `json:"manager" gorm:"ForeignKey:ManagerRefer"`
	ManagerRefer             int                 `json:"manager_id" gorm:"not null;column:manager_id"`
	SubManager               SubManager          `json:"sub_manager" gorm:"ForeignKey:SubManagerRefer"`
	SubManagerRefer          int                 `json:"sub_manager_id" gorm:"column:sub_manager_id"`
}

type SubManager struct {
	SubManagerId int     `json:"sub_manager_id" gorm:"primary_key"`
	Manager      Manager `json:"manager" gorm:"ForeignKey:ManagerRefer"`
	ManagerRefer int     `json:"manager_id" gorm:"not null;column:manager_id"`
	Name         string  `json:"name" gorm:"not null"`
}

type Manager struct {
	ManagerId int       `json:"manager_id" gorm:"primary_key"`
	Name      string    `json:"name" gorm:"not null"`
}
```

//Steps to reproduce
//1. get account from database (note that the account and submanger both reference same Manager)
```
account := GetAccountFromDB() //this returns Account{AccountId:1, Manager : {ManagerId:1, Name:"CATS"}, ManagerRefer : 1, SubManager: {SubManagerId:1, Name:"SUB_CATS", Manager : {ManagerId:1, Name:"CATS"}, ManagerRefer:1}, SubManagerRefer : 1} 
```

//2. update manager code
```
account.Manager.Name = "DOGS"
```

//3. save account with 'save_associations' == true
```
db.Debug().Set("gorm:save_associations", true).Save(&account)
```

//Abridged log of issued sql statements 
//1. first gorm issues Manager update for manager associated to account
[35m(C:/workspace/accounts/src/accounts/account.go:457)[0m 
[33m[2017-02-03 09:01:17][0m  [36;1m[2.00ms][0m  UPDATE "manager" SET "name" = 'DOGS', WHERE "manager"."manager_id" = '1'

//2. then gorm issues Manager update for manager associated to SubManager (setting Name back to original value for Manager 1)
[35m(C:/workspace/accounts/src/accounts/account.go:457)[0m 
[33m[2017-02-03 09:01:17][0m  [36;1m[2.00ms][0m  UPDATE "manager" SET "name" = 'CATS', WHERE "manager"."manager_id" = '1'

Possible hacky solution: Before executing update, check if Account and SubManager reference same Manager. If so, sync them both to the new Manager before updating. The updated Manager could be the Account's Manager or the SubManager's Manager.

**Comment by jinzhu** [comment]
Please follow https://github.com/jinzhu/gorm/blob/master/.github/ISSUE_TEMPLATE.md to reopen another issue if it is still a problem for you.
