### ISSUE TITLE
Alter size of varchar

### ISSUE THREAD

**Issue by hamid-elaosta** [jinzhu/gorm#1338]
It appears that gorm does not/can not alter the size of a varchar according to the annotation;

If I start with this
```
type User struct {
...
Token        string `gorm:"type:varchar(64);not_null"`
...
}
```
then alter to this:

```
type User struct {
...
Token        string `gorm:"type:varchar(256);not_null"`
Other        string `gorm:"type:varchar(64);not_null"`
...
}
```

My log shows that the `Other` column is added, but the `Token` column is not altered to the new length of 256.

Is there some way to encourage gorm to do so; in order not to have to perform the alter manually?

**Comment by zardak** [comment]
As per http://jinzhu.me/gorm/database.html#migration
> AutoMigrate will ONLY create tables, missing columns and missing indexes, and WON'T change existing column's type or delete unused columns to protect your data.

**Comment by hamid-elaosta** [comment]
@zardak Seems reasonable. Thanks
