### ISSUE TITLE
Renaming column with automigrate

### ISSUE THREAD

**Issue by adriendomoison** [jinzhu/gorm#1344]
Hello,

I tried renaming a column with AutoMerge using `gorm:"column:my_column_name"` on my Go Struct but a new column was created instead.
I know it is written that AutoMerge doesn't delete anything, so do you consider renaming a deletion?

Here is what I did :

```
type User struct {
	gorm.Model
	Email           string 		`gorm:"not null;size:50;unique_index"`
	Password        string 		`gorm:"not null;size:255"`
	AccountStatusID string 		`gorm:"size:255"`
}


type AccountStatus struct {
	Name string `gorm:"primary_key;size:255"`
}
```

I had the columns "email", "password" and "account_status_id".
I wanted to rename "account_status_id" to "account" :

```
type User struct {
	gorm.Model
	Email           string 		`gorm:"not null;size:50;unique_index"`
	Password        string 		`gorm:"not null;size:255"`
	AccountStatusID string 		`gorm:"column:status;size:255"`
}


type AccountStatus struct {
	Name string `gorm:"primary_key;size:255"`
}
```

And I have now the columns "email", "password", "account_status_id" and "account".

It might also be specific to "has on" relationship ?

**Comment by jinzhu** [comment]
GORM doesn't support rename column with auto migration
