### ISSUE TITLE
查询多条数据时，如何指定表名

### ISSUE THREAD

**Issue by jatlee** [jinzhu/gorm#1345]
查询多条数据时，如何指定表名
func (p *PlayerInfo) TableName() string {
	return "player_info_for_" + p.CompanyIdent
}

var players []PlayerInfo
DB.Where("account = ?", ip).Find(&players)
类似这样，如果指定CompanyIdent的值

**Comment by t2krew** [comment]
@jatlee 你好，请问你说的这种情况如果解决的？
