### ISSUE TITLE
A particular column value is skipping while inserting a new record into DB

### ISSUE THREAD

**Issue by ankitvarshney1490** [jinzhu/gorm#1349]
I have a table contains multiple columns, but following column is getting (if it contains value 0) skip while inserting a new record into database.If following field contains value 1 then the column is not getting skip.
---
Active uint8 `sql:"TYPE:tinyint(1) unsigned;not null;DEFAULT:'1'" json:"active"`
---

eg.
 Suppose table t1 contains 4 column(c1,c2,c3, active) 
 1) If active contains value 0.  Following query is getting fired
 insert into 'table' (c1,c2,c3) values ('v1','v2','v3').
 2)If active contains value 1.  Following query is getting fired
 insert into 'table' (c1,c2,c3, active) values ('v1','v2','v3', '1').

**Comment by jinzhu** [comment]
Please follow https://github.com/jinzhu/gorm/blob/master/.github/ISSUE_TEMPLATE.md to reopen another issue if it is still a problem for you.
