### ISSUE TITLE
Concurrent Column Access 

### ISSUE THREAD

**Issue by zeemetz** [jinzhu/gorm#1351]
Dear Jinzhu,

How can i do wallet/balance management on database with concurrent access, lets say to make: lastBalance = lastBalance - Nominal
able to perform in concurrent access (Optimistic Locking is what i look for)

Thank You,
Regards

**Comment by jinzhu** [comment]
like this? `DB.Model(&product).UpdateColumn("quantity", gorm.Expr("quantity - ?", 1))`
