### ISSUE TITLE
rows.Scan cannot read datetime fields

### ISSUE THREAD

**Issue by smousa** [jinzhu/gorm#1361]
```go
rows, err := db.Table("tablename").Select("id, max(end_time) as max_time").Group("id").Having("max_time > ?", datetime).Rows()

for rows.Next() {
    var (
        id int
        maxtime time.Time
    )
    rows.Scan(&id, &maxtime)
    ....
}
```

When I do this, the maxtime field does not have a value.  I can only read the correct value when the `maxtime` is a string, which I have to parse into the time.Time var.  Am I doing this incorrectly?

**Comment by jbfm** [comment]
`Scan` is part of the `Scanner` interface in the [database/sql](https://golang.org/pkg/database/sql/#Scanner) package of Go, if this is an issue it's probably not related to Gorm.

**Comment by jbfm** [comment]
`Scan` is part of the `Scanner` interface in the [database/sql](https://golang.org/pkg/database/sql/#Rows.Scan) package of Go, and has nothing to do with `Find`. `Scan` is used to parse values from the SQL database into Go variables/structs.

**Comment by smousa** [comment]
Gotcha.  Thanks for the clarification.

**Comment by jinzhu** [comment]
are you using mysql?

before set `parseTime` to true refer: https://github.com/go-sql-driver/mysql#parsetime

**Comment by smousa** [comment]
I am using sqlite
