### ISSUE TITLE
DELETE with composite key empties table

### ISSUE THREAD

**Issue by ssimono** [jinzhu/gorm#1363]
Hello, I noticed a quite dangerous behaviour when deleting record using a composite primary key.

1. Create a *test.db* sqlite database

```sql
CREATE TABLE `memberships` (
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `group_id`)
);

INSERT into `memberships` VALUES
(1,1),(1,2),(1,3),(2,1),(2,2),(2,3);
```

2. Create a *main.go* script from [executable script template](https://github.com/jinzhu/gorm/blob/master/CONTRIBUTING.md#executable-script-template)

```go
func main() {

  type Membership struct {
    gorm.Model
    UserID  int64 `gorm:"column:user_id"`
    GroupID int64 `gorm:"column:group_id"`
  }

  db.Unscoped().Delete(&Membership{UserID: 1, GroupID: 3})
}
```

3. Run it: `go run main.go`

**BUG** It executes `DELETE FROM memberships` and rips off the entire table.

The doc says

> WARNING When delete a record, you need to ensure it's primary field has value, and GORM will use the primary key to delete the record, if primary field's blank, GORM will delete all records for the model

And in this case the primary key is clearly not blank.

**Comment by Ganitzsh** [comment]
You didn't specify the `primary_key` flag on your model.

As stated in the documentation, you have to tell gorm that this model uses `UserID` and `GroupID` as composite key. Like this:

```go
type Membership struct {
  gorm.Model
  UserID  int64 `gorm:"column:user_id;primary_key"`
  GroupID int64 `gorm:"column:group_id;primary_key"
}
```

**Comment by ssimono** [comment]
Hello,

Thanks a lot, I was indeed missing the `primary_key` tag. It works as expected now!
