### ISSUE TITLE
Unscoped() is not working for nested structure.

### ISSUE THREAD

**Issue by pragya-techahead** [jinzhu/gorm#1368]
I am using the following structures to save the user data. 
type User struct {
	gorm.Model
        Name                string
	Emails                []UserEmail
	
}
type UserEmail struct{
gorm.Model
UserId       int
Email       string
}
When I run the following code the I thought its behavior will be as follows -
func (u *User) Save() error {
	
	err := DB.Unscoped().Save(&u).Error
//expected behavior
SELECT * FROM `emails`  WHERE  `emails`.`id` = '1'
//what i got is 
SELECT * FROM `emails`  WHERE `emails`.deleted_at IS NULL AND `emails`.`id` = '1'
}

This cause a problem because in our 'emails' table 'deleted_at' has the entry as '0000-00-00 00:00:00' for id 1.

So I got the following error -
 Error 1062: Duplicate entry '1' for key 'PRIMARY' 

Please help me to resolve this.  
Thanks in advance

**Comment by jinzhu** [comment]
Please follow https://github.com/jinzhu/gorm/blob/master/.github/ISSUE_TEMPLATE.md to reopen another issue if it is still a problem for you.

**Comment by sijad** [comment]
I had same issue, gone by adding `association_autoupdate:false` tag to the association.
