### ISSUE TITLE
time.Time as composite primary key has to be set to not null manually

### ISSUE THREAD

**Issue by franzwilhelm** [jinzhu/gorm#1369]
When I try using time.Time as part of a primary key I get this error from mySQL: (Error 1171: All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead). When adding `gorm:"not null;primary_key"` it works. 

	EmployeeID uint      `gorm:"primary_key"`
	Day        time.Time `gorm:"primary_key"`

**Comment by jinzhu** [comment]
Please follow https://github.com/jinzhu/gorm/blob/master/.github/ISSUE_TEMPLATE.md to reopen another issue if it is still a problem for you.
