### ISSUE TITLE
"use of package mssql without selector" "mssql redeclared in this block"

### ISSUE THREAD

**Issue by pathaugen** [jinzhu/gorm#1371]
In the file: gorm/dialects/mssql/mssql.go

`func init() {
	gorm.DefaultCallback.Create().After("gorm:begin_transaction").Register("mssql:set_identity_insert", setIdentityInsert)
	gorm.RegisterDialect("mssql", &mssql{})
}

type mssql struct {
	db *sql.DB
	gorm.DefaultForeignKeyNamer
}`

When building, get:
"use of package mssql without selector"
"mssql redeclared in this block"

Complaining about this line specifically:
`gorm.RegisterDialect("mssql", &mssql{})`

**Comment by jinzhu** [comment]
We should fixed all issues for mssql, if you still have any problem, please create a new issue.

Thank you.
