### ISSUE TITLE
Why there's not function Sum?

### ISSUE THREAD

**Issue by Codefor** [jinzhu/gorm#1373]

**Comment by Codefor** [comment]
?

**Comment by jinzhu** [comment]
use `db.Model(&User{}).Select("sum(age)").Scan()`

**Comment by sunilplivo** [comment]
With Scan(), can I directly read the SUM data into a int/float variable?
It is asking me to use a struct as destination.

**Comment by chenyu1990** [comment]
> use `db.Model(&User{}).Select("sum(age)").Scan()`

result := make(map[string]interface{})
db.Select(selectString).Scan(&result)

我想使用灵活的map[string]interface{}，这样不用在每个Sum都重新构造结构体

**Comment by jinzhu** [comment]
> With Scan(), can I directly read the SUM data into a int/float variable? It is asking me to use a struct as destination.

Supported in V2

> 我想使用灵活的map[string]interface{}，这样不用在每个Sum都重新构造结构体

Supported in V2

**Comment by chenyu1990** [comment]
谢谢
