### ISSUE TITLE
Crashes when debugging in Visual Studio Code

### ISSUE THREAD

**Issue by Acebond** [jinzhu/gorm#1374]
Whenever I try run the Visual Studio Code debugger with GORM in my project, it crashes instantly on the gorm.Open function with the error "signal arrived during external code execution".

Here is a minimal example
```
package main

import (
	"log"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var (
	db *gorm.DB
)

func main() {
	var err error
	db, err = gorm.Open("sqlite3", "app.db")
	if err != nil {
		log.Fatal(err.Error())
	}
	defer db.Close()
}
```

Full Error:

> API server listening at: 127.0.0.1:30512
> Exception 0xc0000005 0x8 0x7622f8 0x7622f8
> PC=0x7622f8
> signal arrived during external code execution
> github.com/mattn/go-sqlite3._Cfunc_sqlite3_close_v2(0x13048a8, 0x0)
> 	github.com/mattn/go-sqlite3/_obj/_cgo_gotypes.go:450 +0x50
> github.com/mattn/go-sqlite3.(*SQLiteConn).Close.func1(0x13048a8, 0x0)
> 	C:/Users/Ace/Documents/GoProjects/src/github.com/mattn/go-sqlite3/sqlite3.go:631 +0x67
> github.com/mattn/go-sqlite3.(*SQLiteConn).Close(0xc04211d860, 0x58cd1e, 0xc042035c60)
> 	C:/Users/Ace/Documents/GoProjects/src/github.com/mattn/go-sqlite3/sqlite3.go:631 +0x47
> database/sql.(*driverConn).finalClose.func2()
> 	C:/Go/src/database/sql/sql.go:440 +0x50
> database/sql.withLock(0x763f20, 0xc042123110, 0xc042035cd8)
> 	C:/Go/src/database/sql/sql.go:2545 +0x6c
> database/sql.(*driverConn).finalClose(0xc042123110, 0xc042035df0, 0x42035de8)
> 	C:/Go/src/database/sql/sql.go:442 +0x160
> database/sql.(finalCloser).(database/sql.finalClose)-fm(0xc04213a028, 0xc0421030b0)
> 	C:/Go/src/database/sql/sql.go:537 +0x36
> database/sql.(*DB).Close(0xc04213a000, 0x681df0, 0xc042062000)
> 	C:/Go/src/database/sql/sql.go:644 +0x304
> github.com/jinzhu/gorm.(*DB).Close(0xc04213c000, 0x1, 0x1)
> 	C:/Users/Ace/Documents/GoProjects/src/github.com/jinzhu/gorm/main.go:96 +0xca
> main.main()
> 	C:/Users/Ace/Documents/GoProjects/src/minumalExample/main.go:21 +0x280
> goroutine 17 [syscall, locked to thread]:
> runtime.goexit()
> 	C:/Go/src/runtime/asm_amd64.s:2197 +0x1
> rax     0x0
> rbx     0x3
> rcx     0x19c
> rdi     0x13048a8
> rsi     0x1305940
> rbp     0x1305b78
> rsp     0xb0fcb8
> r8      0x2
> r9      0x1000
> r10     0xc042017350
> r11     0x68bff2
> r12     0x40
> r13     0x4
> r14     0x0
> r15     0xd6
> rip     0x7622f8
> rflags  0x10202
> cs      0x33
> fs      0x53

I'm using Go 1.8, VS Code 1.10.1 and all go packages up to date. This has always been happening to me, even when I was using Go version 1.7. Im on Windows 10 x64.

**Comment by zardak** [comment]
This is an issue with `cgo` and `delve`, not gorm itself.
