### ISSUE TITLE
Where Association

### ISSUE THREAD

**Issue by theobouwman** [jinzhu/gorm#1377]
```
var mgroups []ModuleLocation
db.Not(ModuleLocation{
   Group: Group{
      Community:true
   }
}).Find(&mgroups)
```
I want to select every ModuleLocation where to related group's community value is nog true OR the ModuleLocations where the group is not set.
The code above results in a error:
```
[2017-03-05 17:57:00]  sql: converting Exec argument #0's type: unsupported type models.Group, a struct 
```
Why is that?

**Comment by jinzhu** [comment]
Please follow https://github.com/jinzhu/gorm/blob/master/.github/ISSUE_TEMPLATE.md to reopen another issue if it is still a problem for you.
