### ISSUE TITLE
db.Delete causes no error if it fails

### ISSUE THREAD

**Issue by deltaskelta** [jinzhu/gorm#1380]
I have a situation that was hard to track down in my code becuase db.Error was nil when delete failed. the primary key was 0 and when it was deleted like this...

```
id := 0
if err := db.Where("user_id = ?", &user.ID).Delete(&thing, id).Error; err != nil {
	fmt.Println(err)
}
```

Is this by design, and if so, what is the purpose?

**Comment by jbfm** [comment]
The query was probably successful, you got not SQL errors, and there's no way Gorm could know how many rows you expect to be deleted. 0 rows deleted is still a valid amount of rows to delete.

**Comment by jinzhu** [comment]
There is a `RowsAffected` column in the result, you could get how many rows deleted from that.

**Comment by cmorent** [comment]
Any update here?

**Comment by gold-kou** [comment]
like this

```
result := r.db.Where("member_id = ?", task.MemberID).Delete(task)
if result.RowsAffected == 0 {
	return errors.New("delete failed")
}
```
