### ISSUE TITLE
What's the tag for varchar charset ? 对应varchar charset的tag是什么？

### ISSUE THREAD

**Issue by beef9999** [jinzhu/gorm#1381]
> `name` varchar(16) CHARACTER SET ascii DEFAULT NULL

> `gorm:"type:varchar(16)" sql:"DEFAULT:null`

What is the corresponding struct tag for CHARACTER SET ascii ?

**Comment by beef9999** [comment]
Answer my own question, it should be:

> gorm:"type:varchar(16) CHARACTER SET ascii" sql:"DEFAULT:null

By the way, why the `DEFAULT` tag is positioned in sql lib, not gorm lib?

**Comment by jinzhu** [comment]
> By the way, why the DEFAULT tag is positioned in sql lib, not gorm lib?　

Both works.
