### ISSUE TITLE
继承BaseModel的方法会提示 Error 1146: Table 'gin.base_models' doesn't exist

### ISSUE THREAD

**Issue by yingce** [jinzhu/gorm#1382]
我需要定义一个BaseModel

type BaseModel struct {
	gorm.Model
}

func (m *BaseModel) Save() error {
	return DB.Save(&m).Error
}

type User struct {
	BaseModel
}

user := &User{}
user.Save()
=> Error 1146: Table 'gin.base_models' doesn't exist.

我该怎么继承一些上层struct定义的方法?

或者我该怎么回去BaseModel的tablename呢？

**Comment by apocelipes** [comment]
@yingce 
首先是否有比较完整的例子来复现该问题，
其次，在
`return DB.Save(&m).Error`
这句中m的类型是*BaseModel，使用&m是否正确？

**Comment by yingce** [comment]
@apocelipes 我理解m 是BaseModel; 但是我需要定义一个基础的model 别的struct来继承他的一些方法和字段
