### ISSUE TITLE
请教一下，在beego 里使用grom，怎么定义连接数据库的全局变量？每次用到的地方都要重新定义连接吗？

### ISSUE THREAD

**Issue by ghn645568344** [jinzhu/gorm#1386]
RT
在beego 里使用grom，怎么定义连接数据库的全局变量？每次用到的地方都要重新定义连接吗？

**Comment by awh521** [comment]
你可以定义个包,在包里声明个全局变量（如DB），init函数里初始化DB，每次用到导入包，直接packagename.DB。我是这样用的

**Comment by wingcd** [comment]
直接在包里面定义一个方法，每次去new一个把，这样好用上连接池。不过beego里面不是自带有orm嘛

**Comment by ghn645568344** [comment]
@awh521 调通了，谢谢了

**Comment by ghn645568344** [comment]
@wingcd beego自带的orm 没有gorm 好用呀
