### ISSUE TITLE
当 record not found  时 db.NewRecord() 返回 false.

### ISSUE THREAD

**Issue by heramerom** [jinzhu/gorm#1387]
不是应该返回 true 的吗？

**Comment by jinzhu** [comment]
NewRecord 会判断主键存在不存在来返回 true、false

**Comment by heramerom** [comment]
你好，下面是我做的一个测试。

第一次执行
![2017-03-20 11 33 33](https://cloud.githubusercontent.com/assets/4046709/24128465/1b0fca2a-0e17-11e7-8113-669101a1c4dd.png)

第二次执行
![2017-03-20 11 33 56](https://cloud.githubusercontent.com/assets/4046709/24128482/2c917122-0e17-11e7-9a25-6cf97e97e938.png)

按道理来说第一次调用的时候不应该返回true的吗？为什么都返回了false。
是我什么地方写错了吗

**Comment by jinzhu** [comment]
NewRecord 判断逻辑比较简单，只是判断 *主键存在不存在* 来返回 true、false

而你的 ID 都存在的。。。你需要用 First查询一下，看看这个数据在数据库里存在不存在

**Comment by heramerom** [comment]
可能是我理解错了。

我把LogModel打开，发现NewRecord不会查数据库的，

那这样NewRecord只是判断model的主键有没有赋值？
