### ISSUE TITLE
Documentation should say that struct fields need to be exported

### ISSUE THREAD

**Issue by deltaskelta** [jinzhu/gorm#1392]
I spent quite a while trying to chase down the reason why I was having errors and it was because the struct fields were note exported (capitalized)

```
// BAD
type Bad struct {
    gorm.Model
    title string
}

//GOOD
type Good struct {
    gorm.db
    Title string 
}
```

**Comment by jbfm** [comment]
This is a Go thing and not a Gorm thing, reflection works on exported fields, and nothing else.

**Comment by deltaskelta** [comment]
Ok, I see. thanks
