### ISSUE TITLE
Does .Raw() prevent SQL injection?

### ISSUE THREAD

**Issue by JonHMChan** [jinzhu/gorm#1393]
Reading https://github.com/jinzhu/gorm/issues/152#issuecomment-47306769, it's stated that GORM uses placeholder parameters, but make exceptions for methods that do not have them built in.

`func (s *DB) Raw(sql string, values ...interface{}) *DB` seems to also support parameters, but it's unclear to me whether this has the same SQL injection protection as the other methods. Which is the case? Either way, would also warrant update to the documentation.

**Comment by tsirolnik** [comment]
Seems like it doesn't, though I'm not 100% sure
```go
// main.go
// Raw use raw sql as conditions, won't run it unless invoked by other methods
//    db.Raw("SELECT name, age FROM users WHERE name = ?", 3).Scan(&result)
func (s *DB) Raw(sql string, values ...interface{}) *DB {
	return s.clone().search.Raw(true).Where(sql, values...).db
}

// search.go
func (s *search) Where(query interface{}, values ...interface{}) *search {
	s.whereConditions = append(s.whereConditions, map[string]interface{}{"query": query, "args": values})
	return s
}
```

**Comment by jinzhu** [comment]
> func (s *DB) Raw(sql string, values ...interface{}) *DB seems to also support parameters, but it's unclear to me whether this has the same SQL injection protection as the other methods. 

Yes, also prevent SQL injection for parameters,  but not the SQL

**Comment by Codefor** [comment]
However, the debug generated sql output to console is not valid.

**Comment by jinzhu** [comment]
> However, the debug generated sql output to console is not valid

This is not the exactly SQL that run in db server, it is just formatted for reference, GORM using golang std sql/database package to run the SQL, and can't get the exactly SQL.

**Comment by g10guang** [comment]
I wonder how does gorm prevent SQL injection.
