### ISSUE TITLE
mssql: 'Invalid column name' error, on valid column name; still executes query

### ISSUE THREAD

**Issue by LuisBosquez** [jinzhu/gorm#1395]
I'm using LogMode to see the T-SQL that gets generated. The line that gets executed in orm.go:71 is this:
`db.Where("UserID = ?", 2).First(&task)`

After executing, it prints this error:
`[35m(C:/Projects/tmp/go-sample/orm.go:71) mssql: Invalid column name 'UserID'.]`

Right afterwards, it still executes the correct query:
`[35m(C:/Projects/tmp/go-sample/orm.go:71) SELECT * FROM "tasks"  WHERE "tasks"."deleted_at" IS NULL AND ((UserID = '2')) ORDER BY "tasks"."id" ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY]`

**Comment by jbfm** [comment]
I tried this out as well, it seems the printed error is simply the result from the executed query. As in "This error came from this query".

If I run the generated query manually I get the same error. The confusion here probably comes from the print order.

**Comment by jinzhu** [comment]
Does this works? `db.Where("user_id = ?", 2).First(&task)`
