### ISSUE TITLE
cannot connect the database when used with pgbouncer

### ISSUE THREAD

**Issue by msean** [jinzhu/gorm#1396]
Before I use pgbouncer,It connect normally,but I just modify the default port(6543) that pgbouncer used,It occur error:
`pq: Unsupported startup parameter: extra_float_digits`
my code:
```
import (
	"github.com/jinzhu/gorm"
	"fmt"
	_ "github.com/jinzhu/gorm/dialects/postgres"
)


func main() {
	db, err := gorm.Open("postgres", "postgres://***:***@192.168.1.170:6543?sslmode=disable")
	if err != nil{
		fmt.Println("Fail to connect the database:",err)
	}else{
		fmt.Println("gorm is already connect",db)
	}
}
```
I can connect with the db on Navicat used with the port(6543).

first,I doute it is the pq  lib result this error.But It can connect the db use the test code:
```
import (
	"database/sql"
	_ "github.com/lib/pq"
	"fmt"
)

func main() {
	db,err := sql.Open("postgres", "postgres://***:***@192.168.1.170:6543/***?sslmode=disable")
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println("here",db)
}
```

**Comment by jinzhu** [comment]
http://lists.pgfoundry.org/pipermail/pgbouncer-general/2008-November/000301.html

**Comment by msean** [comment]
Thank you.It should be configured in the pgboucer.ini:
`ignore_startup_parameters = extra_float_digits`

**Comment by tarasmatsyk** [comment]
Gorm [uses](https://github.com/jinzhu/gorm/blob/master/dialects/postgres/postgres.go#L10) `lib/pq` which hardcodes `extra_float_digits` as [a parameter](https://github.com/lib/pq/issues/475).

I have not found a solution yet, but it does not look like an issue is going to be closed soon. Will post an update if there is a fix available.

**Comment by vladget** [comment]
Right, Issue is in lib/pq.
