### ISSUE TITLE
composite primary key with auto_increment

### ISSUE THREAD

**Issue by rayunstop** [jinzhu/gorm#1397]
The struct:
```golang
type Account struct {
	ID int `gorm:"AUTO_INCREMENT"`
	Username int    `gorm:"primary_key"`
	Company  string `gorm:"primary_key"`
	Server   string `gorm:"primary_key"`
	Age      int
}
```
### call gormDb.AutoMigrate(&Account{})
and i see the sql that create the table:

### CREATE TABLE "accounts" ("id" integer,"username" integer primary key autoincrement,"company" varchar(255),"server" varchar(255),"age" integer )

Why the colunm 'username' describe as autoincrement and id isn't?

**Comment by apelisse** [comment]
Probably related to #1037.

What dialect are you using? Not sure it matters, but ...

At least in sqlite, `AUTO_INCREMENT` needs to come after `PRIMARY KEY`. 
https://www.sqlite.org/syntax/column-constraint.html

**Comment by jinzhu** [comment]
I think you are using sqlite, just like @apelisse said, sqlite doesn't support that.

**Comment by rayunstop** [comment]
Yes, I used sqlite like that way. Thanks.
