### ISSUE TITLE
Plunk returns partial result

### ISSUE THREAD

**Issue by nodestory** [jinzhu/gorm#1398]
This is similar to another issue [find return half result](https://github.com/jinzhu/gorm/issues/1342) which is already solved in this [commit](https://github.com/jinzhu/gorm/commit/23abd03a95a16de0ef2d559979ead26b2a3cce66).

After iterating `sql.rows`, it is necessary to check if there is any error occurred.

The same problem appears in [`plunk`](https://github.com/jinzhu/gorm/blob/master/scope.go#L928), so the fix also applies here.

```
for rows.Next() {
    elem := reflect.New(dest.Type().Elem()).Interface()
    scope.Err(rows.Scan(elem))
    dest.Set(reflect.Append(dest, reflect.ValueOf(elem).Elem()))
}

if err := rows.Err(); err != nil {
    scope.Err(err)
}
```

**Comment by jinzhu** [comment]
Thank you for your report
