### ISSUE TITLE
The deleted column is automatically processed when executing a query?

### ISSUE THREAD

**Issue by beef9999** [jinzhu/gorm#1409]
I think GORM is trying to be too clever here.

A normal db.Find() query would surprisingly filter out all the "deleted = 1" items.

And according to the doc, you suggest that we use "deleted_at" to mark deleted ones. But in our practice, we choose "deleted" and mark the deleting time by "updated_at".

Maybe you should consider to learn some pattern from other languages' ORMs. For instance, Python SQLAlchemy, we can put "deleted = True" into the where clause. In one word, let developers decide.

**Comment by brunocassol** [comment]
Hi beed9999,

Do you have the the deleted_at field in the struct? If so then Find() will use that as documented here http://jinzhu.me/gorm/crud.html#delete: 
> If model has DeletedAt field, it will get soft delete ability automatically! then it won't be deleted from database permanently when call Delete, but only set field DeletedAt's value to current time

If you are not using deleted_at you can remove it from the struct and your Find() will stop including ` AND deleted_at IS NULL.`

I hope that helps.

**Comment by beef9999** [comment]
Thanks, @brunocassol 

But it's not up to me to remove the `deleted_at` field. I was migrating the project to an existing database.

Besides, I found a method called `Scan` that would not automatically filter `deleted = 1`, although I have no idea what are the real differences between `Scan` and `Find`.

**Comment by jbfm** [comment]
Use `Unscoped()` to find deleted records, as per the documentation http://jinzhu.me/gorm/crud.html#delete

`Scan` is part of the `Scanner` interface in the [database/sql](https://golang.org/pkg/database/sql/#Scanner) package of Go, and has nothing to do with `Find`
