### ISSUE TITLE
How do I know whether the `db.First(&product,id)` success or failed?

### ISSUE THREAD

**Issue by roxma** [jinzhu/gorm#1415]

**Comment by jbfm** [comment]
Check `db.First(&product,id).Error`

**Comment by roxma** [comment]
@jbfm 
I tried, it's `nil` even if the id does not exist.

**Comment by jbfm** [comment]
@roxma In that case the database query didn't fail, which `Error` in this case checks for. No data is a valid response, check if `Product.ID` or another required property is its zero value, in which case you'd have no data.

**Comment by roxma** [comment]
I've tried that too. Works.

But, is it safe to assume that there will be no item with `id==0`? This usage looks wierd to me.

**Comment by jbfm** [comment]
You could also check `RowsAffected`, `db.First(&product,id).RowsAffected`, should be 1 in the case of `First`

**Comment by roxma** [comment]
@jbfm 

`RowsAffected` is 0 even if the item exists.

**Comment by Arman92** [comment]
I think the best way to check it is to see if the product.ID is zero. if so, then no such record has been found.

**Comment by jinzhu** [comment]
`db.First(&product,id).RecordNotFound()`
