### ISSUE TITLE
[Help Me !!!] How to fire a subquery?

### ISSUE THREAD

**Issue by beef9999** [jinzhu/gorm#1421]
```
// User has many properties
type User struct {
    Properties   []Property
}

type Property struct {
    UserID      int
    Property   string
}
```

db.Preload("Properties").Find(&users)

----
And then ..
How to find all users who have certain property called <property_string> ?

What I can think of is to use a EXISTS subquery to deal with the property, but it seems GORM didn't provide such syntax.

**Comment by sungwoncho** [comment]
See https://stackoverflow.com/questions/46807891/using-a-subquery-in-from.
