### ISSUE TITLE
Dynamic data loading (reflect: call of reflect.Value.FieldByName on map Value)

### ISSUE THREAD

**Issue by ahirmayur** [jinzhu/gorm#143]
Hi guys,

I have a dynamic query where the structure of table is not knows in advance.

e.g.
```
results := make(map[string]interface{}, 0)
err := DB.Table(table).Find(&results).Error
```

```table``` is a variable passed by user on runtime.

Doing so creates a Panic,

```reflect: call of reflect.Value.FieldByName on map Value```

**Comment by rtm7777** [comment]
@jinzhu is this feature still not available?

**Comment by Mrhyuan** [comment]
@jinzhu any news on this feature?

**Comment by jinzhu** [comment]
Actually I think this is not a necessary feature, You should define a struct to load data.

When can't, just use database's `Row`, `Rows`

**Comment by ruseinov** [comment]
@jinzhu Well, I can tell you that it's painful right now to scan stuff into map, that feature could have actually saved a lot of time, consider this example: joining several tables, selecting all from them and storing, say, in elasticsearch. Why would anyone need to maintain the schema via struct if it could be done via map?

It's not too fast though.

For anyone that would struggle with this in the future I'll just leave that here:

```
var m []map[string]interface{}

cols, err := rows.Columns()


	for rows.Next(){
		row := make([]interface{}, 0)

		generic := reflect.TypeOf(row).Elem()

		for _ = range cols {
			row = append(row, reflect.New(generic).Interface())
		}
		_ = rows.Scan(row...)

		rowMap := make(map[string]interface{})

		for i, col := range cols {
			log.Println(*row[i].(*interface{}))
			rowMap[col] = *(row[i].(*interface{}))
		}

		m = append(m, rowMap)
	}

```

**Comment by jinzhu** [comment]
Why Map? Define a temporary struct like this?

```go
var result struct {
    Name string
    Age  int
}

db.Table("users").Select("name, age").Where("name = ?", 3).Scan(&result)
```

**Comment by ruseinov** [comment]
Why map?

Because the query has 200 + fields from 10 tables, it loads data to make it
searchable into elasticsearch, I don't really need to know what fields are
there, since I need them all. Every time the schema changes I would have to
add new fields to a struct, which is painful.

**Comment by jinzhu** [comment]
OK, so this is not a normal case (you don't even care fields, data type)

So some code like this doesn't seem pain to me, if still think about pain, write a wrapper for this.

```go
var results []map[string]interface{}
cols, err := rows.Columns()

for rows.Next() {
	var row = make([]interface{}, len(cols))
	rows.Scan(row...)

	rowMap := make(map[string]interface{})
	for i, col := range cols {
		rowMap[col] = row[i]
	}

	results = append(results, rowMap)
}
```

**Comment by ruseinov** [comment]
It's not pain any more when it's implemented already.

This does not work by the way, you have to prepopulate row with values,
since Scan expects pointers.

**Comment by ruseinov** [comment]
@jinzhu Anyway, I'm not insisting that it would be a killer feature, but I definitely miss it for various tasks where I don't really want to bother to define a schema. 

Being able to scan values into a map / array of maps would be perfect.

I can contribute that feature given you're gonna accept the PR.
If not - I'll just keep using my own helpers.

**Comment by jinzhu** [comment]
Hello @ruseinov 

Thank you for your kindness.

If the `Scan` method could scan data into a map, it would be helpful, but don't really like the `Find`, `First`, `Save` methods to support it, as it will slow down normal queries.

Thank you.

**Comment by reorx** [comment]
@ruseinov I found there are helper functions that does similar things as you described, referenced FYI https://github.com/go-xorm/xorm/blob/master/helpers.go#L364

**Comment by ruseinov** [comment]
@reorx Nice one, thanks!

**Comment by reorx** [comment]
And I also found that the code on comment https://github.com/jinzhu/gorm/issues/143#issuecomment-155687294 should be corrected:

```
var results []map[string]interface{}
cols, err := rows.Columns()

for rows.Next() {
    var row = make([]interface{}, len(cols))
    var rowp = make([]interface{}, len(cols))
    for i := 0; i < len(cols); i++ {
        rowp[i] = &row[i]
    }

    rows.Scan(rowp...)

    rowMap := make(map[string]interface{})
    for i, col := range cols {
        rowMap[col] = row[i]
    }

    results = append(results, rowMap)
}
```

The parameters passed into `Scan` must be pointers, otherwise the `rowMap` would be an array of <nil> (empty interface)

**Comment by ruseinov** [comment]
I've made that comment a bit earlier, yeah, that is true.
