### ISSUE TITLE
couldn't convert "\x00" into type bool

### ISSUE THREAD

**Issue by wangxufire** [jinzhu/gorm#1432]
I want use golang type bool mapped to mysql bit。

**Comment by jbfm** [comment]
This is an issue in the [MySQL driver](https://github.com/go-sql-driver/mysql/issues/440#issuecomment-256847537) and nog Gorm

**Comment by wangxufire** [comment]
3Q

**Comment by wangrenyi** [comment]
I have encountered the same problem. How to solve it
