### ISSUE TITLE
Cannot insert date before 1970

### ISSUE THREAD

**Issue by abour** [jinzhu/gorm#1433]
A field having the type "time.Time" is mapped to a timestamp in MySQL.
Thus, the MySQL timestamp is the number of seconds after 1970. Every "time.Time"  before 1970 is recorded as "0000-00-00 00:00:00" in MySQL.

**Comment by abour** [comment]
My bad, just need to add: `gorm:"type:date"`

**Comment by alemarcha** [comment]
> My bad, just need to add: `gorm:"type:date"`

Thank you so much!! It helps me a lot.
