### ISSUE TITLE
How can I add foreign keys?

### ISSUE THREAD

**Issue by mingrammer** [jinzhu/gorm#1434]
I have two models as following. 
 
```go
type Project struct {
	gorm.Model
	Title    string    `gorm:"unique" json:"title"`
	Archived bool      `json:"archived"`
	Tasks    []Task    `gorm:"ForeignKey:ProjectID" json:"tasks"`
}

type Task struct {
	gorm.Model
	Title     string    `json:"title"`
	Priority  uint      `gorm:"type:ENUM('0', '1', '2', '3');default:'0'" json:"priority"`
	Deadline  time.Time `json:"deadline"`
	Done      bool      `json:"done"`
	ProjectID uint      `json:"project_id"`
}
```

Then, I've called the `db.AutoMigrate(&Project{}, &Task{})`, but, the foreign key of project id was not created. So, I used the `AddForeignKey` manually instead of using auto migrate.

Is itI bug??

**Comment by jinzhu** [comment]
We doesn't auto generate foreign key in the auto migration, there already an issue related to this, will fix that in the future.
