### ISSUE TITLE
Preload runs multiple sql queries

### ISSUE THREAD

**Issue by Fyb3roptik** [jinzhu/gorm#1436]
Right now Preload is running separate postgres queries to load the data. Is there a way to have preload run the query with joins instead? Or should I just use Join().

Thanks for this awesome ORM!

**Comment by jinzhu** [comment]
No, we don't support preload with joins, with a additional SQL could simplify the generated SQL, and we could use prepared statement to optimize it in the future.

**Comment by Fyb3roptik** [comment]
This is something that is VERY important for production environments. Currently pulling hundreds of rows of data fires off thousands of SQL queries for my postgres server. As you can imagine this is time consuming! This needs to be really thought through for a future version ASAP otherwise my company will not be able to use this wonderful ORM :(

**Comment by jinzhu** [comment]
> Currently pulling hundreds of rows of data fires off thousands of SQL queries for my postgres server.

This is not true, Preload would be helpful to kill N+1 queries, no matter how many data you fetched, will only generate 1 additional SQL.

**Comment by Fyb3roptik** [comment]
If I chain them together like .Preload().Preload() it runs separate queries for each one.

**Comment by Fyb3roptik** [comment]
Or should I do it like this .Preload("table1", "table2")

**Comment by jinzhu** [comment]
` .Preload().Preload()` will only generate 3 SQL queries even pulling hundreds of rows of data? I don't think this is an issue.

**Comment by Fyb3roptik** [comment]
300 vs 100 is a big deal at scale though. For instance I am pulling 50 items each of which have 4-5 preloads each! So it starts to add up. I will see if there is a better way to join this data up and possibly offer a PR. Thanks!

**Comment by jbfm** [comment]
Honestly this sounds like a design issue in your project, and not an issue with any ORM. 50 separate queries sounds like a lot to begin with if it's the same dataset.

**Comment by canhlinh** [comment]
@Fyb3roptik   Any benchmark for both strategies ( JOIN vs PRELOAD )?

**Comment by canhlinh** [comment]
@Fyb3roptik Can you compare GORM with XORM?

**Comment by Fyb3roptik** [comment]
When I have time I will do a comparison. I can tell you from previous experience 1 query is better than several, but for science I will experiment when I get the chance to look further into this.

**Comment by canhlinh** [comment]
Hmm. I know that.
What is happens with many LEFT OUT JOIN?
Bee orm using it https://github.com/astaxie/beego/tree/master/orm

**Comment by lunemec** [comment]
I would also like the support for JOIN preload (different syntax is ok). JOINs should be faster than multiple queries, because you shave off these actions:
* sending SQL command over TCP/socket
* sql server parsing the query
* lookup in query cache (either return from cache or not)
* query anlysis
* actual data lookup from db engine

When sending 3 queries, you're making sql server make additional processing. Look at this stackoverflow answer:
https://stackoverflow.com/a/17480366

I aggree that improvements depend very much on actual use case and tables (indexes, keys, etc..) but I don't think you can go wrong with supporting it via different syntax.

**Comment by Fyb3roptik** [comment]
Here is my issue currently. I do not think I made it clear. I have 3 main tables, which inside of them each have 3-4 joining tables with data. If I call maintable1 and it has 3-4 preloads and 1 of those preloads is maintable2, which itself has a number of preloads including maintable3. You see how 1 query turns into about 20 with the preloader. This should be turned into 1-2 queries max with proper joins. Most if not all main languages that have ORM's have this functionality. Doing separate queries for each preload or related item is NOT the proper way to do this for something that has to scale. 

I have millions of rows of data and these queries are taking up a lot of time and bandwidth. I will have to explore other options until this is resolved.

**Comment by croatiangrn** [comment]
@Fyb3roptik Have you found some other solution to this problem?

**Comment by Fyb3roptik** [comment]
Yep! go-pg was my solution. Move to that and my api endpoint time went from about 30 seconds on large activity data to about 700ms. It was quite an improvement!

**Comment by gmolveau** [comment]
Any update on this topic @jinzhu , please ? :)

**Comment by yoh** [comment]
For information, how go-pg/gorm deals with relations query : https://github.com/go-pg/pg/wiki/FAQ#why-go-pg

**Comment by canhlinh** [comment]
@gmolveau Can not do it

**Comment by Dave3of5** [comment]
How can this be closed ? To me this is a fundamental part of an ORM.

**Comment by Fyb3roptik** [comment]
Because he doesnt understand why it is. I have moved to go-pg as it is way better! He keeps deleting my suggestion to move to go-pg so this comment will probably be deleted

**Comment by lunemec** [comment]
On my other project, I tried https://github.com/volatiletech/sqlboiler and it seems quite nice. I have not used it on other larger project, but I intend to. It might also be a solution.

**Comment by syncore** [comment]
This is a fundamental problem that I only discovered last night. Now I have to re-write a considerable amount of code to switch to something else.

**Comment by alekc** [comment]
This is mental, just found out about this issue... Looks like I'll have to migrate elsewhere as well.

**Comment by Fyb3roptik** [comment]
@jinzhu Still think this is a non issue? This IS A HUGE ISSUE MAN

**Comment by tzilist** [comment]
This is rough. This is causing some of our queries to go from around 300ms to around 700ms-1s. Using joins to load data is a pretty fundamental part of using a relational database. Would really love to see some work done on this.

**Comment by KellyLSB** [comment]
Seems like the logic for making this change occurs entirely in https://github.com/jinzhu/gorm/blob/master/callback_query_preload.go
I may delve into this further at some point.

**Comment by sgon00** [comment]
I am learning GORM, because
* It has 14588 stars, 
* Recommended Go ORM by many people
* Many people say it's well documented (has a very good documentation).

But, what I can't believe when I am learning it:

* Maybe this is Go world. I don't find the doc is clear at all. For example, the doc doesn't even tell you that you should create foreign keys manually when you create associations (AutoMigrate doesn't do it).
* (this issue) I can't use a simple join query to load data. I have to use Preload to run multiple SQL queries instead. I really can't believe it. There is no word that can express my current feeling.
* etc...

This is really disappointing because I have already spent some time on GORM. Anyway, not too late, I will switch to go-pg then. I hope I can understand that doc. Because Go world doesn't have good docs.

**Comment by lunemec** [comment]
@sgon00 Try to use simple queries instead of ORM, or try sqlboiler. It is usually enough for most cases, while supporting raw sql where it is not enough.

**Comment by sgon00** [comment]
@lunemec thanks a lot for the info. ^_^ I think I will use go-pg.

**Comment by dkul108** [comment]
I'm also did this huge mistake of using GORM - I need a tens of joins resulted with 100000+ records, preloads are limited with IN STATEMENT

**Comment by Lucantas** [comment]
How this is NOT an issue?
