### ISSUE TITLE
count syntax bug? 

### ISSUE THREAD

**Issue by researchlab** [jinzhu/gorm#1439]
p.DB.GetDB().Model(&SystemInfo{}).Where("Key=?", data.Key).Count(&count).Error

when i run the above sql , get the following error info:
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Key=?))' at line 1

and when i exec the following one, is exec right, p.DB.GetDB().Model(&SystemInfo{}).Where("Key=?", data.Key).Error

but i want to get the count of the given key,  is this a bug ? how can i do it next?

**Comment by researchlab** [comment]
the above SystemInfo is
type SystemInfo  struct {
gorm.Model
Key string 
Value string 
} 

when I modified it to 
type SystemInfo struct {
gorm.Model
Name string 
Value string 
}
and exec the above sql:   p.DB.GetDB().Model(&SystemInfo{}).Where("Name=?", data.Name).Count(&count).Error,  

it works,

**Comment by researchlab** [comment]
type:question

**Comment by jinzhu** [comment]
Please follow https://github.com/jinzhu/gorm/blob/master/.github/ISSUE_TEMPLATE.md 

Thank you, please reopen another issue if it is still a problem for you.

**Comment by Bartuz** [comment]
what is your `&count`?

**Comment by researchlab** [comment]
var count int64 
p.DB.GetDB().Model(&SystemInfo{}).Where("Name=?", data.Name).Count(&count).Error
@Bartuz
