### ISSUE TITLE
Where() generates incorrect query for boolean fields

### ISSUE THREAD

**Issue by XANi** [jinzhu/gorm#1440]
Querying for bool struct elements via Struct does not generate correct query, omiting boolean part completely:

```go
package main
import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
	"fmt"
)


type Message struct {
	gorm.Model
	Content string
	Sth int
	Sent bool
}


func main() {
	db, err := gorm.Open("sqlite3", `test.db`)
	if err != nil { fmt.Println(err)}
	defer db.Close()
	db.LogMode(true)
	db.AutoMigrate(&Message{})
	var m Message
	db.Where(&Message{Content: "ttt",Sth: 5,Sent: false}).Find(&m)
	db.Where(&Message{Sent: false}).Find(&m)
}
```
results in
```

(/home/xani/src/things/gorm_test/main.go:23)
[2017-04-20 14:36:46]  [0.17ms]  SELECT * FROM "messages"  WHERE "messages".deleted_at IS NULL AND (("content" = 'ttt') AND ("sth" = '5'))

(/home/xani/src/things/gorm_test/main.go:24)
[2017-04-20 14:36:46]  [0.87ms]  SELECT * FROM "messages"  WHERE "messages".deleted_at IS NULL
```

using go1.7.3/sqlite

**Comment by jbfm** [comment]
False is the zero value of a boolean, so it gets ignored in the struct. If you want to search for a zero value you need to do something like `db.Where("sent = ?", false).Find(&m)`.

**Comment by jinzhu** [comment]
http://jinzhu.me/gorm/crud.html#query-with-where-struct--map

**Comment by XANi** [comment]
@jinzhu cool but there is nothing in the doc about it

> "GORM will only query with those fields has value"

int: 0 "has value"
bool: false "has value"

It probably should say "GORM will only query with those fields has **non-default** value"

**Comment by jbfm** [comment]
@XANi Non-zero is probably better than non-default, default _could_ be something that's not a zero value.

**Comment by XANi** [comment]
@jbfm empty string is default but not zero, to give one example. Pointer will be nil too. Non-zero is only for numeric types (and time I guess).

**Comment by jbfm** [comment]
@XANi An [empty string](https://tour.golang.org/basics/12) is called a zero value in Golang

**Comment by koalalorenzo** [comment]
I think this is a HUGE problem as I have to rewrite the entire codebase to have "strings" instead of booleans to prevent true false and false false (_love to say that_).

With `Where` it is excluding properties to be filtered, when those are set to false in the query. 
It seems that this is impacting also when saving/updating and creating... Any suggestion? Is there a specific Type to prevent this and have real booleans?

**Comment by jinzhu** [comment]
Hi All

Thank you for all your input, updated the document a little bit. http://gorm.io/crud.html#query-with-where-struct--map
