### ISSUE TITLE
Combine And/Or conditions with parantheses

### ISSUE THREAD

**Issue by svarogg** [jinzhu/gorm#1443]
### What version of Go are you using (`go version`)?
go version go1.8.1 linux/amd64

### Which database and its version are you using?
mysql version 5.7.17-0ubuntu0.16.10.1-log

### What did you do?
I have quite a complex condition to retrieve items from a table based on the rows a user is permitted to view.
Permissions have quite a complex logic, so it's a condition in the form of `(XXX or YYY or ZZZ)`.
The above is joined with some more condition, so together, I have something like this:
`SELECT * FROM table WHERE AAA AND BBB OR (XXX or YYY or ZZZ)`
This type of conditions are very hard to reproduce using GORM.

This is a dumbed down version of my application:

Provision the database with the following script before running:
```sql
CREATE TABLE tests(a int, b int);
INSERT INTO tests(a,b) VALUES (1,1),(2,2),(3,4);
```

```go
package main

import (
	"fmt"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

var db *gorm.DB

func init() {
	var err error
	db, err = gorm.Open("mysql", "gorm:gorm@/dbname?charset=utf8&parseTime=True")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

type test struct {
	a int32
	b int32
}

func main() {
	t := []test{}
	db.
		Where("a = b").
		Where("a = ?", 1).
		Or("b= ?", 4).
		Find(&t)

	if len(t) == 2 {
		fmt.Println("failed")
	} else {
		fmt.Println("success")
	}
}
```
Output is: 
```
[2017-04-24 12:13:15]  [0.69ms]  SELECT * FROM `tests`  WHERE (a = b) AND (a = '1') OR (b= '4')
failed
```
What I would like to see instead (Note the parantheses after AND):
```
[2017-04-24 12:14:45]  [0.79ms]  SELECT * FROM `tests`  WHERE (a = b) AND ((a = '1') OR (b= '4'))
success
```

Possible workarounds: 
1.  What is suggested in #855 .
Works well for small queries, but gets clunky when the query is quite long, especially when every Or clause has some parameters - gets very unwieldy.
2. Start the first Or clause with an opening parantheses, and the last one with a closing parantheses:
```go
	db.
		Where("a = b").
		Where("(a = ?", 1).
		Or("b= ?)", 4).
		Find(&t)
```
This works well, but not intuitive, very ugly, and impossible to spot for someone reading the code.

Some possible fix suggestions:
1. Every call to Where(as opposed to And) starts a new set of parentheses 
Would work well for my and most usecases, but will not work for even more complex queries that might require nested parantheses.
2. Same as 1 but add a new method so that it doesn't break functionality (Still problematic for complex queries)
3. Add a method that creates a condition surrounded by parentheses that can be passed to .Where().
Said condition should support all methods such as .Where() .And() and .Or().

Thanks,

**Comment by svarogg** [comment]
P.S.
It is defenitely a feature request, but I'm not sure I have the permission to apply type:feature label to the issue.

**Comment by jinzhu** [comment]
`Where(" a = ? OR b = ?", 1, 4)`

**Comment by svarogg** [comment]
>  Where(" a = ? OR b = ?", 1, 4)
This doesn't work for queries that are dynamically built.
At different situations I add different conditions. Of course I can use a string builder, etc, but that beats the whole point of using an ORM.
