### ISSUE TITLE
gorm should allow ignoring UNIQUE fields from being replaced in association.

### ISSUE THREAD

**Issue by MintyOwl** [jinzhu/gorm#1446]
### What version of Go are you using (`go version`)?
1.8

### Which database and its version are you using?
postgres 9.6.2

### What did you do?

```
package main

import (
	"fmt"
	"os"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
)

type Customer struct {
	gorm.Model
	Name   string
	Phones []Phone
}

type Phone struct {
	gorm.Model
	Number     int `gorm:"UNIQUE"`
	CustomerID int
}

func main() {
	credentials := "user=myuser dbname=mydb sslmode=disable password=mypassword"
	db, err := gorm.Open("postgres", credentials)
	defer db.Close()
	gorm.DefaultTableNameHandler = func(db *gorm.DB, defaultTableName string) string {
		return "test" + defaultTableName
	}
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	db.LogMode(true)
	db.AutoMigrate(&Customer{}, &Phone{})

	testInit(db)
	//cleanUp(db)
}

func testInit(db *gorm.DB) {
	createData(db)
	//deleteAssociation(db)
	replaceAssociation(db)
}

func cleanUp(db *gorm.DB) {
	db.DropTable(&Customer{}, &Phone{})
}

func deleteAssociation(db *gorm.DB) {
	var customer = Customer{}
	customer.ID = 1
	db.Model(&customer).Association("Phones").Delete(Phone{Number: 1234})
}

func replaceAssociation(db *gorm.DB) {
	var customer = Customer{}
	customer.ID = 1
	db.Model(&customer).Association("Phones").Replace([]Phone{{Number: 7867}, {Number: 1234}})
}

func createData(db *gorm.DB) {
	customer := Customer{Name: "Customer1", Phones: []Phone{Phone{Number: 1234}, Phone{Number: 5678}}}
	fmt.Println(db.Create(&customer).Error)
}

```
In ``` func replaceAssociation``` above, I am not able to add ```{Number:1234}``` because of 2 reasons
1. Field ```Number``` is UNIQUE (and is being added again)
2. gorm disassociates a UNIQUE field in ```Replace``` method.

**What should be the output?**
Customer with ID=1 should have Phones **7867** and **1234**

**What am I getting instead?**
Customer with ID=1 has only one phone **7867**

**Comment by jinzhu** [comment]
Hi @MintyOwl 

I think this is similar with this issue https://github.com/jinzhu/gorm/issues/1445, it should has primary key for associations for `Replace`, but it is empty for this example.

But I think you might could consider to use `Number` as primary key for `Phone` struct if it is always unique? or you need to query existing `Phone` before assign.

**Comment by MintyOwl** [comment]
Great, thanks again.
