### ISSUE TITLE
Can't cancel request with using a context.Context

### ISSUE THREAD

**Issue by jhorowitz** [jinzhu/gorm#1447]
Before posting a bug report about a problem, please try to verify that it is a bug and that it has not been reported already, please apply corresponding GitHub labels to the issue, for feature requests, please apply `type:feature`.

DON'T post usage related questions, ask in https://gitter.im/jinzhu/gorm or http://stackoverflow.com/questions/tagged/go-gorm,

Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go1.8.1 darwin/amd64

### Which database and its version are you using?
Postgres 1.5

sql.DB provides a method which allows canceling via context db.QueryContext. Is there a way to do a similar type of query using gorm?

**Comment by zardak** [comment]
It's not possible at the moment. The issue is already being discussed https://github.com/jinzhu/gorm/issues/1231.

**Comment by jinzhu** [comment]
duplicated with #1231
