### ISSUE TITLE
Nested struct with pointer cause a panic

### ISSUE THREAD

**Issue by bobcyw** [jinzhu/gorm#1450]
`type:bug`.

### What version of Go are you using (`go version`)?
go version go1.8 darwin/amd64

### Which database and its version are you using?
MySQL

### What did you do?

Please provide a complete runnable program to reproduce your issue.

When I define a nested struct like
```
type A struct{
 X string
}
type B struct{
 gorm.Model
 *A
}
```
After insert some B, then select B, it cause a panic.
I think the Scope.Fields has some defects when it handles struct with a pointer.

**Comment by zardak** [comment]
> Please provide a complete runnable program to reproduce your issue.

**Comment by bobcyw** [comment]
@zardak Hi, this is the program. Database name is gorm.
```
package main

import (
	_ "github.com/go-sql-driver/mysql"
	"github.com/jinzhu/gorm"
)

type A struct {
	X string
	Y string
}

type B struct {
	gorm.Model
	*A
}

func checkErr(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	db, err := gorm.Open("mysql", "user_name:password@tcp(127.0.0.1:3306)/gorm?charset=utf8&parseTime=True&loc=Local")
	checkErr(err)
	checkErr(db.AutoMigrate(&B{}).Error)
	a := &A{X: "x", Y: "y"}
	b := B{A: a}
	checkErr(db.Create(&b).Error)
	var b2 []B
	checkErr(db.Model(&B{}).Where("X=? and Y=?", "x", "y").Find(&b2).Error)
}
```

**Comment by canhlinh** [comment]
@bobcyw I don't think using an anonymous struct as a pointer is a good practice.

**Comment by bobcyw** [comment]
It can avoid another memory allocation and reuse anonymous struct's method.

**Comment by canhlinh** [comment]
Sometime when using ORM you have to consider a deal between maintainable and performance
