### ISSUE TITLE
type:feature  Better support for pq.Int64Array

### ISSUE THREAD

**Issue by nri-pl** [jinzhu/gorm#1455]
`type:feature`

### Which database and its version are you using?
postgresql 9.6

### What did you do?

My current code:
```go
type Test struct {
  ...
  Tags   pq.Int64Array  `gorm:"type:integer[]"`
}
func (p *Test) Tags2() []int64 {
	return []int64(p.Tags)
}
```

Hi, Currently, to retrieve a value from Tags, I have to create a Tags2() or similar method that will convert pq.Int64Array to []int64.

Would it be possible to do it inside Gorm?
So that the model code looks like this:

```go
type Test struct {
  Tags   []int64
}
```
It seems simple and obvious to do.
Apart from other than the PostgreSQL database.

**Comment by jinzhu** [comment]
Field has to be a `Scaner`, `Valuer` to save/receive data from database
