### ISSUE TITLE
db.Model(&user).Updates(User{Actived: false})

### ISSUE THREAD

**Issue by nri-pl** [jinzhu/gorm#1457]
### What version of Go are you using (`go version`)?
go 1.8.1 linux/amd64

### Which database and its version are you using?
PostgreSQL 9.6

### What did you do?

Hi,
I understand perfectly where it comes from
```go
// WARNING when update with struct, GORM will only update those fields that with non blank value
// For below Update, nothing will be updated as "", 0, false are blank values of their types
db.Model(&user).Updates(User{Name: "", Age: 0, Actived: false})
```

However, I think that after adding the .Select() update should occur.
eg:
```go
db.Model(&user).Select("Actived").Updates(User{Name: "", Age: 0, Actived: false})
```
IMHO should do
UPDATE "users" SET Actived = $1 WHERE "users"."id" = $2

Currently to save in database Actived = false, I need to convert an object to map[string]interface{}. Especially if it updates more than one field. Or db.Save(user) it all.

eg:
```go
user = &User{}
db.Find(user, id)
user.Name = "test"
user.Actived = false
changed := []string{"Name", "Actived"}
db.Model(user).Select(changed).Updates(user)
```

It makes more sense when a function `change_in_model` is added.
eg:
```go
func change_in_model(a, b interface{}) (res []string){
	av := reflect.ValueOf(a).Elem()
	bv := reflect.ValueOf(b).Elem()
	at := av.Type()
	for i := 0; i < av.NumField(); i++ {
		af := av.Field(i).Interface()
		bf := bv.Field(i).Interface()
		if !reflect.DeepEqual(af, bf) {
			res = append(res, at.Field(i).Name)
		}
	}
	return
}


user = &User{}
db.Find(user, id)
before := *user
// I change any fields in user, eg after receiving data from POST request.
changed := change_in_model(user, &before)
if len(changed) > 0 {
  db.Model(user).Select(changed).Updates(user)
}
```
In this example I know exactly what was changed in the `user` object and only those changes I send to the database.

**Comment by jbfm** [comment]
Select has nothing to do with Update, making that connection just confuses things. Using a map instead of a struct is a very small change, and requires no effort. Your suggestion honestly seems like a lot more mental work than to just use a map.

The documentation could probably make this clearer though.

**Comment by nri-pl** [comment]
@jbfm - I was also surprised, but you are wrong.
db.Model(user).Select(changed) - Such a thing exists in the documentation and it works ;)
http://jinzhu.me/gorm/crud.html#update  see "Update Selected Fields".
and https://godoc.org/github.com/jinzhu/gorm#DB.Select
```
func (*DB) Select
func (s *DB) Select(query interface{}, args ...interface{}) *DB
Select specify fields that you want to retrieve from database when querying, by default, will select all fields; When creating/updating, specify fields that you want to save to database
```

I close the ticket because I have already solved my issue and am satisfied with the solution.
`DB.Select(fields).Save(user)`
It works like a charm ;)

**Comment by jbfm** [comment]
Look at that, good to know!
