### ISSUE TITLE
Query by field in Preloaded entity

### ISSUE THREAD

**Issue by LeBronoMars** [jinzhu/gorm#1461]
here's my code

```
readings := []m.Reading{}	
query.Preload("Station", "name = ?","Station 001").Order("id desc").Find(&readings)
```

where **name** is field in **Station** entity and when i check the logs i don't understand why i'm getting this query 

`SELECT  * FROM `stations`  WHERE (`stations`.deleted_at IS NULL OR `stations`.deleted_at <= '0001-01-02') AND ((id IN ('26','26','26','26','26','26','26','26','26','26')) AND (name = 'Station 001'))
`

I don't where **((id IN ('26','26','26','26','26','26','26','26','26','26'))** was coming from?

**Comment by canhlinh** [comment]
It is the anwer for the reason Why do you use `Preload` ?
*((id IN ('26','26','26','26','26','26','26','26','26','26'))*  it is ids of `Station` have relationship with each `Reading`.
