### ISSUE TITLE
Update all fields with object (instead of map)

### ISSUE THREAD

**Issue by hangll** [jinzhu/gorm#1464]
From the document, if I do 
```
db.Model(&user).Updates(User{Name: "", Age: 0, Actived: false})
```
It won't update empty fields. However, I'm defining my model using protocol buffer and fields names  are not always same as column names. Thus converting object to map is not so easy.

`db.Save(user)` can be tricky as it'll create new object if `user` doesn't exist. Now, I have to first check existence before every update.

Is there any way I can use a single query that will fail when updating a non-existing object?

**Comment by hangll** [comment]
@canhlinh In my case, fields name are not always same as column names, would you mind to explain how I can convert elegantly?

**Comment by jbfm** [comment]
Check under [Update Selected Fields](http://jinzhu.me/gorm/crud.html#update) in the documentation to specify also update empty fields. Also discussed and resolved in #1457, so check that for some more info!

**Comment by canhlinh** [comment]
```
func Update(object *models.Object, columns ...string) *Error {

		if len(columns) > 0 {

			model := db.NewScope(object)

			params := make(map[string]interface{})

			for _, col := range columns {
				f, _ := model.FieldByName(col)
				params[col] = f.Field.Interface()
			}

			if err := db.Updates(params).Error; err != nil {
				return new(Error)
			}
		}
}
```

**Comment by canhlinh** [comment]
Can the code help you?

**Comment by jinzhu** [comment]
use `Select`

`db.Model(&user).Select("name", "age", "actived").Updates(User{Name: "", Age: 0, Actived: false})`

**Comment by aetherwu** [comment]
> params

Sorry to ask for a bit extra help.
Could this code have an option to save all fields that this object has?

For instrance , assume that we have a db model X:
type X strtuc {
    A
    B
    C
}

Then another struct can be defined in business layer:
type N struct {
    A
    B
}

Then N can be assign to X:

Update(X, N) {
  //....here all fields of N can be saved to X automatically ignoring it is empty or not.
}
