### ISSUE TITLE
Wrong foreign key is used when the model contains "TABLE_NAME_ID" field

### ISSUE THREAD

**Issue by sadu99** [jinzhu/gorm#1473]
### What version of Go are you using (`go version`)?
go version go1.8.1 darwin/amd64

### Which database and its version are you using?
(PostgreSQL) 9.6.3

### What did you do?
When querying relational data, the wrong foreign key is used when the model contains a `table_name_id` field:

For example,

Having the following models:
```go
type User struct {
	gorm.Model
	Emails   []Email
}
type Email struct {
	gorm.Model
	EmailID uint
	Email   string
	UserID  uint
}
```
The following line:
```go
db.Model(&user).Related(&emails)
```
Results in the following sql generated:
```sql
SELECT * FROM emails WHERE email_id = 111
```
Instead of:
```sql
SELECT * FROM emails WHERE user_id = 111
```
Note: Adding ``gorm:"ForeignKey:UserID"`` on the `Emails` property does not help.

**Comment by MungBeanSoup** [comment]
add `gorm:"AssociationForeignKey: UserID"` on Emails

**Comment by sadu99** [comment]
Hey @MungBeanSoup, adding `gorm:"AssociationForeignKey: UserID"` did not help :( So far, it only works when I remove the `EmailID` field.

**Comment by MungBeanSoup** [comment]
Sorry, I got a wrong understanding on `belongs to` and `has many` relationship
Your `gorm:"ForeignKey:UserID"` is Right
What about `db.Model(&user).Related(&emails, 'Emails')`

**Comment by sadu99** [comment]
Ok that worked! Thanks 😄  Can you please explain why that works? This was not required in the `Has Many` example in the documentation: `http://jinzhu.me/gorm/associations.html#has-many`

**Comment by MungBeanSoup** [comment]
Because `Emails` isn't equal to `Email`
There has a comment in `http://jinzhu.me/gorm/associations.html#has-one`
`If the field name is same as the variable's type name, like above example, it could be omitted`
 I think the doc is wrong

**Comment by sadu99** [comment]
Thanks for the help 👍
