### ISSUE TITLE
Preloading multiple relations of the same type with different names

### ISSUE THREAD

**Issue by Allendar** [jinzhu/gorm#1476]
### What version of Go are you using (`go version`)?
go1.8.1 darwin/amd64

### Which database and its version are you using?
MySQL 5.7.18 Homebrew

### What did you do?
I'm having differently named relationships on the same entity-type , which I wanted to Preload, yet there seems to be no way to do this, or I cannot seem to find the way to do this properly.

```go
// Used for most default entities.
type BaseModel struct {
	ID          uint      `gorm:"primary_key"`
	CreatedAt   time.Time `gorm:"not null"`
	UpdatedAt   *time.Time
	CreatedBy   User
	CreatedByID uint `gorm:"not null"`
	UpdatedBy   *User
	UpdatedByID *uint
}

type Product struct {
	BaseModel
}
```
The following will give an association error, but how can I achieve something like this:

```go
var products []Product
result := db.Preload("CreatedBy").Preload("UpdatedBy").Limit(10).Find(&products)

spew.Dump(products[0].CreatedBy.FirstName)
```

**Comment by Allendar** [comment]
Also note that for saving data `BaseModel{CreatedByID: user.ID}` only seems to work instead of `BaseModel{CreatedBy: user}`. I might be wrong, but shouldn't this be core ORM relational structuring? Polymorphism as a workaround seems to be quite redundant.

**Comment by KlausVii** [comment]
What's the exact error? I tried replicating your issue and could not get it to fail. 

And how is your User table defined?

**Comment by Allendar** [comment]
Maybe it gives an issues that the entities live in a subfolder/subpackage?

I get:

```
[2017-05-24 23:14:57]  can't preload field CreatedByUser for dbe.User 
2017/05/24 23:14:57 →
Recovered from a route's Handler('main.routeAdminUsers')
At Request: 200 /_28c4/users GET 127.0.0.1
Trace: can't preload field CreatedByUser for dbe.User
```

Calling it is pretty standard :

```
qb := db.Debug().
	Preload("CreatedByUser").
	Select(fields).
	Table(table).
	Joins(joinsBuffer.String()).
	Where(whereBuffer.String(), whereArguments...).
	Order(orderBuffer.String()).
	Limit(limit).Offset(offset).
	Find(returnList)
if nil != qb.Error {
	panic(qb.Error)
}
```

Maybe the issue is the entities living in the subpackage failing to resolve?

**Comment by Allendar** [comment]
I just tested executing it on the `package main` level and it works as you said. I'm curious tho how I could make it work as the entities live inside the subpackage tho. I need to have them in a package for my templating engine (using code generation), that can only dynamically load from packages to detect strict types.

**Comment by Allendar** [comment]
On the other hand. It didn't seem to work;

```
func test() {
	perror(db.DropTableIfExists(&TestUser{}).Error)
	perror(db.DropTableIfExists(&TestProduct{}).Error)
	perror(db.CreateTable(&TestUser{}).Error)
	perror(db.CreateTable(&TestProduct{}).Error)
	perror(db.Raw("TRUNCATE test_products").Error)
	perror(db.Raw("TRUNCATE test_users").Error)

	perror(db.Create(&TestUser{
		Name: "Allendar",
	}).Error)
	var user TestUser
	perror(db.First(&user).Error)
	spew.Dump(user)

	perror(db.Create(&TestProduct{
		Name: "T-Shirt X01E4",
	}).Error)
	var product TestProduct
	perror(db.Preload("CreatedBy").First(&product).Error)
	spew.Dump(product)
}

// TestUser datbase entity.
type TestUser struct {
	ID   uint `gorm:"primary_key"`
	Name string
}

// TestProduct datbase entity.
type TestProduct struct {
	ID          uint     `gorm:"primary_key"`
	Name        string   `gorm:"not null"`
	CreatedBy   TestUser `gorm:"not null"`
	CreatedByID uint     `gorm:"not null"`
	UpdatedBy   *TestUser
	UpdatedByID *uint
}
```

It outputs:

```
(main.TestUser) {
 ID: (uint) 1,
 Name: (string) (len=5) "Erwin"
}
(main.TestProduct) {
 ID: (uint) 1,
 Name: (string) (len=13) "T-Shirt X01E4",
 CreatedBy: (main.TestUser) {
  ID: (uint) 0,
  Name: (string) ""
 },
 CreatedByID: (uint) 0,
 UpdatedBy: (*main.TestUser)(<nil>),
 UpdatedByID: (*uint)(<nil>)
}
```

`CreatedBy` is not preloaded.

**Comment by Allendar** [comment]
I dissected the statements and it seems to happen when I use `Select(fields).` with aliases in the fields. I will keep this issue open until I found out what exactly caused it. Without `Select()` it works fine, so doesn't seem to be a bug for now.

**Comment by Allendar** [comment]
So it was this; the select fields didn't contain the join field(s):

```
[]string{
	"u.id", "u.created_by_id", "u.first_name", "u.surname", "u.email", "u.country",
},
```

After adding `u.created_by_id` the join succeeded too :)
