### ISSUE TITLE
使用related问题。

### ISSUE THREAD

**Issue by shizenghua** [jinzhu/gorm#1482]
我使用关系查询
```
if err = db.Where(map[string]interface{}{"orderIID":req.OrderIID}).Model(&out).Related(&outItem,"OrderIID").Error; err != nil {}
```
日志显示
```
SELECT * FROM `t_orderitem`  WHERE (`t_orderitem`.`orderIID` = '170420101856670195') AND (`` = '')
Error 1054: Unknown column '' in 'where clause' 
```

为何会多出了一个 (`` = '')， 这个是从哪里来的？

**Comment by finalsatan** [comment]
可以参考一下官方的文档

`// User has one CreditCard, UserID is the foreign key
type User struct {
    gorm.Model
    CreditCard   CreditCard
}

type CreditCard struct {
    gorm.Model
    UserID   uint
    Number   string
}

var card CreditCard
db.Model(&user).Related(&card, "CreditCard")
//// SELECT * FROM credit_cards WHERE user_id = 123; // 123 is user's primary key
// CreditCard is user's field name, it means get user's CreditCard relations and fill it into variable card
// If the field name is same as the variable's type name, like above example, it could be omitted, like:
db.Model(&user).Related(&card)`

你的这个 OrderIID 是不是少了类似于上面代码里面的 UserID 这样一个字段呢？
