### ISSUE TITLE
关于原声查询Raw遇到的问题

### ISSUE THREAD

**Issue by happyEgg** [jinzhu/gorm#1483]
你好，我这样一个查询。
user := make([]*UserInfo,0,10)
db.Raw("语句").Scan(&user)
当数据库里有数据时返回的是正常数据，但是数据库没有数据时，为什么会返回一条默认的数据呢。(.Find(&user)也有同样的问题)
例如：[
     {
          "Uid":0,
          "Name":"",
         "Age":""
     }
]

@jinzhu

**Comment by jinzhu** [comment]
Please follow this template. https://github.com/jinzhu/gorm/blob/master/.github/ISSUE_TEMPLATE.md
