### ISSUE TITLE
关于Raw原生语句查询问题

### ISSUE THREAD

**Issue by happyEgg** [jinzhu/gorm#1484]
go version: 1.8

sql语句：
CREATE DATABASE order_test DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

use order_test;
create table if not exists `order_info`(
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `uid` bigint(20) unsigned NOT NULL,
    `add_series` bigint(20) DEFAULT 0,
    `add_order_number` varchar(50) NOT NULL DEFAULT '',
    `prize` decimal(20,2) unsigned NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    INDEX uid_index(`uid`),
    INDEX add_number_idx(`add_order_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

代码：

package main

import (
	"fmt"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

type OrderInfo struct {
	Id             uint64  `json:"-"`
	Uid            uint64  `json:"-"`
	AddSeries      int64   `json:"-"`
	AddOrderNumber string  `json:"-"`
	Prize          float64 `json:"-"`
}

var db *gorm.DB

func init() {
	var err error
	db, err = gorm.Open("mysql", "root:123456@tcp(127.0.0.1:3306)/order_test?charset=utf8&parseTime=true")
	if err != nil {
		panic(err)
	}
	fmt.Println("db connect success")
	db.LogMode(true)
}

func main() {
	orderList := make([]*OrderInfo, 0, 10)
	fieldStr := "a.id,a.add_order_number,SUM(a.prize) as prize,b.add_series"

	err := db.Raw("select "+fieldStr+" from(SELECT * FROM order_info WHERE uid=? AND add_order_number!='' GROUP BY add_order_number) a"+
		" LEFT JOIN (SELECT add_order_number,add_series FROM order_info WHERE add_order_number in("+
		"SELECT add_order_number FROM order_info WHERE uid=? AND add_order_number!='' GROUP BY add_order_number)"+
		" GROUP BY add_series ORDER BY add_series DESC LIMIT 1) b on a.add_order_number = b.add_order_number LIMIT ?,?",
		1, 1, 0, 10).Scan(&orderList).Error

	fmt.Println(len(orderList), err)
}
数据库没有数据，但是查出的len(orderList)=1
@jinzhu

**Comment by happyEgg** [comment]
其实这样查就有问题，
err := db.Raw("SELECT a.id,a.add_order_number,SUM(a.prize) as prize from(SELECT * FROM order_info WHERE uid=? AND add_order_number!='' GROUP BY add_order_number) a",1).Scan(&orderList).Error
是两个SELECT的问题吗？

**Comment by jinzhu** [comment]
Seems like it is caused by the `SUM(a.prize)`, it always returns a row.

**Comment by jinzhu** [comment]
![image](https://user-images.githubusercontent.com/6843/36088107-ae24ab4a-1010-11e8-9fc1-9d4650881c2d.png)
