### ISSUE TITLE
Use Unique columns

### ISSUE THREAD

**Issue by sredXNY** [jinzhu/gorm#1486]
Hi, I have a table with an Email column, the values of that column are unique, so I need to prevent the insert and update of the registers.
My question is, how can I catch the errors on create or update when that uniqueness constraint is violated? I don't want to show an ugly error that is returned by the database, is there any best practice to deal with these situations?

For example I am getting:

`(pq: duplicate key value violates unique constraint "uix_user_email")`

And don't want to show that message, and neither makes if statements to switch between the errors. How do you handle it? thank you!

**Comment by jinzhu** [comment]
I guess you need to format the error message by yourself... make it more human readable

**Comment by zhangriyueming** [comment]
@jinzhu Is there an option to turn off the messages?

These messages come from the `db.Create()`, so even if formatted it by ourselves `(pq: duplicate key value violates unique constraint "uix_user_email")` still shows up.

**Comment by victorsteven** [comment]
@zhangriyueming have you formatted it better? I am also having the same issue.
