### ISSUE TITLE
默认映射规则能否支持大写？

### ISSUE THREAD

**Issue by chenjpu** [jinzhu/gorm#1487]
结构体字段映射数据库列名的默认规则是为小写，

能否支持大写？因为数据库设计字段都是大写规则

     type User struct {
             ID uint             // column name will be `ID`
             Name string         // column name will be `NAME`
             Birthday time.Time  // column name will be `BIRTHDAY`
             CreatedAt time.Time // column name will be `CREATED_AT`
     }

**Comment by cage1016** [comment]
```go
type User struct {
	ID        uint      `gorm:"column:ID"`
	Name      string    `gorm:"column:NAME"`
	Birthday  time.Time `gorm:"column:BIRTHDAY"`
	CreatedAt time.Time `gorm:"column:CREATED_AT"`
}
```
You can assign column as you want by declare `gorm:column"custom-column-name"`

**Comment by wdqzdd** [comment]
column:CREATED_AT
这个数据格式下划线 是DB需要的格式？
