### ISSUE TITLE
可以直接从数据库表生成gorm的golang结构体吗? 

### ISSUE THREAD

**Issue by zeropool** [jinzhu/gorm#1489]
XORM有这个功能，gorm也有这个就完美了，对项目移植很有用

**Comment by panjf2000** [comment]
同问，解决了吗？

**Comment by yan234280533** [comment]
同问，这个功能很重要

**Comment by jinzhu** [comment]
There are some tools existing, eg https://github.com/Shelnutt2/db2struct 

Maybe you could just use that.
