### ISSUE TITLE
"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DEFAULT VALUES' at line 1"

### ISSUE THREAD

**Issue by benguild** [jinzhu/gorm#1491]
Inserting an empty struct (with no columns defined) using a model that ONLY has ID/autoincrement value:
```go

type Table struct {
  ID int
}
```

... Generates the following unsupported SQL that is unsupported by MySQL 5.6:
```sql
INSERT INTO `TABLE` DEFAULT VALUES
```

Which generates: 
> "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DEFAULT VALUES' at line 1"

... It needs to be:
```sql
INSERT INTO `TABLE` DEFAULT VALUES ()
```

**Comment by jinzhu** [comment]
FIxed, thank you for your report.
