### ISSUE TITLE
self referencing of belongs-to

### ISSUE THREAD

**Issue by jqs7** [jinzhu/gorm#1493]
### What version of Go are you using (`go version`)?

go version go1.8.3 linux/amd64

### Which database and its version are you using?

mysql  Ver 15.1 Distrib 5.5.52-MariaDB, for Linux (x86_64) using readline 5.1

### What did you do?

My Model:
```go
type User struct {
    ID string `gorm:"primary_key"`
    BelongsToUser string
    BelongsTo *User `gorm:"ForeignKey:BelongsToUser"`
}
```
expecting for a belongs-to referencing but behaving as has-one referencing

**Comment by jinzhu** [comment]
Change to?

```go
type User struct {
    ID string `gorm:"primary_key"`
    BelongsToID string
    BelongsTo *User
}
```

**Comment by tab1293** [comment]
What if you have struct property names you can not change?
```go
type User struct {
    UUID string `gorm:"primary_key"`
    BelongsToUUID string
    BelongsTo *User
}
```

I can not easily change the struct property name of `BelongsToUUID` to `BelongsToID`. Can I specify in some kind of tag?

**Comment by vcraescu** [comment]
Same issue here.

**Comment by goors** [comment]
same here ...
