### ISSUE TITLE
Use of Select() inside custom preloading

### ISSUE THREAD

**Issue by Ganitzsh** [jinzhu/gorm#1494]
Hi,

I was trying to do the following:

```go
type A struct {
  Foo string
  Bar int
  Bs []B `gorm:"many2many:a_b`
}

type B struct {
  Field string
  As A[] `gorm:"many2many:a_b`
}

...

db.Preload("As", func(db *gorm.DB) *gorm.DB {
  return db.Select("foo").Order("bar ASC")
}).First(&B{})
```

But the query that is executed is 

```sql
SELECT * FROM "as" .... ORDER BY bar ASC
```

Obviously custom preloading doesn't handle `Select()` when retrieving a `many2many` association.

Is it wanted?

**Comment by jinzhu** [comment]
This should been fixed, thank you for your report.

**Comment by jemmycalak** [comment]
i have same problem, is that fixed ?

**Comment by Djumpen** [comment]
@jinzhu Faced with same problem, `Select()` is not working properly for m2m associations.
I am using m2m and 1toM connections at the same time
