### ISSUE TITLE
Avoid Gorm of add underscore _ on columns with capitals letters

### ISSUE THREAD

**Issue by sredXNY** [jinzhu/gorm#1495]
HI,I have a struct in Go, and the fields can be in this format:

```
FirstField
SecondField
ThirdField
etc
```

When the migration is executed by gorm, it replaces the letters in mayus and also add underscore, the result is something like:

```
first_field
second_field
third_field
```

Is there any way to avoid this behaviour? and let the columns names as defined in the struct?

**Comment by andreynering** [comment]
Overriding using struct tags:

```go
type Model struct {
        FirstField  string `gorm:"column:FirstField"`
        SecondField string `gorm:"column:SecondField"`
        // ...
}
```

**Comment by sredXNY** [comment]
@andreynering thank you!!
