### ISSUE TITLE
Can gorm support table varible in db.Exec() ?

### ISSUE THREAD

**Issue by botieking** [jinzhu/gorm#1497]
I come accross a problem recently. When I want to use gorm lib to communicate with my database, i find that `db.Exec` can not support `table variable`. For example, I want to execute the following sql through gorm:

```go
db.Exec("update ? set id = id - 1 where id >= ? order by id desc", my_test_table, id)
```

I want to pass both `table name` and `id` to sql string, but finally I got a error that said my sql string is not valid. I think gorm can not support passing `table name` to sql string when I execute `raw sql` by db.Exec function.

So I give a solution to solve the problem. we can define `#` to replace the table name, when we call the db.Exec function, we will replace the `#` to real table name firstly and we have not changed the inner code logic of db.Exec.

the code modified is below:
```go
// Exec execute raw sql
func (s *DB) Exec(sql string, values ...interface{}) *DB {
        scope := s.clone().NewScope(nil)
        if strings.Contains(sql, "#") {
                sql = strings.Replace(sql, "#", values[0].(string), 1)
                values = values[1:]
        }       
        generatedSQL := scope.buildWhereCondition(map[string]interface{}{"query": sql, "args": values})
        generatedSQL = strings.TrimSuffix(strings.TrimPrefix(generatedSQL, "("), ")")
        scope.Raw(generatedSQL)
        return scope.Exec().db
}

```

finally, we can write our new code bellow:

```go
db.Exec("update # set id = id - 1 where id >= ? order by id desc", my_test_table, id)
```

**Comment by jinzhu** [comment]
It supports table variable, but not for table name.

**Comment by emmanuel-isaac** [comment]
@botieking Did you try

```
db.Exec(`update ` + my_test_table +  ` set id = id - 1 where id >= ? order by id desc`,  id)
```
?
