### ISSUE TITLE
Parameterized arguments does not work in Exec.

### ISSUE THREAD

**Issue by Storm75** [jinzhu/gorm#1498]

**Comment by AnimusPEXUS** [comment]
confirming. got same issue.
trying to work with sqlcipher and it's Key/ReKey PRAGMA.

code line
self.db.Exec("PRAGMA key = ?;", value) .Error

gets this .Debug() messages:
({some codeline}) 
[2017-07-16 04:39:09]  near "?": syntax error 
({some codeline}) 
[2017-07-16 04:39:09]  [0.17ms]  PRAGMA key = '123';

but "PRAGMA key = '123';" isn't actually executed and db goes unencrypted.

manually replacing ? with actual value - goes ok.

**Comment by jinzhu** [comment]
Because PRAGMA doesn't support that? you could write code like this

```go
db.Exec("select * from users where name = ?", "hello")
```
