### ISSUE TITLE
Documentation: Transaction example does not include error check for db.Begin

### ISSUE THREAD

**Issue by aurelijusbanelis** [jinzhu/gorm#1500]
Using example in http://jinzhu.me/gorm/advanced.html#a-specific-example you can get `panic` error.
If someone have version before https://github.com/jinzhu/gorm/pull/1412

## Possible use case
Assuming there is `MySql 5.7.17-13` with `user` `password` on `localhost` with database `dbName`
```go
db, err := gorm.Open("mysql", "user:password@tcp(localhot:3306)/dbName?charset=utf8&parseTime=True&loc=Local")

transactions := []*gorm.DB{}
for i := 0; i < 10000; i++ {
	tx := db.Begin()

	transactions = append(transactions, tx)
	if tx.Error != nil {
		// Too many connections
		break;
	}
}

for _, tx := range transactions {
	// Panic goes here
	tx.Rollback()
}

db.Close()
```

## Suggested documentation fix
```go
func CreateAnimals(db *gorm.DB) err {
	tx := db.Begin()
	if tx.Error != nil {
		return tx.Error
	}
	// Note the use of tx as the database handle once you are within a transaction

	if err := tx.Create(&Animal{Name: "Giraffe"}).Error; err != nil {
		tx.Rollback()
		return err
	}

	if err := tx.Create(&Animal{Name: "Lion"}).Error; err != nil {
		tx.Rollback()
		return err
	}

	tx.Commit()
	if tx.Error != nil {
		return tx.Error
	}
	return nil
}
```

**Comment by jinzhu** [comment]
Added, thank you for your suggestion.

**Comment by hlj2722** [comment]
@jinzhu  if tx.Commit().Error !=nil , whether to add tx.Rollback(), for example `if tx.Commit().Error != nil {
				tx.Rollback()
			}`

**Comment by vstorm** [comment]
> @jinzhu if tx.Commit().Error !=nil , whether to add tx.Rollback(),
> for example
> `if tx.Commit().Error != nil { tx.Rollback() }`

I also wonder whether I should add tx.Rollback after commit error.
