### ISSUE TITLE
"AddForeignKey" with table name that is a reserved MySQL word always results in error.

### ISSUE THREAD

**Issue by benguild** [jinzhu/gorm#1507]
Not sure if this is worth fixing, but it's something I noticed.

**Comment by jinzhu** [comment]
Hello @benguild 

Could you write down the code that cause this issue? as I found the table name should be quoted already...

**Comment by benguild** [comment]
Something like this...

```go
db.Model(&TableType{}).AddForeignKey("columnName", "case(id)", "RESTRICT", "RESTRICT");
```

**Comment by jinzhu** [comment]
the generated SQL looks like:

```sql
ALTER TABLE `toys` ADD CONSTRAINT toys_columnName_case_id_foreign FOREIGN KEY (`columnName`) REFERENCES case(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
```

Looks correct?

**Comment by benguild** [comment]
No, because `case` is a reserved word. So that's why it wouldn't work.

Try adding backticks around `case` and the column name `id` as well to be safe:
```sql
ALTER TABLE `table_types` ADD CONSTRAINT table_types_columnName_case_id_foreign FOREIGN KEY (`columnName`) REFERENCES `case`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
```

**Comment by benguild** [comment]
It wouldn't hurt to also include backticks or quotes around the constraint name.

**Comment by jinzhu** [comment]
Maybe better to escape it by yourself when calling the `AddForeignKey` method, looks tricky to hack the arguments that you passed in.
