### ISSUE TITLE
更新时使用select，控制只更新部分变量。如果更新的变量为空，则无法更新

### ISSUE THREAD

**Issue by yan234280533** [jinzhu/gorm#1509]
我的sql语句是这样的：
	where := &models.ApplicationModel{
		AppId:               app.AppId,
		ClusterId:     app.ClusterId,
		AppName: app.AppName,
	}

	logger.Infof("appUpdate %v.",appUpdate)

	ret := db.Model(&models.ApplicationModel{}).Where(where).
		Select(appUpdate).
		Update(app)

更新的作用域appUpdate []string{"deployResourceList"}  

使用这个更新语句，如果app.DeployResourceList为“‘’，则该更新语句不会执行

我的结构体：
type ApplicationModel struct {
	ID                   uint64  `gorm:"primary_key;AUTO_INCREMENT;column:id"`
	AppId                uint64  `gorm:"column:appId;index"`
	ClusterId            string  `gorm:"column:clusterId"`
	AppName              string   `gorm:"column:appName"`
	Description          string  `gorm:"column:description"`

	StoreResourceList    string  `gorm:"column:storeResourceList"`
        StoreConfig          string  `gorm:"column:storeConfig"`
	StoreConfigVersion   string  `gorm:"column:storeConfigVersion"`

	DeployResourceList   string  `gorm:"column:deployResourceList"`
	DeployConfig         string  `gorm:"column:deployConfig"`
	DeployConfigVersion  string  `gorm:"column:deployConfigVersion"`

	Version              string  `gorm:"column:version"`
	State                string  `gorm:"column:state"`

	// 时间信息
	CreatedAt           time.Time  `gorm:"column:createdAt"`
	UpdatedAt           time.Time  `gorm:"column:updatedAt"`
	DeleteAt            time.Time  `gorm:"column:deletedAt"`
}

**Comment by jinzhu** [comment]
Please follow https://github.com/jinzhu/gorm/blob/master/.github/ISSUE_TEMPLATE.md
