### ISSUE TITLE
How to remove duplicates from an array

### ISSUE THREAD

**Issue by anoopabbu** [jinzhu/gorm#1511]
Please help me out to remove duplicate as Distinct is not supported by jinzhu gorm.
u := []UserDetailss{}
err = db.Table("users").Select("id,username,company_id").Where("company_id like ? AND roles=?", "%," + id + ",%",1).Find(&u).Error
if err != nil {
Logger.Println(err)
return us, err
}

**Stack**
    Go 1.8.3 darwin/amd64
    SQLite 3.16.0

**Comment by ralli** [comment]
According to #542 

`Select("DISTRINCT(xxx)")` 

should work.

**Comment by wisnuvb** [comment]
sorry, I have not succeeded in using the distinct function as above

`(Error 1305: FUNCTION table_name.DISTRINCT does not exist)`

What should I do? thank you

**Comment by ralli** [comment]
I just noticed, you are using the word "DISTRINCT" (with 'R') instead of DISTINCT. Does that help?

**Comment by wisnuvb** [comment]
I'm not careful, I think it's one (`DISTRINCT`) of the features of gorm.
I follow this [#542](https://github.com/jinzhu/gorm/issues/542), so use `DISTRINCT` instead of `DISTINCT`.

Thank you, all goes well.
