### ISSUE TITLE
Drop table CASCADE (feature request)

### ISSUE THREAD

**Issue by rsec** [jinzhu/gorm#1514]
Drop table with CASCADE option.

It's useful for unit tests in tables with Foreign Keys.

Maybe something like this:

    db.Set("gorm:table_options", "CASCADE").DropTableIfExists(&SomeTable{})
    db.Set("gorm:table_options", "CASCADE").DropTable(&SomeTable{})

**Comment by chrislewispac** [comment]
+1

**Comment by wowissu** [comment]
+1

**Comment by ShahriyarR** [comment]
Still unable to get it to work with `gorm:table_options`. 
Instead I have called SQL statement as:
`db.Exec("DROP TABLE IF EXISTS users CASCADE")`
