### ISSUE TITLE
Duplicate entry for key

### ISSUE THREAD

**Issue by asxalex** [jinzhu/gorm#1515]
I'm using gorm and I wonder how can i get the error when i use the c.Save()?

I'm using gorm for my golang project. The underlying database is mysql, besides the gorm framework, I added a unique index for two column with the below statement manually in mysql prompt:

```
CREATE UNIQUE INDEX unique_name ON users(name, account_type)
```

and then, I use the c.Save(user) for the new record. however, when i insert two record with same name and account_type, but I cann't get it because no error is returned by Save method of DB.

thanks in advance!

**Comment by asxalex** [comment]
I got it, it can be caught with

```
MyDB.Save(record).GetErrors()
```

**Comment by Allendar** [comment]
@asxalex It's lighter to check with `.Error()` to see if any errors occurred. If multiple errors are thrown, you might not always care and it will essentially cost overall more resources if you always ask to get all errors. Just my 2 cents :)

**Comment by asxalex** [comment]
@Allendar aha, got it, thanks a lot!
