### ISSUE TITLE
DefaultTableNameHandler is not enough

### ISSUE THREAD

**Issue by SammyROCK** [jinzhu/gorm#1518]
DefaultTableNameHandler is not powerful enough.

Inside model_struct.go the function TableName calls for ToDBName and, sometimes, inflection.Plural when the TableName is not implemented in the struct.
Since golang does not support type hierarchy it's troublesome to implement TableName function for each table structure.
Therefore it's a limiting factor that requires unnecessary code to bypass the default behavior of nonexistent TableName function in order not to change the naming pattern of the database.

Since Pull Requests signalize to open an issue before adding new features I'm here to discuss if this is truly a matter and how to properly address it.

**Comment by jinzhu** [comment]
Sorry, but I don't get what you are try to do, could you make an example that `DefaultTableNameHandler` can't complete your requests?

Feel free to create a new issue then.
