### ISSUE TITLE
db.First() adds not necessary ORDER BY when specifying table db.Table()

### ISSUE THREAD

**Issue by mykytanikitenko** [jinzhu/gorm#1521]
My table "sales" don't have primary key and I don't need ORDER BY statement which was added by GORM. 

```go
    var result struct {
 		ID int64
    }

    err = db.
		Table("sales").
		Select("billing_groups.id").
		Joins("INNER JOIN numbers ON sales.number_id = numbers.id").
		Joins("RIGHT JOIN billing_groups ON numbers.billing_group_id = billing_groups.id").
		Joins("INNER JOIN users AS suppliers ON billing_groups.user_id = suppliers.id").
		Joins("INNER JOIN users ON sales.user_buyer_id = users.id").
		Where(`(billing_groups.id = ? AND suppliers.parent_id = ?) OR
					 (numbers.billing_group_id = ? AND sales.user_buyer_id = ?)`,
			billigGroupId,
			userId,
			billigGroupId,
			userId).
		First(&result).
		Error
```

Generated query:

```sql
SELECT billing_groups.id
FROM "sales"
  INNER JOIN numbers ON sales.number_id = numbers.id
  RIGHT JOIN billing_groups ON numbers.billing_group_id = billing_groups.id
  INNER JOIN users AS suppliers ON billing_groups.user_id = suppliers.id
  INNER JOIN users ON sales.user_buyer_id = users.id
WHERE ((billing_groups.id = '986' AND suppliers.parent_id = '112') OR
       (numbers.billing_group_id = '986' AND sales.user_buyer_id = '112'))
ORDER BY "sales"."id" ASC
LIMIT 1
```

If I'm specifying Order by db.Order(), it just adds it as addition to sales.id. Workaround is use Limit(1) and Find()

**Comment by Allendar** [comment]
`First()` works correctly, but it probably doesn't do what you expect. It literally means you want the first of a result-set, not a single-result-select.

`Limit(1).Find(&result)` is what you're aiming for. It's not the alternative, but the way it should be used.

Don't worry; you're not the only one who made this wrong assumption :)

**Comment by mykytanikitenko** [comment]
As for me, GORM is library, not framework. It shouldn't do something magical, like this. Would be great to keep it as simple, as possible, it's a go-way. If First() needs magic behaviour, it should be sugar for Limit-Find-Order, or absolutely removed from api. I have clear view how my query should be looks like. With problem #1519 I had to inline huge query in 150 lines into program code. I would never complaining, if it was monster like .NET and Entiity Framework :), but it's really absolutely not what I was expecting for.

**Comment by svarogg** [comment]
I must chime in and say that this behavior is very unintuitive.
Every ORM I've used in any language had a .First() method that returned the first item in the ordering specified by the caller.

Specifically for us this caused a huge performance problem in a query with optimized indexes. Adding the "ORDER BY id" caused the query to use the wrong indexes, and made it unbelievably slower.

After looking into the code, reading documentation, etc. I understood I had to use .Limit(1).Find(), but seriously, something as trivial as .First should require the user to read documentation.

**Comment by jinzhu** [comment]
You still could customize the `order by` to whatever with `Order`.

From my view, `First` should always return the exact first object for all databases, just like the method's meaning, no unexpected behavior should happen, like Postgres will return record by its updated time...
