### ISSUE TITLE
Implement middleware to track all operations

### ISSUE THREAD

**Issue by sredXNY** [jinzhu/gorm#1522]
Hi, I am currently using Gorm in my project, it's a RESTful API. I want to track all operations that are executed with the DB instance that I created using `gorm.Open` . With "track" I mean is, that I want to save the logs of create, update and delete operations. 
I can create a general function to insert the actions in the database, but then I will have to call this function everywhere that I perform a Create, Update or Delete operation and I want to avoid that. So, I am starting to think if there's a way to implement a kind of middleware that will make this operation everytime that some action Create,Update or Delete is called, is possible to do that in Gorm? in afirmative case, how can I do it?
Thanks a lot!

**Comment by smacker** [comment]
You can see example here: https://github.com/smacker/newrelic-context/blob/master/nrgorm/gorm.go

**Comment by jinzhu** [comment]
Also you could overwrite the Logger

**Comment by xj-zh-dev** [comment]
it's based on gorm old version, how does the latest version support newrelic?
