### ISSUE TITLE
[Serious bug?]  wrong source type for join table handler  

### ISSUE THREAD

**Issue by seaguest** [jinzhu/gorm#1523]
hello,

I have updated gorm recently which caused a "wrong source type for join table handler  " problem.

Here is the code:

`

	if err = db.Model(&stream).Related(&stream.Groups, "Groups").Error; err != nil {
		logger.Error(err)
		c.AbortWithStatus(http.StatusInternalServerError)
		return
	}

    // stream many_to_many group 
`

Before this update, the sql shows correctly with join.

But now, it shows:

`

	(/root/Stream/src/mms/controller/mms/stream.go:184) 
	[2017-07-06 11:06:35]  [0.03ms]  SELECT * FROM `resource_group`  

	(/root/Stream/src/mms/controller/mms/stream.go:184) 
	[2017-07-06 11:06:35]  wrong source type for join table handler 

`

the join part is missing and the error occurs, if I switch to the earlier gorm version, it works fine.

Could someone help?

**Comment by pcram-techcyte** [comment]
I'm running into the same problem.  It was working on an earlier version, but is broken after the commit `eae7f6b`.  

### What version of Go are you using (`go version`)?
go version go1.8.1 darwin/amd64

### Which database and its version are you using?
mysql: stable 5.7.18

### What did you do?
This is the simplest reproducible test program I could come up with.

```go
package main

import (
	"fmt"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

type Product struct {
	gorm.Model
	Code       string
	Price      uint
	Attributes []Attribute `gorm:"many2many" json:"attributes"`
}

type Attribute struct {
	gorm.Model
	Value string `json:"value"`
}

type ProductWithFlag struct {
	Product
	InStock bool
}

func main() {

	db, _ := gorm.Open("sqlite3", "test.db")
	defer db.Close()

	db.AutoMigrate(&Product{})
	db.AutoMigrate(&Attribute{})
	db.Create(&Product{Code: "L1212", Price: 1000})

	// Raw SQL in production has a complicated calculation instead of a static value...
	rows, _ := db.Raw("SELECT *, 1 FROM products").Rows()
	defer rows.Close()

	for rows.Next() {
		// Everything works fine if I replace the next line with "Product" instead of "ProductWithFlag"
		var row ProductWithFlag
		db.ScanRows(rows, &row)
	}

	product := Product{}
	db.Model(Product{}).First(&product)

	attributes := []Attribute{}
	if err := db.Model(product).Association("Attributes").Find(&attributes).Error; err != nil {
		// getting "wrong source type for join table handler"
		panic(err)
	}

	fmt.Println("Success!")
}
```

**Comment by jinzhu** [comment]
This should be fixed, sorry for that.
