### ISSUE TITLE
遇到一个 int  = 0的update不操作的问题

### ISSUE THREAD

**Issue by rfyiamcool** [jinzhu/gorm#1524]
```
	db.Model(&MasterInjectInfo{}).Where("task_id = ?", task_id).Update(MasterInjectInfo{
		Status:    status,
		UpdatedAt: time.Now(),
		Extra:     extra,
		Code:      code,
		Hostname:  hostname,
		Size:      size,
	})
```

size 默认为 -1 ，当size 为 0 时，不会更新....   当size为 >0 时，产生更新操作....

**Comment by Mikejinhua** [comment]
这不科学

**Comment by Allendar** [comment]
What does your `MasterInjectInfo` entity definition look like?

**Comment by jinzhu** [comment]
http://jinzhu.me/gorm/crud.html#update

blank fields won't be updated by default, 0 is blank for int

**Comment by rfyiamcool** [comment]
yes, thank u.

**Comment by xs23933** [comment]
so we how to update this filed to 0?

**Comment by panghu1024** [comment]
> so we how to update this filed to 0?

1.change the field to string in your struct definition.
2.try to use map instead of struct.

**Comment by mannixli** [comment]
> so we how to update this filed to 0?

https://stackoverflow.com/questions/54523765/update-with-0-value-using-gorm/57069554#57069554?newreg=8251584d40754e1c9a1656c2bb56bbd0
