### ISSUE TITLE
how to set id field with primary_key but without autoincrement ?

### ISSUE THREAD

**Issue by eosite** [jinzhu/gorm#1527]
how to set id field with primary_key but without autoincrement ?

`
type Model struct {
    ID         int64 `gorm:"AUTO_INCREMENT:no;" sql:"bigint;NOT NULL;primary_key;"`
    CreateTime time.Time
    UpdateTime time.Time
}
`
 it will code:
 CREATE TABLE "users" ("id" integer primary key autoincrement NOT NULL)

i will the code is:
 CREATE TABLE "users" ("id" bigint primary key NOT NULL)

**Comment by rfyiamcool** [comment]
+1

**Comment by nguyenthenguyen** [comment]
Has the same issue
Migrate with primary column with int type will create table has auto increment
```
type Realtime struct {
	DeviceID uint16 `gorm:"primary_key:yes;column:deviceID"`
	Data     string `gorm:"type:text;not null"`
}

func (r *Realtime) TableName() string {
	return "Realtimes"
}
```
![screenshot from 2017-08-13 13-58-30](https://user-images.githubusercontent.com/8535630/29246881-84f336a4-802f-11e7-8373-05e96d942e79.png)

**Comment by kolok** [comment]
+1

**Comment by jinzhu** [comment]
Refer PR #1643
