### ISSUE TITLE
deleted_at required for simple query on existing table

### ISSUE THREAD

**Issue by magegu** [jinzhu/gorm#1534]
Hi there!

### What version of Go are you using (`go version`)?
go1.8.3 darwin/amd64

### Which database and its version are you using?
pg 9.6 (via postgres.app)

### What did you do?

I have an existing RubyOnRails Application and want to query one table from gorm.
Unfortunately the query returns an error with:  "pq: column mailings.deleted_at does not exist", which is true. The question is: why does GORM require my table to have this column?

FYI: my mailings table contains much more columns then the ones used in the struct but no deleted_at column.

```go
package main

import (
	"fmt"
	"time"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
)

type Mailing struct {
	gorm.Model
	ID        int64
	Code   string
	UpdatedAt *time.Time
	CreatedAt *time.Time
}

func main() {
	db, err := gorm.Open("postgres", "host=localhost user=magegu dbname=ds_dev sslmode=disable password=")
	defer db.Close()
	fmt.Printf("%s\n", err)
	db.LogMode(true)
	var mailing Mailing
	db.First(&mailing) //crash with: pq: column mailings.deleted_at does not exist
	fmt.Printf("%s\n", mailing.Barcode)
}
```
result: 

```
%!s(<nil>)

(/Users/magegu/code/godest/example.go:25)
[2017-07-13 09:24:32]  pq: column mailings.deleted_at does not exist

(/Users/magegu/code/godest/example.go:25)
[2017-07-13 09:24:32]  [2.50ms]  SELECT * FROM "mailings"  WHERE "mailings"."deleted_at" IS NULL ORDER BY "mailings"."id" ASC LIMIT 1
```

**Comment by mykytanikitenko** [comment]
Because you have nested gorm.Model struct in your model.

**Comment by adaRn** [comment]
For those taking theirs baby steps with GORM and probably following some tutorials right now, here you can find what `gorm.Model` does and what it's for http://doc.gorm.io/models.html#conventions

**Comment by GerryG** [comment]
The problem here is the gorm.Model, if you want it, and you don't have an deleted_at column in your db table, you need a way to tell it not to use that column name in queries. If you could ignore it with the right tags, that might be a workaround, but I don't think that works.

**Comment by matthewharrilal** [comment]
But doesn't the gorm.Model function already populate your schema with the deleted_at attribute?
