### ISSUE TITLE
AddForeignKey not working

### ISSUE THREAD

**Issue by DaniloPolani** [jinzhu/gorm#1535]
### What version of Go are you using (`go version`)?
1.8.1 linux/amd64

### Which database and its version are you using?
MySQL 5.7.18-0ubuntu0.16.04.1

### What did you do?
I'm trying to set foreign keys for a model, but AddForeignKey it's not generating them. Placing it before or after the automigration doesn't change the fact. I can of course retrieve values with `.Related()`, but in the table `user_id` and `product_id` are not foreign keys (neither indexes).

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

func init() {
	var err error
	db, err = gorm.Open("mysql", "gorm:gorm@/dbname?charset=utf8&parseTime=True")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

func main() {
	type Product struct {
		gorm.Model
		Name string
		Code string
	}
	type User struct {
		gorm.Model
		FirstName  string
		LastName   string
		Email      string
		Password   string
		Products   []UserProduct
	}

	type UserProduct struct {
		gorm.Model
		User      User    // Belongs To
		UserID    int     `sql:"type:bigint REFERENCES users(id)"` // Foreign key
		Product   Product // Belongs To
		ProductID int     `sql:"type:bigint REFERENCES products(id)"` // Foreign key
	}

	// Foreign keys
	db.Model(&UserProduct{}).AddForeignKey("user_id", "users(id)", "CASCADE", "RESTRICT")
	db.Model(&UserProduct{}).AddForeignKey("product_id", "products(id)", "CASCADE", "RESTRICT")

	db.Set("gorm:table_options", "ENGINE=InnoDB").AutoMigrate(
		&User{},
		&Product{},
		&UserProduct{},
	)
}
```

**Comment by MarcusMann** [comment]
It really does not work! I'm also waiting for a return

**Comment by DaniloPolani** [comment]
Find out the problem: the columns type mismatched. My `user_id` was `BIGINT(20)` and `user(id)` `INT(11)`. I deleted the table user_products and recreated it with `int(11)` as type of foreign keys and now it works. 

`AddForeignKeys` must be **after** the `AutoMigrate`. @MarcusMann

**Comment by ostretsov** [comment]
There is two FKs:
1) created with `REFERENCES users(id)`;
2) created by calling `AddForeignKey("user_id", "users(id)"...`.
