### ISSUE TITLE
gorm分表有什么伪代码借鉴么？

### ISSUE THREAD

**Issue by rfyiamcool** [jinzhu/gorm#1537]
我现在是通过  建立多个Struct来实现的分表，比如 tb1, tb2, tb3  一连串的table... 这些表数据结构都一样，只是table不一样.

我想，gorm应该也有些方法可以让多个表共用一个struct，最少不至于写多个struct吧。

@jinzhu   谢谢

```
type MainTask1 struct {
	Id         int64     `gorm:"AUTO_INCREMENT"`
	TaskId     string    `gorm:"size:255" sql:"not null`
	AppId      string    `gorm:"size:255" sql:"not null`
	Priority   int       `gorm:"colum:priority" sql:"not null;default:1"`
}

type MainTask2 struct {
	Id         int64     `gorm:"AUTO_INCREMENT"`
	TaskId     string    `gorm:"size:255" sql:"not null`
	AppId      string    `gorm:"size:255" sql:"not null`
	Priority   int       `gorm:"colum:priority" sql:"not null;default:1"`
}

type MainTask3 struct {
	Id         int64     `gorm:"AUTO_INCREMENT"`
	TaskId     string    `gorm:"size:255" sql:"not null`
	AppId      string    `gorm:"size:255" sql:"not null`
	Priority   int       `gorm:"colum:priority" sql:"not null;default:1"`
}

等等...
```

**Comment by mykytanikitenko** [comment]
I translated your message by google translate, but if you want a separate table for each entity, you have to create method (MainTaskMagicalNumber) TableName() string { return "MySpecialTableName" } for each struct, because it uses by default table name, as struct name in lower snake case in the plural.

**Comment by dotNetDR** [comment]
```go
db.Where("id in (?)", ids).Table("tb1").Find(&mainTaskList)
```

**Comment by xuhrc** [comment]
if you need execute queries, do it like this way
`err = d.MeesageDB.Table(tableName).Where("receiver_id = ?", userID).Find(&msgNotifyList).Error`

if you need auto migration, use gormigrate
```
// for auto migrate use only
func (mn MessageNotify) TableName2() string{
	return fmt.Sprintf("t_message_notify_%d", mn.ID)
}
// get table name by user id hash
func (mn MessageNotify) TableName() string {
	al := fnv.New32()
	_, err := al.Write([]byte(mn.ReceiverID))
	if err != nil {
		log.Error(err)
	}
	hashCode := al.Sum32()
	l := hashCode % uint32(configs.ServerConfig.MessageNotifyShardingNum)
	return fmt.Sprintf("t_message_notify_%d", l)
}
``` 
```
	for i := 0; i < configs.ServerConfig.MessageNotifyShardingNum; i++ {
		tx.AutoMigrate(&model.MessageNotify{})

		notify := &model.MessageNotify{}
		notify.ID = uint32(i)
		tx.Exec(fmt.Sprintf("CREATE TABLE %s (like %s)", notify.TableName2(), model.MessageNotify{}.TableName()))
	}
```

**Comment by cy21st** [comment]
type MainTask struct {
	Id         int64     `gorm:"AUTO_INCREMENT"`
	TaskId     string    `gorm:"size:255" sql:"not null`
	AppId      string    `gorm:"size:255" sql:"not null`
	Priority   int       `gorm:"colum:priority" sql:"not null;default:1"`
}

var demos []*models.MainTask 
Db.Where("1=1").Table("MainTask1").Find(&demos )

var demo models.MainTask 
demo.TaskId = "test"
Db.Table("MainTask2").Save(&demo)

**Comment by aihanjiao** [comment]
> if you need execute queries, do it like this way
> `err = db.Table(tableName).Where("receiver_id = ?", userID).Find(&msgNotifyList).Error`
> 
> if you need auto migration, try [gormigrate](https://github.com/go-gormigrate/gormigrate)
> 
> ```
> // for auto migrate use only
> func (mn MessageNotify) TableName2() string{
> 	return fmt.Sprintf("t_message_notify_%d", mn.ID)
> }
> // get table name by user id hash
> func (mn MessageNotify) TableName() string {
> 	al := fnv.New32()
> 	_, err := al.Write([]byte(mn.ReceiverID))
> 	if err != nil {
> 		log.Error(err)
> 	}
> 	hashCode := al.Sum32()
> 	l := hashCode % uint32(configs.ServerConfig.MessageNotifyShardingNum)
> 	return fmt.Sprintf("t_message_notify_%d", l)
> }
> ```
> 
> ```
> 	for i := 0; i < configs.ServerConfig.MessageNotifyShardingNum; i++ {
> 		tx.AutoMigrate(&model.MessageNotify{})
> 
> 		notify := &model.MessageNotify{}
> 		notify.ID = uint32(i)
> 		tx.Exec(fmt.Sprintf("CREATE TABLE %s (like %s)", notify.TableName2(), model.MessageNotify{}.TableName()))
> 	}
> ```

thanks for your great idea. i am trying this method
