### ISSUE TITLE
NextResultSet() support

### ISSUE THREAD

**Issue by crosslogic** [jinzhu/gorm#1540]
Hi, I have this use case where I need to do many selects statements and I want to avoid all the roundtrips to the database. 
I was suggested by Ben Darnell, to use NextResultSet() method which is in the sql package to do this.

So, that's the way I want to do it, but I couldn't find it in GORM. 

¿Is it possible to add support?

**Comment by jinzhu** [comment]
Use `Rows`?

**Comment by yusufozturk** [comment]
Can we reopen this issue please?

https://stackoverflow.com/questions/61859911/handle-multiple-resultsets-from-sql-in-go-lang-using-gorm

Thanks.
