### ISSUE TITLE
sql server auto migration ModifyColumn 生成sql语句问题

### ISSUE THREAD

**Issue by Migo24K** [jinzhu/gorm#1542]
异常信息：
mssql: “MODIFY”附近有语法错误。
生成sql:
ALTER TABLE "gf_web_order" MODIFY "TrdID" string

据我所知sql server 修改字段类型应该类似于
alter table 表名 alter column 列名 列类型 not null 

是我配置问题呢还是框架针对sql server生成的语句不正确

**Comment by jinzhu** [comment]
Should be fixed.
