### ISSUE TITLE
能不能暴露出一个根据struct得到tablename的方法？

### ISSUE THREAD

**Issue by oshmkufa2010** [jinzhu/gorm#1547]
需求如下：目前我的项目需要得到数据库表的元信息（比如这里的tablename），然后根据元信息对该数据库表的访问做限制

**Comment by rfyiamcool** [comment]
+1

**Comment by ipfans** [comment]
```go
type User struct {} // default table name is `users`

// set User's table name to be `profiles`
func (User) TableName() string {
  return "profiles"
}

func (u User) TableName() string {
    if u.Role == "admin" {
        return "admin_users"
    } else {
        return "users"
    }
}
```
like this?

// Disable table name's pluralization globally
db.SingularTable(true) // if set this to true, `User`'s default table name will be `user`, table name setted with `TableName` won't be affected
