### ISSUE TITLE
MSSQL - gorm uses 'LIMIT' in First() method

### ISSUE THREAD

**Issue by SecretGibbon** [jinzhu/gorm#1549]
### What version of Go are you using (`go version`)?
Go SDK 1.7.3

### Which database and its version are you using?
MS SQL Server 
github.com/denisenkom/go-mssqldb

### What did you do?
When First() method is called, gorm produces this sql statement:
SELECT * FROM "table"  WHERE ("table"."table_id" = '663') ORDER BY "table"."table_id" ASC LIMIT 1
which of course fails on:
Error: Incorrect syntax near 'LIMIT'.
SQLState:  S0001
ErrorCode: 102

It should be probably replaced with TOP(1) in SELECT clause when gorm generates the sql statement.

### Quick fix:
I am using Find() instead of First() ;)

**Comment by tlainevool** [comment]
I ran into this problem as well and realized that I hadn't imported the correct gorm dialect.

Adding
```
import {
    _ "github.com/jinzhu/gorm/dialects/mssql"
}
```

Fixed the problem for me.
