### ISSUE TITLE
sqlserver: Login error: unexpected EOF

### ISSUE THREAD

**Issue by happyEgg** [jinzhu/gorm#1550]
### What version of Go are you using (`go version`)?
1.8.3

### Which database and its version are you using?
sqlserver2000

### What did you do?

GORM, err = gorm.Open("mssql", "sqlserver://sa:123456@localhost:1433?database=wm")
我这样连接报错。Login error: unexpected EOF

**Comment by jinzhu** [comment]
works in CI
