### ISSUE TITLE
Embedded time fields do not appear to be supported

### ISSUE THREAD

**Issue by bbb31** [jinzhu/gorm#1556]
I have the below code:

```golang
// This is not used by gorm; it's used for custom timestamp for UnmarshalJSON
type CustomTime struct {
	time.Time
}

type Events struct {
        ID        int64      `json:"id,omitempty" gorm:"primary_key;not null"`
	Timestamp CustomTime `json:"timestamp,omitempty" gorm:"not_null;index;column:timestamp"`
}
```

When doing the migration, its giving me the following error: `(pq: column "timestamp" does not exist)`

**Comment by bbb31** [comment]
I have tried adding `sql:"type:timestamp"` to force the type; but that also does not work.

**Comment by bbb31** [comment]
If anyone runs into this issue in the future, I got around this by storing the time in just a string pre-unmarshal, then before storing in the DB converting the time:

```golang
	Timestamp     time.Time `json:"-" gorm:"not_null;index"`
	TimestampJSON string    `json:"timestamp,omitempty" gorm:"-"`
```

**Comment by mykytanikitenko** [comment]
I'm not sure, but try to implement Scan(interface{}) error method for your type which wrapping time.Time

**Comment by bbb31** [comment]
@mykytanikitenko do you have an example?

**Comment by mykytanikitenko** [comment]
@bbb31 https://github.com/jinzhu/gorm/pull/353

**Comment by jinzhu** [comment]
Use `Valuer/Scanner`

**Comment by koreset** [comment]
hey @jinzhu this is the same issue I am encountering.. Any examples of the Valuer/Scanner suggestion?
