### ISSUE TITLE
如何处理含嵌套 select 语句生成的临时表的sql语句？

### ISSUE THREAD

**Issue by SenZhangAI** [jinzhu/gorm#1561]
例如如下简单示例：

```sql
select temp_table.name
from (select * from my_table where gender = 'male' ) as temp_table
```

不必在于这条sql的细节，只是简单示意，
主要这种内部嵌套的 `(select .....) as table` 或者`(select ...) table` 的语法没找到gorm对应的函数

如果直接用字符串写这个sql当然没问题，不过内部的where语句需要处理的很灵活，
需要用gorm的Where函数，因此请教一下有没有函数可以处理嵌套select生成的临时表呢？

**Comment by sameor** [comment]
How to solve it ?
