### ISSUE TITLE
Changing the ID type may help

### ISSUE THREAD

**Issue by MarcusMann** [jinzhu/gorm#1567]
### What version of Go are you using (`go version`)?
1.8.3

### Which database and its version are you using?

Mysql

### Question?

Due to the large amount of data that can be taken inside a table I thought it best to place the ID of the uint64 type instead of just uint.

This can also help in converting who is receiving this data, eg:

**Let's say a user expects a userID, this data usually arrives in string format, and Go only provides the conversion to uint64.**

I know I have to manipulate the data manually instead of importing the gorm.Model structure

But it would be cool I came standard.

If you want I can do a pull request to update this.

**Comment by jinzhu** [comment]
It is not necessary to change `uint` to `uint64`, maybe just change database's column type for it should be ok.
