### ISSUE TITLE
mysql复合主键会抛出1075错误，应该是2个键都自增长的问题

### ISSUE THREAD

**Issue by KylinHe** [jinzhu/gorm#1568]
Before posting a bug report about a problem, please try to verify that it is a bug and that it has not been reported already, please apply corresponding GitHub labels to the issue, for feature requests, please apply `type:feature`.

DON'T post usage related questions, ask in https://gitter.im/jinzhu/gorm or http://stackoverflow.com/questions/tagged/go-gorm,

Please answer these questions before submitting your issue. Thanks!
复合主键创建表格的时候会抛出这个异常，可以默认取消自增长吗？
(Error 1075: Incorrect table definition; there can be only one auto column and it must be defined as a key) 

### What version of Go are you using (`go version`)?
1.7

### Which database and its version are you using?

5.6.24
### What did you do?

Please provide a complete runnable program to reproduce your issue.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

func init() {
	var err error
	// db, err = gorm.Open("sqlite3", "test.db")
	// Please use below username, password as your database's account for the script.
	// db, err = gorm.Open("postgres", "user=gorm dbname=gorm sslmode=disable")
	db, err = gorm.Open("mysql", "gorm:gorm@/dbname?charset=utf8&parseTime=True")
	// db, err = gorm.Open("mssql", "sqlserver://gorm:LoremIpsum86@localhost:1433?database=gorm")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

type DBResource struct {
	RoleID  int32   `bson:"-"          gorm:"primary_key"`	//角色id
	ID 	     int32	`bson:"_id"       gorm:"primary_key"`	//物品id
	Value   int32   `bson:"value"   gorm:"NOT NULL"`	//物品当前值
}


func main() {
	// your code here
       err := db.Set("gorm:table_options", "ENGINE=InnoDB").CreateTable(data).Error
	if err != nil {
		fmt.Println("failed")
	} else {
		fmt.Println("success")
	}
}
```

**Comment by KylinHe** [comment]
![image](https://user-images.githubusercontent.com/10087121/29261324-7d2dede2-8101-11e7-8c8a-95f748f39472.png)
跟了一下源码，这里是写的 || 有点费解，是不是该改成&&

**Comment by zjien** [comment]
@KylinHe so have you solved this issue?

**Comment by jinzhu** [comment]
Refer PR #1643
