### ISSUE TITLE
Support for cloudsqlpostgres driver/dialect type:feature

### ISSUE THREAD

**Issue by paulwalker** [jinzhu/gorm#1572]
Use of google's cloud sql proxy requires a special driver named `cloudsqlpostgres`. This requires the postgres dialect, but the postgres dialect instance itself is not public and cannot be accessed in a call to RegisterDialect.

If the individual dialects or the dialectsMap were public, it would allow client code of this package to register custom drivers such as cloudsqlpostgres: https://github.com/GoogleCloudPlatform/cloudsql-proxy#to-use-inside-a-go-program. Alternatively, consider adding support directly for cloudsqlpostgres by simply registering the existing postgres dialect with an additional key.

**Comment by cgestes** [comment]
Or just add in dialect_postgres.go:

```go
	RegisterDialect("postgres", &postgres{})
+	RegisterDialect("cloudsqlpostgres", &postgres{})
```

**Comment by cgestes** [comment]
I guess your patch and this one would be best. I'am making a PR.

Your patch allow to access already defined dialect, but it does add support for cloudsqlpostgres.

**Comment by paulwalker** [comment]
Right, my thinking was just to make the dialect map public and client code could use pre-registered dialects, as ours does now. But I won't complain about native support for `cloudsqlpostgres` as well. :-)

**Comment by tommg** [comment]
I'm really interested in this, but I have tried this patch and it doesn't seem to be working for me. I get the following problem:
`panic: sql: Register called twice for driver postgres goroutine 1 [running]: database/sql.Register(0xb5e0e5, 0x8, 0xe26e80, 0xe82800) /usr/local/go/src/database/sql/sql.go:50`

Any idea what I'm doing wrong here, having huge problems trying to get this to work with Postgres cloudsql
