### ISSUE TITLE
gorm.Table("a").Find(&b)连续执行时，从第二条开始出错

### ISSUE THREAD

**Issue by Croton-D** [jinzhu/gorm#1574]
在使用时发现一个问题，不知是我使用方法不正确还是bug。
type b struct {
        IntTypeID     int       `gorm:"column:intTypeID"`
	StrTypeName   string    `gorm:"column:strTypeName"`
	IntPrive      int       `gorm:"column:intPrive"`
}

func gettag() {
        db := gorm.GetDB()
        c  := b{}
        db.Table("a").Where("strTypeName = ?","aaa").Find(&c)
        db.Table("a").Where("strTypeName = ?","bbb").Find(&c)
        db.Table("a").Where("strTypeName = ?","ccc").Find(&c)
        db.Table("a").Where("strTypeName = ?","ddd").Find(&c)
}
执行后，打印出的sql执行语句为：
select * from `a` where (strTypeName = `aaa`)
select * from `a` where  intTypeID = "1" AND ((strTypeName = `bbb`))
select * from `a` where  intTypeID = "1" AND ((strTypeName = ccc`))
select * from `a` where  intTypeID = "1" AND ((strTypeName = `ddd`))
在数据库中，strTypeName==aaa 的记录，其intTypeID=1.明显地，其后的几条查询将第一条的结果的第一个元素的值作为了where条件。
请告知是否是 该方法不能如此使用
或者这是一个bug

**Comment by DehaiWang** [comment]
我感觉不是一个错误，是用法问题。
我的用法是每次执行数据库的操作时候都是用新的的 gorm.GetDB()，你可以看一下gorm的源码，他的查询的数据是复用的。

**Comment by DehaiWang** [comment]
`// Where return a new relation, filter records with given conditions, accepts `map`, `struct` or `string` as conditions, refer http://jinzhu.github.io/gorm/crud.html#query
func (s *DB) Where(query interface{}, args ...interface{}) *DB {
	return s.clone().search.Where(query, args...).db
}`

如果你用同一个db 多次操作，代码中的clone().

**Comment by DehaiWang** [comment]
> // Where return a new relation, filter records with given conditions, accepts `map`, `struct` or `string` as conditions, refer http://jinzhu.github.io/gorm/crud.html#query
func (s *DB) Where(query interface{}, args ...interface{}) *DB {
	return s.clone().search.Where(query, args...).db
}

> 
如果你用同一个db 多次操作，代码中的clone().

**Comment by jinzhu** [comment]
seems no problem for me.
