### ISSUE TITLE
Limit offset clause use value binding not working

### ISSUE THREAD

**Issue by DarthPestilane** [jinzhu/gorm#1575]
```go
var count = 100
var rows, queryErr = db.Raw("SELECT id FROM tb limit ? option max_matches = ? ", count, count).Rows()
if queryErr != nil {
	panic(queryErr)
}
```

This will go into the panic and when opened `db.LogMode(true)`, logs came out as:
`[2017-08-18 11:52:39]  [2.33ms]  SELECT id FROM tb limit '100' option max_matches = '100' `

It wrapped the binding value with `'`

and the error is `unknown command (code=22)`

Any solutions?

**Comment by mykytanikitenko** [comment]
Try db.Table("tb").Select("id").Limit("? option max_matches = ? ", count, count).Rows()
