### ISSUE TITLE
GetErrors() function should return Errors instead of []error

### ISSUE THREAD

**Issue by mehdy** [jinzhu/gorm#1591]
I was wondering shouldn't the [GetErrors()](https://github.com/jinzhu/gorm/blob/master/main.go#L700) function be like this since `Errors` has implemented the `error` interface?

```go
func (s *DB) GetErrors() Errors {
	if errs, ok := s.Error.(Errors); ok {
		return errs
	} else if s.Error != nil {
		return Errors{s.Error}
	}
	return Errors{}
}
```

**Comment by jinzhu** [comment]
I would prefer return `[]error`, easier to use and developers don't need to know the details of `Errors`
