### ISSUE TITLE
Column name mapping error when name is XXID

### ISSUE THREAD

**Issue by bastengao** [jinzhu/gorm#1594]
### What version of Go are you using (`go version`)?

go1.9 darwin/amd64

### Which database and its version are you using?

postgresql 9.6.4

### What did you do?

```go
type WIFI struct {
	SSID string
}
```

the field SSID of WIFI struct column name is mapping to "ss_id", but "ssid" is expected.

**Comment by sweetycode** [comment]
try this:
`type WIFI struct {
	SSID string `gorm:"column:ss_id"`
}`

**Comment by jinzhu** [comment]
https://github.com/jinzhu/gorm/blob/master/utils.go#L26
