### ISSUE TITLE
Auto-increment in Composite Primary Keys

### ISSUE THREAD

**Issue by dc0d** [jinzhu/gorm#1595]
In a composite primary key that includes integers, like as in:

```
type SentNotification struct {
	PushNotificationID string `gorm:"primary_key"`
	GroupID          int64  `gorm:"primary_key"`
	UserID           int64  `gorm:"primary_key"`
}
```

Gorm should not create auto-increment sequences. Because integers in a composite key are in most cases about referring other tables. Making them auto-increment has not any practical meaning (IMHO).

Currently the above code should be:

```
type SentNotification struct {
	PushNotificationID string `gorm:"primary_key"`
	GroupID          int64  `gorm:"primary_key" sql:"type:int8 NOT NULL DEFAULT 0"`
	UserID           int64  `gorm:"primary_key" sql:"type:int8 NOT NULL DEFAULT 0"`
}
```

Instead; to prevent gorm from creating `GroupID` and `UserID` as auto-increment ones.

Environment: Latest Gorm with PostgreSQL driver, Go 1.8.3.
Note: I've confirmed that this is not the desired behaviour and is a bug, on Gitter.

**Comment by WingGao** [comment]
Same problem
MySQL will raise `Error 1075: Incorrect table definition; there can be only one auto column and it must be defined as a key`

**Comment by enlight** [comment]
@dc0d Thanks for providing a workaround. For anyone else that stumbles upon this issue I'm using the MySQL driver and `gorm.Model` in most of the models, so I've created a composite primary key like so:

```go
type AccountOwner struct {
    AccountID    uint    `gorm:"primary_key" sql:"type:INT(10) UNSIGNED NOT NULL"`
    ExternalOwnerID    string    `gorm:"primary_key"`
    InternalOwnerID    uint    `gorm:"primary_key" sql:"type:INT(10) UNSIGNED NOT NULL"`
}
```
Note that `AccountID` and `InternalOwnerID` in this case are foreign keys referencing a `gorm.Model` ID (which is currently typed as a `uint`).
