### ISSUE TITLE
gorm should respect `Valuer` in where and other SQL clause builders

### ISSUE THREAD

**Issue by MOZGIII** [jinzhu/gorm#1600]
gorm should respect `Valuer` in where and other SQL clause builders.

Look at this code: https://github.com/jinzhu/gorm/blob/e5432b14d2f28ad759d8d6262c1f8a167d517f73/scope.go#L524-L556

It builds `where` condition from the values specified in the query.
As you can see, that code a list of types that are supported. Currently it seems there's no way to extend it with custom types. But there should be.

Consider this listing (mey not be accurate, just for you to get the point):

```go
type ID uint64

type A struct {
    ID ID
    /* ... */
}

id := ID(123)
var a A

db.First(&a, id)
```

Guess what SQL query will be sent?

This one:
```
SELECT * FROM "a"   ORDER BY "a"."id" ASC LIMIT 1
```

You probably expected something like this:
```
SELECT * FROM "a"  WHERE ("id" = 123) ORDER BY "a"."id" ASC LIMIT 1
```

Yep. The where clause is lost. **Silently**.
Btw, this by itself is a bug and probably should be fixed.

But the reason it was lost is because it doesn't match any value from that code (by the link above).
Built in SQL drivers already have this figured out. There's a `sql/driver.Valuer` interface, which allows to change the value, that database will have to interact with.

To me, it seems logical that if I implement `sql/driver.Valuer` for my `ID` type, it should be checked for and applied before all other matching happends in that function. However, currently it's not the case.

There definetly has to be some way to provide values for where and other clauses from custom types. Maybe I'm not right with pososing `sql/driver.Valuer` for this (tell me what you think about it), but we need something there.

**Comment by jinzhu** [comment]
`db.First(&a, id)` this only support number types, you need to write like this `db.First(&a, "id = ?", id)`

**Comment by jinzhu** [comment]
and Valuer should been supported

**Comment by jinzhu** [comment]
Btw, GORM will return an error if passing a query type doesn't support like this one

```go
err := db.First(&a, id).Error
err != nil
```

**Comment by MOZGIII** [comment]
Really? I must've been using an old version that doesn't return an error then. If there's an indication that something's wrong - I'm good with it. It's just in my exprience it was silently omitting the where clause, and it didn't make me pleased.
