### ISSUE TITLE
 feature/support json_text,xml_text of field tags

### ISSUE THREAD

**Issue by imiskolee** [jinzhu/gorm#1601]
sometimes,we need to store a struct to a text.
now,we can implement Scan/Value method of that struct.

but, we need to implement Scan/Value of every struct.

so,i want to add a new feature to support `json_text,xml_text`,it like

```go
type OwnOrmModel struct {
   JsonObject *struct {
       Field string `json:"field"
   } `json:"object",gorm:"type:text", serialization:json"
}
```

do u want it ?

**Comment by imiskolee** [comment]
type:feature

**Comment by glb** [comment]
That would be great, would it also work for:
```go
type Sample struct {
    Strings []string `gorm:"type:text", serialization:"json"`
}
```
? I am looking for a way to serialize slices like this into DBs to simplify my data model.

**Comment by glb** [comment]
I've been able to accomplish something similar using plugins; this would be a very helpful feature to have in the base package, though!

**Comment by jinzhu** [comment]
use scanner, valuer?
