### ISSUE TITLE
Any way to support int slice storage?

### ISSUE THREAD

**Issue by seaguest** [jinzhu/gorm#1602]
Before posting a bug report about a problem, please try to verify that it is a bug and that it has not been reported already, please apply corresponding GitHub labels to the issue, for feature requests, please apply `type:feature`.

DON'T post usage related questions, ask in https://gitter.im/jinzhu/gorm or http://stackoverflow.com/questions/tagged/go-gorm,

Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go 1.8

### Which database and its version are you using?
mysql 5.7

### What did you do?
I want to store int slice in table, it could be a string in table with "," separator, is there any serilizer, deserializer in gorm?

As following, I have that model, the table may have id int, page_ids (string type here, ex: "1,2,3")

Please provide a complete runnable program to reproduce your issue.

```go
type Module struct {
	Id      	uint32 	`gorm:"primary_key"`
	PageIds   	[]uint32  
}
```

**Comment by jinzhu** [comment]
use scanner/valuer
