### ISSUE TITLE
Marshal NullInt64 to `null` in json response?

### ISSUE THREAD

**Issue by aghasoroush** [jinzhu/gorm#1603]
### What version of Go are you using (`go version`)?
1.8

### Which database and its version are you using?
MySQL 5.7

### What did you do?

Please provide a complete runnable program to reproduce your issue.
Here it is my implementation for Marshalling NullInt64 to `null` string.
Is there any way to add it to `GORM` ?
Or we even can add `null` package.

```go
package models

import (
	"database/sql"
	"encoding/json"
)

type JsonNullInt64 struct {
	sql.NullInt64
}

func (v JsonNullInt64) MarshalJSON() ([]byte, error) {
	if v.Valid {
		return json.Marshal(v.Int64)
	} else {
		return json.Marshal(nil)
	}
}

func (v *JsonNullInt64) UnmarshalJSON(data []byte) error {
	// Unmarshalling into a pointer will let us detect null
	var x *int64
	if err := json.Unmarshal(data, &x); err != nil {
		return err
	}
	if x != nil {
		v.Valid = true
		v.Int64 = *x
	} else {
		v.Valid = false
	}
	return nil
}

```
#

**Comment by jinzhu** [comment]
If it is a scanner, valuer, it should work by default?
