### ISSUE TITLE
Assign() ignores zero values in map if default annotation is set for column

### ISSUE THREAD

**Issue by bogatuadrian** [jinzhu/gorm#1607]
### Description

When annotating a struct field with a default value, the `Assign` method ignores map fields that map to a go zero value, i.e. `.Assign(map[string]bool{"column": false})` will not work if `default:true` is set for the "column" field of the model.

### Explanation

Even though the [Default Value documentation](http://jinzhu.me/gorm/crud.html#default-values) states that 

> the inserting SQL will ignore these fields that has default value and its value is blank

in the case of `Assign` as suggested by @jinzhu in https://github.com/jinzhu/gorm/pull/1365#issuecomment-282176146 one would expect that when using a map, `Assign` would treat every map entry as a valid `INSERT`/`UPDATE` clause.

This is not the case when a field is annotated with default value like `` `gorm:"default:true"` ``.

Code example:

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

func init() {
	var err error
	db, err = gorm.Open("postgres", "postgres://postgres:test@localhost:5432/gorm_test?sslmode=disable")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

type Model struct {
	Name string `gorm:"column:name"`
	Bool bool   `gorm:"column:bool;default:true"`
}

func main() {
	db.AutoMigrate(&Model{})

	var model Model
	db.
		Where(&Model{Name: "test"}).
		Assign(map[string]interface{}{
			"bool": false,
		}).
		FirstOrCreate(&model)

	db.DropTableIfExists(&Model{})
}
```

The generated query output:
```
SELECT * FROM "models"  WHERE ("models"."name" = 'test') LIMIT 1
INSERT INTO "models" ("name") VALUES ('test') RETURNING "models".*
```

As you can see the `INSERT INTO "models" ("name","bool") VALUES ('test','false') RETURNING "models".*` is missing in this case, but works if I remove `default:true` directive.

#### To be mentioned

  1. changing the `map[string]interface{}` to `map[string]bool` does not change anything
  2. changing `default:true` with `default:false` does not change anything (the problem is with existence of default)

### What version of Go are you using (`go version`)?

go1.8.3

### Which database and its version are you using?

postgres 9.6.3

**Comment by jinzhu** [comment]
Updated the document. http://gorm.io/crud.html#default-values

**Comment by sahil-dotnet** [comment]
how one can write this mysql query in gorm:
"update table_name SET field_name1 = IF (field_name2 = 2, 1 , 0) where field_name3 = 6;"

is it possible like to convert into gorm.
