### ISSUE TITLE
我想自定义模型json输出时间格式

### ISSUE THREAD

**Issue by shiguanghuxian** [jinzhu/gorm#1611]
![image](https://user-images.githubusercontent.com/13268627/30409774-c1b18220-98cc-11e7-88a2-41342bc77b1b.png)
我这样自定义了时间类型，但是添加进数据库时，时间字段会为空

**Comment by hellojukay** [comment]
@shiguanghuxian 
`// Value insert timestamp into mysql need this function.
func (ts TimeStamp) Value() (driver.Value, error) {
	var zeroTime time.Time
	var ti = time.Time(ts)
	if ti.UnixNano() == zeroTime.UnixNano() {
		return nil, nil
	}
	return ti, nil
}

// Scan valueof time.Time
func (ts *TimeStamp) Scan(v interface{}) error {
	value, ok := v.(time.Time)
	if ok {
		*ts = TimeStamp(value)
		return nil
	}
	return fmt.Errorf("can not convert %v to timestamp", v)
}`

**Comment by shiguanghuxian** [comment]
Thank you. The problem has been settled
@hellojukay
