### ISSUE TITLE
Assign with first and create doesnt update the field and results duplicate key alert

### ISSUE THREAD

**Issue by NikosEfthias** [jinzhu/gorm#1613]
![](https://i.imgur.com/pHQhoTH.png)
Since o.Oddid is the primary key I'm using it in the where clause and then I am using assign to update but it always try to insert instead

**Comment by jinzhu** [comment]
Don't o.Id exists?

**Comment by NikosEfthias** [comment]
yes it does

**Comment by jinzhu** [comment]
Could you create another issue and provide a **runnable** code that could reproduce this issue?
