### ISSUE TITLE
Unclosed TCP connection

### ISSUE THREAD

**Issue by ramvasanth** [jinzhu/gorm#1615]
We have a golang worker that fetches SQS message and process it using MySQL database , the worker uses GORM to connect to database. the worker always stopped working after a week , we found that there is many TCP connections left unclosed. initially we report the bug  GO AWS SDK team , they ask me to run without DB connections , then we did not have the problem. after that we put the DB connection coding back. we have the problem again.  

i attached the screenshot lsof of command for our worker.
Please help us

### What version of Go are you using (`go version`)?
1.8

### Which database and its version are you using?
MySQL 5.7
![image](https://user-images.githubusercontent.com/350578/30508160-cec59aa8-9ac2-11e7-9ce1-b50bc8d5bab7.png)

**Comment by jinzhu** [comment]
Please use shared DB for all requests.
