### ISSUE TITLE
Rollback panic

### ISSUE THREAD

**Issue by catinred2** [jinzhu/gorm#1620]
### What version of Go are you using (`go version`)?
go version go1.9 darwin/amd64

### Which database and its version are you using?
mysql 5.6

### Affected Ver
v1.0

### What did you do?

I have a function like this.

```go
func (dataServer *DataServer) FinishNotifyOrder(k NotifyStruct) error {
	tx := dataServer.db.Begin()
	log := NotifyStruct{
		Id:                  k.Id,
		AddTime:             k.AddTime,
		UpdateTime:          k.UpdateTime,
	}

	err := tx.Create(&log).Error
	if err != nil {
                tx.Rollback()
		return err
	}

	err = tx.Delete(&k).Error
	if err != nil {
		tx.Rollback()
		return err
	}
	tx.Commit()
	return nil
}
```

At some point, tx.Create fails due to Primary Key conflict, program will panic and crash on tx.Rollback.  The error ouput:

>panic: runtime error: invalid memory address or nil pointer dereference
>[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x58d21d]
>goroutine 63 [running]:
>database/sql.(*Tx).rollback(0x0, 0x7e2c00, 0xc42173e801, 0x7f49e6da0658)
>        /usr/local/go/src/database/sql/sql.go:1794 +0x2d
>database/sql.(*Tx).Rollback(0x0, 0x7f49e6da04b0, 0x0)
>        /usr/local/go/src/database/sql/sql.go:1813 +0x30
>callback/vendor/github.com/jinzhu/gorm.(*DB).Rollback(0xc422859360, 0x78c2c0)
 >       /Users/ming/Documents/go/src/ordercallback/vendor/github.com/jinzhu/gorm/main.go:445 +0x65

**Comment by catinred2** [comment]
PS. It does not happen always.

**Comment by jinzhu** [comment]
I guess `dataServer.db` is already in a transaction, so failed to begin a new one.

If you could reproduce this issue, please upload a full code case, thank you.
