### ISSUE TITLE
Incredibly slow when using lots of ? in the query

### ISSUE THREAD

**Issue by nsf** [jinzhu/gorm#1625]
Hi, just want to let you know that gorm has a path where it behaves incredibly slow. Imagine a raw query for inserting thousands of rows into the table of this form: `INSERT INTO table (a, b, c) VALUES (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), ...` and so on, let's say 10000 rows. Right now it seems like a very valid thing to do, especially since mysql driver gives you a flag to perform client-side argument "interpolation". Anyways, even if you use gorm.Exec(), it goes through scope.buildWhereCondition: https://github.com/jinzhu/gorm/blob/c3bb6aaa828867eec72dd8571d111e442688f85f/main.go#L431-L433

And in buildWhereCondition, strings.Replace is used for substituting ? symbols with DB specific ones. Sadly you substitute them 1 by 1: https://github.com/jinzhu/gorm/blob/c3bb6aaa828867eec72dd8571d111e442688f85f/scope.go#L563-L578

Calling strings.Replace() with a limit of 1 in a loop on a string with thousands of ? symbols leads to making thousands of copies of that string. It ends up being extremely slow. Using database/sql however directly for such kind of a request works just fine. The kind of slowdown I'm talking about is like 100ms vs 16s.

**Comment by jinzhu** [comment]
This has been refactored a little bit.
