### ISSUE TITLE
Support for recursive relations

### ISSUE THREAD

**Issue by sredXNY** [jinzhu/gorm#1630]
Hi, currently I have a database model that includes a table that has a relation to itself, as a recursive relation. I don't see in the documentation something about it, the examples covers only relation between different tables.

What I did?
I designed the model as:

```
type Component struct {
	gorm.Model
	Name                        string `
	Active                        bool   `gorm:"column:Active"`
	Parent                      *Component
}
```

But this is not creating the column related with it in the database. I had to put the * to the Parent due that Go detects it as a invalid recursion.
If this hadn't been approached, what options do I have to deal with it? Thank you

**Comment by f1nnix** [comment]
+1, the same issue, no columm is created.
```go
type Post struct {
  ID        uint      `gorm:"primary_key" json:"id"`
  Post      *Post     `json:"post" xml:"post" sql:"default:null"`
}
```
What is the correct apporoch to handle such cases? Thank you.

**Comment by jinzhu** [comment]
Should support this already, you just need to configure its ForeignKey
