### ISSUE TITLE
how to update null string value?

### ISSUE THREAD

**Issue by rfyiamcool** [jinzhu/gorm#1642]
see title ?

I found use gorm udpate 0 and ""  value , then don't update success.

**Comment by Golgothan3** [comment]
I had the same issue at first, but the answer is actually [in the gorm documentation for the **Update** section](http://jinzhu.me/gorm/crud.html#update):
```
// WARNING when update with struct, GORM will only update those fields that with non blank value
// For below Update, nothing will be updated as "", 0, false are blank values of their types
db.Model(&user).Updates(User{Name: "", Age: 0, Actived: false})
```

**Comment by jinzhu** [comment]
refer documents gorm.io/crud.html

**Comment by Tom29** [comment]
@tds123 so it means with nullable field, should i use `*string`, then with other, i should use `string`?
