### ISSUE TITLE
Bug: MySQL Column: float, Raw() Function get wrong precision float

### ISSUE THREAD

**Issue by hongxdong** [jinzhu/gorm#1644]
DB:MySQL
Charset: utf8
Table:
CREATE TABLE `AdjustingFactor` (
  `AdjustingFactor` float DEFAULT NULL COMMENT '因子',
) ENGINE=InnoDB DEFAULT CHARSET=gbk;

Go code:
type AdjustingFactor struct {
  AdjustingFactor      float64   `gorm:"column:AdjustingFactor"`
}

Data Source：
row1   AdjustingFactor = 112.573

When using below function:
sql := "SELECT AdjustingFactor FROM table WHERE id>? ORDER BY id DESC;"
db.Raw(sql, 0).Find(&result)
Get result.AdjustingFactor = 112.57315

But:
sql := "SELECT AdjustingFactor FROM table ORDER BY id DESC;"
db.Raw(sql).Find(&result)
Get result.AdjustingFactor = 112.573

112.57315 != 112.573

It is weird, Raw with values query, causes the result to be a strange value.

**Comment by emirb** [comment]
This is not an issue in Gorm but rather in how you've set up your `float` column in your MYSQL table.

From the manual of [FLOAT](https://dev.mysql.com/doc/refman/5.7/en/floating-point-types.html):

`The FLOAT and DOUBLE types represent approximate numeric data values. MySQL uses four bytes for single-precision values and eight bytes for double-precision values.
`.

To keep precision of up to N decimal places, you can use the `FLOAT(7,4)` syntax:
`MySQL permits a nonstandard syntax: FLOAT(M,D) or REAL(M,D) or DOUBLE PRECISION(M,D). Here, (M,D) means than values can be stored with up to M digits in total, of which D digits may be after the decimal point. For example, a column defined as FLOAT(7,4) will look like -999.9999 when displayed.`

I've added a test that covers this to prove that it's functioning correctly: https://github.com/jinzhu/gorm/pull/2442
