### ISSUE TITLE
Idle Connections Issue

### ISSUE THREAD

**Issue by rambhavaraju** [jinzhu/gorm#1648]
Before posting a bug report about a problem, please try to verify that it is a bug and that it has not been reported already, please apply corresponding GitHub labels to the issue, for feature requests, please apply `type:feature`.

DON'T post usage related questions, ask in https://gitter.im/jinzhu/gorm or http://stackoverflow.com/questions/tagged/go-gorm,

Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
Go 1.8.1

### Which database and its version are you using?
PostgreSQL v9.5.4 x86_64

### What did you do?

Below is the init of the connection. Also an example of how is it being used. What is happening is that even though I exclusively close all the connections, i see a pile of connections sitting idle on the Postgres SQL DB it is reaching to state of max connections allowed for this account and after that i'm unable to connect further. I tried all the suggestions mentioned in the issues posts but nothing seems to work to reduce the idle connections. What would be a better way to handle this? Your help would be really appreciated.
Please provide a complete runnable program to reproduce your issue.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

//Variable which holds the DB connection parameter
var objDB *gorm.DB
func init() {
	log.Println("Opening connection to postgre")
	var err error
	var conn = Utils.GetKey("PostgresqlConnection")
	log.Println("DBConnection", conn)
	objDB, err = gorm.Open("postgres", conn)
	objDB.LogMode(false)
	objDB.DB().SetMaxIdleConns(0)
	objDB.DB().SetConnMaxLifetime(5 * time.Second)
	objDB.DB().SetMaxOpenConns(0)
	//Check if we have encountered any errors
	if err != nil {
		log.Panic("Error while opening postgredb:", err)
	}

	//On DB error
	if err = objDB.Error; err != nil {
		log.Panic(err)
	}
}
func GetData(orderId uint64) []BusinessObjects.Item{
	//Check if the db connection object is available
	//if objDB == nil {
	Init()
	//}
	var Pos []BusinessObjects.Item

	objDB.Joins("Join orders on orders.x=payment_items.x").Where("payment_items.y like 'm%' AND orders.z=?", orderId).Find(&Pos)
	//close the connection
	objDB.Close()
	return Pos
}

```

**Comment by totoleo** [comment]
maybe you will find your answer [here](http://go-database-sql.org/surprises.html)

**Comment by rambhavaraju** [comment]
Thanks totoleo will check on it.

**Comment by rambhavaraju** [comment]
@totoleo the article you've mentioned din't help. Connections are idling out for a long time.
@jinzhu Could you please help in solving this issue.

**Comment by jinzhu** [comment]
http://go-database-sql.org/accessing.html
