### ISSUE TITLE
Bug when using a *sql.Tx

### ISSUE THREAD

**Issue by pjebs** [jinzhu/gorm#1653]
I am getting this panic when I pass a *sql.Tx into the Open function:

`interface conversion: gorm.sqlCommon is *sql.Tx, not *sql.DB`

The relevant part of stack trace:

`
github.com/jinzhu/gorm.Open(0xa57fdc, 0x5, 0xc420011da0, 0x1, 0x1, 0xc4202460a0, 0x0, 0x0)
    go/src/github.com/jinzhu/gorm/main.go:67
`

*sql.Tx satisfies the SQLCommon so why is this error occurring?

Is (lower-case) sqlCommon different to SQLCommon?

**Comment by pjebs** [comment]
My glide package manager file looks like this:
```
- package: github.com/jinzhu/gorm
  version: ^1.0.0
```

I think this causes an older version of gorm to be used because `sqlCommon` was changed to `SQLCommon` on March 15th

**Comment by lunemec** [comment]
I ran into this issue also, it is related to #960.
My issue was different:
```go
func getDB(t *testing.T) *gorm.DB {
	db, err := app.DB()
	if err != nil {
		t.Error(err)
	}

	tx := db.Begin()
	defer tx.Rollback()
	return tx
}
```

Now when I want to call:
```go
db := getDB(t)
db.DB().Exec("...sql...")
```

It results in a error:
```
interface conversion: gorm.sqlCommon is *sql.Tx, not *sql.DB [recovered]
vendor/github.com/jinzhu/gorm.(*DB).DB(...)
        vendor/github.com/jinzhu/gorm/main.go:91
```

Which is this function inside gorm:
```go
// DB get `*sql.DB` from current connection
func (s *DB) DB() *sql.DB {
	return s.db.(*sql.DB)
}
```

Where type cast is being done without first checking the type of `s.db`.

**Comment by pjebs** [comment]
Just make sure glide and go dep use the master branch instead of a particular version.

**Comment by lunemec** [comment]
@pjebs you are right, I tried with master, but now it fails on:
```
runtime error: invalid memory address or nil pointer dereference [recovered]
```
Not sure if bug in my code or in gorm yet.

**Comment by lunemec** [comment]
Ok, not a bug in my code. When calling any method on `gorm.DB.DB()` within transaction, I get invalid memory address or nil pointer dereference.

Code:
```go
	db, err := app.DB()
	if err != nil {
		t.Error(err)
	}
	db.Begin().DB().Ping()
```

**Comment by jinzhu** [comment]
use `db.Exec` , `db.Ping()`
