### ISSUE TITLE
关于为什么软删除中的 DeletedAt默认为null的疑惑

### ISSUE THREAD

**Issue by liu-xuewen** [jinzhu/gorm#1654]
SELECT * FROM users WHERE age = 20 AND deleted_at IS NULL;
这样deleted_at列默认为null. 以上查询就不能建立age与deleted_at的联合索引.
那为什么要建一个这样不友好的 软删除功能? 还不如置为0与1,或者给一个默认时间,可以建索引.

因为看到作者是华人(看过作者的Facebook),所以直接用中文了.
以上问题很重要,当数据量大的时候,不能加索引,就会严重影响新性能.求教!

**Comment by newflydd** [comment]
差点被你忽悠了。
普通联合索引完全可以加入nullable的字段。
标记为unique联合索引，需要本身的联合字段就具备唯一性，题主的age + deleated_at能作为唯一索引？
亲测，age（或者类似字段）+ deleted_at可以创建联合索引，mysql5.7

**Comment by godcong** [comment]
大部分orm的软删除都是这么设计的.是基于时间戳的. 0也是时间戳,所以用null...难道你以前没用过orm
