### ISSUE TITLE
CreatedAt field is set to 0 for new records

### ISSUE THREAD

**Issue by rusenask** [jinzhu/gorm#1660]
### What version of Go are you using (`go version`)?

1.8.3

### Which database and its version are you using?

Postgres:latest (10)

### What did you do?

Updated gorm to the newest  from `9acaa33324bbcc78239a1c913d4f1292c12177b9` commit. All new object CreatedAt fields started getting 0 for their value. Reverting back version fixed the issue.

**Comment by jinzhu** [comment]
seems works in CI.
