### ISSUE TITLE
How many gorm tags in gorm?????

### ISSUE THREAD

**Issue by dncmn** [jinzhu/gorm#1663]
When I look through the document of gorm,I come across some kinds of gorm tags,such as gorm:type varchar(20) and so on .But I don't know the whole gorm  tags existed in gorm .Also in main.go      "gorm:update_interface"  ,I can't fingure it out....

**Comment by newflydd** [comment]
https://github.com/jinzhu/gorm/blob/master/model_struct.go

line173 to 546 is the tags description

**Comment by jinzhu** [comment]
Most tags should be documented in GORM's document, refer http://gorm.io/

Will consider updating the document to have a single page to list all of them in next version.

**Comment by sunanxiang** [comment]
http://gorm.io/docs/models.html
