### ISSUE TITLE
DefaultTableNameHandler override

### ISSUE THREAD

**Issue by AlexDias79** [jinzhu/gorm#1667]
Just started using DefaultTableNameHandler override and noticed a problem, when using structs, the correspondent relational table (many2many) won't trigger the DefaultTableNameHandler.

Example:
[code]
type Company struct {
	gorm.Model
	Code       string       `gorm:"column:code;" sql:"index;"`
	Name         string       `gorm:"column:name;"`
	Users []User `gorm:"many2many:company_users;" sql:"index;"`
}
type User struct {
	gorm.Model
	InternalCode       string       `gorm:"column:internalCode;" sql:"index;"`
	Name         string       `gorm:"column:name;"`
}

...
//so when using
        db, err = gorm.Open(dbType, ConnectionString)
	gorm.DefaultTableNameHandler = func(db *gorm.DB, defaultTableName string) string {
		return "some_prefix_" + defaultTableName
	}
        db.CreateTable(&User{})
        db.CreateTable(&Company{})
[/code]

Will result in 3 tables:
1. some_prefix_user
2. some_prefix_company
3. **company_users** <-- missing prefix

Cheers

**Comment by jinzhu** [comment]
should been fixed.
