### ISSUE TITLE
MySql uuid.UUID primary key not working

### ISSUE THREAD

**Issue by ss-limafriyadi** [jinzhu/gorm#1668]
I use [github.com/satori/go.uuid](github.com/satori/go.uuid) library.

### What version of Go are you using (`go version`)?
golang/1.9

### Which database and its version are you using?
10.1.8-MariaDB Homebrew (supported as mysql?)

### What did you do?

```go
package main

import (
	"github.com/jinzhu/gorm"
        "github.com/satori/go.uuid"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

type Example struct {
       ID uuid.UUID `gorm:"primarykey;type:char(36);column:id"`
       AnotherID uuid.UUID `gorm:"type:char(36);column:another_id"`
}

func init() {
	var err error
	db, err = gorm.Open("mysql", "gorm:gorm@/dbname?charset=utf8&parseTime=True")
        example := Example{uuid.NewV4(), uuid.NewV4()}
        err = db.Create(&example).Error
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

func main() {
	// your code here

	if /* failure condition */ {
		fmt.Println("failed")
	} else {
		fmt.Println("success")
	}
}
```

The example code above produce `uuid: cannot convert int64 to UUID` error.

After digging around I find https://github.com/jinzhu/gorm/blob/6f64b8610da6d5214e9197ed3c1bf8ecf8983c89/callback_create.go#L130 

Then, when i try to change the primary key to ` ID *uuid.UUID`, it worked. Can you check why we cannot have just `uuid.UUID` type as primary key in mysql?

Cheers,

**Comment by varunrau** [comment]
I think you have a typo in your tag. gorm:primarykey should be gorm:primary_key.

You should be able to use `uuid.UUID` as a primary key in mysql.

**Comment by haydenzhourepo** [comment]
refer to this articel may help you 
https://medium.com/@mfkhao2009/use-uuid-within-gorm-and-mysql-8021459a10ba
