### ISSUE TITLE
How to know Find is success?

### ISSUE THREAD

**Issue by iinux** [jinzhu/gorm#1671]
```go
var user User
db.Where("name = ?", "job").Find(&user)
```

How to know it is found or not found?

now I use
```go
var count int
db.Where("name = ?", "job").Find(&user).Count(&count)
if count > 0 {
//found
} else {
// not found
}
```

Is there a better way?

**Comment by Lopastvertoleta** [comment]
I believe you can do something like this 
`
if err := db.Where("name = ?", "job").Find(&user).Error; err != nil { 
    // User not found
}
`

**Comment by iinux** [comment]
@Lopastvertoleta  it works, thanks
