### ISSUE TITLE
Why is bool type resulting in tinyint field?

### ISSUE THREAD

**Issue by lalarsson** [jinzhu/gorm#1674]
As the title says, I'm a bit curious to why a bool field is translated to a tinyint field?

I've only seen this for MySQL/MariaDB so I don't know if this is present in Postgres for example.

The bool type in most databases is an alias for tinyint (which makes sense) but it can be semantically confusing to use tinyint instead of bool when creating the column.

**Comment by martinlindhe** [comment]
Where exactly is this "resulting tinyint field"?

Are you referring to the created table in the database?
Then as you noted, bool is just an alias in mysql for tinyint (there is no such thing as a bool in a mysql database).

**Comment by newflydd** [comment]
give you a smile.
no filed named bool. tinyint is the best filed for bool.

**Comment by pedromorgan** [comment]
its the smallest int that can be 0 or greater.. all db's do it in different flavours efficiently, dont painic 
it could be a null .. krash

https://stackoverflow.com/questions/18872023/what-is-the-best-data-type-to-store-boolean-values-in-a-database
