### ISSUE TITLE
我已经写了`gorm:"-"`了，但是还是抛错给我

### ISSUE THREAD

**Issue by bullub** [jinzhu/gorm#1689]
![image](https://user-images.githubusercontent.com/5164246/33156846-93ce25f4-d038-11e7-8280-a96372829314.png)
![image](https://user-images.githubusercontent.com/5164246/33156860-a8cda77c-d038-11e7-8e8b-2d93916c0583.png)

**Comment by alphayan** [comment]
升级一下gorm版本，有个gorm版本`gorm:"-"`无效

**Comment by pedromorgan** [comment]
Sorry am welsh, so closing and repoen with some explain more.. TIA ;-)
