### ISSUE TITLE
多个方法使用事务？

### ISSUE THREAD

**Issue by lz1988** [jinzhu/gorm#1690]
func dosome() {
	tx := db.Begin()
	tx.Create()
	aa()//调用aa方法
	bb()//调用bb方法
	tx.Commit()
}

func aa(){
	//db新增操作
}

func bb(){
	//db修改操作
}

文档有提到，操作db需要传递句柄
// 注意，一旦你在一个事务中，使用tx作为数据库句柄

那么aa bb方法可以使用到事务，都需要传递tx参数，有没更好的办法，无须在aa，bb方法体传递参数？

**Comment by Tang-RoseChild** [comment]
tx作为参数传进去

**Comment by lz1988** [comment]
这个是唯一解决的办法？这么做，其它方法，必须在函数入口预留txt参数。

**Comment by newflydd** [comment]
你可以用动态可变数量的参数传进去嘛，参数len为0就不用事务，参数为1就取tx。
我建议你问问题就好好问，问题前加个“坑？”是几个意思。

**Comment by lz1988** [comment]
每个方法都要预留一个tx参数？这样不是所有都要加？

**Comment by Tang-RoseChild** [comment]
事务是怎么用的？你难道想开一个事务，然后所有的并发sql请求就自动进入到这个事务中？
这种提问最好先去社区问问，别直接就开个偏见很大的issue

**Comment by JonSnow47** [comment]
可以这样写
``` go
func SetUser(id int, f func(u *User)) (err error) {
  u := &User{Id:id}
  tx := db.Begin()
  err = db.FirstOrCreate(u).Error
  if err != nil {
    tx.Rollback()
    tx.Commit()
    return
  }

  f(u)

  err = tx.Save(u).Error
  if err != nil {
    tx.Rollback()
    tx.Commit()
    return
  }
  err = tx.Commit().Error
  return
}
```
