### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by BorisBorshevsky** [jinzhu/gorm#1694]
Hi,
using go dep, by default gorm will download the version tagged 1.0 from April 2016.
Any chance to create a new tag?

**Comment by s-takehana** [comment]
Relate to #1543.

**Comment by pedromorgan** [comment]
https://github.com/jinzhu/gorm/issues/1702

**Comment by avinassh** [comment]
Is this project no longer maintained? So many unresponded open PRs!

**Comment by Depado** [comment]
This project is still maintained. I just think the maintainer doesn't have much time right now.

**Comment by jinzhu** [comment]
Will start this after v2 release.

Thank you for your report.
