### ISSUE TITLE
passing empty struct to `.Updates` updates ALL rows data (which is bad)

### ISSUE THREAD

**Issue by jeberly** [jinzhu/gorm#1696]
eg. from your docs `db.Model(&user).Updates(User{Name: "hello", Age: 18})`

If you pass in a `nil` `&user`, gorm updates **all** rows in DB, instead of producing an error.  Is that the desired behavior?  To me I would rather it throw an error, as it has burned me a few times.  Or a flag to enable such more strict behavior.

Thanks!

**Comment by titouanfreville** [comment]
I'll had that while trying to test error on Update, I can't generate error if
- The object I want to update does not exist (but that's not an issue as I think it create it instead)
- Old AND/OR new object DOES NOT MEET Database definition.

The second case is quite an issue. I have an error if I try to create data that does not fit the database model declaration but not on the update ?

**Comment by jeberly** [comment]
I had some more thoughts on this too, how a solution might look in gorm to prevent this.  I am not sure if it is idiomatic gorm/golang but I will put it out here.  Add something like `ErrorOnNilObject` to the gorm api.  Eg. 

```
db.Model(&a).ErrorOnNilObject().Updates(User{SetupCompletedAt: now})
```

Similar to how `.Debug()` works, there could also be an option to enable it globally.  If enabled, it would throw a nil object error if any value passed in to the query builder is nil.  Thoughts?

**Comment by pedromorgan** [comment]
Ben stung by this also, if nil object then tantrum maybe

**Comment by jinzhu** [comment]
`db.BlockGlobalUpdate(true)`
