### ISSUE TITLE
请问GORM能否在多对多的关系上进行条件限制？

### ISSUE THREAD

**Issue by newflydd** [jinzhu/gorm#1697]
请问GORM在处理多对多映射时，能否在查询关系中间表时，做一些条件限制。
现在的关系表都是GORM自动生成的，只有两个字段，但是有些关系是需要带标记的，删除关系时有可能还需要软删除，增加delete_at字段，请问GORM设计时考虑这个问题吗？
如果没办法解决，只能手工join吗，或者将model中的多对多字段拆分成两层一对多。

Thanks to the GORM project.

I must add some import fileds into the many-to-many relatisonship table.

just like weight、distance、relationship(mate, child, parent...) or deleted_at

these fileds belong to the relationship。

when I use GORM‘s many-to-many tag，those fileds is difficulty to maintan, and when I use Find() or First() funtions, those fileds can't add query criterias.

How can I do?

Thanks.

**Comment by jinzhu** [comment]
https://github.com/jinzhu/gorm/issues/1701
