### ISSUE TITLE
UpdateColumns(map[string]interface{}) generated Update sql columns should be sorted.

### ISSUE THREAD

**Issue by sunfmin** [jinzhu/gorm#1700]
```
UPDATE "orders" SET "shipping_address_country" = $1, "shipping_address_given_name" = $2, "shipping_address_zipcode" = $3, "shipping_address_family_name" = $4, "shipping_address_katakana_given_name" = $5, "shipping_address_city" = $6, "shipping_address_phone" = $7, "shipping_address_address2" = $8, "shipping_address_prefecture" = $9, "shipping_address_address1" = $10, "shipping_address_phone2" = $11, "shipping_address_name" = $12, "shipping_address_katakana_family_name" = $13  WHERE (order_code = $14 AND state = $15)
```

Right now it generate different sql each time.

**Comment by pedromorgan** [comment]
a map is intentionally unsorted, 
- https://nathanleclaire.com/blog/2014/04/27/a-surprising-feature-of-golang-that-colored-me-impressed/
- https://stackoverflow.com/questions/12108215/golang-map-prints-out-of-order

what is our case example ?  like mine probably of having same query...for debug eyes

**Comment by sunfmin** [comment]
Yes, just for sql logs to be consistent each time.

**Comment by smithjessk** [comment]
@sunfmin @pedromorgan I took a stab at this with #1734. Thoughts?

**Comment by sunfmin** [comment]
@smithjessk That looks great.
