### ISSUE TITLE
find() method generates incorrect query (bool)

### ISSUE THREAD

**Issue by objque** [jinzhu/gorm#1705]
Hi, I'm faced with strange problem: find() method generates incorrect query (tested on MySQL (mariadb))
I wanna get all records from DB that have false in a field.
I'm providing struct into Find() with a boolean field that has a false value, but the final query is simple "select * from XXXX" without where condition.
I know, I can provide map[..].. into Where method, but it's a not correct way for our project. (we provide structs everywhere and don't want to pass map[..]..)
I found similar issue here https://github.com/jinzhu/gorm/issues/1440

### What version of Go are you using (`go version`)?

1.9

### Which database and its version are you using?

mysql/mariadb

**Comment by jinzhu** [comment]
consider using `*bool` as the data type?
