### ISSUE TITLE
Count method returning wrong result

### ISSUE THREAD

**Issue by pyprism** [jinzhu/gorm#1706]
I am using Go 1.9 and Postgres 9.6 . I have a user model and currently there is only one row. I am trying to count number of rows of whole User table .

```
// models/User.go
package models

import "github.com/jinzhu/gorm"

type User struct {
	gorm.Model
	Name string
	Password string
	Admin bool
}
```
and the main.go: 

package main

```
import (
	"fmt"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	"github.com/user/proj/models"
)

func main() {
	conString := "host=localhost user=someuser dbname=xyzdev sslmode=disable password=somepass"
	db, err := gorm.Open("postgres", conString)
	if err != nil {
		panic("failed to connect database")
	}
	defer db.Close()
	db.AutoMigrate(&models.User{})
	var count int64
	db.Debug().Model(&models.User{}).Count(&count)
	fmt.Println(count)
}
```

I am expecting 1 but its printing 0 , here is the output:

```
2017-12-19 10:43:20]  [0.71ms]  SELECT count(*) FROM "users"  WHERE "users"."deleted_at" IS NULL  
[0 rows affected or returned ] 
0
```

**Comment by s-takehana** [comment]
The expect record's `deleted_at` is `NULL` ?

**Comment by pyprism** [comment]
I am not sure how did it come !  It should be just  `SELECT count(*) FROM "users"`

**Comment by s-takehana** [comment]
Please see [this GORM doc](http://jinzhu.me/gorm/models.html#model-definition) Conventions section.
You use `gorm.Model` in User struct, and so GORM uses DeletedAt.

**Comment by pillarlei** [comment]
I had the same

**Comment by jalanga** [comment]
+1, the results of the query are ok, but the Count() method is counting deleted records
