### ISSUE TITLE
how to set `auto_increment_offset` and `auto_increment_increment`

### ISSUE THREAD

**Issue by dongshimou** [jinzhu/gorm#1713]
how to set it when i create table?

**Comment by elisaado** [comment]
I think the struct tag ``gorm:"index"`` will set that. I am not sure though.

**Comment by dongshimou** [comment]
@elisaado no,it's not work.

i try this
```
db.Exec("set auto_increment_increment=1")
```

done!

**Comment by elisaado** [comment]
So it's working now?
If so, please close the issue.
