### ISSUE TITLE
MaxOpenConnections property is getting ignored while connecting to DB- Postgres

### ISSUE THREAD

**Issue by rambhavaraju** [jinzhu/gorm#1716]
What version of Go are you using (go version)?
Go 1.8.1

Which database and its version are you using?
PostgreSQL v9.6.2 x86_64

What did you do?
@jinzhu, i have tagged you in the previous issue also, where i have mentioned about idle connections. Below is the init of the connection. Also an example of how is it being used. What is happening is that even though I exclusively close all the connections, i see a pile of connections sitting idle on the Postgres SQL DB it is reaching to state of max connections allowed for this account and after that i'm unable to connect further. I tried all the suggestions mentioned in the issues posts but nothing seems to work to reduce the idle connections.  After trying to exclusively close the connection I tried to make the connection connect only once as you see below and remove the close methods but that is also in vain. None of that seems to work. Issue is happening only when **DB.Raw** method where the underlying connection is either idling out or staying in established state because of which we see a huge pile of max open connections and after a while the database is refusing any other connections. It is causing a lot of problems to us, your timely help would alleviate our issue.

Please provide a complete runnable program to reproduce your issue.

package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

//Variable which holds the DB connection parameter
var objDB *gorm.DB
func ConnectPostgreDB() *gorm.DB {
	once.Do(func() {
		log.Println("Opening connection to postgre")
		var err error
		var conn = Utils.GetKey("PostgresqlConnection")
		log.Println("DBConnection", conn)
		objDB, err = gorm.Open("postgres", conn)
		objDB.LogMode(false)
		objDB.DB().SetMaxIdleConns(0)
		objDB.DB().SetConnMaxLifetime(5 * time.Second)
		maxcon, _ := strconv.Atoi(Utils.GetKey("MaxDBConnections"))
		log.Println("Max open Connections:", maxcon)
		objDB.DB().SetMaxOpenConns(maxcon)
		//Check if we have encountered any errors
		if err != nil {
			log.Panic("Error while opening postgredb:", err)
		}

		//On DB error
		if err = objDB.Error; err != nil {
			log.Panic(err)
		}
	})
	log.Println("Max open connections at this point:", objDB.DB().Stats().OpenConnections)
	return objDB

}
func GetData(orderId uint64) []BusinessObjects.Item{
	//List of tariff records
	var objTarifList []BusinessObjects.DBList
	var objList BusinessObjects.DBList
	//Check if the db connection object is available
	conn := ConnectPostgreDB()
	//var result interface{}
	conn.LogMode(true)

	//Raw query to execute on the postgresql db
	db := conn.Raw("select v.operator as Operator,array_agg(distinct(v.circle)) as Circle from vwTariffList v group by v.operator")
	rows, err := db.Rows()
	if err != nil {
		log.Println(err.Error())
	}

	var tmpString, tmpString1 string
	for rows.Next() {
		rows.Scan(&tmpString, &tmpString1)
		log.Println(tmpString, tmpString1)
		res := pgArrayToSlice(tmpString1)
		//res1 := pgArrayToSlice(tmpString2)
		log.Println(len(res))
		objList.Operator = tmpString
		objList.Circle = res
		//Append this to the list
		objTarifList = append(objTarifList, objList)

	}
	// if rows != nil {
	// 	rows.Close()
	// 	rows = nil
	// }
	//close the pointer
	//db.Close()
	//Close the connection
	//conn.Close()
	return objTarifList

}
}

**Comment by jinzhu** [comment]
You should not connect db for each request... but have a global connection.
