### ISSUE TITLE
many2many多对多中间表名称没有调用DefaultTableNameHandler

### ISSUE THREAD

**Issue by youjianglong** [jinzhu/gorm#1717]
在tag中指定many2many多对多映射关系的中间表名称没有调用DefaultTableNameHandler处理，这样导致的情况是如果在DefaultTableNameHandler拼接了表前缀，中间表无法自动拼接该前缀，保持一致的表前缀。
```
gorm.DefaultTableNameHandler = func(db *gorm.DB, defaultTableName string) string {
	return database.Prefix + defaultTableName
}

type User struct {
    gorm.Model
    Languages         []Language `gorm:"many2many:user_languages;"`
}
```
这时的user_languages表名字无法自动拼接上database.Prefix

**Comment by electron93** [comment]
In English please. Otherwise, you negate the chance of answering your request. I can also write something, for example, in Russian. Who will feel better? No one.

**Comment by jinzhu** [comment]
@youjianglong thank you for your report, fixed that.

But just like @electron93 said, please use English to report issues, if you can't, consider DM me on gitter.

**Comment by zonzpoo** [comment]
@youjianglong how to auto create join_table 'user_languages'?
