### ISSUE TITLE
DB.FindOrCreate with preload doesn't preload for created instances

### ISSUE THREAD

**Issue by relwell** [jinzhu/gorm#1719]
### What version of Go are you using (`go version`)?
`go version go1.9.2 darwin/amd64`

### Which database and its version are you using?
`psql (9.6.1)`

### What did you do?
Attempted to preload an association with find-or-create.

```
DB.Preload('Association').findOrCreate(&myModel, &myModel{Name: "foo", AssociationID: association.ID}
```

**Comment by jinzhu** [comment]
As it requires another SQL to preload data, and in the normal case, if it is a new record, it should not has any `Associations` saved in the database, so not going to support this.

In your case, you could write it like:

`DB.FindOrCreate(&myModel, &myModel{Name: "foo", Association: associatio)nD}`

Thank you.
