### ISSUE TITLE
Mssql dialect Issue  "setIdentityInsert" function not working

### ISSUE THREAD

**Issue by mukulgoelcubastion** [jinzhu/gorm#1724]
Connection code:
```go

import (
	"github.com/jinzhu/gorm"
	"fmt"
	"log"
	_ "github.com/go-sql-driver/mysql" // MySQL driver
	_ "github.com/denisenkom/go-mssqldb"  //MsSql Driver
	_ "github.com/jinzhu/gorm/dialects/mssql"
)

func Connect(d Info) {
	var err error

	databases = d

	switch d.Type {
	case TypeMsSQL:
		// Connect to MsSQL
		SQL, err = gorm.Open("mssql", "sqlserver://root:password@localhost:1433?database=SampleApp")
		if err != nil {
			log.Println("SQL Driver Error", err)
		}else{
			fmt.Println("Connected")
		}

		if err = SQL.DB().Ping(); err != nil {
			log.Println("Database Error", err)
		}
	default:
		log.Println("No registered database in config")
	}
}


```
Table Struct:
```go

type Device struct {
	Id     uint   `gorm:"column:id" json:"id,omitempty"`
	Uuid   string `gorm:"column:uuid" json:"uuid,omitempty"`
	UserId uint   `gorm:"column:user_id" json:"user_id,omitempty"`
}

// This method will insert one Device in db
func PostDevice(data Device) Device {
        SQL.Create(&data)
	return data
}

// This method will update Device based on id
func PutDevice(newData Device) Device {
	oldData := Device{Id: newData.Id}
	SQL.Model(&oldData).Updates(newData)
	return newData
}

```
Referring to the above code snippet, whenever we are trying to insert a record with identity_column, it works fine for the first time. But whenever we try to do insertion of identity_column after that, it displays error "(mssql: Cannot update identity column 'id'.)" .

In the setIdentityInsert() , following condition is mentioned:
```go
if _, ok := field.TagSettings["AUTO_INCREMENT"]; ok && !field.IsBlank
```
field.TagSettings["AUTO_INCREMENT"] returns AUTO_INCREMENT for the first time, which in turn gives it a bool value true but executing the code after that yields an empty string for field.TagSettings["AUTO_INCREMENT"], hence a bool value false.

Kindly look into this problem.

P.S. This doesn't work for updation of identity column, neither for the first time nor after that. Please try to solve this issue as well.

**Comment by jinzhu** [comment]
MSSQL could pass all tests in our CI, maybe you are using an old version?

Could you create a new issue and post a runnable program that could reproduce this issue and works with our [docker-compose](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml)  configuration?

Thank you.
