### ISSUE TITLE
Query to Struct Slice?

### ISSUE THREAD

**Issue by akaytatsu** [jinzhu/gorm#1727]
It my query:

`qryResult []QuestionResult

qry = `
  select q.*, p.ml_title, p.ml_thumbnail, p.ml_permanent_link, b.ml_nickname, p.ml_price, p.ml_available_quantity, b.ml_permalink buy_pl
  from mdlquetions q
  join mdlproducts p on p.ml_id = q.ml_item_id
  join mdlbuyer b on b.ml_user_id = q.ml_user_id and b.ml_buy_id = q.ml_buy_id
  where %s and q.ml_user_id = %d
    and date(q.ml_date_created) >= '%v'
    and date(q.ml_date_created) <= '%v'
  order by q.ml_date_created asc
  `

qry = fmt.Sprintf(qry, status, ml_user_id, dtIni.Format("2006-01-02"), dtEnd.Format("2006-01-02"))
database.DB.Raw(qry).Limit(limit).Scan(&qryResult)`

But my result is:

https://imgur.com/p6gI5Hm

How exec complex query in GORM to Struct Slice?

**Comment by mayowa** [comment]
Try this:
database.DB.Raw(qry).Limit(limit).**Find**(&qryResult)

**Comment by jinzhu** [comment]
Hi @akaytatsu 

Could you write a runnable program that following that [guide](https://github.com/jinzhu/gorm/blob/master/.github/ISSUE_TEMPLATE.md) if there are still issue for you?
