### ISSUE TITLE
notnull no effect.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [jinzhu/gorm#1732]
### What version of Go are you using (`go version`)?
1.9.2
### Which database and its version are you using?
Sql Server 2016
### What did you do?
`gorm:"column:Id;type:uniqueidentifier;primary_key;notnull;default:newid()"`

but `notnull` not be set.

**Comment by s-takehana** [comment]
It's probably `not null;` , not `notnull;` .

**Comment by MiyamuraMiyako** [comment]
@s-takehana Thank you, sloved.
