### ISSUE TITLE
Can not insert contain uniqueidentifier column's record.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [jinzhu/gorm#1733]
### What version of Go are you using (`go version`)?
1.9.2

### Which database and its version are you using?
Sql Server 2016

### What did you do?
`Id` column have `default newid()`,but can not insert record use gorm.
I try set Id to []byte type, but still failed.
![image](https://user-images.githubusercontent.com/10345361/35192491-9bbee04a-fece-11e7-93f4-c2bd57a96127.png)

**Comment by jinzhu** [comment]
this seems like an error from mssql?
