### ISSUE TITLE
invalid sql type  (slice) for postgres

### ISSUE THREAD

**Issue by ipandtcp** [jinzhu/gorm#1741]
Before posting a bug report about a problem, please try to verify that it is a bug and that it has not been reported already, please apply corresponding GitHub labels to the issue, for feature requests, please apply `type:feature`.

DON'T post usage related questions, ask in https://gitter.im/jinzhu/gorm or http://stackoverflow.com/questions/tagged/go-gorm,

Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?

go version go1.9 linux/amd64

### Which database and its version are you using?

PostgreSQL 9.5.0 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17), 64-bit
### What did you do?
try to create table, and panic appeared, 

invalid sql type  (slice) for postgres
/root/go/src/runtime/panic.go:491 (0x42b6b2)
	gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/root/go_projects/src/github.com/jinzhu/gorm/dialect_postgres.go:79 (0x9379b5)
	(*postgres).DataTypeOf: panic(fmt.Sprintf("invalid sql type %s (%s) for postgres", dataValue.Type().Name(), dataValue.Kind().String()))
/root/go_projects/src/github.com/jinzhu/gorm/scope.go:1107 (0x953ee2)
	(*Scope).createTable: sqlTag := scope.Dialect().DataTypeOf(field)
/root/go_projects/src/github.com/jinzhu/gorm/main.go:515 (0x940cfe)
	(*DB).CreateTable: db = db.NewScope(model).createTable().db

Please provide a complete runnable program to reproduce your issue.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

type Department struct {
        ID int `json:"id" gorm:"column:id"`
        Name string `json:"name" gorm:"column:name"`
        ParentID        int `json:"parentid" gorm:"column:parent_id"`
        TestStr         []string `json:"gorm:"column:test_string"`
        TestInt         []int `json:"gorm:"column:test_int"`
        CreateDeptGroup bool `json:"createDeptGroup" gorm:"column:create_dept_group"`
        AutoAddUser     bool  `json:"autoAddUser" gorm:"column:auto_add_user"`
}

var db *gorm.DB

func init() {
	var err error
	//db, err = gorm.Open("sqlite3", "test.db")
	// Please use below username, password as your database's account for the script.
	db, err = gorm.Open("postgres", "user=gorm dbname=gorm sslmode=disable")
	// db, err = gorm.Open("mysql", "gorm:gorm@/dbname?charset=utf8&parseTime=True")
	// db, err = gorm.Open("mssql", "sqlserver://gorm:LoremIpsum86@localhost:1433?database=gorm")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

func main() {
	db.CreateTable(&Department{})

	if /* failure condition */ {
		fmt.Println("failed")
	} else {
		fmt.Println("success")
	}
}
```

**Comment by s-takehana** [comment]
#1248 may be helpful.
