### ISSUE TITLE
Using Omit() on Create with nested struct fields doesn't work

### ISSUE THREAD

**Issue by Seriallol** [jinzhu/gorm#1743]
Lets say for example that I have these structs:

```
Natural {
   ID      uint
   Person  Person
}

Person{
   ID               uint
   HealthInsurance  HealthInsurance
}

HealthInsurance{
   Name     string
}
```
Now if I do a db.Create(&natural) I want gorm to create the record on the "person" table too but I don't want it to update the record on the "health_insurance" table.
Using:

`db.Omit("person").Create(&natural)`
works fine, gorm will not try to insert the record on the "person" table, but using something like:

`db.Omit("health_insurance").Create(&natural)` 
will not work, gorm will still try to update the table "health_insurance", I've tried a lot of different combinations on Omit, like "person.health_insurance", "Person.HealthInsurance" and so on, nothing worked, is this currently possible or intended in gorm?

Note: I know that I can use save_associations:false tag to omit fields, or disable the associations entirely when using create, I'm just wondering if its possible to do it with Omit() because I don't want to insert the record manually every time that it needs to be inserted.

**Comment by jinzhu** [comment]
there are some new changes might help you. http://gorm.io/crud.html#associations

GORM allows to disable updating existing record but still allow creating for new records.
