### ISSUE TITLE
feature/support CUBRID

### ISSUE THREAD

**Issue by lexesv** [jinzhu/gorm#1746]
CUBRID is a comprehensive open source relational database management system highly optimized for Web Applications. (Initial release  November 20, 2008) http://www.cubrid.org

Links:
repo https://github.com/CUBRID/cubrid
driver for Go https://github.com/sabzil/cubrid
php PDO http://php.net/manual/en/ref.pdo-cubrid.php

**Comment by jinzhu** [comment]
Maybe start with a third party dialect first, will merge it into core when there are enough users.

Thank you.
