### ISSUE TITLE
(sql: converting argument $6 type: unsupported type []int32, a slice of int32) 

### ISSUE THREAD

**Issue by LiuzhOc** [jinzhu/gorm#1747]
i define this struct.when i run	
    face := Face{}
    face.Rect = []int32{2,32, 300, 400}
    face.Age = 20
    db.Create(&face)
i got this error "(sql: converting argument $6 type: unsupported type []int32, a slice of int32) "

type Face struct {
	gorm.Model	
	Rect        []int32   `gorm:"type:integer[]"`	
	FaceFeature []float64 `gorm:"type:float[]"`
	Age         int32
}

**Comment by s-takehana** [comment]
#1588 may be helpful.
