### ISSUE TITLE
Disable callback on preload

### ISSUE THREAD

**Issue by croatiangrn** [jinzhu/gorm#1749]
Is there a way to disable callback on preloaded structs?

For example; I have this code
`findErr := db.Debug().Where("id = ?", startListID).
				Preload("User").
				Preload("Horse").
				First(userStartListObj).GetErrors()
	if len(findErr) > 0 {
		throwErrors(findErr, c)
		return
	}`

I want to disable preload on User only

**Comment by jinzhu** [comment]
Just remove the Preload("User")?

Or overwrite GORM's defaullt callback
