### ISSUE TITLE
First() and RecordNotFound() error

### ISSUE THREAD

**Issue by georgehao** [jinzhu/gorm#1753]
if i write like this:
```
db.Where("openid = ? ", "222").First(&user).RecordNotFound() {
```
the sql is 
`
 SELECT * FROM `users`  WHERE `users`.`deleted_at` IS NULL AND `users`.`id` = '1' AND ((openid = '222')) ORDER BY `users`.`id` ASC LIMIT 1
`
it is error

when i change it like this:
```
tmp := db.Where("openid = ? ", "222").First(&user)
tmp.RecordNotFound()
```
the sql is 
```
SELECT * FROM `users`  WHERE `users`.`deleted_at` IS NULL AND `users`.`id` = '2' AND ((openid = '222')) ORDER BY `users`.`id` ASC LIMIT 1
```
it's right.

it seem this is a bug. I use the code from master

**Comment by Aetheus** [comment]
Hey there, @georgehao . Could you post some more context (e.g: a runnable demo code snippet that reproduces your issue) of the bug you're facing? What DBMS (PostgreSQL,MySQL, etc) you're running on might be useful to know, too. It would be helpful for the debugging process. 

I'm assuming the error is that the query should have search for a ```user``` with the id of 2, and not a user of the id of 1? Have you already populated the fields of the ```user``` variable, or is it just a blank struct when you're running these code snippets?

Note that the ```First``` method will consider the argument that you're passing to it (```user```, in this case) as a query condition. 

So if ```user``` had an "id" field of a value of 1, it would produce the first query that you showed us (```SELECT * FROM users WHERE users.deleted_at IS NULL AND users.id= '1' AND ((openid = '222')) ORDER BY users.id ASC LIMIT 1 ```). 

Likewise  if ```user``` had an "id" value of 2, it would produce the second query you showed us (```SELECT * FROM `users`  WHERE `users`.`deleted_at` IS NULL AND `users`.`id` = '2' AND ((openid = '222')) ORDER BY `users`.`id` ASC LIMIT 1```).

**Comment by jinzhu** [comment]
seems the `user` you passed into `First` already contains a primary key?
