### ISSUE TITLE
How to force Gorm's create, update and delete to use UTC instead of local time?

### ISSUE THREAD

**Issue by kerak19** [jinzhu/gorm#1755]
So, Gorm create, update and delete are setting local time in my database, instead of UTC.

How can i make Gorm to use UTC instead, without changing time zone to UTC in cofig? 

Do i have to use callbacks ?

**Comment by jinzhu** [comment]
I remember you could configure your database to UTC tiem?

Or you could overwrite callbacks that set time.

**Comment by psyhonut** [comment]
> I remember you could configure your database to UTC tiem?
> 
> Or you could overwrite callbacks that set time.

This solution not good for sqlite3, that your library is supporting. Redefining all callbacks it's not easy.

**Comment by nicklasfrahm** [comment]
@kerak19 @psyhonut Had the same issue. Hope this does not come to late, but you can override the `gorm.NowFunc` like this:

```go
...

// Configure timestamp.
gorm.NowFunc = func() time.Time {
  return time.Now().UTC()
}

// Connect to database. Timestamps will now always use UTC.
db, err := gorm.Open(dbDriver, dbPath)

...
```
