### ISSUE TITLE
gorm save with custom primary key field

### ISSUE THREAD

**Issue by shen-xianpeng** [jinzhu/gorm#1760]
try to save with custom primary key field,  gorm.Save(&CompanyContact{CompanyId: 10000}),
won't create new record in database,  only update exist record, is this a bug ?

```go
type CompanyContact struct {
	CompanyId     sql.NullInt64  `db:"company_id" gorm:"primary_key"`
	ContactPerson sql.NullString `db:"contact_person"`
	ContactAddr   sql.NullString `db:"contact_addr"`
	CreateTime    time.Time      `db:"create_time"`
	UpdateTime    time.Time      `db:"update_time"`
}
gorm.Save(&CompanyContact{CompanyId: 10000})

//i have to do this now

func SaveCompanyContact(companyContact *CompanyContact) error {
	companyContact.CreateTime  = time.Now()
	result := CompanyDb.Create(&companyContact)
	if result.Error != nil {
		if strings.Contains(result.Error.Error(), "Duplicate") {
			companyContact.UpdateTime  = time.Now()

			result = CompanyDb.Save(&companyContact)
		} else {
			return result.Error
		}

	}

	return nil
}

```

**Comment by Aetheus** [comment]
Hey there, @shen-xianpeng . In order to create new records, you should call the ```db.Create``` method, not the ```db.Save``` method (which is used for updating). This is probably what you wanted to do instead:

```gorm.Create(&CompanyContact{CompanyId: 10000})```

Tell me if that solves your problem! Otherwise, which database were you running this on? And were you using the master branch of Gorm?

**Comment by shen-xianpeng** [comment]
gorm.Save应该会创建新的记录对吗？如果save时primary key对应的字段没有值时？
我一直这么用的没遇到问题， 直到用了一个特殊指定的primary key而不是id时才遇到这个问题

**Comment by Garfield-yin** [comment]
@shen-xianpeng  我也是这个问题，有解决方法么？
