### ISSUE TITLE
batch delete bug

### ISSUE THREAD

**Issue by xjjrocker** [jinzhu/gorm#1761]
Before posting a bug report about a problem, please try to verify that it is a bug and that it has not been reported already, please apply corresponding GitHub labels to the issue, for feature requests, please apply `type:feature`.

DON'T post usage related questions, ask in https://gitter.im/jinzhu/gorm or http://stackoverflow.com/questions/tagged/go-gorm,

Please answer these questions before submitting your issue. Thanks!

### What did you do?

Please provide a complete runnable program to reproduce your issue.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

type Monitor struct { // 默认表名是`monitors`
	ID uint //字段`ID`为默认主键,列名为 `id`

	Code       string  `gorm:"size:6"` // string默认长度为255, 使用这种tag重设。
	Name       string  //列名为 `name`,名称
}

func main() {
db, err := gorm.Open("mysql", "root:psw@/test?charset=utf8&parseTime=True&loc=Local")
	if err != nil {
		panic("连接数据库失败")
	}
	defer db.Close()

	// 自动生成表,自动迁移模式
	db.AutoMigrate(&Monitor{})

	// 创建
	mon := new(Monitor)
	mon.Code = "600246"
	mon.Name = "记录2"
	db.Create(mon)
	db.Create(&Monitor{Code: "600346", Name: "记录"})
	db.Create(&Monitor{Code: "600446", Name: "记录1"})

//一旦用了批量删除模式，即便查询只有一条记录符合条件，但也会整个表数据删除；很不友好
//不管是查询到几条记录，都应该只删除符合条件的记录；即便是一条也是多条的一个特殊情况而已
	var mons []Monitor 
	db.Where("Code= ?", "600346").Find(&mons)
	db.Delete(&mons)
}
```

**Comment by jinzhu** [comment]
Delete only works for one record, and you could use option `BlockGlobalUpdate` to avoid delete the whole table.

**Comment by xjjrocker** [comment]
`删除所有匹配记录

db.Where("email LIKE ?", "%jinzhu%").Delete(Email{})
//// DELETE from emails where email LIKE "%jinhu%";

db.Delete(Email{}, "email LIKE ?", "%jinzhu%")
//// DELETE from emails where email LIKE "%jinhu%";`
这些是你们的说明诶，自己都说了批量删除，你这个问题不去解决，难道你的意思你gorm没有批量删除的函数？！这个最基本的功能了吧？！

**Comment by jinzhu** [comment]
不支持传 `[]Monitor` 支持传 `Monitor`

**Comment by xjjrocker** [comment]
收到，多谢解答。
