### ISSUE TITLE
why insert to `Mysql`,IsAlter  to `is_alter` ?  

### ISSUE THREAD

**Issue by wuyachao** [jinzhu/gorm#1762]
this is my struct, mysql field is `isalter`.
```
type ModuleInfo struct {
	Module  string `json:"module"`
	Email   string `json:"email"`
	Phone   string `json:"phone"`
	IsAlter int    `json:"isalter"`
}
```
but cause an error`Error 1054: Unknown column 'is_alter' in 'field list'`.
log: ` INSERT INTO `module` (`module`,`email`,`phone`,`is_alter`) VALUES ('waimai1','123@qq.com','11111111','0')`

so, I use `IsalTer` again.

```
but cause an error`Error 1054: Unknown column 'Isal_ter' in 'field list'`.
log: ` INSERT INTO `module` (`module`,`email`,`phone`,`Isal_ter`) VALUES ('waimai1','123@qq.com','11111111','0')`
```
So i don't understand.

**Comment by jinzhu** [comment]
http://gorm.io/models.html#conventions
