### ISSUE TITLE
No relations beetween tables

### ISSUE THREAD

**Issue by ibogdan94** [jinzhu/gorm#1764]
### What version of Go are you using (`go version`)?
go1.9.2 darwin/amd64

### Which database and its version are you using?
mysql  Ver 14.14 Distrib 5.7.18, for macos10.12 (x86_64) 

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
```go
package models

import "github.com/jinzhu/gorm"

type User struct {
	gorm.Model
	FirstName   string `json:"firstName" binding:"required"`
	LastName    string `json:"lastName" binding:"required"`
	Email       string `gorm:"type:varchar(100);unique_index" json:"email" binding:"required"`
	Phone       string `json:"phone"`
	GoogleUid   string
	FacebookUid string
	FeedBacks   []FeedBack
	DishLikes   []Dish `gorm:"many2many:likes_to_dishes;"`
}

type FeedBack struct {
	gorm.Model
	UserID          uint
	Title           string  `gorm:"null"`
	Text            string  `sql:"type:text"`
	Visible         bool
	Deleted         bool
	ServiceScore    float64 `sql:"DECIMAL(10,2)"`
	PriceScore      float64 `sql:"DECIMAL(10,2)"`
	FoodScore       float64 `sql:"DECIMAL(10,2)"`
	AtmosphereScore float64 `sql:"DECIMAL(10,2)"`
}
```

As a result I have tables without relations:
https://www.dropbox.com/s/xo79pgi3x5q09pw/Screenshot%202018-02-11%2014.55.47.png?dl=0

What I did wrong? 

Also, one more question, how I can get User data with related FeedBack?

```go
q := d.DB.Where("id = ?", id).First(&user) //return only user data without feedbacks
```

**Comment by jinzhu** [comment]
Use Preload

**Comment by ibogdan94** [comment]
@jinzhu I didn't received answer for main question about relations 
Could you help me to fix this issue? What I did wrong? I followed by gorm documentation and it's not working

**Comment by jinzhu** [comment]
Are you talking db level foreign key not created? there are several issues discussing this

**Comment by ibogdan94** [comment]
@jinzhu 
yes, you are right 
it's a little bit confusing, when you want to user a package, following instructions and it's not working 
Maybe you need to update docs?

**Comment by dongshimou** [comment]
i have the same problem. foreign key is not created
