### ISSUE TITLE
error in docs and a question about logging.

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [jinzhu/gorm#1767]
I believe there is an error in docs: http://gorm.io/docs/logger.html#Customize-Logger
```
db.SetLogger(gorm.Logger{revel.TRACE})
```
it's not even compiling.

and a question:
I need to disable logging for one line and enable back to default state (only errors)
how to do it?
```
    db.LogMode(false)
    // my code
    db.LogMode(true)
```
this enables logging to full mode, but I need to default mode.
i've scanned through the code and found no way to do it.

**Comment by jinzhu** [comment]
seems it compiles for me?

For the second question, you would like to disable logging for just one line?

GORM doesn't support this right now, btw, what's your use case for this?

**Comment by Vasiliy-Bondarenko** [comment]
oh, revel is an object from external package. i don't have it, so it's not compiling. worth mentioning in docs it requires extra dependency :)

I would like to disable logging for one test. i'm testing DB error - my app must behave correctly catching that error. and i don't want to see this error message to mess with tests output.
now tests output look kind of ugly:
```
=== RUN   TestCreatingTheRoom

(Error 1406: Data too long for column 'name' at row 1) 
[2018-02-16 12:07:19]
--- PASS: TestCreatingTheRoom (0.89s)
=== RUN   TestRegularUsersOrGuestsCantCreateRooms
--- PASS: TestRegularUsersOrGuestsCantCreateRooms (0.39s)
=== RUN   TestPushingRoomListAfterConnect
```

**Comment by jinzhu** [comment]
Ok, I see, I will document it.

For the disable logging thing, Will think about this, for now, maybe you could have another silence DB that doesn't print log.
