### ISSUE TITLE
table with associated primary index cannot create with db.AutoMigrate

### ISSUE THREAD

**Issue by shavac** [jinzhu/gorm#1768]
//go version=current
//gorm version=current
package main
import (
    "github.com/jinzhu/gorm"
    _ "github.com/jinzhu/gorm/dialects/mysql"

    "log"
)

type DbTbl struct {
    uid int32 `gorm:"primary_key"`
    table_id int32 `gorm:"primary_key"`
}

func main() {
    db, err := gorm.Open("mysql", "root:pass@tcp(10.37.129.6:3306)/lynx?parseTime=true")
    if err != nil {
        log.Fatalln(err)
    }
    db.AutoMigrate(&DbTbl{})
}

**Comment by jinzhu** [comment]
```go
type DbTbl struct {
	UID     int32 `gorm:"primary_key"`
	TableID int32 `gorm:"AUTO_INCREMENT:false;primary_key"`
}
```
