### ISSUE TITLE
DB connections shared per different databases?

### ISSUE THREAD

**Issue by stepasite** [jinzhu/gorm#1769]
It seems db connections are shared when connecting to different databases (with the same user) running on the same db server.

For example, when I try to drop database 'a' (after closing its connection), keeping connection to database 'b' open, then I get:

postgres_1          | ERROR:  database "a" is being accessed by other users
postgres_1          | DETAIL:  There are 2 other sessions using the database.
postgres_1          | STATEMENT:  DROP DATABASE a

Setting:

`db.DB().SetMaxIdleConns(0)`

does help, but then the program is much slower.

Any hint would be much welcome. Btw. I always close db connection manually in defer statement.

**Comment by jinzhu** [comment]
Does the `Close` works?  GORM is using database/sql as the backend, doesn't seems an GORM issue.

**Comment by stepasite** [comment]
Yes, you are right. The issue seems to be out of the scope of GORM. The database keeps the connection open even after the Close() on db connection was called. Sorry for the noise.
