### ISSUE TITLE
Purpose of ignoreProtectedAttrs

### ISSUE THREAD

**Issue by malyusha** [jinzhu/gorm#1773]
Hi! 

When using DB method `Updates`, we can see `ignoreProtectedAttrs ...bool` parameter. It sets setting `gorm:ignore_protected_attrs` to bool, but I didn't see the usage of `Get("gorm:ignore_protected_attrs")` later in code. The question is - is this a feature, that haven't been implemented yet or it's just a legacy from previous versions? 

Thank you!

**Comment by jinzhu** [comment]
hi @malyusha, it is a feature, but not implemented yet.

**Comment by malyusha** [comment]
@jinzhu ok, thank you for response
