### ISSUE TITLE
Can't use Create to insert record into table if field is composite primary key, is an integer and has a value of zero

### ISSUE THREAD

**Issue by joesteel2010** [jinzhu/gorm#1776]
go version go1.9 linux/arm64

MySQL 5.7

```go
package main

import (
	"fmt"
	"github.com/coreos/go-log/log"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

type SomeFile struct {
	ID     uint   `gorm:"primary_key" json:"-"  sql:"type:int(10) unsigned;"` // Foreign key to another table
	FileID uint   `json:"id" sql:"type:int" xml:"id,attr"`
	Name   string `json:"name" xml:"name"`
	Url    string `json:"url" xml:"url"`
}

var(
	DB *gorm.DB
	working = &SomeFile{
		ID: 12345,
		FileID: 1,
		Name: "image.jpeg",
		Url: "http://somesite.com/images/image.jpeg",
	}

	notWorking = &SomeFile{
		ID: 12345,
		FileID: 0,
		Name: "image.jpeg",
		Url: "http://somesite.com/images/image.jpeg",
	}
)

func main() {
	DB, err := gorm.Open("mysql", fmt.Sprintf("%v:%v@tcp(%v:%v)/%v?parseTime=True&loc=Local", "root", "password", "127.0.0.1", "3306", "database"))
	if err != nil {
		panic(err)
	}
	DB = DB.Set("gorm:table_options", "CHARSET=utf8")
	DB = DB.Debug()
	DB.LogMode(true)
	DB.AutoMigrate(&SomeFile{})

	if err := DB.Create(working).Error; err != nil {
		log.Error(err)
	}
	if err := DB.Create(notWorking).Error; err != nil {
		log.Error(err)
	}
}
```
When running the above code the first record with a FileID of 1 inserts correctly, but the second insert fails. It appears Gorm ignores zero integer values.  

```
(main.go:42) 
[2018-02-21 17:18:22]  [21.74ms]  CREATE TABLE `some_files` (`id` int(10) unsigned,`file_id` int,`name` varchar(255),`url` varchar(255) , PRIMARY KEY (`id`,`file_id`)) CHARSET=utf8  
[0 rows affected or returned ] 

(main.go:44) 
[2018-02-21 17:18:22]  [1.54ms]  INSERT INTO `some_files` (`id`,`file_id`,`name`,`url`) VALUES ('12345','1','image.jpeg','http://somesite.com/images/image.jpeg')  
[1 rows affected or returned ] 

(main.go:47) 
[2018-02-21 17:18:22]  Error 1364: Field 'file_id' doesn't have a default value 

(main.go:47) 
[2018-02-21 17:18:22]  [0.87ms]  INSERT INTO `some_files` (`id`,`name`,`url`) VALUES ('12345','image.jpeg','http://somesite.com/images/image.jpeg')  
[0 rows affected or returned ] 
Feb 21 17:18:22.192 [    ERROR] - Error 1364: Field 'file_id' doesn't have a default value
```

I've managed to work around this by setting a default value of -1 for the column, but this is not ideal, neither is incrementing the FileID as the data is defined externally and the FileID if used to link the file to a record in another table.

**Comment by joesteel2010** [comment]
Solved. Just needed to use a field with Scanner & Value functions as mentioned [here](http://gorm.io/docs/create.html#Default-Values). I'd tried this earlier but forgot to specify the field as a pointer and therefore it didn't match the method signatures I'd defined & I got the error as shown above.

**Comment by rreubenur** [comment]
@joesteel2010  I am facing this issue. Would you please elaborate what you did to avoid this issue. Sorry I couldn't make it out of the provided link.

**Comment by joesteel2010** [comment]
> @joesteel2010 I am facing this issue. Would you please elaborate what you did to avoid this issue. Sorry I couldn't make it out of the provided link.

Hi @rreubenur, yes it wasn't very obvious from the documentation how to solve this, it does take a bit of research to get the full picture. If you are using a custom type as your PK, the functions that you would need to implement are the [Scanner](https://golang.org/pkg/database/sql/#Scanner) and  [Valuer](https://golang.org/pkg/database/sql/driver/#Valuer) interfaces. 
It looks like there are now types provided in the sql package you can use rather than implementing these interfaces yourself, i.e.: https://golang.org/pkg/database/sql/#NullInt64 - I've not tested these but they look like they should work perfectly.

Hope that helps.
