### ISSUE TITLE
QueryExpr not wrapping SELECT with parenthesis

### ISSUE THREAD

**Issue by maxbeatty** [jinzhu/gorm#1777]
### What version of Go are you using (`go version`)?

go version go1.9.4 darwin/amd64

### Which database and its version are you using?

PostgreSQL 10.1 on x86_64-apple-darwin17.2.0, compiled by Apple LLVM version 9.0.0 (clang-900.0.38), 64-bit 

### Please provide a complete runnable program to reproduce your issue

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"fmt"

	"github.com/jinzhu/gorm"
	// postgres is used internally by gorm
	_ "github.com/jinzhu/gorm/dialects/postgres"
)

var db *gorm.DB

func init() {
	var err error

	db, err = gorm.Open("postgres", "user=gorm password=gorm DB.name=gorm port=9920 sslmode=disable")

	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

type Example struct {
	gorm.Model
}

func main() {
	db.AutoMigrate(&Example{})

	db.Create(&Example{})
	db.Create(&Example{})
	db.Create(&Example{})

	latest := Example{}

	if err := db.Select("MAX(id) AS id").Where(
		"id = ?",
		db.Table("examples").Select("id").Where("id = ?", 1).QueryExpr(),
	).Find(&latest).Error; err != nil {
		panic(err)
	}

	fmt.Printf("found latest id: %d", latest.ID)
}
```

`QueryExpr` is not wrapping the `SELECT`. Here's the query to look for in the logs:

```
SELECT MAX(id) AS id FROM "examples"  WHERE "examples"."deleted_at" IS NULL AND ((id = SELECT id FROM "examples"  WHERE (id = '1'))) 
```

Should be:

```diff
SELECT MAX(id) AS ID
FROM "examples"  
WHERE "examples"."deleted_at" IS NULL 
AND (
  (
-    id = SELECT id FROM "examples"  WHERE (id = '1')
+    id = (SELECT id FROM "examples"  WHERE (id = '1'))
  )
)
```

A workaround is to change the first `id = ?` to `id = (?)`. If that's how it should always be, I could try to update the docs for [SubQuery](http://gorm.io/docs/query.html#SubQuery) that shows just `amount > ?`.

**Comment by jinzhu** [comment]
Hello @maxbeatty 

Thank you for your report.

Added a `SubQuery` method, which will be wrapped.

And will deprecate the `QueryExpr` method in v2.
