### ISSUE TITLE
Save with multiple primary keys

### ISSUE THREAD

**Issue by azrle** [jinzhu/gorm#1778]
### What version of Go are you using (`go version`)?
go1.9.2

### Which database and its version are you using?
MySQL, SQLite, etc.

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

The order of primary keys matter `Save`'s behaviors and may cause errors. The reason may be as follows.
When we have multiple primary keys and the first primary key defined in `struct` is int with default 0 or other type with "blank" value, even other primary keys are not "blank", `scope.PrimaryKeyZero()` will fail and `Save` will fall back to `Create`. And then, it can trigger the duplicated key error.

```go
package main

import (
	"fmt"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

type Dummy struct {
	Foo    int    `gorm:"primary_key" sql:"TYPE:int not null default 0"`
	Bar    string `gorm:"primary_key"`
	Foobar string
}

func main() {
	db, err := gorm.Open("sqlite3", "test.db")
	if err != nil {
		panic("failed to connect database")
	}
	defer db.Close()
	db.CreateTable(&Dummy{})

	db.Save(&Dummy{Foo: 0, Bar: "id-xxx", Foobar: "init"})
	var init Dummy
	db.First(&init, "bar = ?", "id-xxx")
	fmt.Printf("%+v\n", init)

	db.Save(&Dummy{Foo: 0, Bar: "id-xxx", Foobar: "updated"})
	var updated Dummy
	db.First(&updated, "bar = ?", "id-xxx")
	fmt.Printf("%+v\n", updated)

	db.DropTable(&Dummy{})
}
```

**Comment by jinzhu** [comment]
Hi @azrle 

Thank you for your report, but I think it might be better to don't allow to use zero value as primary key, or it will cause many other issues when querying and updating...

Iif you still want to use `0` as the default value, you might want to use `NullInt64` or `*int` as primary key's type, like:

```go
type Dummy struct {
	Foo    *int    `gorm:"primary_key" sql:"TYPE:int not null default 0"`
	Bar    string `gorm:"primary_key"`
	Foobar string
}
```

Thank you.
