### ISSUE TITLE
1.9 is not compatible with 1.0

### ISSUE THREAD

**Issue by ptman** [jinzhu/gorm#1782]
### What version of Go are you using (`go version`)?

1.10

### Which database and its version are you using?

postgresql 10

### The problem

With [1.0](https://github.com/jinzhu/gorm/tree/v1.0) our code works and with [1.9](https://github.com/jinzhu/gorm/tree/v1.9) it throws a panic when calling [DB.Exec](https://godoc.org/github.com/jinzhu/gorm#DB.Exec):

    panic: index out of range

**Comment by jinzhu** [comment]
Hello @ptman 

This should be caused by your SQL contains a `?`, I have pushed a commit to fix the panic.

**Comment by ptman** [comment]
Thank you, it worked.
