### ISSUE TITLE
RecordNotFount`s return in defferent situation

### ISSUE THREAD

**Issue by Aavon** [jinzhu/gorm#1783]
**supposing **

-------------------

Table user has no record 

**First**
-------------------
db.Where("1=1").First(&user).RecordNotFount()    ----->true

**Find**
---------------
db.Where("1=1").Find(&users).RecordNotFount()    ----->false

**So**
-----------------
How about them both return true?

**Comment by emirb** [comment]
`RecordNotFound` makes sense with First when you are specifically looking to get one result and in the case of failure it cannot be found.
On the contrary, when doing `Find` you will get an empty result set which is a bit different IMO to a record not found. I'm not sure about changing this behaviour.
