### ISSUE TITLE
About how to nest transaction-functions within one transaction

### ISSUE THREAD

**Issue by lawrsp** [jinzhu/gorm#1792]
**The situation is**:
There are some functions such as A and B.
When called  separately, it should always start a transaction, 
When both called in  All(), they should be  in the same transaction.

The code may like this:

```go

func A(db *gorm.DB) {
    tx := db.Begin()
    if tx.Error != nil {
         panic(err)
    }
    defer commitOrRollback(tx)
    .....
}

func B(db *gorm.DB) {
    tx := db.Begin()
    if tx.Error != nil {
         panic(err)
    }
    defer commitOrRollback(tx)
    .......
}

func All(db *gorm.DB) {
     tx := db.Begin()
     if tx.Error != nil {
         panic(err)
    }
     defer commitOrRollback(tx)

     A(tx)
     B(tx)    
}


```
The problem is:
when A is called in All(),  it would fail because`` tx.Error ``is not nil.

I have 2 solutions:

1. check if in transaction
```go
func A(db *gorm.DB) {
    var tx *grom.DB
    if checkInTrans(db) {
          tx = db
    } else {
          tx = db.Begin()
          if tx.Error != nil {
                panic(err)
           }
    }
    .....
}

func checkInTrans(db *gorm.DB) bool {
      if db.DB() == nil {
            return true
      }

      return false
}
```

2. check the Error
```go

func A(db *gorm.DB) {
    tx := db.Begin()
    if tx.Error != nil  && tx.Error != gorm. ErrCantStartTransaction {
         panic(err)
    }
    defer commitOrRollback(tx)
    .....
}

```

both works  now but all looks ugly
1.  I think gorm is trying to hide the sql.* type. It also hide the difference between  sql.DB and sql.Tx. Only gorm.DB is what we should cares . then db.DB() == nil means in transaction is too implicit
2. Apparently, ErrCantStartTransaction means in transaction is too implicit either

Then I read the code and found gorm also has this situation internally.
Take ``Create`` for example, it use callbacks to make sure create process in a transaction,
The key is in Scope:

```go

// Begin start a transaction
func (scope *Scope) Begin() *Scope {
	if db, ok := scope.SQLDB().(sqlDb); ok {
		if tx, err := db.Begin(); err == nil {
			scope.db.db = interface{}(tx).(SQLCommon)
			scope.InstanceSet("gorm:started_transaction", true)
		}
	}
	return scope
}

```

it use ``if db, ok := scope.SQLDB().(sqlDb); ok `` to test if in transaction, 
but ``sqlDb`` is not exported and I cannot use it.

So, **I want to disscuss :**
1. Maybe it is necessary to  provide a method to tell if gorm.DB is in transaction explicitly?
2. or is there a better solution on my situation?

**Comment by jw-s** [comment]
What I’ve resorted to do is pass a transaction via dB.Begin() to each dao/repository method/function. This way you don’t need to check if it’s in a transaction (also service level should be handling how transactions are carried out) and on return handling the commit/rollback as normal.

**Comment by lawrsp** [comment]
@jw-s it is a top-down solution and is good at some situations. 
But sometimes, it would do some  transactions that donnot need to do.
And I think it would also has the question when  combining services ?

**Comment by jw-s** [comment]
@lawrsp You mean a service method which starts a transaction and also calls another services' method which also runs a transaction?

**Comment by lawrsp** [comment]
@jw-s yes, maybe, just a thought:
if transactions  were  hidden from the inner logics, then there would be some chances  another services' method was called by mistake, for example, an newly joined developer

**Comment by jw-s** [comment]
@lawrsp IMO services should be separate, i.e not interacting with each other. Whats wrong with having two services which share the same DAO/repository? Keeping to those rules you ensure you handle the transaction in that service

**Comment by win5do** [comment]
```sh
func checkInTrans(db *gorm.DB) bool {
      if db.DB() == nil {
            return true
      }

      return false
}
```

This func not work now gorm@v1.9.12, will panic in follow line:

https://github.com/jinzhu/gorm/blob/7180bd0f27d167f18c253c32d548c7de3adc6b0d/main.go#L129

**Comment by lawrsp** [comment]
@win5do don't do this, like jw-s said, separate the services, use begin/end at top level.
I will close this issue
