### ISSUE TITLE
Foreign Key issues/ One to Many relationships

### ISSUE THREAD

**Issue by jw-s** [jinzhu/gorm#1797]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
1.10

### Which database and its version are you using?
Postgres 10.3

First and foremost, thank you very much for this awesome orm library!

I have a few models which I would like to persist.

FYI I have created the initial db schema manually.

However when I construct the top level object `Project` with it's dependencies i receive a foreign key violation.

I am using the `save()` call and I understood it will save all associations also.

What am I doing wrong?

```go
type Project struct {
	Name         string        `gorm:"primary_key;size:255;unique_index"`
	Type         string        `gorm:"primary_key;size:255;index"`
	Repositories []*Repository `gorm:"foreignkey:ProjectName"`
}

type Repository struct {
	Name        string    `gorm:"primary_key;size:255;unique_index"`
	Branches    []*Branch `gorm:"foreignkey:RepositoryName"`
	ProjectName string //foreign key reference
}

type BranchMeta struct {
	Languages []*Language `gorm:"foreignkey:BranchName"`
	BranchName string //foreign key reference
}

type Branch struct {
	Name           string     `gorm:"primary_key;size:255;unique_index"`
	Meta 			BranchMeta  `gorm:"foreignkey:BranchName"`
	Languages  []*Language `gorm:"foreignkey:BranchName"`
	Commits        []*Commit  `gorm:"foreignkey:BranchName"`
	RepositoryName string //foreign key reference
}

type Commit struct {
	Sha         string     `gorm:"primary_key;size:255;unique_index"`
	Message     string
	Timestamp   *time.Time `gorm:"index"`
	AuthorName  string
	AuthorEmail string
	Added pq.StringArray `gorm:"type:varchar(64)[]"`
	Modified pq.StringArray `gorm:"type:varchar(64)[]"`
	Removed pq.StringArray `gorm:"type:varchar(64)[]"`
	BranchName  string //foreign key reference
}

type Language struct {
	Name       string `gorm:"primary_key;size:255;unique_index"`
	Percentage float64
	BranchName string //foreign key reference
}

```

**Comment by Niraj-Fonseka** [comment]
I see this issue is closed. Were you able to figure out what was wrong with it ?

**Comment by jw-s** [comment]
By default if any primary key is set manually (not by gorm) then gorm will do an update rather than create. So to fix this issue you have to implement a BeforeCreate method and set the columns. 
It seems you also have to create a transfer/holder field in your struct which is used to set the real field which is tagged (this way can't be right as its ugly but it works) example: https://github.com/vastness-io/coordinator/blob/master/pkg/model/repository.go
