### ISSUE TITLE
Why postgres not use dataSourceName like mysql mssql?

### ISSUE THREAD

**Issue by a7a2** [jinzhu/gorm#1802]
(suggest):
driverName: postgres
dataSourceName: postgres://postgres:postgres@127.0.0.1:5432/a7a2?sslmode=disable
Other such xorm(https://github.com/go-xorm/xorm) use like this。

(look like a bug?):
My environment:
driverName: postgres
dataSourceName: user=postgres password=postgres DB.name=test port=5432 sslmode=disable
It is not connected to the “test” database, is connected to the “postgres” database，why？

**Comment by jinzhu** [comment]
You can use it

**Comment by a7a2** [comment]
但是你其他的数据库连接都采用同一种格式，为何就postgres不一样。。。

// db, err = gorm.Open("postgres", "user=gorm password=gorm DB.name=gorm port=9920 sslmode=disable")
	// db, err = gorm.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8&parseTime=True")
	// db, err = gorm.Open("mssql", "sqlserver://gorm:LoremIpsum86@localhost:9930?database=gorm")

就还有就是为何配置的是test数据库，最后实际连接的是postgres数据库？
