### ISSUE TITLE
Unable to connect to Cloud SQL with Gorm

### ISSUE THREAD

**Issue by chrisgreg** [jinzhu/gorm#1804]
Here's the code I'm using:

```
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"path"
	"strconv"

	_ "github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/dialers/mysql"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	"google.golang.org/appengine"
        _ "google.golang.org/appengine/cloudsql"
)

var db *gorm.DB

func main() {

	
	dbConnection := "root@cloudsql(project-id:zone:instance-name)/mydbname?charset=utf8&parseTime=True&loc=UTC"
	
	// Initialise DB
	var err error
	db, err = gorm.Open("mysql", dbConnection)

	db.LogMode(false)
	defer db.Close()

	if err != nil {
		panic("Could not establish database connection")
	}
}
```

And I'm getting:

```
ERROR    2018-03-17 13:32:36,665 http_runtime.py:396] bad runtime process port ['']
panic: not an App Engine context
```

It works fine when my DB connection string is pointed to my local host instead of Google Cloud SQL.

I'm also running it with `$ dev_appserver.py app.yaml`

Can anyone help?

**Comment by lennrt** [comment]
I've had some issues with Cloud SQL in the past, but this connection string format works for me:

`username:password@tcp(ipOfInstance:3306)/DBname?charset=utf8&parseTime=True&loc=Local`

What is the generation of your Cloud SQL instance? I'm using a first generation instance, but if you're using a second generation instance then your connection string format will be slightly different. Also make sure that your IP is whitelisted in the Cloud SQL admin panel.

**Comment by penguinpowernz** [comment]
@chrisgreg you find a fix?

**Comment by chrisgreg** [comment]
@penguinpowernz Nope - gave up in the end and the project isn't active anymore so I haven't tried since
