### ISSUE TITLE
add Context

### ISSUE THREAD

**Issue by koalacxr** [jinzhu/gorm#1807]
Support Context : 
BeginTx(ctx context.Context, opts *TxOptions) (*Tx, error)
ExecContext(ctx context.Context, query string, args ...interface{}) (Result, error)
PrepareContext(ctx context.Context, query string) (*Stmt, error)
QueryContext(ctx context.Context, query string, args ...interface{}) (*Rows, error)
QueryRowContext(ctx context.Context, query string, args ...interface{}) *Row

**Comment by posener** [comment]
I think this duplicates #1231

**Comment by alexsn** [comment]
That's from 2 years ago, is gorm never gonna support context? Are we waiting for a PR or is there a general objection to add context support?

**Comment by penguinpowernz** [comment]
Seems like there is some movement over there with some code available to be merged... let's close this and track it in #1231
