### ISSUE TITLE
Add support for case statements in UPDATE calls.

### ISSUE THREAD

**Issue by colegleason** [jinzhu/gorm#181]
I want to be able to atomically change a value in an UPDATE call. An example of this is where I am treating a column as a semaphore and only want to decrement it if it is > 0.

**Comment by jinzhu** [comment]
Hello @colegleason 

Sorry for the delay, this should be supported long time ago without document, just updated the README for the usage.

```go
db.Model(&user).Where("active = ?", true).Update("name", "hello")
```

https://github.com/jinzhu/gorm#update

**Comment by jinzhu** [comment]
Hi @colegleason 

You might would like to checkout this, it should be helpful for you. https://github.com/jinzhu/gorm#update-with-sql-expression
