### ISSUE TITLE
Can I turn off auto transaction in delete/update/insert?

### ISSUE THREAD

**Issue by himulawang** [jinzhu/gorm#1810]
According to this doc: http://gorm.io/docs/transactions.html

GORM perform single create, update, delete operations in transactions by default to ensure database data integrity.

DB will auto add transaction to single operation. I want to let DB do it rather than give it to gorm in order to save some bandwidth usage.

Is there a switch to turn that off?

**Comment by eslizn** [comment]
you can remove transaction callback process：
```go
	db.Callback().Create().Remove("gorm:begin_transaction")
	db.Callback().Create().Remove("gorm:commit_or_rollback_transaction")
	db.Callback().Update().Remove("gorm:begin_transaction")
	db.Callback().Update().Remove("gorm:commit_or_rollback_transaction")
	db.Callback().Delete().Remove("gorm:begin_transaction")
	db.Callback().Delete().Remove("gorm:commit_or_rollback_transaction")
```
