### ISSUE TITLE
更新过gorm后，gorm:"-"无效

### ISSUE THREAD

**Issue by suruns** [jinzhu/gorm#1817]
go version:1.9
database:mysql
question: gorm:"-"无效啊，怎么更新gorm都无效
![image](https://user-images.githubusercontent.com/12554451/38007281-49578ee8-327b-11e8-9ccd-94472c3ff73f.png)

![image](https://user-images.githubusercontent.com/12554451/38007419-e867c250-327b-11e8-8ed5-8872e033d114.png)

**Comment by kaiiak** [comment]
use `sql:"-"`
