### ISSUE TITLE
gorm ignore does not work on scan if table has column with similar name as struct field

### ISSUE THREAD

**Issue by mnokhatov** [jinzhu/gorm#1826]
I use skinny version of actual model to read records from table. Table has column 'version' type string.
When i scan i got error:
`sql: Scan error on column index 4: converting driver.Value type string ("") to a int: invalid syntax`

If a rename model field 'Version' to 'Ver' i can scan with no problem. The model i used is:
```
type TransportLicensor struct {
	Id              int    `gorm:"primary_key"`
	Idver           string `gorm:"primary_key"`
	Version             int    `json:"version" gorm:"-"`
}
```

**Comment by tofindme** [comment]
**some scan code as follow:**

`	for index, column := range columns {
		values[index] = &ignored

		selectFields = fields
		if idx, ok := selectedColumnsMap[column]; ok {
			selectFields = selectFields[idx+1:]
		}

		for fieldIndex, field := range selectFields {
			if field.DBName == column {
				if field.Field.Kind() == reflect.Ptr {
					values[index] = field.Field.Addr().Interface()
				} else {
					reflectValue := reflect.New(reflect.PtrTo(field.Struct.Type))
					reflectValue.Elem().Set(field.Field.Addr())
					values[index] = reflectValue.Interface()
					resetFields[index] = field
				}

				selectedColumnsMap[column] = fieldIndex

				if field.IsNormal {
					break
				}
			}
		}
	}

	scope.Err(rows.Scan(values...))`

**ignored fields also save the value read from table.**

**Comment by mYmNeo** [comment]
@mnokhatov Add a tag `sql:"-"` to `Version`?

**Comment by mYmNeo** [comment]
@mnokhatov Add a tag `gorm:"column:xxx"` to make this field name not `Version`
