### ISSUE TITLE
How to un default UpdatedAt when create

### ISSUE THREAD

**Issue by gdunghi** [jinzhu/gorm#1827]
when i Create i got updatedAt in the same value with createdAt how to disable it
type Product struct {
	gorm.Model
	CreatedBy string `json:"createdBy" gorm:"size:35"`
	UpdatedBy string `json:"updatedBy" gorm:"size:35"`
	Name         string   `json:"name" gorm:"size:50"`
}

**Comment by dongshimou** [comment]
mabe you can use `UpdateColumns ` ,update what do you want.

i only know  "skip update." when you save the [associations](http://gorm.io/docs/associations.html)

Skip AutoUpdate
If your association is already existing in database, you might not want to update it.
You could use DB setting, set gorm:association_autoupdate to false
