### ISSUE TITLE
Condition of zero value query is not working

### ISSUE THREAD

**Issue by fcce** [jinzhu/gorm#1829]
### go version
`go version go1.10 darwin/amd64`

###  database 
`PostgreSQL/Sqlite`

### Problem
for the query

    db.Where(&Tag{Category: 0}).Find(&tags)

result according to GORM logging is:

    SELECT * FROM "tags"

but when Category is '1', the SQL is correct, Is's sames a bug.

By the way, Category is a `int8` column, but in the SQL it's a string value.
Type conversion will not use index.

Here is the full code

    package main

    import (
      "fmt"
      "github.com/jinzhu/gorm"
      _ "github.com/jinzhu/gorm/dialects/sqlite"
    )

    type Tag struct {
      Category int8
      Title    string `gorm:"varchar(255)"`
    }

    func main() {
      db, err := gorm.Open("sqlite3", `test.db`)
      if err != nil {
        fmt.Println(err)
      }
      defer db.Close()
      db.LogMode(true)
      db.AutoMigrate(&Tag{})
      var tags []*Tag
      db.Where(&Tag{Category: 0}).Find(&tags)
      // SELECT * FROM "tags"
      db.Where(&Tag{Category: 1}).Find(&tags)
      // SELECT * FROM "tags"  WHERE ("tags"."category" = '1')
      db.Where(map[string]interface{}{"Category": 0}).Find(&tags)
      // SELECT * FROM "tags"  WHERE ("tags"."category" = '1')
    }

**Comment by s-takehana** [comment]
Please see http://gorm.io/docs/query.html#Struct-amp-Map

> When query with struct, GORM will only query with those fields has non-zero value, that means if your field’s value is 0, '', false or other zero values, it won’t be used to build query conditions

**Comment by fcce** [comment]
I saw this document.But I don't understand what's the advantages of this design or why do thus design? It looks a bit strange @s-takehana

**Comment by fcce** [comment]
This seems to be an unsolvable problem, can't determine `struct` default value. I close this issue.
