### ISSUE TITLE
`gorm:"auto_preload"` struct tag

### ISSUE THREAD

**Issue by JustonDavies** [jinzhu/gorm#1832]
A version of the documentation found at [docs.gorm.io](http://doc.gorm.io/crud.html#preloading-eager-loading) shows the ability to use a struct tag to automatically preload certain associated models via a callback. I can't seem to get that to work. Is this the intended behavior?

The scope tag DOES work, but its easier in my case (a composite) to state what I would like to load instead of everything I wouldn't like to load and it would be best if that happened automatically.

### What version of Go are you using (`go version`)?
1.9.3

### Which database and its version are you using?
SQLite3

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
[Sample code here](https://gist.github.com/JustonDavies/a695373af82dae514cc6c9e53979f273)
[Also attached here](https://github.com/jinzhu/gorm/files/1876774/main.txt)

**Comment by s-takehana** [comment]
@JustonDavies [doc.gorm.io](http://doc.gorm.io/crud.html#preloading-eager-loading) is old, please see [gorm.io](http://gorm.io/docs/preload.html#Auto-Preloading) .

For more detail, please see #1451 .

**Comment by s-takehana** [comment]
I think Auto Preload behavior has not changed.

#1451 was merged into master branch in 4 May 2017.

This commit(Document Auto Preload) ff8709de is 12 Feb 2018.
