### ISSUE TITLE
How to set utf-8 as default charset?

### ISSUE THREAD

**Issue by jinfagang** [jinzhu/gorm#1835]
Thanks for this very good lib.
When call:
```
	db.AutoMigrate(&Product{})

```
this generate a default latin charset table, no problem for English strings, but when using charaters such as Chinese, error appears:
```
(Error 1366: Incorrect string value: '\xE9\xA6\x99\xE8\x95\x89' for column 'name' at row 1) 

```

We can change charset in mysql console, but this is really in-convinient. How to set utf-8 as default charset anyway?

**Comment by EfimovArtem** [comment]
@dongshimou It didn't help me(

**Comment by dongshimou** [comment]
@EfimovArtem
 
I use mysql 5.7
this is my example
```
args := fmt.Sprintf("%s:%s@tcp(%s:%s)/%s?charset=utf8&parseTime=True&loc=Local",
		cfg.Username, cfg.Password, cfg.Host, cfg.Port, cfg.Database)
db, err = gorm.Open("mysql", args)
//err ...
db = db.Set("gorm:table_options", "ENGINE=InnoDB CHARSET=utf8 auto_increment=1")
```
then `db.AutoMigrate(&Product{})`

**Comment by jinfagang** [comment]
Thanks for help. I finally end up with change MySQL default encoding after installed it. So that later on new db or table the encoding will be utf-8.

**Comment by penguinpowernz** [comment]
Jinfagang, is this all fixed?

**Comment by ZandorZ** [comment]
> Thanks for this very good lib.
> When call:
> 
> ```
> 	db.AutoMigrate(&Product{})
> ```
> this generate a default latin charset table, no problem for English strings, but when using charaters such as Chinese, error appears:
> 
> ```
> (Error 1366: Incorrect string value: '\xE9\xA6\x99\xE8\x95\x89' for column 'name' at row 1) 
> ```
> We can change charset in mysql console, but this is really in-convinient. How to set utf-8 as default charset anyway?

Isn't it Emoji chars?  I had the same problem while back, and I moved from utf8 to utf8mb4 character set
Maybe this will help 
https://hackernoon.com/today-i-learned-storing-emoji-to-mysql-with-golang-204a093454b7
