### ISSUE TITLE
login error:read tcp 192.168.1.250:52948->192.168.1.211:1433?

### ISSUE THREAD

**Issue by 107295472** [jinzhu/gorm#1839]
login error:read tcp 192.168.1.250:52948->192.168.1.211:1433:wsarecv:An existing connectio was f   could not find symbol value for s

**Comment by darkhandz** [comment]
[see here](https://github.com/denisenkom/go-mssqldb/issues/121)
> Edit: I see that scohen28 did mention go version, perhaps an entry in the readme will help others.
> 
> This may also apply when upgrading to go1.5. Error:
> Cannot connect: Login error: EOF
> 
> Appending "encrypt=disable;" to the connection string does allow the connection.
