### ISSUE TITLE
Issue with updating fields with empty/default values using Select()

### ISSUE THREAD

**Issue by ik9999** [jinzhu/gorm#1842]
When the bool field value is false, gorm doesnt update using .Select(fieldName). Works with Save though.

### What version of Go are you using (`go version`)?
1.10rc2

### Which database and its version are you using?
PostgreSQL 10.3

```go
  db.DBManager().Select("BoolField").Model(model).Updates(model)
```

Model:
```go
package models

type Commodity struct {
  BaseModel
  BoolField bool `gorm:"column:bool_field;type:boolean;default:false" valid:"-" json:"bool_field" form:"bool_field" query:"-"`
}

```

**Comment by dongshimou** [comment]
I am not sure whether to solve your problem.
in mysql.
```
Type Test struct{
  SomeField uint
}
```
i use the `Model(&Test{}).Select("some_field").xxxxx`
the gorm will generate the database's column `some_field`.
confirm your column's real name.and make sure the `Model` before the`Select`.

**Comment by ik9999** [comment]
@dongshimou Can you confirm it works for you in latest release version?

**Comment by dongshimou** [comment]
yes. see the [doc](http://gorm.io/docs/update.html)

if you use the struct update . make sure the update column is not default value.

for example :  `v:=Test{}`.   default value: `v.SomeField` == `0`, if you wan't update to `0`,

`Model(&Test{}).Update(&v)`.  the `some_field` column will not be update.

it will be failure.

**Comment by ik9999** [comment]
>BoolField bool

The value is bool type. And i can't update it to false because false is a default value for bool.
And bool field cant be set to false with `Model(&Test{}).Select("some_field")`

**Comment by dongshimou** [comment]
use the `map[string]interface{}` to update. :)

**Comment by ik9999** [comment]
@dongshimou 
I know that its possible to do with `map[string]interface{}` or `.Save()`.
Ive opened this issue because it should be possible to do it with `Select()` and `Update()` as well.
https://github.com/jinzhu/gorm/issues/469#issuecomment-95776852

**Comment by egeozcan** [comment]
set the field to *bool?

**Comment by penguinpowernz** [comment]
@ik9999 did you find a solution?

**Comment by ik9999** [comment]
@penguinpowernz No, i stopped using gorm and use query builders + sqlx instead.

**Comment by penguinpowernz** [comment]
@ik9999 thanks for replying
