### ISSUE TITLE
.Create does a random SELECT after INSERT

### ISSUE THREAD

**Issue by joaodlf** [jinzhu/gorm#1845]
Go 1.9
Postgres 10

I have a structure like so:
```
type UserAgents struct {
	ID           int64     `gorm:"primary_key"`
	DtCreated    time.Time `gorm:"DEFAULT:NOW();not null"`
	UserAgent    sql.NullString
	Family       sql.NullString
	OsFamily     sql.NullString
	DeviceFamily sql.NullString
}
```

When I use .Create and check my logs, I see the following queries:
```
(../user_agents.go:42)
[2018-04-12 10:48:34]  [4.96ms]  INSERT INTO "user_agents" ("user_agent","family","os_family","device_family") VALUES ('Test','Other','Other',
'Other') RETURNING "user_agents"."id"
[1 rows affected or returned ]

(../user_agents.go:42)
[2018-04-12 10:48:34]  [5.09ms]  SELECT "dt_created" FROM "user_agents"  WHERE (id = '8')
[1 rows affected or returned ]
```

I don't understand why Gorm is executing the SELECT directly after the INSERT. The logs indicate both queries were triggered by the .Create line. So it's not an action from another piece of code. 

Why does it do a select? And why does it use the dt_created column?

**Comment by s-takehana** [comment]
Because it's `DEFAULT` tag.
Please see http://gorm.io/docs/create.html#Default-Values .

> Then the inserting SQL will exclude those fields that don’t have value or having zero values, after insert the record into database, gorm will load those fields’s value from database.

**Comment by joaodlf** [comment]
Ah! Makes sense, thank you! Closing this now.
