### ISSUE TITLE
How to contribute to documentation?

### ISSUE THREAD

**Issue by andrewspringman** [jinzhu/gorm#1856]
On the English version of the Transactions page (http://gorm.io/docs/transactions.html):

"If you want to tread multiple create, update, delete as one atomic operation, Transaction is made for that."

tread should be treat

That's the example that made me look for how to contribute.  I don't just want to fix this minor typo.  What is the best way to contribute to the documentation in general?  Is there a separate repo for that?

**Comment by zardak** [comment]
https://github.com/jinzhu/gorm.io
