### ISSUE TITLE
gorm models可以同时支持gin validator吗

### ISSUE THREAD

**Issue by WUJJU** [jinzhu/gorm#1874]
同一个model，想既可以支持gorm来创建数据库表，又可以当做http传入参数的校验。
怎么能够同时支持 go-playgroud validator？

type CreditCard struct {

	CardNumber string `gorm:"type:varchar(255)"`
	Password   string `gorm:"type:varchar(255)"`
	IsValid    bool   `gorm:"default:true"`
	ExpireDate time.Time
}

**Comment by lrita** [comment]
You can add multi struct tag by yourself.
```go
type CreditCard struct {
  CardNumber string `gorm:"type:varchar(255)" valid:"xxx"`
  Password   string `gorm:"type:varchar(255)"  valid:"xxx"`
  IsValid    bool   `gorm:"default:true"  valid:"xxx"`
  ExpireDate time.Time
}
```
