### ISSUE TITLE
Error in GORM Documentation for Preload

### ISSUE THREAD

**Issue by gilmarpalega** [jinzhu/gorm#1889]
correct keyword AssociationForeignkey (this works)
in documentation is association_foreignkey (doesn't work)

I spent a lot of time trying to figure out why the correct data wasnt being retrieved.

according to documentation I should use:
Documents 			[]Documents `gorm:"ForeignKey:UsuarioId;association_foreignkey:AlunoId"`

And the correct way is:
Documents 			[]Documents `gorm:"ForeignKey:UsuarioId;AssociationForeignkey:AlunoId"`

**Comment by emirb** [comment]
Both of them are supported:
https://github.com/jinzhu/gorm/blob/master/model_struct.go#L279-L282
