### ISSUE TITLE
Dry run/ SQL Dump for auto migrations

### ISSUE THREAD

**Issue by tom10271** [jinzhu/gorm#1920]
Hi, I am a PHP and Golang developer. In PHP our team use Doctrine 2.0 which is a perfect ORM in PHP world. The way they handle migrations is a bit safer for me as they will prepare and dump entity changes into a runnable php file and store migrated version in DB for tracking. 

In gorm it looks it will resolve and run change directly without my approval, I am concerned about what if I accidentally added one more or removed one of the field in a struct making production data loss.

I want gorm to dump the changing sql only and let me run it on DB server manually after human checking.

**Comment by snowwolf007cn** [comment]
It's a good suggestion, why nobody answers and leads it to close?

**Comment by roger-king** [comment]
Im looking into a better migration approach using Flyway and would to get the SQL output from Gorm on Table creation. I know I can write myself but it would save time.
