### ISSUE TITLE
github.com/go-sql-driver/mysql auth update leads to panic 

### ISSUE THREAD

**Issue by zwpaper** [jinzhu/gorm#1922]
issue checked, no dup found.

### What version of Go are you using (`go version`)?
go version go1.8 linux/amd64

### Which database and its version are you using?
mysql 5.1.73

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
get the newest version of `github.com/go-sql-driver/mysql`
connect to mysql server

before https://github.com/go-sql-driver/mysql/pull/807, it will panic
after the PR, will show up 
```
[mysql] 2018/05/30 14:36:31 auth.go:191: unknown auth plugin:
[mysql] 2018/05/30 14:36:31 driver.go:120: could not use requested auth plugin '': this authentication plugin is not supported
```
It seems work normally, but I do not know whether there will be problems using like this...

**Comment by nodew** [comment]
https://github.com/go-sql-driver/mysql/issues/828

**Comment by zwpaper** [comment]
this is the driver's issue, further information can look into https://github.com/go-sql-driver/mysql/issues/815, I's closing this issue.
