### ISSUE TITLE
The precondition to perform the delete is invalid?

### ISSUE THREAD

**Issue by TaoSunkist** [jinzhu/gorm#1932]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

#### postgres
```
eg1:
tx.Debug().Where("coin_id = ?", symbol.Name).Delete(&blockcc.Ticker{})
Output: DELETE FROM "temp_tickers"  WHERE (coin_id = 'okb')

eg:2
tx.Debug().Delete(&blockcc.Ticker{CoinID: symbol.Name})
Output: DELETE FROM "temp_tickers"  
```
Why the condition specified in eg2 is invalid?

**Comment by gstvg** [comment]
Isnt invalid, gorm just wont use non-primary fields on Delete. 

http://doc.gorm.io/crud.html#delete  says:

"WARNING When delete a record, you need to ensure it's primary field has value, and GORM will use the primary key to delete the record, if primary field's blank, GORM will delete all records for the model"

If you called BlockGlobalUpdate(true) then delete with no pk is a no-op.
Similar behavior of what you expected can be achieved with db.Where(&ticker).Delete(&ticker)
