### ISSUE TITLE
delete where question

### ISSUE THREAD

**Issue by itcuihao** [jinzhu/gorm#1942]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?

`go version go1.10 linux/amd64`

### Which database and its version are you using?

`5.7.18-log`

```
// Delete delete
func (pes PlanEmployeeStore) Delete(pid, eid string, db *store.DB) error {

	if err := db.Where("plan_id=? AND employee_id=?", pid, eid).Delete(&PlanEmployee{}).Error; err != nil {
		return errors.ErrGeneralInternalFault
	}

	return nil
}
```
程序执行，但是数据未删除，将SQL日志拷贝到数据库中执行，删除成功。

```
// DeleteByEmployeeID delete
func (pes PlanEmployeeStore) DeleteByEmployeeID(db *store.DB, eid string) error {

	if err := db.Where("employee_id=?", eid).Delete(&PlanEmployee{}).Error; err != nil {
		return errors.ErrGeneralInternalFault
	}

	return nil
}

```
程序执行，数据删除

这样多个where条件执行delete的时候会有什么不同吗？

**Comment by gstvg** [comment]
db.Where("employee_id=?", eid).Where("plan_id=?", pid).Delete(&PlanEmployee{})

**Comment by itcuihao** [comment]
需要这样操作吗？ @gstvg

**Comment by gstvg** [comment]
yes. if you really wanna write that way: db.Where(gorm.Expr(""plan_id=? AND employee_id=?", pid, eid")). Inline AND is okay, but with OR would probably work different from what generally is expected.

**Comment by gstvg** [comment]
Sorry, i thought that yes but not really, i dont know why your first code dont worked, it should have. With two Where´s it worked?
