### ISSUE TITLE
how to insert null value to datetime column ?

### ISSUE THREAD

**Issue by DivXPro** [jinzhu/gorm#1943]
btw: when fetch a row from database, the null will be "0001-01-01 00:00:00", how to make it to be null ？

**Comment by gstvg** [comment]
Just make the struct field a pointer to time.Time

type User struct {
    gorm.Model
    FirstPurchase *time.Time
}

**Comment by BaBaSwan** [comment]
I tried using MSSQL (microsoft SQL server) and it works when creating a new record. The value of 'FirstPurchase' field will be null. 

But when I bind the data from SQL database to structure, the value of 'FirstPurchase' will become null no matter it has value or not.

How can it be solved? 

FYI, the range of datetime of MSSQL  is January 1, 1753, through December 31, 9999 and it will have out of range error when default "0001-01-01 00:00:00" is inserted into the database.

https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-2017

**Comment by ThinkontrolSY** [comment]
The same issue, can not insert null to timestamp field

```go
type StateLog struct {
	gorm.Model
	EquipmentId string
	Equipment   *Equipment
	StateId     string
	State       *State
	Enter       *time.Time
	Leave       *time.Time
}
```
When I insert a row into db by create function, I get blow sql statement
```sql
INSERT  INTO "smt_ep_state_logs" ("created_at","updated_at","deleted_at","equipment_id","state_id","enter","leave") VALUES ('2019-12-12 09:39:03','2019-12-12 09:39:03',NULL,'FJX01_KX_A','fault','2019-12-12 01:39:02','2019-12-12 09:39:03') RETURNING "smt_ep_state_logs"."id"
```
the inserted content:
```
StateLog<ID: 0, EquipmentId: FJX01_KX_A, StateId: fault, Enter: 2019-12-12 01:39:02 +0000 UTC, Leave: <nil>>
```

deleted_at field insert null as expected
but leave field change to "2019-12-12 01:39:02" automaticly, where it should be null as deleted_at
