### ISSUE TITLE
create release tags

### ISSUE THREAD

**Issue by KosToZyB** [jinzhu/gorm#1944]
Can you tag the releases going forward?

For example, [this](https://github.com/jinzhu/gorm/commit/6842b49a1ad0feb6b93be830fe63a682cf853ada)  commit has changes for version upgrade 1.9.2.

**Comment by emirb** [comment]
Hi @KosToZyB. From now on we will regularly publish new semver releases. 
[v1.9.4](https://github.com/jinzhu/gorm/releases/tag/v1.9.4) was just released.
