### ISSUE TITLE
mysql里面如果存map[string]string数据

### ISSUE THREAD

**Issue by richardxz** [jinzhu/gorm#1949]
如题，用gorm 连接mysql，好像不支持map类型的数据，有办法workaround吗？或者有办法让创建table时忽略这种类型的数据吗？

**Comment by gstvg** [comment]
Using the tag gorm:"-"

type User struct {
      gorm.Model
      Name string
      IgnoredMap map[string]string `gorm:"-"`
}

If you need to save the map on db, you can create custom Scanner and Valuer for that type:

type MyMap map[string]string

func (m MyMap) Scanner...
func (m MyMap) Valuer...

**Comment by richardxz** [comment]
您好，请问我下面的代码有什么问题吗？在mysql里面还是报不支持

type Annotation map[string]string

func (annotation Annotation)Scan(val interface{}) error{
	switch val := val.(type){
	case string:
		return json.Unmarshal([]byte(val), annotation)
	case []byte:
		return json.Unmarshal(val, annotation)
	default:
		return errors.New("not support")
	}
	return nil
}

func (annotation Annotation)Value() (driver.Value, error){
	bytes, err := json.Marshal(annotation)
	return string(bytes), err
}

**Comment by lvzhihao** [comment]
Scan的话应该func(c *Annotation) Scan(value interface{}) error {}

**Comment by richardxz** [comment]
这方式也试过了，也不行 是不是mysql不支持这样做？

**Comment by xlebenny** [comment]
Have you try specify type?

Change
````
type Annotation map[string]string
````
to
````
type Annotation map[string]string `gorm:"type:LONGTEXT"`
````

**Comment by richardxz** [comment]
when add  `gorm:"type:LONGTEXT"`, the result is same， what can i do to add map to mysql ?

**Comment by xlebenny** [comment]
Finally, i did it https://github.com/xlebenny/397930717

You need change 
````
type Annotation map[string]string
````
to
````
type Annotation struct {
	Values map[string]string `gorm:"type:LONGTEXT"`
}
````

**Comment by richardxz** [comment]
thank you， i can use annotation in mysql now @xlebenny
