### ISSUE TITLE
custom Model struct doesn't populate ID properly

### ISSUE THREAD

**Issue by ags799** [jinzhu/gorm#1950]
### What version of Go are you using (`go version`)?
1.10

### Which database and its version are you using?
Postgres 9.4

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
Will provide soon. Basically, if I have
```
type model struct {
  ID uuid.UUID
}

type Person struct {
  model
  Name string
  Age int
}

func main() {
  ...
  p := Person{"Bob", 34}
  db.Create(&p)
  fmt.Println(p.ID)
}
```

the ID doesn't get set.

**Comment by ags799** [comment]
I have created a repo as an example of this bug: https://github.com/ags799/gorm-1950

**Comment by zxdvd** [comment]
@ags799  maybe you should use `type Model struct` instead of `type model struct` so that gorm can access the `p.ID`.

**Comment by ags799** [comment]
@zxdvd thanks this works
