### ISSUE TITLE
Create → Load Association

### ISSUE THREAD

**Issue by matthew-noken** [jinzhu/gorm#1954]
Hi, is it possible to do something like the following?

```
type Pet struct {
    gorm.Model
    Name string
    OwnerID int64
    Owner Owner
}

type Owner struct {
    gorm.Model
    Name string
}

pet := Pet{
    Name: "Fido",
    OwnerID: 1,
}
if err := db.Create(&pet).Load("Owner").Error; err != nil {
    return err
}
```

In this case `Load()` would populate pet.Owner. Currently, I have to do something like this:

```
pet := Pet{
    Name: "Fido",
    OwnerID: 1,
}
if err := db.Create(&pet).Error; err != nil {
    return err
}
if err := db.Preload("Owner").Find(pet, pet.ID).Error; err != nil {
    return err
}
```

Having a Load method would be one less query. But maybe this functionality already exists and I've missed it? Thanks!

**Comment by gstvg** [comment]
Hi, for that simple and specific case you can do that:
`db.First(&pet.Owner, pet.OwnerID)`

For slices of models or has_many and many_to_many, i think that my pull request would help:
https://github.com/jinzhu/gorm/pull/1926

Would be that way:
`db.Preload("Owner").Preloads(&pet)`

Only table for Owner would be queried 

(i know, not the best name but i prefer let to jinzhu itself choose a more appropriate name)

If you like, please comment the pull and like it, or even better, if you can, write the tests, i have no time now. I close the pull if you open a new and better one. Thanks

**Comment by matthew-noken** [comment]
@gstvg Thanks for replying! I ran into a logic bug with `CreateTable()` creating invalid SQL that forced me to switch to https://github.com/go-pg/pg instead (I didn't have time to create a repro case and thus didn't file a ticket), but this was more about doing a second query after inserting `Pet` in order to populate `Owner`. If you can use `Preload()` with `Create()` (I didn't think to try) then that would have solved my problem.

**Comment by jinzhu** [comment]
Use `Related`
