### ISSUE TITLE
rawsql with add '' to the field

### ISSUE THREAD

**Issue by javahuang** [jinzhu/gorm#1968]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
1.9.2

### Which database and its version are you using?
mysql 5.7.12

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
rawSql :=
`select * from table_a 
where name like ? limit ? offset ?`

db.Raw(rawSql, "jack", 1, 12)
```
the result sql will be

```sql
select*from table_a where name like 'jack' limit '1' offset '12'
```
wille cause that
`Error : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''10' offset 0' at line 1`

so what should i do to remove the **''** of the limit and offset

**Comment by pedromorgan** [comment]
Try `db.Raw(rawSql, "jack").Limit(1).Offset(12)`

If problems then re-open this issue
