### ISSUE TITLE
Migration 时忽略某些动态字段

### ISSUE THREAD

**Issue by hectorqin** [jinzhu/gorm#1969]
struct 里面有一些字段是sql计算出来的动态字段，能不能在自动迁移表结构时忽略这些字段？

**Comment by hectorqin** [comment]
我知道了，使用 - 忽略就行了

http://gorm.io/docs/models.html

**Comment by birdycn** [comment]
使用-导致无法读取。。。

**Comment by birdycn** [comment]
你好，使用gorm - 的话不会导致无法读取到 字段值吗？

**Comment by birdycn** [comment]
> 我知道了，使用 - 忽略就行了
> 
> http://gorm.io/docs/models.html

大哥你是不是搞错了。。

gorm - 忽略后，find和scan都拷贝不到字段上的。。
