### ISSUE TITLE
gorm delete all records if ID is 0

### ISSUE THREAD

**Issue by ComeBurguburu** [jinzhu/gorm#1970]
When the ID of the structure is 0 Gorm delete ll the records of the table

### What version of Go are you using (`go version`)?
go 1.9

### Which database and its version are you using?
mysql

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

func init() {
	var err error
	db, err = gorm.Open("sqlite3", "test.db")
	// db, err = gorm.Open("postgres", "user=gorm password=gorm DB.name=gorm port=9920 sslmode=disable")
	// db, err = gorm.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8&parseTime=True")
	// db, err = gorm.Open("mssql", "sqlserver://gorm:LoremIpsum86@localhost:9930?database=gorm")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}
struct Truck type{
Model
}

func main() {
        db.AutoMigrate(&Truck{})
	db.LogMode(true)
	truck := data.Truck{}
	db.Delete(truck)
	truck.ID = 1
	db.Delete(truck)
}
```
Here are gorm queries logged

UPDATE "trucks" SET "deleted_at"='2018-07-04 18:28:38'  WHERE "trucks"."deleted_at" IS NULL  
UPDATE "trucks" SET "deleted_at"='2018-07-04 18:28:38'  WHERE "trucks"."deleted_at" IS NULL AND "trucks"."id" = '1'

The first query should be 
UPDATE "trucks" SET "deleted_at"='2018-07-04 18:28:38'  WHERE "trucks"."deleted_at" IS NULL AND "trucks"."id" = '0'

**Comment by ermik** [comment]
Storing a `0` in your surrogate key can lead to confusion, since `0` can be read as `NULL` in some circumstances. In database design this is not a recommended practice and I suspect that's why this package is mishandling this use case. Is your sequential surrogate key (in the DB itself) configured to start at `0` or are you just inserting `0` as the value for the first row? (You see, again, "first" usually means "1 place", not "0 place".)

**Comment by ComeBurguburu** [comment]
So the query should be 
Where ID=0
or 
Where ID is null
or gorm should throw an error ID can't be 0

**Comment by ComeBurguburu** [comment]
The explication is here ID=0 is considered as blank
https://github.com/jinzhu/gorm/blob/0fd395ab37aefd2d50854f0556a4311dccc6f45a/scope.go#L721

**Comment by ermik** [comment]
Yea, I really hope that @jinzhu will address this, since it needs to be either supported or needs to fail _loudly_.

**Comment by pedromorgan** [comment]
So closing in favour of #2025 (another dupe). Even I been stung by this!
