### ISSUE TITLE
UpdateUnseafe() function

### ISSUE THREAD

**Issue by daltonfury42** [jinzhu/gorm#1973]
#1112 

Today I ended up accidentally updating all rows of a table, because I had accidentally passed an object with empty primary keys to update.

The mistake was mine, but I think it will be a good feature for all the current update functions to update only if primary key is checked. Then an updateUnsafe() function to update without checking primary keys can be added to the API.

**Comment by pedromorgan** [comment]
Closed for #2025 dupe
