### ISSUE TITLE
gorm with mssql

### ISSUE THREAD

**Issue by dengxuesong** [jinzhu/gorm#1986]
i use mssql, when i use db.first() it return  mssql: in fetch the next is unvalid, is there some different for use gorm with mssql , please give me some help.

**Comment by dengxuesong** [comment]
does gorm only support sqlserver2012? 
the gorm general the sql "SELECT * FROM [Account]  WHERE (PhoneNumber='') OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY " cannot execute in sqlserver2008 r2.

**Comment by legion-zver** [comment]
@dengxuesong you upbeat can describe your dialect and rejoice in life;-)
