### ISSUE TITLE
postGRESQL network types mapped into golang net type support (net.IP, net.HardwareAddr)

### ISSUE THREAD

**Issue by Matt-Texier** [jinzhu/gorm#1987]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?

1.10.3

### Which database and its version are you using?

postGRESQL : 9.5.13

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

I don't have a runnable code for now and I am more asking for help.

I did couple of changes in my fork of gorm to integrate postGRESQL network types (https://www.postgresql.org/docs/9.1/static/datatype-net-types.html) and map it to native network types supported by golang net package.

Please have a look at: 
https://github.com/Pragma-Innovation/gorm/blob/postgre-network-types/dialects/postgres/postgres.go
and
https://github.com/Pragma-Innovation/gorm/blob/postgre-network-types/dialect_postgres.go

I tried to reproduce what has been done for json type support and explain in issue: https://github.com/jinzhu/gorm/issues/1183

I do have a type support issue:
```
(sql: converting argument $13 type: unsupported type postgres.Inet, a struct) 
[2018-07-16 15:58:43]  

(sql: converting argument $13 type: unsupported type postgres.Inet, a struct) 
[2018-07-16 15:58:43]  

(sql: converting argument $13 type: unsupported type postgres.Inet, a struct) 
[2018-07-16 15:58:43]  
```
Using my test program

https://github.com/Matt-Texier/gorm-test

I was not able to find the issue and whether my approach to solve this issue was the right one ... 

Could you please give me a little help ?

Thanks Matt.

**Comment by mykytanikitenko** [comment]
I guess you need pointer to postgres.Inet

**Comment by qianfangyuan** [comment]
Does gorm support postgres.Inet ?
