### ISSUE TITLE
How to find if all the tables are added to the db(db:postgres)

### ISSUE THREAD

**Issue by kgrvamsi** [jinzhu/gorm#1989]
### What version of Go are you using (`go version`)?
go 1.10.3

### Which database and its version are you using?
postgres

Issue: How can i find if all the row inserts are done when dealing with a array of records(consider like 300) any way to findout if all the records are been added (can we do len of the array check to the records added in the db (don't want to query the db though))

**Comment by ermik** [comment]
Try reading the transaction parameters in `AfterUpdate` hook, it has `.RowsAffected`
