### ISSUE TITLE
How can i implement complex query filter condition such as :     a and b and (c or d or e)

### ISSUE THREAD

**Issue by matrixstylite** [jinzhu/gorm#1998]
after i read all the guide document, i am still confuse how cloud i implement complex query condition:
such as:     

select * from test where a_cond and b_cond and (c_cond or d_cond or e_cond)

except to use:
db.where(a_cond, arg1).where(b_cond, arg2).where("c_cond or d_cond or e_cond", args3, args4, args5)

**Comment by ermik** [comment]
Can you show the data model you are using (the struct)?

**Comment by evan-xie** [comment]
type User struct {
	Id string
	Mobile string
	Email string
	Username string
	Password string
	Status int
        Locked int
}

I want to get the result like:
select * from `user` where `status` = 1 and `locked` = 0 and (`mobile` = '888888' or `email` = 'test@test.com' or `username` = 'test')  order by `id` ASC LIMIT 1

**Comment by evan-xie** [comment]
package main

import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
	"github.com/jinzhu/gorm"
	"log"
)

type User struct {
	Id string
	Mobile string
	Email string
	Username string
	Password string
	Status int

}

func AndOr(db *gorm.DB,m map[string]interface{}) (*gorm.DB) {
	if m == nil {
		return db
	}
	str := ""
	args := make([]interface{},0,len(m))
	for k,v := range m{
		str = str + k +" = ? or "
		args = append(args,v)
	}
	str = string([]rune(str)[:len(str)-4])

	return db.Where(str,args...)
}

func main() {
	db,err := gorm.Open("mysql","root:root@(8.8.8.8:3306)/pmm?charset=utf8&parseTime=True")

	if err != nil {
		log.Fatalln(err)
	}
	db.LogMode(true)

	user := User{}

	query := db.Where("status = ?",1)
	query = AndOr(query,map[string]interface{}{"mobile":"888888","email":"test@test.com"})
	dbErr := query.First(&user).Error

	if dbErr != nil{
		log.Fatal(dbErr)
	}
	log.Fatalln(user)

}

**Comment by evan-xie** [comment]
<
package main

import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
	"github.com/jinzhu/gorm"
	"log"
)

type User struct {
	Id string
	Mobile string
	Email string
	Username string
	Password string
	Status int

}

func AndOrs(db *gorm.DB,m map[string]interface{}) (*gorm.DB) {
	if m == nil {
		return db
	}
	str := ""
	args := make([]interface{},0,len(m))
	for k,v := range m{
		str = str + k +" = ? or "
		args = append(args,v)
	}

	str = string([]rune(str)[:len(str)-4])

	return db.Where(str,args...)
}

func main() {
	db,err := gorm.Open("mysql","root:root@(0.0.0.0:3306)/pmm?charset=utf8&parseTime=True")

	if err != nil {
		log.Fatalln(err)
	}
	db.LogMode(true)

	user := User{}

	dbErr := AndOrs(query,map[string]interface{}{"mobile":"888888","email":"test@test.com"}).First(&user).Error

	if dbErr != nil{
		log.Fatal(dbErr)
	}
	log.Fatalln(user)

}
>

**Comment by evan-xie** [comment]
`package main

import (
_ "github.com/jinzhu/gorm/dialects/mysql"
"github.com/jinzhu/gorm"
"log"
)

type User struct {
Id string
Mobile string
Email string
Username string
Password string
Status int

}

func AndOrs(db *gorm.DB,m map[string]interface{}) (*gorm.DB) {
if m == nil {
return db
}
str := ""
args := make([]interface{},0,len(m))
for k,v := range m{
str = str + k +" = ? or "
args = append(args,v)
}

str = string([]rune(str)[:len(str)-4])

return db.Where(str,args...)
}

func main() {
db,err := gorm.Open("mysql","root:root@(0.0.0.0:3306)/pmm?charset=utf8&parseTime=True")

if err != nil {
	log.Fatalln(err)
}
db.LogMode(true)

user := User{}

dbErr := AndOrs(query,map[string]interface{}{"mobile":"888888","email":"test@test.com"}).First(&user).Error

if dbErr != nil{
	log.Fatal(dbErr)
}
log.Fatalln(user)
}`

**Comment by evan-xie** [comment]
other way :(

package main

import (
_ "github.com/jinzhu/gorm/dialects/mysql"
"github.com/jinzhu/gorm"
"log"
)

type User struct {
Id string
Mobile string
Email string
Username string
Password string
Status int

}

func AndOrs(db *gorm.DB,m map[string]interface{}) (*gorm.DB) {
if m == nil {
return db
}
str := ""
args := make([]interface{},0,len(m))
for k,v := range m{
str = str + k +" = ? or "
args = append(args,v)
}

str = string([]rune(str)[:len(str)-4])

return db.Where(str,args...)
}

func main() {
db,err := gorm.Open("mysql","root:root@(0.0.0.0:3306)/pmm?charset=utf8&parseTime=True")

if err != nil {
	log.Fatalln(err)
}
db.LogMode(true)

user := User{}

dbErr := AndOrs(query,map[string]interface{}{"mobile":"888888","email":"test@test.com"}).First(&user).Error

if dbErr != nil{
	log.Fatal(dbErr)
}
log.Fatalln(user)
}

**Comment by evan-xie** [comment]
`func AndOrs(query *gorm.DB, m map[string]interface{}) (*gorm.DB) {
	if m == nil {
		return query
	}

	str := ""
	args := make([]interface{},0,len(m))

	for k,v := range m {
		str = str + k + " = ? or "
		args = append(args,v)
	}

	str = string([]rune(str)[:len(str)-4])

	return query.Where(str,args...)
}`

**Comment by ermik** [comment]
Let's break it down:
* `select * from user` — this is default behavior when you use `.Find()`
* `order by id ASC LIMIT 1` — this is what `.First()` does, use it instead of `.Find`
* `where` — you can use `.Raw()` for complex behaviors; to use more of the ORM you should use `.Where()`
* `where status = 1 and locked = 0` —  do it like this:
```go
.Where("status = ?", statusInt).Where("locked = ?", lockedInt)
```
* ` and (mobile = '888888' or email = 'test@test.com' or username = 'test')` — can still use `.Where()`:
```go
.Where("mobile = ? or email = ? or username = ?", mobileNum, emailAddr, userName)
```

So in full, it should be something like:
```go
var u = User{}
err := db.Where("status = ?", statusInt)
         .Where("locked = ?", lockedInt)
         .Where(
             "mobile = ? or email = ? or username = ?",
             mobileNum,
             emailAddr,
             userName,
         )
         .First(&u)
         .Error
if err != nil {
     // handle db errors
}

// at this point "user" variable should have the found user or remain empty if nothing was found
```

**Comment by evan-xie** [comment]
```
func AndOrs(query *gorm.DB, m map[string]interface{}) (*gorm.DB) {
	if m == nil {
		return query
	}

	str := ""
	args := make([]interface{},0,len(m))

	for k,v := range m {
		str = str + k + " = ? or "
		args = append(args,v)
	}

	str = string([]rune(str)[:len(str)-4])

	return query.Where(str,args...)
}

	query := db.Where("status = ?",1)

	m := map[string]interface{}{
		"mobile":u.Mobile,
		"email":u.Email,
		"username":u.Username,
		"id":u.Id,
	}

	err := utils.AndOrs(query,m).First(&u).Error
```

**Comment by ermik** [comment]
That's really cool!

**Comment by matrixstylite** [comment]
the question i ask because i use a repository pattern base on gorm,  thanks all you guys

**Comment by zbird** [comment]
Seems there is no eligant  solution for    a and (b or c) query.

**Comment by mattdamon108** [comment]
@evan-xie This is awesome. It helps me a lot.
