### ISSUE TITLE
gorm.Expr("(reward * 100 + ? * 100)/100", num)  Precision Error

### ISSUE THREAD

**Issue by m3shine** [jinzhu/gorm#2009]
.Updates(map[string]interface{}{
		"reward": gorm.Expr("(reward * 100 + ? * 100)/100", num)
	})
————————————————————————————————————————
e.g:
reward = 4.52
num = 0.01

updates：
reward = 4.529999999999

**Comment by m3shine** [comment]
the number must 4.52 and 0.01

**Comment by ermik** [comment]
Did you set fixed-precision sql-type in your struct annotation?

**Comment by pedromorgan** [comment]
Am closing, if still a problem please re-open.
