### ISSUE TITLE
How to get id of inserted values

### ISSUE THREAD

**Issue by DuckerMan** [jinzhu/gorm#2010]
### What version of Go are you using (`go version`)?
go version go1.10.3 linux/amd64

### Which database and its version are you using?

Last version of  gorm and postgresql

### Please provide a complete runnable program to reproduce your issue. 

`
type AttachmentsNew struct {
	gorm.Model
	id int `gorm:"AUTO_INCREMENT"`
	ownerId int
	hashkey string `gorm:"size:64"`
	time int
	fileInfo string
	filepath string
	doctype string `gorm:"size:15"`
}

Database.Create(&AttachmentsNew{ownerId: ownerId, hashkey: "test", time:0, fileInfo:file.oldname, filepath:file.path, doctype:file.documentType})`

How i can get id of inserted value?

**Comment by m3shine** [comment]
row := new(Article)
d := Gorm.Create(article).Scan(&row)
if d.Error != nil {
	return 0, d.Error
}
return row.Id, nil

**Comment by DuckerMan** [comment]
undefined Gorm

**Comment by DuckerMan** [comment]
So, what is `article`?

**Comment by DuckerMan** [comment]
My ID is autoincrement.

Your code return ID - 0, buy ID is 6;

**Comment by gmolveau** [comment]
Gorm automatically inserts the ID into the struct.

```go
a := &AttachmentsNew{ownerId: ownerId, hashkey: "test", time:0, fileInfo:file.oldname, filepath:file.path, doctype:file.documentType}
Database.Create(a)
// a.id should be populated
```

**Comment by DuckerMan** [comment]
Populated means extended?

**Comment by gmolveau** [comment]
@DuckerMan yes it means "filled".

**Comment by DuckerMan** [comment]
So, why i should create variable that **point** to my structure?

**Comment by gmolveau** [comment]
so you can get use the ID after the creation. Otherwise I don't know any other method to achieve this.

**Comment by 77Sera** [comment]
i meet the same question, and i just can't get the id.
![image](https://user-images.githubusercontent.com/26327196/57838249-ef2ee980-77f6-11e9-93a2-e943637e4ea6.png)
how can i solve it ? i tried the code like the pic.
please, is there anyone can help me?
