### ISSUE TITLE
Using Elastic APM with GORM?

### ISSUE THREAD

**Issue by nallown** [jinzhu/gorm#2012]
I have to add APM (Application Monitoring) to my API and I found this great tool called [Elastic APM](https://www.elastic.co/solutions/apm) which is made by the people from ElasticSearch, they have great monitoring tools that give insight on the DB and API Queries but I need your guys help to find how I can use it with GORM.

In the docs they said I just need to import their mysql interface which is a wrapper around the normal mysql database and I can't figure out how to make GORM use that custom `db` instance instead of the default `github.com/go-sql-driver/mysql` one.

Do you have any idea how I can make GORM use the `db` instance from the **module/apmsq** example ([which you can find here](https://www.elastic.co/guide/en/apm/agent/go/current/instrumenting-source.html#_module_apmsql)) instead of the default mysql one?

### What version of Go are you using?
Latest

### Which database and its version are you using?
MariaDB/MySQL

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/elastic/apm-agent-go/module/apmsql/mysql"
)

func init() {
	wrappedDb, _ := apmsql.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm")
	gormDb,    _ := gorm.Open(wrappedDb) // TODO: I need something like this
}

```

**Comment by mykytanikitenko** [comment]
Try gorm.Open("mysql", wrappedDb) 

wrappedDb should implement SQLCommon interface
