### ISSUE TITLE
Callback loop forever!

### ISSUE THREAD

**Issue by qianguozheng** [jinzhu/gorm#2024]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
Go1.7.1

### Which database and its version are you using?
sqlite3

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

func Init() {
	var err error
	db, err = gorm.Open("sqlite3", "test.db")
	// db, err = gorm.Open("postgres", "user=gorm password=gorm DB.name=gorm port=9920 sslmode=disable")
	// db, err = gorm.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8&parseTime=True")
	// db, err = gorm.Open("mssql", "sqlserver://gorm:LoremIpsum86@localhost:9930?database=gorm")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
	db.AutoMigrate(&User{})
}
type User struct {
	Name string
	Sex string
}

//func (u *User) AfterUpdate(tx *gorm.DB) (err error) {
//	tx.Debug().Model(u).Update("name", "fix")
//	return
//}


func (u *User) AfterUpdate(scope *gorm.Scope) (err error) {
	scope.DB().Debug().Model(u).Update("name", "fix")
	return
}

func main() {
	Init()
	db.Model(&User{}).Update("name", "rich")
}
```
How to make it only execute one update!

**Comment by Kootain** [comment]
try DB.UpdateColumns, update attributes without callbacks, or Scope.SkipLeft, skip remaining callbacks
```go
func (u *User) AfterUpdate(scope *gorm.Scope) (err error) {
	scope.DB().Debug().Model(u).UpdateColumns("name", "fix")
	return
}
```

**Comment by jinzhu** [comment]
btw, you can change name with `SetColumn("Name", "fix")` in `BeforeUpdate`
