### ISSUE TITLE
no valid transaction

### ISSUE THREAD

**Issue by sh7ning** [jinzhu/gorm#2029]
### What version of Go are you using (`go version`)?
go version go1.10.3 darwin/amd64

### Which database and its version are you using?
mysql

```
var db *gorm.DB

db.DB().SetConnMaxLifetime(time.Duration(120) * time.Second)
db.DB().SetMaxIdleConns(1)
db.DB().SetMaxOpenConns(1)
```

First http request:
```
//without db.Begin() or uncommitted transaction
db.Commit()
```

then other http request use db.Create always : `no valid transaction`.

**Comment by pedromorgan** [comment]
Please provide more detail and re-open issue
