### ISSUE TITLE
sometimes create table type is not right using mysql(should be text not vchar)

### ISSUE THREAD

**Issue by BaSO4** [jinzhu/gorm#2030]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.9.2 linux/amd64

### Which database and its version are you using?
mysql:5.7

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
type BlockInfo struct {
	BlockHight  uint64 `gorm:"type:bigint;primary_key"`
	ChannelID   string `gorm:"type:varchar(128);primary_key"`
	CurrentHash string
	Trans       string `gorm:"type:text"`
}
       connUrl = "root:zaq1xsw@@tcp(10.0.0.10:33002)/mybaas?charset=utf8&parseTime=true&loc=Local"
	db, err := gorm.Open(dbConf.Driver, connUrl)
	db.AutoMigrate(&BlockInfo{})
```
the BlockInfo.Trans item should be created text type in mysql, but sometimes the type is varchar

**Comment by pedromorgan** [comment]
Can you provide more detail, and re-open this bug. The `sometimes` above is intriguing...
