### ISSUE TITLE
Best way to handle Time in sqlLite

### ISSUE THREAD

**Issue by mccalv** [jinzhu/gorm#2032]
Hello, I have receiving this error when trying to bind the query to the gorm.Model
 sql: Scan error on column index 4: unsupported Scan, storing driver.Value type []uint8 into type *time.Time 

I am using sqlite3, and what is the best option in order to Scan and bind Time correctly for this dialect: using int/text in the table definition and callback in gorm?

**Comment by pedromorgan** [comment]
hi @mccalv - Please check

- https://github.com/go-sql-driver/mysql#timetime-support
- https://stackoverflow.com/questions/29341590/go-parse-time-from-database/29343013#29343013

If you still have problems then re-ppen this issue

**Comment by mccalv** [comment]
Thanks for you answer, but still this not solve the problem, both the answers are related to Mysql and not to SqlIte which I am currently using
