### ISSUE TITLE
repeat use a variable query issues

### ISSUE THREAD

**Issue by UpdateSelf** [jinzhu/gorm#2034]
var temp = table_struct{}
if db.where("id = ?","1").first(&temp).RowsAffected >0{
  log("find")
}else{
log("not find")
}

if db.where("id = ?","2").first(&temp).RowsAffected >0{
  log("find")
}else{
log("not find")
}

database have there two record, but result is:
find
not find

if the second use ("id = ?","1") will print:
find
find

**Comment by pedromorgan** [comment]
Looks like you have two dupe id's.. Are you sure `id` is a primary_key ?
