### ISSUE TITLE
Can Gorm be used with google data store

### ISSUE THREAD

**Issue by sachin-puranik** [jinzhu/gorm#2037]
Is it possible to port GORM on Google App Engine DataStore...
Please help

**Comment by pedromorgan** [comment]
Please read the dialects section in the docs

- http://gorm.io/docs/dialects.html

**Comment by sachin-puranik** [comment]
yes I have seen that. But as I understand , along with dialects interface , gorm also depends on core SQL Interface , ex Exec/Raw etc. But in case of google datastore , it needs internal details of the query ....for example Filters to be applied on Entity. it's not one liner question. How will that work? Please suggest.
