### ISSUE TITLE
where the `sum` ?

### ISSUE THREAD

**Issue by dongshimou** [jinzhu/gorm#2044]
i mean the sql function `sum`. 
like `select sum(click) form ad_stat where ad_id= 1`

> i have a table named `ad_stat`.
table structure :

ad_id|date|click
---|---|---
1|2010-01-01|100
1|2010-01-02|101

how can i do this only use gorm function?
or gorm should add this function like
`db.Model(&stat{}).Sum("click").Where(&stat{AdId:1})`

**Comment by pedromorgan** [comment]
@dongshimou look at  `Count()` in the manual - http://gorm.io/docs/query.html#Count

**Comment by pedromorgan** [comment]
OOps think u need the "group"..
http://gorm.io/docs/query.html#Group-amp-Having

**Comment by luaxlou** [comment]
You can do like this:
type NResult {
    N int64 //or int ,or some else
}

func SumSame() int64 {
    var n  NResult
    db.Table("table").Select("sum(click) as n").Scan(&n)
    return n.N
}

**Comment by chenyu1990** [comment]
> @dongshimou look at `Count()` in the manual - http://gorm.io/docs/query.html#Count

Do you know the difference between SUM and COUNT?
