### ISSUE TITLE
add options for naming table name and column name

### ISSUE THREAD

**Issue by Ray0427** [jinzhu/gorm#2061]
The default naming style in gorm is snake case.
Although we can override table name with `gorm.DefaultTableNameHandler` ,
could we add an option for gorm at initialize
to setting table name and column name "snake case" , "camel case" or "upper camel case"

**Comment by limoli** [comment]
+1

**Comment by viettuan1807** [comment]
Any updates on this?

**Comment by ademozay** [comment]
Fixed with #2040
