### ISSUE TITLE
if i use gorm to delete some items, what should i do to return the deleted items' id or other key?

### ISSUE THREAD

**Issue by yjiang724** [jinzhu/gorm#2062]
if i use gorm to delete some items, what should i do to return the deleted items' id or other key?

```go
gorm.Where(where, lineIds).Delete(&Stops{})
```

**Comment by pedromorgan** [comment]
- Databases don't normally return the ID's of a DELETE command
- You have the `lineIDs` already

**Comment by yjiang724** [comment]
I used other ids (not LineIDs) to delete, i can not get LineIDs in this way. However if i use `select` to get LineIDs before `delete`, which will increase duration.
