### ISSUE TITLE
WHERE 位运算怎么写？

### ISSUE THREAD

**Issue by jijunzeng** [jinzhu/gorm#2070]
err := db.Debug().Where("? & 'group'", 3).Find(&games).Error

控制台看转化成SQL如下：
SELECT * FROM `game`  WHERE ('3' & 'group')

1. 为什么代入的int会自动转string，怎样让它不转换？
2. 位运算的gorm该怎样写？

谢谢！

**Comment by seaguest** [comment]
你自己把group带了引号，就会被认为是string了。

**Comment by jijunzeng** [comment]
@seaguest 多谢，不带引号也不对，改成(``)反引号，成功了。
