### ISSUE TITLE
请问如何优雅的实现分表？

### ISSUE THREAD

**Issue by seaguest** [jinzhu/gorm#2073]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
1.9

### Which database and its version are you using?

mysql
### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml)
```
因为业务需求，我需要对某个表进行拆分，譬如每个国家的用户我希望放在单独表里。
每一个请求里，我知道用户是哪个国家的，该查哪张表，基本上都是操作单张表，不需要合表查询。

在gorm怎么做能比较优雅的实现这个基本的那分表功能呢？
如果在db查询时指定table名称，后面的操作无论是对select还是create都会有效吗？

```

**Comment by xunwumizhi** [comment]
有时候指定Table()，并不生效，依旧写到struct同名那个表
