### ISSUE TITLE
RecordNotFound does not work for Raw SQL

### ISSUE THREAD

**Issue by gnomeby** [jinzhu/gorm#2112]
### What version of Go are you using (`go version`)?
master

### Which database and its version are you using?
PostgreSQL 10

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

func init() {
	var err error
	db, err = gorm.Open("sqlite3", "test.db")
	// db, err = gorm.Open("postgres", "user=gorm password=gorm DB.name=gorm port=9920 sslmode=disable")
	// db, err = gorm.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8&parseTime=True")
	// db, err = gorm.Open("mssql", "sqlserver://gorm:LoremIpsum86@localhost:9930?database=gorm")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

func main() {
	init()
	if db.Raw("SELECT 1 AS one WHERE FALSE").RecordNotFound() {
		fmt.Println("success")
	} else {
		fmt.Println("failed")
	}
}
```

**Comment by gnomeby** [comment]
Solution https://github.com/jinzhu/gorm/pull/2111

**Comment by jinzhu** [comment]
db.Raw("SELECT 1 AS one WHERE FALSE").RowsAffected == 0

**Comment by gnomeby** [comment]
You ignore main problem: RecordNotFound is still available for developers suggestions in drop down list in IDE and it can be selected and works incorrectly for Raw SQL.
