### ISSUE TITLE
Wrong documentation for Has One Association

### ISSUE THREAD

**Issue by riwogo** [jinzhu/gorm#2130]
In documentation for has one association  [here](http://gorm.io/docs/has_one.html) is wrote:

``` go
// User has one CreditCard, CreditCardID is the foreign key
type User struct {
  gorm.Model
  CreditCard   CreditCard
  CreditCardID uint
}

type CreditCard struct {
  gorm.Model
  Number   string
}
```
but must be:
``` go
// User has one CreditCard, CreditCardID is the foreign key
type User struct {
  gorm.Model
  CreditCard   CreditCard
}

type CreditCard struct {
  gorm.Model
  Number   string
  UserID   uint
}
```

If it's a **Has one** relationship then CreditCard must have a foreign key to UserID but in documentation User has a foreign key to CreditCardID which in this case makes a **Belong to** relationship which is wrong.

**Comment by rubiagatra** [comment]
I also found wrong documentation in many2many, where I can contribute to fixing it?

**Comment by emirb** [comment]
Fixed in https://github.com/jinzhu/gorm.io/pull/119
