### ISSUE TITLE
[Question Or Feature request] gorm has CreateOrFirst ?

### ISSUE THREAD

**Issue by Bo0km4n** [jinzhu/gorm#2132]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?

1.10

### Which database and its version are you using?

MySQL 5.7

### Example code
Does gorm have `CreateOrFirst` method such as ?:

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

type Person struct {
  ID int
  Name string
}

func main() {
  p := &Person{
    Name: "Hoge",
  }
  if err := db.CreateOrFirst(p).Error; err != nil {
    panic(err) 
  }
}
```

At first, run query which `select * from person where name = ?...`. Next, if not exist person,
run query which `insert into person ...`

I think it would be useful if these methods are standard in the gorm

**Comment by mwm5945** [comment]
http://gorm.io/docs/query.html#FirstOrCreate

**Comment by penguinpowernz** [comment]
Closing as per docs.
