### ISSUE TITLE
How to find out if a column is dirty or not in BeforeSave func

### ISSUE THREAD

**Issue by lvqingan** [jinzhu/gorm#2147]
Suppose we have an `Article` model with `content` and `abstract` columns. We wrote some logic to extract `abstract` from `content` in `BeforeSave`. It works fine.

Now, we have another `vote_count` column for `Article` model. Every time a user click the vote button, the `vote_count` will be increased.

The problem comes: users click the vote button, even they didn't change the `content` but the code doesn't know about that, and it will extract `content` to `abstract` again. 

So, is there any solution to let me find out if certain column is "dirty"?

**Comment by nhh** [comment]
Hi @lvqingan,

did you solved your problem?

I am currently facing a similar one...

Cheers,
Niklas

**Comment by lvqingan** [comment]
@nhh not yet

**Comment by jinzhu** [comment]
UpdateColumn with Select?
