### ISSUE TITLE
大量的Where条件，每次都调用db.clone，可以减少clone的调用吗？

### ISSUE THREAD

**Issue by kyl2016** [jinzhu/gorm#2149]
如题，项目中有很多where条件：like，=，>，<......，用Query Chains实现的，每次都会调用db.clone，可以优化吗？

优化思路：
1. 暴露DB.search的whereConditions? 
2. 允许使用map作为Where的参数，但map的key和value不一定是相等的关系。

感谢大家！

**Comment by liunian1004** [comment]
mark.
db.clone()
search.clone()

我的理解是每次增加一个条件都是一个新的状态，你可以在一个 Where 中增加多个条件。

**Comment by kyl2016** [comment]
> mark.
> db.clone()
> search.clone()
> 
> 我的理解是每次增加一个条件都是一个新的状态，你可以在一个 Where 中增加多个条件。

谢谢！在一个 Where 中增加多个条件可行。
