### ISSUE TITLE
SingularTable - DATA RACE

### ISSUE THREAD

**Issue by EmpireJones** [jinzhu/gorm#2151]
### What version of Go are you using (`go version`)?
1.10.4

### Which database and its version are you using?
sqlite3

Calling SingularTable(...) function on two databases causes a data race (each call is setting the package-level variable modelStructsMap)

https://github.com/jinzhu/gorm/blob/master/main.go#L165

**Comment by emirb** [comment]
Fixed in #2396 and released in [v1.9.4](https://github.com/jinzhu/gorm/releases/tag/v1.9.4).
