### ISSUE TITLE
事务提交有延迟？

### ISSUE THREAD

**Issue by godsoul** [jinzhu/gorm#2168]
我在调用Commit之后，同一秒执行select还是没查询到commit提交的插入数据的事务，要过一下下，这个是不是异步操作的？

**Comment by slivewo** [comment]
你好，我也碰到了这个问题，能告诉我这个问题怎么解决的呢？

**Comment by w1ndyz** [comment]
这个最后是怎么解决的？

**Comment by oz-world** [comment]
> 我在调用Commit之后，同一秒执行select还是没查询到commit提交的插入数据的事务，要过一下下，这个是不是异步操作的？

大佬 这个是怎么解决的 我也遇到这个问题

**Comment by leo-0104** [comment]
> 

请问最后怎么解决呢？我的也遇到这个问题，同一秒执行select还是读的主库，怀疑是异步提交事务导致的
