### ISSUE TITLE
Find does not work with Struct

### ISSUE THREAD

**Issue by smithaitufe** [jinzhu/gorm#2173]
### What version of Go are you using (`go version`)? 
1.10.3

### Which database and its version are you using?
"PostgreSQL 10.5 (Ubuntu 10.5-2.pgdg18.04+1) on x86

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
)

var db *gorm.DB
type Department struct {
gorm.Model
Name string
IsAcademic bool
}

func init() {
	var err error

	db, err = gorm.Open("postgres", "user=gorm password=gorm DB.name=gorm port=9920 sslmode=disable")
	if err != nil {
		panic(err)
	}
db.AutoMigrate(&Department{})
	db.LogMode(true)
}

func main() {
db.Create(&Department{Name: "Elect/Elect", IsAcademic: true})
db.Create(&Department{Name: "Rectory", IsAcademic: false})
departments := []*Department{}
	if err := db.Where(Department{
		IsAcademic: false,
	}).Find(&departments).Error; err != nil {
		fmt.Println("failed")
	}
if len(departments) == 0 {
		fmt.Println("failed")
}
		fmt.Println("success")
}
```
### Expected Output
`SELECT * FROM departments WHERE deleted_at IS NULL AND is_academic = false`

### Actual Output
`SELECT * FROM departments WHERE deleted_at IS NULL`

# What am I doing wrong?

Gorm is a great project.
What I don't understand is why is GORM very restrictive in terms of query building?

**Comment by quangbuule** [comment]
`IsAcademic: false` will lead to zero-value and gorm will ignore that when querying the database, please read the docs carefully, in your case, i suggest using `map[string]interface{}`.
```db.Where(hash[string]interface{} { "IsAcademic": false })```

**Comment by smithaitufe** [comment]
@quangbuule Thanks for response. I have read the doc and saw the statement you made.

My question is why can the library work without using `map[string]interface{}`?

Anyway, I have moved on with the reality that I have do it the gorm's way.

Thanks

**Comment by quangbuule** [comment]
In Golang, zero-value is the default value when you init an object of the struct:
```dep := Department{} => dep.IsAcademic == false```

So `Department{}` and `Department{ IsAcademic: false }` have no difference, and gorm couldn't detect the difference. It would see your query as `Department{}` which caused your problem.

Check out section "Struct and Map" in here http://gorm.io/docs/query.html#Where - they explain and give you alternative solution there.
