### ISSUE TITLE
func Find didn't do the join table

### ISSUE THREAD

**Issue by Paladz** [jinzhu/gorm#2180]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
1.1

### Which database and its version are you using?
Mysql 5.7

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

This is my struct
```go
type Wallet struct {
	ID     string
}

type Address struct {
	ID       uint64
	WalletID string
}

type Utxo struct {
	ID        uint64
	AddressID uint64
	WalletID  string
	RawData   string

	Address Address `gorm:"foreignkey:AddressID"`
	Wallet  Wallet  `gorm:"foreignkey:WalletID"`
}
```

I wanna query all the utxos with wallet and address info in one "mysql query" like:
```mysql
select * from utxo, address, wallet where utxo.address_id = address.id and utxo.wallet_id = wallet.id.
```

I found I can only do it with preload, which means it will have three "mysql query" 
```go
spendUtxos := []*orm.Utxo{}
db.Preload("Wallet").Preload("Address").Find(&spendUtxos)
```
```mysql
1. select * from utxo;
2. select * from address where id in (?);
3. select * from wallet where id in (?);
```
Is there any way to improve it?

**Comment by shr3k3** [comment]
And a similar question. If the number of entries in utxo table > 1000 when using sqlite we get an error "too many SQL variables", while there may be few entries in the address and wallet tables. How to optimize such queries? How can I manually preload address by "select * from address"?

**Comment by vertazzar** [comment]
that is expected behaviour, preload works with IN - it never uses joins

read this http://gorm.io/docs/preload.html

**Comment by penguinpowernz** [comment]
Closing as per documentation.

**Comment by sgon00** [comment]
Refer to #1436
