### ISSUE TITLE
Preload with select don't work normal, how can scan many to many query

### ISSUE THREAD

**Issue by sun-wenming** [jinzhu/gorm#2181]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.11.2 windows/amd64

### Which database and its version are you using?
mysql    version : 5.7

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

### First error:
 
I want to query the special field information, do not show it all. 

#1965  Through parent_id, they are set to null.It looks too bloated

```go
err := db.Preload("Tags", func(db *gorm.DB) *gorm.DB {
		return db.Select("l_tag.id, l_article_tags.article_id")
	}).Where(maps).Find(&articles).Error
```
![image](https://user-images.githubusercontent.com/22268505/48554434-5c7dc280-e919-11e8-9728-f9c5124108a7.png)

### Expect

In many to many queries.
Retrievable data can be retrieved according to the fields you retrieve.

Thanks.

**Comment by IsSwm** [comment]
```go
err := db.Preload("Tags", func(db *gorm.DB) *gorm.DB {
		return db.Select("*")
	}).Where(maps).Find(&articles).Error
````
Plus, it's the only way to write all the data to display normally, but it's too bulky. I hope you can help me tell me how to retrieve custom fields.
![image](https://user-images.githubusercontent.com/22268505/48554434-5c7dc280-e919-11e8-9728-f9c5124108a7.png)

**Comment by sun-wenming** [comment]
fix by `omitempty `
