### ISSUE TITLE
Problem with mysql primary keys

### ISSUE THREAD

**Issue by apwiede** [jinzhu/gorm#2183]
Save with multiple primary keys with mysql

Go version go1.10.4 linux/amd64

DB mysql 5.7.20

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	"fmt"
    )

var db *gorm.DB

func init() {
	var err error
	db, err = gorm.Open("mysql", "gorm:gorm@tcp(localhost:3306)/gorm?charset=utf8&parseTime=True")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

type Tag {
    Branch uint64 `gorm:"primary_key"`
    Identifier uint64 `gorm:"primary_key"`
}

func main() {
	if err := db.CreateTable(&Tag{}).Error; err != nil {
		fmt.Println("failed")
	} else {
		fmt.Println("success")
	}
}
```
Error 1075: Incorrect table definition; there can be only one auto column and it must be defined as a key

I think in dialect_mysql.go function DataTypeOf there should be a check if there is more than one integer type primary key field and then AUTOINCRMENT should not be used in switch dataValue.Kind()

**Comment by Scott-Chen** [comment]
@apwiede 
You have to set gorm:"primary_key;auto_increment:false" to mark a column not auto increment.

```
type Tag {
    Branch uint64 `gorm:"primary_key;auto_increment:false"`
    Identifier uint64 `gorm:"primary_key;auto_increment:false"`
}
```

**Comment by penguinpowernz** [comment]
@apwiede did this fix your problem?

**Comment by apwiede** [comment]
Yes, thanks it did.

Best Regards,

Arnulf

Am 13.02.2019 um 08:31 schrieb Robert McLeod:
