### ISSUE TITLE
auto increment doesn't work

### ISSUE THREAD

**Issue by onecaffeine** [jinzhu/gorm#2190]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go1.11.1

### Which database and its version are you using?
mysql 8.0.13

```go
package main

import (
	"fmt"
)

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

type TParkRecord struct {
	ID       uint `gorm:"type:bigint(20) unsigned;not null;auto_increment;primary_key"`
	ParkCode int  `gorm:"type:bigint(10) unsigned;not null;default:'0'"`
}

func (t TParkRecord) TableName() string {
	return "t_park_record"
}

func main() {
	db, err := gorm.Open("mysql", "user:password@/dbname?charset=utf8&parseTime=True&loc=Local")
	if err != nil {
		fmt.Println(err)
	}
	defer db.Close()

	db.LogMode(true)

	db.Set("gorm:table_options", "ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE = utf8_bin").AutoMigrate(&TParkRecord{})
}

```

when i run this code,i found auto increment doesn't work.

![image](https://user-images.githubusercontent.com/26565257/48939919-cff28600-ef50-11e8-98e2-191322582c59.png)

**Comment by onecaffeine** [comment]
@jinzhu
please tell me what should i do?thx

**Comment by baocaixiong** [comment]
@onecaffeine 
请像这样定义字段
```go
ID uint64 `gorm:"type:bigint(20) unsigned auto_increment;not null;primary_key"`
```
`auto_increment`指令在建表时是个对某一字段单独的指令，所以需要放在`type`后

**Comment by dengguojie** [comment]
@baocaixiong 
it works!!
why AUTO_INCREMENT is special for bigint ??

**Comment by inliquid** [comment]
Seems this comment clarifies:
https://github.com/jinzhu/gorm/issues/201#issuecomment-52582868

**Comment by dengguojie** [comment]
@inliquid Thanks. I go it.

**Comment by onecaffeine** [comment]
@baocaixiong thx,it works!!

**Comment by david-castaneda** [comment]
For anyone else having issues, setting the type to serial worked for me.
```go
type User struct {
      ID int `gorm:"type: serial;"`
}
````
This sets the column default to the next sequential value:
"nextval('users_account_number_seq'::regclass)"

**Comment by eajardini** [comment]
> For anyone else having issues, setting the type to serial worked for me.
> 
> ```go
> type User struct {
>       ID int `gorm:"type: serial;"`
> }
> ```
> 
> This sets the column default to the next sequential value:
> "nextval('users_account_number_seq'::regclass)"

Works for me too!
