### ISSUE TITLE
请问查询多条记录，怎么关联其他表？

### ISSUE THREAD

**Issue by maiguangyang** [jinzhu/gorm#2193]
// 用户有多张信用卡，UserID 是外键
type User struct {
    gorm.Model
    CreditCards []CreditCard
}

type CreditCard struct {
    gorm.Model
    Number   string
    UserID  uint
}

// 查询多条记录
list := make([]User, 0)
db.Model(&list).Find(&list).Related(&list)

结果为：invalid association []
请问查询多条记录，怎么关联其他表？

**Comment by Scott-Chen** [comment]
```
var list []User
db.Preload("CreditCards").Find(&list)
```

**Comment by DrowningMan** [comment]
> ```
> var list []User
> db.Preload("CreditCards").Find(&list)
> ```

use preload can't select field
