### ISSUE TITLE
Using Having on .Count() function

### ISSUE THREAD

**Issue by agungwk** [jinzhu/gorm#2194]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go1.10.1 windows/amd64

### Which database and its version are you using?
10.1.34-MariaDB

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"fmt"
	"time"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

var db *gorm.DB

func init() {
	var err error
	db, err = gorm.Open("mysql", "user:pass@tcp(localhost:3306)/dbName?charset=utf8mb4&parseTime=True&loc=Local")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

type Package struct {
	ID             int                 `gorm:"primary_key" json:"-"`
	Serial         string              `json:"serial"`
	Name           string              `json:"name" binding:"required"`
	Description    string              `json:"description"`
	TagID          []int               `json:"tagID,omitempty" gorm:"-"`
	Tags           []Tag               `json:"tags,omitempty" gorm:"-"`
}

type Tag struct {
	ID        int       `gorm:"primary_key" json:"id"`
	Name      string    `json:"name" binding:"required"`
}

func main() {
        db.Model(Package{}).Joins("JOIN package_tag pt ON pt.package_serial = serial").
			Joins("JOIN tag t ON t.id = pt.tag_id").
			Where("t.name IN (?)", strings.Split(query.TagNames, ",")).
			Having(fmt.Sprintf("COUNT(package.id)=%d", len(strings.Split(query.TagNames, ",")))).
			Group("package.serial")
        var total int
        db.Count(&total) // this cause SQL Error

	if total > 0 {
		db.Offset(offset).Limit(query.PageSize).Find(&packages) // this line works well
	}
}
```
![capture](https://user-images.githubusercontent.com/4101717/49063506-31b13980-f24a-11e8-8c2d-e1b8c3bc21b6.PNG)

The generated query from Gorm is 

> SELECT count(*) FROM ( SELECT count(*) as name  FROM `package` JOIN package_tag pt ON pt.package_serial = serial JOIN tag t ON t.id = pt.tag_id WHERE (t.name IN ('xxx','yyy')) GROUP BY package.serial ) AS count_table HAVING (COUNT(package.id)=2)

 which raise SQL Error `Error 1054: Unknown column 'package.id' in 'having clause' `.
Correct SQL statement is 

> SELECT count(*) FROM ( SELECT count(*) as name  FROM package JOIN package_tag pt ON pt.package_serial = serial JOIN tag t ON t.id = pt.tag_id WHERE (t.name IN ('xxx','yyy')) GROUP BY package.serial HAVING (COUNT(package.id)=2)) AS count_table 

Please notice the `HAVING (COUNT(package.id)=2)` position.

What should I do to achieve correct SQL statement?

**Comment by jacobtylerdavis** [comment]
I had this exact issue too.  The [patch which is referenced](https://github.com/jinzhu/gorm/pull/2324) solved this but introduced another issue which caused count queries with `Having()` to be malformed when being passed to `db.Model(...).Count()`.  

In case anyone is having still having trouble with this, an easy but not-so-elegant solution is to append your `HAVING` statement to the `Group()` func and avoid `Having()` altogether.

Broken (errors, even after referenced patch):
```golang
...Group(`users.id`).Having(`COUNT(...) > 1234`)
```
Working (albeit, less elegant)
```golang
...Group(`users.id HAVING COUNT(...) > 1234`)
```
