### ISSUE TITLE
gorm怎么创建json字段的数据？

### ISSUE THREAD

**Issue by zwl1619** [jinzhu/gorm#2195]
gorm怎么创建json字段的数据？

官方文档有个创建一条记录的示例： http://gorm.io/zh_CN/docs/index.html
```
// 创建
  db.Create(&Product{Code: "L1212", Price: 1000})
```

**问题：**
如果这个Product模型有个规格(Spec)字段，这个字段是json格式的，有三项内容：
```
{
"length":"20cm",
"width":"30cm",
"weight":"40g"
}
```
这个创建语句应该怎么写？下面这样写IDE会报错：
```
// 创建
  db.Create(&Product{Code: "L1212", Price: 1000,Spec:{"length":"20cm","width":"30cm","weight":"40g"}})
```

**Comment by baocaixiong** [comment]
可以使用`Scanner`接口和`Valuer`接口来实现。下面假设我们要存储的是一个map[string]string类型的json数据，可以这么实现接口：
```go
type StringMap struct {
	Src   map[string]string
	Valid bool
}

func NewEmptyStringMap() *StringMap {
	return &StringMap{
		Src:   make(map[string]string),
		Valid: true,
	}
}

func NewStringMap(src map[string]string) *StringMap {
	return &StringMap{
		Src:   src,
		Valid: true,
	}
}

func (ls *StringMap) Scan(value interface{}) error {
	if value == nil {
		ls.Src, ls.Valid = make(map[string]string), false
		return nil
	}
	t := make(map[string]string)
	if e := json.Unmarshal(value.([]byte), &t); e != nil {
		return e
	}
	ls.Valid = true
	ls.Src = t
	return nil
}

func (ls *StringMap) Value() (driver.Value, error) {
	if ls == nil {
		return nil, nil
	}
	if !ls.Valid {
		return nil, nil
	}

	b, e := json.Marshal(ls.Src)
	return b, e
}
```
然后像这样定义你的模型
```go
type User struct {
    Info *StringMap `gorm:"type:json"`
}

u := &User{
     Info: NewEmptyStringMap(), // 这样会初始化map，即使不设置任何值，保存后在db中的值为`{}`
}
u.Info.Src["nihao"] = "123"
```

**Comment by zwl1619** [comment]
@baocaixiong 好复杂的样子，看到另一个答案说可以这样：
```
type Product struct {
    Thumbnails    json.RawMessage `gorm:"default:'[]'"`
}
```
行吗？

**Comment by baocaixiong** [comment]
也可以
你说的这个`json.RawMessage`实际就是`byte[]`的别名，数据取出来后需要手动再次Unmarshal

**Comment by zwl1619** [comment]
感谢大佬!

**Comment by zwl1619** [comment]
@baocaixiong 

`gorm:"default:'[]'"`里面的`[]`加了单引号，这里单引号里面可以有多个字符吗？

**Comment by imageslr** [comment]
实现方法是为该子段的类型实现 Scanner 和 Valuer 接口。这类似于 Eloquent 中的 `cast`。

比如某个字段在数据库中是 varchar，但是其格式是 JSON，那么可以在从数据库中取出的时候，自动解析为对应的结构体。比如我们有一个 User 模型：
```go
// User 用户模型
type User struct {
	models.BaseModel
	Nickname  string     `json:"nickname" gorm:"type:varchar(255);not null"`
	Name      string     `json:"name" gorm:"type:varchar(255);not null"`
	Phone     string     `json:"phone" gorm:"type:varchar(255);unique;default:NULL" sql:"index"`
	IDCardImg *IDCardImg `json:"id_card_img" gorm:"type:varchar(255)"`
}
```

`IDCardImg` 类型定义如下：
```go
// IDCardImg 身份证照片 url
type IDCardImg struct {
	Front string `json:"front"`
	Back  string `json:"back"`
}
```

我们希望在从数据库中取出记录的时候，自动填充 IDCardImg 的字段；在保存数据的时候，自动将 IDCardImg 字段序列化为字符串。只需要**为该结构体实现 Scanner 和 Valuer 接口。**
```go
// Scan 实现 gorm Scanner 接口
func (ls *IDCardImg) Scan(value interface{}) error {
	if value == nil {
		*ls = IDCardImg{}
		return nil
	}
	t := IDCardImg{}
	if e := json.Unmarshal(value.([]byte), &t); e != nil {
		return e
	}
	*ls = t
	return nil
}

// Value 实现 gorm Valuer 接口
func (ls *IDCardImg) Value() (driver.Value, error) {
	if ls == nil {
		return nil, nil
	}
	b, e := json.Marshal(*ls)
	return b, e
}
```

因此可以将模型中的字段设置为任意类型，不管数据库中实际是什么格式。只要为模型中的该字段类型实现 Scanner 和 Valuer 这两个接口，就可以在从数据库中读取的时候自动解析格式、在保存的时候自动编码。

**Comment by Septemberd** [comment]
> 可以使用`Scanner`接口和`Valuer`接口来实现。下面假设我们要存储的是一个map[string]string类型的json数据，可以这么实现接口：
> 
> ```go
> type StringMap struct {
> 	Src   map[string]string
> 	Valid bool
> }
> 
> func NewEmptyStringMap() *StringMap {
> 	return &StringMap{
> 		Src:   make(map[string]string),
> 		Valid: true,
> 	}
> }
> 
> func NewStringMap(src map[string]string) *StringMap {
> 	return &StringMap{
> 		Src:   src,
> 		Valid: true,
> 	}
> }
> 
> func (ls *StringMap) Scan(value interface{}) error {
> 	if value == nil {
> 		ls.Src, ls.Valid = make(map[string]string), false
> 		return nil
> 	}
> 	t := make(map[string]string)
> 	if e := json.Unmarshal(value.([]byte), &t); e != nil {
> 		return e
> 	}
> 	ls.Valid = true
> 	ls.Src = t
> 	return nil
> }
> 
> func (ls *StringMap) Value() (driver.Value, error) {
> 	if ls == nil {
> 		return nil, nil
> 	}
> 	if !ls.Valid {
> 		return nil, nil
> 	}
> 
> 	b, e := json.Marshal(ls.Src)
> 	return b, e
> }
> ```
> 
> 然后像这样定义你的模型
> 
> ```go
> type User struct {
>     Info *StringMap `gorm:"type:json"`
> }
> 
> u := &User{
>      Info: NewEmptyStringMap(), // 这样会初始化map，即使不设置任何值，保存后在db中的值为`{}`
> }
> u.Info.Src["nihao"] = "123"
> ```

这种方式可以读写整个json字段，不知道能否实现json里面的部分属性更新？

**Comment by Septemberd** [comment]
> 可以使用`Scanner`接口和`Valuer`接口来实现。下面假设我们要存储的是一个map[string]string类型的json数据，可以这么实现接口：
> 
> ```go
> type StringMap struct {
> 	Src   map[string]string
> 	Valid bool
> }
> 
> func NewEmptyStringMap() *StringMap {
> 	return &StringMap{
> 		Src:   make(map[string]string),
> 		Valid: true,
> 	}
> }
> 
> func NewStringMap(src map[string]string) *StringMap {
> 	return &StringMap{
> 		Src:   src,
> 		Valid: true,
> 	}
> }
> 
> func (ls *StringMap) Scan(value interface{}) error {
> 	if value == nil {
> 		ls.Src, ls.Valid = make(map[string]string), false
> 		return nil
> 	}
> 	t := make(map[string]string)
> 	if e := json.Unmarshal(value.([]byte), &t); e != nil {
> 		return e
> 	}
> 	ls.Valid = true
> 	ls.Src = t
> 	return nil
> }
> 
> func (ls *StringMap) Value() (driver.Value, error) {
> 	if ls == nil {
> 		return nil, nil
> 	}
> 	if !ls.Valid {
> 		return nil, nil
> 	}
> 
> 	b, e := json.Marshal(ls.Src)
> 	return b, e
> }
> ```
> 
> 然后像这样定义你的模型
> 
> ```go
> type User struct {
>     Info *StringMap `gorm:"type:json"`
> }
> 
> u := &User{
>      Info: NewEmptyStringMap(), // 这样会初始化map，即使不设置任何值，保存后在db中的值为`{}`
> }
> u.Info.Src["nihao"] = "123"
> ```

@baocaixiong  这种方式可以读写整个json字段，不知道能否实现json里面的部分属性更新？

**Comment by baocaixiong** [comment]
> > 可以使用`Scanner`接口和`Valuer`接口来实现。下面假设我们要存储的是一个map[string]string类型的json数据，可以这么实现接口：
> > ```go
> > type StringMap struct {
> > 	Src   map[string]string
> > 	Valid bool
> > }
> > 
> > func NewEmptyStringMap() *StringMap {
> > 	return &StringMap{
> > 		Src:   make(map[string]string),
> > 		Valid: true,
> > 	}
> > }
> > 
> > func NewStringMap(src map[string]string) *StringMap {
> > 	return &StringMap{
> > 		Src:   src,
> > 		Valid: true,
> > 	}
> > }
> > 
> > func (ls *StringMap) Scan(value interface{}) error {
> > 	if value == nil {
> > 		ls.Src, ls.Valid = make(map[string]string), false
> > 		return nil
> > 	}
> > 	t := make(map[string]string)
> > 	if e := json.Unmarshal(value.([]byte), &t); e != nil {
> > 		return e
> > 	}
> > 	ls.Valid = true
> > 	ls.Src = t
> > 	return nil
> > }
> > 
> > func (ls *StringMap) Value() (driver.Value, error) {
> > 	if ls == nil {
> > 		return nil, nil
> > 	}
> > 	if !ls.Valid {
> > 		return nil, nil
> > 	}
> > 
> > 	b, e := json.Marshal(ls.Src)
> > 	return b, e
> > }
> > ```
> > 
> > 
> > 然后像这样定义你的模型
> > ```go
> > type User struct {
> >     Info *StringMap `gorm:"type:json"`
> > }
> > 
> > u := &User{
> >      Info: NewEmptyStringMap(), // 这样会初始化map，即使不设置任何值，保存后在db中的值为`{}`
> > }
> > u.Info.Src["nihao"] = "123"
> > ```
> 
> @baocaixiong 这种方式可以读写整个json字段，不知道能否实现json里面的部分属性更新？

@Septemberd 最近不写golang了，自己试试吧[😂]
