### ISSUE TITLE
gorm设置varchar(100)和size:100有什么区别？

### ISSUE THREAD

**Issue by zwl1619** [jinzhu/gorm#2200]
gorm设置varchar(100)和size:100有什么区别？
http://gorm.io/zh_CN/docs/models.html

![image](https://user-images.githubusercontent.com/13177997/49430477-157f4080-f7e6-11e8-81b0-31f74c2dbeb2.png)

**Comment by baocaixiong** [comment]
区别在于，`type`后的定义将会直接作用到create table语句中，你还可以设置 type:"int(11) unsigned auto_increment;"，且`type`有最高优先级
`size`只作用于类型为`string`或`array`或`slice`的字段，为`string`类型时判断size在0到65532之间时自动设置为varchar，大于65532时设置为`longtext`，否则自动设置为`varbinary`或`longblob`类型
详见：[dialect_mysql.go#L31](https://github.com/jinzhu/gorm/blob/master/dialect_mysql.go#L31)（仅针对mysql）

**Comment by zwl1619** [comment]
@baocaixiong 谢谢，再请教一下，还是上面那张截图：
1、`Age`字段后面的sql.NullInt64是什么意思？
2、`MemberNumber`字段的类型是`*string`，和`string`有什么不同，什么时候使用指针类型？
3、`IgnoreMe`字段后面的`gorm:"-" // 忽略本字段`，这个**忽略本字段**是什么意思？

**Comment by baocaixiong** [comment]
@zwl1619 
1.  允许db中值为NULL的bigint类型
2. `*string`允许为空，也就是说允许设置为NULL，`string`默认值是空字符串，保存时前者设置为NULL，后者为空字符串
3. 本字段不作为数据库的映射字段

**Comment by zwl1619** [comment]
@baocaixiong 文档哪里有这些说明吗？

**Comment by zwl1619** [comment]
`type:"int(11) unsigned auto_increment;"`
中间不用加分号吗？像这样：
`type:"int(11);unsigned;auto_increment;"`

**Comment by baocaixiong** [comment]
@zwl1619 
`type:"int(11) unsigned auto_increment;"`
文档没看到

**Comment by zwl1619** [comment]
@baocaixiong 再请教一下大佬：
1、`Email`字段`unique_index`和`MemberNumber`字段的`unique`有什么区别呢？
2、文档没有这些内容，那您是怎么知道这些的，看源码吗？

**Comment by zwl1619** [comment]
>1、Email字段unique_index和MemberNumber字段的unique有什么区别呢？
我知道了，唯一约束和唯一索引，mysql没有唯一约束。

**Comment by zwl1619** [comment]
@baocaixiong 再请教一下：
示例代码：
```
type BaseModel struct {
	Id        uint64     `json:"id" gorm:"type:'int(11) unsigned auto_increment;';primary_key;"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"-" sql:"index"`
}
```
1、Id字段type包含多个值，因为外面有双引号，里面只能用单引号，可是golang里面单引号好像只能是单个字符，那么用在这里可以吗？
2、还是Id字段，`auto_increment;`，后面的分号是不能少的是吗？

**Comment by baocaixiong** [comment]
看源码

```go
type BaseModel struct {
	Id        uint64     `json:"id" gorm:"type:int(11) unsigned auto_increment;primary_key;"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"-" sql:"index"`
}
```

`;`是tagsetting的分隔符，分隔多个setting需要
