### ISSUE TITLE
HasOne and BelongsTo relationships new documentation error

### ISSUE THREAD

**Issue by ezk84** [jinzhu/gorm#2206]
There is an error in the more recent documentation, these two types of relationships actually appear to be the same there.

BelongsTo example

```go
type User struct {
  gorm.Model
  Name string
}

// `Profile` belongs to `User`, `UserID` is the foreign key
type Profile struct {
  gorm.Model
  UserID int
  User   User
  Name   string
}
```

HasOne example
```go
// User has one CreditCard, CreditCardID is the foreign key
type User struct {
  gorm.Model
  CreditCard   CreditCard
  CreditCardID uint
}

type CreditCard struct {
  gorm.Model
  Number   string
}
```

But note that if I take the HasOne example and replace CreditCard with User and User with Profile we arrive at the same relationship. In both there is this pattern:

```go
type ThisModel struct{
  gorm.Model
  OtherModel OtherModel
  OtherModelID uint
}
```

This is confusing. 

It seems the old version of the docs linked in issue #1131 (http://doc.gorm.io/associations.html#has-one) has the proper syntax for a HasOne relationship, where the pattern is

```go
type ThisModel struct{
  gorm.Model 
  OtherModel OtherModel
}

type OtherModel struct{
  gorm.Model
  ThisModelID uint
}
```

**Comment by rcastill** [comment]
I am also super confused with this. Everything made sense with the old docs. Tanks @ezk84

**Comment by confixyu** [comment]
Hi!,  I was trying that example "the User hasOne CreditCard" relationship, gorm should not let me make insert or create a CreditCard register if the User does not exist.

Who know another way to solve it?

Another Question. The  gorm relationship is only for query?

**Comment by ezk84** [comment]
For doing a check like that, you could implement a BeforeCreate/BeforeSave hook to check the related User exists. 

If the User has a non nil ID then gorm will assume it is in the database. Under normal circumstances it will do an UPDATE of the related resource (if it didn’t have an ID this would result in an INSERT instead). This behavior could be turned off with the `gorm:association_autocreate` and `gorm:association_autoupdate` flags (see [here](http://gorm.io/docs/associations.html) for details).

**Comment by fgm** [comment]
I added a PR for that issue: https://github.com/jinzhu/gorm.io/pull/116 , Does anyone here want to ensure it is clearer now ?

**Comment by sgon00** [comment]
@fgm Sorry to say that it completed entirely confuses me. Where is "CreditCardID" in the PR doc? It only has `UserID` field in the struct. Btw, why can't the doc show how to create a foreign key to make it more clear and make life easier?

**Comment by sgon00** [comment]
@fgm to make myself more clear. Your change has the comment `// User has one CreditCard, CreditCardID is the foreign key`, but it doesn't have `CreditCardID` field.

**Comment by sgon00** [comment]
By reading some articles about BelongsTo and HasOne, the only difference between the two is where to store the foreign key. One stores in the child and one stores in the parent. If this is correct, both @ezk84 and @fgm PR are wrong. 

> But note that if I take the HasOne example and replace CreditCard with User and User with Profile we arrive at the same relationship.

This quote is wrong because you should not swap the parent with the child. The difference between the two concept is where to store the foreign key. So the old article before @fgm PR should be correct. 

Thus the following is correct:

BelongsTo example

```go
type User struct {
  gorm.Model
  Name string
}

// `Profile` belongs to `User`, `UserID` is the foreign key
type Profile struct {
  gorm.Model
  UserID int
  User   User
  Name   string
}
```

HasOne example

```go
// User has one CreditCard, CreditCardID is the foreign key
type User struct {
  gorm.Model
  CreditCard   CreditCard
  CreditCardID uint
}

type CreditCard struct {
  gorm.Model
  Number   string
}
```

**Comment by fgm** [comment]
The doc prior to this patch (on the old doc site) matches what the code does, but the doc prior to this patch on the current doc site inverts the descriptions. PR https://github.com/jinzhu/gorm.io/pull/116  restores the original wording from the old site, which is what the code does, from what I see it doing when applied to my code. Apparently, this is what @ezk84 and @rcastill also see.

If it does the opposite on your code, I have no explanation.
