### ISSUE TITLE
Do I need to close the connection when using inside an AWS Lambda?

### ISSUE THREAD

**Issue by celicoo** [jinzhu/gorm#2208]
### What version of Go are you using (`go version`)?
go version go1.11.2 darwin/amd64

### Which database and its version are you using?
MYSQL  Ver 8.0.12 for osx10.13 on x86_64 (Homebrew)

### Question

Do I need to close the connection before responding to a request when using within an AWS Lambda?

**Comment by celicoo** [comment]
up

**Comment by vertazzar** [comment]
db driver manages pool of connections in the background, so no - there is no need to close db every request

you can setup your db config for example:

```
db.DB().SetConnMaxLifetime(time.Second * 100)
db.DB().SetMaxIdleConns(50)
db.DB().SetMaxOpenConns(200)
```
that will keep max 200 connections, and keep 50 that are idle, along with that it wont allow connection to be alive more than 100 seconds
