### ISSUE TITLE
column "id" does not exist

### ISSUE THREAD

**Issue by krypticallusion** [jinzhu/gorm#2213]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
1.10 i suppose

### Which database and its version are you using?
postgresql ; 10

###code

```
type Locks struct {
    id int64
    photos bool
    videos bool
    stickers bool
    all bool 
}

func main() {
    db, err := gorm.Open("postgres", "user=postgres password=changeme")
    if err != nil {
        panic("failed to connect database")
    }
    defer db.Close()
    db.CreateTable(&Locks{})
    ChatLock = Locks{
            id: ChatID,
            all: true,
            }
    db.Create(&ChatLock)
    RC := db.First(&lock, "id", "ChatID")
}

## output ;
pg: column "id" does not exist.
```

I can do db.First(&Locks, Photos, "whatever") but not id

Tried to check on google, nothing good found.
}

**Comment by vertazzar** [comment]
you did not export your fields in struct

i think the struct should look like:

```
type Locks struct {
    ID int64
    Photos bool
   ...
}

```

**Comment by penguinpowernz** [comment]
Should be able to close this now.
