### ISSUE TITLE
new feature, add SetConnMaxLifetime(time.Duration) to db engine

### ISSUE THREAD

**Issue by fwhezfwhez** [jinzhu/gorm#2218]
**What I do?**
add `func (db *DB) SetConnMaxLifetime(time.Duration){...}`
**Why to add this?**
In some cases like 
```go
   if e :=db.Model(&model).First(&model);e!=nil{
        handle(e) 
   }
```
When db like postgres hung up, this program will be stuck. time-out setting should never be controled only by database server one side because once database server accidentally hangs up or blocks,its time control might lose its action. This is why `database/sql` has its way `sql.SetConnMaxLifetime(time.Duration)`,however not found in gorm engine.Except for programing like this 
```go
var ok
go func(ok chan int){
    db.Exec()
     ok<- 1
}(ok)
select{
    case <-ok:
       return
    case <-time.After(10*time.Minute):
      log.Println("time out")
      return
}
```
apparently not all programmer like to operate db like this.
Luckily I found gorm engine has its basic engine `github/lib/pq` and this realize SetConnMaxLifetime(time.Duration).
May I pull a request ?

**Comment by penguinpowernz** [comment]
PR are welcome.

**Comment by fwhezfwhez** [comment]
I realize this can be well set by
`db.DB().SetConnMaxLifetime()`
