### ISSUE TITLE
Lack Of Versioning Is An Issue

### ISSUE THREAD

**Issue by postables** [jinzhu/gorm#2224]
### What version of Go are you using (`go version`)?
1.11.3

### Which database and its version are you using?
PostgreSQL 10.6

### Issue

The lack of versioning for Gorm is some what of an issue for using it within other projects, and for a library as updated as this, which receives many fixes, potentially even breaking changes, having no way of determining, and fixing what version of the code-base is in use, *is* an issue, and will occur at some point in time.

For example, in between the version `1.9.2` and now, a major bugfix that fixed data races was merged into the codebase.Not having this library being versioned, means that to now receive this bugfix, one must pull the code in from master. For dependency management, this creates an issue over the longrun and *will* lead to pulling in unexpected changes, causing unexpected results. This can extend to pulling in breaking changes, when that isn't the desired outcome. Ultimately this leads to greater difficulties when using this library.

This is an *easy* fix, and does not require modifying any code, it just requires regularly publishing new releases. This saves developers a lot of headache, and dependency management problems and should be something that is a **must** for a project as popular as GORM as it makes package maintainers, and package users have a much more streamlined experience.

**Comment by emirb** [comment]
Thanks @postables. From now on we will regularly publish new semver releases. 
[v1.9.3](https://github.com/jinzhu/gorm/releases/tag/v1.9.3) was just released.
