### ISSUE TITLE
ID field always returns 0

### ISSUE THREAD

**Issue by fltonii** [jinzhu/gorm#2250]
So... i'm a go newbie and i'm stuck here trying to delete some posts.
I'm using Insomnia REST to help with debugging so i'll print my results.

My model:
    
    type Post struct {
	    gorm.Model
	    Title   string
	    Content string
    }

The controller in which i create a post: 

    func CreatePost(w http.ResponseWriter, r *http.Request) {
	    var newPost *models.Post
	    _ = json.NewDecoder(r.Body).Decode(&newPost)
	    fmt.Println(newPost.ID) // PRINTS ID

	    config.Db.Create(&newPost)

	    json.NewEncoder(w).Encode(newPost)
    }

The controller in which i want to access the id:

    func DeletePost(w http.ResponseWriter, r *http.Request) {
	    params := mux.Vars(r)
	    var toBeDeleted []*models.Post
	    config.Db.Where("ID = ?", params["id"]).First(&toBeDeleted)

	    config.Db.Delete(toBeDeleted)

	    config.Db.Find(&Posts)
	    json.NewEncoder(w).Encode(Posts)
    }

so when i make the post request to create a new post the response containing the post new post is:

    {
      "ID": 88,
      "CreatedAt": "2019-01-07T20:53:04.983929467-02:00",
      "UpdatedAt": "2019-01-07T20:53:04.983929467-02:00",
      "DeletedAt": null,
      "Title": "Test",
      "Content": "Hello GitHub =D"
    }
So the ID is saved correctly and auto increments.
However that `fmt.Println(newPost.ID)` ALWAYS returns 0, and the `Db.Where` never finds anything :/
What am i missing here? Is there a different way i should be calling the ID?

**Comment by penguinpowernz** [comment]
You are passing a pointer of a pointer to the method:

```
func CreatePost(w http.ResponseWriter, r *http.Request) {
    var newPost *models.Post
    _ = json.NewDecoder(r.Body).Decode(&newPost)
    fmt.Println(newPost.ID) // PRINTS ID

    config.Db.Create(&newPost)

    json.NewEncoder(w).Encode(newPost)
}```

So the `Create` method is getting a value with a type `**models.Post`.  I don't know what that will do but probably not the right thing.  Either instantiate your model as a non-pointe:

```
var newPost model.Post
```
Or don't deference the pointer when you pass it to create:
```
    _ = json.NewDecoder(r.Body).Decode(newPost)
```

**Comment by penguinpowernz** [comment]
@fltonii did this help at all?

**Comment by fltonii** [comment]
@penguinpowernz yes, it solved it! Sorry for the delay.
