### ISSUE TITLE
zero-length delimited identifier at or near """"

### ISSUE THREAD

**Issue by tywkeene** [jinzhu/gorm#2260]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.10.7 linux/amd64

### Which database and its version are you using?
Docker image postgres:9.6.1

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"fmt"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
)

var db *gorm.DB

func init() {
	var err error

	db, err = gorm.Open("postgres", "user=gorm password=gorm DB.name=gorm port=9920 sslmode=disable")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

func main() {
	type dbRow struct {
		val int
	}
	var data dbRow
	result := db.Exec("SELECT nextval(pg_get_serial_sequence('test_table', 'id')) AS val").Scan(&data)
	if result.Error != nil {
		fmt.Println("failed")
	} else {
		fmt.Println("success")
	}
}

```

Additional note: I tried the same thing with straight pq, and it worked perfectly. It seems as if there's something getting garbled in the query between gorm and pq.

This works, but another db connection isn't really ideal, especially for one off cases such as this.

**Comment by maltegrosse** [comment]
try db.Raw instead of db.Exec - helped me:
https://github.com/jinzhu/gorm/issues/1631

**Comment by axetroy** [comment]
I got same problme

```go
	tx = db.Db.Begin()

	filter := db.HostRecord{
		UserID: c.Uid,
	}

	if err = tx.Where(&filter).Count(total).Error; err != nil {
		return
	}
```

**Comment by andreijco** [comment]
you can try using db.Debug() in db.Debug().Db.Begin() to see verbose message which can help to debug

**Comment by maxbitcoin** [comment]
change “tx.Where(&filter).Count(total).Error” to “tx.Table("YourTableName").Where(&filter).Count(total).Error”
