### ISSUE TITLE
强制要求表结构中必须有created_at,updated_at和deleted_at吗？

### ISSUE THREAD

**Issue by MukuroSama** [jinzhu/gorm#2263]
没有就报错？
定义model的时候无法配置【是否使用时间戳】吗？以及指定时间戳的名称。

**Comment by lvhuat** [comment]
我就遇到相同的问题。。。使用Update的时候会自动检查，然后替换为字符串格式的updated_at 然后报错。

**Comment by lwyj123** [comment]
这个需求有什么场景吗？而且我没太理解不使用时间戳的理由。

**Comment by lvhuat** [comment]
因为我们不需要时区含糊，并且不含毫秒的时间戳。我就需要数字时间戳

**Comment by lvhuat** [comment]
复现代码见：https://github.com/lvhuat/gormtest

**Comment by MukuroSama** [comment]
我觉得，作为一个工具，给使用者自由是最基础的吧……
比如laravel的模型定义就很自由：
https://laravel-china.org/docs/laravel/5.5/eloquent/1332#0c6482
可以在定义模型的时候声明是否需要使用时间戳，而且时间戳的名字也不定死，可以自由设置（万一现有的表里就不是用的created_at呢，比如历史遗留，取了个create_time的名字）

**Comment by jinzhu** [comment]
可以不引用　gorm.Model

**Comment by lvhuat** [comment]
@jinzhu  不引用也报错了

**Comment by jinzhu** [comment]
@lvhuat en, 现在是根据 UpdatedAt 这个名字来判断的.... 暂时可以先把 UpdatedAt 换个名字, column 配置下数据库用同样的名字, 这个问题我后续再看看.
