### ISSUE TITLE
我就想请教一个问题，sql:类型的tag和gorm:类型的tag的区别是啥？我没找到相关的资料，谢谢！

### ISSUE THREAD

**Issue by y6828863** [jinzhu/gorm#2281]
如题所示。谢谢！

**Comment by y6828863** [comment]
> 没看懂

type Product struct {
    Code string `gorm:"primary_key"`
    Price uint
    UserID uint         `sql:"type:bigint REFERENCES users(id) on update no action on delete cascade"`
    UserCode string `sql:"type:bigint REFERENCES users(code) on update no action on delete cascade"`
    User User           `gorm:"foreignkey:UserID;association_foreignkey:ID"`
    gorm.Model
}

就是这个结构体中的，sql:和gorm： ，我自己测试发现没啥区别。

**Comment by jinzhu** [comment]
没有区别，可通用。
