### ISSUE TITLE
Publishing Russian translate

### ISSUE THREAD

**Issue by AlexCollin** [jinzhu/gorm#2282]
Hello! 
@jinzhu please add Russian language on site.

Only master pages are now translated. A later I plan to do documentation.
Thank

**Comment by jinzhu** [comment]
Hello @AlexCollin 

Done that, thank you.

BTW, could you help me to translate the language name?

https://github.com/jinzhu/gorm.io/blob/master/pages/_data/languages.yml#L21

Thank you.
