### ISSUE TITLE
Join relationship

### ISSUE THREAD

**Issue by ronna-s** [jinzhu/gorm#229]
Hi,
This is probably supported, but I can't seem to make it work, and couldn't find it in the documentation:
Let's say I have a one to one relation between 2 tables:
``` Go
Item struct{
    Id int
    Translation Translation
}

Translation struct{
    ItemId int
}
```
And let's say I want to get all the items with the Translations initialized. Or even 2 arrays of matching sizes using joins. Any way to do it?

**Comment by schickling** [comment]
+1

**Comment by jinzhu** [comment]
Hi All,

We already have the eager loading feature, please checkout https://github.com/jinzhu/gorm#preloading-eager-loading
