### ISSUE TITLE
AfterFind callback (a real one)

### ISSUE THREAD

**Issue by ernestoalejo** [jinzhu/gorm#230]
Currently the AfterFind callback gets called both when there's a result and when there's not. Some models need additional initialization (like decoding a JSON chunk or caching data) that only needs to occur if the Find() call actually finds something.

I propose renaming AfterFind to AfterQuery and make a real AfterFind callback.

**Comment by jinzhu** [comment]
Hi @ernestoalejo 

> Also we can take advantage of the change to fix the an error in the callbacks system, when using a []*model{} doesn't work, but when using a []model{} works. Should I open another issue for that or do we solve it in this one?

This issue should already been fixed

Also changed gorm to don't call callbacks if there are any errors.

**Comment by ernestoalejo** [comment]
Thx!
