### ISSUE TITLE
如何去除deleted_at默认查询条件？

### ISSUE THREAD

**Issue by always-waiting** [jinzhu/gorm#2319]
我们有一个deleted_at字段，但不是软删除标记字段，标记字段是is_delete字段
现在的困境是查询时，会默认添加`deleted_at is null`这个条件，我要怎么去除?

@jinzhu

**Comment by soogoo** [comment]
可以试试这个，文档上有写
```
// 使用Unscoped查找包含软删除的记录
db.Unscoped().Where("age = 20").Find(&users)
//// SELECT * FROM users WHERE age = 20;

// 使用Unscoped永久删除记录
db.Unscoped().Delete(&order)
//// DELETE FROM orders WHERE id=10;
```

**Comment by deslum** [comment]
please use issue pattern https://github.com/jinzhu/gorm/blob/0fd395ab37aefd2d50854f0556a4311dccc6f45a/.github/ISSUE_TEMPLATE.md

**Comment by jinzhu** [comment]
don't embed the `gorm.Model` struct, write your own without `DeletedAt` column.
