### ISSUE TITLE
version 1.9.2  manytomany:tableName not correct

### ISSUE THREAD

**Issue by lizhihua0925** [jinzhu/gorm#2322]
I define a many to many relation:
type Xxx struct {
UserAlerts      []*UserAlert      `gorm:"many2many:userAlert;association_autoupdate:false"`
}
type Yyy struct {
        Name                   string
	WebhookAlerts    []*Xxx`gorm:"many2many:userAlert"`
}
then the code 
<pre> 
db.Preload("Xxx").Where(&Yyy{Name: name}).First(u)
</pre>
in version 1.9.1 
<pre>
SELECT * FROM `Xxx` INNER JOIN `userAlert` ....
</pre>
but in version 1.9.2
<pre>
SELECT * FROM `Xxx` INNER JOIN `user_alert` ....
</pre>

The tables userAlert and user_alert is auto create, how to keep use userAlert?

**Comment by Clowning** [comment]
Same issue...

**Comment by apuckey** [comment]
Not sure if this helps but you can customize the NamingStrategy:
```
gorm.AddNamingStrategy(&gorm.NamingStrategy{
	DB: func(name string) string {
		return name
	},
	Table: func(name string) string {
		return name
	},
	Column: func(name string) string {
		return name
	},
})
```
Probably the same in #2326

**Comment by emirb** [comment]
Fixed in https://github.com/jinzhu/gorm/pull/2331
