### ISSUE TITLE
Many2Many syntax error

### ISSUE THREAD

**Issue by Clowning** [jinzhu/gorm#2326]
GoVersion : 1.12
Database : PostgreSQL 11.2

Hi, i'm trying to make a many2many relation but I've got this error ->
```pq: relation "'offers_operating_systems'" does not exist``` 

And it's true, this table doesn't exist!

But in my (offer)model i set it to 
```gorm:"many2many:offers_operatingSystems;foreignkey:id;association_foreignkey:id;association_jointable_foreignkey:operatingSystemsId;jointable_foreignkey:offersId;" ```

I guess this issue is because I use a capital for 'Systems' but I can't change my database.

So, can you know have to fix this table name? 

Thanks

**Comment by emirb** [comment]
Fixed in https://github.com/jinzhu/gorm/pull/2331
