### ISSUE TITLE
GORM project name intersects with already in use GORM in Grails

### ISSUE THREAD

**Issue by ibakirov** [jinzhu/gorm#2340]
Project name GORM intersects with already in use name GORM in Grails project (http://gorm.grails.org/, https://github.com/grails) which leads to confusion.

**Comment by inliquid** [comment]
Kinda joke. Project GORM intersects with many other 'ORM' projects. Grails can always change its name if they think it's a problem.

**Comment by ibakirov** [comment]
Name 'ORM', yes definitely is common used term in many languages and frameworks. Today I came across with this project and slightly confused with name. I'm just bringing the fact from Java world user perspective using frameworks such as Spring, Grails and etc.

**Comment by inliquid** [comment]
'GORM' length is just 4 chars. 3 of them is 'ORM' which is definitely points to its nature. One remaining char is 'G' which is definitely points to 'Go'. There will always be some competing names that will want to name themselves by 1 letter + ORM. And number of latin letters is quite limited. Fortunately, it's not a domain name or trademark. I am quite familiar with Java world, and don't think it's confusing and makes any difficulties in recognition.

**Comment by longwa** [comment]
Or you could just name it something that isn't already taken....

Seriously, of the probably 30 or 40 ORM tools out there for every language, almost none of them have the ORM letters in the name.

Yet, you choose one that (you already knew) was being used and now shows up as top search results everytime I search for something. Thanks.
