### ISSUE TITLE
查询映射问题

### ISSUE THREAD

**Issue by simsq** [jinzhu/gorm#2343]
type Result struct {
	Id        int
	ProjectId int
}

func GetOrderInfo(w rest.ResponseWriter, r *rest.Request) {
	var result []Result
	db.Raw("SELECT Id,ProjectId  FROM orders  WHERE CreateTime LIKE '%2019-03-18%'").Scan(&result)
	fmt.Println(result)	 
}
如上代码返回的结果为 
[205 rows affected or returned ] 
[{0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0} {0 0｝ 
是我哪里写错了吗？

**Comment by edgeidea** [comment]
where is the table orders? 你的查询语句有问题哦，没看到交叉查询关键子。你写的只是单表查询

**Comment by simsq** [comment]
> 表订单在哪里？你的查询语句有问题哦，没看到交叉查询关键字。你写的只是单表查询

是的，我在尝试使用单表查询，然后将结果映射到Result结构体中，可为什么输出的结果是 0 0 而不是我实际数据库表中的值？百思不得其解，是bug吗？

**Comment by simsq** [comment]
我已经解决了！我换了Xorm   就ok了。
