### ISSUE TITLE
为什么 db.Exec() 执行select语句，总是返回 [0 rows affected or returned ] 

### ISSUE THREAD

**Issue by kiwi2019** [jinzhu/gorm#2378]
我执行：
row := db.Exec("SELECT * FROM user Limit 1")

连接、库、表名 都没有任何报错。
debug 信息:
[2019-04-08 11:46:30]  [4.10ms]  SELECT * FROM joy Limit 1  
[0 rows affected or returned ] 

表里也是有记录的
我把这个sql语句，放到Navicat里面执行  SELECT * FROM joy Limit 1
是可以得到结果的。

是哪里设置有问题？

**Comment by a969295028** [comment]
请问是怎么解决的

**Comment by a969295028** [comment]
好吧 要用 raw  ---

**Comment by TomLiu-GitHub** [comment]
我的raw一样返回0

**Comment by Basenode** [comment]
> 我的raw一样返回0

解决了吗

**Comment by TomLiu-GitHub** [comment]
> > 我的raw一样返回0
> 
> 解决了吗

解决了

**Comment by stevenkitter** [comment]
如何解决不说么
