### ISSUE TITLE
请问isnert之后，获取自增ID值的最佳实践是什么？

### ISSUE THREAD

**Issue by gi19901212** [jinzhu/gorm#2383]
比如添加完一个用户，我马上就要知道这个user的ID，其中在数据库中这个ID是自增的。这个功能用原生的mysql是很好实现的，在其它orm上也提供有简单方法获取，但是看了一遍gorm文档居然没发现怎么获取的。。。。。。求大神们支招。

**Comment by Tang-RoseChild** [comment]
1.结构体中带个id字段
2.用原生的sql接口,Result有个LastInsertId

**Comment by gi19901212** [comment]
> 1.结构体中带个id字段
> 2.用原生的sql接口,Result有个LastInsertId

你好，小弟不才，请问你写的1和2是两种方法，还是两个步骤？

**Comment by Tang-RoseChild** [comment]
> > 1.结构体中带个id字段
> > 2.用原生的sql接口,Result有个LastInsertId
> 
> 你好，小弟不才，请问你写的1和2是两种方法，还是两个步骤？

两种方法

**Comment by miaozilong** [comment]
用uuid才是最佳实践，获取自增id要多操作一次数据库，还要加锁

**Comment by DoubleLuck** [comment]
job = db.Create(job).Value.(*model.Job)
fmt.Println(job.ID)

**Comment by qufo** [comment]
> 用uuid才是最佳实践，获取自增id要多操作一次数据库，还要加锁

Yes, you are doing the  right thing.
