### ISSUE TITLE
Gorm does not support MSSQL Server

### ISSUE THREAD

**Issue by smithaitufe** [jinzhu/gorm#2395]
### What version of Go are you using (`go version`)?
1.11.4

### Which database and its version are you using?
MSSQL Server and version is 2017 via docker
### Error
`mssql` is not officially supported, running under compatibility mode.
(/home/smith/go/src/github.com/smithaitufe/games/backend/db/migration.go:48) 
[2019-04-13 20:28:33]  mssql: Incorrect syntax near 'AUTO_INCREMENT'. 

(/home/smith/go/src/github.com/smithaitufe/games/backend/db/migration.go:48) 
[2019-04-13 20:28:33]  [0.06ms]  CREATE UNIQUE INDEX uix_days_name ON "days"("name")   
[0 rows affected or returned ] 

(/home/smith/go/src/github.com/smithaitufe/games/backend/db/migration.go:48) 
[2019-04-13 20:28:33]  mssql: Incorrect syntax near 'AUTO_INCREMENT'. 
2019/04/13 20:28:33 mssql: Incorrect syntax near 'AUTO_INCREMENT'.

Thank for your prompt response

**Comment by Enginebeck** [comment]
> Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.
> 
> ### What version of Go are you using (`go version`)?
> 1.11.4
> 
> ### Which database and its version are you using?
> MSSQL Server and version is 2017 via docker
> 
> ### Error
> `mssql` is not officially supported, running under compatibility mode.
> (/home/smith/go/src/github.com/smithaitufe/games/backend/db/migration.go:48)
> [2019-04-13 20:28:33] mssql: Incorrect syntax near 'AUTO_INCREMENT'.
> 
> (/home/smith/go/src/github.com/smithaitufe/games/backend/db/migration.go:48)
> [2019-04-13 20:28:33] [0.06ms] CREATE UNIQUE INDEX uix_days_name ON "days"("name")
> [0 rows affected or returned ]
> 
> (/home/smith/go/src/github.com/smithaitufe/games/backend/db/migration.go:48)
> [2019-04-13 20:28:33] mssql: Incorrect syntax near 'AUTO_INCREMENT'.
> 2019/04/13 20:28:33 mssql: Incorrect syntax near 'AUTO_INCREMENT'.
> 
> Thank for your prompt response

same question

**Comment by TomLiu-GitHub** [comment]
`mssql` is not officially supported, running under compatibility mode.

**Comment by Enginebeck** [comment]
> `mssql` is not officially supported, running under compatibility mode.

@TomLiu-GitHub Thanks, @smithaitufe  I solved this issue by exec `go get github.com/jinzhu/gorm/dialects/mssql`, you can try this, please close this issue if it worked on your environment.

**Comment by TomLiu-GitHub** [comment]
haaaaaaa,After I set up the TCP connection, it worked well.
![image](https://user-images.githubusercontent.com/32833966/59260693-a429ba00-8c6e-11e9-9b5e-c9f4c7771d55.png)
