### ISSUE TITLE
Associations don't work when using slice of struct pointers

### ISSUE THREAD

**Issue by rvenugopal** [jinzhu/gorm#240]
Hello

If I change the example in the documentation to use a slice to struct pointers, Gorm complains.
I am using Postgres 9.3 if that helps 

```
type User struct {
    Id           int64
 
    Emails            []*Email         // This doesn't work 
}
```

Thanks
-Rv

**Comment by jinzhu** [comment]
Hi @rvenugopal 

Sorry for the long time no response, this should be fixed now.

Thank you for your report.
