### ISSUE TITLE
can't create table with charset utf8mb4

### ISSUE THREAD

**Issue by GeorgeXc** [jinzhu/gorm#2407]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.10.8 darwin/amd64

### Which database and its version are you using?
mysql 5.6.42

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package utils

import (
	"github.com/jinzhu/gorm"
	//_ "github.com/jinzhu/gorm/dialects/mysql"
)

type GormDb struct {
	db *gorm.DB
}

func NewGormDb(dsn string) (*GormDb, error) {
	db, err := gorm.Open("mysql", dsn)
	if err != nil {
		return nil, err
	}
	db.Set("gorm:table_options", "CHARSET=utf8mb4")
	return &GormDb{db: db}, nil
}

func (g *GormDb) CreateTables() {
	g.db.CreateTable(&Product{}) //未使用utf8建表
}
func (g *GormDb) Close() {
	g.db.Close()
}

type Product struct {
	gorm.Model
	Code  string
	Price uint
}
```
```go
package main

import (
	"base/pkg/utils"
	"fmt"

	"github.com/jinzhu/gorm"
)

func main() {
	g, err := utils.NewGormDb("test:123456@tcp(127.0.0.1:3306)/testdb?parseTime=True&loc=Local&charset=utf8")
	if err != nil {
		fmt.Println(err.Error())
		return
	}
	gorm.DefaultTableNameHandler = func(db *gorm.DB, defaultTableName string) string {
		return "tb_" + defaultTableName
	}
	g.CreateTables()
	g.Close()
}
```

**Comment by KwonGiho** [comment]
Ya i wanna know this too.

theres an issue about how to set utf-8 when table created
https://github.com/jinzhu/gorm/issues/1835

it also is not working for me. 

is there who can help us? :(

**Comment by GeorgeXc** [comment]
> Ya i wanna know this too.
> 
> theres an issue about how to set utf-8 when table created
> #1835
> 
> it also is not working for me.
> 
> is there who can help us? :(
db, err := gorm.Open("mysql", dsn)
	if err != nil {
		return nil, err
	}
db = db.Set("gorm:table_options", " ENGINE=InnoDB CHARSET=utf8mb4")

**Comment by qm012** [comment]
@GeorgeXc  Could you please tell me how you solved this problem?
@jinzhu An error occurred when using db.create () with CHARSET= utf8MB4 for the self-created database
```shell
Error 1366: Incorrect string value: '
```

precondition
```go
dsn: charset=utf8mb4&parseTime=True&loc=Local&collation=utf8mb4_unicode_ci
```

gorm generates SQL execution error
```sql
Error 1366: Incorrect string value: '\xD8\xC9\x9C\xCB\xFCn...' for column 'phone' at row 1
[1.501ms] [rows:0] INSERT INTO `member_account` (`platform_no`,`phone`,`password`,`id`) VALUES ('sOD48WeM7u','�ɜ��n�^�JZU�0�','$2a$10$bwSP/E8Tj0zxmWTBwKISYeeEPaZiYg.08IJj4kkRICSmonFCsqK5.',29)
```

But executing this statement on the SQL client is valid
```sql
[SQL]INSERT INTO `member_account` (`platform_no`,`phone`,`password`,`id`) VALUES ('sOD48WeM7u','�ɜ��n�^�JZU�0�','$2a$10$bwSP/E8Tj0zxmWTBwKISYeeEPaZiYg.08IJj4kkRICSmonFCsqK5.',29)

受影响的行: 1
时间: 0.010s
```
