### ISSUE TITLE
Self-Referencing cannot generate such a statement

### ISSUE THREAD

**Issue by liov** [jinzhu/gorm#2414]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?

1.12.4
### Which database and its version are you using?
postgre 11.0.1

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
)

var db *gorm.DB

func init() {
	var err error
	db, err = gorm.Open("postgres", "user=gorm password=gorm DB.name=gorm port=9920 sslmode=disable")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}


type Comment struct {  
	ID uint 
        PraentID uint
	SubComment  []Comment  `gorm:"association_jointable_foreignkey:praent_id"`
}

func main() {
	db.Preload("SubComment").First(&comment , "id = ?", 1)
}
```
why not
```sql
SELECT a.* FROM "comment" a INNER JOIN "comment" b ON a.praent_id = b.id WHERE b.id =1;
```

**Comment by zaneli** [comment]
Try to use `foreignkey` and `association_foreignkey`.
```go
type Comment struct {
	ID         uint
	PraentID   uint
	SubComment []Comment `gorm:"foreignkey:id;association_foreignkey:praent_id"`
}
```

http://gorm.io/docs/has_many.html#Association-ForeignKey

**Comment by liov** [comment]
thanks
