### ISSUE TITLE
How to  config one to many with same model?

### ISSUE THREAD

**Issue by mfdefs** [jinzhu/gorm#2422]
the struct like this：
type Tree struct {
	gorm.Model
	Name     string
	children []Tree
}

**Comment by HeJiaNong** [comment]
![image](https://user-images.githubusercontent.com/39476157/57286124-388c8400-70e7-11e9-89f1-e75eb7f5d82c.png)

To define a self-referencing many2many relationship, you have to change association’s foreign key in the join table.

to make it different with source’s foreign key, which is generated using struct’s name and its primary key
