### ISSUE TITLE
Skip loading struct fields value after create

### ISSUE THREAD

**Issue by kaustubhmallik** [jinzhu/gorm#2426]
### What version of Go are you using (`go version`)?
go version go1.11.1

### Which database and its version are you using?
PostgreSQL v10.6

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
```
type Animal struct {
    ID   int64
    Name string `gorm:"default:'galeone'"`
    Age  int64
}

db.Automigrate(&Animal{})

var animal = Animal{Age: 99, Name: ""}
db.Create(&animal)
// INSERT INTO animals("age") values('99');
// SELECT name from animals WHERE ID=111; // the returning primary key is 111
// animal.Name => 'galeone'
```

In the above create method, there are actually two steps getting performed.

1. A struct is getting inserted by the **INSERT** query into the database.
2. Database row data is getting loaded into the struct using **SELECT** query.

Is there a way to skip the second step, and just insert and check if the insert is successful. The reason I am looking for this is that I am using the same database connection concurrently to do multiple inserts inside a transaction block.

And, it fails due to the concurrent reads happening in the second step. So, is there a way to turn-off/skip the second step of the Create method call.

**Comment by zaneli** [comment]
Call `db.Callback().Create().Remove("gorm:force_reload_after_create")`

```go
	type Animal struct {
		ID   int64
		Name string `gorm:"default:'galeone'"`
		Age  int64
	}

	db.Callback().Create().Remove("gorm:force_reload_after_create")
	var animal = Animal{Age: 99, Name: ""}
	if err := db.Create(&animal).Error; err != nil {
		return err
	}

	// db saved real value is 'galeone', but struct value is empty.
	fmt.Println(animal.Name)
```

**Comment by kaustubhmallik** [comment]
Thanks a lot @zaneli Is there a way I can get to see a list of all such` gorm:force_reload_after_create` parameters to change the default behavior.

**Comment by zaneli** [comment]
Hmmm...I don't know if there is document or so on.
I read source code `gorm/callback_***.go` and actually tried it.

https://github.com/jinzhu/gorm/blob/b7156195f7f3415f97c20abbd6aff894b847fee8/callback_create.go#L10-L18

**Comment by kaustubhmallik** [comment]
Thanks.
