### ISSUE TITLE
Gorm 怎么对接达梦数据库？

### ISSUE THREAD

**Issue by flame2017** [jinzhu/gorm#2446]

**Comment by DoubleLuck** [comment]
达梦貌似是oracle套了个壳子，官方不支持oracle。
参考
* https://github.com/jinzhu/gorm/issues/1453
* https://github.com/go-xorm/xorm

**Comment by flame2017** [comment]
十分感谢您的回复




发自网易邮箱大师


在2019年05月10日 10:14，DoubleLuck<notifications@github.com> 写道：

达梦貌似是oracle套了个壳子，官方不支持oracle。
参考

#1453
https://github.com/go-xorm/xorm
