### ISSUE TITLE
Enhancement request : Event hooks not firing for intersection table struct

### ISSUE THREAD

**Issue by rvenugopal** [jinzhu/gorm#245]
Lets say I have 2 model objects with a many to many relationship between them.  When I try to create a person, the child Address objects are being created.  

However, I would like to map a struct to the intersection table and have the event hooks (BeforeCreate/BeforeSave/AfterSave etc) fire even for the intersection struct.  Please see below example.

```
type Person struct {
    Id int64
    Addresses         []Address `gorm:"many2many:person_addresses;"` // Many-To-Many relationship
}

type Address struct {
    Id int64
    People         []Person `gorm:"many2many:person_addresses;"` // Many-To-Many relationship
}

type Person_Address struct {
   PersonId  int64
   AddressId int64
   CreatedAt  time
   DeletedAt time
   Version int
}

func (self Person_Address) Table_Name() string {
   return "person_addresses"
}

func (self Person_Address) BeforeCreate() {
   self.CreatedAt = time.Now().UTC()   // **Not firing**
}


```

**Comment by jinzhu** [comment]
Gorm support JoinTableHandler now https://github.com/jinzhu/gorm/blob/master/join_table.go,  so possible to support any thing for join table, please check the test as example https://github.com/jinzhu/gorm/blob/master/join_table_test.go

Let me know if have any suggestions.

**Comment by rvenugopal** [comment]
:thumbsup:
