### ISSUE TITLE
db.Where().Row().Scan()之后，方法结束，where条件未释放，下次执行同一个方法会把上次执行方法的where条件带进来

### ISSUE THREAD

**Issue by hypwxm** [jinzhu/gorm#2452]
```go
err = db.Model(&User{}).Where("id=?", 1).Select("id").Row().Scan(&modelOne.Salt)
```
如果第一次是select id from user where id=1;
第二次进来如果条件改为Where("id=?", 2)就会 select id from user where id=1 and id=2

**Comment by hypwxm** [comment]
db.Model(model) 里面的model是全局的，条件里面加id对这个model造成了影响。

**Comment by hoysoft** [comment]
同样问题，不知道如何解决

**Comment by hypwxm** [comment]
可能是你用Model选择表的时候用了全局的变量。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: hoysoft <notifications@github.com>
发送时间: 2019年7月13日 12:56
收件人: jinzhu/gorm <gorm@noreply.github.com>
抄送: hypwxm <1825909531@qq.com>, State change <state_change@noreply.github.com>
主题: 回复：[jinzhu/gorm] db.Where().Row().Scan()之后，方法结束，where条件未释放，下次执行同一个方法会把上次执行方法的where条件带进来 (#2452)




同样问题，不知道如何解决
