### ISSUE TITLE
Should not log messages like "(pq: duplicate key value violates unique constraint) "

### ISSUE THREAD

**Issue by zhangriyueming** [jinzhu/gorm#2457]
### What version of Go are you using (`go version`)?
1.12.5

### Which database and its version are you using?
postgres 12

### What do you expect?

Should not log messages like `(pq: duplicate key value violates unique constraint) `

**Comment by buildscientist** [comment]
@zhangriyueming 
These types of logs and others can be suppressed by by calling `gorm.DB.LogMode(false)`

See the gorm docs on [logging](http://gorm.io/docs/logger.html#content-inner) for more details.

**Comment by zhangriyueming** [comment]
@buildscientist - Thank you, I'm going to close this issue.
