### ISSUE TITLE
Dialect mssql treat password as port if there is a # character in password

### ISSUE THREAD

**Issue by whs-dot-hk** [jinzhu/gorm#2467]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### Which database and its version are you using?
go version go1.12.5 darwin/amd64

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	// _ "github.com/jinzhu/gorm/dialects/mysql"
	// _ "github.com/jinzhu/gorm/dialects/postgres"
	// _ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

func init() {
	var err error
	// db, err = gorm.Open("sqlite3", "test.db")
	// db, err = gorm.Open("postgres", "user=gorm password=gorm DB.name=gorm port=9920 sslmode=disable")
	// db, err = gorm.Open("mysql", "gorm:gorm@tcp(localhost:9910)/gorm?charset=utf8&parseTime=True")
	db, err = gorm.Open("mssql", "sqlserver://gorm:passwordEndWith#@localhost:9930?database=gorm")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

func main() {
	//if [> failure condition <] {
		//fmt.Println("failed")
	//} else {
		//fmt.Println("success")
	//}
}
```

**Comment by li-keli** [comment]
So, did you solve your problem? I have the same problem

**Comment by whs-dot-hk** [comment]
Hi, solved

I generated another password without a #

**Comment by li-keli** [comment]
.....
I'm a tragedy

**Comment by whs-dot-hk** [comment]
No, see this line

https://github.com/golang/go/blob/c2c2ba280c77e76115cf1918d91a509f6bf98390/src/net/url/url.go#L476

it is a rfc3986 spec

https://tools.ietf.org/html/rfc3986#section-3.5

**Comment by li-keli** [comment]
I have found that a different concatenation string can avoid the splitting of some special characters

```go
connectionString := fmt.Sprintf("server=%s;user id=%s;password=%s;port=%d;database=%s", host, user, password, port, dbname)
db, err := gorm.Open("mssql", connectionString)
```
