### ISSUE TITLE
how to update id field?

### ISSUE THREAD

**Issue by xiehui3651** [jinzhu/gorm#2473]
### What version of Go are you using (`go version`)?

go version go1.12.4

### Which database and its version are you using?
mysql 5.6

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

func init() {
	var err error
	db, err = gorm.Open("mssql", "sqlserver://gorm:LoremIpsum86@localhost:9930?database=gorm")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

type TestTable struct {
ID uint32 `gorm:"primary_key"`
Name string `gorm:"size:64;index;not null;comment:'名称'"`
}

func main() {
        insertData := &TestTable {
              ID:1,
              Name:"test",
       }
        db.Create(&insertData)
        db.Model(&TestTable ).Where("id=?", insertData.ID).Update("id", 22)
	if /* failure condition */ {
		fmt.Println("failed")
	} else {
		fmt.Println("success")
	}
}
```
want sql: UPDATE `t_test_table ` SET `id` = 22WHERE `t_course`.`deleted_at` IS NULL AND `t_test_table `.`id` = 1
execute sql:UPDATE `t_test_table ` SET `id` = 22WHERE `t_course`.`deleted_at` IS NULL AND `t_test_table `.`id` = 1 AND ((id = 22))

so id can't be update

**Comment by xuhrc** [comment]
I got a same problem, 
Execute an original sql to update the primary key.

**Comment by zaneli** [comment]
hmm...
https://github.com/jinzhu/gorm/blob/836fb2c19d84dac7b0272958dfb9af7cf0d0ade4/scope.go#L744-L749

work around... 😕 

```go
db.Table("test_tables").Where("id=?", insertData.Id).Update("id", 22)
```
