### ISSUE TITLE
按月分表后数据还是写到了上一个月的表

### ISSUE THREAD

**Issue by osenv** [jinzhu/gorm#2475]
Hello，

gorm我这边使用了分表，如果程序是5月份启动的，那么6月份如果不重启程序的话，数据还是会写到5月份的表里去，请问下有遇到这种情况的吗？

I'm using gorm for splitting table data writing and fetching. If I start the go program this month and leave it without restarting next month, the data will be still writing into the previous month mysql table, which is unacceptable. Is there any other guys come across this situation? If so, how do you handle this problem? Many thanks if any help could be given.

### What version of Go are you using (`go version`)?
go version go1.12.5 darwin/amd64

### Which database and its version are you using?
MySQL with version 5.7

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

```go
func (q Message) TableName() string {
	currentTime := time.Now().Local()
	format := currentTime.Format("200601")
	return fmt.Sprintf("message_%s", format)
}

```

**Comment by lrita** [comment]
Do you use a long term `gorm.Scope`? Some `gorm.DB` method will create a internal `gorm.Scope`.

**Comment by osenv** [comment]
Hi I used the Table function to make this solved. Thank you anyway!
