### ISSUE TITLE
model filed have zero values,but why inserting SQL include those fields?

### ISSUE THREAD

**Issue by sun-wenming** [jinzhu/gorm#2476]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.12 windows/amd64

### Which database and its version are you using?
mysql 5.5.53

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

I read docs : https://gorm.io/docs/create.html#Default-Values.

but the zero values insert into sql. How to fix it?

My code:
```
        userProfile := new(proto.UserProfile)
	userProfile.Nickname = swmUtil.GetRandomString(15)
	fmt.Println(userProfile)  // nickname:"c2c56284dyZ2utt"

	// INSERT  INTO `user_profile` (`nickname`,`created_at`,`updated_at`,`deleted_at`,`status`,`xxx_unrecognized`,`xxx_sizecache`)
	// VALUES (?,?,?,?,?,?,?)[c2c56284dyZ2utt  0 0 0 [] 0] 0
	if err := tx.Create(userProfile).Error; err != nil {
		tx.Rollback()
		return err
	}
```

Looking forward to your reply.

**Comment by sun-wenming** [comment]
I think it is case by `!field.IsPrimaryKey`.

In addition to the primary key will be inserted into sql.

Is there anything else that can be solved?

@jinzhu  Looking forward to your help.

```
 if !field.IsPrimaryKey || !field.IsBlank {
  columns = append(columns, scope.Quote(field.DBName))
  placeholders = append(placeholders, scope.AddToVars(field.Field.Interface()))
}
```

[callback_create.go#L66](https://github.com/jinzhu/gorm/blob/b7156195f7f3415f97c20abbd6aff894b847fee8/callback_create.go#L66)

**Comment by DoubleLuck** [comment]
`If you want to avoid this, consider using a pointer type or scanner/valuer`
You can get this from [doc](https://gorm.io/docs/create.html)

**Comment by sun-wenming** [comment]
I have tried this program.
I used this library last year and it is normal.
But now the code is the same and the result is wrong.
I do not know why.
Temporary plan `!field.IsPrimaryKey` delete .
```
        var profile = proto.UserProfile{Nickname: "99",}
	if err := u.db.Create(&profile).Error; err != nil {
		return err
	}
```

**Comment by sun-wenming** [comment]
Change code can solve my problem. I don't know if it is correct.
for reference only
```
 } else if !field.IsPrimaryKey || !field.IsBlank {
    columns = append(columns, scope.Quote(field.DBName))
    placeholders = append(placeholders, scope.AddToVars(field.Field.Interface()))
}
```

To 

```
} else if !field.IsBlank {
	if !field.IsPrimaryKey {
	  columns = append(columns, scope.Quote(field.DBName))
	  placeholders = append(placeholders, scope.AddToVars(field.Field.Interface()))
	}
}
```
