### ISSUE TITLE
scope.Fields() returns nil

### ISSUE THREAD

**Issue by DarainS** [jinzhu/gorm#2477]
In the follow codes:
```go
func (scope *Scope) Fields() []*Field {
	if scope.fields == nil {
		// do something
	}
	return *scope.fields
}
```
the Fields() method would check scope.fields' nil. But in golang, both its type and its value are nil and it would be nil.  *(scope.fields) is nil, but scope.fields are not. And this method returns nil.
Is it as expected or a bug?

**Comment by emirb** [comment]
Check out the `scope_test.go`, this code is fully covered.
The method works as expected and returns `[]*Field`.
