### ISSUE TITLE
结构体查询的时候,表名不正确

### ISSUE THREAD

**Issue by anheicang** [jinzhu/gorm#2479]
var keyword3 Keyword
	result := db.Table("keyword").Where(&Keyword{Name: "哈哈"}).First(&keyword3)
	if result.Error != nil {
		fmt.Println(result.Error)
	}
	fmt.Printf("%+v\n", keyword3)

  Error 1054: Unknown column 'keywords.name' in 'where clause' 
为什么表名显示的是keywords ??

**Comment by emirb** [comment]
By default, table name is the pluralized version of struct name.
To override this, you can define `TableName()` method on your `Keyword` struct:
```go
func (Keyword) TableName() string {
  return "keyword"
}
```
