### ISSUE TITLE
阿里云MYSQL分析数据库连接错误

### ISSUE THREAD

**Issue by hookover** [jinzhu/gorm#2534]
gorm 连接阿里云分析数据库for mysql错误，使用database/sql和xorm 没问题
主要报两个错误:
Error 1044: Can not use this command here！
Error 30101: MPP_QUERY_FAILED Retry_time=1 message=MPP engine error code: 30101, message: processId=2019070119233401121604708609999304728 QueryError{message=line 2:6: backquoted identifiers are not supported; use double quotes to quote identifiers, sqlState=null, errorCode=32010, errorName=PARSING_ERROR, errorType=USER_ERROR, errorLocation=ErrorLocation{lineNumber=2, columnNumber=6}, failureInfo=mpp.client.FailureInfo@3c821efb} processId=2019070119233401121604708609999304728 mppQueryId=20190701_112334_349_agt3m

错误代码解释：
https://helpcdn.aliyun.com/document_detail/26431.html

### What version of Go are you using (`go version`)?
最新版本

### Which database and its version are you using?
https://www.aliyun.com/product/ads?spm=a2c4g.11186623.cwnn_jpze.61.17634c07BpqsJb

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
package dbtablestruct

import (
	"fmt"
	sql2 "database/sql"
	_ "github.com/go-sql-driver/mysql"
	"github.com/go-xorm/xorm"
	"github.com/jinzhu/gorm"
	"synchronizer/library/walle/element"
)

func GetTableFieldType(db *gorm.DB, tableName string) (err error, fields []*element.Field) {
	sql := fmt.Sprintf("select table_name,column_name,data_type from INFORMATION_SCHEMA.columns where table_name = '%s'", tableName)

	if q := db.Exec(sql); q.Error != nil {
		fmt.Println("grom error:", q.Error)
	} else {
		if rows, err := q.Rows(); err != nil {
			fmt.Println("qrows error", err)
		} else {
			fmt.Println("gorm ok:",rows)
		}
	}

	engine, err := xorm.NewEngine("mysql", "密码传到github，慌得一批")
	results, err := engine.Query(sql)
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println("xorm ok :",len(results))
	}

	db2, err := sql2.Open("mysql", "密码传到github，慌得一批")
	res, err := db2.Query(sql)
	if err != nil {
		fmt.Println("Errorrrr", err)
	} else {
		fmt.Println("database/sql ok:", res)

	}

	return
}

```

response:
```
qrows error Error 30101: MPP_QUERY_FAILED Retry_time=1 message=MPP engine error code: 30101, message: processId=2019070120354310010604714509999294190 QueryError{message=line 2:6: backquoted identifiers are not supported; use double quotes to quote identifiers, sqlState=null, errorCode=32010, errorName=PARSING_ERROR, errorType=USER_ERROR, errorLocation=ErrorLocation{lineNumber=2, columnNumber=6}, failureInfo=mpp.client.FailureInfo@71bda3c6} processId=2019070120354310010604714509999294190 mppQueryId=20190701_123543_1664_sgyvq
xorm ok : 88
database/sql ok: &{0xc00045c500 0x44400e0 0xc0001b8050 <nil> <nil> {{0 0} 0 0 0 0} false <nil> []}
```

**Comment by jinzhu** [comment]
http://gorm.io/docs/sql_builder.html
