### ISSUE TITLE
how to Execute multi update sql ?

### ISSUE THREAD

**Issue by nevernet** [jinzhu/gorm#2557]
```
sql = `update chapters set parent_id=112812 where id=112770;
	update chapters set parent_id=112766 where id=112771;`

err := w.GetWriteConnection().Raw(sql).Error
```

use `Raw` or `Exec` doesn't work. 
please advice, thank you

**Comment by xwjdsh** [comment]
You need to set `multiStatements ` to `true` in dsn.

https://github.com/go-sql-driver/mysql#multistatements

**Comment by nevernet** [comment]
@xwjdsh i got error: 'panic: 初始化数据库连接失败:<省略了>?charset=utf8mb4&parseTime=True&multiStatements=True&loc=Local(Error 1193: Unknown system variable 'multiStatements')'

**Comment by nevernet** [comment]
i have updated gorm and go-sql-driver, and everything goes well now :)

**Comment by SmileYun** [comment]
```
sql := "INSERT ....; INSERT ...."
sql := "INSERT ....; CALL xx(input)"
```

`.Exec(sql)` will return a syntax error Err:1064 while db using`gorm.Open` with the param `PrepareStmt=true`. (Also multiStatements=true be set in dsn )

Could you give some guidance or advice for that? Or Is it confirmed that the gorm.db cannot support this?
@xwjdsh @jinzhu 

Thanks in advance！
