### ISSUE TITLE
error in "incomplete parentheses found" checking

### ISSUE THREAD

**Issue by nevernet** [jinzhu/gorm#2561]
see bug fix from #2517 and pull request `https://github.com/jinzhu/gorm/pull/2519/commits`

but please try this sql: 
```
REPLACE INTO origin_exercise_options SET id=707105, content='（–2014)–1 ', exercise_id=473112, is_true=1, created_time=NOW();
```

in the field `content` there is Chinese `（` and English `)`， when use `Exec(rawSQL)`, then i got the error: 
`incomplete parentheses found: `

but the sql is correct.

any advice?

**Comment by ansel1** [comment]
Ditto.  The IsCompleteParentheses() function doesn't ignore parens inside quotes.  Here's the sql that's a problem for me:

```
SELECT 'ALTER TABLE ' || 
       quote_ident(dest_schema) || 
       '.' || 
       quote_ident(rn.relname) ||
       ' ADD CONSTRAINT ' ||
       quote_ident(ct.conname) ||
       ' ' ||
       regexp_replace(pg_get_constraintdef(ct.oid),
           ' REFERENCES (?:' ||
                                                   quote_ident(source_schema) ||
                                                   '\.)?(.*)\(',
           ' REFERENCES ' ||
                                                                 quote_ident(dest_schema) ||
                                                                 '.\1(') ||
      ';'
      FROM pg_constraint ct
      JOIN pg_class rn ON rn.oid = ct.conrelid
     WHERE connamespace = src_oid
       AND rn.relkind = 'r'
       AND ct.contype = 'f'
```

Note the parens inside the quoted string args to regexp_replace().  I gather if those strings were injected later as variables, this would probably work.

I'm not seeing an obvious workaround.  IsCompleteParentheses looks specifically for ascii chars, so maybe the parens inside the quoted strings could be replaced with an encoded unicode point or something?  IsCompleteParentheses seems like a half baked solution for SQL injection.

**Comment by emirb** [comment]
For the time being, should we revert https://github.com/jinzhu/gorm/pull/2519? 
cc @jinzhu

**Comment by ansel1** [comment]
I think you should.  It makes gorm unusable with certain, valid SQL.

**Comment by ansel1** [comment]
Workaround to avoid the code that does the parens matching:

    db = db.NewScope(nil).Raw(problemSQL).Exec().DB()

**Comment by athom** [comment]
This is a breaking change, should be disabled by default. 
it will make existing record can not be updated.
another workaround is to revert to tag `v1.9.9` lol

**Comment by Jonathan34** [comment]
are we going to have a 1.9.12 that fixes this CVE? This is preventing us to release our deployment :o.
Thanks
