### ISSUE TITLE
请问：gorm中怎么创建联合唯一索引？

### ISSUE THREAD

**Issue by lddlww** [jinzhu/gorm#2575]

**Comment by minchenzz** [comment]
`type Test struct {
	ID int
	Filed1 string `gorm:"type:varchar(100);unique_index:idx1"`
	Filed2 string `gorm:"type:varchar(100);unique_index:idx1"`
	Filed3 string `gorm:"type:varchar(100);unique_index:idx1"`
}`

**Comment by lddlww** [comment]
貌似我这样写不生效：
type Test struct{
    gorm.Model
    Metric        string  `gorm:"type:varchar(1000);not null;unique_index:uq_metric_mid"`
    Filter          string `gorm:"type:varchar(20)"`
    App           string `gorm:"type:varchar(20)"`
    MetersID   uint `gorm:"unique_index:uq_metric_mid"`
    Meters       Meters
}

**Comment by minchenzz** [comment]
mysql默认情况下单个列的索引不能超过767位 (utf-8)
fmt.Println(DB.AutoMigrate(&Test{}).Error)
应该会显示错误的

**Comment by lddlww** [comment]
@minchenzz ，谢谢，我用的是5.6版本是有这个问题

**Comment by jokerhahaha123** [comment]
用这个创建联合索引的话最左匹配原则是怎样的啊？就联合索引中字段的排序是怎样的

**Comment by minchenzz** [comment]
@jokerhahaha123 
gorm 生成索引是按 go struct 中定义的顺序
