### ISSUE TITLE
It is very terrible of update struct.

### ISSUE THREAD

**Issue by enjoydiy** [jinzhu/gorm#2578]
It's first time to use gorm.

About update, I want to update some cols. In xorm, I do this:
`type User struct {
Name string
Age uint
}`
`e.ID(u.ID).Cols("name", "age").Update(u)`

But in gorm, I try:
`
db.Model(&u).Select("Name,Age").Update(&u)
`

It does not work. Look up the apis, no work. How do you update? Using the sick map struct?

**Comment by enjoydiy** [comment]
Fond one way:
`db.Model(&u).Select("Name", "Age").Update(&u)`

There is no more detail about select api. Can someone explain the detail?

**Comment by enjoydiy** [comment]
Actually, I use the api like:
`
func (this *User) Update(cols ...interface{}) error {
	return db.Model(this).Select(nil,cols...).Update(this).Error
}
`

I do not know if it is right way.

**Comment by enjoydiy** [comment]
There is one issue:
When the name is null string, the field name do not be updated.

Can gorm disable the check point?

**Comment by sswanv** [comment]
> Fond one way:
> `db.Model(&u).Select("Name", "Age").Update(&u)`
> 
> There is no more detail about select api. Can someone explain the detail?

In addition to this way, you can also：
```golang
db.Model(&u).Select([]string{"Name", "Age"}).Update(&u)
```
[This is a detailed code snippet.](https://github.com/jinzhu/gorm/blob/master/scope.go#L297-L315)

**Comment by enjoydiy** [comment]
> > Fond one way:
> > `db.Model(&u).Select("Name", "Age").Update(&u)`
> > There is no more detail about select api. Can someone explain the detail?
> 
> In addition to this way, you can also：
> 
> ```go
> db.Model(&u).Select([]string{"Name", "Age"}).Update(&u)
> ```
> 
> [This is a detailed code snippet.](https://github.com/jinzhu/gorm/blob/master/scope.go#L297-L315)

Thanks, I finally pick the way
`
func (this *User) Update(cols ...string) error { return db.Model(this).Select(cols).Save(this).Error }
`
