### ISSUE TITLE
Order函数有sql注入风险，如何防止?

### ISSUE THREAD

**Issue by zltgo** [jinzhu/gorm#2591]
```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

var db *gorm.DB

type User struct {
	Model
	Name string
	PasswordHash string
}

func init() {
	var err error
	db, err = gorm.Open("sqlite3", "test.db")
	")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
}

func main() {
	users := make([]User, 0)
        //这段代码能执行成功
        db.Debug().Order("name; drop table 'users'").Find(&users)
}
```

**Comment by movsb** [comment]
我觉得下面这段代码也能执行成功：

```go
db.Exec("drop table users")
```

要不要也修修呢？

**Comment by 5-say** [comment]
> 我觉得下面这段代码也能执行成功：
> 
> ```go
> db.Exec("drop table users")
> ```
> 
> 要不要也修修呢？（狗头）

话糙理不糙，不过话是真的糙！

**Comment by jamsonzan** [comment]
> 我觉得下面这段代码也能执行成功：
> 
> ```go
> db.Exec("drop table users")
> ```
> 
> 要不要也修修呢？（狗头）

话糙理不糙，不过话是真的糙！

**Comment by zltgo** [comment]
@5-say
只是请教一下解决办法，不是要修代码。

再一个，exec表示执行任何sql语句，而order函数表示排序，语义是不一样的。
gorm的where函数就是把条件都用括号括起来了，能够防止一些恶意注入，就很不错。

**Comment by movsb** [comment]
其实，`Exec`和`Order`应该是给程序员自己写的代码调用的。如果要把用户的输入直接交给这类函数，需要程序员自己过滤不安全的内容。当然，由于`Order`的功能很明确，加上校验也无可厚非。

至于解决办法，你可以自己写一个正则表达式过滤一下就好了。类似（手写的）：`\w+( ?\w+)?`。

`Where`括起来是因为内部在拼接SQL语句的时候保证子表达式的优先级和代码的预期一致。

**Comment by zltgo** [comment]
where函数还是蛮完善的，函数体内对用户输入的括号数量及顺序进行了检查，
db.Where( “1=1);drop table users(”  )是无法执行的。

**Comment by movsb** [comment]
`Where`更不像是直接放入用户的输入的，加上检查反倒降低了性能。如果要放入用户的查询语句，考虑使用DSL，然后转换成SQL。

**Comment by zltgo** [comment]
大佬再请教下如何对用户输入进行校验，我是刚接触这一块没什么经验。比如以下查询
db.Where(“name=？”‚user.Name)
需要对变量user.Name进行什么样的校验，是用正则表达式么，检查该变量不能有空格分号这样？

**Comment by movsb** [comment]
突然成为大佬。。。

像这样的代码，只要第一个参数（query）不出现用户的内容，就不需要任何校验。

**Comment by zltgo** [comment]
刚测试了一下确实是这样，db.Where(“name=？”‚“aa or 1=1") 是不能查询成功的。
生成的sql语句是((name = 'aa or 1=1'))

现在就剩下Order函数怎么检查了，按什么排序是用户指定的，如何设计接口和检查来防止注入呢。

**Comment by movsb** [comment]
如果你数据库里面存在一个`name`==`aa or 1=1`的数据，还那是会查询成功的啊。

你要严格检查的话，我以前这样写过，你可以参考一下：

https://github.com/movsb/taoblog/blob/2de16d6d52b7d167e3ac828338dfce288e25fe6e/themes/blog/page_posts.go#L41

这样太严格了，不太推荐。

你可以规定格式为：`字段名,升降序`。然后用正则表达式检测一下是否符合这个规则。符合的话，把逗号改成空格，传递给`Order`。把字段是否存在，升降序留给数据库去检查。

**Comment by navono** [comment]
问个跟这个问题不相关的问题，这里的 sqlite 怎么使用 [User Authentication](https://github.com/mattn/go-sqlite3#user-authentication)?

**Comment by chenyu1990** [comment]
可以考虑自己封装一个func来拼接Order

**Comment by tuhaolam** [comment]
> 问个跟这个问题不相关的问题，这里的 sqlite 怎么使用 [User Authentication](https://github.com/mattn/go-sqlite3#user-authentication)?

这种你另外起issue吧
