### ISSUE TITLE
how to order by field ?

### ISSUE THREAD

**Issue by apptut** [jinzhu/gorm#2596]
I can't find anything about order by mysql function `field()`, just as:

```sql
select id from Table order by field(id, 3, 1, 2);
```
how to work in gorm?

**Comment by shi-yang** [comment]
I am also confused about this. The feasible solution I know so far is:
```golang
DB.Order(gorm.Expr("FIELD(id,3,1,2)")
```

However, if I have an array of type int , I have to convert it to a string and splice into the `gorm.Expr` expression.

```golang
	ids := []int{3, 1, 2}
	idsString := strings.Replace(strings.Trim(fmt.Sprint(ids), "[]"), " ", ",", -1)
	// idsString now is a string: 3,1,2
	DB.Where("id in (?)", ids).
		Order(gorm.Expr(fmt.Sprintf("FIELD(id, %s)", idsString))).
		Find(&post)
```
The generated sql is:
```sql
 SELECT * FROM `post`  WHERE (id in ('3','1','2')) ORDER BY FIELD(id, 3,1,2)
```

Is there any other better solution?

**Comment by apptut** [comment]
Thanks, I got it!
