### ISSUE TITLE
Table() Model() 具体都有什么区别

### ISSUE THREAD

**Issue by dulumao** [jinzhu/gorm#2599]
rt

**Comment by star936** [comment]
db.Table()参数为database表名，以此来操作数据;
使用db.Model()前需要先将database表与struct结构关联起来，然后就可以使用struct对象来操作数据.

**Comment by dulumao** [comment]
> db.Table()参数为database表名，以此来操作数据;
> 使用db.Model()前需要先将database表与struct结构关联起来，然后就可以使用struct对象来操作数据.

嗯明白，是否可以理解 db.Table("xxx").whereXXX与db.Model(&struct).whereXXX结果集是没有区别的

**Comment by star936** [comment]
还是有区别的.可以看看中文文档:https://jasperxu.github.io/gorm-zh/

**Comment by dulumao** [comment]
好的
