### ISSUE TITLE
where doesn't use tag 'Column' and generated wrong sql

### ISSUE THREAD

**Issue by marcelloh** [jinzhu/gorm#2613]
go version 1.12.8
Various databases (sqlite and postgres)

I have a model "user" that has a field:
```
LocationID uint `gorm:"Column:location_id"` // Foreign key location
```
When I try to filter on this field, this is the sql generated:
```
SELECT * FROM "user"  WHERE "user"."deleted_at" IS NULL AND ((LocationID = '1')) 
```
This sql statement is wrong!
It should however use the Column tag's variant:
```
SELECT * FROM "user"  WHERE "user"."deleted_at" IS NULL AND ((location_id = '1')) 
```
I can fix this in a workaround (by altering the ware with the correct tag variant, but I expect Gorm to do this automagically. (This is where the tag 'Column' is used for, I think.)

**Comment by zaneli** [comment]
Hmm...I can't reproduce it.
This seems to be works fine.
```go
func find(db *gorm.DB) ([]User, error) {
  var users []User
  if err := db.Where(&User{LocationID:1}).Find(&users).Error; err != nil {
    return nil, err
  }
  return users, nil
}

type User struct {
  gorm.Model
  LocationID uint `gorm:"Column:location_id"`
}
```
generate
```sql
SELECT * FROM `users`  WHERE `users`.`deleted_at` IS NULL AND ((`users`.`location_id` = 1))
```
Can you provide the complete code?

**Comment by marcelloh** [comment]
No unfortunately not, since this was in August and we moved on.
