### ISSUE TITLE
Feature Request: AutoMigrate for indexes

### ISSUE THREAD

**Issue by gnidan** [jinzhu/gorm#262]
I'm using AutoMigrate() and also setting up indexes. If I've already set up the table, running AddIndex complains about duplicate key name.

There doesn't seem to be a HasIndex() function that I could use to check for an index first, so I'm not even sure of a workaround. Please advise!

Thanks!

**Comment by pedromorgan** [comment]
Yes please..

This is my messy workarounds...
and also Views..
So I got a function to createIndex
https://github.com/daffodil/factory-planner/blob/master/app/fp/projects/brand.go

and whole create tables sequence is
https://github.com/daffodil/factory-planner/blob/master/app/fp/dev/db_create.go

and views
https://github.com/daffodil/factory-planner/blob/master/app/fp/dev/db_views.go

Index'es would really help..

**Comment by pedromorgan** [comment]
Is anyone working on this..

Basically is there an idea how to do it ?? eg `gorm:"index"` or alike ??

**Comment by pedromorgan** [comment]
Mysql =  single table =
```
SHOW INDEX FROM <table>;
```
Mysql = All indexes in db
```
SELECT DISTINCT TABLE_NAME, INDEX_NAME FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = '<table>'
```

Dont the information schema work on all DB's sql92?? or whatever ??

**Comment by jinzhu** [comment]
Hi All,

I have added this, you could use it like this:

```go
type Email struct {
    ID      int
    UserID  int     `sql:"index"` // tag `index` will create index for this field when using AutoMigrate
    Email   string  `sql:"type:varchar(100);unique_index"` // tag `unique_index` will create unique index
}

type Language struct {
    ID   int
    Name string `sql:"index:idx_name_code"` // Create index with name, and will create combined index if find other fields defined same name
    Code string `sql:"index:idx_name_code"` // `unique_index` also works
}
```

Thank you.
