### ISSUE TITLE
Using pointers in the schema

### ISSUE THREAD

**Issue by ventayol** [jinzhu/gorm#263]
Hi,

I've the following schema:
`````
 go
type AppVersion struct {
    Id            int64     `json:"id"`
    App           App       `json:"app,omitempty"`
    AppId         int64     `sql:"not null" json:"app_id"`
    Version       string    `sql:"not null" json:"version"`
    Sessions      []Session `json:"-"`
    SessionsCount int       `sql:"-"`
    CreatedAt     time.Time `json:"created_at"`
    UpdatedAt     time.Time `json:"updated_at"`
    DeletedAt     time.Time `json:"deleted_at"`
}
``````

Everything works fine, but I would like to change the `App App` to `App *App`, so I can set it to `nil` when I encode it to JSON.
I've tried it and I get errors using the pointer version. 
Is it supported?
Any suggestion?

**Comment by jinzhu** [comment]
Hello @ventayol 

Yes, the pointer version is supported, but it has to been a Scanner, so the database driver knows how to decode the value into database.

**Comment by codingrogue** [comment]
I just came across the same problem, can you explain what you mean with Scanner? I have the following example struct:
```
type Device struct {
    Guid *string
}
```
I'm doing this because I want to be able to distinguish if the field has been set to zero value ("") on purpose or if the field got ommited when implementing my PATCH rest route.
