### ISSUE TITLE
Build failed when using go modules

### ISSUE THREAD

**Issue by dre2004** [jinzhu/gorm#2630]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

```go
package main

import (
  "github.com/jinzhu/gorm"
  _ "github.com/jinzhu/gorm/dialects/sqlite"
)

type Product struct {
  gorm.Model
  Code string
  Price uint
}

func main() {
  db, err := gorm.Open("sqlite3", "test.db")
  if err != nil {
    panic("failed to connect database")
  }
  defer db.Close()

  // Migrate the schema
  db.AutoMigrate(&Product{})

  // Create
  db.Create(&Product{Code: "L1212", Price: 1000})

  // Read
  var product Product
  db.First(&product, 1) // find product with id 1
  db.First(&product, "code = ?", "L1212") // find product with code l1212

  // Update - update product's price to 2000
  db.Model(&product).Update("Price", 2000)

  // Delete - delete product
  db.Delete(&product)
}
```
When using go modules (go mod init && go mod tidy) with the above code I get the following error.
```
$ GO111MODULE=on go mod tidy
go: finding github.com/jinzhu/gorm/dialects/sqlite latest
go: finding github.com/jinzhu/gorm/dialects latest
go: finding cloud.google.com/go v0.37.4
go: cloud.google.com/go@v0.37.4: unknown revision v0.37.4
go: error loading module requirements

```
Note that this works fine when doing ``` go get -u github.com/jinzhu/gorm``` and then running / building / etc without the use of go modules. The problem is specifically related to go modules.

This is enabled by setting the environment variable GO111MODULE=on. I believe the root cause is the go.mod & go.sum files within the project root.

**Comment by emirb** [comment]
Hi @dre2004, can you give me some more details about the following:
- do you do this in a newly initialized directory, just creating main.go and then running `go mod init` and `go mod tidy`? my output is the following and everything works fine:
```bash
$ go mod init
go: creating new go.mod: module github.com/emirb/gorm-test
$  go mod tidy
go: finding github.com/jinzhu/gorm/dialects/sqlite latest
go: finding github.com/jinzhu/gorm/dialects latest
```
- can you paste the content of yours `go.mod` after doing the above? 

Thanks!

**Comment by dre2004** [comment]
Hello @emirb !

Thanks for the response, here correct the example I showed above was from a freshly initialized directory. I created this simple example main.go file using an example from the readme.md on this repo.

```
[ec2-user@ip-x-x-x-x testgorm]$ ls
main.go
[ec2-user@ip-x-x-x-x testgorm]$ GO111MODULE=on go mod init
go: creating new go.mod: module testgorm
[ec2-user@ip-x-x-x-x testgorm]$ GO111MODULE=on go mod tidy
go: finding github.com/jinzhu/gorm/dialects/sqlite latest
go: finding github.com/jinzhu/gorm/dialects latest
go: finding cloud.google.com/go v0.37.4
go: cloud.google.com/go@v0.37.4: unknown revision v0.37.4
go: error loading module requirements
[ec2-user@ip-x-x-x-x  testgorm]$ cat go.mod
module testgorm

go 1.12
[ec2-user@ip-x-x-x-x testgorm]$
```

I've tried it on both a Linux / Windows / Docker container and get the same result. On my actual project that I'm running into this issue I've found a work around by using glide which seems to deal with the versions better (its been able to stick to version ^1.9.10 as opposed to HEAD which I assume go mod uses?)
