### ISSUE TITLE
how use in GORM  DISTINCT to many rows ?

### ISSUE THREAD

**Issue by SergeyVlasov** [jinzhu/gorm#2637]
I want something like this:
SELECT DISTINCT name, addres FROM table

**Comment by monzarrugh** [comment]
db.Select("DISTINCT(name, addres)").Find(&model)

**Comment by SergeyVlasov** [comment]
thanks!!!

**Comment by zaneli** [comment]
@SergeyVlasov 
If you have already solved it, please close this issue yourself.
