### ISSUE TITLE
Rename main.go to gorm.go

### ISSUE THREAD

**Issue by mjarkk** [jinzhu/gorm#2646]
### My issue:
![Screenshot from 2019-09-04 09-48-25](https://user-images.githubusercontent.com/15320763/64235716-3998bb00-cef9-11e9-8cf3-93a3cb7d55db.png)
When i want to open the main.go in a project with gorm in the vendor folder my editor always suggests to open the main.go file in gorm.  

Because gorm is the only package in my hole vendor folder that contains at least 200 git projects that all don't have a main.go file this looks a bit wrong.  

It would be nice of the main.go file had another name to overcome this like `gorm.go`.

### What version of Go are you using (`go version`)?
```
go version go1.12.7 linux/amd64
```

### Which database and its version are you using?
```
Database: mysql
Gorm: v1.9.10
```

**Comment by iWinston** [comment]
I don't think it's necessary to rename main.go. Maybe you should config your VScode to fix this problem.

**Comment by mjarkk** [comment]
Yes it's not really necessary but this is more of a best practice for go libraries.

**Comment by iWinston** [comment]
I notice there's a phrase("recently opened") in your screenshot. Maybe the editor suggested you open the main.go file in gorm is just because you had opened it?
