### ISSUE TITLE
only Raw select works

### ISSUE THREAD

**Issue by berk-can** [jinzhu/gorm#2669]
### What version of Go are you using (`go version`)?
1.12.5

### Which database and its version are you using?
Mysql 5.6.45

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

I can successfully select by where condition by using Raw as shown below:
```
        user:=model.User{}
	err = U.db.Raw("SELECT username,password FROM user WHERE username=?","berk").Scan(&user).Error
```

but cannot get model by any other method
eg:
```
	err = U.db.Where("username=?","berk").First(&user).Error
	err = U.db.Model(&model.User{}).Where("username=?","berk").First(&user).Error

```

could it be some configuration I am missing?
My model is as shown below:

type User struct {
	Username    Username
	Password    Password
	Email       Email
	Status      UserStatus
	Permissions []UserPermission
	Role        Role
	ID        uuid.UUID `json:"id"         bson:"_id" gorm:"primary_key;"`
	Version   int       `json:"version"    bson:"version"`
	CreatedAt time.Time `json:"created_at" bson:"created_at"`
	UpdatedAt time.Time `json:"updated_at" bson:"updated_at"`
	DeletedAt time.Time `json:"deleted_at" bson:"deleted_at"`
}

**Comment by berk-can** [comment]
I've found the problem, querying without Raw put deleted_at IS NULL to the select and my values are inserted with deleted_at being 0000-00-00 00:00:00
is there a way to insert them with NULL instead of 0000-00-00 00:00:00 ?

**Comment by jeckii** [comment]
Hey bro, I've found the same issue. I can only use the table to get the struct model. But your solution is not affective.
golang version is 1.12.9
mysql version is 8.0.18

`      var user User
        DB.Table("user").
		Select("id,name,password,salt,role,permission,data_flag,lock_flag, creation_time").
		Where("name = ?", name).
		Scan(&user) // successfull
	DB.Take(&user, "name = ?", name) // all fields is null
	DB.First(&user, "name = ?", name) // all fields is null
`

**Comment by jeckii** [comment]
Hey bro, I've found the same issue. I can only use the table to get the struct model. But your solution is not affective.
golang version is 1.12.9
mysql version is 8.0.18
the code is as shown below:
var user User

DB.Table("user"). Select("id,name,password,salt,role,permission,data_flag,lock_flag, creation_time"). Where("name = ?", name). Scan(&user) // successfull

DB.Take(&user, "name = ?", name) // all fields is null 

DB.First(&user, "name = ?", name) // all fields is null

**Comment by jeckii** [comment]
Hey bro, I've found the same issue. I can only use the table to get the struct model. But your solution is not affective.
golang version is 1.12.9
mysql version is 8.0.18
the code is as shown below:
var user User

DB.Table("user"). Select("id,name,password"). Where("name = ?", name). Scan(&user) // successfull

DB.Take(&user, "name = ?", name) // all fields is null

DB.First(&user, "name = ?", name) // all fields is null

**Comment by berk-can** [comment]
@jeckii do you have delete_at field in SQL? Also is there a row with variable name and deleted_at being EMPTY or NULL ?

**Comment by jeckii** [comment]
@berk-can there is no field called deleted_at in SQL. does this field have to be in SQL? I've not notice the rule.

**Comment by berk-can** [comment]
@jeckii there is no rule that obligates for a filed like 'deleted_at' but my issue occurred when I use that field on SQL and not make it pointer because when it is not pointer golang makes it nil TIME which is a bunch of 0's and when I query without Raw gorm automatically puts 'AND deleted_at==NULL' which causes empty result, but your problem has nothing in common here

**Comment by jeckii** [comment]
@berk-can Thanks, I've found out the cause of the problem. Because of the field name is upper case in my database. But the convention of gorm is that the names of columns should be lower case if I use the model instead of table.  I ignore it when i used the framework.

**Comment by berk-can** [comment]
@jeckii good for you, if you follow camel case naming all you need to do is convert first letter to lower case and all other upper case letters to _lower case letters or you can define gorm tag and you can enable debugging to see executed sql queries by gorm which helps me so much
