### ISSUE TITLE
gorm 默认对零值的处理行为会导致不可预知的副作用

### ISSUE THREAD

**Issue by zhyq0826** [jinzhu/gorm#2676]
由于 gorm 不处理零值，比如一个带副作用的操作，删除或更新，且 struct 的关键字段带零值，会导致 gorm 处理完成的 where 语句中不带任何条件，这种默认行为会造成非常危险的副作用，建议提供开关可以关闭这种行为。

```go
DB.Delete(&Domain{ID: 0})                                                   //DELETE FROM `domains`
```

**Comment by fumeboy** [comment]
因为结构体的初始化会携带 0 值，所以这个问题是难以避免的，你可以用一个额外的字符串数组说明 结构体 中的哪些值 是需要传入的

**Comment by DoubleLuck** [comment]
* read doc
* https://godoc.org/github.com/jinzhu/gorm#DB.BlockGlobalUpdate

**Comment by fumeboy** [comment]
今天在golangtc 这个网站也找到了讨论零值和空的帖子。你可以看一下这个库：https://github.com/mattn/go-nulltype

**Comment by zhyq0826** [comment]
DB.BlockGlobalUpdate 一定程度上可以避免，而且对项目改动较小 @DoubleLuck

**Comment by m3shine** [comment]
gorm各种不符原生数据库操作的预期，简直坑死人

**Comment by axetroy** [comment]
中国确实很坑爹

在 update 的时候，一些 0 值的字段就没办法更新上去

只能使用 `map[string]interface{}` 去更新

可是这样又失去了编译检查
