### ISSUE TITLE
can you change the gorm.Model definition？

### ISSUE THREAD

**Issue by snowdream** [jinzhu/gorm#2681]
gorm.Model

now:
```
type Model struct {
  ID        uint `gorm:"primary_key"`
  CreatedAt time.Time
  UpdatedAt time.Time
  DeletedAt *time.Time
}
```

new:
```
type Model struct {
	ID        uint       `gorm:"primary_key" json:"id"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}
```

**Comment by siku2** [comment]
You don't have to use `gorm.Model` in your structs. `gorm.Model` isn't required and doesn't do anything apart from providing these fields. Instead, GORM looks for fields with the names "ID", "CreatedAt", and so on and updates them accordingly ([relevant documentation](http://gorm.io/docs/conventions.html)).

This means that you can define your own "base model" struct:

```go
type MyModel struct {
  ID        uint       `gorm:"primary_key" json:"id"`
  CreatedAt time.Time  `json:"created_at"`
  UpdatedAt time.Time  `json:"updated_at"`
  DeletedAt *time.Time `json:"deleted_at"`
}
```

and use it in your structs:

```go
type User struct {
  MyModel

  Name string `json:"name"`
}
```

The fields from `MyModel` will be treated the same way as those defined in `gorm.Model`.
