### ISSUE TITLE
support postgres array types

### ISSUE THREAD

**Issue by pakohan** [jinzhu/gorm#270]
Given two tables:
```sql
CREATE TABLE foo (
  id SERIAL PRIMARY KEY,
  data TEXT,
  bar_ids INTEGER []
);

CREATE TABLE bar (
  id SERIAL PRIMARY KEY,
  data TEXT
);
```

And the current structs:
```go
type Bar struct {
  Id uint64
  Data string
}

type Foo struct {
  Id uint64
  Data string
  Bars []Bar
}
```

I want to use the feature of Postgres arrays to make a many2many reference, without using a third table. I assume this is not possible yet, since I tried in several ways, for example with the `Scanner` interface and Querying in the `Scan()` method of Bar.

The solution is adding a field *Bar_ids* to `type Foo struct` and then adding an `AfterFind()` callback, the ParameterConverter of the *pg* driver is able to handle int slices. But I assume gorm overwrites the ParameterConverter and is not able to handle int slices.

I tested this with the same struct in the same program execution, pure *pg* driver is able to handle this case, with gorm I get the following error:

```
reflect.Set: value of type []uint8 is not assignable to type []int
```

Is there a possibilty to use the drivers ParameterConverter as a fallback? I don't think this is possible yet.

**Comment by deoxxa** [comment]
@pakohan, you might want to look at https://github.com/jinzhu/gorm/pull/353 - I'm using this mechanism to implement the `Scanner` and `Valuer` interfaces for named slice types (e.g. `type IntList []int`) in an application I'm building.

I implement a `Value` function that basically returns `"{" + list.join(",") + "}"` for that type to persist it to the database, and a `Scan` function that does the same in reverse to pull it back out.

**Comment by jinzhu** [comment]
Going to close this issue because long time haven't receive any feedback from original reporter.

I think we can't use a array type for many to many relations, maybe for has_many relations? but it is not necessary in this case then, we don't need a join table.

anyway, just like @deoxxa said, you could try to use Valuer, Scanner to save/get any value to/from database.
