### ISSUE TITLE
where("id in (?)", []uint8{1,2})  got unexpected result

### ISSUE THREAD

**Issue by rbdoer** [jinzhu/gorm#2703]
### What version of Go are you using (`go version`)?
go version go1.11.4 darwin/amd64

### Which database and its version are you using?
mysql

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

 When I was using `where("id in (?)", []uint8{1,2})`, I set LogMode=2 and I got the sql of "SELECT * FROM `test_table`  WHERE (id IN ('< binary>') ) ".   

After checking the code, I find out the code in scope.go line:612
```
case reflect.Slice: // For where("id in (?)", []int64{1,2})
	if scanner, ok := interface{}(arg).(driver.Valuer); ok {
		arg, err = scanner.Value()
		replacements = append(replacements, scope.AddToVars(arg))
	} else if b, ok := arg.([]byte); ok { 

		// HERE: if the arg is type of []byte,  it will be parsed to string
		replacements = append(replacements, scope.AddToVars(b))
	} 
```

I think it may be a bug to fix

**Comment by zaneli** [comment]
Hmm...It may be unexpected, but I think this is a valid specification.

`uint8` is an alias for `byte`.

```go
vs := []uint8{97, 98}
s := string(vs) // ab
```

`97`, `98` slice or `ab` string seems to be indistinguishable.
You should use `[]int8`, `[]uint16` and so on.

**Comment by rbdoer** [comment]
@zaneli  Yeah, we fix it by using []int8.  But I think gorm should be compatibility with []uint8 .
how about stop using "[]uint8{97, 98}" , instead of using string type "ab" ?

**Comment by zaneli** [comment]
@rbdoer 
I agree with your opinion.
However, maybe not good to change default behavior.

This just came to my mind, I tried to send #2745.
If this PR is accepted, we can use as below.
```go
db.Set("gorm:bytes_value_as_array", true).Where("id IN (?)", []byte{1, 2})
```
or
```go
db = db.Set("gorm:bytes_value_as_array", true)
db.Where("id IN (?)", []byte{1, 2}).Find(&user)
```

**Comment by jinzhu** [comment]
https://github.com/jinzhu/gorm/pull/2745#issuecomment-562183691

**Comment by jinzhu** [comment]
https://github.com/jinzhu/gorm/pull/2745#issuecomment-562183691
