### ISSUE TITLE
How to check if table column exists

### ISSUE THREAD

**Issue by tentone** [jinzhu/gorm#2711]
### Which database and its version are you using?
MS SQL Server

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Hello

Is there a way with GORM to check if a table column exists by its name?

Im tring to figure out a way to achieve this (for data migration routines).

Thanks a lot

**Comment by sirius1024** [comment]
https://godoc.org/github.com/jinzhu/gorm#DB.HasTable
Is this function that you need?

**Comment by tentone** [comment]
Hello

No, i was looking for something like:

`db.Table("something").HasColumn("derp")`

To check if a table has a column with the name "derp".

Thanks a lot

**Comment by sirius1024** [comment]
Sorry my fault.
I think dialects for MSSQL can resolve it.
https://github.com/jinzhu/gorm/blob/795328fedc12a34cd2ea7483b2d8ee618bca46c6/dialects/mssql/mssql.go#L154

https://github.com/jinzhu/gorm/blob/795328fedc12a34cd2ea7483b2d8ee618bca46c6/embedded_struct_test.go#L29

**Comment by tentone** [comment]
Thanks a lot that worked perfectly.
