### ISSUE TITLE
增加db.Use()函数,便于多个库切换

### ISSUE THREAD

**Issue by TomLiu-GitHub** [jinzhu/gorm#2719]
我需要在同一服务器上的多个数据库中切换工作

> 现在我只能用sql构建

例如
```
databasename:="users"
db.Row("use "+databasename+";select * from user;")
```
>  这样我失去了gorm的大部分功能.我只能使用sql构建.

***
### 请问,能否考虑增加Use函数

例如
```
db.Use("databasename").Find(&users)
```
Thanks

**Comment by fifsky** [comment]
个人建议这个功能应该在应用层包装，比如定义个连接map，将所有需要用到的数据库连接好存放到map中，然后定义一个Use方法取即可

**Comment by TomLiu-GitHub** [comment]
> 个人建议这个功能应该在应用层包装，比如定义个连接map，将所有需要用到的数据库连接好存放到map中，然后定义一个Use方法取即可

这样叫变通实现，并不能完美解决这个需求问题。
多个连接会产生资源浪费等，
有的库不一定用到，产品不行必要的连接。
考虑库的创建删除，动态查询，以及负载等情况，如果用map管理连接，就需要很多地方去维护这个map，增加系统的复杂程度。
***
比如
一般企业管理系统会有个xxSystem用来做系统库，用户建立一个账套创建一个新的账套数据库。
用户选择登录哪个库的时候查询哪个库的数据。
集团客户多个子公司的时候，选择多个库来查询，这样，库是动态的，并不固定。

**Comment by jinzhu** [comment]
建议 `db.Table("databasename.users").Find(&users)`

**Comment by TomLiu-GitHub** [comment]
这样的话会非常非常的麻烦，因为有很长很长的sql语句
像下图这样
![image](https://user-images.githubusercontent.com/32833966/73604233-08b3d380-45c8-11ea-910e-2f7411aa3ad0.png)

**Comment by cyanzhao** [comment]
> 这样的话会非常非常的麻烦，因为有很长很长的sql语句
> 像下图这样
> ![image](https://user-images.githubusercontent.com/32833966/73604233-08b3d380-45c8-11ea-910e-2f7411aa3ad0.png)

现在有解决方案了吗，我也觉得应该是每个表维护自己的一个meta（包括连接的数据库等），是比较好的方案。而不是需要查找所在的库

**Comment by TomLiu-GitHub** [comment]
jinzhu closed this on 27 Jan
