### ISSUE TITLE
offset bug

### ISSUE THREAD

**Issue by apptut** [jinzhu/gorm#2734]
Hi, guys:

When I use the offset() for pagnation, but I found strange things, I think this is a bug !

My database have 3200000 records, when the offset more than 1000000 the Find Sql offset disappear, the code as:

```go
page := 101 // test
offset := (math.Max(float64(page), 1) - 1) * float64(pageSize) // the offset is 1000000
db.Debug().Where(where).Limit(pageSize).Offset(offset).Find(&results);
```
the output as

```sql
[2019-10-29 13:47:48]  [348.58ms]  SELECT * FROM `site`  WHERE (is_available = 1 AND is_recommend = 1) ORDER BY `id` LIMIT 10000  
[10000 rows affected or returned ] 
```
At last I founded, if I change the offset type float64 to Int , this bug not show again, Why?

**Comment by zaneli** [comment]
offset seems to convert `interface{}` -> `string` -> `int`

https://github.com/jinzhu/gorm/blob/179760d8343ed15cbb9f071ca824bc35ee7784bb/dialect_common.go#L148-L152

999999 as float64 : `999999` works fine.
1000000 as float64 : `1e+06` failed to `strconv.ParseInt`
https://play.golang.org/p/C6KIAZZsXC6

I think this is unnatural behavior, maybe a bug.
But anyway now you should change the offset type float64 to Int.
