### ISSUE TITLE
Are Nested Relationships Possible?

### ISSUE THREAD

**Issue by robotman1053** [jinzhu/gorm#274]
I have a scenario were a "users" table has a one to many relationship with an "address" table, users can have more than one address. 

I have defined this like so:

```go
db.Model(&user).Related(&user.Addresses, "UserId")
```

However my "address" table also has a one to one relationship with a "state" table. My question is, how would you define the relationship between users->address->state so that all data could be gathered in a single query.

My current workaround has been to iterate over each address after running the above statement like so:

```go
for i,_ := range user.Addresses {
    db.Model(&user.Addresses[i]).Related(&user.Addresses[i].State, "StateId")
}
```  

However this would preform separate queries for each address which is messy. 

Thanks in advance!

**Comment by rtm7777** [comment]
Hi everyone, do we have any changes at the moment? We still can't use nested relations?
Thanks!

**Comment by jinzhu** [comment]
Hi All,

We have the eager loading feature already, checkout  https://github.com/jinzhu/gorm#preloading-eager-loading
