### ISSUE TITLE
Set("gorm:insert_option", "ON DUPLICATE KEY UPDATE") execute failed

### ISSUE THREAD

**Issue by hantmac** [jinzhu/gorm#2791]
### What version of Go are you using (`go version`)?
`go 1.13`

### Which database and its version are you using?
`mysql`

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
```
database.DB.Self.Set("gorm:insert_option", "ON DUPLICATE KEY UPDATE").
			Table(dm.TableName()).
			Create(&dm)
```
The log is :
```
[2019-12-04 11:06:35]  [232.30ms]  INSERT  INTO `domain_manage` (`domain_name`,`expire_date`,`refresh_date`,`type`) VALUES ('zmxuexi.com','2020-09-26','2019-12-04','domain') ON DUPLICATE KEY UPDATE  
[0 rows affected or returned ] 

(test.go:40) 
[2019-12-04 11:06:35]  Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 

```

**Comment by zaneli** [comment]
It's invalid SQL.
https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html

You must append update column and value.
```go
Set(
  "gorm:insert_option",
  fmt.Sprintf("ON DUPLICATE KEY UPDATE `expire_date` = '%s'", dm.ExpireDate),
)
```
and so on.
(Sorry, I have not really tried.)

**Comment by hantmac** [comment]
> It's invalid SQL.
> https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html
> 
> You must append update column and value.
> 
> ```go
> Set(
>   "gorm:insert_option",
>   fmt.Sprintf("ON DUPLICATE KEY UPDATE `expire_date` = '%s'", dm.ExpireDate),
> )
> ```
> 
> and so on.
> (Sorry, I have not really tried.)

Thanks for your reply and I will try and give a feedback.

**Comment by hantmac** [comment]
> It's invalid SQL.
> https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html
> 
> You must append update column and value.
> 
> ```go
> Set(
>   "gorm:insert_option",
>   fmt.Sprintf("ON DUPLICATE KEY UPDATE `expire_date` = '%s'", dm.ExpireDate),
> )
> ```
> 
> and so on.
> (Sorry, I have not really tried.)

It worked! Thank you!
