### ISSUE TITLE
[Question] Log of `db.LogMode(true)` is not same as real MySQL log one

### ISSUE THREAD

**Issue by momotaro98** [jinzhu/gorm#2792]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?

```
$ go version
go version go1.11.1 darwin/amd64
```

### Which database and its version are you using?

```
mysql> select version();
+------------+
| version()  |
+------------+
| 5.7.22-log |
+------------+
```

### Table schema and Go code with gorm

```table_definition.sql
CREATE TABLE `students` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `is_completed` tinyint(1) NOT NULL DEFAULT '0',
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4
```

```go
type Students struct {
       	ID          uint64     `gorm:"column:id;type:int unsigned;primary_key"`
	IsCompleted bool       `gorm:"column:is_completed;type:TINYINT(1)"`
}

func filteredIsCompleted(isCompleted bool) func(*gorm.DB) *gorm.DB {
	return func(tx *gorm.DB) *gorm.DB {
		return tx.Where(
			"is_completed = ?", isCompleted, // It's boolean in Go but tinyint in MySQL table column type
		)
	}
}
```

#### GORM LogMode(true) log result

```
[2019-12-05 08:26:19]  [1.30ms]  SELECT * FROM `students`  WHERE (id = '1') AND (is_completed = 'true')
[1 rows affected or returned ]
```

#### Real MySQL Logs

```
2019-12-05T08:26:19.266507Z        12 Prepare   SELECT * FROM `students`  WHERE (id = ?) AND (is_completed = ?)
2019-12-05T08:26:19.266627Z        12 Execute   SELECT * FROM `students`  WHERE (id = 1) AND (is_completed = 1)
gorm structure
```

### Question

I expect that GORM LogMode(true) log shows `SELECT * FROM `students`  WHERE (id = 1) AND (is_completed = 1)` as well as real MySQL log.

Does my request make sense to the GORM policy or not?

**Comment by zaneli** [comment]
> `id = '1'`

> `is_completed = 'true'`

It has been improved from the [v1.9.3](https://github.com/jinzhu/gorm/releases/tag/v1.9.3).　https://github.com/jinzhu/gorm/pull/2258

#### GORM LogMode(true) log result (v1.9.3~)
```sql
SELECT * FROM `students`  WHERE (id = 1) AND (is_completed = true)
```

`true` and `1` are probably treated as the same on MySQL tinyint(1) type.

**Comment by momotaro98** [comment]
Oh, I was using v1.9.2

```
[[projects]]
  name = "github.com/jinzhu/gorm"
  packages = ["."]
  pruneopts = "UT"
  revision = "472c70caa40267cb89fd8facb07fe6454b578626"
  version = "v1.9.2"
```

After I updated it succeeded to show well as #2258 did.
@zaneli thank you so much and I'm sorry for not showing gorm version.
