### ISSUE TITLE
New release to support projects using go modules

### ISSUE THREAD

**Issue by mrpound** [jinzhu/gorm#2793]
### What version of Go are you using (`go version`)?
1.12, 1.13

### Question
Is there an upcoming release planned that contains these ~33 commits made since the last release in September? [See comparison](https://github.com/jinzhu/gorm/compare/v1.9.11...master)

When using go modules, the current release (v1.9.11) which is pulled by go mod does not contain the latest commits to master, so our Docker builds are breaking because it's pulling that release which doesn't fixes in the aforementioned commits.

Is there a planned release upcoming so those of using go modules don't have to manually edit dependencies or deal with bugs that have been patched and merged into master since the last release? Thank you.

**Comment by vsimon** [comment]
+1 for a new release. 

In the meantime with go modules, it is possible to point to the commit hash or even "master" using `go get ...` within the go module project directory. Go modules will correctly update the dependency files (go.mod, go.sum) automatically to check-in to the repo.

Either of these would work:

`go get github.com/jinzhu/gorm@79a77d771dee`
(specific commit)

`go get github.com/jinzhu/gorm@master`
(latest master commit)
