### ISSUE TITLE
Permission denied on stored procedure is not returning error

### ISSUE THREAD

**Issue by bluebrown** [jinzhu/gorm#2815]
### Issue

This function should return an error as I don't have permission to execute the procedure. But there is no error

### What version of Go are you using (`go version`)?
go 1.13

require (
	github.com/gorilla/handlers v1.4.2
	github.com/gorilla/mux v1.7.3
	github.com/jinzhu/gorm v1.9.11
)

### Which database and its version are you using?
sql server 14.0.2027.2
 
### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
func (a *Controller) AddHistory(m model.History) (int64, error) {
	clone := a.db.Raw("Exec addHistorytoDecisions @tid=?, @his=?, @flag=?", m.TaskID, m.Entry, m.Close)
	if errs := clone.GetErrors(); len(errs) > 0 {
		return clone.RowsAffected, errs[0]
	}
	return clone.RowsAffected, nil
}
```

actual sql error from normal sql query:
```
Msg 229, Level 14, State 5, Procedure addHistorytoDecisions, Line 1
The EXECUTE permission was denied on the object 'addHistorytoDecisions', database 'Test', schema 'dbo'.

```

**Comment by zaneli** [comment]
> Raw use raw sql as conditions, won't run it unless invoked by other methods

https://github.com/jinzhu/gorm/blob/79a77d771dee4e4b60e9c543e8663bbc80466670/main.go#L492-L494

Probably you should use `a.db.Exec()`.

https://github.com/jinzhu/gorm/blob/79a77d771dee4e4b60e9c543e8663bbc80466670/main.go#L498-L499

By the way, `RowsAffected` maybe don't work using `Exec()`, always return 0.

(Sorry, I haven't actually tried it.)

**Comment by bluebrown** [comment]
Yes, I switched to exec. Rows affected seem to work for me on exec though.
