### ISSUE TITLE
table name with underline

### ISSUE THREAD

**Issue by zbml** [jinzhu/gorm#2816]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
1.13.1

### Which database and its version are you using?
postgres

I hava a struct like this

type AssetBrid struct {
	ID               int    `json:"id"`
	AssetID          int    `json:"asset_id"`
	BridCode       string `json:"brid_code"'`
	BridName       string `json:"brid_name"`
}

and I have a table  'asset_bird' in my database

I use find to query all the record from this table:

var brids []AssetBridge
err = db.Where(maps).Offset(pageNum).Limit(pageSize).Find(&brids).Error

I found that this stuct name(AssetBird) works fine. But I think the struct name should be Asset_Bird?

Then I changed the strcut name to Asset_Bird. I found it works too.

So I am confused. Can anyone tell me why?

**Comment by zaneli** [comment]
Default naming strategy append `_` before upper case character.
https://github.com/jinzhu/gorm/blob/79a77d771dee4e4b60e9c543e8663bbc80466670/naming.go#L71-L124

**Comment by zbml** [comment]
> Default naming strategy append `_` before upper case character.
> https://github.com/jinzhu/gorm/blob/79a77d771dee4e4b60e9c543e8663bbc80466670/naming.go#L71-L124

thanks
