### ISSUE TITLE
How to update all fields without adding

### ISSUE THREAD

**Issue by jinkun2014** [jinzhu/gorm#2819]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
1.12.9

### Which database and its version are you using?
1.9.11

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

Save (): update all fields if they exist, add them if they don't exist, is there a way to update all fields, and don't add them if they don't exist

**Comment by zaneli** [comment]
Probably you must do manually.

```go
if err := db.Where(&User{ID: user.ID}).First(&User{}).Error; err == nil {
  // run only if user record exists
  db.Save(&user)
}

```
