### ISSUE TITLE
gorm全局只用创建一个DB实例，在goroutine中不需要再实例化DB吗？是协程安全的是吗？

### ISSUE THREAD

**Issue by Jessppp** [jinzhu/gorm#2844]
不好意思,才开始使用gorm,问的问题比较初级...我比较关心上百个goroutine中的DB对象是否会存在污染的情况?是需要每个协程中独立创建DB实例还是就用全局的那个就OK？

**Comment by yuchanns** [comment]
https://github.com/jinzhu/gorm/blob/79a77d771dee4e4b60e9c543e8663bbc80466670/main.go#L839-L865
看一下源码便知，DB有个私有方法`clone`，每次你调用一个方法，它就会clone一个DB实例给你，比如`Where`：
https://github.com/jinzhu/gorm/blob/79a77d771dee4e4b60e9c543e8663bbc80466670/main.go#L234-L236
