### ISSUE TITLE
Can gorm reuse the reflect result for struct?

### ISSUE THREAD

**Issue by litgh** [jinzhu/gorm#285]
As I know, every operations will invoke NewScope(value), it means that `func (scope *Scope) Fields(noRelations ...bool) map[string]*Field ` can only reuse `scope.fields` in current scope.
can gorm support some func like `Register(struct)` that reflect result in every db operations can reuse,
 make it more effective

**Comment by GeertJohan** [comment]
This would definitely improve the benchmarks!

**Comment by jinzhu** [comment]
Hi @GeertJohan 

I am working on this already, hope could finish it soon.

**Comment by jinzhu** [comment]
Hi All,

Gorm is reusing reflect result now, this change really improved the performance, will keep improving it.
