### ISSUE TITLE
The Logger doesn't work on Google App Engine

### ISSUE THREAD

**Issue by pjebs** [jinzhu/gorm#288]
I discovered that the logger doesn't work on google app engine.
I'm not sure if you've used GAE before, but it is an amazing place to run go apps - but it contains a lot of restrictions including writing to the standard io.
This needs to be changed in your code.

You need to make your gorm library into a hybrid library so that it works on GAE and as a stand-alone binary: https://blog.golang.org/the-app-engine-sdk-and-workspaces-gopath
 

The solution is this:

1) Make two copies of logger.go  -> logger_gae.go  & logger_standalone.go
2) In logger_gae.go at the top put: // +build appengine
3) In logger_standalone.go at the top put: // +build !appengine
4) For logger_gae.go, add this line at the bottom of func (logger Logger) Print(v ...interface{}) {

		logger.Println(messages...)
		log.Printf("%+v", messages) //NEW LINE ADDED

**Comment by jinzhu** [comment]
Hello @pjebs 

I have re-read your code about the logger in GAE, I think gorm could support this with a customized logger, you could do it like this:

```go
db.SetLogger(log.New(os.Stderr, "", log.LstdFlags))
```

Please test it and let me know if it works, I will add it to the README then.

**Comment by benguild** [comment]
@jinzhu This does not work.

**Comment by benguild** [comment]
I've fixed this and will be posting code shortly.

**Comment by benguild** [comment]
Problem solved: https://github.com/benguild/GAEBridge

```
db.LogMode(true);
db.SetLogger(log.New(gaebridge.DebugLogWriter{ gaebridge.Context(r) }, "", log.LstdFlags));
```
