### ISSUE TITLE
Wrong default branch

### ISSUE THREAD

**Issue by FauconFan** [jinzhu/gorm#2899]
Hi @jinzhu 

I'm actively developing with gorm and my CI/CD pipeline fail because the default branch of the project have changed. It is now v2_dev. 
![Screenshot from 2020-02-25 15-28-14](https://user-images.githubusercontent.com/22058263/75256371-ab382e80-57e3-11ea-8315-4ea396819201.png)

Locally, it is still working cause go appears to leak the version of gorm to the branch i have started to develop it (simple git pull by go). But remotely when i'm downloading dependencies, my system fall down pathetically.

I think it's just a error. Can you change default branch please.

Note:
I have fixed my problem by creating a mod.go. 'go mod init'.
But i really think default branch should change

**Comment by renomarx** [comment]
Hi @jinzhu

Same problem here.

**Comment by Fyb3roptik** [comment]
@jinzhu This is affecting production environments that use CI/CD

**Comment by gregpmillr** [comment]
@jinzhu Having the same problem in our CI/CD pipeline. As a temporary workaround we've forked master to import.

**Comment by sebapintoag** [comment]
I have the same problem. My work team is having a lot of trouble right now...

**Comment by wizofaus** [comment]
Is there something we can change in the import line

_ "github.com/jinzhu/gorm/dialects/mssql"

To ensure it always uses a fixed branch/version?

**Comment by Fyb3roptik** [comment]
> Is there something we can change in the import line
> 
> _ "github.com/jinzhu/gorm/dialects/mssql"
> 
> To ensure it always uses a fixed branch/version?

You have to use go mods

**Comment by wizofaus** [comment]
Yeah I tried but can't find a version tag that works!

**Comment by Fyb3roptik** [comment]
https://github.com/jinzhu/gorm/releases/tag/v1.9.11

or just the master branch

**Comment by wizofaus** [comment]
Still no luck, guess we have to make quite a few changes to be able to use modules.  But weirdly it's building fine as is on my Mac Air, only failing on our (linux) ci build nodes.

**Comment by wizofaus** [comment]
Was able to get it building using modules which looks like a somewhat better way forward anyway, but rather more of a change that I would have liked to have made just to allow our software to keep building (I never liked having so many online dependencies)

**Comment by jinzhu** [comment]
Ooops, sorry for this, going to change the default branch back to master.

**Comment by jinzhu** [comment]
But suggest locking the version GORM in your application as we are going to release the new version soon.
