### ISSUE TITLE
SQL查询2020-02-01-2020-02-29 回跳过2020-02-29的数据

### ISSUE THREAD

**Issue by pengshaomin** [jinzhu/gorm#2916]
SQL查询2020-02-01-2020-02-29 返回数据集  无法得到2020-02-29号的数据，应该是驱动BUG

**Comment by Rohan-Liu** [comment]
假设你的语句是dt between ‘2020-02-01’ and ‘2020-02-29’ 那么实际等效于
dt between ‘2020-02-01 00:00:00’ and ‘2020-02-29 00:00:00’ 即不写分秒时默认是0点0分0秒
你需要更改为 dt between ‘2020-02-01’ and ‘2020-02-29 23:59:59.997’ 或 ‘2020-03-01’

**Comment by pengshaomin** [comment]
我们使用的查询是  dt >= ‘2020-02-01’ <= ‘2020-02-29 23:59:59.997’ 无法返回  2020-02-29 的数据
暂时使用了 dt >= ‘2020-02-01’ < ‘2020-03-01 00:00:00’ 来解决

**Comment by Rohan-Liu** [comment]
在数据库里执行查询语句能不能查询出来？用debug()查看查询语句，如果数据库里也查不出来那可能是数据库对时间区域设置可能不同。

**Comment by pengshaomin** [comment]
使用Debug SQL到数据库查询,是可以查询出来的
