### ISSUE TITLE
Object Mapper design/functionality?

### ISSUE THREAD

**Issue by bbros-dev** [jinzhu/gorm#2933]
Thank you for the effort you have put into this project and making it available as open source.

I'm new to Go and am looking for an Object Mapper library in Golang - I'm struggling to see past the sytax right now - hence this question. 
 
Essentially Object Mapper approach builds on the lessons learned from the AvtiveRecord and DataMapper patterns/conventions, as well as the implementation lessons from the like named projects.

Something with the design and functionality of [rom-rb](https://rom-rb.org/learn/).

Does your library a Object Mapper type functionality?  
If not would you kind enough to share the name of any OM libraries that your know of in Goland?

**Comment by monzarrugh** [comment]
It is an ORM, hence the name "GORM"

Migrating structs to database table: https://gorm.io/docs/migration.html
