### ISSUE TITLE
Scan() method can not reflect correct values to the struct when executing a `desc table_name` sql raw command.

### ISSUE THREAD

**Issue by bennya8** [jinzhu/gorm#2936]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.12.7 darwin/amd64

### Which database and its version are you using?
MariaDB / MySQL

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

reproduce way A

```
function main() {
	// get your db
	type Result struct {
		Field   string `json:"field"`
		Type    string `json:"type"`
		Null    string `json:"null"`
		Key     string `json:"key"`
		Default string `json:"default"`
		Extra   string `json:"extra"`
	}
	var results []Result
	var row Result

	rows, err := db.GetDb().Raw("desc user;").Rows()

	for rows.Next()  {
		rows.Scan(&row)
		results = append(results, row)
	}

	rows.Close()

	fmt.Println(results)
}
```

> [{     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     }]

reproduce way B

```
function main() {
	type Result struct {
		Field   string `json:"field"`
		Type    string `json:"type"`
		Null    string `json:"null"`
		Key     string `json:"key"`
		Default string `json:"default"`
		Extra   string `json:"extra"`
	}
	var results []Result
	db.GetDb().Raw("desc " + vTable + ";").Scan(&results)
	fmt.Println(results)
}
```

>  [{     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     } {     }]

still no luck...

**Comment by fwhezfwhez** [comment]
Usually Raw should specifc all sql , it's not advised to use raw style and orm style together.

db.Raw("select * from xxx where xxx=xxx", args...).Scan(&results)

**Comment by bennya8** [comment]
Finally, I got a simple solution, but I'm not sure it's the best way.

```
type Result struct {
    Field string `json:"field"`
    Type string `json:"type"`
    Collation string `json:"collation"`
    Null string `json:"null"`
    Key string `json:"key"`
    Default string `json:"default"`
    Extra string `json:"extra"`
    Privileges string `json:"privileges"`
    Comment string `json:"comment"`
}

var results[] Result
var row Result

rows, err: = db.GetDb().Raw("show full columns from " + vTable + ";").Rows()
if err != nil {
    log.Fatal(err)
}

for rows.Next() {
    rows.Scan(&row.Field, &row.Type, &row.Collation, &row.Null, &row.Key, &row.Default, &row.Extra, &row.Privileges, &row.Comment)
    results = append(results, row)
}
```

Somehow it works when specific each row manually.
