### ISSUE TITLE
How can i get the attributes that will been changed

### ISSUE THREAD

**Issue by mrhopelee** [jinzhu/gorm#2952]
I mean, I want to keep accurate records of the data that is about to change.
1. send to db with logger?
2. get dirty data on BeforeUpdate / AfterUpdate ?

**Comment by jinzhu** [comment]
no, can't support this without redefining all data types...

**Comment by System-Glitch** [comment]
Has it changed since GORM v2?

**Comment by jinzhu** [comment]
Yes, we added the ability to support it in some cases.

**Comment by System-Glitch** [comment]
I found the documentation for it: https://gorm.io/docs/update.html#Check-Field-has-changed
If that can help anyone.
