### ISSUE TITLE
请问能支持跨库操作吗？

### ISSUE THREAD

**Issue by iHDJ** [jinzhu/gorm#2959]
@jinzhu 坑爹甲方，user表放在User库，discover表放在discover库。要求分库管理数据。我想问下gorm能否支持跨库CRUD操作。目前我在文档上翻遍了都找不到及相关的介绍。

**Comment by iHDJ** [comment]
我是真tm想手刃了甲方

**Comment by jinzhu** [comment]
type User struct {
}

type (User) TableName() string {
  return "User.user"
}

type Discover struct {
}

func (Discover) TableName() string {
  return "discover.discover"
}
