### ISSUE TITLE
auto_increment 非主键列不生效

### ISSUE THREAD

**Issue by youmisun** [jinzhu/gorm#2964]
### What version of Go are you using (`go version`)?
go version go1.13.5 darwin/amd64
### Which database and its version are you using?
mysql5.7

```go
package main

import (
	"database/sql"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	"log"
	"time"
)

type User struct {
	gorm.Model
	Name         string
	Age          sql.NullInt64
	Birthday     *time.Time
	Email        string  `gorm:"type:varchar(100);unique_index"`
	Role         string  `gorm:"size:255"` // 设置字段大小为255
	MemberNumber *string `gorm:"unique;not null"` // 设置会员号（member number）唯一并且不为空
	Num          int     `gorm:"AUTO_INCREMENT"` // 设置 num 为自增类型
	Address      string  `gorm:"index:addr"` // 给address字段创建名为addr的索引
	IgnoreMe     int     `gorm:"-"` // 忽略本字段
}

func main() {
	db, err := gorm.Open("mysql", "root:@(127.0.0.1:3306)/test?charset=utf8&parseTime=True&loc=Local")
	if err != nil {
		log.Fatalln(err)
	}
	db.SingularTable(true)
	db.LogMode(true)
	err = db.DropTableIfExists(&User{}).Error
	if err != nil {
		log.Fatalln(err)
	}
	err = db.AutoMigrate(&User{}).Error
	if err != nil {
		log.Fatalln(err)
	}
}

```
![image](https://user-images.githubusercontent.com/17755936/78423608-f9b9d200-7699-11ea-9cce-8e903300d755.png)

就用了文档中的User模型，Num字段设置了auto_increment，但是不生效

**Comment by xpunch** [comment]
The auto_increment column must be part of the PRIMARY KEY or a UNIQUE KEY (and in almost 100% of the cases, it should be the only column that makes up the PRIMARY KEY)
(https://dev.mysql.com/doc/refman/8.0/en/example-auto-increment.html)
[https://dev.mysql.com/doc/refman/8.0/en/example-auto-increment.html]

**Comment by youmisun** [comment]
> The auto_increment column must be part of the PRIMARY KEY or a UNIQUE KEY (and in almost 100% of the cases, it should be the only column that makes up the PRIMARY KEY)
> https://dev.mysql.com/doc/refman/8.0/en/example-auto-increment.html
![QQ截图20200602100038](https://user-images.githubusercontent.com/17755936/83471762-1ca90c80-a4b8-11ea-85c0-25d9a4ad7a4f.png)
![QQ截图20200602100115](https://user-images.githubusercontent.com/17755936/83471765-203c9380-a4b8-11ea-970c-87769dc8cda9.png)
设置unique key也是不生效的

**Comment by xpunch** [comment]
I've test mysql dialect of gorm, I think this is a bug of gorm, field can be auto increment only when it's primay key.
```go
func (s *commonDialect) fieldCanAutoIncrement(field *StructField) bool {
	if value, ok := field.TagSettingsGet("AUTO_INCREMENT"); ok {
		return strings.ToLower(value) != "false"
	}
	return field.IsPrimaryKey
}
```
So even you defined "auto_increment" in the model, if it's not a primary key, gorm will ignore it.

**Comment by xpunch** [comment]
This sql works fine in mysql 8.
```sql
CREATE TABLE `users` (`id` int unsigned ,`name` varchar(255),`uid` int AUTO_INCREMENT UNIQUE, PRIMARY KEY (`id`));
```

**Comment by jinzhu** [comment]
![image](https://user-images.githubusercontent.com/6843/83590540-91e41280-a588-11ea-8a2d-bd04e17fbd18.png)

**Comment by xpunch** [comment]
@jinzhu If the field is Key, but not primary key, it still can auto_increment.
You can test it in mysql 5.6/5.7/8.
