### ISSUE TITLE
Is there any performance comparison available? 

### ISSUE THREAD

**Issue by thanzen** [jinzhu/gorm#298]
Are there any significant regression compared to raw sql(s) ?

**Comment by jinzhu** [comment]
Hi All,

I am working on improving the performance recently, the first step is cache generated reflect result, this really worked, I will keep working on the performance thing.

**Comment by zj8487** [comment]
@jinzhu 
is there any new data for performace test?

**Comment by cristian-sima** [comment]
Are there any improvements about the performance?

**Comment by BrunoQuaresma** [comment]
+1

**Comment by cpapidas** [comment]
+1

**Comment by cpapidas** [comment]
I think we can get some ideas from *sqlx*, it's really fast!

**Comment by ismailzakky** [comment]
+1

**Comment by Wulfheart** [comment]
+1
