### ISSUE TITLE
no data

### ISSUE THREAD

**Issue by liuyangsds** [jinzhu/gorm#2986]
package main

import (
	"fmt"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

type User struct {
	id int
	userddname string
	mobile string
	password string
	nickname string
}

func main()  {
	db,err := gorm.Open("mysql","root:liuyang@(localhost:3306)/goodgame?charset=utf8mb4&parseTime=True&loc=Local")
	if err != nil {
		fmt.Println(err)
	}
	defer db.Close()

	db.LogMode(true)

	db.SingularTable(true)

	var user User

	db.First(&user)
	fmt.Println(user)
}

![gorm1](https://user-images.githubusercontent.com/15158874/79758658-436c1300-8350-11ea-8a16-83203cbae4d3.png)
![mysql1](https://user-images.githubusercontent.com/15158874/79758681-48c95d80-8350-11ea-9c4b-41bd99fefd80.png)

**Comment by shbht** [comment]
Any update on this. I am also getting the same issue. I am using gorm version 1.9.12

**Comment by ap-in-git** [comment]
@liuyangsds  your table name should be users

**Comment by fishyww** [comment]
@liuyangsds Defining a struct pays attention to the case of the syntax
type User struct {
	Id int
	UserddName string
	Mobile string
	Password string
	Nickname string
}

**Comment by liuyangsds** [comment]
> @liuyangsds定义结构时要注意语法
> 类型User struct {
> Id int
> UserddName字符串
> 移动字符串
> 密码字符串
> 昵称字符串
> }

Thank you for the reminder

**Comment by liuyangsds** [comment]
> @liuyangsds Defining a struct pays attention to the case of the syntax
> type User struct {
> Id int
> UserddName string
> Mobile string
> Password string
> Nickname string
> }

Thank you for the reminder

**Comment by LonglyCode** [comment]
why reopened? any problem?
