### ISSUE TITLE
可以使用defer  tx.rollback()的方式吗？

### ISSUE THREAD

**Issue by birdycn** [jinzhu/gorm#3008]
```
tx:=db.begin()
defer tx.rollback()

if !conditionA{
return
}

tx.commit()
```

请问可以在事务函数中使用这样的方式吗？因为有时候判断条件有点多，每个条件都写
```
tx.rollback()
return;
```
的话有点繁琐，有时候也会忘了写，导致死锁。

请问使用上述的方式会不会产生什么问题，比如tx.commit之后tx.rollback会不会产生什么问题

**Comment by liuhao2050** [comment]
我经常defer，没觉得有什么问题

**Comment by liuhao2050** [comment]
https://gorm.io/docs/transactions.html#A-Specific-Example

**Comment by birdycn** [comment]
> https://gorm.io/docs/transactions.html#A-Specific-Example

@liuhao

```
func CreateAnimals(db *gorm.DB) error {
  // Note the use of tx as the database handle once you are within a transaction
  tx := db.Begin()
  defer tx.Rollback()

  if err := tx.Error; err != nil {
    return err
  }

  if err := tx.Create(&Animal{Name: "Giraffe"}).Error; err != nil {
     return err
  }

  if err := tx.Create(&Animal{Name: "Lion"}).Error; err != nil {
     return err
  }

  return tx.Commit().Error
}
```

出错的时候tx.rollback，如果判断语句多的话，有时候会忘了写，直接用这样的写法，会产生什么错误不？
无论是否tx.commit(),defer的时候都tx.rollback()

**Comment by liuhao2050** [comment]
不会
已经commit 之后 rollback 不会生效
没有commit 执行 rollback 会成功
另外，example也是这么写的，不放心你可以测试下

**Comment by birdycn** [comment]
好的谢谢

**Comment by liuhao2050** [comment]
直接rollback会报错，我觉得你可以加个 if err != nil 的判断更好一些
