### ISSUE TITLE
Association .Delete(), .Clear(), .Replace() don't modify the underlying struct or db

### ISSUE THREAD

**Issue by jnfeinstein** [jinzhu/gorm#301]
I saw this in code, and confirmed it with this test:
```go
func TestAssociationFunctionality(t *testing.T) {
	DB.DropTableIfExists(&Child{})
	DB.DropTableIfExists(&Toy{})
	DB.DropTableIfExists("children_toys")

	DB.AutoMigrate(&Child{})
	DB.AutoMigrate(&Toy{})

	child := Child{Name: "Tim"}
	toy := Toy{Name: "Ball"}
	DB..Save(&child)

	DB.Model(&child).Association("Toys").Append(&toy)
	if DB.Model(&child).Association("Toys").Count() != 1 {
		t.Errorf("Should have one toy in db")
	} else if len(child.Toys) != 1 {
		t.Errorf("Should have one toy in slice")
	}

	DB.Model(&child).Association("Toys").Delete(&child.Toys)
	if DB.Model(&child).Association("Toys").Count() != 0 {
		t.Errorf("Should have zero toys in db")
	} else if len(child.Toys) != 0 {
		t.Errorf("Should have zero toys in struct")
	}
}

// --- FAIL: TestAssociationFunctionality (0.01 seconds)
// 	 association_test.go:247: Should have zero toys in struct
```
It looks like other than `.Append()`, all they do is manipulate the join table.  `.Append()` will both manipulate the underlying struct and save the new records.  I think it would be better to have all these functions manipulate the struct and db, or none manipulate the struct and db, otherwise the API is confusing.  Preferably it would be all manipulate the struct such that the underlying struct is a representation of the database.

My guess is that since normal `.Delete()` doesn't clean up the join table, and pretty much all this is does is manipulate the join table, you probably built this to perform that specific functionality.

It would also be great if the association API was the preferred way of dealing with an association.  It's slick and I think makes more sense than `.Related()`.

**Comment by jnfeinstein** [comment]
I'd like it to manipulate the slice as well as the database.  It's already done for `.Append()` such that the slice will exactly match the database.  Continuing, for example, `.Delete()` could both delete all the entries from the database and leave you with an empty slice.  You can then assume that the slice correctly represents the state of the database, which could be useful to avoid roundtrips to the database.

I can code this up if you think this would be useful.

**Comment by nativematch** [comment]
Hi, 

Further to this, I think there is a bug in the "Replace" method which executes a delete for a blanket NOT IN based on a series of ids results in the tabled being cleared of all other related rows.

>> DELETE FROM children_toys  WHERE (children_toys."toy_id" NOT IN ($1,$2,$3,$4))

**Comment by jinzhu** [comment]
Hi @nativematch

Sorry for the problem, just pushed a commit to fix the issue.

Hi @jnfeinstein

Sorry, I have missed your comment, but seems like I have understood your question, and sure, it would be helpful if you code it up.

Thank you.

**Comment by jinzhu** [comment]
Hey @jnfeinstein

I have pushed a commit to do it like what you said. Please check it out.

Thank you for your suggestion.

**Comment by jnfeinstein** [comment]
Fantastic!  I will take a look. :+1:
