### ISSUE TITLE
grom 操作数据库的日志，输出到文件的时候没有进行格式化

### ISSUE THREAD

**Issue by 2017RXL** [jinzhu/gorm#3012]
var connectDbErr error
	MysqlDb, connectDbErr = gorm.Open("mysql", dbInfoInit())
	if connectDbErr != nil {
		panic(connectDbErr)
	}
	//去掉表名称后面自带s
	MysqlDb.SingularTable(true)
	//同步struct 到mysql
	MysqlDb.AutoMigrate(model.Person{})
	//MysqlDb.Debug()
	MysqlDb.DB().SetMaxIdleConns(10)
	MysqlDb.DB().SetMaxOpenConns(100)

	//开始数据库操作日志
	MysqlDb.LogMode(true)

	f, err := os.OpenFile("gormExecDb.log", os.O_RDWR|os.O_CREATE|os.O_APPEND, 0666)
	if err != nil {
		log.Fatalf("file open error : %v", err)
	}

	log := log.Logger{}
	log.SetOutput(f)
	log.SetPrefix(time.Now().Format("2006-01-02 15:04:05	"))
	log.SetFlags(0)
	MysqlDb.SetLogger(&log)

	LogRXL.Info("%s", "connect mysql success")
为什么不可以和beego log整合下?输出同一个文件中

**Comment by 2017RXL** [comment]
2020-05-08 23:40:31	sqlD:/Go/GOPATH/src/learnGo/gormLearn/main.go:1862.1724msINSERT INTO `person` (`person_name`,`person_age`,`person_create_user`,`create_date`) VALUES (?,?,?,?)[芮旭78乐 27 88888 2020-05-08 23:40:34.059767 +0800 CST m=+11.094433201] 1

文件中打印的数据库操作日志没有 格式 ，没有空格间隔开？

**Comment by aapelismith** [comment]
@2017RXL   
As long as the following interfaces are implemented, they can be used as logger
```
type logger interface {
    Print (v ... interface {})
}
```

examples:

```
type MyLogger struct{}

func (*MyLogger) Print(v ...interface{}) {
	// call your self logger
	logs.Info(v...)
}
...
func main(){
...
	orm.LogMode(true).SetLogger(&MyLogger{})
}
```

**Comment by 2017RXL** [comment]
Thank you. I have solved it. Thank you very much. I'm a Chinese programmer. How about you

> @2017RXL
> As long as the following interfaces are implemented, they can be used as logger
> 
> ```
> type logger interface {
>     Print (v ... interface {})
> }
> ```
> 
> examples:
> 
> ```
> type MyLogger struct{}
> 
> func (*MyLogger) Print(v ...interface{}) {
> 	// call your self logger
> 	logs.Info(v...)
> }
> ...
> func main(){
> ...
> 	orm.LogMode(true).SetLogger(&MyLogger{})
> }
> ```

Thank you. I have solved it. Thank you very much. I'm a Chinese programmer. How about you

**Comment by 2017RXL** [comment]
谢谢 你们

**Comment by aapelismith** [comment]
@2017RXL  me too😄
