### ISSUE TITLE
gorm中如何获取sql语句

### ISSUE THREAD

**Issue by javaLx** [jinzhu/gorm#3013]
找了一遍官网的文档貌似没有看到有获取sql的方法  请问在gorm中应该如何去获取sql语句 就是设置了条件后的db最后执行的语句  而不是控制台的方式打印

**Comment by sdghchj** [comment]
不行

**Comment by fishyww** [comment]
> 找了一遍官网的文档貌似没有看到有获取sql的方法 请问在gorm中应该如何去获取sql语句 就是设置了条件后的db最后执行的语句 而不是控制台的方式打印

源码没有实现获取sql语句的方法，可以打断点 Debug 就可以看到了最后执行语句了
![image](https://user-images.githubusercontent.com/51019225/81782459-67c0a700-952c-11ea-91d5-d302bfbedeb0.png)

**Comment by javaLx** [comment]
已经用原生sql解决了 谢谢各位

**Comment by sdghchj** [comment]
> > 找了一遍官网的文档貌似没有看到有获取sql的方法 请问在gorm中应该如何去获取sql语句 就是设置了条件后的db最后执行的语句 而不是控制台的方式打印
> 
> 源码没有实现获取sql语句的方法，可以打断点 Debug 就可以看到了最后执行语句了
> ![image](https://user-images.githubusercontent.com/51019225/81782459-67c0a700-952c-11ea-91d5-d302bfbedeb0.png)

你这个还是在gorm层，驱动本身也是支持sql语句带参数的方式的，所以对于带参数的方式，你看到的scope里的sql语句也不是完整的。
