### ISSUE TITLE
Is this project deprecated?

### ISSUE THREAD

**Issue by jalock** [jinzhu/gorm#3015]
So many issues were opened, but none of them got any replies or discussions from the contributors or community members.

I'm looking for a mature ORM for my Go projects, and found this famous library. Can anyone else see this thread and let me know if there's any better choice? Thanks a lot!

**Comment by fr3fou** [comment]
v2 is in the workings right now, so there haven't been any updates to v1 #2886

**Comment by jalock** [comment]
> v2 is in the workings right now, so there haven't been any updates to v1 #2886

It's strange! Apart from the bugs/feature requests, questions are all ignored too! 👎
