### ISSUE TITLE
Nested preload didn't work !

### ISSUE THREAD

**Issue by Wiidz** [jinzhu/gorm#3018]
### What version of Go are you using (`go version`)?
1.13

### Which database and its version are you using?
mysql

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**
People have their own coat,and each coat has a brand.
Now I‘m trying to select them.

```go
type Brand struct {
      ID int `gorm:"primary_key;column:id;type:int(11);not null" json:"-"`
      Name string `gorm:"name;type:varchar(20)" json:"name"`
}

type Coat struct {
      ID int `gorm:"primary_key;column:id;type:int(11);not null" json:"-"`
      BrandID int `gorm:"column:brand_id;type:int(11)" json:"brand_id"`
      Brand Brand `gorm:"foreignkey:BrandID"  json:"brand"`
}

type People struct {
      ID int `gorm:"primary_key;column:id;type:int(11);not null" json:"-"`
      CoatID Shoe `gorm:"column:coat_id;type:int(11)" json:"coat_id"`
      Coat Coat `gorm:"foreignkey:CoatID"  json:"coat"`
}


func test(){
...
	var rows []People
	err := db.Debug().Preload("Coat").Preload("Coat.Brand").Find(&rows).Error
	return rows, err
...
}
```

And I only saw the people table and the coat table been selected,the brand table didn't.

When I wrote a wrong code , like 
Preload("Coat.Material")
I would got a debug info, it showed that can not preload Material field

**Comment by bombsimon** [comment]
I'm not sure if your example is actually running but it won't compile in the current state. I'm not sure why you've set `CoatID` to be a `Shoe` but since it's a foreign key to be used to find references it would have to be the same type as the ID field. Also I don't think this is the issue but it seems like specifying the column ID for ID fields, as well as `NOT NULL` makes `gorm` not creating those as auto increment. I don't know if you use `gorm` for your migrations but if you do this might be an issue.

Here's a working minimum viable example to show the nested preloading wokring:

```go
package main

import (
	"fmt"

	"github.com/davecgh/go-spew/spew"
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

type Brand struct {
	ID   int    `gorm:"primary_key"`
	Name string `gorm:"name;type:varchar(20)"`
}

type Coat struct {
	ID      int `gorm:"primary_key"`
	BrandID int `gorm:"type:int(11)"`
	Model   string
	Brand   Brand `gorm:"foreignkey:BrandID"`
}

type People struct {
	ID     int `gorm:"primary_key"`
	Name   string
	CoatID int  `gorm:"type:int(11)"`
	Coat   Coat `gorm:"foreignkey:CoatID"`
}

func main() {
	// docker run -it --rm -p 3306:3306 -e MYSQL_ROOT_PASSWORD=abc mysql:latest
	db, _ := gorm.Open(
		"mysql",
		"root:abc@tcp(localhost:3306)/test",
	)

	defer db.Close()

	setupTables(db)
	populateTables(db)

	var rows []People

	db.Preload("Coat").
		Preload("Coat.Brand").
		Find(&rows)

	spew.Dump(rows)
}

func setupTables(db *gorm.DB) {
	for _, tbl := range []string{"peoples", "coats", "brands"} {
		db.Exec(fmt.Sprintf("DROP TABLE IF EXISTS %s", tbl))
	}

	db.AutoMigrate(&Brand{})

	db.AutoMigrate(&Coat{}).
		AddForeignKey("brand_id", "brands(id)", "CASCADE", "CASCADE")

	db.AutoMigrate(&People{}).
		AddForeignKey("coat_id", "coats(id)", "CASCADE", "CASCADE")
}

func populateTables(db *gorm.DB) {
	db.Create(&People{
		Name: "Gorm",
		Coat: Coat{
			Model: "Long",
			Brand: Brand{
				Name: "Nike",
			},
		},
	})
}
```

This will dump the following result, including the preloaded coat (showing the type `Long`) and the preloaded brand for that coat (showing the name `Nike`).

```text
([]main.People) (len=1 cap=1) {
 (main.People) {
  ID: (int) 1,
  Name: (string) (len=4) "Gorm",
  CoatID: (int) 1,
  Coat: (main.Coat) {
   ID: (int) 1,
   BrandID: (int) 1,
   Model: (string) (len=4) "Long",
   Brand: (main.Brand) {
    ID: (int) 1,
    Name: (string) (len=4) "Nike"
   }
  }
 }
}
```

**Comment by Wiidz** [comment]
> I'm not sure if your example is actually running but it won't compile in the current state...
> ```

Thx a lot gentle !
I just wrote wrong here with **Shoe** , actually it's **int**.
That's a mistake.

Today my code works correct ! 
It seems I used chinese sysmble **：** instead of **:** in my project.

As you said  **the same type as the ID field** , i do had this fault in my real project.
But it seems didn't cause bug (I didn't use **ForeignKey reference** in my sql design).
It can also select out rows by preloading.
