### ISSUE TITLE
循环外定义接收的变量，循环内重复接收的时候变量值不变

### ISSUE THREAD

**Issue by 00LT00** [jinzhu/gorm#3020]
这种写法从第二个开始就多了一个id的判断，导致我循环过程中获取的所有变量都是同一个
```go
project:=new(Project)
for _,v:=range(pju) {
	s.DB.Where(&Project{ProjectID:v.ProjectID}).Find(project)
	result.ProjectList = append(result.ProjectList,project)
}
```
放到外面定义就不会了
```go
for _,v:=range(pju) {
	project:=new(Project)
	s.DB.Where(&Project{ProjectID:v.ProjectID}).Find(project)
	result.ProjectList = append(result.ProjectList,project)
}
```
这是gorm的特性还是？我不懂为什么要这么设计

**Comment by 00LT00** [comment]
说错了，是放到里面就不会有问题了

**Comment by The-Phantom-Of-The-Opera** [comment]
跟gorm没关系，你在外面new分配一块内存返回project指针，你的result数组里指针指向的就是同一块内存， 你在里面每次循环新分配一块内存返回指针，最后数组里的指针就是指向不同的内存。

**Comment by 00LT00** [comment]
> 跟gorm没关系，你在外面new分配一块内存返回project指针，你的result数组里指针指向的就是同一块内存， 你在里面每次循环新分配一块内存返回指针，最后数组里的指针就是指向不同的内存。

意思是说我list这个切片实际上添加了好多个同一个地址的指针，所以改一个就会全部改，然后gorm出于某种保护机制，就限制了我在循环中只能获取第一个值以此来保护切片不受影响？

**Comment by The-Phantom-Of-The-Opera** [comment]
> > 跟gorm没关系，你在外面new分配一块内存返回project指针，你的result数组里指针指向的就是同一块内存， 你在里面每次循环新分配一块内存返回指针，最后数组里的指针就是指向不同的内存。
> 
> 意思是说我list这个切片实际上添加了好多个同一个地址的指针，所以改一个就会全部改，然后gorm出于某种保护机制，就限制了我在循环中只能获取第一个值以此来保护切片不受影响？

所以和gorm有什么关系，gorm只是把查出的数据放进你的project指针指向的内存呀:)。你的result.ProjectList是[]*Project吧，你把他换成值slice而不是指针slice就好了。

**Comment by 00LT00** [comment]
> > > 跟gorm没关系，你在外面new分配一块内存返回project指针，你的result数组里指针指向的就是同一块内存， 你在里面每次循环新分配一块内存返回指针，最后数组里的指针就是指向不同的内存。
> > 
> > 
> > 意思是说我list这个切片实际上添加了好多个同一个地址的指针，所以改一个就会全部改，然后gorm出于某种保护机制，就限制了我在循环中只能获取第一个值以此来保护切片不受影响？
> 
> 所以和gorm有什么关系，gorm只是把查出的数据放进你的project指针指向的内存呀:)。你的result.ProjectList是[]*Project吧，你把他换成值slice而不是指针slice就好了。

有的有的，我开了debug模式，第一个sql语句正常的，第二个开始就有问题了，他会多加一个where条件，判断id是不是等于第一条的那个id，就导致我后面几条语句查出来的RowsAffected直接就是0，不会更改结果，始终是第一条，最后的list里面也全都是第一条，如果单单只是slice指针的问题的话，结果应该全部都是遍历的最后一条，因为每次遍历按道理都会更改数据的

**Comment by The-Phantom-Of-The-Opera** [comment]
@00LT00 
`func (s *DB) Find(out interface{}, where ...interface{}) *DB {
	return s.NewScope(out).inlineCondition(where...).callCallbacks(s.parent.callbacks.queries).db
}`
`func (s *DB) NewScope(value interface{}) *Scope {
	dbClone := s.clone()
	dbClone.Value = value
	scope := &Scope{db: dbClone, Value: value}
	if s.search != nil {
		scope.Search = s.search.clone()
	} else {
		scope.Search = &search{}
	}
	return scope
}`
上面是源码，Find执行的时候根据提供的指针new一个scope，多次用同一个指针的话旧查询的一些属性可能被带了过去。

**Comment by 00LT00** [comment]
@The-Phantom-Of-The-Opera 
好的好的，炒鸡感谢
