### ISSUE TITLE
Scope.SetColumn logic error(gorm@v1.9.12)

### ISSUE THREAD

**Issue by MedusaLeee** [jinzhu/gorm#3026]
Your issue may already be reported! Please search on the [issue track](https://github.com/jinzhu/gorm/issues) before creating one.

### What version of Go are you using (`go version`)?
go version go1.13 darwin/amd64
gorm@v1.9.12
### Which database and its version are you using?
postgresql 10

### Please provide a complete runnable program to reproduce your issue. **IMPORTANT**

The model has nickname and name field，and use scope.SetColumn("nickname", "name") in beforeUpdate hook, gorm will add the name field to  gorm `updateAttrs` in gorm `Scope.SetColumn ` func source code. I find the logic code:

![image](https://user-images.githubusercontent.com/17797874/82781362-30d38500-9e8c-11ea-9dd4-45b5e47160ce.png)

![image](https://user-images.githubusercontent.com/17797874/82781401-45178200-9e8c-11ea-9800-84aef3ceb8d6.png)

![image](https://user-images.githubusercontent.com/17797874/82781414-506aad80-9e8c-11ea-8d41-48e7f956844e.png)

Is right logic is like the following picture?

![image](https://user-images.githubusercontent.com/17797874/82782658-6ded4680-9e8f-11ea-8be7-a0fd06b4283e.png)

Need to runnable with [GORM's docker compose config](https://github.com/jinzhu/gorm/blob/master/docker-compose.yml) or please provides your config.

```go
please see picture
```

**Comment by jinzhu** [comment]
Removed the SetColumn in v2, most people feel confused when using it....

You can just set field's value, and it will be updated in v2.
