### ISSUE TITLE
Syntax error on dropTableIfExists with SQL Server

### ISSUE THREAD

**Issue by kiwih** [jinzhu/gorm#310]
When using dropTableIfExists() connected to Microsoft SQL Server with go-mssqldb library, mssql returns "Incorrect Syntax near the keyword 'IF'."

The function seems to use the syntax "DROP TABLE IF EXISTS %v", which is the MySQL syntax, but I don't believe that this is the ANSI standard.

**Comment by jinzhu** [comment]
Hi @kiwih

Sorry for the problem, this should be fixed now.

Thank you for your report.
