### ISSUE TITLE
Many2many is giving null?

### ISSUE THREAD

**Issue by milanvanschaik** [jinzhu/gorm#315]
I've a many to many defined like this:
```
Publishers []Publisher `json:"publishers" gorm:"many2many:book_publisher;"`
```

I want Publishers to become an array with the publishers.
What happens is that Publishers stays/is null. Am I doing something wrong or isn't this feature available (yet) and is the tag only creating the join table?

**Comment by sebastiandeutsch** [comment]
I have the same issue - this is my struct:

    type Bookmark struct {
      Id          int64
      Url         string
      Title       string
      Description string
      UserId      int64

      CreatedAt time.Time
      UpdatedAt time.Time

      Tags []Tag `gorm:"many2many:tag_bookmarks;"`
    }

and tags

    type Tag struct {
      Id   int64
      Name string

      CreatedAt time.Time
      UpdatedAt time.Time

      Bookmarks []Bookmark `gorm:"many2many:tag_bookmarks;"`
    }

when I get the bookmarks and tranform them to JSON then the 'tags' attributes are null.

    var bookmarks []models.Bookmark
    db.Order("created_at desc").Find(&bookmarks)
    b, err := json.Marshal(bookmarks)

I guess it's normal since how does the json encoder know how to call

    db.Model(&bookmark).Related(&tags, "Tags")

Any idea how to do this?

**Comment by sebastiandeutsch** [comment]
I found a solution to "enrich" the original bookmarks collection:

    var bookmarks []models.Bookmark
    controller.Database.Connection.Order("created_at desc").Find(&bookmarks)
    for index, _ := range bookmarks {
      var tags []models.Tag
      controller.Database.Connection.Model(&bookmarks[index]).Related(&tags, "Tags")
      bookmarks[index].Tags = tags
    }

Still an idea how to improve this?

**Comment by jinzhu** [comment]
@sebastiandeutsch Maybe you could find all Tags first, then map the bookmarks and assign the related tags to it? (to kill the N+1 queries)

For this issue, I think I can't do much in the gorm side for now, you have to handle it in your code.

But anyway, please let me know if you have any suggestions.

**Comment by jinzhu** [comment]
Or maybe gorm could support this?

```go
controller.Database.Connection.Include("Tags").Find(&bookmarks)
```

Then it will auto fill related tags for bookmarks?

**Comment by milanvanschaik** [comment]
That would be great!

**Comment by sebastiandeutsch** [comment]
Great idea! I would also love to see such a feature.

**Comment by DimShadoWWW** [comment]
Is this open or close ? the Include API is already included?

**Comment by jinzhu** [comment]
@DimShadoWWW this is not included, but there is a similar ticket about this. I will look into it recently.
