### ISSUE TITLE
UUID primary key auto generate in PostgreSQL - 9.3.5 (pq)

### ISSUE THREAD

**Issue by ferhatelmas** [jinzhu/gorm#320]
``` go
type User struct {
	Id                 uuid.UUID `sql:"type:uuid;default:uuid_generate_v4()"`
	Password           []byte
	Email              string
	FirstName          string
	LastName           string
}
```

Generates this SQL (edited for legibility):

```sql
CREATE TABLE "users" (
  "id" uuid,
  "password" bytea,
  "email" varchar(255),
  "first_name" varchar(255),
  "last_name" varchar(255)
)
```

As seen, there is nothing about default value of `id`

How should I define struct for auto generation of `Id`. Thanks!

PS: Extension is created for the following db and it's working on the shell.

**Comment by jinzhu** [comment]
@ferhatelmas 

Fixed, thank you for your report!

**Comment by HangingClowns** [comment]
Not sure how this is supposed to work? But seems auto generation of uuid doesn't work.

**Comment by EwanValentine** [comment]
Yeah I can't get this to work either :/
