### ISSUE TITLE
Existing Schema retriveing One to Many from Legacy Database

### ISSUE THREAD

**Issue by ikennaokpala** [jinzhu/gorm#321]
HI guys,

I am struggling with associating two entities with golang's [gorm][1] library.

I am practicing with an old wordpress db i have attached the ERD to this thread.

I have defined a Post and an Author model, but i can't seem to figure out the right combination for associating them. 

Currently i return the post without any authors.. they are return as am empty object.

My definition is as follows. 

    // Author model
    type Author struct {
    	Id       int64  `gorm:"column:ID;primary_key:yes"json:"id"`
    	Name     string `gorm:"column:display_name"json:"name"`
    	NickName string `gorm:"column:user_nicename"json:"nickname"`
    	Email    string `gorm:"column:user_email"json:"email"`
    	URL      string `gorm:"column:user_url"json:"url"`
    	Post     []Post `gorm:"foreignkey:post_author;"json:"-"`
    }
    
    // TableName Method
    func (a Author) TableName() string {
    	return "wp_users"
    }
    
    
    package models
    
    // Post model
    type Post struct {
    	Id            int64        `gorm:"column:ID; primary_key:yes"json:"id"`
    	Type          string       `gorm:"column:post_type"json:"type"`
    	Slug          string       `gorm:"column:post_name"json:"slug"`
    	URL           string       `gorm:"column:guid"json:"url"`
    	Status        string       `gorm:"column:post_status"json:"status"`
    	Title         string       `gorm:"column:post_title"json:"title"`
    	Content       string       `gorm:"column:post_content"json:"content"`
    	Excerpt       string       `gorm:"column:post_excerpt"json:"excerpt"`
    	Date          string       `gorm:"column:post_date"json:"created_at"`
    	Modified      string       `gorm:"column:post_modified"json:"modified_at"`
    	Categories    []Category   `json:"categories"`
    	Tags          []Tag        `json:"tags"`
    	Author        Author       `gorm:"foreignkey:ID;"json:"author"`
    	Comments      []Comment    `json:"comments"`
    	Attachments   []Attachment `json:"attachments"`
    	CommentCount  string       `gorm:"column:comment_count"json:"comment_count"`
    	CommentStatus string       `gorm:"column:comment_status"json:"comment_status"`
    	Thumbnail     string       `sql:"-"json:"-"`
    	CustomFields  string       `sql:"-"json:"-"`
    }
    
    // TableName Method
    func (p Post) TableName() string {
    	return "wp_posts"
    }

Thanks

See WP ERD diagram here http://i.stack.imgur.com/LF0fR.png

  [1]: https://github.com/jinzhu/gorm

**Comment by jinzhu** [comment]
Hello @ikennaokpala 

Gorm won't query relations but you need to query it by yourself with

```go
db.Model(&post).Related(&post.Comments)
```

**Comment by ikennaokpala** [comment]
I tried it and it did not add the comments to the results that was returned.

**Comment by jinzhu** [comment]
Please checkout https://github.com/jinzhu/gorm#preloading-eager-loading to see if it could resolve your issue, please reopen it if it still doesn't work.

**Comment by ikennaokpala** [comment]
Thanks i will check it out..

On Wed, Feb 11, 2015 at 11:52 AM, Jinzhu <notifications@github.com> wrote:

> Closed #321 <https://github.com/jinzhu/gorm/issues/321>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jinzhu/gorm/issues/321#event-233869208>.
>



-- 
Ikenna
