### ISSUE TITLE
Disable Callbacks

### ISSUE THREAD

**Issue by jsimnz** [jinzhu/gorm#323]
I can't seem to find it, but is it possible to disable callbacks for a given query.

If not, it would just act as a modifier to the request to instruct it to not call any of the found callbacks for a model.

**Comment by jinzhu** [comment]
Hello @jsimnz 

This sounds like you need a callback to do this, I have write a sample one, you could extend it for your use case. 

```
func GetRelatedResult(scope *Scope) {
	var results = scope.IndirectValue()
	if results.Type() == reflect.TypeOf(&[]User) {
		// get user ids
		// get emails with all user ids
		for _, email := range emails {
			for _, user := range users {
				if user.Id == email.UserId {
					user.Email = email
				}
			}
		}
	}
}

db.Callback().Query().After("gorm:query").Register("get_related_result", GetRelatedResult)
```
