### ISSUE TITLE
Call RecordNotFound() when value isn't of right type

### ISSUE THREAD

**Issue by milanvanschaik** [jinzhu/gorm#324]
When I'm trying to getting by id like this:
`db.First(&user, id).RecordNotFound()`
and id isn't an integer and the record is not found, it doesn't call RecordNotFound().
I'd expect that RecordNotFound() was called since the record is not found. I think it's because of the value isn't of the right type.

**Comment by jinzhu** [comment]
Hello @milanvanschaik 

Based on the implementation, it shouldn't works like this. it should works for all cases that can't find a struct.

Could you give me sample code that could explain your issue? 

Thank you.

```go
package main

import (
    _ "github.com/go-sql-driver/mysql"
    "github.com/jinzhu/gorm"
    _ "github.com/lib/pq"
    _ "github.com/mattn/go-sqlite3"
)

var db gorm.DB

func init() {
    var err error
    db, err = gorm.Open("sqlite3", "test.db")
    // db, err := gorm.Open("postgres", "user=username dbname=password sslmode=disable")
    // db, err := gorm.Open("mysql", "user:password@/dbname?charset=utf8&parseTime=True")
    if err != nil {
        panic(err)
    }
    db.LogMode(true)
}

func main() {
    // Your code
}
```

**Comment by jinzhu** [comment]
Hello @milanvanschaik 

Does this issue still happen to you, if it does, feel free to reopen it

Thank you.
