### ISSUE TITLE
Update record that no longer exists does not fail in error. Should it?

### ISSUE THREAD

**Issue by bramp** [jinzhu/gorm#330]
I don't know if this should be considered an issue or not. Consider the following

```go
db.First(&user)
db.Delete(&user)
db.Save(&user)
//// UPDATE users SET name='jinzhu 2', age=100, updated_at = '2013-11-17 21:34:10' WHERE id=111;
```

The save will run the update, but updates zero rows. I might expect a Error to be returned saying "Expected to update one row, but none found", or similar.

For the moment I am checking RowsAffected, to ensure that one, and only one row is updated.

Comparing this to Hibernate, I believe Hibernate would throw a StaleStateException

**Comment by jinzhu** [comment]
Hello @bramp

Could you let me know your case to update a delete record? how it happened?

**Comment by bramp** [comment]
In my case it was a race. Another user deleted the row while I was in the
middle of updating. I just simplified it for this issue.

**Comment by jinzhu** [comment]
Thank you for your feedback, I will add a error message if nothing saved when trying to save a single object.

**Comment by jinzhu** [comment]
Hello @bramp 

Just for your information, I am not going to add the error message in this case, maybe better to keep checking the `RowsAffected`

Seems like the error message is not really necessary, and even database don't treat this as an error, so not going to add this, it usually easier to add a feature, but hard to remove them in the future then.
