### ISSUE TITLE
NewRecord or not shouldn't be depend on primary key `Id` is blank or not

### ISSUE THREAD

**Issue by sunfmin** [jinzhu/gorm#333]
```
// returns true if record hasn’t been saved (primary key `Id` is blank)
db.NewRecord(user) // => true

```

If I use my own key generator to set primary key, I probably first set the Id value and then save it to db. But the db.NewRecord didn't return correct value.

**Comment by jinzhu** [comment]
You may want to set the id value in the before create callback?

Or if you set it in other place, you should already know the record is a new record?
