### ISSUE TITLE
.Delete(&model) delete all items when it empty.

### ISSUE THREAD

**Issue by dorajistyle** [jinzhu/gorm#334]
I think that gorm is beautiful ORM for golang.
However Delete function is confusing.

type Role struct{
	//    Role model
	Id            int64  `json:"id"`
	Name          string  `json:"name",sql:"size:255"`
	Description   string  `json:"description",sql:"size:255"`
}
var role Role
db.First(&role, 11) // id 11 is not exist.
fmt.Printf("role id : %d", role.Id) // It print that Id is 0.
db.ORM.Delete(&role) // It delete whole roles.

I temporally prevent this like below:
if role.Id > 0 {
db.ORM.Delete(&role)
}

Any suggestion?

**Comment by jinzhu** [comment]
Hello @dorajistyle

yes, this is excepted behaviour, the Delete function will use the value to search and delete all matched records.

For your case, you could delete it like this:

```go
db.ORM.Delete(&Role{}, 11)
```
OR 
```go
if !db.First(&role, 11).RecordNotFound() {
  db.ORM.Delete(&role) // It delete whole roles.
}
```

**Comment by dorajistyle** [comment]
Thank you for the response.
