### ISSUE TITLE
How to get the primary key id of the new inserted object?

### ISSUE THREAD

**Issue by dubiao** [jinzhu/gorm#337]
`c.Txn.Table("group_info").Save(&newGroup)`

I saved a new object this way, but newGroup.Id value which the primary key is still 0 after calling.
I need the Id value of it and return it. How could I get that?

**Comment by jinzhu** [comment]
If should not be 0, but should has the real primary key.

Could you send me a sample code that could reproduce the issue?

**Comment by dubiao** [comment]
This is the data struct define

```
type GroupData struct {
	Id   int64  `gorm:"column:Fid; primary_key:yes" json:"id" `
	Name string `gorm:"column:Fname" json:"name"`
}
```
Here I create one and save:
```
newGroup := GroupData{Name: "aabbaa"}
c.Txn.Table("group_info").Create(&newGroup) // OR Save(&newGroup)
```
This can insert a row successfully. Then, I call
```
RenderJson(...)
```
And got this:
```
{
    id: 0,
    name: "aabbaa"
}
```

Do you need other infomation? @jinzhu

**Comment by dubiao** [comment]
Hi, @jinzhu 
I found that in `func (scope *Scope) SetColumn` function, 
after `dbName := ToSnake(str)` , dbName is "fid"
but `scope.Fields()` returns a map that the key is Fid.
so this function finally returned an error.

but i cant rename my thousands of columns from Fxxx to fxxx.

I want to modify the `ToSnake` func to return Fid so that can work. Is there any risk of doing this?
or I should make the map's key to lowercase which scope.Fields() returned ?

**Comment by jinzhu** [comment]
Hello @dubiao 

Sorry for the problem, just pushed a commit to fix the issue.

**Comment by seriallink** [comment]
Hi, @jinzhu. 

Did you fix this issue? Because I have the same problem here.

My struct has its pk changed to 0 (int) or "\x00" (string) after calling the method Create.

In both cases I'm not using auto generation of id.

**Comment by bubenkoff** [comment]
@jinzhu issue is still actual, primary key is not set on save, and no other ways to get last inserted id either

**Comment by bubenkoff** [comment]
@jinzhu sorry my bad, it's working fine
