### ISSUE TITLE
Association().Delete() delete whole association without Model's Id.

### ISSUE THREAD

**Issue by dorajistyle** [jinzhu/gorm#341]
userId := 3
    roleId := 13
    var user model.User
    var role model.Role
    db.First(&user, userId)
    db.First(&role, roleId)

     //FIRST SQL : DELETE FROM users_roles  WHERE users_roles.`role_id` IN ('13')
    db.Model(&user).Association("Roles").Delete(role)  // Q1
      
    // SECOND SQL: DELETE FROM users_roles  WHERE user_id = '3' AND users_roles.`role_id` IN ('13')
    db.Model(&user).Where("user_id = ?", userId).Association("Roles").Delete(role) // Q2

I've expected second query from the Q1.
Even so it's not recognize user's Id. It's confusing.
Q2 works. Nevertheless looks no good.

**Comment by jinzhu** [comment]
Hi @dorajistyle

Sorry for the problem, just pushed a commit to fix the issue.
