### ISSUE TITLE
Don't gorm physical delete when struct has DeletedAt field and you use Unscoped?

### ISSUE THREAD

**Issue by uzimith** [jinzhu/gorm#342]
When a struct has `DeletedAt` field, I thought gorm works as follows.
```go
db.Unscoped().Where("age = ?", 20).Delete(&User{})
////DELETE from users where age = 20;
```

However, gorm actually works as follows.

```go
db.Unscoped().Where("age = ?", 20).Delete(&User{})
//// UPDATE users SET deleted_at="2013-10-29 10:23" WHERE age = 20;
```

Is this an expected behavior?

**Comment by enmand** [comment]
Hi uzimith,

Yes, this is expected behaviour that takes advantage of Gorm's "[Soft Delete](https://github.com/jinzhu/gorm#soft-delete)" feature. Records that have been soft-deleted are ignored when Gorm queries for related records.

You can use `Unscoped` to hard-delete a record, instead of soft-deleting it.

**Comment by uzimith** [comment]
Thank you, enmand.

> You can use Unscoped to hard-delete a record, instead of soft-deleting it.

Does this mean I should use as follows?

```
db.Unscoped().Delete(&order)
//// DELETE FROM orders WHERE id=10;
```

OK, I understood it.

However, I'm wondering if gorm doesn't have batch hard delete.

**Comment by jinzhu** [comment]
Hi @uzimith 

this is hard batch delete?

```go
db.Unscoped().Where("age = ?", 20).Delete(&User{})
////DELETE from users where age = 20;
```

**Comment by uzimith** [comment]
Hi jinzhu,

I tried writing simple sample code and it worked well.
I might misunderstand a behavior. Sorry.

**Comment by Asad-noor** [comment]
How to get back that value I mean how to the field DeletedAt to null again?

**Comment by hongsenliu** [comment]
@Asad-noor I faced the same question, and I found a solution that is using SetColumn in BeforeUpdate/BeforeSave callback.
