### ISSUE TITLE
Error when using custom columns with ignored fields

### ISSUE THREAD

**Issue by xconstruct** [jinzhu/gorm#346]
The feature described in [TestCustomColumnAndIgnoredFieldClash](https://github.com/jinzhu/gorm/blob/master/customize_column_test.go#L16) is currently broken, probably because of 6c1ca7adb82ef5981165037d8834c9b94e0eb2ba. It causes a "duplicate column name" error.

Unfortunately, the same test is broken, too, since it silently discards the error without checking for success. Here is the corrected test case which currently fails with a "duplicate column name: body" error.
```go
func TestCustomColumnAndIgnoredFieldClash(t *testing.T) {
	DB.DropTable(&CustomColumnAndIgnoredFieldClash{})
	if err := DB.AutoMigrate(&CustomColumnAndIgnoredFieldClash{}).Error; err != nil {
		t.Errorf("Should not raise error: %s", err)
	}
}
```
A workaround is to give the ignored field a temporary custom name.

I think you need a `field.IsIgnored`-check somewhere in `(Scope) createTable()`, but I'm not sure where.

**Comment by jinzhu** [comment]
Hi @xconstruct 

Thank you for your report, just fixed this.
