### ISSUE TITLE
belongs_to 的关联查询在没有 includes 实现的情况下，你们是如何解决问题的？

### ISSUE THREAD

**Issue by huacnlee** [jinzhu/gorm#352]
比如 ActiveRecord 里面这样

```ruby
class User
end

class Post
  belongs_to :user
end

@posts = Post.includes(:user).limit(10)
```

```erb
<% @posts.each do |p| %>
  <li><span><%= p.user.try(:nick) %></span> <%= p.title %></li>
<% end %>
```

在 Gorm 里面应该如何实现？

**Comment by jinzhu** [comment]
现在没有这个方法，现在的话，可以再写个方法包装下，取出所有的users, 然后一对一map到post上

不过最近我也准备加这个功能， 有一个ticket提过这个。

**Comment by huacnlee** [comment]
另外，昨晚我读了你的代码以及测用例，居然没发现一处关 belongs_to 的用法

**Comment by jinzhu** [comment]
有的， 这些应该都是吧belongs_to吧

![selection_450](https://cloud.githubusercontent.com/assets/6843/5956026/18519f02-a7e4-11e4-94f6-b2c1d87c0f2a.png)

**Comment by huacnlee** [comment]
.User 会自动出来么？

**Comment by jinzhu** [comment]
User不会自动出来的，go不能动态的给一个struct加方法的

你可以这样子取出来

db.Model(&credit_card).Related(&user)

**Comment by huacnlee** [comment]
为何不在 struct 上面定一个 User 呢

```go
type User struct {}
type Email struct {
    Id int16
    UserId int
    User User
    Email string
}
```

**Comment by huacnlee** [comment]
```go
type Topic struct {
	Id        int32
	UserId    int32  `sql:"not null"`
	Title     string `sql:"size:300;not null"`
	Body      string `sql:"type:text;not null"`
	Replies   []Reply
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (t *Topic) User() *User {
	u := &User{}
	db.Model(t).Related(u)
	return u
}
```

我现在实际上是这么做的

**Comment by jinzhu** [comment]
> 为何不在 struct 上面定一个 User 呢

这个是从测试里面拷贝出来的，struct里面定义struct的也有测试

> 我现在实际上是这么做的

嗯，现在是要这样子做的，等我加上include, 来解决N+1的问题

**Comment by jinzhu** [comment]
现在已经可以解决N+1的问题了，可以参考这里 https://github.com/jinzhu/gorm#preloading-eager-loading
