### ISSUE TITLE
Broken Count:  sql: expected x destination arguments in Scan, not 1

### ISSUE THREAD

**Issue by danbogos** [jinzhu/gorm#354]
Hi,

We have integrated Gorm into our project and works like a charm so far, thank you for this!

The only issue we are facing for now is Count(*arg) not behaving.

Since the project is public, it is easy for me to point you on specific code so you can understand better our use case.

We do a join query with some where filters on it. This query works fine (so no issue with building it and getting results from with via .Rows() and .Scan()). 

As soon as we apply a Count on the same query, we get the following error:
"sql: expected 22 destination arguments in Scan, not 1". 

Following that up, it appears that the error comes from Go SQL package:
database/sql/sql.go

Our code which triggers the error is here:
https://github.com/cgrates/cgrates/blob/master/engine/storage_sql.go#L960

Tried calling .Rows() before Count() but not much joy there either.

We ended up commenting the test which is here:
https://github.com/cgrates/cgrates/blob/master/engine/storage_mysql_local_test.go#L570 
and as you can see in previous test query works fine since that one passes:
https://github.com/cgrates/cgrates/blob/master/engine/storage_mysql_local_test.go#L563

The Count() used to work for us without issues until your commit here, and not anymore after:
https://github.com/jinzhu/gorm/commit/429a10085676fdd0fff56169b3b9e42dddcbd3b1

I would appreciate any tip/advice

Ta,
DanB

**Comment by jinzhu** [comment]
Hello @danbogos 

Thank you for your report.

Seems it is not easy to setup your projec,t could you please just let me know the generated Count sql by using `Debug` method like this:

```go
if err := q.Debug().Count(&cnt).Error; err != nil {
```

**Comment by danbogos** [comment]
Hi @jinzhu,

Many thanks for so fast reaction.

Here is the information you asked for a simple query (which should be with count):

```
(/usr/local/goapps/src/github.com/cgrates/cgrates/engine/storage_sql.go:967) 
[2015-02-05 18:24:11]  [2.27ms]  SELECT  cdrs_primary.cgrid,cdrs_primary.id,cdrs_primary.tor,cdrs_primary.accid,cdrs_primary.cdrhost,cdrs_primary.cdrsource,rated_cdrs.reqtype,rated_cdrs.direction,rated_cdrs.tenant,rated_cdrs.category,rated_cdrs.account,rated_cdrs.subject,rated_cdrs.destination,rated_cdrs.setup_time,rated_cdrs.answer_time,rated_cdrs.usage,cdrs_extra.extra_fields,rated_cdrs.runid,cost_details.account,cost_details.subject,rated_cdrs.cost, count(*) FROM cdrs_primary LEFT JOIN cdrs_extra ON cdrs_primary.cgrid=cdrs_extra.cgrid LEFT JOIN rated_cdrs ON cdrs_primary.cgrid=rated_cdrs.cgrid LEFT JOIN cost_details ON rated_cdrs.cgrid=cost_details.cgrid AND rated_cdrs.runid=cost_details.runid WHERE ((cdrs_primary.deleted_at IS NULL OR cdrs_primary.deleted_at <= '0001-01-02')) AND ((cdrs_extra.deleted_at IS NULL OR cdrs_extra.deleted_at <= '0001-01-02')) AND ((cost_details.deleted_at IS NULL OR cost_details.deleted_at <= '0001-01-02')) AND ((rated_cdrs.deleted_at IS NULL OR rated_cdrs.deleted_at <= '0001-01-02'))

(/usr/local/goapps/src/github.com/cgrates/cgrates/engine/storage_sql.go:967) 
[2015-02-05 18:24:11]  sql: expected 22 destination arguments in Scan, not 1 
```

DanB

**Comment by danbogos** [comment]
Hi @jinzhu,

Was wondering if my debug information is sufficient or may I assist you in any other way?

Ta,
DanB

**Comment by jinzhu** [comment]
Hello @danbogos 

Sorry for the delay, I forgot to check it ;(

Seems I could understand your issue, and just fixed it in the last commit.

Thank you for your feedback.

**Comment by danbogos** [comment]
@jinzhu: I confirm that I have tested your implementation which works as expected.

Thanks again!
DanB

**Comment by akshaydeo** [comment]
@jinzhu  I am facing this issue with postgres with this commit level ef4299b39879ad31b5511acecc12ef4457276d40 (latest). 

Here are my debug logs

```
SELECT * FROM "deals"  WHERE ("deals".deleted_at IS NULL OR "deals".deleted_at <= '0001-01-02') AND recurring_type = '1' AND (start_time < '2015-04-18T19:14:25Z' AND end_time > '2015-04-18T19:14:25Z' AND locality = 'Ragvilas Society' AND city = 'Pune' AND sub_type = '1' AND is_on = true) UNION ALL SELECT * FROM "deals"  WHERE ("deals".deleted_at IS NULL OR "deals".deleted_at <= '0001-01-02') AND (recurring_type = '2' AND day='Sunday') AND (start_time < '2015-04-18T19:14:25Z' AND end_time > '2015-04-18T19:14:25Z' AND locality = 'Ragvilas Society' AND city = 'Pune' AND sub_type = '1' AND is_on = true) UNION ALL SELECT * FROM "deals"  WHERE ("deals".deleted_at IS NULL OR "deals".deleted_at <= '0001-01-02') AND recurring_type = '3' AND day not in ('Saturday','Sunday') AND (start_time < '2015-04-18T19:14:25Z' AND end_time > '2015-04-18T19:14:25Z' AND locality = 'Ragvilas Society' AND city = 'Pune' AND sub_type = '1' AND is_on = true)
DEBU[0003] [Parsing result 0]
DEBU[0003] [[id restaurant_id created_by type description pool start_time end_time created_at updated_at deleted_at sub_type locality city latitude longitude deal_hash recurring_type day started_on ended_on is_on purchased] <nil>]
WARN[0003] sql: expected 23 destination arguments in Scan, not 1
```

**Comment by jinzhu** [comment]
@akshaydeo could you give me a sample code that could reproduce your issue?

**Comment by slygo** [comment]
I have the same problem wih lastest version with xom :(

**Comment by scbizu** [comment]
@slygo check your struct which this SQL will be finally  unmarshaled  to .
