### ISSUE TITLE
Soft deleted rows is not ignored.

### ISSUE THREAD

**Issue by vhakulinen** [jinzhu/gorm#355]
Here is a sample code
```go
package main

import (
	"log"
	"time"

	"github.com/jinzhu/gorm"
	_ "github.com/mattn/go-sqlite3"
)

type T struct {
	Id        int64
	CreatedAt time.Time
	DeletedAt time.Time
}

func main() {
	db, err := gorm.Open("sqlite3", "db.db")
	if err != nil {
		log.Fatal(err)
	}
	db.AutoMigrate(&T{})
	t := &T{}
	db.Debug().Save(t)
	db.Debug().Delete(t)
	ts := []*T{}
	db.Debug().Find(&ts)
	for _, o := range ts {
		println(o.Id)
	}
}
```

Functionality differs from [this](https://github.com/jinzhu/gorm#soft-delete) readme statement of soft delete.

**Comment by jinzhu** [comment]
Hello @vhakulinen 

Thank you for your report, if you change `ts`'s type to `[]T{}`, then it will works. 

But sure, this is considered as an bug, I will fix it, sorry for the problem.

**Comment by vhakulinen** [comment]
No problem and thanks for the tip!

**Comment by jinzhu** [comment]
Hello @vhakulinen 

This issue have been fixed. Thank you for your report.
