### ISSUE TITLE
Test Setup

### ISSUE THREAD

**Issue by sivagollapalli** [jinzhu/gorm#356]
Hi

I am gopher newbie. I will try setup and run tests of the project. To make it run all tests I asked to install  necessary packages required in tests. It would be better if we make a script where user can install all necessary packages at a single shot. If you guys agree with my point I would make a PR. Thanks.

**Comment by jinzhu** [comment]
This `go get -u -t -f ./... ` should works?

**Comment by sivagollapalli** [comment]
@jinzhu `go get -u -t ./....` worked for me. We need to update this in README. Shall I do it?

**Comment by jinzhu** [comment]
I think this is a feature of golang, developers should know this information from golang's document, gorm should not teach you that ;)
