### ISSUE TITLE
Many-to-many condition

### ISSUE THREAD

**Issue by Milyh** [jinzhu/gorm#358]
Hi @jinzhu thanks for the library. 
I have a questions... Let's use 2 struct from example:
```Go
type User struct {
    Id           int64
    Birthday     time.Time
    Age          int64
    Languages         []Language `gorm:"many2many:user_languages;"`

type Language struct {
    Id   int64
    Name string
}
```
This code generate third table calls user_languages.
It good.
But I don't understand how to get all users with language "'en"?
Sql query looks like this:
```Sql
select u.*
from users u
join user_languages as link on u.id = link.user_id
join languages as lang on lang.id = link.language_id
where lang.name = 'en'
```

In LINQ (I'm a .NET developer) I write simple query:
```Go
db.Users.Where(user => user.Language.Any(lang => lang.Title == "en"));
```

Iwrite gorm query like this:
```Go
db.Joins(
    "join user_languages on users.id = user_languages.user_id " +
    "join languages as on languages.id = user_languages.language_id").
  Where("languages.name = ?", "en").
  Find(&users)
```

It works! But I think it isn't the best way.

Can you help me?

Thanks,
Dima.

**Comment by jinzhu** [comment]
Hello @Milyh 

Yes, you have to write it like this for now ;(

Anyway, I will think about this to see if I could improve the API, please let me know if you have any suggestions about this

Thank you.

**Comment by leonlcw** [comment]
Is there a better way now?

**Comment by jonathanroze** [comment]
Is there a better way now?
