### ISSUE TITLE
AutoMigrate does not support pointers

### ISSUE THREAD

**Issue by pedromorgan** [jinzhu/gorm#361]
I'm in the position of using a legacy database/but also to migrate, and want a way to use null's 

So I have the following struct to support the nulls
```
type JobView struct {
        Job
	AccountId int ` json:"account_id" `

        // these are data types, but automigrate cant detect type
	OrderOrdered *time.Time ` json:"order_ordered" `
	OrderRequired *time.Time ` json:"order_required" `

        // this could be null as a join not exist
	JobItemsCount *int ` json:"job_items_count"   `
}
```

This works well, apart from AutoMigrate which cant work out the "type" of a pointer..
Is there a way around this ??

**Comment by jinzhu** [comment]
Hi @pedromorgan 

Just fixed this, thank you for your report.
