### ISSUE TITLE
 ` gorm:?` docs

### ISSUE THREAD

**Issue by pedromorgan** [jinzhu/gorm#362]
Where is the documentation for the 
`  gorm: ` things.. eg 

```
JobId int `json:"job_id" gorm:"column:job_id; primary_key:yes"`
```

**Comment by jinzhu** [comment]
Seems like we don't have document for all details about tags ;(

Although you could find some of them in the README, I am trying to list all of them here.

gorm:"column:job_id; primary_key:yes; foreignkey:job_id; foreigntype:User; associationforeignkey:user_id;many2many:user_jobs;polymorphic:Owner;"`

column: db name of this field
primary_key: use this field as primary key
foreignkey: used as foreign key for relations
foreigntype/polymorphic: used for polymorphic relations https://github.com/jinzhu/gorm#polymorphism
associationforeignkey: used as association foreign key for relations
many2many: define many to many join table

**Comment by blaskovicz** [comment]
:+1: I second this comprehensive list of struct tags. I'm trying to figure out how to change the columns used for a `many2many` join, and this is very confusing.

See my [stackoverflow post](http://stackoverflow.com/questions/33437453/using-different-join-table-columns-than-defaults-with-gorm-many2many-join).
