### ISSUE TITLE
How map embedded type?

### ISSUE THREAD

**Issue by dtanner** [jinzhu/gorm#363]
Hi,
I created this struct to embed a Time type:
```go
type LocalDate struct {
	time.Time
}
```
and set that as the type for a struct like this:
```go
type foo struct {
	Id                int
	EffectiveDate localdate.LocalDate
}
```

The problem is that when querying for foo, during scanning I'm getting this error (mysql db):
```
panic: reflect.Set: value of type time.Time is not assignable to type localdate.LocalDate [recovered]
	panic: reflect.Set: value of type time.Time is not assignable to type localdate.LocalDate
```

Is there a hook/config where I can specify how to convert to/from a field of this custom type?
It looks like issue #273 relates to this, but I didn't see a resolution and couldn't find an example in the tests.

Thanks for any help!

**Comment by deoxxa** [comment]
You *could* implement the [`Valuer`](http://golang.org/pkg/database/sql/driver/#Valuer) and [`Scanner`](http://golang.org/pkg/database/sql/#Scanner) interfaces for `LocalDate`, but it's probably easier just to use the `time.Time` directly.

**Comment by jinzhu** [comment]
Hi @dtanner 

Yes, you need to implement a Valuer and Scanner just like @deoxxa mentioned.

**Comment by dtanner** [comment]
Thanks guys.  For anyone wondering what the solution looks like, here's what appears to work for me:
```go
// sql.Scanner implementation to convert a time.Time column to a LocalDate
func (ld *LocalDate) Scan(value interface{}) error {
	ld.Time = value.(time.Time)
	return nil
}

// sql/driver.Valuer implementation to go from LocalDate -> time.Time
func (ld *LocalDate) Value() (driver.Value, error)  {
	return ld.Time, nil
}
```

**Comment by deoxxa** [comment]
You should probably check to make sure that type assertion succeeds, and
return an error if it doesn't.

**Comment by dtanner** [comment]
Thanks again!
