### ISSUE TITLE
Question about Fetching Data

### ISSUE THREAD

**Issue by danbopes** [jinzhu/gorm#364]
First off, I apologize for creating an issue about this (Not sure where else to get help from). Was hoping you could help me out with an issue fetching data. Below I have two structs (Very similar to User and BillingAddress in your example):

```
type NSet struct {
	Id      string
	Name null.String
}

type NCard struct {
	Id   string
	Name null.String
	SetId   string
	NSet NSet
}
```

NCard belongs to NSet. I'm just trying to do a simple query to fetch all NCards with their associated NSet as well. The idea is to end up with something like this:

```
[{
        Id: "4",
        Name: "test card",
        SetId: "2",
        NSet: {
            Id: "2",
            Name: "test set"
        }
    ]
```

The ideal query would be:

```
SELECT * FROM `NCard` LEFT JOIN `NSet` ON `NCard`.`SetId` = `NSet`.`Id`
```
This may return duplicate names (ie. NCard.name or NSet.name). Not sure if the orm supports things like this. I've tried just about everything, and I'm at a loss here.

**Comment by jinzhu** [comment]
Just try the new feature I just added ;)

https://github.com/jinzhu/gorm#preloading-eager-loading

**Comment by danbopes** [comment]
I like where this is going, but I think in regards to optimizing, this would need to go inside one query. I mean, if there are thousands of adjoining records it could generate very large queries (That may fail due to the query size). This is the optimal solution for grabbing has many records, but not for one to one tables. One one to one tables: having to run two queries, and then loop through data structures twice in order to fill that data seems like a greedy solution.

**Comment by jinzhu** [comment]
Hello @danbopes 

Thank you for your feedback.

Build one query would be tricky, need to do much more work,  so I have chosen the two queries solution, also helpful for the N+1 problem.

The good thing of using two queries is it could reuse database query cache more.
