### ISSUE TITLE
Preload 需要 uniq 以后在查询

### ISSUE THREAD

**Issue by huacnlee** [jinzhu/gorm#365]
```sql
 SELECT  * FROM `users`  WHERE (`id` in ('13','13','13','13','14','13','13','13','13','13'))
```

**Comment by huacnlee** [comment]
另外发现有 Bug，是怎么查询了，但出来的结果里面只有两个 User 对象有值

**Comment by jinzhu** [comment]
嗯，没有做 uniq , 我看看

> 另外发现有 Bug，是怎么查询了，但出来的结果里面只有两个 User 对象有值

应该不会吧，有代码我来测试一下么？

**Comment by jinzhu** [comment]
> 另外发现有 Bug，是怎么查询了，但出来的结果里面只有两个 User 对象有值

这个问题我已经找到原因了，是在关联到相同的记录的情况下会发生，已经修好了。

**Comment by huacnlee** [comment]
:smile: 我就说有嘛

**Comment by jinzhu** [comment]
嗯，测试的时候全是新建的关联，没有测试到这个情况。。。走着走着路想起来了，刚补上测试。。。

**Comment by huacnlee** [comment]
@jinzhu Train 是你们同事搞的吧？叫他 Review 这个 PR https://github.com/shaoshing/train/pull/17

**Comment by jinzhu** [comment]
现在他已经去美国了，我微信 ping了下

**Comment by jinzhu** [comment]
uniq的问题已经解决了 ;)

**Comment by huacnlee** [comment]
:+1:
