### ISSUE TITLE
Update not working after Where First query

### ISSUE THREAD

**Issue by nativematch** [jinzhu/gorm#367]
Hi,

I have been testing using an Update method after fetching a record with Where and First, and found that this doesn't work, yet the UpdateColumn method does work. I've put together a test 

	func TestWhereUpdate(t *testing.T) {
		product1 := Product{Code: "product1whereupdate"}

		DB.Save(&product1)

		var product2 Product
		DB.Where("code = ?", product1.Code).First(&product2).Update("code", "product2whereupdate")

		var product3 Product
		DB.First(&product3, product1.Id)
		if product3.Code != "product2whereupdate" {
			t.Errorf("product 1 should be updated")
		}
	}

	func TestWhereUpdateColumn(t *testing.T) {
		product1 := Product{Code: "product1whereupdatecolumn"}

		DB.Save(&product1)

		var product2 Product
		DB.Where("code = ?", product1.Code).First(&product2).UpdateColumn("code", "product2whereupdatecolumn")

		var product3 Product
		DB.First(&product3, product1.Id)
		if product3.Code != "product2whereupdatecolumn" {
			t.Errorf("product 1 should be updated")
		}
	}

The test passes on sqllite, but this doesn't appear to work for me with postgres, are you able to investigate and provide a fix?

Thanks,
Julian.

**Comment by jinzhu** [comment]
Hi @nativematch 

I have added those two tests into main_test.go, and it has been passed. could you try to update the pg driver and gorm and test it again?

![selection_458](https://cloud.githubusercontent.com/assets/6843/6164958/dfbd833a-b2de-11e4-8aa8-8291a1369b2c.png)
