### ISSUE TITLE
怎么在保存的时候只更新指定的字段？

### ISSUE THREAD

**Issue by cgyy** [jinzhu/gorm#368]
比如有
type Product struct {
Id        int64
Name      string
CreatedAt time.Time
UpdatedAt time.Time
}
p := Product{Id:1, Name: "tom"} // 数据库已存在ID为1的记录
db.Save(&p)// 保存之后create_at字段会设为0值，怎么指定只修改name字段？

**Comment by jinzhu** [comment]
使用UpdateColumn https://github.com/jinzhu/gorm#update-without-callbacks
