### ISSUE TITLE
Before After callback need in transaction

### ISSUE THREAD

**Issue by huacnlee** [jinzhu/gorm#369]
In ActiveRecord

```ruby
class Comment
  after_create do
    self.post.execute ...
  end
end

Comment.create(post: @post, title: "foobar")
```

```sql
BEGIN;
insert into coments ...;
update posts set comments_count = (comments_count + 1) where id = xxx;
COMMIt;
```

So, when then `update` failed, the `insert` command will rollback.

**Comment by jinzhu** [comment]
It's already in a transaction, for example: https://github.com/jinzhu/gorm/blob/master/callback_create.go#L90-L97


Check out https://github.com/jinzhu/gorm#example
