### ISSUE TITLE
Are gorm tags on model structs mandatory?

### ISSUE THREAD

**Issue by acasanova** [jinzhu/gorm#376]
Is it mandatory to put gorm: column: tags on structs? 

My model struct looks like the following

```
type Cd struct {
	Id        int64
	ProdTitle string `gorm:"column:Prod_Title"`
	ProdCode  string `gorm:"column:Prod_Code"`
	ProdDesc  string `gorm:"column:Prod_Desc"`
	Company   string 
	Ext       string
	HiRes     sql.NullString
}
```

```
func TestGetGetty360CD(t *testing.T) {
	cd := models.Cd{}
	var is services.ImageService
	is.InitDBConnection("abcd:1234@tcp(172.17.8.101:3306)/images?parseTime=true")
	is.Connection.Where("Prod_Desc=?", "getty360").First(&cd)
	fmt.Println(cd.Company)
	if cd != (models.Cd{}) && cd.Company == "Getty2" {
		t.Log("Found getty360")
	} else {
		t.Error("Could not find getty360")
	}
}
```

If I don't put a gorm column tag then I can't access the field when I get query results. If I add the gorm tag it works however I'd have to add the tag to a lot of structs. I was wondering if there was a workaround for this. The fmt.Println(cd.Company) is an empty space without any value.

**Comment by jinzhu** [comment]
Hi @acasanova 

You don't need the Tag if follow gorm's conventions (db's column name is the snake value of Field name), so ProdTitle's db name should be `prod_title` but not `Prod_Title` (the database could be auto generated with `AutoMigrate`)

But if you are using a existing database, and don't want to migrate the data according to gorm's convention, then you have to use the tag then.

**Comment by acasanova** [comment]
Thank you for clearing that up for me

**Comment by jjdd12** [comment]
I have the same or similar question but for FKs, I guess more generally, can gorm be used comprehensively without any tags?
