### ISSUE TITLE
How could I store geo points?

### ISSUE THREAD

**Issue by javiermanzano** [jinzhu/gorm#377]
I'm designing a backend with gorm which one of the models contains a geopoint as a field.

Right now I have it like a separate model, but this also includes automigrating other new table and I reallly want to store it in the same table.

I've think on storing it as two sepparate fields "geoPointLat" and "geoPointLon", but I don't know if it's the correct way.

Thanks

**Comment by jinzhu** [comment]
Hi @javiermanzano 

If you make the struct to be a scanner/valuer, it won't create a new table. please refer: http://golang.org/pkg/database/sql/#NullString

**Comment by javiermanzano** [comment]
But this only allows me to map the field to another column just transforming data on the `Value()` function:

```
type GeoPoint struct {
	Lat float64 `json:"lat" form:"lat" binding:"required"`
	Lon float64 `json:"lon" form:"lon" binding:"required"`
}
```

Is there any way that allows me to map GeoPoint to GeoPointLat and GeoPointLon?
