### ISSUE TITLE
Using RowsAffected when multiple goroutines are inserting

### ISSUE THREAD

**Issue by tarikjn** [jinzhu/gorm#378]
Hey there,

I have multiple goroutines inserting data in a database from a shared pointer to a single gorm.DB connection. After an insert I would like to know if it succeeded, so I use RowsAffected, however, given that that pointer is shared between multiple goroutines making insertions, how can I be sure that RowsAffected has not been updated by another goroutine?

Thanks

**Comment by jinzhu** [comment]
Gorm is goroutine-safe, it won't be updated by other goroutine

**Comment by tarikjn** [comment]
Thanks! just wanted to make sure I am doing it right.
