### ISSUE TITLE
Feature request: Auto load related data on Find, First, and so on

### ISSUE THREAD

**Issue by metal3d** [jinzhu/gorm#381]
Hi and at first: great work. Gorm is really impressive and cover the entire functionnalities I want :)

I'm creating a complete framework and I'm implementing Gorm as "plugin" (mysql, pgsql and sqlite will use gorm, but mongo will use mgo and so on...)

To be easilly implemented and usable, as Mongo can do, I really want to be able to fetch data with joined value. Let me explain:

```go
type Address struct {
     City string
     Street string
}

type User struct {
    Name string
    Addresses []Adress
}
```

Gorm understand that I should regsiter Addresses, Mongo registers full data in one dataset. 

When I save an User. That's ok. Each of drivers saves the result as it should.

But when I fetch User, the Addresses "field" is not filled... Mongo hasn't this "problem" because the Addresses field is in the record.

With Gorm I have to call Related to set another list, I have to give struct to fill. 

Yes... I can do it myself in drivers (fetch field, verify they have tables, then assgn related object to the main struct). But... if Gorm plans to be able to do it... That could be great :)

**Comment by jinzhu** [comment]
Seems you are requesting something like https://github.com/jinzhu/gorm#preloading-eager-loading

And Gorm has a plugin system, you could register callbacks with it, I think this maybe helpful for you, check it out: https://github.com/jinzhu/gorm/blob/master/doc/development.md#register-a-new-callback 

(not well documented yet, still improving the plugin system API, so please let me know if you have any questions)

Thank you.

**Comment by daMupfel** [comment]
Will many2many be supported in the preloading api in the future?

**Comment by metal3d** [comment]
mmmmh yes... there are too much things to do for my framework to be able to autoload joined data.

I have to discover table fields to preload, and user has to set "EntityId" to make it working. Warn: I really love gorm and I'm impressed by your work. What I'm telling is only for my own work in a special case. Don't think I'm saying that gorm is bad :)

I paste you a test that I made to test preloading, and I've got a big error log calling this:

```go 
package kwiscaledbsqlite3

import (
	"github.com/jinzhu/gorm"
	_ "github.com/mattn/go-sqlite3"
	"os"
	"testing"
)

func cleanDB(db string) {
	os.Remove(db)
}

type SubData struct {
	id       int64
	Info     string
	UpDataId int64
}

type UpData struct {
	Id       int64
	Name     string
	SubDatas []SubData
}

func TestDirectDB(t *testing.T) {

	defer cleanDB("testdb.db")

	g, _ := gorm.Open("sqlite3", "testdb.db")
	g.LogMode(true)
	g.CreateTable(&UpData{})
	g.CreateTable(&SubData{})

	s := &UpData{
		Name: "foodata",
	}

	sub := make([]SubData, 0)

	sub = append(sub, SubData{
		Info: "info 1",
	})
	sub = append(sub, SubData{
		Info: "info 2",
	})

	s.SubDatas = sub
	g.Save(s)

	res := UpData{}
	g.Preload("SubDatas").Find(&res)
	t.Log(res)
}
```

**Comment by jinzhu** [comment]
Hi @daMupfel

Yes, we will support preload many to many, this is not used often, so I don't have the time to code it up.

@metal3d

There is an error in your struct definition 

```go
type SubData struct {
    id       int64
    Info     string
    UpDataId int64
}
```

Should be

```go
type SubData struct {
    Id       int64
    Info     string
    UpDataId int64
}
```

**Comment by metal3d** [comment]
You're absolutly right. That works now.

Anyway, I know that Gorm is not made to do what I plan to do. Even if I will use it and tell everybody that Gorm is the better ORM for Go I've ever tried (and trust me, I tested a lot of Go ORM :))

I plan to make Gorm working as a Mongo/mgo like interface. I have to test again, maybe I've got solutions. If I found something interessing, I will tell you how I made.

And anyway, I will use Gorm in my framework. 

Big thanks :+1:

**Comment by jinzhu** [comment]
Cool, looking forward to it ;)

**Comment by metal3d** [comment]
To precise, the only problem (this is not a problem from gorm, but from my need) I've to find a solution to not tell user to set "ParentId" for related structs...
Gorm is very cool, I can set "Id" on a "parent" struct that my users have to use as composition:

```go
type User struct {
    ORMData
    Name string
    Age int
}
```

My "ORMData" parent struct has got an Id and Gorm works like I want. Now, the problem I've to resolve:

```go
type Email struct {
    ORMData
    For string
    Address string
    // Without this one, that cannot work
    // but I'm seeking solution to remove this need:
    UserId int64
}

type User struct {
    ORMData
    Name string
    Age int
    Emails []Email
}
```

As soon as I found this solution (see comment in Email struct), I will be able implement my mgo driver and my framework will be able to manage any data with any database :)

**Comment by jinzhu** [comment]
You have to have a column to save foreign key, so we could get relations later.

**Comment by metal3d** [comment]
Yes, I understand why we need this column. My work is to make it transparent for the user.

**Comment by LiranCohen** [comment]
@jinzhu is Preload for many2many not currently supported? Thanks!

**Comment by daMupfel** [comment]
@LiranCohen As far as i know not yet.

**Comment by amoghe** [comment]
+1 for preloading many2many associations

**Comment by jinzhu** [comment]
Hi @all 

Preloading for many2many is already supported.
