### ISSUE TITLE
add more custom examples

### ISSUE THREAD

**Issue by spx** [jinzhu/gorm#382]
var T struct {
	Var1 string
	Var2 int
}
for row.Next() {
	row.Scan(&T.Var1, &T.Var2)
}

also would be nice have row.Scanf(&T) for fields by fields order.
all projects have same issue - to little custom and complex examples.

**Comment by spx** [comment]
how about; db.ignore().insert().....

**Comment by spx** [comment]
another good example to build queries like: https://github.com/parnurzeal/gorequest 
a, err := db.select().blah().rollbackonerror().exec()

**Comment by jinzhu** [comment]
Hey @spx,

There is an issue related to this already https://github.com/jinzhu/gorm/issues/59, so please follow that one.

Thank you.
