### ISSUE TITLE
maybe: db.Table().Select().RowsMap() ?

### ISSUE THREAD

**Issue by spx** [jinzhu/gorm#383]
map[int][string]interface{}
then int - PK or just row id and string = field name and value = field value

**Comment by spx** [comment]
or maybe:
type Row struct { name, value } 
type Rows []*Row
db.Register(&Rows{}, &Row{}).Select().Where().Done()

**Comment by spx** [comment]
or maybe 
type Rows []interface{}
and then row.(Row)

**Comment by jinzhu** [comment]
Sorry, @spx , seems I can't understand what you are talking...
