### ISSUE TITLE
Searching for Zero

### ISSUE THREAD

**Issue by majimboo** [jinzhu/gorm#387]
Why is it that when I try to find a value with 0, it doesn't get shown in the query?

    db.FirstOrCreate(&charData0, CharacterData{CharId: charId, Segment: segment})

Say segment is zero, then the query shown is:

    SELECT  * FROM `character_data`  WHERE (`char_id` = '1') LIMIT 1

How do I force it to query `segment = 0`? Because I also have segment 1-8 in my table.

**Comment by jinzhu** [comment]
You need to use map in this case, like this:

```go
db.FirstOrCreate(&charData0, map[string[interface{}{"CharId": charId, "Segment": segment})
```

But I am thinking about how to improve this, maybe we will make it works like this in future

```go
db.Select("CharId", "Segment").FirstOrCreate(&charData0, CharacterData{CharId: charId, Segment: segment})
```

Let me know if you have any suggestion
