### ISSUE TITLE
Binary data being truncated

### ISSUE THREAD

**Issue by majimboo** [jinzhu/gorm#388]
My data field is `varbinary(2000)` but why is the data being inserted (new) being truncated to around 20 bytes?

	var charData CharacterData
	db.Where(CharacterData{CharId: charId, Segment: 0}).FirstOrInit(&charData)
	charData.Data = data[16:]
	db.Save(&charData)

`len(data[16:])` is 2000.

     type CharacterData struct {
	  CharId    uint32
	  Data      []byte
	  Segment   uint8
	  SegmentId uint16

	  CreatedAt time.Time
	  UpdatedAt time.Time
	  DeletedAt time.Time
     }

**Comment by jinzhu** [comment]
Could you post a runnable script here that could reproduce this issue?

**Comment by majimboo** [comment]
I have an open [question](stackoverflow.com/questions/28767067) at stackoverflow about this and it seems like the problem is with golang?
