### ISSUE TITLE
How to add foreign key in sqlite3

### ISSUE THREAD

**Issue by klniu** [jinzhu/gorm#390]
Hello. Thanks for your work. It's so helpful.

At https://github.com/jinzhu/gorm/issues/23 you have mentioned that it can add reference key via adding tag in the field of the struct, like this:

<pre>
type User {
  ...
  BillingAddressId  sql.NullInt64 `sql:"type:bigint REFERENCES address(id)"`
}
</pre>

In sqlite3 how can I add foreign key between tables. The syntax for creating table for adding foreign key is like this:

<pre>
CREATE TABLE track( 
period INTEGER,  
trackname TEXT,  
trackartist INTEGER,  
FOREIGN KEY(trackartist) REFERENCES artist(artistid )
);
</pre>
I tried
<pre>
type User {
  ...
  BillingAddressId int `sql:"type:INTEGER FOREIGN KEY(billing_address_id) REFERENCES address(id)"`
}</pre>
but no effect. Could you please give some suggest how to do this?

**Comment by jinzhu** [comment]
I just tested it with below script, and seems works for me.

```go
package main

import (
	"fmt"

	"github.com/jinzhu/gorm"
	_ "github.com/mattn/go-sqlite3"
)

type User struct {
	Id      int
	Name    string
	Address Address
}

type Address struct {
	Id       int
	Address1 string
	UserId   int `sql:"type:bigint REFERENCES users(id)"`
}

func main() {
	db, _ := gorm.Open("sqlite3", "testdb.db")
	db.Exec("PRAGMA foreign_keys = ON")
	db.LogMode(true)
	db.AutoMigrate(&User{}, &Address{})
	fmt.Println(db.Save(&User{Name: "jinzhu", Address: Address{Address1: "address 1"}}).Error)
	fmt.Println(db.Save(&Address{Address1: "address 1", UserId: 9999}).Error)
}
```

**Comment by klniu** [comment]
Thanks, It is helpful. Wish you a happy day.
