### ISSUE TITLE
Nested preloading

### ISSUE THREAD

**Issue by nkovacs** [jinzhu/gorm#392]
I'd like to do something like this, but I don't think it's possible:

```go

type City struct {
    Id int
    Name string
}

type Address struct {
    HouseNumber int
    Street string

    City City
    CityId int
}

type Order struct {
    Address Address
    AddressId int
    
    User User
    UserId int
}

type User struct {
    Id int

    Orders []Order
}

db.Model(user).Preload("Address").Preload("Address.City").Related(&orders) // Address.City is not a relation in Order, so it's ignored
```

**Comment by jinzhu** [comment]
Hi @nkovacs

Yes, this is not supported yet, but on the plan already.

**Comment by rebyn** [comment]
:+1: would be lovely if gorm supports this.

**Comment by egeozcan** [comment]
I'm also looking forward to this. Any cues/ideas on how the api will be?

**Comment by jinzhu** [comment]
It will like @nkovacs's example.

```go
db.Model(user).Preload("Address").Preload("Address.City").Related(&orders)
```

**Comment by dimascyriaco** [comment]
That would be really useful.

**Comment by rtm7777** [comment]
@jinzhu Can you confirm, this feature is working now?
https://github.com/jinzhu/gorm#nested-preloading

If it works, I think we also can update http://stackoverflow.com/questions/29230261/how-preload-a-full-hierachy-in-go-using-gorm

**Comment by jinzhu** [comment]
Hi @rtm7777 

Yes, it is works already. sorry forgot to update this issue.

**Comment by benguild** [comment]
Keep in mind that this implementation uses subsequent SELECT(s). While this is great for simplicity (and perhaps multi-level caching with the correct callback configuration) ... it's also could be optimized by using `JOIN` statements to reduce latency to/from the server from multiple queries.
