### ISSUE TITLE
Scan error when performing a count query

### ISSUE THREAD

**Issue by arvin** [jinzhu/gorm#397]
When I do a count query, I get:

sql: Scan error on column index 0: destination pointer is nil
Here's the sql: SELECT  count(*) FROM "posts"  WHERE ("posts".deleted_at IS NULL OR "posts".deleted_at <= '0001-01-02') AND ((username = 'arvin'))

Here's the line in question:
db.Model(&Post{}).Where("username = ?", username).Count(total)

Thanks!

**Comment by jinzhu** [comment]
it should be?

```go
db.Model(&Post{}).Where("username = ?", username).Count(&total)
// &count not count
```

Let me know if it still doesn't work.

**Comment by arvin** [comment]
the variable itself is a *int64

**Comment by arvin** [comment]
nvm I think I got it
