### ISSUE TITLE
best to way to create related objects

### ISSUE THREAD

**Issue by vpereira** [jinzhu/gorm#399]
hi I'm doing something similar with https://gist.github.com/vpereira/69f0acd27d4124d45f86, to create users.. however the relationship doesnt look right.. where I'm getting it wrong?

**Comment by amoghe** [comment]
In your gist, the user struct needs a ```RoleId``` field to store the foreign key (assuming a user can have one role, i.e. "has one/belongs to" type of relationship).

Compare this to the example in the README (simplified for this example):

```
type User struct {
    ID           int
    Birthday     time.Time
    Age          int
    Name         string

    Emails            []Email         // One-To-Many relationship (has many)
}

type Email struct {
    ID         int
    UserID     int     // Foreign key for User (belongs to) *SEE THIS*
    Email      string 
    Subscribed bool
}
```

Notice that in this example a ```User``` can have multiple emails (has-many relationship), and each ```Email``` has a field to store the foreign key for the ```User``` it belongs to. You just need to ensure that the foreign key field exists in your struct and ```gorm``` will do the rest. Of course, things get a little more complicated for a many-many type of relationship (user has many roles). For that take a look at the README for the many-many example. If that is confusing, I *highly* recommend reading http://guides.rubyonrails.org/association_basics.html which is an excellent primer on how to think about model associations (and therefore foreign keys).

**Comment by jinzhu** [comment]
@amoghe thank you for your explanation

**Comment by vpereira** [comment]
hi thank you, for the explanation! I how to do it in rails and thats why i did as I did (without explicitely adding the keys. - i thought that would happen automatically by db migrate!) 

thank you!
