### ISSUE TITLE
how to open a mysql connection?

### ISSUE THREAD

**Issue by john-qin** [jinzhu/gorm#403]
I have a mysql DB lives on another server.  is my connection string correct?  I kept getting "Default addr for network '11.11.11.12:3306' unknown", not sure what is wrong and hwo to fix it.

i.DB, err = gorm.Open("mysql", "test:Abcd1234567@11.11.11.12:3306/gormtest?charset=utf8@parseTime=true")

**Comment by jinzhu** [comment]
Should be: `id:password@tcp(your-amazonaws-uri.com:3306)/dbname`

Please refer https://github.com/go-sql-driver/mysql

**Comment by sunlianqiang** [comment]
you should make sure the database you connect (here gormtest) has been created.

**Comment by sadegh-shahbazi** [comment]
what is the code if we want open a connection and never close it 
should we open in func init(){} ?

**Comment by D-sense** [comment]
> what is the code if we want open a connection and never close it
> should we open in func init(){} ?

Simply don't call "defer db.Close()" after opening the connection to the database. But, this would be a very bad practice.
