### ISSUE TITLE
FirstOrCreate with primary

### ISSUE THREAD

**Issue by majimboo** [jinzhu/gorm#405]
Is it possible to use FirstOrCreate with a primary key?

I have a table that the primary key is `user_id`. I defined `UserId` as `gorm:"primary_key:yes"`.
But when I use `FirstOrCreate` it keeps giving me an empty model and doesn't create any data on the database.

	db.FirstOrCreate(&billing, Billing{UserId: playerId})

**Comment by jinzhu** [comment]
Seems it works for me, here is the sample code.

```go
package main

import (
        "fmt"

        "github.com/jinzhu/gorm"
        _ "github.com/mattn/go-sqlite3"
)

type Billing struct {
        UserId int `gorm:"primary_key:yes"`
}

func main() {
        db, err := gorm.Open("sqlite3", "/tmp/gorm.db")
        fmt.Println(err)
        db.AutoMigrate(&Billing{})

        var billing = Billing{}
        db.Debug().FirstOrCreate(&billing, Billing{UserId: 10})
        fmt.Println(billing)
}
```

**Comment by majimboo** [comment]
Is it okay to use `uint32` as a primary key?

type Billing struct {
        UserId uint32 `gorm:"primary_key:yes"`
}

**Comment by jinzhu** [comment]
@majimboo yes, it is possible

**Comment by majimboo** [comment]
It's still not working for me. Should the table still have an ID column? Because I do not have one, I used the `user_id` instead.

**Comment by jinzhu** [comment]
```go
package main

import (
	"fmt"

	"github.com/jinzhu/gorm"
	_ "github.com/mattn/go-sqlite3"
)

type Billing struct {
	UserId uint32 `gorm:"primary_key:yes"`
}

func main() {
	db, err := gorm.Open("sqlite3", "/tmp/gorm.db")
	fmt.Println(err)
	db.DropTable(&Billing{})
	db.Debug().AutoMigrate(&Billing{})

	var billing = Billing{}
	db.Debug().FirstOrCreate(&billing, Billing{UserId: 10})
	fmt.Println(billing)
}
```

**Comment by m90** [comment]
I'm hitting this too and I think it's a backend issue. I can repro the condition @majimboo is describing using `postgres`, but when I use `sqlite` it works as expected.
