### ISSUE TITLE
Allowing other default values for postgres ID fields

### ISSUE THREAD

**Issue by james-m** [jinzhu/gorm#406]
Currently the postgres dialect will create a SERIAL for ID fields, which behind the scenes results in a default value being the nextval from a sequence. I would like to set a default value to be a custom function I  create for generating ids, but still use the name ID and have gorm know it is the PK. 

So, I'd like to have a model like:

```go
type User struct {
	ID        uint64 `sql:"DEFAULT:user_gen_id()"`
...
}
``` 

This results in errors when trying to create the table: 
```
pq: multiple default values specified for column "id" of table "users"
```

I believe it should be straight forward enough in the postgres dialect (maybe https://github.com/jinzhu/gorm/blob/master/postgres.go#L59) to detect the string default in the StructTag and instead of creating the PK as a SERIAL create it as the appropriately sized integer. I could put a pull request together if people think this could work.

This is also my first day looking at gorm (evaluating it and ran into this snag for my use case)  so if there is a workaround for accomplishing this I'm all ears. Thanks.

**Comment by jinzhu** [comment]
You should be able to do it like this:

```go
type User struct {
    ID        uint64 `sql:"type:integer PRIMARY KEY;default:user_gen_id()"`
...
}
```

**Comment by beef9999** [comment]
Where to define that user_gen_id function?

Right here in Go source code?

@jinzhu
