### ISSUE TITLE
Documentation / Relation confusion

### ISSUE THREAD

**Issue by smw1218** [jinzhu/gorm#407]
I think the README may be out of date with the code; but I'm a bit confused about how relations work in general.

The Has Many doc has the following example:

// User has many emails
db.Model(&user).Related(&emails)

I'm confuse why there's the &emails variable.  The user model already has an []Emails slice so why can't I load into that?

In my model I also needed to specify the foreign key explicitly to get the query to run.  I'm not sure but I think there's some weird naming stuff around Id vs. ID.  I first named my variables UserID like the doc but the migration produced columns like user_i_d.  So I switched it to UserId. But I think the auto foreign key detection must be looking for UserID

**Comment by jinzhu** [comment]
For the migration, maybe you are using an out of date gorm. with latest gorm, you could be used name it to ID or Id.

For the load, sure you could load it into user's []Emails, both will works.
