### ISSUE TITLE
Named integer fields not supported

### ISSUE THREAD

**Issue by bprosnitz** [jinzhu/gorm#408]
type N int64

type A struct {
	ID int
	T  N
}

db.CreateTable(&A{})
db.Save(&A{0, 22})
var x A
db.First(&x)

Fails with:
panic: reflect.Set: value of type int64 is not assignable to type data.N

Because of this, standard library types like time.Duration (int64) can't be used

**Comment by egeozcan** [comment]
Bug exists indeed. It works when anonymous though:

    type Record struct {
    	ID        int64     `json:",string"`
    	CreatedAt time.Time `json:"createdAt"`
    	UpdatedAt time.Time `json:"updatedAt"`
    	DeletedAt time.Time `json:"deletedAt"`
    }

    type User struct {
    	Record
    	Name      string    `sql:"size:255" form:"username" binding:"required"`
    }

**Comment by egeozcan** [comment]
See #363 for a solution

**Comment by jinzhu** [comment]
`N` need to be a Scanner, refer NullInt64 https://golang.org/pkg/database/sql/#NullInt64
