### ISSUE TITLE
abnormal behaviour with TableName() callback

### ISSUE THREAD

**Issue by psykeron** [jinzhu/gorm#410]
I was working with the latest version of gorm, and encountered an issue with the TableName() callback

```go
type User struct {
	TableType       string
}

func (s User) TableName() string {
	return "user:"+s.TableType+":stats"
}
```
When I use the struct style of fetching a record
```go
output := User{TableType: "admin"}
err := db.First(&output, id).Error
```
The query breaks because it can't find the table. I can see TableName() being called only once for a struct type. All future queries seem to use a cached result of the function.

Also, in my case the value of s.TableType is always blank for some reason. So the table being queried by gorm is `user::stats` instead of `user:admin:stats`, or `user:simple:stats`

I reverted my gorm package to a97a508ec79815db84ebbfb522d3ef6832159bac, and it didn't work. Then
I reverted to 1b4490fd4731b7ba60100458ec2fc00fc461d9dd, and it works. I haven't figured out when this issue was introduced.  Hope that information helps.

**Comment by jinzhu** [comment]
Hello @psykeron 

Thank you for your report, the issue should be fixed.
