### ISSUE TITLE
sqlite []byte is not stored

### ISSUE THREAD

**Issue by vitas** [jinzhu/gorm#411]
I'm trying to save entity with field type of []byte, it works in postgresql just fine, but does not in sqlite.
PS. i see it generate db type blob, is it ok or i should provide some mapping?

thank you

**Comment by jinzhu** [comment]
Hello @vitas,

Could you give me an example, I think there should be no problem, because this is tested here. https://github.com/jinzhu/gorm/blob/master/create_test.go#L28

Does the tests fail to run in you local?

**Comment by vitas** [comment]
Hi,
Sorry, looks like it was my mistake,. it works as expected! thank you

but i have another problem: AutoMigration does work for sqllite (Postgres is OK) for foreign key generation as it uses alter table what is not supported

I'm getting "near "CONSTRAINT": syntax error"

Foreign keys have to be created with the CREATE TABLE statement and not via ALTER TABLE (see http://www.sqlite.org/foreignkeys.html).
