### ISSUE TITLE
) LIMIT 1 is added on Raw queries that are supposed to return 1 value

### ISSUE THREAD

**Issue by HenrikPihl** [jinzhu/gorm#413]

**Comment by HenrikPihl** [comment]
change happened in commit 5330572c258c16742c3052af3f82f67031112f2e

**Comment by jinzhu** [comment]
Hi @HenrikPihl

Could you give me an example about this?

**Comment by HenrikPihl** [comment]
I added some logging in the code:

func (scope *Scope) prepareQuerySql() {

    if scope.Search.Raw {

        log.Print(scope.CombinedConditionSql());

        log.Print(strings.TrimLeft(scope.CombinedConditionSql(), "WHERE "));

        log.Print(strings.TrimRight(strings.TrimLeft(scope.CombinedConditionSql(),
"WHERE ("), ")"));

        scope.Raw(strings.TrimRight(strings.TrimLeft(scope.CombinedConditionSql(),
"WHERE ("), ")"))

    } else {

        scope.Raw(fmt.Sprintf("SELECT %v %v FROM %v %v", scope.topSql(),
scope.selectSql(), scope.QuotedTableName(), scope.CombinedConditionSql()))

    }

    return

}

Output:

2015/03/11 10:54:08  WHERE (SELECT count(*) as count FROM favorites f WHERE
f.topic_id = $$) LIMIT 1

2015/03/11 10:54:08 (SELECT count(*) as count FROM favorites f WHERE
f.topic_id = $$) LIMIT 1

2015/03/11 10:54:08 SELECT count(*) as count FROM favorites f WHERE
f.topic_id = $$) LIMIT 1


The last ) results in a sql syntax error.


Best regards,

Henrik Pihl

**Comment by mattbostock** [comment]
I have also seen this same issue.

**Comment by jinzhu** [comment]
Hi All,

Thank you for your report, I should fixed that issue already.

Sorry for that.
