### ISSUE TITLE
How to populate and embedded array?

### ISSUE THREAD

**Issue by javiermanzano** [jinzhu/gorm#414]
I have 2 structs with data like this:

```
type User struct {
  Pics Pic[]
}
```
```
type Pic struct {
  Id int   
  UserId int64
}
```

Although everytime I insert an User, Each of the pics are inserted on their table everytime I find the users, pics are not populated:

```
var users []User
db.Limit(pagesize).Where("updated_at > ?", date).Find(&users)
```

Am I doing something wrong?

**Comment by gillesfabio** [comment]
@javiermanzano You should use `Preload()`. Like this:

```go
var users []User

db.Preload("Pics").Where("updated_at > ?", date).Limit(pagesize).Find(&users)

for _, user := range users {
    // You should have pics now
    fmt.Println(user.Pics)
}
```

Documented [here](https://github.com/jinzhu/gorm#preloading-eager-loading).

Hope it helps.
