### ISSUE TITLE
Specify foreign key for preload

### ISSUE THREAD

**Issue by AdnanHidic** [jinzhu/gorm#415]
First I'd like to thank you and other contributors for your great work on this package. Thank you!

Something I noted with the new Preload feature is that it currently only supports associations by convention, for example one can preload BillingAddress only if type has BillingAddressId field. 

I'd like to be able to do something like:
db.PreloadWithForeignKey("BillingAddress", "MyForeignKeyField").Find(&user)

This would also be consistent with how the API for associations works because method "Related" already supports specifying which field's value to use as foreign key.

Thanks!

**Comment by jinzhu** [comment]
I am going to introduce you a undocumented feature for gorm ;)

```go
type User struct {
  BillingAddress `gorm:"ForeignKey:MyForeignKeyField"`
}
```

After that, Preload should works like a charm.

Still thinking how to organize those things into README, or should I do that, because I want people follow the convention as much as possible...
