### ISSUE TITLE
Missing Row() method returns unexpected results

### ISSUE THREAD

**Issue by mattbostock** [jinzhu/gorm#416]
I was trying to figure out why, in this query, `minutes` was assigned a value of `0`:

```go
var minutes int32

err := db.Table("leave_requests").
                 Select("SUM(minutes)").
                 Scan(&minutes).Error
```

After looking at the Gorm tests, it seems I was missing `Row()` in the method chain. Is there a way to make this error more obvious, so that others don't repeat my mistake? No error was raised, just I saw a zero value rather than the expected value.

```go
var minutes int32

err := db.Table("leave_requests").
                 Select("SUM(minutes)").
                 Row().
                 Scan(&minutes).Error
```

**Comment by jinzhu** [comment]
Hi @mattbostock

Sorry for the trouble, this should be documented better. 

`db.Scan` could only scan into a struct, and `Row().Scan()` just works like the golang sql package.
https://github.com/jinzhu/gorm#scan
https://github.com/jinzhu/gorm#row--rows

But anyway, I just added a error message, so you could know you get an error for those cases.

**Comment by mattbostock** [comment]
Thanks for the quick response and for adding the error message!
