### ISSUE TITLE
Incorrect database creation?

### ISSUE THREAD

**Issue by VasilyPupkin** [jinzhu/gorm#418]
"github.com/mattn/go-sqlite3"

	Client struct {
		ID        int
		Ip        string `sql:"not null;unique;index:idx_ip"`
		Model     string `sql:"not null;unique;index:idx_model"`
		Service   string `sql:"not null;index:idx_service"`
		Crashes   []Media
		Played    []Media
		Supported []Media
	}

	Category struct {
		ID       int
		Category string `sql:"not null;unique;index:idx_category"`
	}

	Media struct {
		ID       int
		Remote   bool
		Resource string `sql:"not null;unique;index:idx_resource"`
		Library  Library
		Duration int64
		Category Category
		Subtype  string `sql:"not null"`
	}

	Library struct {
		ID   int
		Name string `sql:"not null;unique;index:idx_library_name"`
		Path string `sql:"not null;unique;index:idx_library_path"`
	}

maps to this:

PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "clients" ("id" integer,"ip" varchar(255) NOT NULL UNIQUE,"model" varchar(255) NOT NULL UNIQUE,"service" varchar(255) NOT NULL  , PRIMARY KEY (id));
CREATE TABLE "medias" ("id" integer,"remote" bool,"resource" varchar(255) NOT NULL UNIQUE,"duration" bigint,"subtype" varchar(255) NOT NULL  , PRIMARY KEY (id));
CREATE TABLE "categories" ("id" integer,"category" varchar(255) NOT NULL UNIQUE , PRIMARY KEY (id));
CREATE TABLE "libraries" ("id" integer,"name" varchar(255) NOT NULL UNIQUE,"path" varchar(255) NOT NULL UNIQUE , PRIMARY KEY (id));
COMMIT;

**Comment by jinzhu** [comment]
Hi @VasilyPupkin 

What's the error you got? or unexpected behaviours happened?
