### ISSUE TITLE
Many2Many assigns join table's id to related model's id field

### ISSUE THREAD

**Issue by nkovacs** [jinzhu/gorm#420]
```go
type User struct {
    Id int64
    Name string
    Languages []Language `gorm:"many2many:user_languages"`
}

type Language struct {
    Id int64
    Name string
}
```

user_languages table contains three fields: id (primary key), user_id and language_id (foreign keys)

If I do 
```go
var languages []Language

db.Debug().Model(user).Related(&languages, "Languages")
```

the Id field of the Language structs in the languages array will be id the field from the user_languages table, not the id field of the language in the languages table.

The workaround is to add `.Select("languages.*")`. I did not test this with Preload though.

**Comment by jinzhu** [comment]
Hi @nkovacs 

Thank you for your report, the join table is created manually by yourself?

**Comment by nkovacs** [comment]
Yes

**Comment by LiranCohen** [comment]
I used Association()  for relationship when looking for 1 which works fine with many2many.

Preload works great with one2many relationships, but I'm getting a "not supported relation" error with many2many Preload.

Wonder if this is the same issue.

**Comment by djboris9** [comment]
querying an many2many realation also fails if one of the primary keys is not named "ID". Could you please provide an working example with preloading of an many2many relation as a Gist or playground snippet?

**Comment by jinzhu** [comment]
Hi @nkovacs 

The issue for `Related` should been fixed for a while, and just pushed a commit to fix the issue with `Preload`

Thank you.
