### ISSUE TITLE
after prolong usage it give error "use of closed network"

### ISSUE THREAD

**Issue by badoet** [jinzhu/gorm#423]
after prolong usage it give error "use of closed network"

any idea what might cause this?
is it somehow the connection might get forced closed internally?
and if possible any way to mitigate this?

**Comment by jinzhu** [comment]
Do you know where the error happened? I searched my GOPATH, can't find the error message, and googled mysql with the error message, also doesn't help

**Comment by badoet** [comment]
sorry, the alert is sent to the wrong place.
apparently its the error from my redis library. 
the GCE will terminate idle tcp after 10 minutes and there is no way to prevent it.
