### ISSUE TITLE
Delete struct with ID=0 will empty the table

### ISSUE THREAD

**Issue by Iceyer** [jinzhu/gorm#425]
````
type Test struct  {
    ID int
}
t := &Test{}
db.Delete(t) //will empty the whole table??!!

````

**Comment by jinzhu** [comment]
@Iceyer Yes, or what's your excepted behaviour? 

If you want to delete an records match a conditions, you should add that like this:

````go
db.Delete(&Test{}, "id = ?", 10)
db.Delete(&Test{}, "code = ?", "expired")

// delete if found
var test Test
if !db.First(&test).RecordNotFound() {
  db.Delete(&test)
}
```

**Comment by bigokro** [comment]
+1 to reopen this.

I don't think the default behavior should be to trust that the developer/code wants to delete the whole table. This would have to be a pretty rare thing to actually want to do. Better to throw a panic or something when called with an empty struct, and have a method like `DeleteAll`, or have to use `Exec` to really wipe out a whole table.

As it is, you need to follow a recommended best-practice pattern every time you want to (safely) use the Delete command.

**Comment by brunoksato** [comment]
+1

**Comment by any35** [comment]
It's not a good idea to delete records with object query. it will not parse the conditions which have default value.

**Comment by jinzhu** [comment]
http://jinzhu.me/gorm/curd.html#delete

**Comment by jsm** [comment]
lol
