### ISSUE TITLE
Should I do something for migration?

### ISSUE THREAD

**Issue by dorajistyle** [jinzhu/gorm#428]
I've used 087b7083ad1154ff0573d560b64310e4869a2820.
It worked well.
Yesterday I've tried to update gorm from 17b20bcdd8e54c8f66c7a8549b0e80a04618ee5f.
It's not works.
And then I checked which commit version works well, 
Before https://github.com/jinzhu/gorm/commit/da8fc53c86cb9cecde4080820b00bb9598dd27da , gorm work well.
After that commit version, my application broken.

When I use https://github.com/jinzhu/gorm/commit/17b20bcdd8e54c8f66c7a8549b0e80a04618ee5f ,

I've got a some error messages below.

/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467dd5d8 sp=0xc2467dd5c0
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc2578ac680, 0x2)
/src/github.com/jinzhu/gorm/model_struct.go:222 +0x203c fp=0xc2467ddbd8 sp=0xc2467dd5d8
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc2578ac680, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467ddbf0 sp=0xc2467ddbd8
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc2759d4e80, 0xc2759d4f00)
/src/github.com/jinzhu/gorm/model_struct.go:262 +0x2582 fp=0xc2467de1f0 sp=0xc2467ddbf0
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc2759d4e80, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467de208 sp=0xc2467de1f0
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc2759d4d00, 0x2)
/src/github.com/jinzhu/gorm/model_struct.go:236 +0x2777 fp=0xc2467de808 sp=0xc2467de208
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc2759d4d00, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467de820 sp=0xc2467de808
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc2759d4700, 0x2)
/src/github.com/jinzhu/gorm/model_struct.go:222 +0x203c fp=0xc2467dee20 sp=0xc2467de820
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc2759d4700, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467dee38 sp=0xc2467dee20
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc2578ca500, 0xc2578ca580)
/src/github.com/jinzhu/gorm/model_struct.go:262 +0x2582 fp=0xc2467df438 sp=0xc2467dee38
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc2578ca500, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467df450 sp=0xc2467df438
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc2578ca200, 0x2)
/src/github.com/jinzhu/gorm/model_struct.go:236 +0x2777 fp=0xc2467dfa50 sp=0xc2467df450
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc2578ca200, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467dfa68 sp=0xc2467dfa50
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc2578e9800, 0x2)
/src/github.com/jinzhu/gorm/model_struct.go:222 +0x203c fp=0xc2467e0068 sp=0xc2467dfa68
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc2578e9800, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467e0080 sp=0xc2467e0068
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc2759b3900, 0xc2759b3980)
/src/github.com/jinzhu/gorm/model_struct.go:262 +0x2582 fp=0xc2467e0680 sp=0xc2467e0080
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc2759b3900, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467e0698 sp=0xc2467e0680
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc2759b3580, 0x2)
/src/github.com/jinzhu/gorm/model_struct.go:236 +0x2777 fp=0xc2467e0c98 sp=0xc2467e0698
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc2759b3580, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467e0cb0 sp=0xc2467e0c98
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc2759b2f80, 0x2)
/src/github.com/jinzhu/gorm/model_struct.go:222 +0x203c fp=0xc2467e12b0 sp=0xc2467e0cb0
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc2759b2f80, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467e12c8 sp=0xc2467e12b0
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc257901780, 0xc257901800)
/src/github.com/jinzhu/gorm/model_struct.go:262 +0x2582 fp=0xc2467e18c8 sp=0xc2467e12c8
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc257901780, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467e18e0 sp=0xc2467e18c8
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc257901280, 0x2)
/src/github.com/jinzhu/gorm/model_struct.go:236 +0x2777 fp=0xc2467e1ee0 sp=0xc2467e18e0
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc257901280, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467e1ef8 sp=0xc2467e1ee0
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc257900900, 0x2)
/src/github.com/jinzhu/gorm/model_struct.go:222 +0x203c fp=0xc2467e24f8 sp=0xc2467e1ef8
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc257900900, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467e2510 sp=0xc2467e24f8
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc27599cf00, 0xc27599cf80)
/src/github.com/jinzhu/gorm/model_struct.go:262 +0x2582 fp=0xc2467e2b10 sp=0xc2467e2510
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc27599cf00, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467e2b28 sp=0xc2467e2b10
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc27599cd80, 0x2)
/src/github.com/jinzhu/gorm/model_struct.go:236 +0x2777 fp=0xc2467e3128 sp=0xc2467e2b28
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc27599cd80, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467e3140 sp=0xc2467e3128
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc27599c600, 0x2)
/src/github.com/jinzhu/gorm/model_struct.go:222 +0x203c fp=0xc2467e3740 sp=0xc2467e3140
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc27599c600, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467e3758 sp=0xc2467e3740
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc25792c500, 0xc25792c580)
/src/github.com/jinzhu/gorm/model_struct.go:262 +0x2582 fp=0xc2467e3d58 sp=0xc2467e3758
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc25792c500, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467e3d70 sp=0xc2467e3d58
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc25792c200, 0x2)
/src/github.com/jinzhu/gorm/model_struct.go:236 +0x2777 fp=0xc2467e4370 sp=0xc2467e3d70
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc25792c200, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467e4388 sp=0xc2467e4370
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc25794ba00, 0x2)
/src/github.com/jinzhu/gorm/model_struct.go:222 +0x203c fp=0xc2467e4988 sp=0xc2467e4388
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc25794ba00, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467e49a0 sp=0xc2467e4988
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc257967800, 0xc257967880)
/src/github.com/jinzhu/gorm/model_struct.go:262 +0x2582 fp=0xc2467e4fa0 sp=0xc2467e49a0
github.com/jinzhu/gorm.(*Scope).GetStructFields(0xc257967800, 0x0, 0x0, 0x0)
/src/github.com/jinzhu/gorm/model_struct.go:293 +0x43 fp=0xc2467e4fb8 sp=0xc2467e4fa0
...additional frames elided...

goroutine 5 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208066fa0)
/usr/lib/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
/usr/lib/go/src/database/sql/sql.go:452 +0x31c
exit status 2

----
Should I do something for migration?

**Comment by jinzhu** [comment]
This should be fixed, sorry for the problem.

Thank you.

**Comment by dorajistyle** [comment]
Thanks a lot!
