### ISSUE TITLE
CREATE TABLE problem

### ISSUE THREAD

**Issue by fire988** [jinzhu/gorm#431]
package main

import (
	"fmt"
	_ "github.com/go-sql-driver/mysql"
	"github.com/jinzhu/gorm"
)

type Table_common_member struct {
	ID       int    ``
	Email    string `sql:"type:char(40)  ;not null  ; default:'' "`         // key不支持
	Username string `sql:"type:char(15)  ;not null  ; default:'' ; unique"` //	 邮箱
}

func main() {
	//引擎
	db, err := gorm.Open("mysql", "jamie:qwer1234@/test?charset=utf8&parseTime=True&loc=Local")
	db.LogMode(true)
	if err != nil {
		fmt.Println("err:", err)
		return
	}
	db.DropTableIfExists(&Table_common_member{})
	db1 := db.CreateTable(&Table_common_member{})

	fmt.Println(db1)
}

//program ablove will cause a problem, The table will not be created. because the statement is wrong,
"unique" and "default" will conflict.

**Comment by fire988** [comment]
modify model_struct.go line 319 as below can fix this.

additionalType = additionalType  + " " + "DEFAULT " + value

**Comment by jinzhu** [comment]
Thank you for your report, this should been fixed.
