### ISSUE TITLE
Query related object using struct field name failed.

### ISSUE THREAD

**Issue by li3p** [jinzhu/gorm#434]
I have to structs defined as following:
```
type Story struct {
	Id        uint32 `gorm:"column:st_id; primary_key"`
	Title     string `gorm:"column:st_title;size:255" sql:"not null"`
	Value     uint32 `gorm:"column:st_value" sql:"not null;default:0;type:int unsigned"`
	Points    uint32 `gorm:"column:st_points" sql:"not null;default:0;type:int unsigned"`
	Accptance string `gorm:"column:st_acceptance;size:255" sql:"not null;type:text"`
	State     uint8  `gorm:"column:st_state"`
	PageId    uint32 `gorm:"column:st_page_id" sql:"not null;default:0;type:int unsigned"`
	Content   Page
}

type Page struct {
	Id           uint32    `gorm:"column:page_id;primary_key" sql:"type:int unsigned auto_increment"`
	Namespace    int32     `gorm:"column:page_namespace" sql:"not null;default:0"`
	Title        string    `gorm:"column:page_title;size:255" sql:"not null"`
	Views        uint64    `gorm:"column:page_views" sql:"not null; default:0; type:bigint unsigned"`
	Edits        uint64    `gorm:"column:page_edits" sql:"not null;default:0;type:bigint unsigned"`
	Latest       uint32    `gorm:"column:page_latest" sql:"not null;default:0;type:int unsigned"`
	Len          uint32    `gorm:"column:page_len" sql:"not null;default:0;type:int unsigned"`
	ContentModel string    `gorm:"column:page_content_model" sql:"not null;default:'markdown';size:32"`
	CreateAt     time.Time `gorm:"column:page_created"`
	UpdateAt     time.Time `gorm:"column:page_updated"`
	DeleteAt     time.Time `gorm:"column:page_deleted"`
}
```

Now if I query related Page of Story object like this:
`db.Model(&story).Related(&page, "PageId")`
it does not work, still using the Story.Id field. 

If I change it to : 
`db.Model(&story).Related(&page, "st_page_id")`
that worked. 

And I also have  other two questions : 
1. how could I define a integer column as unsigned ? Even I defined a field of a struct as uint32/uint64, the generated sql of Create Table is still `int` or `bigint`  without the `unsigned` keyword. 
2. About the CreateAt field, if I changed its table field name by specifying `gorm:"column:page_created"` , then gorm will not automatically create a creation time for this field right?

**Comment by jinzhu** [comment]
> Query related object using struct field name failed

Should been fixed

> 1. how could I define a integer column as unsigned ? Even I defined a field of a struct as uint32/uint64, the generated sql of Create Table is still int or bigint without the unsigned keyword. 

Use sql tag

> 2. About the CreateAt field, if I changed its table field name by specifying gorm:"column:page_created" , then gorm will not automatically create a creation time for this field right?

Gorm will automatically generate it

Thank you
