### ISSUE TITLE
Too many connections issue.

### ISSUE THREAD

**Issue by Kaustubh-Deshmukh** [jinzhu/gorm#435]
I am getting too many connections issue at large scale. I am using joins. 

These are some of the errors I am getting. 
```
pq: remaining connection slots are reserved for non-replication superuser connections 
pq: too many connections for the role 
```

I have set max open connections to 20. I am getting this error extensively, I have to kill all the connections. Even after that 20 connections are acquired rapidly.

**Comment by jinzhu** [comment]
Sounds like you are connecting database for each time you use it?
