### ISSUE TITLE
Relations are broken.

### ISSUE THREAD

**Issue by dorajistyle** [jinzhu/gorm#437]
I updated gorm to 7d16055 from 087b708.

It seems to works well.

But I found some fuctions are broken on relations.

22b1a93e03dd316f44ddefbbc583d49935c47398 also not working.

# Association appending broken.

type User struct {
	Likings     []User     `gorm:"foreignkey:userId;associationforeignkey:follower_id;many2many:users_followers;"`
}
user := &.User{}
db.First(user, form.UserId)
db.Model(user).Association("Likings").Append(likingUser)

appending not works.

# Wrong count.
currentUserlikedCount := db.ORM.Model(&article).Where("id =?", currentUserId).Association("Likings").Count()

It should return 0 if article has no likings. but returns 1.

My application works fine in 087b708.

Update history about 087b708 to 7d16055
https://github.com/jinzhu/gorm/issues/428

**Comment by jinzhu** [comment]
Hello @dorajistyle 

Could you confirm if there are still any issues? as this is tested in tests, and should works.

Please reopen this issue if still have problem.

**Comment by dorajistyle** [comment]
I updated gorm to ede940e82d978b7f414dc05f7de1e2d33702e6c0.
It still not working.
It works at 087b7083ad1154ff0573d560b64310e4869a2820 well.

I got a runtime error below.

Panic recovery -> runtime error: invalid memory address or nil pointer dereference
/go/src/runtime/panic.go:423 (0x402b169)
	gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/go/src/runtime/panic.go:42 (0x4029829)
	panicmem: panic(memoryError)
/go/src/runtime/sigpanic_unix.go:24 (0x403ffe9)
	sigpanic: panicmem()
/golang/src/github.com/dorajistyle/goyangi/.vendor/src/github.com/jinzhu/gorm/association.go:184 (0x43dc4c1)
	(*Association).Count: relationship := association.Field.Relationship


The error occurs in method below.


// RetrieveLikings retrieves likings.
func RetrieveLikings(item interface{}, currentPages ...int) ([]model.User, int, bool, bool, int) {
	var users []model.User
	var currentPage int
	if len(currentPages) > 0 {
		currentPage = currentPages[0]
	} else {
		currentPage = 1
	}
	count := db.ORM.Model(item).Association("Likings").Count() // error here
	offset, currentPage, hasPrev, hasNext := pagination.Paginate(currentPage, config.LikingPerPage, count)
	db.ORM.Limit(config.LikingPerPage).Order(config.LikingOrder).Offset(offset).Select(config.UserPublicFields).Model(item).Association("Likings").Find(&users)
	return users, currentPage, hasPrev, hasNext, count
}

User model below.
type User struct {
	Id              int64     `json:"id"`
Likings     []User     `gorm:"foreignkey:userId;associationforeignkey:follower_id;many2many:users_followers;"`
}

Take care.
