### ISSUE TITLE
Associations belongsTo/hasOne collection issue

### ISSUE THREAD

**Issue by cadizjavier** [jinzhu/gorm#441]
I asked [this question](http://stackoverflow.com/q/29435783/1373105) too in StackOverflow if you want to check but i haven't received any answer yet. My issue/question is the following:

The relation is simple. One Town has multiple Places and one Place belongs to one Town.

    type Place struct {
      ID          int
      Name        string
      Description string
      Town        Town
    }

    type Town struct {
      ID   int
      Name string
    }
Now i want to query all places and get along with all their fields the info of the corresponding town. This is my code:

    db, _ := gorm.Open("sqlite3", "./data.db")
    defer db.Close()

    places := []Place{}
    db.Find(&places)
    mt.Println(places)

And i'm receiving this:

`[{1 Place1 {0 }} {2 Mares Place2 {0 }}]`

But i'm expecting to receive something like this (both places belongs to the same town):

`[{1 Place1 {1 Town1}} {2 Mares Place2 {1 Town1}}]`

How can i do such query ? I tried using Preloads without success.

**Comment by jinzhu** [comment]
Hi,

You need to have TownID in `Place`, like this:

```go
type Place struct {
  ID          int
  Name        string
  Description string
  TownID int
  Town        Town
}

// then query it like this
db.Preload("Town").Find(&places)
```
