### ISSUE TITLE
Possibility to use Related/Association with model slices in Many To many relation

### ISSUE THREAD

**Issue by crystalin** [jinzhu/gorm#445]
The purpose is to query (in the test struct) **many** users **including** their languages:
(In the TestManyToMany)
```go
	var users []User
	DB.Find(&users).Association("Languages").Find(&newLanguages)
	if len(newLanguages) != len([]string{"ZH", "EN"}) {
		t.Errorf("Should be able to find many to many relations")
	}
```

This is now giving the "primary key can't be nil" issue

**Comment by jinzhu** [comment]
refer https://github.com/jinzhu/gorm#association-mode
