### ISSUE TITLE
How to avoid updating a relation

### ISSUE THREAD

**Issue by ronna-s** [jinzhu/gorm#447]
My problem is referring to a many 2 many relation, but it's probably relevant to any other type of relation.
I have a many 2 many relation between 2 tables, and whenever I save a model corresponding with the first, it automatically updates the relations in the second. My problem is that nothing ever changes in the related table, so I want to avoid this update entirely.

Any way to do that?

**Comment by jinzhu** [comment]
You could use `Select` or `Omit` to select which columns to update or ignore.

**Comment by kync** [comment]
For version 1.9.1 auto update can be disable handily by setting _association_autoupdate_ as false. `db.Set("gorm:association_autoupdate", false).Create(&user)`

http://gorm.io/docs/associations.html#Skip-AutoUpdate

**Comment by gayanhewa** [comment]
Can we do this globally for all models?
