### ISSUE TITLE
uint64 is not unsigned in database

### ISSUE THREAD

**Issue by nkovacs** [jinzhu/gorm#449]
I used automigrate to create a table in a mysql database. The `uint64` columns were created as `bigint(20)`. I was expecting them to be `bigint(20) unsigned`

```go
type TestRun struct {
	ID        uint64
	StartedAt int64
	EndedAt   int64
}

db.AutoMigrate(&TestRun{})
```

I know I can override the type with a tag, but shouldn't uints be converted to unsigned by default?
See also #201.

**Comment by jinzhu** [comment]
Just added that support for mysql, thank you for your report.
