### ISSUE TITLE
Create(): reflect: call of reflect.Value.Interface on zero Value

### ISSUE THREAD

**Issue by xaionaro** [jinzhu/gorm#451]
I'm a newbie in Golang and Gorm. Can you give an advice how to debug this error (it appears while trying to call `Create()`)?

    (/home/voip/gocode/********/src/voip/app/controllers/dbs.go:98) 
    [2015-04-13 21:12:17]  field value not valid 
    ERROR 2015/04/13 21:12:17 panic.go:29: reflect: call of reflect.Value.Interface on zero Value
    /home/voip/gocode/********/src/voip/app/controllers/dbs.go:98 (0x522f50)
            Dbs.saveNewUnits: transaction.Debug().Create(&unit);

The `transaction` is:

    transaction := app.DB_local.Begin();

The `app.DB_local` is:

    var DB_local  gorm.DB;

**Comment by xaionaro** [comment]
This's the `unit` structure:

    type Unit struct {
    // DB data:
            UnitId          int             `gorm:"primary_key"`;
            CodeStr         string          `db:"unique_index"`;
            Name            string;
            Shortname       string;
            Theme           string;
            ParentsCodeStr  string;
    
    // Additional data:
            Code            UnitCode        `db:"-"`;
            Parents         []*Unit         `db:"-"`;
            Children        []*Unit         `db:"-"`;
    }

**Comment by xaionaro** [comment]
The same problem with:

    app.DB_local.Debug().Create(&unit);

instead of:

    transaction.Debug().Create(&unit);

**Comment by xaionaro** [comment]
Hm. The bug is somehow bypassed by renaming field "UnitId" to "Id". Look like a GORM bug. Should I post any additional information?

**Comment by jinzhu** [comment]
```go
package main

import (
        "github.com/jinzhu/gorm"
        _ "github.com/mattn/go-sqlite3"
)

type Unit struct {
        // DB data:
        UnitId         int    `gorm:"primary_key"`
        CodeStr        string `db:"unique_index"`
        Name           string
        Shortname      string
        Theme          string
        ParentsCodeStr string

        Parents  []*Unit `db:"-"`
        Children []*Unit `db:"-"`
}

func main() {
        DB, _ := gorm.Open("sqlite3", "/tmp/gorm.db")
        DB.AutoMigrate(&Unit{})

        unit := Unit{}
        DB.Debug().Save(&unit)
}
```

seems like that works for me?

the generated table is `CREATE TABLE "units" ("unit_id" integer,"code_str" varchar(255),"name" varchar(255),"shortname" varchar(255),"theme" varchar(255),"parents_code_str" varchar(255) , PRIMARY KEY (unit_id));`
