### ISSUE TITLE
Create setting ID to 0 if primary field not auto-increment

### ISSUE THREAD

**Issue by chao-mu** [jinzhu/gorm#453]
Given the following model:
```
type Foo struct {
        ID int
}
```

Backed by the following table with a primary key without auto-increment (in MySQL)...
```
CREATE TABLE `foos` (
  `id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

The following call to create will wipe out the value set for Id
```
foo := Foo{ID: 23}

fmt.Println("ID before Create:", foo.ID)
err = db.Debug().Create(&foo).Error
if err != nil {
        log.Fatal(err)
}
fmt.Println("ID after Create:", foo.ID)
```

Producing the following output:
```
ID before Create: 23
(/redacted/isolate.go:46) [2015-04-14 18:35:56]  [0.71ms]  INSERT INTO `foos` (`id`) VALUES ('23')
ID after Create: 0
```

From my research, the problem seems to lie in callback_create.go's function Create:
```
    if scope.Dialect().SupportLastInsertId() {
      if result, err := scope.SqlDB().Exec(scope.Sql, scope.SqlVars...); scope.Err(err) == nil {
        id, err := result.LastInsertId()
        if scope.Err(err) == nil {
          scope.db.RowsAffected, _ = result.RowsAffected()
          if primaryField != nil {
            scope.Err(scope.SetColumn(primaryField, id))
          }
        }
      }
````

Note how the value of result.LastInsertId is used for the "primaryField". This value will, in the case described, not reflect the value of the inserted Id.

**Comment by jinzhu** [comment]
I get this `CREATE TABLE `foos` (`id` int AUTO_INCREMENT , PRIMARY KEY (id))`

with this script, could you please try it:

```go
package main

import (
	_ "github.com/go-sql-driver/mysql"
	"github.com/jinzhu/gorm"
	_ "github.com/mattn/go-sqlite3"
)

type Foo struct {
	ID int
}

func main() {
	// DB, _ := gorm.Open("sqlite3", "/tmp/gorm.db")
	DB, _ := gorm.Open("mysql", "gorm:gorm@/gorm?charset=utf8&parseTime=True&loc=Local")
	DB.Debug().DropTable(&Foo{})
	DB.Debug().AutoMigrate(&Foo{})
}

```

**Comment by chao-mu** [comment]
In your example you're creating an auto-incrementing ID column. The bug is when there is NOT an auto-incrementing ID column - in that case the specified ID gets overwritten.

**Comment by jinzhu** [comment]
How did you created the table that without the auto-incrementing option? and of course, if it is not auto-incrementing, you have to specify an ID for it when creating a new record

**Comment by chao-mu** [comment]
Please see the issue I posted above. The SQL snippet is how to create a table and in my code I explicitly set the ID. I have also quoted the GORM code where the bug overwrites the ID I set.
