### ISSUE TITLE
按照readme中的例子试了下，竟然跑不通

### ISSUE THREAD

**Issue by ElvizLai** [jinzhu/gorm#455]
readme中的例子都无法正常运行，基本上就没啥继续用的信心了

**Comment by davyzhang** [comment]
可以去看看测试用例,文档中的例子没有连贯性
比如
https://github.com/jinzhu/gorm/blob/master/main_test.go
这是目前我用过最顺手的golang的orm

**Comment by jinzhu** [comment]
@ElvizLai 其实我个人感觉readme你读读应该可以会了，不过要是一点go的基础也没有的话，可能有点问题，但稍微学点应该没有什么问题吧？

有具体的问题可以告诉我。文档只是最快的把最重要的信息展现过用户，从来不可能会包含所有的内容
