### ISSUE TITLE
Clarify how save and update cascades to "has one" relations

### ISSUE THREAD

**Issue by ansel1** [jinzhu/gorm#460]
From the docs, it's a little unclear what to expect when you have "has one" relations defined.  Does the save/update operation always cascade down to the related, nested struct?  What if nested struct is all zero values (because it was not loaded from the db)?  What if the nested field is a pointer to a struct and the field value is nil?  Will a delete on the parent cascade?  Thanks.

**Comment by jinzhu** [comment]
It will skip save relations if it is zero value, so won't delete on the parent cascade
