### ISSUE TITLE
Document Thread Safety/Pooling

### ISSUE THREAD

**Issue by chao-mu** [jinzhu/gorm#461]
This is a ticket on a gap in the otherwise lovely documentation.

I noticed a lack of mention of thread safety or pooling in the documentation.

It looks like sql.Open is being used which states "The returned DB is safe for concurrent use by multiple goroutines and maintains its own pool of idle connections. Thus, the Open function should be called just once. It is rarely necessary to close a DB." 

But it seems worth documenting if gorm.DB stores any data without returning a clone or something else that might break multi-threaded access.

**Comment by jinzhu** [comment]
gorm.DB will return a clone for all queries, so it should be thread safe.

let me think how to include it into the README.

**Comment by cookingkode** [comment]
hi @jinzhu i assume like sql.Open i can keep a global gorm.DB object to pass queries to, from multiple goroutines. I know you already alluded to this, just confirming.
