### ISSUE TITLE
Is there a way to save a model without updating its foreign objects?

### ISSUE THREAD

**Issue by laurentsigal** [jinzhu/gorm#467]
I have a main object that I load, as well as some of its foreign objects.

I'd like to be able to save this model without recursively saving all its foreign objects (which have not changed).
Is there a way to achieve this?

BTW thanks a lot for this library, it is very powerful!

**Comment by jinzhu** [comment]
You could use `Select` or `Omit` to select which columns to save or ignore.

**Comment by laurentsigal** [comment]
Awesome thanks a lot!
