### ISSUE TITLE
Could not use default value for bool/int fields

### ISSUE THREAD

**Issue by cw35** [jinzhu/gorm#469]
Hi,

As you mentioned in the home page, "update SQl will ignore these fields if is set blank data"...

The problem is, if I wanna use a bool field with some default value, or, int field, and then, this field could never be set to be 0 with Update function.

As for me, this isBlank is not appropriate. Or maybe, you could provide a new function to save without checking value isBlank, like UpdateWithoutCheckingBlank?

Many thx.

**Comment by jinzhu** [comment]
You could just use `Save`, or if you are sure want to update some columns, you could use `Select`  like `db.Select("IsAdmin").Model(&user).Update(User{IsAdmin: false})`

**Comment by ansel1** [comment]
@jinzhu I've been struggling with this for a while.  I've tried `db.Select("Enabled").Model(&user).Update(User{Enabled:false})` (with and without the `Select`), I've tried `...Update("Enabled",false)`, I've tried `...Update(map[string]interface{}{"Enabled":false})`, I've tried setting `user.Enabled = false` then `db.Save(&user)`. (I'm running against postgres)

I have not been able to get any of those ways to update a boolean column to false.  It looks like raw sql is the only way to do it.  Looking at the tests, it doesn't look like there is a test for updating bool columns.

**Comment by dvdplm** [comment]
This is definitely a problem. If I have a boolean column with a default of `false` I can update it to false, but as soon as I try to set it back to false, gorm will see that there's a default value and *omit the column* from the update clause, leaving the value still set to `true`.
Boolean columns with default values should never be omitted when saving/updating.

**Comment by dvdplm** [comment]
Looking at the code (https://github.com/jinzhu/gorm/blob/master/callback_update.go#L54) I think this issue affects all fields, not only booleans. If I have a text column with a default value of "beef" and then I update it with a value of "" (empty string, si `field.IsBlank` is true) then I'd still expect Gorm to update the column.

The create case is different and the only place where I'd expect default column values to come into play.

If I change Gorm callback_update.go to this, my issue with booleans is fixed:

```
fields := scope.Fields()
for _, field := range fields {
	if scope.changeableField(field) && !field.IsPrimaryKey && field.IsNormal {
		isBool := field.HasDefaultValue && field.Field.Type().Kind() == reflect.Bool
		if isBool || !field.IsBlank || !field.HasDefaultValue {
			sqls = append(sqls, fmt.Sprintf("%v = %v", scope.Quote(field.DBName), scope.AddToVars(field.Field.Interface())))
		}
… …
```
However, I think the real fix is to stop checking for default values all together for the update case.

@jinzhu would you be open to a PR to address this?

**Comment by cw35** [comment]
@dvdplm in fact, not just bool, but also Int, etc.

And this may be not secure. While you are creating a new instance, the default value may not work, you have to assign the default value to you instance...

As for me, I changed all my Save with Update, or UpdateColumn. Hope this may help...

**Comment by dvdplm** [comment]
@cw35 yes, it can lead to bugs that hard to find. Unfortunately we cannot stop using `Save` everywhere.
@jinzhu would you accept a PR for this? :)

**Comment by ansel1** [comment]
I'm honestly still a bit unclear where this issue crops up and where it doesn't, but I did only now realize that specifying a default value in `sql:` annotations has an impact on it.  Hoping this saves something else some time:

I was dealing with updating boolean columns with this helper function:

```go
// Utility function for updating boolean columns.  Unfortunately, updating bool
// columns is tricky, because gorm has a tough time detected whether they are changed.
func UpdateBoolColumns(db *gorm.DB, model interface{}, columns map[string]bool) *gorm.DB {
	selects := []interface{}{}
	for key := range columns {
		selects = append(selects, key)
	}
	log.Trace("updating bool columns", "model", model, "columns", columns, "selects", selects)
	return db.Model(model).Select("updated_at", selects...).Update(columns)
}
```

But I found that was working for some columns and not others.  It turns out, the column was ignored if you specified a default column value to gorm via the sql annotations, and were trying to update an existing record's column to that value, i.e.:

```go
type MyStruct struct {
  ID int
  Cool bool `sql:"default:false"`
}

func notcool(db *gorm.DB) {
  c := Cool{ID: 1}
  db.Model(&c).Select("cool").Update("cool", false)  // won't work!!
}
```

We moved to a different tool for schema migrations, so we didn't need the annotations anymore.  We've removed them all, and it's working ok now.
