### ISSUE TITLE
Tag release?

### ISSUE THREAD

**Issue by thoas** [jinzhu/gorm#474]
Hi,

I'm looking to use gorm in a big project, I have noticed you don't tag your release which is an issue for us to choose a stable version.

Is that something you could do in the future?

Thank you

**Comment by pjebs** [comment]
Now that your package is very mature, I agree that you should be using tags for versioning.
You should also be using: http://labix.org/gopkg.in
so instead of 
"go get -u github.com/jinzhu/gorm"
it can be 
"go get -u gopkg.in/gorm.v1"

**Comment by amoghe** [comment]
+1.

I previously tried to make a case for it [here](https://github.com/jinzhu/gorm/issues/373#issuecomment-88295379). I guess it didn't get noticed because the bug was closed before I commented.

The short version is that while gopkg.in does not provide reproducible builds, it does provide API version (and therefore stability), which is sufficient for a some (large?) set of developers.

**Comment by danielmt** [comment]
I'm also looking to use gorm in a big project, but, without a version tag it really hurts.
I can't pin a specific version to a project, and I cannot guarantee it's not going to break all of a sudden because of api changes or unstable/experimental code.

Please, TAG it. :)

Please? :P

**Comment by thoas** [comment]
@jinzhu can we have your feedback about this plz?

Thank you :)

**Comment by preppypiet** [comment]
Yeah I love me some tags as well :) Please? :)

**Comment by moosilauke18** [comment]
I agree with everyone else. It would be nice to know which ref I can use that won't add potentially breaking features. Thanks for the great package!

**Comment by gillesfabio** [comment]
+1. Please, please.

**Comment by jinzhu** [comment]
Although this have been really done, we have a good start, refer: https://github.com/jinzhu/gorm/pull/794

I am going to release the first public release in the next few months. 

Any comments are welcome in that thread.
