### ISSUE TITLE
Unnecessary precision in float values

### ISSUE THREAD

**Issue by sathishvj** [jinzhu/gorm#477]
A row is defined in the database like this: myfield float DEFAULT NULL
This field has a value of 0.2

A type definition has a field like this: MyField   float64   `gorm:"column:myfield"`
When we get this here, it shows a value like 0.20000000298023224.

How do we get it to be with normal precision?

I tested this out with a small piece of code as below and am unable to see the same issues:
```
CREATE TABLE test_numbers (
          id bigint(20) NOT NULL AUTO_INCREMENT primary key,
          f float default null,
          fp float(13,8) default null,
          d double default null,
          dp double precision(13,8) default null
        ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```
-----------------
```
package main

import (
	"fmt"

	_ "github.com/go-sql-driver/mysql"
	"github.com/jinzhu/gorm"
)

type Model struct {
	F  float64 `gorm:"column:f"`
	FP float64 `gorm:"column:fp"`
	D  float64 `gorm:"column:d"`
	DP float64 `gorm:"column:dp"`
}

func main() {
	connStr := "root:@tcp(localhost:3306)/mydb?parseTime=true"
	db, err := gorm.Open("mysql", connStr)

	if err != nil {
		fmt.Println(err)
		return
	}

	var models []Model
	db.Table("test_numbers").Find(&models)
	for _, v := range models {
		fmt.Printf("\n%+v\n", v)
	}
}
```

**Comment by sathishvj** [comment]
Not sure why I was unable to replicate it in independent code, but I changed the sql field type to double in my other code and it started working as expected with only required precision.

**Comment by alecha** [comment]
I've the same issue, using float32 or float64 does not solve, how I can do? the SQL created field (using MySql) is double instead of float...

**Comment by imboooooo** [comment]
I've the same issue, to translate type data float in sql to gorm model, the data IconPosX and IconPosY always 0.
this my . struct :
type Icons struct {
Id int gorm:"column(id);
Name string gorm:"column(name);
IconPosX float32 gorm:"column(icon_pos_x);FLOAT(5,2);"
IconPosY float32 gorm:"column(icon_pos_y);FLOAT(5,2);"
}
in the sql database IconPosX and IconPosY type data is FLOAT(5,2)
