### ISSUE TITLE
db.Exec doesn't work as shown

### ISSUE THREAD

**Issue by HangingClowns** [jinzhu/gorm#481]
Using Postgres with uuid. Here's a sample struct:
``` go
type SomeTable struct {
SomeTableId string `gorm:"primary_key"`
Field     string `sql:"not null"`
}
```
```go
// I've tried this:
db.Exec("INSERT INTO some_table (some_table_id, field) VALUES (uuid_generate_v4(), ?) RETURNING some_table_id;", a.Field).Row().Scan(&a.SomeTableId)
}
// and this:
db.Exec("INSERT INTO some_table (some_table_id, field) VALUES (uuid_generate_v4(), ?) RETURNING some_table_id;", a.Field).Scan(&a)
```
Neither of these seem to work. Because we're using a UUID in Postgres, it seems to cause a ton of issues.

Interesting, though, is that if I use the Row() method, it will give me a strange query which LogMode shows as: `SELECT  * FROM "" `. I've also tried adding `RETURNING some_table_id::varchar`, in case it doesn't like that it's a uuid, i try to turn it in to a string, still no use.

Any ideas? BTW, I have also ran the queries, barebones, that I got from LogMode, and they seem to work, so my query should be good, just can't seem to get the returning ID which the DB should generate for me.

**Comment by wari** [comment]
I got problems with db.Exec() also, fixed with db.Raw(). Try it, may work for you.

**Comment by bkalis** [comment]
my 2 cents:  I also use UUIDs for primary keys. Since I need multi SQL platform support, I generated the UUIDs in Go code.  It seems to be working OK for me so far.  There are one issue that Jinzhu fixed yesterday.  See the sample code at: https://github.com/jinzhu/gorm/issues/509
Good luck!
Biju

**Comment by jinzhu** [comment]
Yes, you should use `Raw` here, `Exec` will run the SQL you passed in, and won't return it as `Row`
