### ISSUE TITLE
Int composite primary key

### ISSUE THREAD

**Issue by everclear** [jinzhu/gorm#482]
int based composite primary key columns are flagged auto increment. So they can't be created.

type ContactSchedule struct {
	ContactID  int64 `gorm:"primary_key"`
	ScheduleID int64 `gorm:"primary_key"`
}

**Comment by jinzhu** [comment]
You could disable the auto increment with tags.

**Comment by hermanbergwerf** [comment]
@jinzhu that doesn't seem to play nicely with different databases. For example, I use MariaDB (MySQL) on my local machine but the program must also be compatible with PostgreSQL which we use in our cloud infrastructure.
