### ISSUE TITLE
Not Null tags getting ignored on AutoMigrate

### ISSUE THREAD

**Issue by codingrogue** [jinzhu/gorm#486]
I have the following model:
```
type Location struct {
	ID        int        `json:"id",gorm:"primary_key"`
	Name      *string    `json:"name",sql:"size:255;not null"`
	Longitude *float64   `json:"longitude",sql:"not null"`
	Latitude  *float64   `json:"latitude",sql:"not null"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt"`
}
```
and when I AutoMigrate/Create it:
```
DAO.DB.AutoMigrate(&Location{})
```
I get the following table output:
![screen shot 2015-05-11 at 23 58 13](https://cloud.githubusercontent.com/assets/1425202/7575958/9c5a442a-f839-11e4-99fe-17984f791338.png)

Any ideas :) ?

**Comment by jinzhu** [comment]
Hello @codingrogue 

AutoMigrate won't update current column to make sure your data to be safe.

But seems like update `NOT NULL` doesn't really matter, I will look into that to make `AutoMigrate` update some things that won't hurt data

**Comment by codingrogue** [comment]
But I deleted the database and recreated it with Automigrate. I thought when it's creating a fresh DB it's considering all tags including not-null?

**Comment by codingrogue** [comment]
My mistake! I used comma to separate the tags instead of space! Now the sql tags are getting interpreted correctly and not-null works now!
