### ISSUE TITLE
The 1 + N problem

### ISSUE THREAD

**Issue by nicholasf** [jinzhu/gorm#487]
Hi jinzhu,

I can't find a way to model the query of an association that results in a left outer join. I assumed that Preload might solve this problem - https://github.com/jinzhu/gorm#preloading-eager-loading - but it doesn't seem to.

Am I missing something? What is your current strategy for automating 1 + N loads for associations? Is there a way, for example, to model the User and Address has one example here - https://github.com/jinzhu/gorm#has-one - that results in a single query as a left outer join between User and Address?

I understand that this is a hard problem to solve. If you don't currently have a strategy for it we would like to understand to perhaps contribute.

Cheers,
Nicholas

**Comment by nicholasf** [comment]
I just found https://github.com/jinzhu/gorm#joins . So I think the fallback is to handwrite these queries?

**Comment by jinzhu** [comment]
Hello @nicholasf 

The `Preload` could be used to resolve this issue. Although we are not using a single query to get user, address, using two queries.

For example:

`db.Preload("Addresses").Preload("Profile").Find(&users)`

It will generate SQL:

```
select * from users;
select * from addresses where user_id in (1,2,3....)
select * from profiles where user_id in (1,2,3....)
```
