### ISSUE TITLE
The created_at column is changed when updating a record

### ISSUE THREAD

**Issue by tland** [jinzhu/gorm#489]
Hi,

I have a postgres table which contains a created_at column, updated_at and deleted_at column. Since the data was imported to the table, the value of the created_at column is set to NULL, which I think is okay. When I do a sql update to a record, the record's created_at column is also being updated. I know this cause is probably that I don't have valid values set for the created_at column in the first place. However, I wonder if it would be better (or safe) to just ignore the created_at column when performing a sql update? 

    CreatedAt            time.Time  `json:"created_at,omitempty"`
    UpdatedAt            time.Time `json:"updated_at,omitempty"`
    DeletedAt            *time.Time `json:"deleted_at,omitempty"`

The actual logic is like below

    db.DB.Offset(start).Limit(limit).Order("id asc").Find(&record)
    ....
    db.DB.Save(&record)

The sql log is something like this
    
    UPDATE "table" SET "created_at" = '0001-01-01T00:00:00Z', "updated_at" = '2015-05-14T00:33:33-04:00', "deleted_at" = '<nil>'...

**Comment by funnythingz** [comment]
me too...
still unresolved ?

**Comment by coquifrogs** [comment]
This is because your model doesn't allow the CreatedAt to be null so it is defaulting to the 0 value for a time.Time when you are getting it back from Find.  It's the same as if you just make an instance of the record struct.  Then when you are saving it uses that "0" value.

**Comment by tland** [comment]
@coquifrogs I think your explanation makes sense. Making CreatedAt a pointer type *time.Time does resolve the problem. I am going to close the ticket. Thanks again.

**Comment by funnythingz** [comment]
:+1:
