### ISSUE TITLE
.Table is wrapping a statement in quotes, how to bypass?

### ISSUE THREAD

**Issue by dougbarrett** [jinzhu/gorm#490]
I have some specific custom code that looks similar to:

~~~~
Table(fmt.Sprintf(`(SELECT ip_id, SUM(count) AS count FROM stats_ip
			WHERE property_id = '%v' AND category_id = '%v' AND action_id = '%v' AND timeslice >= '%s' %s
			GROUP BY ip_id) g1`, p.Id, catid, actid, today, zoneQuery))
~~~~

This worked perfectly, but there must have been a commit that I pulled in locally that I didn't on production, and now this is broken because it wraps the output in tick marks, like so:

~~~~
FROM `(SELECT ip_id, SUM(count) AS count FROM stats_ip
			WHERE property_id = '3' AND category_id = '2' AND action_id = '17' AND timeslice >= '2015-05-14 07:00:00 +0000 UTC' 
			GROUP BY ip_id) g1`
~~~~

Is it possible that I can quickly set something for it to not do this and revert back to the old way, or do I need to rewrite as a DB().Query() command?

**Comment by jinzhu** [comment]
Sorry for the trouble, just fixed that.

**Comment by dougbarrett** [comment]
Just an FYI, not sure how but this locked things up.  I'm just rewriting it as custom queries, not sure if you want to revert this commit or not.

Thanks!
