### ISSUE TITLE
AutoMigrate should return an error when it skips newly added FK fields

### ISSUE THREAD

**Issue by tp** [jinzhu/gorm#493]
Relates to #349 and #450.

If automatically migrating FK fields is not yet possible / done, I think gorm should at least return an error.

Otherwise it will just silently start dropping parts of the inserted objects, when using the not-yet-migrated table.

**Comment by jinzhu** [comment]
@tp return an error will revert the created table, I think this won't be the way we will go.

And if you want the FK constraints, you still could create it manually.
