### ISSUE TITLE
Create doesn't add columns for associations

### ISSUE THREAD

**Issue by tp** [jinzhu/gorm#494]
Using `gorm` with Postgres 9.4.1.

structs:
```
type TestType struct {
	ID        int
	Users     []NewUser
	OtherUser NewUser
}

type NewUser struct {
	ID   int
	Name string
}
```

CreateTable runs without errors:
```
	err = db.CreateTable(&NewUser{}).Error
	if err != nil {
		log.Println(err.Error())
	} else {
		log.Println("created table new_user")
	}

	err = db.CreateTable(&TestType{}).Error
	if err != nil {
		log.Println(err.Error())
	} else {
		log.Println("created table test_type")
	}
```

But the created table "test_type" is missing columns for `users` and `other_user`.
```
                         Table "public.test_type"
 Column |  Type   |                       Modifiers
--------+---------+--------------------------------------------------------
 id     | integer | not null default nextval('test_type_id_seq'::regclass)
Indexes:
    "test_type_pkey" PRIMARY KEY, btree (id)
```

Though insertion with this worked fine (from a Go perspective, the value are of course missing in the DB :cry:):
```
	v := &TestType{
		Users: []NewUser{
			NewUser{Name: "User 1"},
			NewUser{Name: "User 2"},
		},
		OtherUser: NewUser{Name: "User 0"},
	}

	err = db.Create(v).Error
	if err != nil {
		log.Println(err.Error())
	} else {
		log.Println("inserted fine")
	}
```

And the new_user table is also empty
```
# select * from new_user;
 id | name
----+------
(0 rows)
```

I tried to base my code on the README example, but maybe I am missing something.

If this is not a simple bug, I think at least the docs and Error messages should be modified.

**Comment by TrungACZNE** [comment]
I'm having the same problem. The doc needs to be updated (I noticed there's a "Related" function but its doc doesn't help either)

**Comment by jinzhu** [comment]
You should define foreign keys in the struct, just like the document says.
