### ISSUE TITLE
Placing `.Where()` in wrong place in a chain returns unexpected results

### ISSUE THREAD

**Issue by mattbostock** [jinzhu/gorm#495]
The order of methods in a chained query can cause unexpected results. This makes query chains very prone to developer error, e.g. data intended to be filtered by user might be displayed by all users.

Please see mattbostock/leavediary@6e2d672 for an example.

**Comment by jinzhu** [comment]
You have to write conditions before query it from database? so you have to write it in correct order.

**Comment by mattbostock** [comment]
In this case, surely this should raise an error?
