### ISSUE TITLE
Using '.Pluck()' on "select distinct" query returns empty strings

### ISSUE THREAD

**Issue by ottokart** [jinzhu/gorm#496]
```go
phoneNumbers := []string{}
db.Select("DISTINCT phone_number").Where("name IN (?)", names).Find(&Client{}).Pluck("phone_number", &phoneNumbers)
```
...results in an array of empty strings.

**Comment by jinzhu** [comment]
should like this? 

`db.Where("name IN (?)", names).Find(&Client{}).Pluck("DISTINCT phone_number", &phoneNumbers)`

**Comment by ottokart** [comment]
Seems to work, thanks! Though it would be nice if it worked both ways. It's really easy to make this kind of mistake and it's only discovered if tests cover this.
