### ISSUE TITLE
Sequence Generator

### ISSUE THREAD

**Issue by vahid-sohrabloo** [jinzhu/gorm#498]
I not found Sequence in gorm. I think gorm must support Sequence;

**Comment by jinzhu** [comment]
Could you explain it more?

**Comment by vahid-sohrabloo** [comment]
In some DBMS such as postgresql or oracle use Sequence for auto increment 
http://www.postgresql.org/docs/9.4/static/functions-sequence.html

**Comment by jinzhu** [comment]
Hi @vahid-sohrabloo 

Then it could works if you are using sql expression https://github.com/jinzhu/gorm#update-with-sql-expression, or use default value with sql tag?

**Comment by vahid-sohrabloo** [comment]
@jinzhu yes we can use default value in sql tag
