### ISSUE TITLE
CreatedAt/UpdatedAt Naming

### ISSUE THREAD

**Issue by devchakraborty** [jinzhu/gorm#500]
Is it possible to use the timestamp-setting functionality on columns that aren't named created_at and updated_at? The ones I'm working with are called created and updated, for example.

**Comment by jinzhu** [comment]
You could create your callbacks, refer https://github.com/jinzhu/gorm/blob/master/callback_create.go#L99 https://github.com/jinzhu/gorm/blob/master/doc/development.md for how to
