### ISSUE TITLE
有没有可能修复一下检查table结构的sql代码打印信息

### ISSUE THREAD

**Issue by davyzhang** [jinzhu/gorm#501]
SELECT count(*) FROM sqlite_master WHERE tbl_name = 'static_logs' AND (sql LIKE '%!((MISSING)"updated_at" %!'(MISSING) OR sql LIKE '%!,(MISSING)"updated_at" %!'(MISSING) OR sql LIKE '%!((MISSING) updated_at %!'(MISSING) OR sql LIKE '%!,(MISSING) updated_at %!'(MISSING));

打印出来的都是%!(MISSING)

**Comment by jinzhu** [comment]
这个应该已经修复了。
