### ISSUE TITLE
Does not persist if one-to-many relation is a pointer

### ISSUE THREAD

**Issue by codepushr** [jinzhu/gorm#502]
I'm having the following problem, I want the relation collection to be a pointer, which works quite well for fetching but not for inserting! Example:

```
type Event struct {
    Locations *[]Location // one-to-many
}
```
This does not insert the record when I use Create! It prints `0` for the `id` and `0` for the `eventID` key.
I found a fix where I have to persist the locations AFTER persisting the event but I would like to use the "Associations will be inserted automatically" feature of GORM.

**Comment by jinzhu** [comment]
The Event don't have any other columns, could you write a runnable script that reproduce your problem?

**Comment by codingrogue** [comment]
Thanks for checking in, I will add a runnable script today when I get home!

**Comment by jinzhu** [comment]
@codepushr  just checked, seems should works with latest gorm

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/lib/pq"

	_ "github.com/mattn/go-sqlite3"
)

type User struct {
	gorm.Model
	Name  string `sql:"name"`
	Roles []*Role
}

type Role struct {
	gorm.Model
	UserID uint
	Name   string
}

func main() {
	// sqlite3
	db, _ := gorm.Open("postgres", "user=gorm DB.name=gorm sslmode=disable")
	// Logger
	db.LogMode(true)
	db.DropTable(&User{}, &Role{})
	db.AutoMigrate(&User{}, &Role{})

	db.Save(&User{Name: "user",
		Roles: []*Role{
			{Name: "role1"},
			{Name: "role2"},
		}})
}
```
