### ISSUE TITLE
Omit function

### ISSUE THREAD

**Issue by ghigt** [jinzhu/gorm#503]
Hi,

When I want to only `select` some columns, it works fine:
```go
db.Select("id, login").First(&g, id)
{ "id": 1,
  "login": "plop" }
```
But when I want to `omit`, it does not:
```go
db.Omit("id").First(&g, id)
{ "id": 1,
  "login": "plop",
  "password": "$2a$10$rs2..." }
```

Am I doing something wrong?

**Comment by jinzhu** [comment]
Omit is only used for update.
