### ISSUE TITLE
Add a way to get the query string

### ISSUE THREAD

**Issue by solher** [jinzhu/gorm#506]
Hi,

I was wondering I there was a way to simply generate an SQL query with Gorm without effectively executing it on the DB.
I would like to execute nested queries without the overhead of the execution of the first query, the result processing, the execution of the query after using the results, processing another time, etc. 

Something like that:
generatedSql, err := db.Select("id").Find(&Users).GetSQL()
err = db.where("id IN (?)", generatedSql).Delete(&User{})

(The example is stupid but you see the point)

Thanks

**Comment by jinzhu** [comment]
refer https://github.com/jinzhu/gorm/issues/427

**Comment by HelloHaiGG** [comment]
遇到同样的问题，请问这个怎么搞呢？我只想要拼接好的sql语句。 https://github.com/jinzhu/gorm/issues/427   （404）

**Comment by jinzhu** [comment]
https://gorm.io/docs/session.html#DryRun

**Comment by HelloHaiGG** [comment]
我有看到这个文档，但是我的db对象为什么没有Session呢？是我饮用的版本不对吗？我引用的库：github.com/jinzhu/gorm v1.9.11

**Comment by HelloHaiGG** [comment]
我有看到这个文档，但是我的db对象为什么没有Session呢？是我引用的版本不对吗？我引用的库：github.com/jinzhu/gorm v1.9.11
