### ISSUE TITLE
Problem with *string* primary key while using db.Create api

### ISSUE THREAD

**Issue by bkalis** [jinzhu/gorm#509]
Hello,

I found gorm package very helpful in my project. I bumped into the following issue this week.

This issue is similar to the old one : https://github.com/jinzhu/gorm/issues/50
The issue seems to be related to db.Create API. This issue does not occur if we use db.Save API. 

Do you think we should not use the gorm API  db.Create if we are using string Id field and assigning the primary key in our own code?  Thanks in advance!

Biju

Problem:
Primary key (Id field in Golang struct) is overwritten with a bad value if we use db.Create API to save the object to database. The example code listed below will generate the following output.

-

Testing gorm string primary key
User before save:{"Id":"22e58664-ce23-4ada-a7c6-1acbdddd8615","Name":"John Smith"}
User after save:{"Id":"\u0001","Name":"John Smith"}

-

Example code (also visible at http://play.golang.org/p/JnVhwrceKX )

--
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"github.com/jinzhu/gorm"
	_ "github.com/mattn/go-sqlite3"
	"github.com/satori/go.uuid"
	"os"
	"strings"
)

var sqliteFileName = "test_data.db"

type User struct {
	Id   string `sql:"type:varchar(100);primary_key"`
	Name string
}

func main() {
	fmt.Printf("\nTesting gorm string primary key")

	if _, err := os.Stat(sqliteFileName); err == nil {
		err = os.Remove(sqliteFileName)
		if nil != err {
			fmt.Printf("\nError while deleting file:%v %v", sqliteFileName, err.Error())
		}
	}

	db, err := gorm.Open("sqlite3", sqliteFileName)
	if err != nil {
		fmt.Printf("\nError while opening db:%v", err.Error())
		return
	}

	newDBConn := db.DB()
	err = newDBConn.Ping()
	if err != nil {
		fmt.Printf("\nError while pinging new db:%v", err.Error())
		return
	}

	db.AutoMigrate(&User{})

	newId := strings.ToLower(uuid.NewV4().String())
	user1 := User{
		Id:   newId,
		Name: "John Smith",
	}

	jsnStr, err := ConvObjectToJson(user1)
	if nil != err {
		fmt.Printf("Error while converting to json:%v", err.Error())
		return
	}
	fmt.Printf("\nUser before save:%v", jsnStr)

	res := db.Create(&user1)
	if res.Error != nil {
		fmt.Printf("\nError while saving new user:%v", res.Error.Error())
		return
	}

	jsnStr, err = ConvObjectToJson(user1)
	if nil != err {
		fmt.Printf("Error while converting to json:%v", err.Error())
		return
	}
	fmt.Printf("\nUser after save:%v", jsnStr)

}

func ConvObjectToJson(obj interface{}) (string, error) {
	var buf bytes.Buffer
	encdr := json.NewEncoder(&buf)
	err := encdr.Encode(obj)
	if nil == err {
		return buf.String(), nil
	} else {
		return "", err
	}
}
--

**Comment by jinzhu** [comment]
Thank you for your report, and nice example, just fixed that on master branch.

**Comment by bkalis** [comment]
Jinzhu,

I did a quick test with my example and your master branch latest code. Original problem I reported seems to be fixed now.  Thank you very much!
Biju
