### ISSUE TITLE
string length 

### ISSUE THREAD

**Issue by goors** [jinzhu/gorm#510]
How can i set mysql column to be longtext since struct type sting is 255 varchar?

**Comment by jaytaylor** [comment]
use tags, e.g.:

```go
type MyStruct struct {
   ...
    LongField string `sql:"type:varchar(text);"`
   ...
}
```

**Comment by jinzhu** [comment]
You could change the string length with `sql:"size:999999"` also

**Comment by goors** [comment]
Hi Jay,

LongField string `sql:"type:text;"`

this is not working. 

When I do <pre>dbmap.AddTableWithName(Post{}, "posts").SetKeys(true, "Id")</pre>
I am still getting 255 varchar.

<pre>
type Post struct {
    Id      int64 `db:"post_id"`
    Created int64
    Title   string `form:"Title"`
    Body    string `sql:"type:text;"`
	
}
func initDb() *gorp.DbMap {
    // connect to db using standard Go database/sql API
    // use whatever database/sql driver you wish
    
    //db, err := sql.Open("sqlite3", "/tmp/post_db.bin")
    db, err := sql.Open("mysql", "user:pass@/martini")
    checkErr(err, "sql.Open failed")

    // construct a gorp DbMap
    dbmap := &gorp.DbMap{Db: db, Dialect: gorp.MySQLDialect{"InnoDB", "UTF8"}}

    // add a table, setting the table name to 'posts' and
    // specifying that the Id property is an auto incrementing PK
    dbmap.AddTableWithName(Post{}, "posts").SetKeys(true, "Id")

    // create the table. in a production system you'd generally
    // use a migration tool, or create the tables via scripts
    err = dbmap.CreateTablesIfNotExists()
    checkErr(err, "Create tables failed")

    return dbmap
}
</pre>

**Comment by Unknwon** [comment]
@goors Work for my at least for MySQL by using

```go
`sql:"type:text"`
```
