### ISSUE TITLE
transaction lifetime

### ISSUE THREAD

**Issue by yanfali** [jinzhu/gorm#511]
Hello,

thanks for creating Gorm, it seems really solid. I have a question about controlling transaction lifetimes. If the default behavior is to create transactions for every save and delete, is there a way to specify the life cycle?

For example, imagine I have two tables that need to be updated within the same transaction, and I want the first save to be rolled back if the second one fails. What is the correct way to do that?

I can imagine using the callbacks to trigger additional operations, but it's complicated in the struct callbacks to figure out what the overall operation was without adding some sort of global state, or possibly introducing something into the scope level.

Also what is the correct way to do interleaved transactions? For example, right now, if I start a transaction at the beginning of a method and run multiple saves within that transaction gorm complains about there being an existing transaction running.

Is there some way for gorm to detect that a transaction is currently running and not add a new transaction and rollback assuming that this is being handled elsewhere?

Many thanks in advance.

**Comment by yanfali** [comment]
Hmm, ok after poking around more, I found doc/development.md, it seems I can control the behavior of the callback chains. Is this an appropriate way to control transaction lifecycles?

**Comment by jinzhu** [comment]
```go
tx := db.Begin()
tx.Save(&user)
tx.Save(&product)
tx.Save Or Rollback
```

**Comment by yanfali** [comment]
Hi Jinzhu,

thanks for the response. Does this work too?

tx := db.Begin()
tx.Create(&user)
tx.Save(&product)
tx.Commit() or Rollback()

Thanks

Yan

**Comment by yanfali** [comment]
OK, Sorry for the issue. One comment. The documentation in the README, is a bit ambiguous, and it would be awesome is there was a bit of explanation about the lifetime of a transaction. I think when I was unit testing it I managed to do something wrong and trigger some warnings, totally my fault. Thanks gain.

**Comment by jinzhu** [comment]
Yes, this will works also.

The transactions will only be closed automatically if it is started by itself.
