### ISSUE TITLE
Support associations for Scan

### ISSUE THREAD

**Issue by codingrogue** [jinzhu/gorm#512]
Hey,

is it possible to scan associations, because I tried but it didn't work so far:
```
var events []Event

self.DAO.DB.Raw("SELECT"+
    " e.ID, e.title, e.description,"+
    " d.ID, d.date, d.start_time, d.end_time,"+
    " d.event_id"+
    " FROM events e"+
    " LEFT JOIN dates d ON e.ID = d.event_id").
    Scan(&events)
```
For the following two example structs:
```
type Event struct {
    ID int
    Title string
    Description string
    Dates []Date
}

type Date struct {
    ID int
    Date time.Time
    StartTime time.Time
    EndTime time.Time
    EventID int
}
```
It is not populating the `Dates` property, so it stays nil.

**Comment by ljesus** [comment]
I have the same issue. I've searched and it seems that gorm does not support scanning associations on joins. Can anyone confirm? The way I've bypassed this issue is by scanning the values myself row by row.

**Comment by jinzhu** [comment]
Hi @codingrogue 

Yes, doesn't support Scan association, maybe you want to use `Preload` here?

**Comment by codepushr** [comment]
Just quickly asking if this is somwhere on the roadmap? Preloading 3-4 Tables takes up a considerable abount of time due to multiple statements. One statement with multiple Joins is much quicker.

**Comment by tom10271** [comment]
How to use Preload? I have tried

```go
rows, err := pDb.
		Model(&entity.User{}).
		Preload(`UserProfiles`).
		Order(`id ASC`).
		Rows()
```

but it is not working. `db.ScanRow` only populate user object except `UserProfiles` field

**Comment by shackra** [comment]
Can confirm, Preload does nothing when using `Rows` or in `ScanRows`

**Comment by petrogdev** [comment]
Has anyone found a solution for this?
Im experiencing something similar.

**Comment by egsk** [comment]
Came here for a same reason - `Preload` does not loading associations. Please, let us know if there any additional info.

**Comment by paultag** [comment]
Same issue; this appears to be valid, Preload isn't doing anything with `Rows` as far as I can see, this bug should likely be re-opened

**Comment by ali-gitinejad** [comment]
yes we call result by sp and use gorm lib to populate data with scan and preload enable.
but is doesnt work .
it's very good solution which gorm support preload with scan 
plz add this feature
