### ISSUE TITLE
When I put sql.NullInt64 in type struct, NULL is always written to db. Why?

### ISSUE THREAD

**Issue by goors** [jinzhu/gorm#521]
I have this model:

    type RouteCategory struct {

	Id					int
	ParentCategory  	*sql.NullInt64 		`gorm:"column:ParentCategory sql:"index;null"`
	CategoryName   		string  			`gorm:"column:CategoryName; sql:"type:varchar(64);"`
	CategoryDescription string  			`gorm:"column:CategoryDescription; sql:"type:varchar(255);"`
	IsActive 			int 				`gorm:"column:IsActive; sql:"type:smallint(1);"`
    }

ParentCategory is fk to table itself. Now in form I have some dropdown with category and subcategory,
where subcategory parent is category.

When I try changing ParentCategory to int then I can not insert Category since ParentCategory is null.

Can anyone help me with this?

**Comment by jinzhu** [comment]
ParentCategory don't need to use Poiner, and did you set `Valid` to true?

**Comment by Sdaf47** [comment]
why i can't use Pointer for this?

**Comment by danhardman** [comment]
@Sdaf47 Why would you want to? Either use a `*Int64` or use `sql.NullInt64` properly. The value of a `sql.NullInt64` column is set to null if the value is not valid so:

`ParentCategory := sql.NullInt64{Int64: 10, Valid: false}` would be null

`ParentCategory := sql.NullInt64{Int64: 10, Valid: true}` would be 10 in the database
