### ISSUE TITLE
Migrations: invalid sql type JSON (map) for postgres

### ISSUE THREAD

**Issue by elliotlings** [jinzhu/gorm#523]
I have created my own JSON type which is a map[string]interface{}. I have added a Scan and Value function to it and it all works when inserting and selecting from the database.

My issue is that when I migrate it's throwing the error "invalid sql type JSON (map) for postgres". I have tried the tags sql:"json" and gorm:"type:json" but I am having no luck.

Like I say, it's only issue when auto migrating. Can this be resolved please?

**Comment by boonep** [comment]
sql:"type:json" (postgres9.3) or sql:"type:jsonb" (postgres9.4) work for me.  Looks like you were close!

**Comment by elliotlings** [comment]
Boom! Thanks so much, I was almost there!
