### ISSUE TITLE
Postgres bytea not supported in where condition

### ISSUE THREAD

**Issue by bojan-embroker** [jinzhu/gorm#524]
In the following case

`var token []byte`
`...`
`obj = &myStruct{}`
`db.First(obj , tokenHash, token )`

SQL query was "WHERE token IN ('124', '36', ...)" instead of "WHERE token=$1"

Solution might be to where a separate First() and FirstIn() in order to support postgres array types.

**Comment by jinzhu** [comment]
Hi @bojan-embroker 

Thank you for your report, this should been fixed.
