### ISSUE TITLE
Fetching Query String from gorm.DB object

### ISSUE THREAD

**Issue by jainsangam** [jinzhu/gorm#526]
Is it possible to fetch all the queries that has been fired to the database ?

**Comment by jinzhu** [comment]
Do you means? https://github.com/jinzhu/gorm/issues/427

**Comment by kinnalru** [comment]
query := db.Where("column" + " ILIKE " + "'%name%'")
log.Println(query.QueryExpr())

**Comment by sergolius** [comment]
@kinnalru unfortunately `.QueryExpr()` returns private object, so you can't reuse out of gorm.
Example: save it to file system.
