### ISSUE TITLE
SingularTable is not working on specific model.

### ISSUE THREAD

**Issue by dorajistyle** [jinzhu/gorm#528]
Hello jinzhu,

I'm using 087b7083ad1154ff0573d560b64310e4869a2820 because the problem below.

https://github.com/jinzhu/gorm/issues/437

Today I updated gorm as cde05781a05feb80def1aa46edac24a57ec93b30

And I found a new issue.

db.SingularTable(true) is not working on specific model.

I have 'User' model and 'Role' model.
'User' model works fine.
But 'Role' did not working.
gorm tried to find roles table.
When I tried to db.AutoMigrate, it generate 'roles' table.

**Comment by jinzhu** [comment]
Hi @dorajistyle 

Thank you for the report, this should been fixed for a while.
