### ISSUE TITLE
issue with index creation, if the same table  + field combination exist in a different schema 

### ISSUE THREAD

**Issue by jainsangam** [jinzhu/gorm#532]
The current function to check index 

func (commonDialect) HasIndex(scope *Scope, tableName string, indexName string) bool {
	var count int
	scope.NewDB().Raw("SELECT count(*) FROM INFORMATION_SCHEMA.STATISTICS where table_name = ? AND index_name = ?", tableName, indexName).Row().Scan(&count)
	return count > 0
}

doesn't specify table_schema

**Comment by jinzhu** [comment]
HI @jainsangam 

This issue should been fixed already (about one or two months ago). thank you for your report.
