### ISSUE TITLE
How to change dependency order of Preload?

### ISSUE THREAD

**Issue by rvenugopal** [jinzhu/gorm#534]
Hi

Given the model in https://github.com/jinzhu/gorm#define-models-structs

How do I write a preload query which does the equivalent of "Find me all the users (with emails preloaded) whose email.subscribed is subscribed and email.email is "jinzhu@gorm.com")

Thanks
-Rvg

**Comment by LiranCohen** [comment]
Given that model that will not find you "all users".
In that model the e-mail addresses each email is unique.

So you would only have one user as jinzhu@gorm.com.  In which case the Preload function isn't necessary.

Also with an specific query like that even if the emails weren't unique you wouldn't want to use preload.  You would want to have a query just for that search with joints tables I would assume. 

I think something like this may work:

users := []User{}

query := db.Joins("inner join emails on emails.user_id = users.id").Where("emails.email = ?", "jinzhu@gorm.com").Find(&users)

if query.Error != nil {
 // query error could be "record not found"
}

**Comment by jinzhu** [comment]
```go
db.Preload("Emails", "emails.email = ? AND emails.subscribed = ?", "jinzhu@gorm.com", true).Find(&users)
```
