### ISSUE TITLE
Many to many firing extra updates

### ISSUE THREAD

**Issue by rvenugopal** [jinzhu/gorm#535]
Extra updates appears to be occurring as reported on #329. My model is 

```
type Language struct {
    Id   int
    Name string
    Users []User `gorm:"many2many:user_languages;"`
}

type User struct {
    Id        int
    Name      string
    Languages []Language `gorm:"many2many:user_languages;"`
}
 
```

**Comment by rvenugopal** [comment]
Is there a way for me to perform just a save on the intersection table without performing a dirty check on either of the models here (User or Language).  I want to be able to use 

```
db.Model(&User{Id = 123}).Association("Languages").Append(Language{Id = 456})

```

Thanks
-Rvg

**Comment by goddardcm** [comment]
Also still seeing this behavior. Nearly identical scenario to @rvenugopal.

**Comment by damnpoet** [comment]
Same error here, any workarounds?

**Comment by LiranCohen** [comment]
Anyone able combat this?  The additional dirty checks are a bit screwy not to mention I have to make a full call for the "Language" in this case otherwise it will update it with blank fields.

**Comment by goddardcm** [comment]
The way I worked around my particular issue was to flip how the association gets created. I can't exactly recall if that solution would be generally acceptable or was specific to my use-case. But essentially I did
```
db.Model(&Language{Id = 456}).Association("Users").Append(User{Id = 123})
```
instead of 
```
db.Model(&User{Id = 123}).Association("Languages").Append(Language{Id = 456})
```

**Comment by jinzhu** [comment]
Hi All,

Sorry for the delay, the problem should be fixed.

**Comment by rvenugopal** [comment]
Works great.  Thanks
