### ISSUE TITLE
About total count

### ISSUE THREAD

**Issue by chrislearn** [jinzhu/gorm#536]
I have some code like this:
```golang
 c.Tx.Debug().Model(&models.Creative{}).Order("updated_at desc").Find(&creatives, "name LIKE ?", "%" + q + "%").Count(&totalCount)
```
I just want to know the totalCount with name Like q, but the generated sql is:

```sql
SELECT  count(*) FROM "creatives"  WHERE ("creatives".deleted_at IS NULL OR "creatives".deleted_at <= '0001-01-02') ORDER BY updated_at desc
```
This is not I wanted, how can I fix my code?

**Comment by jinzhu** [comment]
c.Tx.Debug().Model(&models.Creative{}).Order("updated_at desc").Where("name LIKE ?", "%" + q + "%").Find(&creatives).Count(&totalCount)
