### ISSUE TITLE
Handle null value correctly

### ISSUE THREAD

**Issue by ilgooz** [jinzhu/gorm#540]
When I'm using <code>Rows().Scan()</code>, null values not converted to destination type instead it breaks following extractions. Consider this <code>rows.Scan(&a.Id, &b.Name)</code> if a.Id is null then b.Name will not be extracted even it's not null.

Tip: I'm using <code>IFNULL(a.id, 0)</code>, <code>IFNULL(b.Name, "")</code> in my queries to avoid this problem now.

**Comment by jinzhu** [comment]
First, Find could handle NULL value correctly, but good to know your tip. ;)
