### ISSUE TITLE
Calling json.Marshal on an empty slice after calling Find results in "null" rather than "[ ]"

### ISSUE THREAD

**Issue by tland** [jinzhu/gorm#548]
Hi @jinzhu,

No really sure if it's an expected behaviour, but seems there introduced a regression with the **Find** method by commit 2d802c3 recently. 

If the Find method is called to search a table with certain conditions, and no matched results are found, then calling json.Marshal against the returned results (in this example is the slice "users") would result in "null" rather than "[ ]". 

```
var users []User
db.Where(...).Find(&users)
```

To workaround this issue, I had to do a re-assignment after calling the Find method.

```
if users == nil {
    users = []Users{}
}
```

Thanks,
Kevin

**Comment by LiranCohen** [comment]
I would test for the "record not found" error and handle it that way.

Something along these lines.

query := db.Where(...).Find(&users)
if query.Error != nil {
   if query.Error.Error() == "record not found" {
      //handle record not found
   }
   //handle other record
}

**Comment by 9uuso** [comment]
There actually has been discussion of this earlier, see #260, #292 and #228. If you look at the final comment on #228, you will notice that originally this was supposed to be fixed. Looks like it slipped trough again.

Anyhow, thanks @tland for the workaround. I'll use it for now.

**Comment by mraxus** [comment]
The query does not return an error for me. Instead I have this less than pretty solution:

```go
func (i *Impl) queryClassifications(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {
	classifications := []Classification{}
	if err := i.DB.Preload("Names").Preload("Descriptions").Find(&classifications).Error; err != nil {
		log.Error("Could not query DB for classifications:", err)
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if len(classifications) == 0 {
		// Gorm returns empty set as 'null' but we want '[]'
		i.R.JSON(w, http.StatusOK, []Classification{})
	} else {
		i.R.JSON(w, http.StatusOK, &classifications)
	}
}
```

**Comment by jinzhu** [comment]
Seems like works with latest master, going to close this.

```go
package main

import (
	"encoding/json"
	"fmt"

	_ "github.com/lib/pq"

	"github.com/jinzhu/gorm"
)

type User struct {
	gorm.Model
	Email string
}

func main() {
	db, err := gorm.Open("postgres", "user=gorm DB.name=gorm sslmode=disable")
	if err != nil {
		panic(err)
	}

	db.LogMode(true)
	db.DropTable(&User{})
	db.AutoMigrate(&User{})

	user := User{
		Email: "hello@example.com",
	}

	db.Create(&user)

	var users1 []User
	if err := db.Find(&users1).Error; err != nil {
		panic(err)
	}

	var users2 []User
	if err := db.Find(&users2, "1 = 2").Error; err != nil {
		panic(err)
	}

	var users3 []User

	fmt.Println("== slice has value")
	fmt.Println(json.Marshal(users1))

	fmt.Println("== empty slice after find")
	fmt.Println(json.Marshal(users2))

	fmt.Println("== empty slice")
	fmt.Println(json.Marshal(users3))
}
```
