### ISSUE TITLE
quoting breaks alter table on mariadb

### ISSUE THREAD

**Issue by yanfali** [jinzhu/gorm#553]
git commit 27a442b5ecef401a3ba2325383a96a09b0a983d9 breaks mariadb alter table statements:

Broken generated SQL:
```
ALTER TABLE `drawer` ADD CONSTRAINT `drawer_analyst_id_foreign` FOREIGN KEY (`analyst_id`) REFERENCES `analyst(id)` ON DELETE RESTRICT ON UPDATE RESTRICT;
```
Working SQL:
```
ALTER TABLE `drawer` ADD CONSTRAINT drawer_analyst_id_foreign FOREIGN KEY (analyst_id) REFERENCES analyst(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
```
Seems like mariadb specifically doesn't like quoting of REFERENCES `analyst(id)` and throws an sql error:
```
2015/07/01 15:29:29 Error 1005: Can't create table `analyst`.`#sql-562_210` (errno: 150 "Foreign key constraint is incorrectly formed")
```

**Comment by yanfali** [comment]
Applying the following patch allows it to work again on mariadb.

```
-       scope.Raw(fmt.Sprintf(query, scope.QuotedTableName(), scope.Quote(keyName), scope.Quote(field), scope.Quote(dest), onDelete, onUpdate)).Exec()
+       scope.Raw(fmt.Sprintf(query, scope.QuotedTableName(), scope.Quote(keyName), scope.Quote(field), dest, onDelete, onUpdate)).Exec()
```

Not sure what the right answer is though for different databases.

**Comment by jaytaylor** [comment]
Right, then it will break all the other databases which require the names
to be quoted!

:s

**Comment by yanfali** [comment]
@jinzhu there may be an alternate format that works for everyone. `analyst` (`id`). This seems to work on mariadb. @jaytaylor does this work on your database?

**Comment by yanfali** [comment]
OK, I think the simplest way to fix this is update Quote in mysql.go to be smarter. I'll try and get something working.

**Comment by yanfali** [comment]
OK, if you patch mysql.go to work something like this:

```
func (mysql) Quote(key string) string {
	if strings.Contains(key, "(") {
		pos1 := strings.Index(key, "(")
		pos2 := strings.Index(key, ")")
		return fmt.Sprintf("`%s`(`%s`)", key[0:pos1], key[pos1+1:pos2])
	}
	return fmt.Sprintf("`%s`", key)
}
```
It now returns correctly formatted and quoted strings.

**Comment by jinzhu** [comment]
Hi @yanfali


This should be fixed, thank you for your feedback.
