### ISSUE TITLE
Recursive many2many relation

### ISSUE THREAD

**Issue by WnP** [jinzhu/gorm#554]
Trying to implement a recursive `many2many` relation like the following:

```go
package main

import (
        "github.com/jinzhu/gorm"
        _ "github.com/lib/pq"
)

var db, _ = gorm.Open("postgres", "user=gorm dbname=gorm sslmode=disable")

type User struct {
        gorm.Model
        Name    string
        Friends []User `gorm:"many2many:user_friends;"`
}

func main() {
        db.LogMode(true)
        db.DB().Ping()
        db.AutoMigrate(&User{})
}
```
ends with the following error:
```
pq: column "user_id" specified more than once
```
my questions are:
- is it possible to implement such a schema?
- is it plan to manage this feature in the future?
- do you know an elegant alternative to handle this kind of schema?

Thanks in advance

**Comment by jinzhu** [comment]
Hello,

Seems it is pretty tricky to do that...

Maybe better to define a Friend struct, and it works like a join table
