### ISSUE TITLE
Select without backquotes

### ISSUE THREAD

**Issue by ghigt** [jinzhu/gorm#555]
In the README, there is this line:
```go
db.Table("users").Select("COALESCE(age,?)", 42).Rows()
//// SELECT COALESCE(age,'42') FROM users;
```

But actually, instead of generating a string between quotes as `'42'`, it generates it with backquotes as \``42``. So I receive this error:
> Unknown column '42' in 'field list'

I have the same error on my project when I use `?` inside a `.Select`.

**Comment by jinzhu** [comment]
Hi @ghigt 

Thank you for your feedback, just fixed that.
