### ISSUE TITLE
Select/limit etc handles blank string but order doesn't

### ISSUE THREAD

**Issue by e247** [jinzhu/gorm#560]
db.Select("*").Limit("").Order("").Find(&users)
//outputs "SELECT * FROM users ORDER BY"
//note limit is omitted from the sql but order is not.

I am pre-filling variables before passing to grom. I could put the Order() in if statements if I knew how.

Many thanks!
jJ

**Comment by jinzhu** [comment]
Thank you for your feedback, just fixed that, You could pass an blank string to Order now.
