### ISSUE TITLE
AddForeignKey: Unlucky constraint names

### ISSUE THREAD

**Issue by angelow1337** [jinzhu/gorm#562]
AddForeignKey creates unlucky constraint names.

The following code fails, because the constraint names are duplicate (both are "rights_principal_id_foreign"):

```go
db.Model(&models.Right{}).AddForeignKey("principal_id", "users(id)", "NO ACTION", "NO ACTION")
db.Model(&models.Right{}).AddForeignKey("principal_id", "roles(id)", "NO ACTION", "NO ACTION")
```

**Recommendation**: Use the reference table name in the constraint name like "rights_users_principal_id_foreign" and "rights_roles_principal_id_foreign"

**Comment by jinzhu** [comment]
Hi @angelow1337 

Thank you for your feedback, just fixed that.
