### ISSUE TITLE
plural support

### ISSUE THREAD

**Issue by jasonzhao3** [jinzhu/gorm#563]
Hi,

First thank you for the fantastic orm library. I'm from RoR background, and therefore quite picky about the correct plural format. Seems there are some words that are not supported very well. Like:

criterion => criteria
media => media

Thanks advance for the fix!

**Comment by jinzhu** [comment]
Hi @jasonzhao3 

Thank you for your suggestion, just changed gorm's default plural engine to github.com/qor/inflection, which has exactly rules with the rails one.

And it provide the ability for your to change its rules.

Thank you.
