### ISSUE TITLE
Gorm logging with per-request context

### ISSUE THREAD

**Issue by chsmp** [jinzhu/gorm#564]
I use Gorm in a net/http server where the HTTP server calls into a DB instance using Gorm's API.  I use Gorm's database trace output to log DB operations to a file.  Since the Gorm DB log messages are not explicitly associated with each client's request, I have to infer from the log file which DB request is associated with which client request.  I would like to somehow make that client->DB request association explicit.

Go says to use the "Context" pattern (https://blog.golang.org/context) for these cases.  I would assume to implement this I would create a context and pass it down into all of the functions I invoke, including Gorm's API calls.  I would then expect that context would be made available by Gorm to its logger.  I imagine I would use Gorm's SetLogger to pass my own logger that would then grab whatever values were in the context and decorate the output with them along with whatever message was passed to the logger.

I don't see a way to do this using Gorm's current API, though.  Am I looking in the right place?  I'm aware of a tricky way to do this using https://github.com/jtolds/gls.  However, any practice that uses Goroutine-local variables is strongly discouraged by Go's language maintainers.  Is there a simple way to do this in Gorm that I'm overlooking?

Thanks!

**Comment by jinzhu** [comment]
Hi @chsmp 

I think it could be something like this:

when a request coming, you generate a new db instance with `db.New()` and set a logger to it.

all logs from gorm will put into the request's logger.
