### ISSUE TITLE
Scan ignoring struct field when using `sql:"-"`

### ISSUE THREAD

**Issue by ivpusic** [jinzhu/gorm#565]
I have something like this

```
type Type struct {
	Paid bool `sql:"-" json:"paid"`
}
```

And then I have query something like this:
```
SELECT 
  CASE WHEN condition IS NOT NULL THEN true
       ELSE false
  END as paid
FROM type ....
```

With this setup ``Paid`` field is ignored (gorm is not filling in value from query into this field). If I remove ``sql:"-"`` then it works, but I don't want to add this field to my table.

**Comment by jinzhu** [comment]
Once it is ignored, it won't be scanned.

If you just want to skip the `paid` column when save the record, you could use the `Omit` function, but not ignore the struct with `sql tag`

**Comment by jinzhu** [comment]
Hi @ivpusic 

Just FYI, the latest gorm will try to scan into ignored fields if there is no ambiguity
