### ISSUE TITLE
max_prepared_stmt_count error

### ISSUE THREAD

**Issue by LYY** [jinzhu/gorm#566]
I use mysql and [maxscale](https://mariadb.com/products/mariadb-maxscale) as readwrite split, when I use gorm on my production. 
I got max_prepared_stmt_count error on maxscale log.

Db connection source file is this gist [gorm.go](https://gist.github.com/LYY/b7fd1c4402ca1ce25e5b).

I use [go-workers](https://github.com/jrallison/go-workers) as sidekiq worker.
So I use like this:

in main.go
```go
utils.InitDB()
```

in sub-worker.go, the sub-worker working in goroutine
```go
db := utils.DbBegin()
db.Where("showing = ? and version = ? and start_at <= now() and action = ?", true, 1, actionType).Find(&tasks)
...some code...
db.Create(&taskLog)
...some code...
db.DbCommit()
```

error log:
```
Jul 15 20:01:26 localhost MaxScale[17429]: Error : Failed to execute SELECT  count(*) FROM `user_app_versions`  WHERE (user_id = ? and version = in 10.4.17.91:3306. 42000 Can't create more than max_prepared_stmt_count statements (current value: 16382)
```

When I get an error like that, the maxscale will be stopped, my product is down.

How can I fix this?

**Comment by LYY** [comment]
I test my code directly to connect mysql ,all is ok. I think it may be maxscale + database/sql issue.

**Comment by jinzhu** [comment]
Possible, have never saw the problem, anyway, let me know if it is reproducible with gorm.

**Comment by yiqinguo** [comment]
I also encountered this problem.

**Comment by kvneight** [comment]
Why this issue closed? Is it fixed?I can still reproduce this issue with latest version

**Comment by jianzhiyao** [comment]
Just call:
```
defer db.Close()
```
