### ISSUE TITLE
Unable to get int value using pq/postgres

### ISSUE THREAD

**Issue by sathishvj** [jinzhu/gorm#568]
We have a struct that has an int64 or uint values mapped to integer/bigint values in postgres.  We are getting back string, bigserial, etc. values properly but the bigint/integer values are always 0 in the returned data.  Is there something wrong in what we are doing?

Our code is similar to that show below:

type User struct {
    Id        int64    `gorm:"column:id"`
    OrgId  uint       `sql:"column:orgid"`
    CreatedBy   int64     `gorm:"column:createdby_id"`
}

We then connect to gorm and use a call like this:
    var users []User
    r := db.Table("app_user").Find(&users)
    if r.Error != nil {
     fmt.Printf("Error getting app_user data: %+v\n", r.Error)
    }
    fmt.Printf("users: %+v\n", users)

**Comment by jinzhu** [comment]
Hi 

Because int, int64 things would be initalized with value `0`. so when save it, will insert the 0 into database. but you would change the type to things like, `*uint` , then it could return nil if no value found.

```go
type User struct {
Id int64 gorm:"column:id"
OrgId *uint sql:"column:orgid"
}
```
