### ISSUE TITLE
proposal: generate structs from schema info 

### ISSUE THREAD

**Issue by alfonsodev** [jinzhu/gorm#574]
Hi, 
I'm started to write [my own orm like package](https://github.com/alfonsodev/yao)  for learning proposes, 
it's not fully featured as gorm (not even close) but It has a command line tool that can generate files with structs from database information. This saves a lot of time when working with big databases (hundreds of tables).
Are you interested to have this feature in gorm?  If so, I can port and adapt my existing code to a PR.
The use case would be  
``` 
go get -u github.com/jinzhu/gorm
gorm generate -d dbname -o outputpath
```
gorm generate could generate all structs needed under `outputpath`  with gorm tags included. 
Another option is that I add the option to generate gorm ready structs to my existing `yao gen` command.   

Thoughts ?

**Comment by jinzhu** [comment]
Hi @alfonsodev 

Sure, it is good to have a tool to generate models from database schema, but I don't really want to integrate it into gorm itself.

Just want gorm focus on the ORM related things, but tools like this could be third party tools.

**Comment by rsperl** [comment]
This is a start: https://gist.github.com/rsperl/f0b9d48f38cd6aeccc81 . You'll have to set env vars DBNAME, DBUSER, DBPASS, DBHOST for db info. 

./gorm-generate-types.pl --package mypackage --filename MyTypes.go

The types map needs some work, but this should provide a pretty good start for generating types for database DBNAME.

**Comment by fobispo-link** [comment]
I actually think this would be a GREAT idea, similar to what `dbicdump` does for perl's `DBIx::Class`, but to be feasible it should be written in GO, and should have an API to allow for custom database types to plugin, so it can work with different drivers and DB backends. I'm going to try to build one.

**Comment by jadolg** [comment]
I'd like to hear more from this.

**Comment by Frzifus** [comment]
Any updates?

**Comment by p581581** [comment]
Any updates? really needs this feature!

**Comment by dalu** [comment]
The perl script is a good start.
But essentially you need just 4 mysql commands (not sure about postgres or other).
```
SHOW DATABASES;
SHOW TABLES;
SHOW COLUMNS FROM table_name;
SHOW INDEX FROM table_name;
```

Right now I have a site that was written in PHP and uses mysql but the schema was created with doctrine.
so there are tables like game_tag game_game game_video etc.
That's probably the more complicated thing, because I have not given it a thought yet.
And I don't know how gorm handles toMany toOne and inverse from a schema point of view

**Comment by weisd** [comment]
Any updates? really needs this feature!

**Comment by sakar-sr** [comment]
good feature, it will be helpful for freelance programmers to cut sort the coding time a lot when it comes to handling database in Golang.

**Comment by awking** [comment]
Wish authro can provide this feature, thrid-party hard to compatibility perfact.

**Comment by opannapo** [comment]
Hi, look at this repository
https://github.com/opannapo/db-to-struct

Execute JAR file :
Create one -> --init <db_user>,<db_password>, --tbl <table_name>
Create All   -> --init <db_user>,<db_password>, --tbl all

For example :
java -cp ./db-to-struct.jar Main --init napouser,napouser,MataPena --tbl tbl_user
