### ISSUE TITLE
Support request: IN query

### ISSUE THREAD

**Issue by theduke** [jinzhu/gorm#579]
How would I go about doing an IN query?
Is ther any convenience method for escaping built in?

ids := []uint{22,23,27}
db.Where("id IN ?", ids).Find(&jobs)

**Comment by galeone** [comment]
Hi @theduke, as the `README.md` says, this feature already exists in gorm:
> db.Where("name in (?)", []string{"jinzhu", "jinzhu 2"}).Find(&users)
