### ISSUE TITLE
Delete not respecting ID? (struct slice)

### ISSUE THREAD

**Issue by Knorkebrot** [jinzhu/gorm#584]
I'm calling Delete with a slice of structs that have an ID field that is not zero, but Delete issues an SQL that doesn't contain the IDs. I tried to use `db.Where(fields).Delete(CalcField{})`, but that didn't help, as did having empty structs with only the ID set.

What am I doing wrong?

Output is godebug with gorm logging enabled:
```
-> _ = "breakpoint"
(godebug) l

                for _, v := range f.Values {
                        values = append(values, CalcFieldValue{ID: v.ID})
                }
        }
-->     _ = "breakpoint"
        if err := db.Delete(fields).Error; err != nil {
                return errgo.Mask(err)
        }
        if len(values) > 0 {

(godebug) p fields
[]models.CalcField{models.CalcField{ID:1, CreatedAt:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, UpdatedAt:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}, DeletedAt:(*time.Time)(nil), Name:"", Type:0, Values:[]models.CalcFieldValue(nil), CalcID:0}}
(godebug) n
-> if err := db.Delete(fields).Error; err != nil {
(godebug) n

(/var/folders/_l/q7lyqn4577d05ykp5nr4k8v40000gp/T/godebug854068453/src/xxx.go:242)
[2015-07-28 13:46:57]  [0.95ms]  UPDATE "calc_fields" SET deleted_at='2015-07-28T13:46:57+02:00'  WHERE ("calc_fields".deleted_at IS NULL OR "calc_fields".deleted_at <= '0001-01-02')
-> if len(values) > 0 {
(godebug)
```

**Comment by Knorkebrot** [comment]
I'm working around this by using an int slice and `Where("id in (?)", fields)` now.

**Comment by jinzhu** [comment]
HI @Knorkebrot 

Yes, `Delete`, `Save`, `Create` all could only accept a struct but not a slice for now.

**Comment by bah2830** [comment]
Can we get a check added in to error if a slice is given? Currently NewScope() is able to find the correct table from the slice but not build the where clause, this results in it deleting all records from the table which is very bad.
