### ISSUE TITLE
Preload(): can't find field

### ISSUE THREAD

**Issue by nikolaybobrovskiy** [jinzhu/gorm#586]
Hello.

I have got a problem preloading data (sqlite). Please, look at this code:
```
type User struct {
	gorm.Model
	UserName    string `sql:"not null;unique"`
	Password    string
	DisplayName string `sql:"not null;unique"`
	IsAdmin     bool
	IsDisabled  bool
	Ou          OrganizationUnit
	OuID        uint `sql:"type:integer REFERENCES organization_unit(id) ON DELETE CASCADE ON UPDATE CASCADE"`
}

type OrganizationUnit struct {
	gorm.Model
	Name  string `sql:"not null;unique"`
	Users []User
}

ou := &OrganizationUnit{}
db.Preload("Users").First(ou)
```
I get: can't find field Users in *models.OrganizationUnit

Could you say what I am doing wrong?

**Comment by andboson** [comment]
bump

it has been worked in 82d726bbfd8cefbe2dcdc7f7f0484551c0d40433 (last from 21.07)

**Comment by jinzhu** [comment]
Hi @nikolaybobrovskiy 

```go
type User struct {
    Ou          OrganizationUnit
    OuID        uint `sql:"type:integer REFERENCES organization_unit(id) ON DELETE CASCADE ON UPDATE CASCADE"`
}

type OrganizationUnit struct {
    Users []User
}
```

Because you are not using the naming convention, so `OrganizationUnit` don't know the `Users` relations's foreign key is `OuID` unless you tell it. so you could change the `OrganizationUnit` to:

``` 
type OrganizationUnit struct {
    Users []User ``gorm:"foreignkey:OuID"`
}
```

**Comment by nikolaybobrovskiy** [comment]
@jinzhu thank you

**Comment by andboson** [comment]
thanks!

**Comment by schickling** [comment]
I'm still having this issue. I've just updated via `go get -u github.com/jinzhu/gorm` to the latest version and ended up with this error. (I'm following the gorm naming conventions.)

**Comment by jinzhu** [comment]
@schickling please paste the code could reproduce your issue here.

**Comment by schickling** [comment]
@jinzhu I've figured out the problem. I'm getting the error `can't find field Users` when there are no `User` models in the database yet. Should I open another issue for this since I think this is unintended behavior?

**Comment by gpopovic** [comment]
I'm having the same problem as @schickling 
First time i load something, it will throw that error and when i reload (query gets issued for second time), then everything works
