### ISSUE TITLE
syntax error: unexpected range, expecting {

### ISSUE THREAD

**Issue by rghose** [jinzhu/gorm#588]
go version go1.3.3 darwin/amd64

I get this on building:

github.com/jinzhu/gorm
src/github.com/jinzhu/gorm/association.go:233: syntax error: unexpected range, expecting {
src/github.com/jinzhu/gorm/association.go:243: non-declaration statement outside function body
src/github.com/jinzhu/gorm/association.go:244: syntax error: unexpected }

**Comment by mrkaspa** [comment]
I got the same problem could you merge this plz

**Comment by jinzhu** [comment]
Hi @rghose 

Thank you for your PR.
