### ISSUE TITLE
Iteration doesn't support parsing raw data into struct?

### ISSUE THREAD

**Issue by Mattieuga** [jinzhu/gorm#59]
I may be missing something, but the docs aren't really clear on this. They mention the `Rows()` function can be used to iterate over table but since this returns `*sql.Row`, I'm not sure how to scan this into the struct for this row. The great thing about gorm is that it handles parsing the sql data into a struct, but this seems to be missing for iteration.

The example shows this, which really isn't great given how easy all of the other functions are to use.
```
rows.Scan(&name, &age, &email)
```

**Comment by jinzhu** [comment]
```go
rows, err := db.Model(&User{}).Where("name = ?", "jinzhu").Select("name, age, email").Rows() // (*sql.Rows, error)
defer rows.Close()

for rows.Next() {
  var user User
  db.ScanRows(rows, &user)
  // do something
}
```
