### ISSUE TITLE
Soft Deletes and Foreign Keys

### ISSUE THREAD

**Issue by juandiegopalomino** [jinzhu/gorm#591]
Hi gorm people,
I've been using gorm for a couple libraries now, and I really like it, but I'm currently having a small issue: if I create 2 tables via 2 structs and then add a foreign key from one to the other, the soft deletes don't cascade (e.g. the cars table has a modelID field referencing an entry in the models table. Soft deleting that models table doesn't soft delete the corresponding cars records). I was wondering if there's currently a way around this. Thank you for your time, and have a nice day.

**Comment by jinzhu** [comment]
Hi @juandiegopalomino 

Sorry, but soft delete doesn't do the job. but you could write a `AfterDelete` to do that.
