### ISSUE TITLE
AddForeignKey quotes reference table

### ISSUE THREAD

**Issue by travisby** [jinzhu/gorm#593]
Hello,

I believe the AddForeignKey table has a small bug in it:

My golang code:

```go
 db.Model(&A{}).AddForeignKey("b_id", "b(id)", "RESTRICT", "RESTRICT")
```
Generated Query:

```sql
 ALTER TABLE "a" ADD CONSTRAINT "a_b_id_foreign" FOREIGN KEY ("b_id") REFERENCES "b(id)" ON DELETE RESTRICT ON UPDATE RESTRICT;
```

Expected query (runs in postgres):

 ```sql
ALTER TABLE "a" ADD CONSTRAINT "a_b_id_foreign" FOREIGN KEY ("b_id") REFERENCES b(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
```

I *think* the solution is to not QuoteIfPossible on: https://github.com/jinzhu/gorm/blob/0def184b0ca6d0b4d4b772a18b909d35b6cb86a1/scope_private.go#L574 for dest

Hope this is helpful for others who use foreign keys :)  I was able to convert all but two of my foreign keys to struct tags (`sql:"type uuid REFERENCES c(id)"`), but I encountered this when two tables referred to one another (so I can't change creation ordering, heh)

**Comment by bertzzie** [comment]
Hello,

I have the same problem in MariaDB (MySQL). Here's my database version for reference:

    $ mysql --version
    mysql  Ver 15.1 Distrib 10.0.19-MariaDB, for osx10.10 (x86_64) using readline 5.1

The rest of my problem is exactly the same with @travisby. Not sure about the solution though.

**Comment by tsingson** [comment]
Thanks 

发自我的 iPhone
