### ISSUE TITLE
Crash when dealing with multiple requests

### ISSUE THREAD

**Issue by tland** [jinzhu/gorm#596]
Hi @jinzhu,

While I am not 100% sure the following crash is due to gorm's fault, I guess it might still have something to do with the use of golang's buildin non-thread-safe map. I can easily reproduce the crash by firing multiple requests to my server at the same time. The [smap](https://github.com/jinzhu/gorm/blob/master/utils.go#L20) map defined in utils.go is shared within the package and can be modified by method [ToDBName](https://github.com/jinzhu/gorm/blob/master/utils.go#L37). Perhaps it needs a write protection, though there could be a penalty performance wise.

Go version: 1.4.2 darwin/amd64
Gorm commit: 6b8f2fc

Backtrace attached:

```
fatal error: bad map state

goroutine 19 [running]:
runtime.gothrow(0x7c14b0, 0xd)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/panic.go:503 +0x8e fp=0xc2082a4850 sp=0xc2082a4838
runtime.evacuate(0x566ac0, 0xc2081f2b70, 0x1)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/hashmap.go:799 +0x36a fp=0xc2082a4910 sp=0xc2082a4850
runtime.growWork(0x566ac0, 0xc2081f2b70, 0x2)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/hashmap.go:769 +0x8a fp=0xc2082a4930 sp=0xc2082a4910
runtime.mapassign1(0x566ac0, 0xc2081f2b70, 0xc2082a4a88, 0xc2082a4a78)
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/hashmap.go:408 +0x18f fp=0xc2082a49d0 sp=0xc2082a4930
github.com/jinzhu/gorm.ToDBName(0x7af730, 0xb, 0x0, 0x0)
	Go/src/github.com/jinzhu/gorm/utils.go:37 +0x30a fp=0xc2082a4ac8 sp=0xc2082a49d0
github.com/jinzhu/gorm.(*Scope).GetModelStruct(0xc2080b4300, 0x0)
	Go/src/github.com/jinzhu/gorm/model_struct.go:148 +0xc2a fp=0xc2082a4e20 sp=0xc2082a4ac8
github.com/jinzhu/gorm.(*Scope).PrimaryField(0xc2080b4300, 0x19)
	Go/src/github.com/jinzhu/gorm/scope.go:130 +0x28 fp=0xc2082a4e80 sp=0xc2082a4e20
github.com/jinzhu/gorm.(*Scope).PrimaryKey(0xc2080b4300, 0x0, 0x0)
	Go/src/github.com/jinzhu/gorm/scope.go:143 +0x3a fp=0xc2082a4e98 sp=0xc2082a4e80
github.com/jinzhu/gorm.Query(0xc2080b4300)
	Go/src/github.com/jinzhu/gorm/callback_query.go:20 +0x10d fp=0xc2082a51d8 sp=0xc2082a4e98
github.com/jinzhu/gorm.(*Scope).callCallbacks(0xc2080b4300, 0xc208078a60, 0x3, 0x4, 0xc2080b4300)
	/Go/src/github.com/jinzhu/gorm/scope_private.go:310 +0x6b fp=0xc2082a5218 sp=0xc2082a51d8
github.com/jinzhu/gorm.(*DB).First(0xc2081e41e0, 0x70a480, 0xc208059180, 0x0, 0x0, 0x0, 0xc2081aa000)
	/Go/src/github.com/jinzhu/gorm/main.go:204 +0x172 fp=0xc2082a5270 sp=0xc2082a5218
```

Thanks,

**Comment by tland** [comment]
Just to follow up on this issue, found a quick fix as below is working for me.

```
--- a/utils.go
+++ b/utils.go
@@ -3,6 +3,7 @@ package gorm
 import (
        "bytes"
        "strings"
+       "sync"
 )

 // Copied from golint
@@ -16,10 +17,13 @@ func init() {
        }
        commonInitialismsReplacer = strings.NewReplacer(commonInitialismsForReplacer...)
 }
-
+var lock sync.Mutex
 var smap = map[string]string{}

 func ToDBName(name string) string {
+       lock.Lock()
+       defer lock.Unlock()
+
        if v, ok := smap[name]; ok {
                return v
        }
```

**Comment by jinzhu** [comment]
Although `smap` is non-thread-safe map, won't cause any problem, I have tested it with lots of requests before.

Not sure if the issue caused by recently go updates, But if the program could be crashed due to this? definitely we need to fix that.

**Comment by tland** [comment]
I am using Beego in combination with GORM. Beego uses goroutine to handle each request according to its doc, which seems explains why I can reproduce the crash with even less than 10 requests. 

Beego implements its own version of thread-safe [map](https://github.com/beego/beedoc/blob/master/en-US/Controllers_SafeMap.md). I never used it, however it might give some insight.

**Comment by chakrit** [comment]
@jinzhu @tland before Go 1.5 GOMAXPROCS defaults to `1` which might explains why your code works before. In Go 1.5, this is no longer the case.

See https://docs.google.com/document/d/1At2Ls5_fhJQ59kDK2DFVhFu3g5mATSXqqV5QrxinasI/edit

So it's a race condition, that didn't happen before because of GOMAXPROCS. This needs to be fixed.

**Comment by jinzhu** [comment]
HI @all

I just added the safe map back, hope this will resolve the problem.
