### ISSUE TITLE
support limit and offset for sqlserver 2008

### ISSUE THREAD

**Issue by sdhjl2000** [jinzhu/gorm#597]
for now "FETCH NEXT" don't work for sql server 2008,i create a fork(https://github.com/sdhjl2000/gorm/commit/1d05ca32a9c7b1e3ab5ff467328bb83da8c7c151) and use  the old  "ROW_NUMBER() OVER " way solve this problem ,but it break query to use fetch feature for new sqlserver version. any suggestion

**Comment by jinzhu** [comment]
I am not a mssql expert, but I think support newer sql server versions should be better.

Anyway, PR is welcome, If could make it works on any version.
