### ISSUE TITLE
Order of Preload

### ISSUE THREAD

**Issue by jeffutter** [jinzhu/gorm#598]
Is there any way to do a .Order on a preload?

I am doing something like this:
```go
DB.Preload("Images").Preload("Images.SmallFile").Preload("Images.DefaultFile").Where("slug = ? AND type = ?", slug, page_type).Find(&page)
```

And I would like to get the Images ordered by Position. Is this possible in one query?

**Comment by nbgo** [comment]
Also would to have this feature.

**Comment by sarim** [comment]
I tried to implement this in https://github.com/sarim/gorm/commit/1ed8d908dfa1184deabfda5260f1a22117c62538 . only for `has_many` for now. I'll try to implement `many_to_many` later and do PR.

Right now it works like this

```go
db.Order("g_id asc").Preload("Categories").PreloadOrder("c_id asc").Find(&groups)
```

Looking for suggestion from maintainer/owner.

**Comment by jinzhu** [comment]
It is possible to use multiple `Preload` like

`db.Preload("Categories").Preload("Brands").Find(&products)`

So having another method `PreloadOrder` make me feel confusing ;(

It might be good to use inline conditions for this, something like:

`db.Preload("Categories", "order by id desc").Find(&groups)`

But right now, the inline condition is used as where conditions, so it won't works.

**Comment by sarim** [comment]
In multiple preload, my current code will work like
```go
db.Preload("Categories").PreloadOrder("category_id asc").Preload("Brands").PreloadOrder("brand_id asc").Find(&products)
```
Call to `PreloadOrder` adds the OrderBy to last preload on preload list, so it is possible to apply order to individual Preloads.
Still, not clean.
I'm been using Doctrine ORM (php) for a long time, the way it works there is, orderBy clauses are defined in field tag. Similar Example would be:
```go
type Product struct {
     ............
     Categories []ProductCategory `gorm:"orderby:c_id"`
}
```
It is less confusing that way.


> But right now, the inline condition is used as where conditions, so it won't works.

Yes, Everything is `string` now, i think a cleaner way would be using types.

```go
type WhereCondition struct {
   Condition string
   Value string
}

type OrderCondition struct {
   Column string
   Order string
}
.....................
db.Preload("Categories", WhereCondition{"color = ?", "blue"}, OrderCondition{"id", "desc"}).Find(&groups)
```

**Comment by jinzhu** [comment]
So maybe go with the `tag solution` for now, and think using types as conditions later.

Ideas?
