### ISSUE TITLE
Callbacks are not triggered on associations

### ISSUE THREAD

**Issue by TMaYaD** [jinzhu/gorm#599]
Here is a gist of the callbacks_test.go modified for association callbacks. Not complete by any stretch of the word but a good starting point IMHO.

https://gist.github.com/TMaYaD/2de2578c4a9e4a6ffd70

**Comment by TMaYaD** [comment]
On further debugging any saves inside callbacks are calling further callbacks. Is this a *"feature"*?

**Comment by jaytaylor** [comment]
Yes this is documented - checkout the #callbacks section of the [README](https://github.com/jinzhu/gorm/blob/master/README.md#callbacks).

Also good to be aware of gorm's excellent callback system makes it's possible to override or re-wire the callbacks to suit particular needs and use-cases.

Here is an example one that @jinzhu helped me create - [gorm_aliven_soft_deletion.go](https://gist.github.com/jaytaylor/6ae48dc26a36c98d34b2).
