### ISSUE TITLE
Change Id to ID

### ISSUE THREAD

**Issue by feribg** [jinzhu/gorm#60]
Seems like the default primary key is hardcoded to be "Id", while golint suggest "ID" as the id field of a struct. Not that this is of any importance, but would be nice to be compliant with the coding standards.

"dao.go:16:2: struct field Id should be ID"

**Comment by GeertJohan** [comment]
:+1:

**Comment by GeertJohan** [comment]
Wasn't this issue solved by #175 ?
I think it can be closed.

**Comment by jinzhu** [comment]
Yes, this issue could be resolved with that pull request, but I am going to make gorm support `ID` w/o specify the column

**Comment by jinzhu** [comment]
Hi all,

The ID should works without any change now, and all other common initialisms should also works.

Here is the list (get it from golint): 

"API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "LHS", "QPS", "RAM", "RHS", "RPC", "SLA", "SMTP", "SSH", "TLS", "TTL", "UI", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XSRF", "XSS"

**Comment by wwwdata** [comment]
wow, big thx!
