### ISSUE TITLE
Preload(): can't find field

### ISSUE THREAD

**Issue by nbgo** [jinzhu/gorm#607]
This preload fails by some reason. Now I am using gorm:"foreignkey:OuID", but it does not help. Still having "can't find field Users in *[]main.OrganizationUnit"
```
package main
import (
	"github.com/jinzhu/gorm"
	_ "github.com/mattn/go-sqlite3"
	"database/sql"
	"log"
	"os"
)

type User struct {
	gorm.Model
	UserName    string `sql:"not null;unique"`
	Ou          *OrganizationUnit
	OuID        sql.NullInt64
}

type OrganizationUnit struct {
	gorm.Model
	Name       string `sql:"not null;unique"`
	Users      []User `gorm:"foreignkey:OuID"`
}

func main() {
	db, _ := gorm.Open("sqlite3", "test.db")
	db.SetLogger(log.New(os.Stderr, "", log.LstdFlags))
	db.LogMode(true)
	db.SingularTable(true)
	db.AutoMigrate(&User{}, &OrganizationUnit{})
	var ous []OrganizationUnit
	db.Preload("Users").Find(&ous)
}
```

**Comment by KevinSjoberg** [comment]
Could this be related to #602?

**Comment by nbgo** [comment]
Not sure. Second call of db.Preload("Users").Find(&ous) produces the same error.

**Comment by nbgo** [comment]
Using 
```
db.AutoMigrate(&OrganizationUnit{}, &User{})
```
instead of 
```
db.AutoMigrate(&User{}, &OrganizationUnit{})
```
fixes the problem. Could anybody do any explanations?

**Comment by goddardcm** [comment]
Must be related, as mentioned by @KevinSjoberg, to #602. I just left a [comment] (https://github.com/jinzhu/gorm/issues/602#issuecomment-134102784) there with some findings as to when the problem first arose.

**Comment by jinzhu** [comment]
Hi All,

This issue should be fixed, sorry for the problem.
