### ISSUE TITLE
Tags Documentation

### ISSUE THREAD

**Issue by JesusIslam** [jinzhu/gorm#608]
It seems that gorm lacks documentation for `gorm` and `sql` tags. 
Any pointer in where I could find them?

**Comment by zasran** [comment]
This would be very useful, as far as I can tell right now the only way to find out about the tags is to read the source (some are mentioned in docs).

**Comment by zasran** [comment]
Also see issue  #362 which is an old bug that has some information about the struct tags that gorm uses. It would be really useful if it was properly documented (I stumbled across issue #362 somehow but it's not easy to find)

**Comment by jinzhu** [comment]
Hi All

I suggest only used documented tags in the README, all other tags don't promise any compatibility.

But be sure to let me know what is missing when develop your application.

![image](https://cloud.githubusercontent.com/assets/6843/9804049/dbd68186-585b-11e5-85ad-5e6231fe7198.png)

**Comment by angelbirth** [comment]
@jinzhu 
I may have overlooked, but where is the README you mentioned?
