### ISSUE TITLE
Wrong ID Inserted on Complex JOIN Query

### ISSUE THREAD

**Issue by bertzzie** [jinzhu/gorm#610]
Hello,
I think I've found a bug when we use a complex query involving several joins on table. A demonstration of my problem:

The models I use:

    type Contributor struct {
        ID        int64
        Name      string    `sql:"size:255;not null;index:name"`
        Email     string    `sql:"size:255;not null;unique_index"`

        Posts []Post
    }

    type Category struct {
        ID          int64
        Heading     string `sql:"type:text;not null"`
        Description string `sql:"type:text;"`
        Image       string `sql:"type:text;"`
    }

    type Post struct {
        ID        int64
        Title     string    `sql:"size:1024;not null"`
        Content   string    `sql:"type:text;not null"`
        Published bool      `sql:"default:false;not null"`
        CreatedAt time.Time `sql:"default:NOW();not null"`
        UpdatedAt time.Time `sql:"default:NOW();not null"`

        Author     *Contributor
        AuthorID   int64      `sql:"not null;REFERENCES contributors(id)"` // foreign key
        Categories []Category `gorm:"many2many:post_categories"`           // many to many to prepare for future use
    }

Now I want to get all posts by a particular contributor, filtered by category. Here's how I do it, per #358:

    var posts []models.Post
    db = db.Preload("Author").Order("created_at desc")

    // some processing to get user id

    db = db.Where("author_id = ?", uid)

    db = db.Joins(
        "join post_categories as pc on posts.id = pc.post_id " +
        "join categories as c on c.id = pc.category_id")

    // some processing to get category id

    db = db.Where("c.id = ?", category)
    db.Find(&posts)

The resulting query, if called with `Debug()` here is:

    SELECT  * 
        FROM `posts` 
            join post_categories as pc on posts.id = pc.post_id 
            join categories as c on c.id = pc.category_id 
        WHERE (c.id = '5') 
        ORDER BY created_at desc

Which gives us the right query, but on the resulting `posts` I get the wrong `Post.ID` for every post. All the IDs inserted into those posts are the same: the category's ID. I think gorm inserted the wrong ID into the posts because both `posts` and `categories` tables have a `ID` column.

I could workaround this by using a `Select` statement like this:

    db = db.Select("posts.id, posts.title, posts.content, posts.published, posts.created_at, posts.updated_at, posts.author_id")

But I think gorm should be able to detect the right ID to use.

For now, I can only report this bug, but I'll try to submit pull request once I got the time to. Hope this helps.

**Comment by jinzhu** [comment]
Hi @bertzzie 

Thank you for your report, already fixed that.
