### ISSUE TITLE
Question - Save dirty only?

### ISSUE THREAD

**Issue by MathieuDoyon** [jinzhu/gorm#612]
Does Gorm only update dirty fields 
or update the complete struct?

**Comment by adrianmacneil** [comment]
In my experience it updates the entire struct, regardless of what has changed.

**Comment by jinzhu** [comment]
yes, it will update complete struct, as it can't know dirty fields.

but you could use `Select`, `Omit` to select/omit some fields when update.

**Comment by gwillem** [comment]
FYI `norm` has solved this with shadow field values:

https://github.com/picatic/norm/blob/master/field/decimal.go

**Comment by jinzhu** [comment]
>　FYI norm has solved this with shadow field values

If you define field types properly, then nothing needs to do with GORM to support this, the problem is you have to redefine all data types... and if you want to go this way...
