### ISSUE TITLE
Find() ignoring Soft Delete

### ISSUE THREAD

**Issue by LiranCohen** [jinzhu/gorm#618]
There seems to be a bit of an error with Soft Delete feature.  And I don't think this was always the case, not sure how recent it started occurring.

A simple .Find (even passing the ORDER function) will ignore any mention of soft delete.
A more complex Find (using count) will take soft delete into account, but not for the initial count... that will still count all records.

I never really noticed this before because of 2 reasons.
a) Most of my Find requests are pretty complex with preload, count, limit, offset, etc. 
b) I have not noticed the count discrepancies because I've only been working with test data.  

Can anyone else confirm this?

type Company struct {
   ID int
   Name string
   CreatedAt time.Time
   UpdatedAt time.Time
   DeletedAt time.Time
}

c := Company{}

if query := db.Model(c).Order("id asc").Find(&c); query.Error != nil {
   panic(query.Error)
}

//[2015-08-13 17:20:59]  [30.75ms]  SELECT  * FROM "companies"   ORDER BY id asc

c := Company{}
var count int

if query := db.Model(c).Count(&count).Find(&c); query.Error != nil {
   panic(query.Error)
}

//[2015-08-13 16:09:37]  [10.48ms]  SELECT  count(*) FROM "companies"
//[2015-08-13 16:09:37]  [0.98ms]  SELECT  * FROM "companies"  WHERE ("companies".deleted_at IS NULL OR "companies".deleted_at <= '0001-01-02')

**Comment by jinzhu** [comment]
seems works for me.

```go
package main

import (
	"fmt"
	"time"

	_ "github.com/go-sql-driver/mysql"
	"github.com/jinzhu/gorm"
	_ "github.com/mattn/go-sqlite3"
)

type Company struct {
	ID        int
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt time.Time
}

func main() {
	dbuser, dbpwd := "gorm", "gorm"
	db, err := gorm.Open(
		"mysql",
		fmt.Sprintf("%s:%s@/gorm?parseTime=True&loc=Local", dbuser, dbpwd),
	)
	// db, err := gorm.Open("sqlite3", "/tmp/gorm.db")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)

	db.AutoMigrate(&Company{})

	c := Company{}
	db.Model(c).Order("id asc").Find(&c)
}
```

![image](https://cloud.githubusercontent.com/assets/6843/9804153/3c911a8a-585d-11e5-889f-13673d3a8ea2.png)


FYI, you could try `gorm.Model` for id, created_at, deleted_at...

**Comment by kiwih** [comment]
+1 for me. The following:

`dbGorm.Debug().Model(&MonitoringInstruction{}).Where(&MonitoringInstruction{AccountId: p.Id}).Find(&monitoringInstructions)`

returns 

`SELECT  * FROM "monitoring_instructions"  WHERE ("account_id" = 'a444cf21-f6e5-43f6-a6ca-8f35826d8cf3')`

MonitoringInstructions do feature a DeletedAt field, and it is present in more complex queries.

No mention of soft delete in there. I am using sqlite3 as the driver, and using UUIDs (as shown).

**Comment by schultz9999** [comment]
I am having the same issue with `Where`: 
```
	if err := d.roconn.Where(filter).Find(res).Error; err != nil {...
```
