### ISSUE TITLE
AutoMigrate and Many2Many does not seem to set any constraints on the bridge table

### ISSUE THREAD

**Issue by robvdl** [jinzhu/gorm#619]
If I have the following User and Group models with a many 2 many field on User called "Groups":

<pre>
type User struct {
	ID       uint `gorm:"primary_key"`
	Username string
	Groups   []Group `gorm:"many2many:user_group;"`
}

type Group struct {
	ID   uint `gorm:"primary_key"`
	Name string
}
</pre>

Right now when calling AutoMigrate on these models it generates the following SQL in Postgres for the bridge table:

<pre>
CREATE TABLE user_group
(
  user_id integer,
  group_id integer
)
</pre>

Note that there are no constraints at all on the bridge table, there is no combined primary key between user_id and group_id, also user_id and group_id don't have foreign keys on them, I would expect to see something like this instead:

<pre>
CREATE TABLE user_group
(
  user_id integer,
  group_id integer
  PRIMARY KEY (user_id, group_id),
  FOREIGN KEY (user_id) REFERENCES user (id),
  FOREIGN KEY (group_id) REFERENCES group (id)
)
</pre>

For me this is a bit of a deal breaker and makes me want to create the bridge tables by hand using SQL instead, any chance this could get fixed?

**Comment by jaytaylor** [comment]
I've noticed the same issue and ended up putting some manual statements.
Would love to see it fixed and/or implemented!

On Sat, Aug 15, 2015 at 5:44 AM, Rob van der Linde <notifications@github.com

**Comment by robvdl** [comment]
Yeah, you can basically still let Gorm create the bridge table as it does now, then add the primary and foreign key constrains manually after with some manual SQL, at least in Postgres I can add the constrains after.

It would be really nice if these constraints get added automatically though.

**Comment by robvdl** [comment]
I am happy to help and implement this, I really need bridge tables to be created with foreign key and primary key constraints by default, I am not really that keen on manual statements after creating tables that manually add these in.

If there is no objection to this, this is what I wanted to do:

If using gorm:many2many tag on a field:

 * automatically create the correct foreign key constraints on both *_id fields
 * create a combined primary key constraint across both fields *_id fields

Notes:

I think a combined primary key is definitely the best and easiest way to go. However, sometimes people also tend make this into a combined unique constraint instead and add an extra primary key id column on the bridge table instead. The question is do we need to support this (a this point) a an extra option to the many2many tag? or not? You probably need it on a case by case basis and only for certain models, not necessarily all your models. I guess that this can always be added later if needed as it really is a new feature all together.  The cool thing with this however, is that the bridge table itself can be made a struct if needed.

I am also going to have a look if this affects both CreateTable and AutoMigrate, so far I only know it affects AutoMigrate.

I know you can do

**Comment by jinzhu** [comment]
Hi @robvdl 

It would be good to have this feature. before when I look at it, it might caused failed to create tables if two many2many structs has each other in postgres, because postgres has strict check when create table.

**Comment by JeanLebrument** [comment]
Any update so far?

**Comment by robvdl** [comment]
I haven't done any work towards this yet sorry, I've been sort of busy working on a big patch to another project the last few weeks.  I am still interested in doing this ticket at some point though, unless someone else beats me to it!

**Comment by jinzhu** [comment]
Duplicated with #450
