### ISSUE TITLE
when createTable failed, there is no error info.

### ISSUE THREAD

**Issue by wujunbin** [jinzhu/gorm#623]
In your READEME.md file, there is an user struct.
there is a filed that is " Num int `sql:"AUTO_INCREMENT"` " in your struct.
it is wrong because id is also an auto_increment column.
When i call the method db.CreateTable(), there is nothing info about the error and the program runs successfully.  I think that it should panic an error for user, when CreateTable encounter something that is wrong. If not, finding the error is a difficult thing.

**Comment by tugouer** [comment]
I called the method db.AutoMigrate(), and I got a log message, tell me to add an 'index' for this column

**Comment by jinzhu** [comment]
There should be some error if you are checking, when I test it got

`Error 1075: Incorrect table definition; there can be only one auto column and it must be defined as a key`

```go
package main

import (
	"fmt"

	_ "github.com/go-sql-driver/mysql"
	"github.com/jinzhu/gorm"
	_ "github.com/mattn/go-sqlite3"
)

type MyStruct struct {
	gorm.Model
	Num         int    `sql:"AUTO_INCREMENT"`
	CurrentCNPJ string `gorm:"column:current_cnpj" sql:"not null;size:50;"`
}

func main() {
	dbuser, dbpwd := "gorm", "gorm"
	db, err := gorm.Open(
		"mysql",
		fmt.Sprintf("%s:%s@/gorm?parseTime=True&loc=Local", dbuser, dbpwd),
	)
	// db, err := gorm.Open("sqlite3", "/tmp/gorm.db")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
	fmt.Println(db.DropTable(&MyStruct{}).Error)
	fmt.Println(db.CreateTable(&MyStruct{}).Error)
	fmt.Println(db.AutoMigrate(&MyStruct{}).Error)
}
```
