### ISSUE TITLE
Should support get table name from .Where(), If it's passing struct address 

### ISSUE THREAD

**Issue by sunfmin** [jinzhu/gorm#626]
```
DB.Where(&ReportItem{ClientDeviceInID: clientDeviceInID}).Delete()
```

Currently this doesn't work. Should support it. :-)

**Comment by jinzhu** [comment]
Not going to support that, will be confusing especially when where is using string as conditions.

Maybe using `DB.Delete(&ReportItem{ClientDeviceInID: clientDeviceInID}`?
