### ISSUE TITLE
Enum default tag doesn't seems to work

### ISSUE THREAD

**Issue by JesusIslam** [jinzhu/gorm#628]
This tag doesn't seems to work in the model, it doesn't set the default to 'user' on insert.

`sql:"type:enum('user','creator','admin') DEFAULT 'user'"`

Am I doing it wrong?

**Comment by jinzhu** [comment]
`sql:"type:enum('user','creator','admin');DEFAULT:user"`

**Comment by qshuai** [comment]
Please mysql usage: [https://github.com/jinzhu/gorm/issues/1978#issuecomment-421919405](https://github.com/jinzhu/gorm/issues/1978#issuecomment-421919405)
