### ISSUE TITLE
db.find returns only one record ie (last modified record)

### ISSUE THREAD

**Issue by naviens** [jinzhu/gorm#629]
db.find returns only one record. ie (last modified record) even though there is 10 records in my table.
But on debugging mode query is correct
My query 
	user := models.User{}
	Gdb.Find(&user)
	fmt.Println(user)

Debug: 
[2015-08-23 18:00:55]  [2.10ms]  SELECT  * FROM "users"  
{11  Jinzhup []  2015-08-23 17:51:47.388222 +0530 IST 2015-08-23 17:51:47.388222 +0530 IST}

**Comment by ccxdd** [comment]
please try
```go
user := models.User{}
Gdb.Find(&user, 1)
fmt.Println(user)
```

**Comment by jinzhu** [comment]
```go
users := []models.User{}
db.Find(&users)
