### ISSUE TITLE
Problem calling callback in bulk delete

### ISSUE THREAD

**Issue by mrkaspa** [jinzhu/gorm#630]
When I do this, calls the callback AfterDelete with zeros values in the struct

```go
txn.Where("user_id = ? and project_id = ?", u.ID, projectID).Delete(UsersProjects{}).Error

//the callback
func (u UsersProjects) AfterDelete(txn *gorm.DB) error {}
```
The u inside the callback has zero fields, so I think it should pass the real variable to the callback or don't call the callback

**Comment by jinzhu** [comment]
It will pass the value you passed to `Delete` to `Callback`

You might want to find the value out first, then delete it, like:

```go
if !db.First(&userProject, "user_id = ? AND project_id = ?", uid, pid).RecordNotFound() {
  db.Delete(&userProject)
}
```
