### ISSUE TITLE
create table error

### ISSUE THREAD

**Issue by FlamingTree** [jinzhu/gorm#631]
when table has combined primary key when both type are int, they are all defined auto increment, but it's not permitted

**Comment by alecha** [comment]
The solution to this issue to manually define the sql type in the field tag, an example:

    type UserRole struct {
        UserID int64 'sql:"type:bigint(20);not null;" json:"userId" gorm:"primary_key"'
        RoleID int64 'sql:"type:bigint(20);not null;" json:"roleId" gorm:"primary_key"'
    }

**Comment by jinzhu** [comment]
@alecha thank you for your reply.

just create with unique_index for `UserID`, `RoleID`
