### ISSUE TITLE
Document dialect interface

### ISSUE THREAD

**Issue by zasran** [jinzhu/gorm#632]
It would be useful to have documentation for Dialect interface.

Some function names are self-explanatory, e.g. HasTable returns boolean that says whether a given database has a table of a given name. However some other ones are not so obvious, e.g. BinVar, SupportLastInsertId (what support exactly?) etc.

Thinking of adding support for HANA (driver github.com/SAP/go-hdb/driver) so hoping to get a bit more information to start...

**Comment by bpizzi** [comment]
I Second that, I'd like to implement driver rana/ora for Oracle and a documented interface would be helpful here.

**Comment by jinzhu** [comment]
I have added some documents about `Dialect`, please refer v1.0_dev branch https://github.com/jinzhu/gorm/blob/v1.0_dev/dialect.go

Feedbacks welcome
