### ISSUE TITLE
Print query

### ISSUE THREAD

**Issue by dani-h** [jinzhu/gorm#634]
Is it possible to print the SQL query generated by gorm methods? I'm looking for a way to inspect the sql query created after `db.CreateTable()` and `db.First()` so that I can debug it in case anything goes wrong. Currently I have an error message that warns me about syntax errors near `CONSTRAINT`, but since I can't see the entire query debugging is hard.

**Comment by grounded042** [comment]
This should be what you need: https://github.com/jinzhu/gorm#logger

**Comment by dani-h** [comment]
Thanks!
