### ISSUE TITLE
Foreign key for SQLite doesn't work

### ISSUE THREAD

**Issue by dani-h** [jinzhu/gorm#635]
It seems like SQLite does not support `ALTER TABLE ADD CONSTRAINT` as per https://sqlite.org/omitted.html and yet gorm tries to add foreign keys using this syntax.

When running this code I get the cryptic error message
```go
db.CreateTable(&transaction{}).AddForeignKey("account_id", "accounts(id)", "RESTRICT", "RESTRICT")
```
(near "CONSTRAINT": syntax error) 

Same error I hit in #634

**Comment by nbgo** [comment]
And some more details here: https://github.com/jinzhu/gorm/pull/360

As to me I use this vatiant:
```
type User struct {
	Ou          *OrganizationUnit
	OuID        sql.NullInt64 `sql:"type:integer REFERENCES organization_unit(id) ON DELETE CASCADE ON UPDATE CASCADE"`
}
```

**Comment by dani-h** [comment]
@nbgo Thanks, I resorted to raw SQL for creating the table with the foreign key but that looks better.

**Comment by jinzhu** [comment]
@nbgo looks good.

**Comment by lmas** [comment]
So it's still a bug and you still have to use the example provided by @nbgo?

**Comment by pankajcheema** [comment]
@nbgo  Not working for me

**Comment by rafalbraun** [comment]
for future travellers that reach this thread - by peeking into the gorm code one can find a line with a commentary:
[`847| // sqlite does not support ADD CONSTRAINT in ALTER TABLE`](https://github.com/jinzhu/gorm/blob/master/association_test.go#L847)

The reason for this is the fact that sqlite3 by default cannot add foreign key constraint on already created table - the only way to do this is through data definition table (prettty peculiar I think). What is even funnier the official documentation mentions [fallback](https://www.techonthenet.com/sqlite/foreign_keys/foreign_keys.php?fbclid=IwAR1cBPZ2-te7K3mTBj4N1mjW1gs5ud0IPJzp0V_RZe8Pdi1oBjaDWm4ey7g)

my recommendation is to swich to mysql or postgresql or not to migrate schema through gorm
