### ISSUE TITLE
When I select MAX() and MIN() for same column, How can I Scan it ? 

### ISSUE THREAD

**Issue by sotayamashita** [jinzhu/gorm#638]
For example, Here is a table named **A** and I run query `SELECT MIN(size), MAX(size) FROM A; `

```
mysql > show columns from A;
+----+------+
| id | size |
+----+------+
|  1 |    4 |
|  2 |    0 |
+----+------+

mysql > select max(size), min(size) from A;
+-----------+-----------+
| max(size) | min(size) |
+-----------+-----------+
|         4 |         0 |
+-----------+-----------+
```

**Comment by sotayamashita** [comment]
I solve this question.

**Comment by younglifestyle** [comment]
How did you do it?

**Comment by younglifestyle** [comment]
thank you，I have solved it.

**Comment by zhangwei17** [comment]
how did you solve it?

**Comment by zhangwei17** [comment]
I just want to get the value of MAX(version),neither the code db.Instance.Raw("select max(version) as version from config").Pluck("version", &version) nor db.Instance.Raw("select max(version) as version from experiment_config").scan(&version) got the right value. They both report error with message:results should be a slice, not int
