### ISSUE TITLE
Related ignores model foreign keys, uses default ones

### ISSUE THREAD

**Issue by zasran** [jinzhu/gorm#640]
We have following data structures:

	User struct {
		Id            uint64        `json:"id" gorm:"column:USER_ID;primary_key"`
		// ...
		PhoneNumbers  []PhoneNumber `json:"phoneNumbers" gorm:"foreignkey:UserId"`
	}
	PhoneNumber struct {
		Id     uint64 `json:"id" gorm:"column:PHONE_NUMBER_ID;primary_key"`
		UserId uint64 `json:"userId" gorm:"column:USER_ID"`
		// ...
	}
	usersFromDb := []User{}
	db.Find(&usersFromDb)
	for i, _ := range usersFromDb {
		db.Model(usersFromDb[i]).Related(&usersFromDb[i].PhoneNumbers)
	}

Which results in an SQL query that uses default foreign key user_id when querying PhoneNumbers.

Function Related (main.go) is calling s.clone().NewScope(s.Value).related(value, foreignKeys...) which in turn only considers foreign keys passed to Related and default foreign keys, see scope_private.go related function which tries to find a valid foreign key like this:

	for _, foreignKey := range append(foreignKeys, toScope.typeName()+"Id", scope.typeName()+"Id") {
		// ...
	}

where foreignKeys are what's passed by Related and the other two are the default ones.

Not sure what the intent here is but as far as I can tell one of the following two approaches would make sense:

  - think the best solution that fits gorm well is for foreign keys set in model to always override default foreign keys, including in Related/related functions
  - not very good but at least somewhat reasonable solution would be to only use explicitly specified foreign keys in Related function, i.e. if the foreign keys from model are not used then do not use the default foreign keys either (I believe there is no valid use case where default foreign keys would work better (or even at all) if the model specifies foreign keys)

**Comment by jinzhu** [comment]
Seems like generating correct SQL for me

![image](https://cloud.githubusercontent.com/assets/6843/12103166/0d3db51c-b37b-11e5-9cc7-5042746816aa.png)

Also suggest you use `Preload` for the job.

```go
package main

import (
	_ "github.com/lib/pq"

	"github.com/jinzhu/gorm"
)

type User struct {
	Id           uint64 `json:"id" gorm:"column:USER_ID;primary_key"`
	Name         string
	PhoneNumbers []PhoneNumber `json:"phoneNumbers" gorm:"foreignkey:UserId"`
}

type PhoneNumber struct {
	Id     uint64 `json:"id" gorm:"column:PHONE_NUMBER_ID;primary_key"`
	UserId uint64 `json:"userId" gorm:"column:USER_ID"`
	Phone  string
}

func main() {
	db, err := gorm.Open("postgres", "user=gorm DB.name=gorm sslmode=disable")
	if err != nil {
		panic(err)
	}
	db.DropTable(&User{}, &PhoneNumber{})
	db.AutoMigrate(&User{}, &PhoneNumber{})

	db.LogMode(true)

	db.Create(&User{
		Name: "user",
		PhoneNumbers: []PhoneNumber{
			{Phone: "111"},
		},
	})

	usersFromDb := []User{}
	db.Find(&usersFromDb)
	for i, _ := range usersFromDb {
		db.Model(usersFromDb[i]).Related(&usersFromDb[i].PhoneNumbers)
	}
}
```
