### ISSUE TITLE
Question - behavior of the First() if struct have primary key value

### ISSUE THREAD

**Issue by deltam** [jinzhu/gorm#641]
First() added primary key to the conditions if struct have primary key.

https://github.com/jinzhu/gorm/blob/master/update_test.go#L403
```
freshUser := &User{Id: user.Id}
DB.Debug().First(freshUser)
// SELECT  * FROM "users"  WHERE ("id" = '110') ORDER BY "users"."id" ASC LIMIT 1
```
Is this behavior by design?

Is there a way to can change this behavior?

**Comment by jinzhu** [comment]
`First` will order by ID, `Find` won't do that.
