### ISSUE TITLE
Using gorm:column, all sql rules are ignored on automigrate

### ISSUE THREAD

**Issue by jplethier** [jinzhu/gorm#643]
I have a attribute on my struct called CurrentCNPJ, and I want the column name to be current_cnpj, and I want that column to not be null able and to be a string with size 50. So I did my struct like this:
```
type MyStruct struct {
  CurrentCNPJ string `gorm:"column:current_cnpj" sql:"not null;size:50;"`
}
```

The gorm column tag works perfectly, but the tags that I added to sql are ignored, and the result is that I have a table with a column named current_cnpj that are null able and is a string with 255 size.

**Comment by jinzhu** [comment]
It should works. 

Btw, did you added the sql tag at the beginning, or added it later, auto migrate won't change sql type once it is created.

**Comment by jplethier** [comment]
I added on the beginning, and after I tried to run automigrate again sometimes, always deleting the column, and all the times it create the column with correct name, but ignoring the sql tags

**Comment by jinzhu** [comment]
![image](https://cloud.githubusercontent.com/assets/6843/9803919/7a1da9e8-585a-11e5-895f-17a4f56b9f8c.png)

```go
package main

import (
	_ "github.com/go-sql-driver/mysql"
	"github.com/jinzhu/gorm"
	_ "github.com/mattn/go-sqlite3"
)

type MyStruct struct {
	CurrentCNPJ string `gorm:"column:current_cnpj" sql:"not null;size:50;"`
}

func main() {
	db, err := gorm.Open("sqlite3", "/tmp/gorm.db")
	if err != nil {
		panic(err)
	}
	db.LogMode(true)
	db.AutoMigrate(&MyStruct{})
}
```
Seems works for me.

**Comment by jplethier** [comment]
It is working now, I can't say why it was not working.
Em 10/09/2015 20:55, "Jinzhu" <notifications@github.com> escreveu:

**Comment by Usamon** [comment]
Hi ,(I am japanese, a little English Sorry)

I also experienced the same phenomenon.

〇 `gorm:"column:NAME;" sql:"size:16;not null;"
〇 `gorm:"column:NAME;size:16" sql:"type:varchar(n);not null;"

------------------------------
CREATE TABLE `ITEM` (`ID` integer NOT NULL, ,`NAME` varchar(16)

--------------------------------
merge size:16 + varchar(n)

but,
×　`gorm:"column:NAME;" sql:"type:varchar(n);size:16;not null;"
------------------------------
CREATE TABLE `ITEM` (`ID` integer NOT NULL, ,`NAME` varchar(n)

not merge , SQL "varchar(n)"
