### ISSUE TITLE
Create fails with 'sql: no rows in result set' (go-hdb driver)

### ISSUE THREAD

**Issue by zasran** [jinzhu/gorm#644]
Create uses QueryRow for insert. Driver for HANA (https://github.com/SAP/go-hdb) returns error sql.ErrNoRows (string "sql: no rows in result set") when insert is used which seems reasonable because insert does not return any rows.

Not sure how/why other drivers work but it seems that HANA works as described by http://golang.org/pkg/database/sql/ specifically the documentation of QueryRow and ErrNoRows error.

Any opinions on proper solution for this? Seems like the following options are at elast sort of reasonable:

- use Exec instead of QueryRow for INSERT, seems most appropriate, docs say that Exec is for queries that do not return rows like INSERT or UPDATE (Exec is already used by gorm for UPDATE)
- continue to use QueryRow but don't consider ErrNoRows to be an error
- ask HANA driver go-hdb to change behaviour or QueryRow, that does not sound too reasonable but if it's consensus that QueryRow should treat INSERT in some special way then I guess it would work

**Comment by danhardman** [comment]
I'm in favour of the first option, using Exec instead of QueryRow. We definitely shouldn't be ignoring ErrNoRows.

**Comment by jinzhu** [comment]
This should be changed already, thank you for your report.

QueryRow is used as postgres won't return the primary key like other database, right now, drivers that support return last insert id will use `Exec`, others will use `QueryRow`
