### ISSUE TITLE
go test errors for mssql database dialect

### ISSUE THREAD

**Issue by biju-kalissery** [jinzhu/gorm#647]
I got errors like the following while running 'go test'  using GORM_DIALECT = mssql.  
I am testing some fixes, will submit a pull request soon.

Environment: Go 1.5, Windows 10 64bit,  SQL Server 2014 running at localhost
All these tests pass if I use sqlite 

```
C:/Go/bin/go.exe test -v [C:/00_builds/go/src/github.com/jinzhu/gorm]
testing mssql...
=== RUN   TestRegisterCallback
--- PASS: TestRegisterCallback (0.00s)
=== RUN   TestRegisterCallbackWithOrder
--- PASS: TestRegisterCallbackWithOrder (0.00s)
=== RUN   TestRegisterCallbackWithComplexOrder
--- PASS: TestRegisterCallbackWithComplexOrder (0.00s)
=== RUN   TestReplaceCallback
[info] replacing callback `create` from C:/00_builds/go/src/github.com/jinzhu/gorm/callback_test.go:94
--- PASS: TestReplaceCallback (0.00s)
=== RUN   TestRemoveCallback
[info] removing callback `create` from C:/00_builds/go/src/github.com/jinzhu/gorm/callback_test.go:107
--- PASS: TestRemoveCallback (0.00s)
=== RUN   TestCloneSearch
--- PASS: TestCloneSearch (0.00s)
=== RUN   TestHasOneAndHasManyAssociation
--- PASS: TestHasOneAndHasManyAssociation (0.05s)
=== RUN   TestRelated
--- PASS: TestRelated (0.07s)
=== RUN   TestManyToMany
--- PASS: TestManyToMany (0.14s)
=== RUN   TestForeignKey
--- PASS: TestForeignKey (0.00s)
=== RUN   TestRunCallbacks
--- PASS: TestRunCallbacks (0.03s)
=== RUN   TestCallbacksWithErrors
--- PASS: TestCallbacksWithErrors (0.04s)
=== RUN   TestCreate
--- PASS: TestCreate (0.02s)
=== RUN   TestCreateWithNoGORMPrimayKey
--- FAIL: TestCreateWithNoGORMPrimayKey (0.00s)
	create_test.go:63: No error should happen when create a record without a GORM primary key. But in the database this primary key exists and is the union of 2 or more fields
		 But got: There is no generated identity value
=== RUN   TestCreateWithNoStdPrimaryKeyAndDefaultValues
--- PASS: TestCreateWithNoStdPrimaryKeyAndDefaultValues (0.01s)
=== RUN   TestAnonymousScanner
--- PASS: TestAnonymousScanner (0.01s)
=== RUN   TestAnonymousField
--- PASS: TestAnonymousField (0.01s)
=== RUN   TestSelectWithCreate
--- PASS: TestSelectWithCreate (0.04s)
=== RUN   TestOmitWithCreate
--- PASS: TestOmitWithCreate (0.03s)
=== RUN   TestCustomizeColumn
--- FAIL: TestCustomizeColumn (0.06s)
	customize_column_test.go:40: There should be one record be affected when create record
	customize_column_test.go:47: Failed to query CustomizeColumn
	customize_column_test.go:56: Failed to query CustomizeColumn
=== RUN   TestCustomColumnAndIgnoredFieldClash
--- PASS: TestCustomColumnAndIgnoredFieldClash (0.02s)
=== RUN   TestDdlErrors
testing mssql...
--- PASS: TestDdlErrors (0.02s)
=== RUN   TestDelete
--- PASS: TestDelete (0.02s)
=== RUN   TestInlineDelete
--- PASS: TestInlineDelete (0.02s)
=== RUN   TestSoftDelete
--- PASS: TestSoftDelete (0.16s)
=== RUN   TestSaveAndQueryEmbeddedStruct
--- PASS: TestSaveAndQueryEmbeddedStruct (0.03s)
=== RUN   TestJoinTable

[35m(There is no generated identity value)[0m 
[33m[2015-09-06 15:06:57][0m [31;1m [0m

[35m(There is no generated identity value)[0m 
[33m[2015-09-06 15:06:57][0m [31;1m [0m

[35m(There is no generated identity value)[0m 
[33m[2015-09-06 15:06:57][0m [31;1m [0m

[35m(There is no generated identity value)[0m 
[33m[2015-09-06 15:06:57][0m [31;1m [0m

[35m(There is no generated identity value)[0m 
[33m[2015-09-06 15:06:57][0m [31;1m [0m
--- FAIL: TestJoinTable (0.28s)
	join_table_test.go:58: Should found one address
	join_table_test.go:62: Should found one address
	join_table_test.go:66: Found two addresses with Unscoped
=== RUN   TestStringPrimaryKey
--- PASS: TestStringPrimaryKey (0.08s)
=== RUN   TestExceptionsWithInvalidSql

[35m(mssql: An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.)[0m 
[33m[2015-09-06 15:06:57][0m [31;1m [0m

[35m(mssql: Invalid column name 'aaa'.)[0m 
[33m[2015-09-06 15:06:57][0m [31;1m [0m

[35m(mssql: The multi-part identifier "sdsd.zaaa" could not be bound.)[0m 
[33m[2015-09-06 15:06:57][0m [31;1m [0m
--- PASS: TestExceptionsWithInvalidSql (0.01s)
=== RUN   TestSetTable

[35m(mssql: Invalid object name 'invalid_table'.)[0m 
[33m[2015-09-06 15:06:57][0m [31;1m [0m
--- PASS: TestSetTable (0.22s)
=== RUN   TestHasTable
--- PASS: TestHasTable (0.02s)
=== RUN   TestTableName
--- PASS: TestTableName (0.00s)
=== RUN   TestSqlNullValue

[35m(mssql: Cannot insert the value NULL into column 'name', table 'gosqltest.dbo.null_values'; column does not allow nulls. INSERT fails.)[0m 
[33m[2015-09-06 15:06:57][0m [31;1m [0m
--- PASS: TestSqlNullValue (0.03s)
=== RUN   TestTransaction

[35m(sql: Transaction has already been committed or rolled back)[0m 
[33m[2015-09-06 15:06:57][0m [31;1m [0m
--- PASS: TestTransaction (0.02s)
=== RUN   TestRow
--- PASS: TestRow (0.02s)
=== RUN   TestRows
--- PASS: TestRows (0.02s)
=== RUN   TestScan
--- PASS: TestScan (0.02s)
=== RUN   TestRaw
--- PASS: TestRaw (0.03s)
=== RUN   TestGroup
--- PASS: TestGroup (0.00s)
=== RUN   TestJoins
--- PASS: TestJoins (0.02s)
=== RUN   TestHaving
--- PASS: TestHaving (0.00s)
=== RUN   TestTimeWithZone
--- PASS: TestTimeWithZone (0.02s)
=== RUN   TestHstore
--- SKIP: TestHstore (0.00s)
	main_test.go:523: 
=== RUN   TestSetAndGet
--- PASS: TestSetAndGet (0.00s)
=== RUN   TestCompatibilityMode
`testdb` is not officially supported, running under compatibility mode.
--- PASS: TestCompatibilityMode (0.00s)
=== RUN   TestOpenExistingDB
--- PASS: TestOpenExistingDB (0.01s)
=== RUN   TestIndexes

[35m(mssql: Cannot insert duplicate key row in object 'dbo.emails' with unique index 'idx_email_email_and_user_id'. The duplicate key value is (36, user1@example.com).)[0m 
[33m[2015-09-06 15:06:57][0m [31;1m [0m

[35m(mssql: Cannot insert duplicate key row in object 'dbo.emails' with unique index 'idx_email_email_and_user_id'. The duplicate key value is (36, user1@example.com).)[0m 
[33m[2015-09-06 15:06:57][0m [31;1m [0m
--- PASS: TestIndexes (0.08s)
=== RUN   TestAutoMigration

[35m(mssql: The CREATE UNIQUE INDEX statement terminated because a duplicate key was found for the object name 'dbo.emails' and the index name 'uix_emails_registered_at'. The duplicate key value is (<NULL>).)[0m 
[33m[2015-09-06 15:06:58][0m [31;1m [0m
--- FAIL: TestAutoMigration (0.28s)
	migration_test.go:104: Auto Migrate should not raise any error
	migration_test.go:115: Failed to create index
=== RUN   TestManyToManyWithMultiPrimaryKeys
--- FAIL: TestManyToManyWithMultiPrimaryKeys (0.22s)
	multi_primary_keys_test.go:43: should found 3 tags with blog
=== RUN   TestPointerFields

[35m(mssql: An expression of non-boolean type specified in a context where a condition is expected, near ','.)[0m 
[33m[2015-09-06 15:06:58][0m [31;1m [0m

[35m(mssql: An expression of non-boolean type specified in a context where a condition is expected, near ','.)[0m 
[33m[2015-09-06 15:06:58][0m [31;1m [0m
--- PASS: TestPointerFields (0.04s)
=== RUN   TestPolymorphic
--- PASS: TestPolymorphic (0.15s)
=== RUN   TestPreload
--- PASS: TestPreload (0.14s)
=== RUN   TestNestedPreload1
--- PASS: TestNestedPreload1 (0.05s)
=== RUN   TestNestedPreload2
--- PASS: TestNestedPreload2 (0.06s)
=== RUN   TestNestedPreload3
--- PASS: TestNestedPreload3 (0.06s)
=== RUN   TestNestedPreload4
--- PASS: TestNestedPreload4 (0.06s)
=== RUN   TestNestedPreload5
--- PASS: TestNestedPreload5 (0.06s)
=== RUN   TestNestedPreload6
--- PASS: TestNestedPreload6 (0.07s)
=== RUN   TestNestedPreload7
--- PASS: TestNestedPreload7 (0.06s)
=== RUN   TestNestedPreload8
--- PASS: TestNestedPreload8 (0.06s)
=== RUN   TestNestedPreload9
--- PASS: TestNestedPreload9 (0.13s)
=== RUN   TestManyToManyPreloadWithMultiPrimaryKeys
--- FAIL: TestManyToManyPreloadWithMultiPrimaryKeys (0.10s)
panic: mssql: An expression of non-boolean type specified in a context where a condition is expected, near ','. [recovered]
	panic: mssql: An expression of non-boolean type specified in a context where a condition is expected, near ','.

goroutine 1586 [running]:
testing.tRunner.func1(0xc08200e090)
	c:/go/src/testing/testing.go:450 +0x178
github.com/jinzhu/gorm_test.TestManyToManyPreloadWithMultiPrimaryKeys(0xc08200e090)
	C:/00_builds/go/src/github.com/jinzhu/gorm/preload_test.go:652 +0xad8
testing.tRunner(0xc08200e090, 0xc65798)
	c:/go/src/testing/testing.go:456 +0x9f
created by testing.RunTests
	c:/go/src/testing/testing.go:561 +0x874

goroutine 1 [chan receive]:
testing.RunTests(0xa1fbd0, 0xc651e0, 0x62, 0x62, 0xc0824c6300)
	c:/go/src/testing/testing.go:562 +0x8b4
testing.(*M).Run(0xc082769ee8, 0xc08200a1c0)
	c:/go/src/testing/testing.go:494 +0x77
main.main()
	github.com/jinzhu/gorm/_test/_testmain.go:254 +0x11d

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	c:/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 454 [chan receive]:
database/sql.(*DB).connectionOpener(0xc0828e0dc0)
	c:/go/src/database/sql/sql.go:634 +0x4c
created by database/sql.Open
	c:/go/src/database/sql/sql.go:481 +0x33d

goroutine 881 [chan receive]:
database/sql.(*DB).connectionOpener(0xc0825e9b80)
	c:/go/src/database/sql/sql.go:634 +0x4c
created by database/sql.Open
	c:/go/src/database/sql/sql.go:481 +0x33d

goroutine 1619 [runnable]:
time.absDate(0x7ffffffe70c61f93, 0x1, 0x99df20, 0x0, 0x111, 0x99df24)
	c:/go/src/time/time.go:678
time.Time.AppendFormat(0xecd7e85d3, 0x1e8e7088, 0xc7fd40, 0xc082845bb0, 0x0, 0x40, 0x99df24, 0xf, 0x0, 0x0, ...)
	c:/go/src/time/format.go:460 +0x317
time.Time.Format(0xecd7e85d3, 0x1e8e7088, 0xc7fd40, 0x99df20, 0x13, 0x0, 0x0)
	c:/go/src/time/format.go:430 +0xf9
github.com/jinzhu/gorm.Logger.Print(0xfd4528, 0xc0820adf90, 0xc08287c220, 0x2, 0x2)
	C:/00_builds/go/src/github.com/jinzhu/gorm/logger.go:33 +0xca
github.com/jinzhu/gorm.(*Logger).Print(0xc0828e2bd0, 0xc08287c220, 0x2, 0x2)
	<autogenerated>:158 +0xbd
github.com/jinzhu/gorm.(*DB).print(0xc08207caa0, 0xc08287c220, 0x2, 0x2)
	C:/00_builds/go/src/github.com/jinzhu/gorm/main_private.go:23 +0x98
created by github.com/jinzhu/gorm.(*DB).AddError
	C:/00_builds/go/src/github.com/jinzhu/gorm/main.go:528 +0x287
exit status 2
FAIL	github.com/jinzhu/gorm	3.631s
Error: process exited with code 1.

```

**Comment by biju-kalissery** [comment]
Adding this  to mssql.go fixed most of the errors from above, some errors related to ID column still open.

func (s mssql) SupportLastInsertId() bool {
	return false
}

New results from go test
=========================
C:/Go/bin/go.exe test -v [C:/00_builds/go/src/github.com/jinzhu/gorm]
testing mssql...
=== RUN   TestRegisterCallback
--- PASS: TestRegisterCallback (0.00s)
=== RUN   TestRegisterCallbackWithOrder
--- PASS: TestRegisterCallbackWithOrder (0.00s)
=== RUN   TestRegisterCallbackWithComplexOrder
--- PASS: TestRegisterCallbackWithComplexOrder (0.00s)
=== RUN   TestReplaceCallback
[info] replacing callback `create` from C:/00_builds/go/src/github.com/jinzhu/gorm/callback_test.go:94
--- PASS: TestReplaceCallback (0.00s)
=== RUN   TestRemoveCallback
[info] removing callback `create` from C:/00_builds/go/src/github.com/jinzhu/gorm/callback_test.go:107
--- PASS: TestRemoveCallback (0.00s)
=== RUN   TestCloneSearch
--- PASS: TestCloneSearch (0.00s)
=== RUN   TestHasOneAndHasManyAssociation
--- FAIL: TestHasOneAndHasManyAssociation (0.04s)
	association_test.go:21: Got errors when save post: sql: no rows in result set
	association_test.go:25: Category should be saved: record not found
	association_test.go:32: Category Id should exist
	association_test.go:36: Comment 1 should be saved
	association_test.go:39: Comment Should have post id
	association_test.go:44: Comment 2 should be saved
	association_test.go:48: Comment 2 Should have post id
=== RUN   TestRelated
--- FAIL: TestRelated (0.02s)
	association_test.go:68: After user save, credit card should have id. User:{0 0 0 jinzhu 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC [{0 0 jinzhu@example.com 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC} {0 0 jinzhu-2@example@example.com 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC}] {0 Billing Address - Address 1   2015-09-06 15:11:07.7700671 -0400 EDT 2015-09-06 15:11:07.7700671 -0400 EDT 0001-01-01 00:00:00 +0000 UTC} {0 true} {0 Shipping Address - Address 1   0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC} 0 {0 1234567890 {0 false} 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC} 0 [] 0 {0 company1 <nil>} {} [] 0 [] {} <nil>}
	association_test.go:72: After user save, billing address should have id
	association_test.go:76: After user save, billing address should have id
	association_test.go:82: Should have two emails
	association_test.go:88: Should have two emails
	association_test.go:94: Should have only one email match related condition
	association_test.go:100: Should get billing address from user correctly
	association_test.go:106: Should get user from address correctly
exit status 2
FAIL	github.com/jinzhu/gorm	0.473s
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 117 [running]:
testing.tRunner.func1(0xc0820abef0)
	c:/go/src/testing/testing.go:450 +0x178
github.com/jinzhu/gorm_test.TestRelated(0xc0820abef0)
	C:/00_builds/go/src/github.com/jinzhu/gorm/association_test.go:110 +0x12ee
testing.tRunner(0xc0820abef0, 0xc65288)
	c:/go/src/testing/testing.go:456 +0x9f
created by testing.RunTests
	c:/go/src/testing/testing.go:561 +0x874

goroutine 1 [chan receive]:
testing.RunTests(0xa1fbf0, 0xc651e0, 0x62, 0x62, 0xc082120300)
	c:/go/src/testing/testing.go:562 +0x8b4
testing.(*M).Run(0xc0825fdee8, 0xc08200a200)
	c:/go/src/testing/testing.go:494 +0x77
main.main()
	github.com/jinzhu/gorm/_test/_testmain.go:254 +0x11d

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	c:/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 34 [chan receive]:
database/sql.(*DB).connectionOpener(0xc082071e00)
	c:/go/src/database/sql/sql.go:634 +0x4c
created by database/sql.Open
	c:/go/src/database/sql/sql.go:481 +0x33d
Error: process exited with code 1.
===============================

**Comment by jinzhu** [comment]
Hi @biju-kalissery

Thank you for your testing, and waiting for your PR.


Sorry, I don't have mssql installed, so can't test it.

**Comment by biju-kalissery** [comment]
I have committed the following changes in my version. I will submit a pull request shortly.

* Added method 'EnableIdentityInsert' to the Dialect interface and implemented it for mssql. This helps us to temporarily enable IDENTITY column inserts for specified table for MS SQL.

* Changed the index in auto-migration test table (BigEmail) from unique index to normal index. MS SQL does not allow multiple NULL values in a column with unique index.

* Skipped TestCreateWithNoGORMPrimayKey  in create_test.go for mssql dilect because MS SQL generates error if we check for identity value for tables that do not have Id column.

* Cleaned up error handling/reporting in various _test.go files to easily see the reason behind test failures. 
 

## Pending issue 1 
* The generated SQL for searching for  xxx IN ( yyy ) is not correct for MSSQL.  This causes SQL error like this:
```
An expression of non-boolean type specified in a context where a condition is expected, near ','
```

SQL generated by gorm now:
```
exec sp_executesql N'SELECT  * FROM "tags" INNER JOIN blog_tags ON blog_tags."tag_id" = "tags"."id" AND blog_tags."tag_locale" = "tags"."locale" WHERE (("blog_id","blog_locale") in ((@p1,@p2)))',N'@p1 bigint,@p2 nvarchar(2)',@p1=5,@p2=N'ZH'
```

MS SQL requires the SQL to do the following to avoid the error 
```
exec sp_executesql N'SELECT  * FROM "tags" INNER JOIN blog_tags ON blog_tags."tag_id" = "tags"."id" AND blog_tags."tag_locale" = "tags"."locale" WHERE ("blog_id" in (@p1)) OR ("blog_locale" in (@p2))',N'@p1 bigint,@p2 nvarchar(2)',@p1=5,@p2=N'ZH'
```

=== RUN   TestManyToManyWithMultiPrimaryKeys
--- FAIL: TestManyToManyWithMultiPrimaryKeys (0.10s)
	multi_primary_keys_test.go:49: Error while reading tags related to blog:mssql: An expression of non-boolean type specified in a context where a condition is expected, near ','.
	multi_primary_keys_test.go:54: should found 3 tags with blog, found:0

=== RUN   TestManyToManyPreloadWithMultiPrimaryKeys
--- FAIL: TestManyToManyPreloadWithMultiPrimaryKeys (0.04s)
	preload_test.go:663: Error in Preload:mssql: An expression of non-boolean type specified in a context where a condition is expected, near ','.

## Pending issue 2
The struct RecordWithSlice definition in slice_test.go needs review/refinement.  It looks like it is trying to save a binary slice into a text column.  

=== RUN   TestScannableSlices
[35m(mssql: Operand type clash: varbinary is incompatible with text)[0m 
[33m[2015-09-08 14:32:03][0m [31;1m [0m
--- FAIL: TestScannableSlices (0.03s)
	slice_test.go:23: Should save record with slice values:mssql: Operand type clash: varbinary is incompatible with text
	slice_test.go:29: Should fetch record with slice values:record not found
	slice_test.go:33: Should have serialised and deserialised a string array
	slice_test.go:37: Should have serialised and deserialised a struct array

**Comment by kiwih** [comment]
+1. I am also getting similar error messages with Azure SQL Database.
