### ISSUE TITLE
Is Gorm goroutine safe?

### ISSUE THREAD

**Issue by cnaize** [jinzhu/gorm#648]
Hello!
I'm using `gorm` with `postgres`.
I created global connection variable:
```go
var DB *gorm.DB
...
DB = ...
...
```
Then I'm trying to use `DB` inside of different `goroutine`:
```go
var user db.User
DB.First(&user)
```
And waiting.. and waiting..
It looks like `DB.First()` hangs on.
How to fix it?

**Comment by jinzhu** [comment]
Hi @cnaize 

Yes, it is.

Have you debugged why it hangs on? caused by gorm?
