### ISSUE TITLE
Adding Id field to existing struct during AutoMigrate doesn't work

### ISSUE THREAD

**Issue by ottokart** [jinzhu/gorm#649]
If I have the following struct...
type Client struct {
	FirstName	string `sql:"size:50"`
	LastName	string `sql:"size:50"`
}
... do an automigrate. Then notice that I have forgotten an Id field. Update the struct to...
type Client struct {
	Id			int64
	FirstName	string `sql:"size:50"`
	LastName	string `sql:"size:50"`
}
... and do another migrate. Then the following sql stetement is generated which produces an error:
ALTER TABLE `free_passes` ADD `id` bigint AUTO_INCREMENT;
Error 1075: Incorrect table definition; there can be only one auto column and it must be defined as a key

Seems that the generated sql statement should be this instead:
ALTER TABLE `free_passes` ADD `id` bigint AUTO_INCREMENT PRIMARY KEY;

**Comment by jinzhu** [comment]
Hi @ottokart 

Gorm doesn't assume you will miss the primary key of a table, so won't auto migrate primary keys.

Btw, you could use `gorm.Model` for the case, like this:

```go
type Client struct {
  gorm.Model
  FirstName string
}
```
