### ISSUE TITLE
Self referencing many2many relation

### ISSUE THREAD

**Issue by acristal** [jinzhu/gorm#653]
Hi guys,

I am stuck trying to make a self referencing many2many relationship with gorm.

I first tried the naive approach thinking that it should work:

``` go
type User struct {
    Id int64
    Contacts []User `gorm:"many2many:user_contacts;"`
}
```

But I get errors saying that the column `user_id` is duplicated.

I found a post saying that this:

``` go
type User struct {
    Id int64
    Contacts []User `gorm:"foreignkey:user_id;associationforeignkey:contact_id;many2many:user_contacts;"`
}
```

should work. However, it doesn't because it tries to create a join table with no column.
I believe it comes from a29230c86f0849b51bbb3c19b71f108fbb74541d, where you check that the foreign key fields exist with `toScope.FieldByName` in `model_struct.go`, so it is not possible to use a non-existent field in `foreignkey` and `associationforeignkey`.

I however found a way to bypass that by using a custom JoinTableHandler (following the example in `join_table_test.go`):
I use this struct:

``` go
type User struct {
    Id int64
    Contacts []User `gorm:"associationforeignkey:nonExistentField;many2many:user_contacts;"`
}
```

It works because the `associationForeignKey` doesn't exist, so it creates the join table `user_contacts` with the fields `user_id` and nothing else. Then, when migrating, it adds the `contact_id` column.

So in the end, I have my join table with the good columns, but I don't think this was the intended way to do it.
Am I doing something wrong?

Thanks a lot,

**Comment by aliksend** [comment]
it is actual for me too, so i'm waiting (and looking) for solution too

**Comment by DieselDraft** [comment]
same problem

**Comment by DieselDraft** [comment]
I implemented in next way and it work:

`func CreateBookInfo(bookInfo BookElement) {
	edition := NewEdition()

	edition.Title.String = bookInfo.Title
	edition.Title.Valid = true

	edition.Year.Int64 = int64(bookInfo.Year)
	edition.Year.Valid = true

	for _, a := range bookInfo.Author {

		author := Author{}
		author.Name = a.Name

		services.Con.FirstOrCreate(&author, author)

		edition.Authors = append(edition.Authors, author)
	}

	services.Con.Save(&edition)
}`

**Comment by NickNeedsAName** [comment]
+1 that this is super broken. 

WRT https://github.com/jinzhu/gorm/commit/a29230c86f0849b51bbb3c19b71f108fbb74541d it looks like this commit just COMPLETELY destroyed any hope of doing anything with many2many relations + setting association keys + foreign keys.

Any insight into what the new code is doing and why it's better than the old code would be nice? Maybe comments?  My main point of concern here is that it looks like with the new code literally nothing will ever work unless the names of things match up which seems like a meaningless safety check?


A nice note somewhere in the readme saying "many2many relations where anything more than a custom table is defined do not work" would also be cool.

**Comment by NickNeedsAName** [comment]
For those who come here after me, here is my workaround:

Assuming we have:
```
type model1 struct {
     stuff
}
type model2 struct {
     M1s []model1 `gorm:"many2many:<model1model2jointable>"`
}
```
And that the table model1model2jointable model is:
```
type m1m2join struct {
       PKey uint `gorm:"primary_key"` //NAMING THIS NOT 'ID' IS SUPER IMPT
       M1_ID model1
       M2_ID model2
}
```
then when you set up gorm and create tables//models//structs//stuff, you can put the following code in
```
relation := gorm.Relationship{}
relation.Kind = "many2many"
relation.ForeignFieldNames = []string{"id"} //(M1 pkey)
relation.ForeignDBNames = []string{"M1_ID"} //(M1 fkey in m1m2join)
relation.AssociationForeignFieldNames = []string{"id"} //(M2 pkey)
relation.AssociationForeignStructFieldNames = []string{"id", "ID"} //(m2 pkey name in m2 struct?)
relation.AssociationForeignDBNames = []string{"M2_ID"} //(m2 fkey in m1m2join) 
m1Type := reflect.TypeOf(model1{})
m2Type := reflect.TypeOf(model2{})
handler := gorm.JoinTableHandler{}
// ORDER BELOW MATTERS
// Install handler
db.SetJoinTableHandler(&M2{}, "M1s", &handler)
// Configure handler to use the relation that we've defined
handler.Setup(&relation, "m1m2join", m1Type, m2Type)
// Order matters because 'SetJoinTableHandler' calls handler.setup(rltn, etc.) with the 
// rltn that gorm inferred from the struct tags.  If we call setup before setjointablehandler
// all of our hard hacky work is clobbered :(
```

This replicates the behavior of what gorm tries to do while parsing struct tags.

THE JOIN TABLE MUST NOT SHARE ANY COLUMN NAMES WITH EITHER SOURCE OR DESTINATION TABLES.  gorm does some really lazy select * stuff, and then when scanning just puts things where they match.  So if you select * from join tables, and the join table has an column titled "id" you get "id ...<stuff>... id ...<more stuff>..." where the first id is the ID of the model you want, and the second ID is the id from the join table.  Gorm will scan + parse this as "okay, the model you want has the id from the column id....oooo a new id column! lets make the model id this new one!"

Hopefully this helps someone!

**Comment by cdevienne** [comment]
I attempt to use @NickNeedsAName workaround for a self-referencing relation without success. The dbnames are not taken into account when preloading, and it is unclear how the table is supposed to be created (nor what the m1m2join struct is for).

A "how to" for defining such a relation would be nice. I think it is a common need.

**Comment by NickNeedsAName** [comment]
I suspect something has changed in a recent update and my workaround no longer works :(

I also haven't used GORM in some time so I can't suggest an alternative.  Best of luck!

**Comment by MaxBlaushild** [comment]
Any movement on this? This still broken at the moment. Would like to not have to hack this type of relationship

**Comment by jinzhu** [comment]
duplicated with #1194
