### ISSUE TITLE
Pointer confusion

### ISSUE THREAD

**Issue by pedromorgan** [jinzhu/gorm#656]
Newbie... I feel that the gorm instance should be a pointer...??
Can someone advice as am creating gorm from an exisgin instance.. 
```go
var Dbg gorm.DB
// var Dbg *gorm.DB << expected ??

func SetupDb( engine string, db *sql.DB){
	var err error
	Dbg, err = gorm.Open(engine, db)

}
```

**Comment by jinzhu** [comment]
`gorm.Open("mysql", your_existing_instance)`

**Comment by pedromorgan** [comment]
UH?

`gorm.Open` returns 

```var Db gorm.DB```
not
```var Db *gorm.DB```
