### ISSUE TITLE
ISSUES: add labels

### ISSUE THREAD

**Issue by pedromorgan** [jinzhu/gorm#657]
Can we add labels to the issues,,

eg 
Bug, FeatureRequest, Driver, ORM, table, column, row, field, log, etc...

Eg like on revel  project.. https://github.com/revel/revel/issues

**Comment by jinzhu** [comment]
I don't really have time to do that. ;(

But it would be cool if someone could do.

**Comment by pedromorgan** [comment]
Well if u give me perms, Its quite easy to do...

**Comment by pedromorgan** [comment]
OK labels are..
```
#schema  #config #mysql  #postgres, #mssql, #sqlite #query #index #relation #callback #code 
docs request bug planned maybe question release
```

Am for example chcking automigrate.. 

Add me as a contrib or something so I can tag..

**Comment by jinzhu** [comment]
Hi @pedromorgan 

Just added you as contrib, thank you for your work.
