### ISSUE TITLE
pq: syntax error at or near "WHERE" When using Association() after commit 2fe185eb77a22a3dbdb42cebed976598162ec294

### ISSUE THREAD

**Issue by LiranCohen** [jinzhu/gorm#662]
On or before commit 2fe185eb77a22a3dbdb42cebed976598162ec294 everything (with some exceptions) seems to be working fine.  After that commit is where the "WHERE" clause breaks on Association().  I'll include some code to look at.

I'm not using AutoMigrate to create my tables as that was broken when I started using gorm.

if query := db.DBAccess.Model(c).Association("People").Find(&p); query.Error != nil {
    fmt.Println(query.Error)
    return errors.New("Could not retrieve people")
}

[2015-09-15 21:55:45]  [0.98ms]  SELECT  * FROM "people" INNER JOIN companies_people ON WHERE ("people".deleted_at IS NULL OR "people".deleted_at <= '0001-01-02') AND ((company_id in ('1')))
 

[2015-09-15 21:55:45]  pq: syntax error at or near "WHERE"
pq: syntax error at or near "WHERE"

**Comment by LiranCohen** [comment]
I've also tried this with AutoMigrate and get the same results.
It seems that the ON statement is missing some keys, were they defined/gathered differently in previous commits?

**Comment by LiranCohen** [comment]
I have figured this out.

In my structs I was using the AssociationForeignKey gorm struct tag to explicitly specify the foreign key on a many2many relationship.  Is this no longer supported? What is the correct way to explicitly state a foreign key?

**Comment by seriallink** [comment]
I have a similar error here using the tags *associationforeignkey* and *foreignkey*.

```
type Person struct {
  IdPerson string `gorm:"column:idPerson;primary_key:true"`
  ...
  Accounts []Account `gorm:"many2many:dw.PersonAccount;associationforeignkey:idAccount;foreignkey:idPerson"`
}
```
This code used to work just fine until recently.
```
db.Model(&person).Association("Accounts").Find(&accounts)
```
Now I'm getting the following error:

```Error 1054: Unknown column 'person_idPerson' in 'where clause'```

And the SQL generated by gorm:

```
SELECT  `dw`.`Account`.* FROM `dw`.`Account` INNER JOIN dw.PersonAccount ON dw.PersonAccount.`account_idAccount` = `dw`.`Account`.`idAccount` WHERE (person_idPerson in ('661448f9-6dfb-11e5-82f7-74e6e2cff675'))
```

**Comment by jinzhu** [comment]
The error should been fixed, added few test cases to ensure this

https://github.com/jinzhu/gorm/blob/master/customize_column_test.go#L67-L104

https://github.com/jinzhu/gorm/blob/master/multi_primary_keys_test.go#L10-L25
