### ISSUE TITLE
How to get email with username

### ISSUE THREAD

**Issue by clinyong** [jinzhu/gorm#663]
```go
type User struct {
    ID int64
    Name string
}
type Email struct {
   ID int64
   UID int64
   Content string
}
type EmailUser struct {
    Email
    Username string
}
```

User has many emails and each email belong to one user, the UID is the foreign key. How can I get every email with the username at the same time?

**Comment by galeone** [comment]
Are you looking for [Joins](https://github.com/jinzhu/gorm#joins)?

**Comment by GarrettSYHampton** [comment]
Something like this maybe?

db.Joins("left join users on users.id = emailusers.uid").Where("users.name = ?", "jinzhu").Find(&emailusers)

**Comment by jinzhu** [comment]
Yes, it should works with Joins.
