### ISSUE TITLE
Keep getting 1071 - Specified key was too long; max key length is 767 bytes with automigrate

### ISSUE THREAD

**Issue by danqing** [jinzhu/gorm#664]
I have the following fields in my struct:

```go
UUID     string `sql:"type:varchar(36);index"`
SomeID   int    `sql:"index"`
Category string `sql:"type:varchar(64);index"`
Variant  string `sql:"type:varchar(64);index"`
Version  string `sql:"type:varchar(32);index"`
```

and when I do `db.AutoMigrate()` I always get the 1071 error "Specified key was too long; max key length is 767 bytes". I am using `utf8mb4` so each char is 4 bytes, but even so this shouldn't have any issues...

I'm not sure what's gone wrong. Any insights would be appreciated.

Thanks!

**Comment by jinzhu** [comment]
Hi @danqing 

I think you didn't add the `type` at the beginning? so it is created with length 256 already. which caused raise error when create index.
