### ISSUE TITLE
Since when table ended with Data  not add "s"?

### ISSUE THREAD

**Issue by davyzhang** [jinzhu/gorm#665]
like 
type TestData struct {
	ID int
}

before I get table name "test_datas"

then I get "test_data"

Where can I find these code changes?

bunch of my program won't work because of this

**Comment by nkovacs** [comment]
Probably this: https://github.com/jinzhu/gorm/commit/05b3f036f8bbb96b22336bbe3510253879ac0ab1
Here's the rule: https://github.com/qor/inflection/blob/master/inflections.go#L41

**Comment by jinzhu** [comment]
Hi @davyzhang 

Sorry for the problem.

Yes, this issue should be introduced at that time, just copied rails's rules thought it might be good for people.

Maybe better you need to write a TableName method for `TestData` struct.
