### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by nkovacs** [jinzhu/gorm#667]
This is possibly the cause of #547 

```
WARNING: DATA RACE
Read by goroutine 7:
  runtime.mapaccess2()
      /tmp/workdir/go/src/runtime/hashmap.go:320 +0x0
  github.com/jinzhu/gorm.(*Scope).GetModelStruct()
      /home/nkovacs/progs/go/src/github.com/jinzhu/gorm/model_struct.go:94 +0x2f5
  github.com/jinzhu/gorm.(*Scope).PrimaryFields()
      /home/nkovacs/progs/go/src/github.com/jinzhu/gorm/scope.go:123 +0x99
  github.com/jinzhu/gorm.(*Scope).GetModelStruct.func1()
      /home/nkovacs/progs/go/src/github.com/jinzhu/gorm/model_struct.go:261 +0x29ca

Previous write by main goroutine:
  runtime.mapassign1()
      /tmp/workdir/go/src/runtime/hashmap.go:411 +0x0
  github.com/jinzhu/gorm.(*Scope).GetModelStruct()
      /home/nkovacs/progs/go/src/github.com/jinzhu/gorm/model_struct.go:372 +0x1037
  github.com/jinzhu/gorm.(*Scope).TableName()
      /home/nkovacs/progs/go/src/github.com/jinzhu/gorm/scope.go:282 +0x2f6
  github.com/jinzhu/gorm.(*Scope).QuotedTableName()
      /home/nkovacs/progs/go/src/github.com/jinzhu/gorm/scope.go:292 +0x1eb
  github.com/jinzhu/gorm.(*Scope).prepareQuerySql()
      /home/nkovacs/progs/go/src/github.com/jinzhu/gorm/scope_private.go:300 +0x342
  github.com/jinzhu/gorm.Query()
      /home/nkovacs/progs/go/src/github.com/jinzhu/gorm/callback_query.go:44 +0x979
  github.com/jinzhu/gorm.(*Scope).callCallbacks()
      /home/nkovacs/progs/go/src/github.com/jinzhu/gorm/scope_private.go:314 +0x95
  github.com/jinzhu/gorm.(*DB).Find()
      /home/nkovacs/progs/go/src/github.com/jinzhu/gorm/main.go:215 +0x10f
  main.main()
      /home/nkovacs/progs/go/src/gormtest/main.go:113 +0x360

Goroutine 7 (running) created at:
  github.com/jinzhu/gorm.(*Scope).GetModelStruct()
      /home/nkovacs/progs/go/src/github.com/jinzhu/gorm/model_struct.go:370 +0xfc1
  github.com/jinzhu/gorm.(*Scope).TableName()
      /home/nkovacs/progs/go/src/github.com/jinzhu/gorm/scope.go:282 +0x2f6
  github.com/jinzhu/gorm.(*Scope).QuotedTableName()
      /home/nkovacs/progs/go/src/github.com/jinzhu/gorm/scope.go:292 +0x1eb
  github.com/jinzhu/gorm.(*Scope).prepareQuerySql()
      /home/nkovacs/progs/go/src/github.com/jinzhu/gorm/scope_private.go:300 +0x342
  github.com/jinzhu/gorm.Query()
      /home/nkovacs/progs/go/src/github.com/jinzhu/gorm/callback_query.go:44 +0x979
  github.com/jinzhu/gorm.(*Scope).callCallbacks()
      /home/nkovacs/progs/go/src/github.com/jinzhu/gorm/scope_private.go:314 +0x95
  github.com/jinzhu/gorm.(*DB).Find()
      /home/nkovacs/progs/go/src/github.com/jinzhu/gorm/main.go:215 +0x10f
  main.main()
      /home/nkovacs/progs/go/src/gormtest/main.go:113 +0x360
==================
```

**Comment by nkovacs** [comment]
[This](https://github.com/nkovacs/gorm/tree/race-fix) fixes the race condition (go test -race passes, and I no longer get the "can't find field" errors). It's a mess though.
After introducing synchronization to the map and the ModelStructs, the problem became deadlocks, since it was possible to create circular dependencies.
So my solution was to split the model struct creation into two passes. After the first pass, the model struct is made available for internal use by other calls to GetModelStruct, but normal calls have to wait until the relations are resolved. Because GetModelStruct calls various methods of Scope that then again call GetModelStruct (causing the deadlocks), I had to add methods that instead accept a ModelStruct which doesn't have related fields yet (but these should not be necessary for those methods).
I used goroutines to defer functions to the second pass, so I wouldn't have to split the whole thing into two for cycles, and duplicate a bunch of code. This does make the code harder to understand though.

It's still possible to create a deadlock with this code: 

```go
type A struct {
	ID uint64
	*B
}

type B struct {
	BFoo string
	*A
}
```

Of course this doesn't make sense and wouldn't work with gorm (Automigrate fails with "duplicate column 'id'"), so there probably needs to be a check against this.

**Comment by jinzhu** [comment]
Hi @nkovacs 

Thank you for your report, this should been fixed.

**Comment by nkovacs** [comment]
It's not fully fixed. Only the map is protected, the ModelStructs inside it are not. If you do two concurrent Finds for example, you'll get a data race warning.

**Comment by nkovacs** [comment]
Your recent refactoring fixed the race condition with the concurrent Finds. Thanks
