### ISSUE TITLE
I cannot seem to set an offset

### ISSUE THREAD

**Issue by marksalpeter** [jinzhu/gorm#671]
this is the exact line I'm using 
db.Order(meta.OrderBy()).Offset(meta.Offset).Limit(meta.Limit).Where("business_id = ?", manager.BusinessId).Find(&newsletters).Count(&meta.Total)

All of the params in meta are within the bounds of the collection I'm querying, but, I keep getting "(sql: no rows in result set) " whenever i set the offset. Any ideas?

--- update. I found the debug mode docs. it failing on count 
SELECT  count(*) FROM `newsletter`  WHERE (`newsletter`.deleted_at IS NULL OR `newsletter`.deleted_at <= '0001-01-02') AND ((business_id = '0')) LIMIT 3 OFFSET 2
isn't returning a number. it should return three

**Comment by jinzhu** [comment]
I think there will be no issue for the Count, if you still get any problem, follow https://github.com/jinzhu/gorm/blob/master/CONTRIBUTING.md to submit a runnable script.

Thank you.
