### ISSUE TITLE
DB Panel

### ISSUE THREAD

**Issue by pedromorgan** [jinzhu/gorm#675]
Thinking about creating a control panel..

So one can query the database structure, table names and configuration
of a running instance.. and connection..

Kinda like a mini "myphpadmin".. just to query tables and structs etc

**Comment by DSchalla** [comment]
While I like the idea, I think that is unrelated to gorm. Is there any justification why I should load that stuff into a production project? The idea itself is great, but as user I wouldn't like that gorm would get bloated like that.

**Comment by jinzhu** [comment]
Might be good to checkout another project I am working on

Refer:
github.com/qor/qor
getqor.com
