### ISSUE TITLE
Question about how gorm handles NULL

### ISSUE THREAD

**Issue by qimingweng** [jinzhu/gorm#678]
I see that when I have a pointer type on a struct, and I update it, gorm generates this SQL:

```sql
UPDATE "object" SET "nullable_column" = '<nil>'  WHERE ("id" = '5BdF4x')
```

The `.Error` property of the `gorm` call is nil, so nothing happens, and I think this updates.

I think somewhere this updates the column with NULL (if the column is nullable), but just wanted to confirm this feature or find this better documented somewhere.

Does `gorm` transform the above SQL to a different actual SQL that's sent to Postgres? Running the exact SQL doesn't work.

**Comment by jinzhu** [comment]
Hi @qimingweng 

The above SQL is formatted by logger https://github.com/jinzhu/gorm/blob/master/logger.go, it is not the exactly SQL passed to Postgres, arguments are handled by database adaptor.

**Comment by qimingweng** [comment]
@jinzhu Is it possible to be pointed to the parts of the code handle this? I'd like to get a better understanding of the inner workings and contribute perhaps to the documentation
