### ISSUE TITLE
Bug with Order() for some queries

### ISSUE THREAD

**Issue by nikbyte** [jinzhu/gorm#679]
In function orderSql() in scope_private.go you have code:
if len(scope.Search.orders) == 0 || scope.Search.countingQuery {
    return ""
}

I cannot understand why .Order() for my query didn't work.
I've found these code in selectSql():
scope.Search.countingQuery = hasCountRegexp.MatchString(sql)

So, regexp
var hasCountRegexp = regexp.MustCompile(`(?i)count(.+)`)
is wrong for queries like

SELECT account FROM table;

Please, change it little bit to match only count(*). For example:

-var hasCountRegexp = regexp.MustCompile(`(?i)count(.+)`)
+var hasCountRegexp = regexp.MustCompile(`(?i)count\((.+)`)

The bug: I cannot apply Order() method to query like SELECT account FROM table.

**Comment by charleshimmer** [comment]
That regex check for count is general is a problem.  I have several cases where I need to do a sub select query which contains a count and the main query needs an `order by` clause.  For example:
```sql
select id, name, (select count(*) from tableB where id = 2) as bCount order by bCount desc;
```
This is not possible with gorm without a lot of hacks. I think trying to check if the query is a count and then possibly saving the user from accidentally using an order by clause with a count shouldn't be the ORM's concern.  That's on the developer.
