### ISSUE TITLE
Many2Many Associate Append updates the newly appended object

### ISSUE THREAD

**Issue by MalteJ** [jinzhu/gorm#683]
I have a many2many relation between `User` and `Device`.

    type User struct {
        Meta
        Devices      []Device `gorm:"many2many:user_devices"`
    }
    
    type Device struct {
        Meta
        Users        []User `gorm:"many2many:user_devices"`
    }
    

When I do

    Db.Model(&device).Association("Users").Append(user)

the relation is saved in the join table AND the `user` gets updated in the database.
Imho the user should not get modified. The only thing I want is to create an entry in the join table.

Am I doing something wrong or is this a bug?

Thanks!
Malte

**Comment by ptman** [comment]
I agree. Or preferably it would be possible to choose UpdatedAt is touched or not.

**Comment by jinzhu** [comment]
Use won't be update now if it has primary key, if doesn't have it, will insert the user first, then create a record in the join table.
