### ISSUE TITLE
Qualified table name support

### ISSUE THREAD

**Issue by tarqe39** [jinzhu/gorm#684]
I was wondering would it make sense to support specifying schema (qualified table name) while querying?
For example I have a PostgresDb with schema created for every user (multi tenancy), and I don't see any simple way for querying using qualified table name or querying across schemas. The same goes for MySql and querying across databases.

**Comment by seriallink** [comment]
I solved this problem this way:

```
type Person struct {
  ...
}

func (this *Person) TableName() string {
    return "dw.Person"
}
```

Although I'd prefer to have something like that:

```
func (this *Person) SchemaName() string {
    return "dw"
}
```

**Comment by tarqe39** [comment]
TableName method might work fine to dynamicaly create schema suffix. I will try that

**Comment by jinzhu** [comment]
Yes, you could use TableName, or like `db.Table("tx.users").Find(&user)`
