### ISSUE TITLE
Enum value in database

### ISSUE THREAD

**Issue by aliksend** [jinzhu/gorm#686]
Hello everybody
I wanna store smth like enums in my database
I follow [this](http://stackoverflow.com/questions/24264485/saving-enumerated-values-to-a-database), and all is good when I use `First`. But when I use `Find` I have this error:
```
Panic recovery -> interface conversion: interface is []uint8, not int64
/usr/local/Cellar/go/1.5/libexec/src/runtime/panic.go:423 (0x2a249)
        gopanic: reflectcall(nil, unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/usr/local/Cellar/go/1.5/libexec/src/runtime/iface.go:221 (0xd9b0)
        assertE2T: panic(&TypeAssertionError{"", *ep._type._string, *t._string, ""})
/Users/admin/gopath/src/gin_server/backend/model/item.go:63 (0x10431a)
        (*MyType).Scan: *t = MyType(value.(int64))
/usr/local/Cellar/go/1.5/libexec/src/database/sql/convert.go:190 (0x3675a1)
        convertAssign: return scanner.Scan(src)
/usr/local/Cellar/go/1.5/libexec/src/database/sql/convert.go:218 (0x368834)
        convertAssign: return convertAssign(dv.Interface(), src)
/usr/local/Cellar/go/1.5/libexec/src/database/sql/sql.go:1692 (0x374e0a)
        (*Rows).Scan: err := convertAssign(dest[i], sv)
/Users/admin/gopath/src/github.com/jinzhu/gorm/callback_query.go:82 (0x1e6782)
        Query: scope.Err(rows.Scan(values...))
/Users/admin/gopath/src/github.com/jinzhu/gorm/scope_private.go:314 (0x212298)
        (*Scope).callCallbacks: (*f)(scope)
/Users/admin/gopath/src/github.com/jinzhu/gorm/main.go:215 (0x1f6ef3)
        (*DB).Find: return s.clone().NewScope(out).inlineCondition(where...).callCallbacks(s.parent.callback.queries).db
/Users/admin/gopath/src/gin_server/backend/api/items.go:65 (0x2cd35e)
        (*MyResourse).readAll: err = db.Limit(itemsOnPage).Offset((page - 1) * itemsOnPage).Find(&item).Error
==== and stack trace of other my code there ====
```
And when I putting this
```go
log.Printf("Scan() type with %v <%T>", value, value)
```
to my `Scan` method I have this output 
```
Scan() type with [48] <[]uint8>
```
with same error. But when I call `select` method on my db I can see that value is actually equal 0.

And one question more. With gorm I can store `int`s fields in database (I use MySQL), but using enums I can just use [this types](https://golang.org/pkg/database/sql/#Scanner) (and go's `int64` type represents as `bigint(20)` in database instead of `int(11)` for `int`). Can I use `int(11)` for this field too?
Thank you for your attention

**Comment by aliksend** [comment]
Ok. Looking [there](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/ASCII-Table-wide.svg/2000px-ASCII-Table-wide.svg.png) I can say that it returned me a string with one symbol – zero.
But why string? Why encoded (or not decoded) – it has `[]utf8` type?
And I know that I can write code that checks type and if it is `[]utf8` than decode into string, convert to int and have profit, but it is crutch not solution, am I right?

**Comment by jinzhu** [comment]
Hi @aliksend 

database will pass `[]byte` to the scaner when query data from it, so I think you have to check it in your scanner.

For the second question, you could use size in field's tag. refer: https://github.com/jinzhu/gorm#define-models-structs

**Comment by qshuai** [comment]
Please mysql usage: [https://github.com/jinzhu/gorm/issues/1978#issuecomment-421919405](https://github.com/jinzhu/gorm/issues/1978#issuecomment-421919405)
