### ISSUE TITLE
How to trace the gorm's activity for better visibility?

### ISSUE THREAD

**Issue by kurtzhong** [jinzhu/gorm#690]
Hi, 
Thanks for the awesome project, i used to use gorp, and recently turn to gorm for the more friendly developer interface really helps. One way I liked gorp a lot is you could see every action it performs, especially thos transaction begin/rollback events, is there any easy way to accomplish this?

**Comment by pedromorgan** [comment]
You want to see sql queries then
```go
db.LogMode(true)
```

**Comment by kurtzhong** [comment]
This method did help, but seems I need to modify the `database/sql` package to see more output. Thanks.
