### ISSUE TITLE
UpdateColumn doesn't update UpdatedAt

### ISSUE THREAD

**Issue by aspcartman** [jinzhu/gorm#692]
`callback_update.go` contains this if 
```go
func UpdateTimeStampWhenUpdate(scope *Scope) {
	if _, ok := scope.Get("gorm:update_column"); !ok {
		scope.SetColumn("UpdatedAt", NowFunc())
	}
}
```
and in tests that's an expected behaviour. Ok. How then can I update only what have changed\what I want plust UpdatedAt timestamp? Call to `Update()` makes a huge update with all columns and relationships I didn't change. 

If that's an expected behaviour and there is no other way to selectively update, seems forking the whole gorm and removing this line is the only solution for me personally. Have no clue how to do oop override in go(

**Comment by aspcartman** [comment]
Well, eventually removing this if doesn't help the issue and gorm is very untrivial project to find why doesn't it help. Any suggestions?

**Comment by pedromorgan** [comment]
To override..
- Create a branch, and make it work..
- Then create a fork at github
- and add remote, push and put in a pull request.. ;-)

**Comment by aspcartman** [comment]
@pedromorgan Thx for suggestion, but it's know how to use git :) I'm strugling at how to make it work as I want it to work. 

And I'm sure, by looking at test suite, this behaviour of UpdateColumns is rather unwanted.

Well, I guess I'll just insert a dirty hack to callbak_update.go:38 
```go
func Update(scope *Scope) {
	if !scope.HasError() {
		var sqls []string

		if updateAttrs, ok := scope.InstanceGet("gorm:update_attrs"); ok {
			aMap := updateAttrs.(map[string]interface{})
			if _, exist := aMap["updated_at"]; exist == false {
				aMap["updated_at"] = NowFunc()
			}
			for key, value := range aMap {
				if scope.changeableDBColumn(key) {
					sqls = append(sqls, fmt.Sprintf("%v = %v", scope.Quote(key), scope.AddToVars(value)))
				}
			}
....
```

**Comment by pedromorgan** [comment]
So its a #pull `dirty hack` .. love foss ;-)

Buts is a Timestamp problem right ?

**Comment by jinzhu** [comment]
Hi @aspcartman 

UpdateColumn designed to don't update updated_at, if you want, you could include `updated_at` in the map or struct.
