### ISSUE TITLE
database table's field is case sensitive

### ISSUE THREAD

**Issue by qiuchengw** [jinzhu/gorm#694]
accurately, the table field must be lower case. 

say:
```
sql:
tb_mytable{    
     TAG_NAME  varchar(50),
}

golang:
type TbMytable struct {
      TagName string,
}

```
will not work.  unless use the tag 
```
  TagName string  "gorm:column:TAG_NAME"
```

why not support Case Insensitivity filed name by default? It will be convenient and reasonable.

**Comment by jinzhu** [comment]
@qiuchengw this will be tricky issues if do so.

**Comment by yhjhoo** [comment]
Hmmm, wondering why is this closed
