### ISSUE TITLE
One-To-Many / Has-Many inserting not working depending on order of struct fields

### ISSUE THREAD

**Issue by Teelevision** [jinzhu/gorm#698]
Calling `CreateDummyNodes()` in the following example is only inserting the top `Node`, but not its children:
```go
package foobar
import (
    "github.com/jinzhu/gorm"
)

type Node struct {
    ID uint
    Name string
    Children []Node
    NodeID uint `sql:"index"`
}

func CreateDummyNodes(db *gorm.DB) {

    group := &Node{
        Name: "Node A",
        Children: []Node{
            {
                Name: "Node A.1",
            },
            {
                Name: "Node A.2",
            },
        },
    }
    db.Create(group)

}
```

However, if I swap the positions of the fields `Children` and `NodeID`, it works:
```go
type Node struct {
    ID uint
    Name string
    NodeID uint `sql:"index"`
    Children []Node
}
```

Create inserts all three nodes into the table.

This does not affect the creating of tables (via auto migration). Both versions will create a valid table structure.

**Comment by jinzhu** [comment]
HI @Teelevision 

Thank you for your report, this should been fixed.
