### ISSUE TITLE
Getting a panic when trying to use one to many association

### ISSUE THREAD

**Issue by marksalpeter** [jinzhu/gorm#701]
I get the following error message when I add a one to many slice into one of my structs. Note: It appears not to matter wether or not the second table is created, as long as I set my struct up with a slice.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x1549c7]

goroutine 7 [running]:
github.com/jinzhu/gorm.(*Scope).GetModelStruct.func1(0xc8201c1300, 0xb, 0x10, 0xc8201c1200, 0x7a70a8, 0x455b00, 0xc8201e6540, 0xc8201e65a0)
	/Users/Mark/Sites/Server/src/github.com/jinzhu/gorm/model_struct.go:280 +0x1fb7
created by github.com/jinzhu/gorm.(*Scope).GetModelStruct
	/Users/Mark/Sites/Server/src/github.com/jinzhu/gorm/model_struct.go:388 +0xc80
```
Any ideas what might be going on

**Comment by marksalpeter** [comment]
So I'm trying to trace this thing. It seems like the problem is in scope.go at  line 126 of  `func (scope *Scope) PrimaryFields() []*Field  `.

`field.DBName` is "id", but there doesn't seem to be an "id" key in `scope.Fields()`
so its appending a `nil` pointer to the `[]*Fields` array it returns. Eventually this get used in a context where you try to append field.Name to, I'm assuming, the foreign key or something like that.

I'm still at a loss though. I'm not as familiar with the inner workings of this library as @jinzhu is. It would be really helpful if he, or someone else from the core team could assist. Thanks

**Comment by marksalpeter** [comment]
I figured out what the issue is. 
creating this table panics:
```go
type Email struct {	
	Views		[]View			`json:";omitempty"`
	Id			uint			`gorm:"primary_key"`
}
```

creating this table is fine:
```go
type Email struct {	
	Id			uint			`gorm:"primary_key"`
	Views		[]View			`json:";omitempty"`
}
```

It looks like you must be iterating over the keys in the order in which they appear and theres a problem if the primary key doesn't get added before a slice with a foreign key that points to it.

**Comment by rcmgleite** [comment]
+1

**Comment by jinzhu** [comment]
Hi @marksalpeter 

Thank you for your report, this issue should been fixed.
