### ISSUE TITLE
One to One Relatoin Not working , Shows Empty Data

### ISSUE THREAD

**Issue by sh0umik** [jinzhu/gorm#702]
```
type User struct {
	Id       int64
	Username string
	Email    string
	Profile  Profile
}

type Profile struct {
	Id        int64
	UserID    int64 `sql:"index"`
	Firstname string
	Lastname  string
}

func GetUsers(c *gin.Context) {

	var users []User
	var profile []Profile
	db.Select("id, username, email").Find(&users)

	db.Model(&profile).Related(&users)

	c.JSON(200, users)

}
```
It shows the Users table data but the Profile is empty . I have tried all combinations Has One , Belongs To .. I am not able to get any results . What am i doing wrong ?

**Comment by azer** [comment]
I'm having the same issue. gorm runs only one insert query when we save the user, profile doesn't get saved

**Comment by jinzhu** [comment]
the `profile` should be an struct, but not slice. and it needs to have primary key value.

**Comment by sh0umik** [comment]
making `profile` a struct does not solve the problem i am getting empty result sets
