### ISSUE TITLE
Preload many-to-many somehow using the id of the pivot table

### ISSUE THREAD

**Issue by faeronsayn** [jinzhu/gorm#703]
So I have users and groups with a many-to-many relationship.

`db.Preload("Groups").First(&user, 1)`

and do `user.Groups` the ids of the groups are weirdly not the ids i'm seeing in the database. Instead, they are the primary key ids of the `group_users` table records. (The relationship record ids). Which is extremely odd.

I'm assuming there is some weird stuff going on in the preload `many-to-many` relationship code.

**Comment by taoh** [comment]
Hit this too. The workaround is avoiding using id as PK for join tables.

**Comment by jinzhu** [comment]
Hi @faeronsayn 

This issue should been fixed, thank you for your report.
