### ISSUE TITLE
Changing Join Table Columns For `many2many` Join

### ISSUE THREAD

**Issue by blaskovicz** [jinzhu/gorm#707]
Right now, I'm trying to wrap an existing schema via structs with gorm.

In one of my cases, I'm doing a `many2many` join from an `AuthUser` table to a `ReviewsGroup` table, but the join table, `reviews_group_users` uses `group_id` and `user_id` as the foreign keys, rather than the default key gorm generates, `reviews_group_id` and `auth_user_id`, respectively. Is there a way to specify the column name overrides on the join?

I tried `gorm:"foreignkey:group_id;associationforeignkey:user_id;many2many:reviews_group_users"` but it generates some an erroneous, empty `JOIN .. ON ..` query.

_StackOverflow [Question](http://stackoverflow.com/questions/33437453/using-different-join-table-columns-than-defaults-with-gorm-many2many-join)_
_Related Questions About Struct Tags_: #608 | #362

**Comment by ezeql** [comment]
+1. I got stuck into this too before.

**Comment by ready4god2513** [comment]
Anything on this?  Can't get it figured out either.

**Comment by jinzhu** [comment]
```go
// Gorm will parse the model and keep all relationship related information into a Relationship struct.
// Suppose you have below structs defined
type User struct {
	gorm.Model
	Groups []Group `gorm:"many2many:user_groups"`
}

type Group struct {
	gorm.Model
}

// default foreign keys for User is `id`
// default foreign keys for join_table `user_groups` is `user_id`, `group_id`
// default foreign keys for Group is `id`

// Then relationship's value would be:
type Relationship struct { // https://github.com/jinzhu/gorm/blob/master/model_struct.go#L89-L98
       ...
  ForeignFieldNames            // => []string{"id"}
	ForeignDBNames               // => []string{"user_id"}
	AssociationForeignFieldNames // => []string{"id"}
	AssociationForeignDBNames    // => []string{"group_id"}
}

// You could access the relationship's value with
for _, field := range db.NewScope(&User).GetStructFields() {
   if field.Name == "Groups" {
      field.Relationship // struct contains foreign keys informations
   }
}

// If you want to use `uid`, `gid` as the foreign keys for join table, you could change the Relationship's value accordingly
relationship.ForeignDBNames = []string{"uid"}
relationship.AssociationForeignDBNames = []string{"gid"}

// PS1: Make sure those code run before migrations
// PS2: Not suggesting people do it like this, might be better to migrate your database if possible
```

**Comment by hit9** [comment]
Seems not working..

**Comment by vpol** [comment]
And using it seems to be very difficult in real life. Tag fields would be preferred to define association table fk's.

**Comment by Azuka** [comment]
Also facing this issue and it looks like the underlying api has changed.

**Comment by schmurfy** [comment]
I too was hit by this, if I don't specify the foreignkey and associationforeign, the query uses the wrong column name it generated but as soon as I specify one or both it produces an invalid query and the name I gave do not even appear in the requlting query (I use debug mode to see the queries), if this really has not been working since 2015 maybe just removing the option to specify the columns is better and adding a note in the documentation which falsly claims it works...

If it does work, any real working example would be greatly appreaciated.

**Comment by Azuka** [comment]
@schmurfy see #1565 . I'm manually inserting those changes until I find a way to fix.
