### ISSUE TITLE
reflect: Len of non-array type

### ISSUE THREAD

**Issue by jw-00000** [jinzhu/gorm#710]
When auto-migrating, I now get the error "reflect: Len of non-array type".

Stack trace (abridged):

    goroutine 149 [running]: 
    reflect.(*rtype).Len(0x7b9c20, 0xc8202bc300) 
        /usr/local/go/src/reflect/type.go:652 +0x7b 
    my-app/vendor/github.com/jinzhu/gorm.isUUID(0x7b9c20, 0xc8202bc300, 0xd7, 0x1) 
        ~/go/src/my-app/vendor/github.com/jinzhu/gorm/postgres.go:73 +0x5a 
    my-app/vendor/github.com/jinzhu/gorm.postgres.SqlTag(0x7b9c20, 0xc8202bc300, 0xd7, 0xff, 0xc82022b100, 0x0, 0x0) 
        ~/go/src/my-app/vendor/github.com/jinzhu/gorm/postgres.go:57 +0x15c 
    my-app/vendor/github.com/jinzhu/gorm.(*postgres).SqlTag(0xc88e68, 0x7b9c20, 0xc8202bc300, 0xd7, 0xff, 0x0, 0x0, 0x0) 
        <autogenerated>:54 +0xca 
    my-app/vendor/github.com/jinzhu/gorm.(*Scope).generateSqlTag(0xc820138980, 0xc820056410, 0x0, 0x0) 
        ~/go/src/my-app/vendor/github.com/jinzhu/gorm/model_struct.go:443 +0x64d 
    my-app/vendor/github.com/jinzhu/gorm.(*Scope).createTable(0xc820138980, 0xc820138980) 
        ~/go/src/my-app/vendor/github.com/jinzhu/gorm/scope_private.go:523 +0x114 
    my-app/vendor/github.com/jinzhu/gorm.(*Scope).autoMigrate(0xc820138980, 0xc820138980) 
        ~/go/src/my-app/vendor/github.com/jinzhu/gorm/scope_private.go:606 +0x103 
    my-app/vendor/github.com/jinzhu/gorm.(*DB).AutoMigrate(0xc8201f8460, 0xc82022b7d8, 0x6, 0x6, 0xc81fff3c4f) 
        ~/go/src/my-app/vendor/github.com/jinzhu/gorm/main.go:411 +0xc7 
    my-app/db.Init(0xc8201f8460) 
        ~/go/src/my-app/db/init.go:28 +0x310 

I think this error was introduced in commits 3cb95264dff572434ed72977d78f16ab4fe1dc83 and/or 92f9584c837c28c80bc164f319afb1b442d06750. It happens on the check `value.Type().Len()` (line 73 of postgres.go), which tries to get the Len of a non-array type.

**Comment by jinzhu** [comment]
Sorry for the problem, this should be fixed

**Comment by jswalens** [comment]
Thanks!
