### ISSUE TITLE
Panic when initializing the application

### ISSUE THREAD

**Issue by euller88** [jinzhu/gorm#714]
Hi, I'm a newbie with golang, and I know almost nothing about gorm, only the basics. Recently I was working with utron, and an error happened when I tried to run an application, that make it crashes right after starting. Following the error stack, I've discovered that the panic happened in the clone function, and I still don't know how to fix it. Here is the output that shows when i try to start the application:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5a5ef8]

goroutine 1 [running]:
github.com/jinzhu/gorm.(*DB).clone(0x0, 0xc8200a6f00)
	/opt/dev/src/github.com/jinzhu/gorm/main_private.go:6 +0x3a8
github.com/jinzhu/gorm.(*DB).AutoMigrate(0x0, 0xc82009bd80, 0x1, 0x1, 0xc8200a6f00)
	/opt/dev/src/github.com/jinzhu/gorm/main.go:409 +0x25
github.com/gernest/utron.(*Model).AutoMigrateAll(0xc82013faa0)
	/opt/dev/src/github.com/gernest/utron/models.go:83 +0x164
github.com/gernest/utron.Migrate()
	/opt/dev/src/github.com/gernest/utron/utron.go:232 +0x27
github.com/gernest/utron.Run()
	/opt/dev/src/github.com/gernest/utron/utron.go:239 +0x24
main.main()
	/opt/dev/src/naraka/main.go:11 +0x14

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
exit status 2

**Comment by pedromorgan** [comment]
This dont smell like a gorm issue to me.. so closing. .But re-open if a problem
