### ISSUE TITLE
Silencing errors in preloads

### ISSUE THREAD

**Issue by aspcartman** [jinzhu/gorm#715]
```go
err := db.Preload("SomeOtherThing").Find(&something, ...).Error
```
If there is no something found, there will still be a query executed (why?) for SomeOtherThing, which will contain `some_other_thing.id in ()` which will raise a syntax error, and is visible in log. But `err == nil`, which is not expected.

1. Unexpected useless queries
2. Loosing an error somewhere

**Comment by jinzhu** [comment]
This issue should been fixed for a while, thank you for your report.
