### ISSUE TITLE
Fix Gorm Tests (Incorrect Package)

### ISSUE THREAD

**Issue by dabfleming** [jinzhu/gorm#716]
From the [documentation on testing](https://golang.org/pkg/testing/)
> To write a new test suite, create a file whose name ends _test.go that contains the TestXxx functions as described here. Put the file in the same package as the one being tested.

Gorm's test files should all be in the `gorm` package, not the `gorm_test` package. Additionally, because some of the test files import `"github.com/jinzhu/gorm"` a contributor working in their fork of gorm is not running all test code against their fork.

### Example

- Create `$GOPATH/src/github.com/username/gorm/` and clone/checkout 67f88d9 (current master as of this writing).
- In `$GOPATH/src/github.com/jinzhu/gorm` checkout 5f113dc
- `GORM_DIALECT=postgres go test github.com/username/gorm` will succeed.
- In `$GOPATH/src/github.com/jinzhu/gorm` checkout 67f88d9
- `GORM_DIALECT=postgres go test github.com/username/gorm` will fail.

This has allowed the addition of bugs (see below) which don't break tests initially, but do after they have been merged.

### TODO

- All files should be in package `gorm`
- None should import `"github.com/jinzhu/gorm"`, all references to gorm should be to the current package.

ie. Make the changes proposed in PR #144. I understand your objection there, however note that dependencies that are only in test files are not needed to build the project, only to test it, and are only fetched when using the `-t` flag with go get.

I would be happy to supply PR if you'd like.

### References

This issue is the root cause of the confusion in #140. It allowed the introduction of #710 (Note that `GORM_DIALECT=postgres go test github.com/jinzhu/gorm` fails in panic on current master, 67f88d9). If the tests ran properly, the current panic would have been caught and #709 would have been added before merging #708

**Comment by pedromorgan** [comment]
What is still burning in my HEAD is a GORM guide, but thereagain, I back out cos its a brainfuck..

**Comment by pedromorgan** [comment]
Its something like..for a php programmer...

Once upon a time, a database had all different engines.. like kitchens..
and the master check said, lets create a Menu..
and all of the servers..

**Comment by mark-adams** [comment]
It's probably also worth pointing out here that using a "gorm_test" package is also acceptable:

> Test files that declare a package with the suffix "_test" will be compiled as a
separate package, and then linked and run with the main test binary.

**Comment by jinzhu** [comment]
I already know go won't import dependencies in `*test.go` files with go build, but still thinking `gorm_test` is fine, as:

* You solution won't solve problems for those packages having sub packages, so I think the problem using a wrong workflow, you should clone your fork into the `$GOPATH/src/github.com/jinzhu/gorm`, and make modifies there.
* There are pretty much tests for now, around 60% codes are tests, I am thinking move them into a sub package to make them better organized, just need some time to rewrite those tests.

Thank you for your suggestion anyway.
