### ISSUE TITLE
Associations (incorrectly) assume that saving new values cannot fail.

### ISSUE THREAD

**Issue by rburchell** [jinzhu/gorm#718]
Let's assume there are two structs:

Companion:
  name (unique_index constraint)

Cats
  name (unique_index constraint)

A Companion can have many Cats, a cat can have many Companions. But we cannot have a Companion or a Cat with the same name.

Given this setup, the code:

	db.Model(&User).Association("Cats").Append(Cat{Name: "Tom"})
	db.Model(&User).Association("Cats").Append(Cat{Name: "Tom"})

Will cause an invalid row to be inserted into the association table.

I'm new to the codebase, but I assume the problem lies here (func (association *Association) Append):

		if scope.New(value).PrimaryKeyZero() {
			scope.NewDB().Save(value)
		}

^ ... where the save is not correctly tested for the unique constraint (or other) failure.

**Comment by rburchell** [comment]
(I think this problem is actually worse than the situation I describe, because of course, the save can probably fail for other reasons. But that's the one I noticed, and probably the easiest to reproduce.)

**Comment by jinzhu** [comment]
Hi @rburchell 

Thank you for your report, this issue should been fixed.
