### ISSUE TITLE
FirstOrCreate function on postgresql uuid type fields

### ISSUE THREAD

**Issue by davyzhang** [jinzhu/gorm#722]
```
type Role struct {
	AppUserUid string `sql:"type:UUID";"index"` 


	CreatedAt time.Time
	UpdatedAt time.Time
	ID        int
}
```

if I use

```db.FirstOrCreate(&gamePlayer, &Role{AppId: app.ID, AccountId: player.ID})```

when there's a new record, the pq will complain a about "" is not a valid uuid

I guess gorm not auto generate a valid uuid here

Is that practical to detect uuid field of pg and auto generate uuid using the the internal UUID or just fake one to pass the check?

**Comment by jinzhu** [comment]
@davyzhang gorm not going to auto generate any value, if you want auto generate it, need to set a default value for the field. refer: https://github.com/jinzhu/gorm/issues/320

**Comment by talpa** [comment]
That is not all, you need extension for postgres and autogenerate uuid function
