### ISSUE TITLE
Fancy way to run arbitrary SQL and get result data in generic format? (ie: []map[string]interface{})

### ISSUE THREAD

**Issue by twitchyliquid64** [jinzhu/gorm#724]
Hi,

I wish to implement a maintenance panel in my application, to allow any admin to run SQL and get the results which will be rendered to HTML.

I cannot see any way to run random SQL *AND* get the data back in some generic format. Is this possible?

Also, getting a list of tables and list of columns would be nice.

Cheers for any suggestions,
Tom

**Comment by jinzhu** [comment]
You might want to checkout qor https://github.com/qor/qor

Here is the demo: http://demo.getqor.com/admin

Btw, gorm doesn't support get data back in generic format, it might be support in the future.  https://github.com/jinzhu/gorm/issues/143#issuecomment-156886936
