### ISSUE TITLE
Error handling is poorly documented

### ISSUE THREAD

**Issue by azer** [jinzhu/gorm#728]
We can see there is only one example with error handling. I think the README should lead users to handle errors for each query by having error handling in all (at least, more than one) examples.

**Comment by jinzhu** [comment]
Should the README full of error handing to double its size? ;)

Gorm's README is only for showing gorm's features to people, not teaching people write idiomatic code, but golang's doc should do that.

**Comment by azer** [comment]
gorm handles errors differently than idiomatic golang, that's why you should document it more. Current documentation looks like there ll be never errors. if query fails, it might be handled, or may be not.

**Comment by eenblam** [comment]
@jinzhu Would you be open to a PR explaining that GORM errors are driver-dependent, and that you'll need to do something [like this](https://stackoverflow.com/a/41666013/2074215) to handle errors for your driver?

**Comment by azer** [comment]
@eenblam I ended up creating an alternative library [crud](https://github.com/azer/crud)
