### ISSUE TITLE
Update fields having a default value

### ISSUE THREAD

**Issue by galeone** [jinzhu/gorm#731]
I open this issue to make more visible my comment in the commit 2a46856d5238837a5f65f4a05181a6685335a4a

https://github.com/jinzhu/gorm/commit/2a46856d5238837a5f65f4a05181a6685335a4af#commitcomment-14500486

I think that commit broke the right behavior of the update operation on fields with an associated default value, when the field is empty.

regards

**Comment by jinzhu** [comment]
refer https://github.com/jinzhu/gorm/pull/735
