### ISSUE TITLE
Default friendly names for tables and columns

### ISSUE THREAD

**Issue by arafath-mk** [jinzhu/gorm#734]
For following struct, gorm is creating bad default names, which makes extremely difficult to write custom SQL queries.

```
type PFAndESI struct {
	ID         int
	EmployeeID int
	PFNo       string
	ESINo      string
}
```

Following are the gorm created table name and column names. (MySQL is used as database.)
```
p_f_and_e_s_i
id
employee_id
p_f_no
e_s_i_no
```

It would be better, if gorm can generate the following names by default.
```
pf_and_esi
id
employee_id
pf_no
esi_no
```

I have attached a go file to achieve the above output. Could you please review it and incorporate this functionality to gorm? (Please give an option to set a flag to use new friendly naming.)

[main.go.txt](https://github.com/jinzhu/gorm/files/40809/main.go.txt)

**Comment by jinzhu** [comment]
Hi @arafath-mk 

It is a good change, but it might broken people's application, anyway, could you please create pull request, and I will merge it when we release next incompatible release.

Thank you.

**Comment by arafath-mk** [comment]
Thanks @jinzhu 
I will create a pull request.

**Comment by jinzhu** [comment]
Hi  @arafath-mk 

Pushed a commit https://github.com/jinzhu/gorm/commit/f70de0bdff7c9ddf2126fc1f37e4c9adfdca1631　in this pull request https://github.com/jinzhu/gorm/pull/794

Thank you for your work.

**Comment by arafath-mk** [comment]
Thanks @jinzhu
