### ISSUE TITLE
FirstOrCreate + Attrs + Where sometimes creates a new record even if one exists.

### ISSUE THREAD

**Issue by swenson** [jinzhu/gorm#739]
We're seeing a random (about 50% of the time) error when invoking `FirstOrCreate` like so:

```go
err := tx.Where(&metadata).Attrs(NewMetadata{ID: uuid.NewRandom().String()}).FirstOrCreate(&metadata).Error
```

Specifically, even if the `metadata` in the `Where` is populated and exists in the database, a new record will be created in the database.

This way of using the API is straight out of the README.

**Comment by jinzhu** [comment]
Please follow https://github.com/jinzhu/gorm/blob/master/CONTRIBUTING.md

**Comment by jinzhu** [comment]
Going to close this one, please feel free to reopen it if has reproducible script.
