### ISSUE TITLE
Unexpected behaviour

### ISSUE THREAD

**Issue by everclear** [jinzhu/gorm#743]
From the docs..

    // Get record with primary key
    db.First(&user, 10)
    //// SELECT * FROM users WHERE id = 10;

However if you don't provide an int, the argument is passed to the SQL.

    db.First(&user, "1=1")
    //// SELECT * FROM users WHERE 1=1;

To me, that's not the expected behaviour.

**Comment by jinzhu** [comment]
refer https://github.com/jinzhu/gorm#query-with-inline-condition

**Comment by everclear** [comment]
It looks like a security issue to me.

When you have a two parameters, the documentation suggests it's evaluating the second parameter against the primary key (unless struct or map). You are not expecting to be able to inject random SQL.

This certainly allows SQL to be injected into my software, because I assumed the parameter would quoted and checked against the primary key.
