### ISSUE TITLE
Documentation for `sql` tags/annotations?

### ISSUE THREAD

**Issue by AuthorOfTheSurf** [jinzhu/gorm#744]
I have scoured the internet and taken a look at the source code to try and find an enumeration of the possible `sql` tags that gorm accepts. The documentation is good about providing examples:
- `sql:"min:4;max:20;unique"`
- `sql:"size:255"`
- `sql:"AUTO_INCREMENT"`
- `sql:"type:varchar(100);unique"`

but does not enumerate the possibilities, nor does the source code e.g. no list of "acceptable values" when `sql` tag is [parsed](https://github.com/jinzhu/gorm/blob/master/model_struct.go#L456). Could anyone link me to documentation for this? Or direct me to a clear section of the source code that I may have missed?

**Comment by imajes** [comment]
+1 - i'm several hours into something that could really use this (try describing structs for a legacy database... not any fun)

**Comment by derekperkins** [comment]
:+1:

**Comment by jadengore** [comment]
+1 to this as well, it's very confusing. Seems like @jinzhu is working on it for 1.0.

**Comment by renannprado** [comment]
:+1: 
Any news?

**Comment by sredXNY** [comment]
what about default values? for example,I am using postgres and I would like to set as default value in a timestamp, the current timestamp. I tried:
`
Mycolumn time.Time `sql:"DEFAULT NOW()"``

But with no success!

**Comment by jinzhu** [comment]
Done that!

Please checkout http://gorm.io/docs/models.html#Struct-tags
