### ISSUE TITLE
UpdateColumns with zero value will update all field 

### ISSUE THREAD

**Issue by wxf4150** [jinzhu/gorm#745]
m.Mysql.Debug().Where(&CKBiochemical{MhID:v.MhID}).Model(CKBiochemical{}).UpdateColumns(CKBiochemical{TotalBilirubin:0})

when i set the field    TotalBilirubin:0  the debug sql will be:
UPDATE `pr_check_biochemica
l_check` SET `triglycerides` = '0', `high_sensitivity_c_reactive_protein` = '0',
 `alanine_aminotransferase` = '0', `total_bilirubin` = '0', `medical_history_id`
 = '0', `total_cholesterol` = '0', `high_density_lipoprotein_cholesterol` = '0',
 `low_density_lipoprotein_cholesterol` = '0', `creatinine` = '0', `sodium` = '0'
, `potassium` = '0', `creatine_kinase` = '0', `aspartate_aminotransferase` = '0'
  WHERE (`medical_history_id` = '46356')

when i set the field    TotalBilirubin:1  the debug sql will be right:
UPDATE `pr_check_biochemica
l_check` SET `total_bilirubin` = '1'  WHERE (`medical_history_id` = '46356')

some error?

**Comment by galeone** [comment]
@jinzhu my pull request https://github.com/jinzhu/gorm/pull/737 fix this issue.

**Comment by jinzhu** [comment]
Added more documents about this in https://github.com/jinzhu/gorm/tree/v1.0_dev#update

Feedback welcome in #794

**Comment by zj8487** [comment]
@jinzhu 
Is there some good way to get the hanged fields from a struct to ```Update Changed Fields```
any suggestions?

**Comment by jinzhu** [comment]
@zj8487 sorry, could you give some examples, don't really understand what your meaning.

**Comment by zj8487** [comment]
@jinzhu  thanks your feedback

```go
changed := map[string]interface{}{"name": "hello", "age": 18, "actived": false}
db.Model(&user).Updates(changed)
```
Is there good lib for get the ```changed field or map``` for the usage for above?
