### ISSUE TITLE
Gorm doesn't insert false value into database for boolean field

### ISSUE THREAD

**Issue by fengjh** [jinzhu/gorm#746]
```go
type Post struct {
	Title           string
	CommentsEnabled bool `sql:"default:true"`
}

func main() {
	post := Post{Title: "A test post", CommentsEnabled: false}

	err := DB.Debug().Create(&post).Error
	if err != nil {
          panic(err)
        }

	fmt.Println(post.CommentsEnabled)
}

// DB log: INSERT INTO "posts" ("title") VALUES ('A test post') RETURNING "posts".*
// Output: true
```

As the example shows above. The expected result should be `false`, but got `true`. You can reproduce this bug using this gist: https://gist.github.com/fengjh/bb1bc2379d0d857cd52a

**Comment by galeone** [comment]
@jinzhu my PR fixes this bug

**Comment by optimality** [comment]
That's https://github.com/jinzhu/gorm/pull/737 for those of you following along at home.

**Comment by jinzhu** [comment]
Added more documents about this in https://github.com/jinzhu/gorm/tree/v1.0_dev#update

Feedback welcome in #794
