### ISSUE TITLE
Add index to many2many tables two ids

### ISSUE THREAD

**Issue by gnewton** [jinzhu/gorm#751]
The many2many tables auto-generated by gorm of the form:
CREATE TABLE "Article_Author" ("article_id" bigint,"author_id" integer);

And inserts into these table have the form:
INSERT INTO Article_Author (article_id,author_id) SELECT '72','191'  WHERE NOT EXISTS (SELECT * FROM Article_Author WHERE "article_id" = '72' AND "author_id" = '191')

However, when the Article_Author table becomes large, the inner select is a limiting factor as it is performing a where clause on two unindexed colums for each insert. On bulk loads this becomes a problem.

In this example, when I added an index across both columns:
CREATE UNIQUE INDEX a2 on Article_Author(article_id,author_id);

Performance was significantly improved.
I suggest adding the index by default. 
I am using SQLite version 3.8.9 2015-04-08 12:16:33 on Linux Fedora 21 (64bit)

Thanks,
Glen

**Comment by gnewton** [comment]
Actually, for bulk updates, it would be nice to have the choice to turn off the inner select, for content that you know is consistent, and then not take the hit (indexed or not) of the select.

**Comment by jinzhu** [comment]
Created composite primary keys for join tables, thank you for your report.
