### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by ansel1** [jinzhu/gorm#753]
We're trying to collect query time metrics.  The only global hook I see to capture this is by setting a custom logger, which is what we're doing.  However, benchmarking shows that enabled LogMode on a gorm.DB more than doubles the query time for a simple, single row read:

    BenchmarkDebugModeOn-8 	    2000	   1053447 ns/op
    BenchmarkDebugModeOff-8	    3000	    383293 ns/op

I imagine this is because each log statement looks for source file name and line in the callstack, which is expensive.

Could there be another way to capture query times without incurring the addition overhead of debug log mode?  

A middleware-like callback API could do this, and might be useful for other interesting features.  The callback API as it is now is useful, but can only easily be modified on a per-model basis, not globally.

**Comment by jinzhu** [comment]
You could write callbacks for this. https://github.com/jinzhu/gorm/blob/master/doc/development.md
