### ISSUE TITLE
Spatial types

### ISSUE THREAD

**Issue by devfubar** [jinzhu/gorm#757]
Hi,

If I have the following struct;

```go
type Location struct {
	gorm.Model

	UserID uint `sql:"index"`

	Line1   string
	Line2   string
	Town    string
	County  string
	Country string

	Point geo.Point `sql:"type:point"`
}
```
I can select rows easily if I use "https://github.com/paulmach/go.geo" (it implements the scan interface).

To insert spatial data I can use the following SQL;

```sql
INSERT INTO 'locations' ('point') VALUES (GeomFromText('POINT(10 10)'));
```

Currently `db.Create` generates this insert;

```sql
INSERT INTO `locations` (`created_at`,`updated_at`,`deleted_at`,`line1`,`line2`,`town`,`county`,`country`,`point`,`user_id`) VALUES ('2015-12-12T00:37:06Z','2015-12-12T00:37:06Z','<nil>','10','Fubar Road','Madeupvill','Test province','no where','POINT(10 10)','2')
```
Close but how to I get the function *GeomFromText* in front of the string *POINT(10 10)* in the values? I am trying really hard to avoid using raw sql statements.

http://stackoverflow.com/questions/34234027/golang-sql-driver-database-functions/34234432 shows one way I was trying

**Comment by jinzhu** [comment]
For Update you could use `gorm.Expr`, but for create, I guess you can do nothing but use raw sql ;(

**Comment by devfubar** [comment]
Thanks for getting back to me.

Is there a way to make spatial types a feature request?  If I get a bit of direction I don't mind doing a PR as it would be great to have this.  I use them a lot.

**Comment by devfubar** [comment]
Or maybe not specifically spatial types but an interface; similar to Value in *database/sql/driver* that returns customised values?

**Comment by rexfordnyrk** [comment]
@devfubar Please how did you end up implementing this? did you use raw sql or there was some sort of work around. I find myself working with spatial queries and postgres a lot lately. I am new and switching to using golang these days and gorm has been awesome for the most part except for geo queries. Please any help will be appreciated.

@jinzhu please has this been included yet? any best way of achieving this?

**Comment by devfubar** [comment]
Hi @rexfordnyrk you are testing my memory. I believe I ended up not using this library at all as this feature was a must for me.

**Comment by rexfordnyrk** [comment]
@devfubar Thanks very much for the feedback.
