### ISSUE TITLE
Is it possible to make an empty slice for an association that has no data instead of nil?

### ISSUE THREAD

**Issue by Gacnt** [jinzhu/gorm#758]
I'm currently working on a project and right now I have some basic javascript

`blah.map(function(lBlah) {});`

`blah` is generated from an ajax request to a database which returns an array of objects (or slice if you prefer)

The only problem is I get a JS error: `cannot read property 'map' of null` this is because if my `one-to-many` association has no associated values at the time, it just makes that field `nil` instead of an empty slice so when I `json.Marshal` it it sends a null value instead of an empty `[]` which would fix all my errors, currently having to range over each `struct` that is returned from the database and check for nil values then `make([]blah, 0)` is annoying and looks messy. Is there an easier way to accomplish this? Is it possible to set a default `json:"default:[]"` or something? Any help would be great thanks.

**Comment by jugglinmike** [comment]
gh-1199 addresses this.
