### ISSUE TITLE
Identifier name 'maintenance_appointment_service_provider_id_service_provider_id_foreign' is too long

### ISSUE THREAD

**Issue by chanwai1219** [jinzhu/gorm#762]
main table is service_provider, main key is id;
foreign table is maintenance_appointment, foreign key name is service_provider_id;

the outcome of creating a foreign key constraint like this "(Error 1059: Identifier name 'maintenance_appointment_service_provider_id_service_provider_id_foreign' is too long) "

I am using mysql;

I guess that gorm should constraint the foreign key name length;

**Comment by chanwai1219** [comment]
func (scope *Scope) addForeignKey(field string, dest string, onDelete string, onUpdate string) {
	var table = scope.TableName()
	var keyName = fmt.Sprintf("%s_%s_%s_foreign", table, field, regexp.MustCompile("[^a-zA-Z]").ReplaceAllString(dest, "_"))
	if len(keyName) > 60 {
		keyName = keyName[0:60]
	}
	keyName = regexp.MustCompile("_+").ReplaceAllString(keyName, "_")
	var query = `ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s ON DELETE %s ON UPDATE %s;`
	scope.Raw(fmt.Sprintf(query, scope.QuotedTableName(), scope.QuoteIfPossible(keyName), scope.QuoteIfPossible(field), dest, onDelete, onUpdate)).Exec()
}

**Comment by chanwai1219** [comment]
it seems that mysql only support abount 60 char in foreign key name, code above is a workaroud for this issue

**Comment by jinzhu** [comment]
Refer https://bugs.mysql.com/bug.php?id=13942

Seems like you are able to increase the length of foreign key, by default it is 64.

So maybe change the default value in mysql side sounds like a better solution.
