### ISSUE TITLE
#743 Security issue

### ISSUE THREAD

**Issue by everclear** [jinzhu/gorm#763]
#743  - It looks like a security issue to me. I can't reopen it. If you disagree that it could lead to a security to hole then close this too. My software is open to SQL injection because I assumed the example in the docs was correct.

**Comment by jinzhu** [comment]
When you find record with primary key like `db.Find(&user, 1)`, you have to ensure it is a valid primary key.

If you just want to accept user's input as the condition, you should find it like this: `db.Find(&user, "id = ?", 1)`, it could avoid SQL injection.

**Comment by everclear** [comment]
I think you would expect

`db.Find(&user, "john")` to result in `WHERE (name = 'john')`

not

`db.Find(&user, "john")` to result in `WHERE (john)`

As it expects an interface it's not obvious that only an int will work as documented in this scenario.
