### ISSUE TITLE
Expose `For Update` in a transaction context

### ISSUE THREAD

**Issue by marksalpeter** [jinzhu/gorm#769]
Many times, when I perform an update, I use `for update` on a row to guarantee its synchronicity system wide. This is actually a very common thing to do within a transaction. Could something like this be added to the api? Here is an example of how I would like to use it:
```go
tx := db.Begin()
var model Model
if err := tx.First(&model).ForUpdate().Error; err != nil { /* SELECT FIRST * FROM model WHERE id = ? FOR UPDATE */
	log.Println(err)
	tx.Rollback()
	return err
}
model.Field = "update this field in a synchronized way"
if err := tx.Save(&model).Error; err != nil {
	log.Println(err)
	tx.Rollback()
	return err
}
tx.Commit()
```

**Comment by derekperkins** [comment]
:+1:

**Comment by douglarek** [comment]
@jinzhu hi, I see you marked a `v1.0` milestone, would you please wrtite a plan about it in a single issue to track it ?

**Comment by douglarek** [comment]
@jinzhu Ok, it is in #794

**Comment by marksalpeter** [comment]
Excellent!

**Comment by huangzhiran** [comment]
@marksalpeter how can i use "select for update" with gorm, I cannot find description in http://gorm.io/docs/
thanks

**Comment by burtbai** [comment]
@huangzhiran  
这里 [Extra Querying option](http://gorm.io/docs/query.html#Extra-Querying-option)
```
// Add extra SQL option for selecting SQL
db.Set("gorm:query_option", "FOR UPDATE").First(&user, 10)
//// SELECT * FROM users WHERE id = 10 FOR UPDATE;
```

**Comment by marksalpeter** [comment]
@huangzhiran  sorry I didn't see this sooner
http://gorm.io/docs/query.html#Extra-Querying-option
