### ISSUE TITLE
Pivot Columns

### ISSUE THREAD

**Issue by jadedevin13** [jinzhu/gorm#776]
https://laravel.com/docs/5.1/eloquent-relationships#many-to-many

It looks like the one on the link.

The table that is joining the many-to-many relationship has another column aside from the id of the two tables.

**Comment by jinzhu** [comment]
Don't really get what's your question, if you would like to know the usage of many2many relations, refer: https://github.com/jinzhu/gorm#many-to-many

**Comment by jadedevin13** [comment]
For one instance, you have a user that subscribes to products and product can have many subscribers.

```
type Product struct{
   gorm.Model
   User []User `gorm:"many2many:user_product;"`
}
```

```
type User struct{
   gorm.Model
   Product []Product `gorm:"many2many:user_product;"`
}
```

What if I wanted that the table with the user_product name has another columns other than the id of the user and product which is typically like this.

USER_PRODUCT TABLE

user_id | product_id|other_columns
---------- | -------------- |---------------------
1            |                  2 | something
2            |                  3 | something_else


The other_columns is what I mean by **pivot column**. Is there a way that I can access this column from the gorm library?

**Comment by surahmans** [comment]
@jadedevin13 have you solve this case?
