### ISSUE TITLE
Index is not created when CreateTable invoked(MySQL)

### ISSUE THREAD

**Issue by douglarek** [jinzhu/gorm#780]
```
type Order struct {
         SerialNumber     uint64 `sql:"not null;unique_index"`
          ...
 }
```

SerialNumber index is not created when I used `DB.CreateTable`, but it works in `DB.AutoMigrate`.
does it do this on purpose ?

**Comment by jinzhu** [comment]
It was by design, when create table, will only create table, not indexes.

But I am thinking it might be better to auto create indexes, so just change to like this.
