### ISSUE TITLE
Pivot Columns v2

### ISSUE THREAD

**Issue by jadedevin13** [jinzhu/gorm#781]
For one instance, you have a user that subscribes to products and product can have many subscribers.

```
type Product struct{
   gorm.Model
   User []User `gorm:"many2many:user_product;"`
}
```

```
type User struct{
   gorm.Model
   Product []Product `gorm:"many2many:user_product;"`
}
```

What if I wanted that the table with the user_product name has another columns other than the id of the user and product which is typically like this.

###### USER_PRODUCT TABLE

user_id | product_id|other_columns
---------- | -------------- |---------------------
1            |                  2 | something
2            |                  3 | something_else

The other_columns is what I mean by **pivot column**. Is there a way that I can access this column from the gorm library?

**Comment by jinzhu** [comment]
refer: https://github.com/jinzhu/gorm/issues/719#issuecomment-168485989
