### ISSUE TITLE
Tag for primary key gets ignored

### ISSUE THREAD

**Issue by dc0d** [jinzhu/gorm#785]
Tag for primary key gets ignored if the primary key resides in a struct that is embedded in out model struct (This is tested with `github.com/lib/pq`).

Assume out base struct is:
```go
type Model struct {
	ID        int64      `sql:"type:bigint PRIMARY KEY;default:0" json:"id"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at" sql:"index"`
}
```

And our actual model is:
```go
type VirtualUnit struct {
	Model
}
```

The generated id is of type `bigserial` and a sequence named `virtual_units_id_seq` is created too.

But when the `ID` field is added directly inside the struct (here, our actual model `VirtualUnit`) it works as expected.

**Comment by dc0d** [comment]
I forgot to mention that `json:"deleted_at" sql:"index"` for `DeletedAt` is getting ignored too.

**Comment by jinzhu** [comment]
Thank you for the report, this should been fixed.
