### ISSUE TITLE
Major Bug With Where Clause & Empty String

### ISSUE THREAD

**Issue by RichardKnop** [jinzhu/gorm#789]
Consider this test table:

```go
// AccessToken ...
type AccessToken struct {
	gorm.Model
	Token string `sql:"type:varchar(40);unique;not null"`
}
```

Let's say we only have one row in the table with token value being `test_token`.

When using where condition to search for a row by token, if you use empty string, it will return the first row from the table!

```go
accessToken := new(AccessToken)
db.Where(AccessToken{Token: ""}).First(accessToken)
```

Will find a row. This seems like a major bug. The workaround for now is to use plain SQL such as:

```go
accessToken := new(AccessToken)
db.Where("token = ?", "").First(accessToken)
```

Which will work correctly and no rows will be returned.

Here is a full test:

```go
package foobar

import (
	"log"
	"testing"

	"github.com/jinzhu/gorm"

	// sqlite driver
	_ "github.com/mattn/go-sqlite3"
)

// AccessToken ...
type AccessToken struct {
	gorm.Model
	Token string `sql:"type:varchar(40);unique;not null"`
}

func TestFoobar(t *testing.T) {
	db, err := gorm.Open("sqlite3", "/tmp/foobar.sqlite")
	if err != nil {
		log.Fatal(err)
	}

	db.AutoMigrate(&AccessToken{})

	if err := db.Create(&AccessToken{
		Token: "test_token",
	}).Error; err != nil {
		log.Fatal(err)
	}

	accessToken := new(AccessToken)
	notFound := db.Where(AccessToken{Token: ""}).First(accessToken).RecordNotFound()
	log.Print(accessToken)
	log.Print(notFound)

	if !notFound {
		t.Error("Access token should not be found!!")
	}
}

```

**Comment by alecha** [comment]
Totally agree, I have to place a lot of if statements to handle this behaviour which is not the right one....

**Comment by jinzhu** [comment]
In go, there is no different between:

```go
AccessToken{} 
// and
AccessToken{Token: ""}
```

So this is not something gorm could fix, `Update` is similar, when using struct as argument for `Update`, it could only handle those fields with none zero values.

refer: https://github.com/jinzhu/gorm#update
