### ISSUE TITLE
BUG for update

### ISSUE THREAD

**Issue by Yuhang** [jinzhu/gorm#791]
DB.Model(&product).Updates(map[string]interface{}{"price": gorm.Expr("price * ? + ?", 2, 100)})

this line. it will update with propertities in `product`, with some changes not exist in map[string]interface{}{"price": gorm.Expr("price * ? + ?", 2, 100)}

It's a feature? or when to fix?

AND

DB.Table("product").Updates(map[string]interface{}{"price": gorm.Expr("price * ? + ?", 2, 100)})
 works fine.

**Comment by Yuhang** [comment]
![image 16-1-8 at 11 21](https://cloud.githubusercontent.com/assets/1201124/12201342/d0f0c2ac-b65e-11e5-9263-04ae21535107.jpg)

**Comment by jinzhu** [comment]
This is thought as a feature, as you might change some values in the callbacks, so those changes will be saved into database also.

You might want to checkout `UpdateColumns` if you only want to update selected Columns.
