### ISSUE TITLE
DISTINCT for Preload

### ISSUE THREAD

**Issue by tuwukee** [jinzhu/gorm#793]
Is it possible to achieve distinct functionality for many2many relations with gorm?

I'd like to force smth like this:
`db.Preload("Posts").Find(&tag, id)`

to generate the next query:
```
SELECT DISTINCT `posts`.* FROM `posts` INNER JOIN `posts_tags` ON `posts`.`id` = `posts_tags`.`post_id` WHERE  `posts_tags`.`tag_id` = 1
```

**Comment by begizi** [comment]
I'm also looking to be able to do custom sql for preload queries
