### ISSUE TITLE
Searching & Sorting on related member fields

### ISSUE THREAD

**Issue by jakblu** [jinzhu/gorm#801]
Hello there,

let assume we have the following datamodel:

```
type User struct {
	ID     uint
	RoleID uint
	Role   Role
}

type Role struct {
	ID   uint
	Name string
}
```

When i want to retrieve the Users and there Roles from the database i do the following with preloading:

```
func GetUsersFromDatabase(users []User) {
	DB.Preload("Role")
	DB.Find(&users)
}
```

Now I want to search or sort the result dependend on the Role Name...

I searched in the tests and documentation for a way to filter ("Where") and sort ("Order") this type of modelstructure on the database. Is there a way to do this with the Preload mechanism or is there more work to do, e.g. with the Join function?

Thanks for your advise.

**Comment by jinzhu** [comment]
Duplicated with #598, will support this in the v1.0 release.
