### ISSUE TITLE
Clarify what happens to associations on update

### ISSUE THREAD

**Issue by RichardKnop** [jinzhu/gorm#807]
Maybe it would be good to make it clear in the README what actually happens with associations on update.

Let's say you have a user with a profile:

```go

user := &User{
    Username: "username",
    Profiles: []*Profile{
        &Profile{"buyer"},
    },
}
db.Create(user)
```

When you fetch that user from the database:

```go
user := new(User)
db.Preload("Profiles").Last(user, 1)
```

And then replace the profile with a new one:

```go
user.Profiles = []*Profiles{
    &Profile{"seller"},
}
db.Save(user)
```

It won't delete the previous relationship to the buyer profile and you will end up with a user with both seller and buyer profile.

Is that correct? That seems to be the current behaviour according to my tests.

Is recommended way to update the relationships then using `Association` method?

```go
db.Model(user).Association("Profiles").Replace(&profile{"seller"})
```

As that is the logical behaviour. Using the `Save` method doesn't behave as I would expect. After saving a model I would expect for the database state to reflect exactly how the struct I passed to `Save` was.

**Comment by jinzhu** [comment]
Yes, it is correct behaviour according to my understanding. if you want to replace current relationship, refer: https://github.com/jinzhu/gorm#association-mode

Checkout this file to see what really happened when creating https://github.com/jinzhu/gorm/blob/v1.0_dev/callback_create.go#L9-L19 , updating https://github.com/jinzhu/gorm/blob/v1.0_dev/callback_update.go#L10-L18

**Comment by RichardKnop** [comment]
@jinzhu Thanks. I am building a REST API and thought it would be sweet to just unmarshal JSON from request into a model and `Save` would completely handle relationships (delete what's not in the request and add anything new). But that would probably lead to unexpected behaviour in other scenarios.

I'll just use `UpdateColumns` to update all model columns and then use `Association.Replace` to update related objects.

**Comment by jinzhu** [comment]
Hi @RichardKnop 

If you just want to simple REST API, maybe you could check this out https://github.com/qor/qor-example#restful-api

**Comment by jonathanfoster** [comment]
The association docs link above is broken. The new link is http://gorm.io/docs/associations.html#Association-Mode.

**Comment by sanjaesan** [comment]
> @jinzhu Thanks. I am building a REST API and thought it would be sweet to just unmarshal JSON from request into a model and `Save` would completely handle relationships (delete what's not in the request and add anything new). But that would probably lead to unexpected behaviour in other scenarios.
> 
> I'll just use `UpdateColumns` to update all model columns and then use `Association.Replace` to update related objects.

Hi @RichardKnop 

Please can i know if gormV2 now works exactly the way you intended here?
