### ISSUE TITLE
Preload() with preexisting schema

### ISSUE THREAD

**Issue by wyattjoh** [jinzhu/gorm#812]
We have pre-exising schema as seen in https://gist.github.com/wyattjoh/850c56c8526a10300af2#file-schema-sql and are experiencing some issues while trying to use the `Preload` feature.

Specifically, we try https://gist.github.com/wyattjoh/850c56c8526a10300af2#file-does_not_work-go and it does not work, yielding the error:

```
[2016-01-19 17:30:01]  can't find field ProfileImage in *[]main.User
2016/01/19 17:30:01 can't find field ProfileImage in *[]main.User
```

Yet if we change the name in Go as in https://gist.github.com/wyattjoh/850c56c8526a10300af2#file-does_work-go (Changing `ProfileImage` to `Profileimage`) it does work. We'd like to keep our notation of using `ProfileImage`, but we aren't sure of the correct tags to add to make it work.

**Comment by jinzhu** [comment]
This should been fixed.
