### ISSUE TITLE
Where clause is getting appended to subsequent requests

### ISSUE THREAD

**Issue by collinglass** [jinzhu/gorm#814]
This happens with both the Where.("id = ?", id).First(&entity) as well as .First(&entity, id)

My first request will look like the following:

```
SELECT  * FROM "games"  WHERE ("games".deleted_at IS NULL OR "games".deleted_at <= '0001-01-02') AND (("id" = '18')) ORDER BY "games"."id" ASC LIMIT 1
```

And my second request will have this:

```
SELECT  * FROM "games"  WHERE ("games".deleted_at IS NULL OR "games".deleted_at <= '0001-01-02') AND ("id" = '18') AND (("id" = '20')) ORDER BY "games"."id" ASC LIMIT 1
```

**Comment by collinglass** [comment]
It happens to me when I define an API like so:

func RestGetById(intf interface{}) func(w rest.ResponseWriter, r *rest.Request) {
	return func(w rest.ResponseWriter, r *rest.Request) {
		id := r.PathParam("id")
		if err := DB().First(intf, id).Error; err != nil {
			rest.NotFound(w, r)
			return
		}
		w.WriteJson(intf)
	}
}

and I defined my handlers like this:

rest.Get("/games/:id", RestGetById(&models.Game{})).

Here, there is a single models.Game{} pointer that is reused on every request. So my first request works fine but for some reason, any subsequent requests have the sideeffect of a second id clause in the generated SQL.

By moving over to an http handler that creates a new models.Game object every request, it doesn't have this side effect.

**Comment by jinzhu** [comment]
Please follow https://github.com/jinzhu/gorm/blob/master/CONTRIBUTING.md to submit a runnable script

**Comment by jinzhu** [comment]
Hi @collinglass 

I just noticed you are sharing one `Game` for multiple requests, this is not goroutine safe, and could cause bug to use it like this.
