### ISSUE TITLE
How to insert 2 records with null value in to a unique indexed column?

### ISSUE THREAD

**Issue by chenzhendong** [jinzhu/gorm#817]
In Postgres, the Unique Indexed column allowing Null value.   When an index is declared unique, multiple table rows with equal indexed values are not allowed. Null values are not considered equal. A multicolumn unique index will only reject cases where all indexed columns are equal in multiple rows.
which means Null != Null.

But gorm insert a empty space instead of Null value, since golang don't allow nil?   How could I implement unique index allowing insert null value through the gorm?

**Comment by jinzhu** [comment]
You could use pointer of string or `NullString`
