### ISSUE TITLE
Avoid save some struct field that is another struct

### ISSUE THREAD

**Issue by llcan1120** [jinzhu/gorm#818]
```go 

struct User {
    Photo Photo
    PhotoID int
    ID       int
}

struct Photo {
    ID     int
}
```

Say i have struct as above, when a save User or update User, gorm will automatically save Photo again. Is there any way to prevent this operation?

**Comment by chenzhendong** [comment]
Try put a tag  `gorm:"-"` after "Photo Photo"?

**Comment by jinzhu** [comment]
refer: https://github.com/jinzhu/gorm/issues/844
