### ISSUE TITLE
Cannot get an error back (but see it printed)

### ISSUE THREAD

**Issue by debedb** [jinzhu/gorm#819]
I am creating an entry in a transaction. The entry has a unique key and the unique constraint fails. Then I am trying to do GetErrors() but I get nothing either from the transaction object (whatever got returned by db.Begin() or from db itself). Here, db is *gorm.DB. I do however see the error printed in stdout. 

I see that it is getting added to some place - callback_create.go:74 does a scope.Err which should add this error to the list. I've put a debug print there and sure enough the error gets added to some list of errors... Just not the one I apparently am getting?

I realize this is not very well formatted as an issue as I am not giving exact steps to reproduce, but I couldn't find elsewhere to ask.

**Comment by jinzhu** [comment]
Hi @debedb 

It might be good to write a simple demo to reproduce your issue, I think it should be reproducible. 

Then I could check if there are anything wrong, thank you.
