### ISSUE TITLE
many2many relationships with join parameter

### ISSUE THREAD

**Issue by pnagy** [jinzhu/gorm#821]
I can't see the way to implement a many2many relationship between two table if this relationship has some parameter. For example:
```
user:
ID int
Name string

language:
ID int
Name string

user_language
UserID int
LanguageID int
StartedAtAge int
```
What is the best way to do this?

**Comment by begizi** [comment]
I'm also looking for the best way to accomplish this. So far what I've come up with is creating the struct to represent the join table and use pointers to reference the join entities.

```
User:
ID int
Name string

Project:
ID int
Name string

Membership: (join table)
UserID *User
ProjectID *Project
IsOwner bool
CreatedAt time.Time
```

I'm guessing I wont be able to use the association helpers like `Append` if I want to be able to populate the `IsOwner` and `CreatedAt` fields though. Anyone have a better way to do this?

**Comment by jinzhu** [comment]
refer: https://github.com/jinzhu/gorm/issues/719#issuecomment-168485989
