### ISSUE TITLE
How to use ILIKE instead = when using Query With Where (Struct & Map)

### ISSUE THREAD

**Issue by basco-johnkevin** [jinzhu/gorm#825]
```
Db.Where(model.State{
    Name: sessionCreateForm.Email
}).First(&user)
```
The code above will translate to this query: `SELECT * FROM state WHERE name = 'AlabaMa'`

But how would I use ILIKE instead of `=` ? 

I wanted to construct this query: `SELECT * FROM state WHERE name ILIKE 'AlabaMa'` using Query With Where (Struct & Map) - https://github.com/jinzhu/gorm#query-with-where-struct--map

**Comment by basco-johnkevin** [comment]
Is this currently possible?

**Comment by jinzhu** [comment]
This is not possible and I don't think we will support it shortly ;(

**Comment by basco-johnkevin** [comment]
@jinzhu Okay, no problem. Thank you. Anyway, I think it will be nice if we just leave this issue open? And label it as a feature request? Someone might be willing to send a pull request.

**Comment by jinzhu** [comment]
Hi @basco-johnkevin 

I don't really have a clear idea for how to support this, maybe not even possible ;(

So not going to leave it open, but anyway, if you have any suggestions for the API, feel free to reopen another issue.

**Comment by gelidus** [comment]
@jinzhu Is it possible to use some sort of raw query to achieve this?

**Comment by tavyandy97** [comment]
```
Where("name ilike ?", "AlabaMa")
```
would render an SQL something like
```
WHERE name ILIKE 'AlabaMa'
```
