### ISSUE TITLE
Saving a record with deleted_at column returns an error in mysql strict mode

### ISSUE THREAD

**Issue by ivijayprasad** [jinzhu/gorm#828]
- Connect to mysql in strict mode by giving strict=true in option while opening gorm DB connection
- Try to update an existing record with deleted_at column using save. That will generate a query of below type

`UPDATE `<table_name>` SET `deleted_at` = '<nil>',  `<column_name>` = '<column_value>'... WHERE (`<table_name>`.deleted_at IS NULL OR `<table_name>`.deleted_at <= '0001-01-02') AND (`id` = '<id>');`
- The above query will throw a waring like 'Warning 1292: Incorrect datetime value: '0001-01-02' for column 'deleted_at' at row 1'. Since we are connected to mysql in strict mode where warnings are treated as errors, The update will throw an error.

**Comment by ivijayprasad** [comment]
This looks to be happening because in the base gorm.Model, deletedAt is a pointer to time.Time whereas createdAt and updatedAt are of type time.Time.

Can anyone explain on why the type of deletedAt is a pointer to time.Time?

**Comment by jinzhu** [comment]
`DeletedAt` is using pointer to time.Time as it could be NULL, in this case, I don't want to use zero time as the default value.

The above SQL will be changed in the v1.0 release, will only including `deleted_at IS NULL` then.

For now, it might be better to change mysql mode for this.

**Comment by andela-hkoske** [comment]
@ivijayprasad How did you fix this problem?
