### ISSUE TITLE
Foreign key names too long

### ISSUE THREAD

**Issue by speijnik** [jinzhu/gorm#829]
Some DBMS, like MySQL, support foreign key names only up to a certain length. The current approach
generates a name that depends on multiple factors, possibly generating a FK name that is rather long.

The idea here is to use a hash function to generate parts of the name, possibly making it shorter and not exceed limits on MySQL.

**Comment by jinzhu** [comment]
Hi @speijnik 

I think change the default length might be a better solution, Refer https://bugs.mysql.com/bug.php?id=13942
