### ISSUE TITLE
unexpected command tag UPDATE

### ISSUE THREAD

**Issue by vpol** [jinzhu/gorm#833]
```go
sql := "update table1 set field1 = field1 + 1 where id = 1 returning field1, field2"
tx := DB.Begin()
rows, err := tx.Raw(sql).Rows()
if err != nil {
	tx.Rollback()
	log.Panic(err)
	return
}
...
tx.Commit()
```

[2016-02-03 11:30:12]  [20.36ms]  update table1 set field1 = field1 + 1 where id = 1 returning field1, field2
[2016-02-03 11:30:12]  unexpected command tag UPDATE

What am i doing wrong?

Same scenario works perfectly in sql database itself.

**Comment by jinzhu** [comment]
I think this is not an error from GORM, but from database, so can't help on that.

Maybe good to search this question with more detailed information of your database.

Sorry for that.
