### ISSUE TITLE
Count With Preload

### ISSUE THREAD

**Issue by LiranCohen** [jinzhu/gorm#837]
This seems to just give a count of all people regardless of what Preload is pulling with it's arguments. 

```
db.Model(&people).
   Preload("Addresses", "state = (?)", "FL").
   Offset(0).Limit(20).
   Find(&people).
   Count(&count)
```

**Comment by jinzhu** [comment]
The `Count` method is getting people's count, not related about the `Preload` method, so I think it works correctly?
