### ISSUE TITLE
Cyclical References

### ISSUE THREAD

**Issue by pjebs** [jinzhu/gorm#838]
type User struct {
    gorm.Model
    Languages         []Language `gorm:"many2many:user_languages;"`
}

type Language struct {
    gorm.Model
    Name string
}

db.Model(&user).Related(&languages)

**Comment by pjebs** [comment]
If User and Languages struct were in different packages and they both had a many-to-many field linking to each other, how can I avoid cyclical references?

**Comment by pjebs** [comment]
A better example:


package A
type customer {
Name string
Events []B.Event gorm:"many2many:..."
}

package B
type event {
Id int
Customers []A.Customer gorm:"many2many:..."
}

**Comment by jinzhu** [comment]
This is not allowed in Go

If in same package, then possible to use pointer of struct for this.

**Comment by pjebs** [comment]
Any work a rounds with interfaces?

**Comment by pjebs** [comment]
I think it would be good if you can define gorm.Model etc in terms of interfaces so this problem can be solved.
