### ISSUE TITLE
github.com/orgs/go-gorm/dashboard

### ISSUE THREAD

**Issue by pedromorgan** [jinzhu/gorm#842]
Have registeres the "namespace in github"

github.com/orgs/go-gorm/dashboard

Am creating the "definitive guide to Gorm" as an idea.. but from #1 we need multilang ;-)

**Comment by pedromorgan** [comment]
Is this ok with @jinzhu  and @gorm onpinion in general .. ??

**Comment by jinzhu** [comment]
Hi @pedromorgan 

As I talked, I would like to use github pages for this, refer: https://pages.github.com/
