### ISSUE TITLE
Batch finds

### ISSUE THREAD

**Issue by ronna-s** [jinzhu/gorm#843]
I needed something similar to rails find_each - iterating over a large table in batches of 1000, and running callbacks on the results, so I implemented something small, but I'm not sure I'm doing it correctly (specifically, how I'm handling the where arguments and what scope to return, also where I can define a constant batch size), so it's not good enough for a PR yet.
I also have a problem specifying the table for the Count query.
Thoughts?

```go
func (s *DB) FindEach(out interface{}, cb func(), where ...interface{}) *DB {
	var (
		count  uint64
		offset uint64
		limit  uint64
	)
	c := s.clone()
	if len(where) > 0 {
		c = c.Where(where)
	}
	c = c.Count(&count)
	offset = 0
	limit = s.batchSize
	for offset < count {
		c = s.clone()
		c = c.Offset(offset).Limit(limit).Find(out, where...)
		cb()
		offset += limit
	}
	return c
}
```

**Comment by jinzhu** [comment]
For those cases, I prefer use this: https://github.com/jinzhu/gorm#row--rows

In the v1.0 release, I will add some helpers to scan `Row` into struct.

Thank you
