### ISSUE TITLE
Question: is there any way to ignore associations on Save call?

### ISSUE THREAD

**Issue by elgris** [jinzhu/gorm#844]
Let's say I have an entity with associations. I enjoy gorm's preloading, but I don't need to save all associations again when I update a model.

Example:
```
type A struct {
 B FooType
 C BarType
}
...
a := LoadSomeAFromDatabaseWithAssociationsAndChangeSomething()
db.Save(a)
...
```
In this scenario `gorm` also tries to save something in tables `b` and `c`. I'd like to avoid it.

Thanks in advance for any suggestion!

**Comment by RichardKnop** [comment]
You can use UpdateColumn or UpdateColumns:

```go
db.Model(&user).UpdateColumn("name", "hello")
//// UPDATE users SET name='hello' WHERE id = 111;

// Update with struct only works with none zero values, or use map[string]interface{}
db.Model(&user).UpdateColumns(User{Name: "hello", Age: 18})
//// UPDATE users SET name='hello', age=18 WHERE id = 111;
```

**Comment by jinzhu** [comment]
You could also use `Omit`, `Select` to ignore some columns or relations.

Or use `db.Set("gorm:save_associations", false).Save(&user)` , this will ignore all relations.
