### ISSUE TITLE
embedded structure

### ISSUE THREAD

**Issue by DieselDraft** [jinzhu/gorm#847]
I found strange behavior. The UpdateColumn() dont know work with embedded structure

```
package models

import "bitbucket.org/bukorama/backend/src/services"

type BaseBook struct {
	ID uint64 `gorm:"column:id"; primary_key:yes`
}

type Book struct {
	BaseBook
	OriginalId *uint64 `gorm:"column:original_id;`
}

func (v Book) TableName() string {
	return "book"
}


func (book Book) SetOriginalID(OriginalId uint64) {
	services.Con.Debug().Model(book).UpdateColumn("original_id", OriginalId)
}

```

I receive the next SQL `UPDATE book SET original_id = '38290` . It forgot about WHERE

**Comment by jinzhu** [comment]
Please follow https://github.com/jinzhu/gorm/blob/master/CONTRIBUTING.md to submit a runnable script

**Comment by jinzhu** [comment]
closing this one as not responded from reporter, feel free to reopen it if still has issue.
