### ISSUE TITLE
Use not primary key as foreign key

### ISSUE THREAD

**Issue by sunprophit** [jinzhu/gorm#849]
I have an existing schema like:
type ObjectA struct {
    ID int64
    Name string
    B ObjectB
    ObjectBNonPrimaryKey int64
}

type ObjectB struct {
    ID int64
    NonPrimaryKey int64
}

Is it possible to specify ObjectB.NonPrimaryKey field as foreign key for ObjectA

Only workaround I found
type ObjectB struct {
    ID int64
    NonPrimaryKey int64 `gorm:"primary_key"`
}

**Comment by jinzhu** [comment]
You could use that by setting tag `ForeignKey`, `AssociationForeignKey`, refer: https://github.com/jinzhu/gorm/blob/master/model_struct.go

Will have more detailed document in v1.0 https://github.com/jinzhu/gorm/issues/744
