### ISSUE TITLE
Many2many association broken by struct naming

### ISSUE THREAD

**Issue by asampal** [jinzhu/gorm#852]
If I have the following structs (simplified here), there is a problem following relations due to the naming that arises by convention on capitalized words. The table definition for the join table was created by hand with columns `sku_id` and `sku_item_id`. Gorm, in the generated SQL for the association table, will use names like `s_k_uitem_id` and `s_k_u_id`. Is it possible to specify the column names to use in the association table or do I have to rename the structs to `Sku` and `SkuItems` (which makes things work)?

```
type SKU struct {
	ID       int             `gorm:"primary_key" json:"id"`
	SKUItems []SKUItem       `gorm:"many2many:sku_x_sku_item;associationforeignkey:id;foreignkey:id;" json:"skuItems"`
}

func (p SKU) TableName() string {
	return "skus"
}

type SKUItem struct {
	ID int `gorm:"primary_key" json:"id"`
}

func (p SKUItem) TableName() string {
	return "sku_items"
}
```

**Comment by jinzhu** [comment]
Hi @asampal 

The v1.0_dev branch should fixed the issue.

**Comment by asampal** [comment]
Do you have any idea when that will make it to master?

**Comment by jinzhu** [comment]
Hopefully before the end of this month
