### ISSUE TITLE
Relational Association Improvements

### ISSUE THREAD

**Issue by marksalpeter** [jinzhu/gorm#858]
--
To illustrate some of the cases when dealing with relational tables, I'm going to reference the following `many2many` relationship:
```go
type Foo struct {
	ID   uint
	Bars []Bar `gorm:"many2many:foo_bar;"`
}

type Bar struct {
	ID uint
}
```
--
#### 1. `DropTable` Support
 `DropTable`  should drop relational tables on models with an explicit relational table added. Currently there doesn't appear to be a way to do this in gorm. 

###### For Example: 
```go
db.DropTable(&Foo{})
// PROBLEM: `foo` is gone, but `foo_bar` is still in the database 
```
--
#### 2. Better `Append` Support
Append doesn't create a new record when the id isn't auto incremented.

###### For Example: 
```go
var foo Foo
if err := db.Find(&foo, 1).Error; err != nil {
	log.Println(err)
	return err
}
db.Model(&foo).Association("Bars").Append(&Bar{ ID: 12345 })
// PROBLEM: this adds a row to the `foo_bar` table, but doesn't add a row to the `bar` table
```
--
#### 3. Better `Related` Support
Related doesn't seem to work both ways

###### For Example: 
```go
var bar Bar
if err := db.Find(&bar, 1).Error; err != nil {
	log.Println(err)
	return err
}
var foo Foo
if err := db.Model(&bar).Related(&foo).Error; err != nil {
	// PROBLEM: we shouldn't end up here if there is a Foo related to this Bar
	log.Println(err)
	return err
}
```
--
Thanks for looking this issued over. I'm not sure if any of these issues matter to anyone else, but I've found them to be minor hiccups in an otherwise smooth workflow.

\- Mark

**Comment by jinzhu** [comment]
Hi @marksalpeter 

Thank you for your feedback.

For your first question, I prefer better don't drop the join table automatically, kind of dangers. If you want, you could use `db.DropTable("foo_bar")` to delete it.

Second question, GORM won't save associations with non-blank primary key to reduce unnecessary SQL. if you want to create it, better to run `db.Create(&Bar{ ID: 12345 }` first.

Doesn't really understand your third question, could you give more details, a runnable script would be better.

**Comment by marksalpeter** [comment]
I didn't realize I could just pass a string for the first one and I hadn't though out the consequences of the second in the case where I simply needed to add foreign key relations to existing tables. I think you're right on both accounts.

Here's an example of the third:
```go
type Foo struct {
    ID   uint
    Bars []Bar `gorm:"many2many:foo_bar;"`
}

type Bar struct {
    ID uint
}

func main() {
  // create a foo
  var foo Foo
  if err := db.Create(&foo).Error; err != nil {
      log.Println(err)
      return err
  }

  // append a bar
  var bar Bar
  db.Model(&foo).Association("Bars").Append(&bar)

  // look up the foo from the bar fails
  var relatedFoo Foo
  if err := db.Model(&bar).Related(&relatedFoo).Error; err != nil {
      // PROBLEM: we shouldn't end up here if there is a Foo related to this Bar
      log.Println(err)
      return err
  }

}
```
Thanks for the feed back.

**Comment by jinzhu** [comment]
Hi @marksalpeter 

The third one need a foreign key
```go
type Bar struct {
    ID uint
   FooID uint
}
```
