### ISSUE TITLE
How to inject net.Context into gorm callbacks/functions?

### ISSUE THREAD

**Issue by amrnt** [jinzhu/gorm#862]
I had a callback that update CreatorID, UpdaterID AfterCreate and AfterUpdate. The userID is saved in the context. What would be the best practice to pass the context to fetch the data required for the callbacks (or maybe somewhere else)?

**Comment by jinzhu** [comment]
Hi @amrnt 

There is a GORM plugin, did almost same thing, please refer this: https://github.com/qor/audited
