### ISSUE TITLE
Log fatal sql errors by default

### ISSUE THREAD

**Issue by ArmstrongCN** [jinzhu/gorm#864]
Fatal sql errors should be logged by default no matter what the debug option is. When debug option is on, there are too many ouputs for human eyes to notice the error.

**Comment by jinzhu** [comment]
Is it the default behaviour already? If you don't set the `LogMode`, if there are any errors happened except `RecordNotFound, they should be printed.

You could run gorm's tests to check it out.

**Comment by ArmstrongCN** [comment]
wow.. If LogMode has been set, there is no way to get it back to "default" behavior. How about turnning ture/false into log level so as to change logging behavior on the fly?

**Comment by jinzhu** [comment]
Yes, so there are actually three log levels, the default level is print errors happened, if you want to change the logging behaviour on fly, you could `New` another db, and change its log mode.

`db.New().LogMode(true)`
