### ISSUE TITLE
scope question

### ISSUE THREAD

**Issue by mosheco** [jinzhu/gorm#869]
(I couldn't find a discussion group for gorm, so I am asking here).

What is the purpose of scopes and Unscoped() ?
I did see the examples in the README for scopes but could not deduct the advantage vs. regular WHERE.

**Comment by jinzhu** [comment]
`Scope` could be used to do the same job as `Where`, it is useful when you want to share some complicated `Where` but not write it everywhere.

`Unscoped` is used for soft delete.

**Comment by matrixstylite** [comment]
how can i delete the scope
