### ISSUE TITLE
Easier way to update with Associations?

### ISSUE THREAD

**Issue by danhardman** [jinzhu/gorm#871]
I was just wondering if there was a better way to update models with their associations. The `DB.Create()` function handles associations fine so why can't `DB.Save()`?

What I'm currently doing is:

	var post model.Post
	if err := config.DB.First(&post, id).Error; err != nil {
		return err
	}

    post.Title = title
	post.Content = content
	post.AuthorID = author.ID
	post.URL = url

	if err := config.DB.Save(post).Error; err != nil {
		return err
	}

	if err := config.DB.Model(&post).Association("Author").Replace(author).Error; err != nil {
		return err
	}

	if err := config.DB.Model(&post).Association("Tags").Replace(tags).Error; err != nil {
		return err
	}

	return nil

If I set the `post.Author` and `post.Tags` values before calling `DB.Save()`, I get: `reflect.Value.Addr of unaddressable value` from:

    /usr/local/go/src/reflect/value.go:240 +0x8c
    github.com/jinzhu/gorm.SaveBeforeAssociations(0xc8205a1200)
	  /Users/danhardman/Code/go/src/github.com/jinzhu/gorm/callback_shared.go:21 +0x311

**Comment by jinzhu** [comment]
Please follow https://github.com/jinzhu/gorm/blob/master/CONTRIBUTING.md to submit a runnable script
