### ISSUE TITLE
gorm 映射 create的时候失效

### ISSUE THREAD

**Issue by skadilover** [jinzhu/gorm#872]
当我定义的时候  
type order struct{ 
        LastSatus int `gorm:"status"`
}

t.Save(&o)是好用的，但是t.Create(&o)就会报错找不到字段
err_msg":"Error 1054: Unknown column 'last_status' in 'field list'

**Comment by jinzhu** [comment]
按照这个　https://github.com/jinzhu/gorm/blob/master/CONTRIBUTING.md　写个可以复现的脚本？

**Comment by skadilover** [comment]
异常信息:
(/data/home/liyu1/workspace/order2/Go/src/tmp/main.go:46)
[2016-03-01 10:25:38]  Error 1146: Table 'trade.tests' doesn't exist

(/data/home/liyu1/workspace/order2/Go/src/tmp/main.go:46)
[2016-03-01 10:25:38]  [2.22ms]  INSERT INTO `tests` (`s_aage`) VALUES ('29')
Error 1146: Table 'trade.tests' doesn't exist

代码如下：

var db gorm.DB

var text = flag.String("c", "", "connect string")

func init() {
    flag.Parse()
    var err error
    fmt.Println("text is:", *text)
    db, err = gorm.Open("mysql", *text)
    if err != nil {
        panic(err)
    }
    db.LogMode(true)
}

/*
DDL:
  create table `test` (
    `id` int(10) not null default 0,
    `age` int(10) not null default 0,
    primary key (`id`)
  )
*/

type Test struct {
    Id    int
    SAage int `gorm:"age"` // SAage 映射为age了
}

func main() {
    // Your code
    test := &Test{
        SAage: 29,
    }
    if err := db.Debug().Create(test).Error; err != nil {
        fmt.Println(err)
    }
}

**Comment by jinzhu** [comment]
```go
type test struct {
	id    int
  saage int `gorm:"column:age"` // saage 映射为age了
}
```
定义错了，参考上面
