### ISSUE TITLE
Handling of byte slice/array and time.Time

### ISSUE THREAD

**Issue by nkovacs** [jinzhu/gorm#873]
If I create a new type out of `[]byte` (`type ByteArr []byte`), the postgres dialect (specifically, `isByteArrayOrSlice`) will recognize it as a byte slice, and will use the postgres `bytea` type. The others will not.

Here's an example comparing the two methods:
http://play.golang.org/p/PyBc8eGOF6

The Postgres dialect also supports byte arrays (the go type), the others do not.

time.Time has a similar problem, you can't use a custom type that derives from time.Time.

The other types all use Kind, so custom types derived from them work.

You could use reflect.Type.ConvertibleTo to support custom types derived from time.Time:
http://play.golang.org/p/kzXczO4xef
The same would work for []byte, but `isByteArrayOrSlice` is better, because it supports byte arrays too.

An example of where this would be useful is json.RawMessage. I can't use it as the field's type, I have to use `[]byte`, but that means I can't just take the model and convert it to json, because the byte slice will become a base64 encoded string. (I know I can specify the sql type manually in the tag, but if I use the mysql type `longblob`, it won't work on postgres, and vice versa).

**Comment by nkovacs** [comment]
Looks like this isn't as easy as I thought. I implemented it here: https://github.com/nkovacs/gorm/tree/byte-time-handling. Migration works, and reading works as well, but inserting doesn't, because the sql package or the driver isn't smart enough to convert the go `time.Time` or `json.RawMessage` to the appropriate sql type, and I get an unsupported type error from Exec.

**Comment by jinzhu** [comment]
Write a scanner, valuer for this.

**Comment by nkovacs** [comment]
Gorm still won't be able to figure out the type during migration.

**Comment by jinzhu** [comment]
If it is a scanner, gorm will use the scanner's first field's type to generate the SQL type.

or you could just use the sql tag to set the type.

**Comment by pedromorgan** [comment]
We need a FAQ out of all these closed issues...
and need a couple days to create new website.. (time.time.time)
seems to be same question reappearing....

**Comment by nkovacs** [comment]
Thanks, I'll try it out.

**Comment by jinzhu** [comment]
@pedromorgan most closed issues, not really problems, and the answer could be find in the documents or past issues...

I think we should be more strict to ask a runnable script for issues, only people who want to contribute his time by writing the script worth our time, it is pretty time costing for me to setup testing env for every issues.
