### ISSUE TITLE
SQL Injection with First

### ISSUE THREAD

**Issue by cristian-sima** [jinzhu/gorm#874]
@jinzhu 

I am really starting to worry about SQL Injection

Suppose this simple code:

```
rawID := "'; -- "
account := &auth.Account{}
db.First(&account, rawID)
```

The console prints the following log:

```
 Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''; --)) ORDER BY `account`.`id` ASC LIMIT 1' at line 1
```

which is a *clear sign* of a SQL injection. 

Thus, the `First` function does not escape the input which may be a cause of SQL injection.

Are the other methods (`Where`,`Find`, etc) working in the same way? It is really a big security problem.

Thanks

**Comment by jinzhu** [comment]
You should never accept user's inputs as SQL conditions, but only params, this will works, will avoid SQL injection.

```
db.First(&account, "name = ?", "'; --")
```

**Comment by cristian-sima** [comment]
In the case I have this object

```
user := User{
 name : "'; --',
}

db.Save(user)

```
Do I have a problem with SQL injection?

**Comment by jinzhu** [comment]
No, won't have SQL injection problem.

**Comment by danhardman** [comment]
Is user provided input okay when using the `db.Create` method? I currently do:

	post := &model.Post{
		Title:    r.FormValue("title"),
		Content:   r.FormValue("content"),
		Author:   author,
		AuthorID: author.ID,
	}

	err := config.DB.Create(&post).Error
	if err != nil {
		return err
	}

Am I safe with this? Are the values properly prepared as parameters?

**Comment by lazercorn** [comment]
@danhardman should be fine. jinzhu said cristian-sima's User object example won't have any SQL injection and name : "'; --", is essentially a SQL injection statement so you can assume r.FormValue("title") was "'; --' . If his example is fine, according to jinzhu, yours should be too.
