### ISSUE TITLE
Batch update expecting array only getting single value

### ISSUE THREAD

**Issue by asampal** [jinzhu/gorm#875]
If I have the following SQL:
```	
if err:= App.Exec(
		`update orders
			set tracking_number = data_table.tracking_number,
			stage_id = (select id from order_stages os where os.id = data_table.stage_id::integer),
			meta = data_table.meta::jsonb
		from
			(select unnest(array[?]) as dcl_order_number, unnest(array[?]) as stage_id, unnest(array[?]) as tracking_number, unnest(array[?]) as meta) as data_table
		where orders.dcl_order_number = data_table.dcl_order_number;	`, []string{"TEST0003", "TEST0002"}, []int{10, 60}, []string{"AKZZ1234-00023", "FOOBA9888"}, []string{`{"serial_numbers": "1232154553,756675665657,sdlsdjlf9328"}`,`{"serial_numbers": "5555,756675665657,sdlsdjlf9328"}`}).Error; err != nil {
		return err
	}
	return nil
```
I should not need to wrap the parameters to `unnest()` with `array[]` if the values being used are of type array or slice as the `unnest` function is meant to work with that data type. Without the `array[]` I get an error.

**Comment by jinzhu** [comment]
![image](https://cloud.githubusercontent.com/assets/6843/13529396/fdf066d0-e256-11e5-906a-29c1bc745f53.png)

**Comment by asampal** [comment]
I'm not clear what you're saying here - I need to do batch updates and I was using unnest() along with the `update` statement. Are you saying that the SQL I was using is not needed to do batch updates? The issue I raised had to do with Gorm not providing the proper data type to the statement (which expects a multi-valued type). 

Do you mean to say that the query you showed can be used with an `update` statement?

**Comment by jinzhu** [comment]
Hi @asampal 

Grom won't add the `array[]` for a slice, just like how it works for the `IN`.

**Comment by asampal** [comment]
So Gorm treats an array literal (what you used) differently than a slice or array reference? If yes, why does it do that?

**Comment by jinzhu** [comment]
GORM don't analyze your SQL, don't know when should we add the `array[]`, what it does is replace the `?` with its values.
