### ISSUE TITLE
UpdateColumns() ignores bool field when the value is false

### ISSUE THREAD

**Issue by basco-johnkevin** [jinzhu/gorm#876]
```
type EventPatch struct {
    Date time.Time
    Uneditable bool
}

var eventPatch EventPatch
eventPatch.Date = time.Now()
eventPatch.Uneditable = false

var event model.Event
if Db.First(&event, 1).RecordNotFound() {
    c.JSON(http.StatusNotFound, gin.H{
        "message": "Event doesn't exist.",
    })
    return
}

Db.Model(&event).UpdateColumns(eventPatch)
```

will generate this query: `UPDATE "event" SET "date" = '2016-01-01T09:00:00-06:00'  WHERE ("id" = '1')`

But if the value of eventPatch.Uneditable is true, this is the generated sql query: `UPDATE "event" SET "date" = '2016-01-01T09:00:00-06:00', "uneditable" = 'true'  WHERE ("id" = '1')`

**Comment by jinzhu** [comment]
there are couple of issues about this already, please search before post, also refer: http://jinzhu.me/gorm/curd.html#update
