### ISSUE TITLE
能否建立数据库？如何设置mysql字符集？

### ISSUE THREAD

**Issue by hoysoft** [jinzhu/gorm#877]
当数据库不存在时，能否自动建立数据库？
如何设置mysql数据表字符集？

**Comment by hoysoft** [comment]
字符集问题已解决 DB.Set("gorm:table_options", "ENGINE=InnoDB CHARSET=utf8")

**Comment by jinzhu** [comment]
数据库还是要自己建的，因为 connection 的时候就需要连接数据库。。。

**Comment by qjebbs** [comment]
gorm:table_options

**Comment by bluealert** [comment]
是的。文档太简略了。
