### ISSUE TITLE
db.FirstOrCreate() returns unmatched record when query value is empty string

### ISSUE THREAD

**Issue by danhardman** [jinzhu/gorm#880]
The following code is returning the first record in the table (ID: 1) when the query parameter is an empty string (`""`). 

    if err := config.DB.Where(model.Tag{Name: name}).FirstOrCreate(&tag).Error; err != nil {
		return err
	}

and

    if err := config.DB.FirstOrCreate(&tag, model.Tag{Name: name}).Error; err != nil {
		return err
	}

When `name == ""`, `db.FirstOrCreate()` returns the record with ID: 1, even though its `Name` value is not an empty string.

**Comment by jinzhu** [comment]
`config.DB.Where(model.Tag{Name: name})` there is no different with `config.Db.Where(model.Tag{})` when name is blank string, so it will return the first record.

If the name could be blank string, you should use `db.Where("name = ?", name).FirstOrCreate()` or `db.Where(map[string][string]{"name":""}).FirstOrCreate`
