### ISSUE TITLE
AddForeignKey - Error 1059: Identifier name is too long 

### ISSUE THREAD

**Issue by cristian-sima** [jinzhu/gorm#881]
Hi mates. I have a big problem.

I have the following structure of tables:

- a table `Company`
- a table `CompanyDetails `which has a reference to the `Company ` table, using the field `CompanyID`
- a table `InsuranceInstitution`

Now, I want to have a field called `InsuranceInstitutionID`, inside `CompanyDetails`

Thus, I set the following relation:

```
installer.Db.Model(&administrative.CompanyDetails{}).AddForeignKey("insurance_institution_id", "insurance_institution(id)", "RESTRICT", "CASCADE") 
```

I am getting this error:

```
[2016-03-03 19:15:22]  Error 1059: Identifier name 'company_details_insurance_inst_id_insurance_institution_id_foreign' is too long
```

Thus, I went to the [functions which creates the identifier](https://github.com/jinzhu/gorm/blob/0cf369dcff417ed51c8e439d8047f1b7503d87ce/scope_private.go#L621) and I can see it does the following:

``` 
var keyName = fmt.Sprintf("%s_%s_%s_foreign", scope.TableName(), field, dest)
keyName = regexp.MustCompile("(_*[^a-zA-Z]+_*|_+)").ReplaceAllString(keyName, "_") 

```

So, from this, I understand that the func ensures that the identifier is unique.

**The problem** is that the limit of the identifier is[ 64 characters as the documentation states](http://dev.mysql.com/doc/refman/5.5/en/identifiers.html).

Thus, I suggest to have a hash function which produces a unique hash. We can use the hash rather than the long identifier. 

[BCrypt ](https://godoc.org/golang.org/x/crypto/bcrypt)creates a hash of 60 characters which is enough to fill that.

@jinzhu  what do you think? Should I implement this?

**Comment by jinzhu** [comment]
Lets discuss it here #882
