### ISSUE TITLE
Where method convert the column name to lower case

### ISSUE THREAD

**Issue by zccaliDev** [jinzhu/gorm#885]
Db.Whare("categoryI(this is a upper case later)d = ?", id.(int)).Delete(&product)
error: the column categoryid is not exists

when column name changed to lower case in the database it working.

i'm using postgres 9.x

**Comment by jinzhu** [comment]
gorm won't auto convert the case, as it doesn't know it should be upper case or lower case.

**Comment by zccaliDev** [comment]
yeah that is true, i see in the log, but why th postgres returns this error of lowering the latter?
