### ISSUE TITLE
prepareQuerySql() as public method

### ISSUE THREAD

**Issue by nbgo** [jinzhu/gorm#886]
Can be `func (scope *Scope) prepareQuerySql()` made public as `CombinedConditionSql()`?

**Comment by jinzhu** [comment]
Hello @nbgo 

Could you let me know why you need it in a external package? also I am thinking to make `CombinedConditionSql` private

**Comment by nbgo** [comment]
I have a query with subquery where limiting option is used. So I wanted to get ready subquery sql statement text considering dialect.HasTop() and then insert this text into another more complex query. Now I have to check HasTop() flag manually. No a big a deal but it would be nice to reuse gorm logic.

**Comment by jinzhu** [comment]
@nbgo the `HasTop` method has been removed from `v1.0_branch`, how will you run the complex  query, with `gorm` or not? Or you could give me more details for what you want to do, to see if I could have better suggestion.

**Comment by nbgo** [comment]
This the logic where HasTop() is used currently:
```
func getActiveUnreadPrivateRooms(userID int64) ([]*models.Room, error) {
	var rooms []*models.Room

	const sqlQryTpl string =
	"is_private = ? and room.is_disabled = ? and " +
	"exists(select 1 from (select%v is_unread from message left join message_user_status on message.id = message_user_status.message_id " +
	"where message.room_id = room.id and message_user_status.user_id = ? order by message.timestamp desc%v) where is_unread = ?)"
	var sqlQryText string
	scope := models.Db.NewScope(models.Message{})
	if scope.Dialect().HasTop() {
		sqlQryText = fmt.Sprintf(sqlQryTpl, fmt.Sprintf(" top(%v)", numberOfLastMessagesToCheckForUnreadDecision), "")
	} else {
		sqlQryText = fmt.Sprintf(sqlQryTpl, "", fmt.Sprintf(" limit %v", numberOfLastMessagesToCheckForUnreadDecision))
	}

	err := models.Db.
	Select("id, name, is_main, is_private, owner1_id, owner2_id").
	Where(sqlQryText, true, false, userID, true).
	Find(&rooms).Error
	if err != nil {
		if !fail.IsError(err, gorm.RecordNotFound) {
			return nil, fail.NewErrWithReason(fmt.Sprintf("failed to get private unread rooms for user (ID=%v)", userID), err)
		}
	}
	return rooms, nil
}
```

**Comment by nbgo** [comment]
Not actual after Gorm 1.0 release.
