### ISSUE TITLE
.Related does not work with uuid keys.

### ISSUE THREAD

**Issue by i0n** [jinzhu/gorm#890]
Seem to be running in to a lot of trouble trying to use gorm with postgres (uuids as keys)
Either it's bugged or I'm doing something wrong (quite hard to find docs or examples on this)

This does not work:

```
type Domain struct {
	ID	        uuid.UUID	 `gorm:"primary_key;type:uuid;default:uuid_generate_v4()"`
	Pages	[]Page
}
type Page struct {
	ID               uuid.UUID	 `gorm:"primary_key;type:uuid;default:uuid_generate_v4()"`
	Domain      Domain
	DomainID   uuid.UUID	 `gorm:"type:uuid"`
}

domain := Domain{}
pages := []Page{}

db.First(&domain, id).Related(&pages)
```

`(sql: converting Exec argument #0's type: unsupported type uuid.UUID, a array)
`
However this does work:

```
db.First(&domain, id)
db.Where("domain_id = ?", domain.ID.String()).Find(&pages)
```

I am using `github.com/satori/go.uuid `for uuid.UUID type, but I have tried switching everything in the structs to strings (keeping uuid in postgres) and get similar results.

**Comment by jinzhu** [comment]
```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/postgres"
	"github.com/satori/go.uuid"
)

type Domain struct {
	ID    uuid.UUID `gorm:"primary_key;type:uuid;default:uuid_generate_v4()"`
	Pages []Page
}
type Page struct {
	ID       uuid.UUID `gorm:"primary_key;type:uuid;default:uuid_generate_v4()"`
	Domain   Domain
	DomainID uuid.UUID `gorm:"type:uuid"`
}

func main() {
	db, err := gorm.Open("postgres", "user=gorm DB.name=gorm sslmode=disable")

	if err != nil {
		panic(err)
	}
	db.LogMode(true)
	db.AutoMigrate(&Domain{})
	db.AutoMigrate(&Page{})

	domain := Domain{}
	pages := []Page{}
	db.Create(&domain)

	db.Model(&domain).Related(&pages)
}
```

Seems it works for me.

**Comment by EwanValentine** [comment]
I'm struggling to get UUID's working, my models struct is as followed... 

```
type User struct {
	ID        uuid.UUID `gorm:"primary_key;type:uuid;default:uuid_generate_v4()" json:"id"`
	FirstName string    `form:"first_name" json:"first_name,omitempty"`
	LastName  string    `form:"last_name" json:"last_name,omitempty"`
	Password  string    `form:"password" json:"password" bindind:"required"`
	Email     string    `gorm:"type:varchar(110);unique_index" form:"email" json:"email,omitempty" binding:"required"`
	Location  string    `form:"location" json:"location,omitempty"`
	Avatar    string    `form:"avatar" json:"avatar,omitempty"`
	BgImg     string    `form:"bg_img" json:"bg_img,omitempty"`
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt time.Time
}

func (user *User) BeforeCreate(scope *gorm.Scope) error {
	scope.SetColumn("ID", uuid.NewV4())
	return nil
}
```

I've tried it with or without `BeforeCreate` and haven't had any luck, without I get the following error: `(sql: Scan error on column index 0: uuid: cannot convert int64 to UUID)`.

**Comment by MohamedFAhmed** [comment]
@i0n @EwamValentine were you able to solve the UUID issue mentioned above?

**Comment by briankhdo** [comment]
I'm getting the same issue 

`type Campaign struct {
    gorm.Model
    ID           uuid.UUID `gorm:"primary_key;type:uuid;default:uuid_generate_v4()"`
    Name         string
    CreatedAt    time.Time
    UpdatedAt    time.Time
}`
and got
`sql: Scan error on column index 0: converting driver.Value type []uint8 ("e1d01f77-f557-4c5e-900f-661c11d30723") to a uint: invalid syntax`
everytime trying to get the first Campaign from the database, and the ID is always "00000000-0000-0000-0000-000000000000"

**Comment by ezk84** [comment]
It seems that support depends on the go UUID implementation you're using.

For me @jinzhu snippet works, but if i replace the UUID library with "github.com/twinj/uuid" for example, I get the `Scan error...` message.

**Comment by dalu** [comment]
Should one even use `uuid.UUID` over `string` as Go type?
