### ISSUE TITLE
Does .Error also throw an error if no update is made?

### ISSUE THREAD

**Issue by majimboo** [jinzhu/gorm#891]
In this statement, what errors are possible?

	if err := tx.Where(Character{Id: charId}).Where("slot = ?", 0).First(&char).Updates(map[string]interface{}{
		"name":       gorm.Expr("null"),
		"created_at": gorm.Expr("null"),
	}).Error; err != nil {
		tx.Rollback()
		return char, err
	}

I wish to check for any error, and also check if the entry does exist. For example, whats being updated `where name null and created_at null` is not found, so there is none to update. right?

So the question really is: Does it error when the entry is not found? I don't want to execute the queries after this one if this query doesn't update anything.

**Comment by jinzhu** [comment]
Refer: http://jinzhu.me/gorm/curd.html#batch-updates

You could get updated records count with `RowsAffected`

**Comment by majimboo** [comment]
But I'm already checking `.Error;` at the end. How do I check for `RowsAffected` too?

**Comment by jinzhu** [comment]
```go
results := db.Update("xxx")
results.Error
results.RowsAffected
```
