### ISSUE TITLE
Getting Started Guide

### ISSUE THREAD

**Issue by pjebs** [jinzhu/gorm#894]
The new getting started guide makes it hard to Search for content since it's not in 1 page anymore.

Can you please still keep the original readme up.

**Comment by jinzhu** [comment]
Hi @pjebs 

If you want to search it in one page, maybe godoc is a better choice? I also added documents for it.

https://godoc.org/github.com/jinzhu/gorm

**Comment by pjebs** [comment]
I use to search through examples for various "sql" patterns to find exactly what I wanted. GoDoc doesn't allow that.

**Comment by jinzhu** [comment]
I will add a separate document for this, or it is too difficult to maintain two documents.

**Comment by pjebs** [comment]
For future reference to anyone:

https://github.com/jinzhu/gorm/blob/f57198fe97b14fcd6ab9f689b51c7dc73e995386/README.md

You will have to compare with http://jinzhu.me/gorm/ for latest changes.
