### ISSUE TITLE
Warning When Updating Gorm

### ISSUE THREAD

**Issue by euller88** [jinzhu/gorm#895]
Hi, today I was updating all the library I have, then I saw that Gorm had been updated. So I did the following:

`~$ go get -u -v github.com/jinzhu/gorm`

Then I got the following message from the go tool:

```
github.com/jinzhu/gorm (download)
github.com/jinzhu/inflection (download)
github.com/jinzhu/gorm
# github.com/jinzhu/gorm
workspace/go/src/github.com/jinzhu/gorm/utils.go:137: syntax error: unexpected range, expecting {
workspace/go/src/github.com/jinzhu/gorm/utils.go:147: non-declaration statement outside function body
workspace/go/src/github.com/jinzhu/gorm/utils.go:148: syntax error: unexpected }
```

I still didn't tested it to see if harm my software, but I thought that was good to point this.

**Comment by jinzhu** [comment]
Maybe you could run it few times? might be your network's problem.

Or you could run:

```
cd $GOPATH/src/github.com/jinzhu/gorm/
git pull
```

**Comment by euller88** [comment]
I was using an older version of Go, then I updated to 1.6 and now works fine. Sorry for the false alarm.
