### ISSUE TITLE
mssql Dialect - Simple Select causes SQL Error

### ISSUE THREAD

**Issue by roXDesign** [jinzhu/gorm#899]
Hello

When I do: `db.First(&user)` with gorm and mssql driver I get 
`[2016-03-09 16:21:27]  mssql: Invalid usage of the option NEXT in the FETCH statement.`

Debug() reveals the query which does not work in MS SQL Dialect:
`[2016-03-09 16:21:27]  [2.49ms]  SELECT * FROM "User"   OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY`

Here the code:

```
type User struct {
    ID uint `gorm:"column:userId"`
    FirstName string `gorm:"column:nameGiven"`
    LastName  string `gorm:"column:nameFamily"`
    pin string `gorm:"column:pin"`
}

func (User) TableName() string {
    return "User"
}

func dbTest(res http.ResponseWriter, req *http.Request) {

    db, error := gorm.Open("mssql", "server=xxxx;user id=yyy;password=zzzz!;database=abcd")

    if error != nil {
        log.Println(error.Error())
        http.Error(res, error.Error(), http.StatusInternalServerError)
        return
    }

    var user User

    db.Debug().First(&user)

    fmt.Printf("%#v\n",user)
}
```

**Comment by kiwih** [comment]
Make sure you're importing the mssql dialect in addition to gorm -
You should have
`	_ "github.com/jinzhu/gorm/dialects/mssql" `
in your imports

**Comment by roXDesign** [comment]
Hello! Thanks for your response.

I did have the import statement of your dialect library. But what I noticed in the meantime is that this only happens with the First() statement - without a ID. Works fine with a id attached and other functions like Find() work as well.

If this is intended (i.e. no First statement without id) please close the issue.

**Comment by euforia** [comment]
In order to use the fetch next statements order by is required.

Per docs here: https://technet.microsoft.com/en-us/library/gg699618.aspx

**Comment by euforia** [comment]
Seems like this has been fixed on the master branch.  I am successfully able to perform the query.

**Comment by jinzhu** [comment]
We should fixed all issues for mssql, if you still have any problem, please create a new issue.

Thank you.
