### ISSUE TITLE
Cant find dialects

### ISSUE THREAD

**Issue by majimboo** [jinzhu/gorm#900]
data.go:8:2: cannot find package "github.com/jinzhu/gorm/dialects/postgres" in any of:
        C:\Go\src\github.com\jinzhu\gorm\dialects\postgres (from $GOROOT)
        c:\go\src\github.com\jinzhu\gorm\dialects\postgres (from $GOPATH)

**Comment by jinzhu** [comment]
Try to update your gorm to latest version. this should not be an issue of GORM, might be an issues of your environment

**Comment by mnvx** [comment]
@majimboo How you has fixed it?

**Comment by mnvx** [comment]
Solved. [It helped](https://github.com/kardianos/govendor/issues/340#issuecomment-317387402) me.

```bash
govendor fetch github.com/jinzhu/gorm/^
```
