### ISSUE TITLE
Questions in guides

### ISSUE THREAD

**Issue by clinyong** [jinzhu/gorm#901]
I am using gorm for few days, but still can not understand the guides well. Below is my first question

At [this](http://jinzhu.me/gorm/associations.html#belongs-to) setion

```go
// `User` belongs to `Profile`, `ProfileID` is the foreign key
type User struct {
  gorm.Model
  Profile   Profile
  ProfileID int
}

type Profile struct {
  gorm.Model
  Name string
}

db.Model(&user).Related(&profile)
//// SELECT * FROM profiles WHERE id = 111; // 111 is user's foreign key ProfileID
```

In `db.Model(&user).Related(&profile)`, what this means, to find user or profile or both? 

And the comment `SELECT * FROM profiles WHERE id = 111; // 111 is user's foreign key ProfileID` where does this come from?

**Comment by jinzhu** [comment]
```go
db.Model(&user).Related(&profile)
```
suppose `user` already been found, and it's id is `111`

```go
// find this user's related profile.
db.Model(&user).Related(&profile)
```
