### ISSUE TITLE
Is there a plan for gorm supporting the r/w split?

### ISSUE THREAD

**Issue by coseyo** [jinzhu/gorm#907]
I think gorm could add a feature for r/w split. That will be a useful feature for large web server.

**Comment by CpuID** [comment]
To clarify @coseyo - you mean providing 2 servers in the configuration, one for read only and one for (predominantly) writes?

**Comment by coseyo** [comment]
Yes. We could set a r/w database config array, and it could add some config param like round robin weight.

**Comment by dvdplm** [comment]
Sound like an app-level concern to me. What would the ORM library add vs just opening DB connections and send reads to one and writes to another?

**Comment by coseyo** [comment]
So it just be a extra feature. because grom could recognize the "select or update or transation" in the lower level, doing such things maybe easier.

**Comment by jinzhu** [comment]
Why not use a load balancer to do the job? like: http://agiletesting.blogspot.com/2009/04/mysql-load-balancing-and-read-write.html 

It is much more powerful and could do the job much better, like remove a slave serve if it is down...

Don't want to bring too much things into GORM, sometimes less means more ;)

**Comment by CpuID** [comment]
@jinzhu a load balancer still makes sense in the context of this issue, as the load balancer doesn't have sufficient intelligence to break out read only from read write traffic. you would use 2 load balancer endpoints (could be 2 ports on the same LB), one which has >1 slaves behind it for read only, and one that takes write traffic (either single master or multi master backends)

I think the LB aspect is unrelated to this feature request. But fair enough, if you would prefer to not add that level of "smarts" to GORM, ok :) Others can always fork and go down that road if it becomes crucial at least.

**Comment by jinzhu** [comment]
Mysql Proxy is smart enough to do the read/write splitting

**Comment by CpuID** [comment]
Oh, my bad sorry. I stand corrected :)

**Comment by coseyo** [comment]
The mysql-proxy is no longer updated and supported, it is a alpha version. And I had use ameba for a while, but it is not so reliable, some transaction were not atomic. So I think It may be much reliable and controllable doing the things in the app lower level.

**Comment by jinzhu** [comment]
Have you tried https://dev.mysql.com/doc/connector-j/en/connector-j-usagenotes-j2ee-concepts-managing-load-balanced-connections.html?

**Comment by jinzhu** [comment]
so this is no workable read/write load banalcer for mysql? I haven't use it personally, but think there should be some solutions for that.

**Comment by coseyo** [comment]
Of course there has it. Just like the kingshard, but it not support gorm for some orm grammar.

**Comment by jinzhu** [comment]
which grammar  is not supported?

**Comment by coseyo** [comment]
Well, the kingshard's author had fixed some related issue. Maybe I can have a try now, Thanks for replying :-)
