### ISSUE TITLE
AutoMigrate map string to text on PostgreSQL

### ISSUE THREAD

**Issue by slava-vishnyakov** [jinzhu/gorm#910]
Unlike MySQL - on PostgreSQL there is not much to win by using `varchar(255)`, it's better to use `text` type.

Can we make it a default so that strings produce `text` fields when `AutoMigrate` runs on PostgreSQL?

Also, I tried to do this:

```
	Name        string `gorm:"type:text"`
```

But on PostgreSQL it still created `character varying(255)`, am I doing it wrong?

Thanks!

**Comment by jinzhu** [comment]
Not sure about this, let me research, if yes, it is better to change the default type to text for postgres.

**Comment by slava-vishnyakov** [comment]
@jinzhu If it helps:
http://stackoverflow.com/a/4849030/37141

**Comment by jinzhu** [comment]
Cool, thank you.

**Comment by slava-vishnyakov** [comment]
Awesome! Thanks!
