### ISSUE TITLE
Multiple Updates using a single query

### ISSUE THREAD

**Issue by pjebs** [jinzhu/gorm#920]
In your documentation, you have a section for `Batch Updates`.

It seems a bit limited in that the value being updated has to be the same.

Can you please implement this:

UPDATE mytable SET title = CASE
WHEN id = 1 THEN ‘Great Expectations’
WHEN id = 2 THEN ‘War and Peace’
...
END
WHERE id IN (1,2,...)

http://blog.bubble.ro/how-to-make-multiple-updates-using-a-single-query-in-mysql/

**Comment by pjebs** [comment]
It allows us to set different values for different primary keys.

**Comment by pjebs** [comment]
`db.Table("users").Where("id IN (?)", []int{10, 11}).Update("title", []string{"Great Expectations", "War and Peace"})`

**Comment by pjebs** [comment]
`gorm.Expr`

**Comment by jinzhu** [comment]
Hi @pjebs 

This is not supported, and I think it would be better to use RawSql mode to do the job http://jinzhu.me/gorm/advanced.html#sql-builder

**Comment by pjebs** [comment]
I know it's not supported. I think it's a nice feature to add.

**Comment by pjebs** [comment]
I'm currently using `gorm.Expr`
