### ISSUE TITLE
model update异常

### ISSUE THREAD

**Issue by qiukeren** [jinzhu/gorm#923]
理论上，或者说理想中，Update应该是
db.Model(model.A{}).Where(" ? ? ? ",a,a,a).Update("status","success")，
db.Model(model.A{}).Where(" ? ? ? ",a,a,a).Updates(map[]{}{status,success})，
当然文档中并没有这种用法，但是按照常理是应该支持的…

实际上从debug模式中看到生成的SQL where部分一切正常，
只是update部分有一个问题，
变成了 update status = ""，
“success”没有传进去。

**Comment by jinzhu** [comment]
写个测试用例我看看？理论上应该可以的

**Comment by qiukeren** [comment]
写完整用例太麻烦……
大概的日志如下：
git变更为：
(build.go:425)
[2016-03-23 20:15:26]  UPDATE `build_task` SET `status` = ''  WHERE (order_id = '323' and env = 'pre' and isdeleted = 0)   《------生成的SQL出错，status并没有传进去

修复方案：

-db.Model(model.BuildTask{}).Where("app_id = ? and order_id = ? and env = ?", appid, orderid, env).Update("status", status)
+db.Table("build_task").Where("app_id = ? and order_id = ? and env = ?", appid, orderid, env).Updates(map[string]interface{}{"status": status})

**Comment by hui** [comment]
+1

遇到相同问题：

`
models.DB.Model(models.Post{}).Unscoped().Where("project_id = ? AND id = ?", project.ID, id).Updates(models.Post{Position: position})
`

不管position附什么值，都只会更新为0

**Comment by rand99** [comment]
english please :)

**Comment by qiukeren** [comment]
@rand99 


SQL log:

(build.go:425)
[2016-03-23 20:15:26]  UPDATE `build_task` SET `status` = ''  WHERE (order_id = '323' and env = 'pre' and isdeleted = 0)   <- generated SQL is wrong with the empty value("") of status



Changelog to avoid this :

-db.Model(model.BuildTask{}).Where("app_id = ? and order_id = ? and env = ?", appid, orderid, env).Update("status", status)
+db.Table("build_task").Where("app_id = ? and order_id = ? and env = ?", appid, orderid, env).Updates(map[string]interface{}{"status": status})

**Comment by rand99** [comment]
@qiukeren: thx. I ve reported the same issue yesterday :)

**Comment by qiukeren** [comment]
#946

**Comment by jinzhu** [comment]
已修复，参考：https://github.com/jinzhu/gorm/issues/946

不好意思，因为 issue 误报率太高，所以需要提交可复现代码，或者多人确认后我才会修复，谢谢。
