### ISSUE TITLE
Attaching Google App Engine Logger

### ISSUE THREAD

**Issue by pjebs** [jinzhu/gorm#924]
I'm having difficulty adding the Google App engine logger to gorm:

`db.SetLogger(log.New(os.Stdout, "\r\n", 0))` (your example)

https://godoc.org/google.golang.org/appengine/log#Criticalf

`import "google.golang.org/appengine/log"`

`log.Criticalf(ctx, "log this %s", "arg")` //func Criticalf(ctx context.Context, format string, args ...interface{})

**Comment by pjebs** [comment]
Also, it would be very handy if we can load the generated sql into a string.
I'm getting errors with sql statement on GAE but Debug() and Logger() writes to `stdout` and we don't have access to that on GAE.

**Comment by pjebs** [comment]
Here is a solution:

Change Debug so it accepts `sqlString ...*string`

That way the code is backwards compatible because if there is no argument passed into to `Debug()`, then the parameter slice will just be len = 0.

You can then check if there is a parameter i.e. 

var sqlString string
.Debug(&sqlString).

That will load sqlString with the generated sql string which I can then pass to the Google App Engine Logger.

**Comment by pjebs** [comment]
A similar approach can be done with the Logger()

**Comment by pedromorgan** [comment]
This is not a gorm issue, imho..

So closing this bug..

## BUT
If u got a good idea.. we can use in a patch

**Comment by pjebs** [comment]
How is this not a gorm issue? It's a feature request/expansion in functionality so I can get the generated sql string by giving a string variable as a parameter to the `Debug()` method.

Currently the generated string can't be accessed. It either prints the the standard logger or allows you to provide your own logger which then has to print.

Either way, it doesn't allow someone using Google App Engine to access the generated sql string. There may be other use cases too where this functionality will be handy.

**Comment by benguild** [comment]
+1 for this. Has anyone found a solution?

**Comment by pjebs** [comment]
Grabbing the generated sql as a string will also help create a caching layer

**Comment by benguild** [comment]
@pjebs What?

**Comment by pjebs** [comment]
I'm just saying if we can get the generated sql *with* the substituted values, we can save that string as the key and the values returned as the value in a cache. We can then check the cache if we have a value. If we do, then we take the value from cache rather than from the database.

**Comment by pjebs** [comment]
All the action happens at this point: https://github.com/jinzhu/gorm/blob/master/scope.go#L927

**Comment by benguild** [comment]
@pjebs @jinzhu Have you seen this? http://www.captaincodeman.com/2015/03/05/dependency-injection-in-go-golang/ ... Would wrapping the GAE methods/context with a custom logger solve this?

**Comment by benguild** [comment]
I've fixed this and will be posting code shortly.

**Comment by benguild** [comment]
Problem solved: https://github.com/benguild/GAEBridge

```
db.LogMode(true);
db.SetLogger(log.New(gaebridge.DebugLogWriter{ gaebridge.Context(r) }, "", log.LstdFlags));
```

**Comment by benguild** [comment]
@jinzhu I think this can probably be closed. @pjebs If you have any issues with that please send a PR to the repo or contact me directly. This doesn't seem to be related to GORM, and if the other issue above would help in some other way then maybe create another issue referencing this one.

**Comment by pjebs** [comment]
Great work @benguild . Can you put `// +build appengine` on the top of each file.

I still want to keep this open because I still want to get the generated sql string for caching purposes.

**Comment by benguild** [comment]
That sounds like it might be related to #1030 that I just posted. Do you want to take up that discussion there? This issue thread is specifically titled for GAE logging.

I'll add your comment to the beginning of each file now.

**Comment by benguild** [comment]
Suggesting this be closed and/or another new specific discussion started.

**Comment by pjebs** [comment]
I'll change the title after I test your library.
I don't think `context.go` does what it's meant to do.
You'll need to copy Gorilla Context's design: https://github.com/gorilla/context/blob/master/context.go#L16

mutex sync.RWMutex
data  = make(map[*http.Request]*context.Context)

**Comment by benguild** [comment]
It's the App Engine context. You have to create only one and pass it around. It's tested and working for me but feel free to send a PR. 



On Sat, May 21, 2016 at 9:33 PM -0700, "pjebs" <notifications@github.com> wrote:












I'll change the title after I test your library.

I don't think context.go does what it's meant to do.

You'll need to copy Gorilla Context's design: https://github.com/gorilla/context/blob/master/context.go#L16



mutex sync.RWMutex

data  = make(map[http.Request]context.Context)

**Comment by pjebs** [comment]
I guess your way *would* work if you use it as per your example - 1 gaebridge.DebugLogWriter &gaebridge.Context(r) per request but it's not as robust as protecting it properly in case someone does something that differs from your example code.

**Comment by benguild** [comment]
@pjebs No worries, if you think of a better solution for the same issue please feel free to send a PR. I'm trying to finish up a bunch of other stuff but am always looking to improve the code.

**Comment by pjebs** [comment]
@benguild I fixed up goroutine and general concurrency protection.

**Comment by benguild** [comment]
Cool, will check it out. Are you OK to close this issue or split it into something else? Could also be renamed/edited.
