### ISSUE TITLE
struct tag support for CHECK constraints?

### ISSUE THREAD

**Issue by klauern** [jinzhu/gorm#926]
Is it possible to implement support for struct tags to allow check constraints?  Something like this:

```go
type Disruption struct {
	gorm.Model
	Completed time.Time `gorm:"default:0"`
	Cluster   string
	Type      string
	Duration  time.Duration `gorm:"CHECK(Duration > 0)"`
	Why       string
}
```

I'm currently using SQLite3 and their version of [`table-constraint`](https://www.sqlite.org/syntax/table-constraint.html), so I'm not sure how portable this, but I would like to implement this at the database-level if possible, rather than putting a random `if` statement in my code.

**Comment by klauern** [comment]
To add to this, I see in the [documentation](http://jinzhu.me/gorm/database.html#modifycolumn) that there's a way to change a column in a table, so being able to add different checks and constraints would be something I'd like to do.  Is there some document explaining the options for `ModifyColumn`?:

```go
db.Model(&User{}).ModifyColumn("description", "text")
```

**Comment by jinzhu** [comment]
Hi @klauern

You could use tag like `gorm:"type:integer CHECK(Duration > 0)"` to initalize a model also.
