### ISSUE TITLE
gorm:"type:varchar(36)" doesn't work on mysql

### ISSUE THREAD

**Issue by yuklai** [jinzhu/gorm#929]
when i add the above tag to a uuid field, mysql table still use varchar(255):
```
+-------------------------+--------------+------+-----+---------+-------+
| Field                   | Type         | Null | Key | Default | Extra |
+-------------------------+--------------+------+-----+---------+-------+
| uuid                    | varchar(255) | YES  |     | NULL    |       |
```
when i use the tag `sql:"type:varchar(36)"` then it finally worked as expected. known issue?

**Comment by jinzhu** [comment]
Hi @yuklai 

I think you are not using latest GORM?

I just tested with latest GORM, which should works.

**Comment by yuklai** [comment]
I think I'm using an older version from a month or two ago. Will update and try. Thank you @jinzhu !
