### ISSUE TITLE
Docs referencing wrong Struct Tag

### ISSUE THREAD

**Issue by diogogmt** [jinzhu/gorm#931]
In the Model definition document it says to ignore a field the Struct Tag ``` `gorm:"-"` ``` must be set.
http://jinzhu.me/gorm/models.html#model-definition

However, after checking the source code it seems that the Struct tag ``` sql:"-"` `` must be set to ignore fields.

Where is the code for the documents stored?

**Comment by jinzhu** [comment]
Are you using an old version gorm?
