### ISSUE TITLE
gorm.Open error 

### ISSUE THREAD

**Issue by ptarpan** [jinzhu/gorm#933]
Hello,
I am new to gorm and am just getting started. Here's my code to test connectivity to the db: 

package main

import (
	"fmt"

	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mssql"
)

func main() {
	db, err := gorm.Open("mssql", "user=testuser password=testpass dbname=testdb host=ipofdb sslmode=disable")
	if err != nil {
		panic(fmt.Sprintf("Got an error when connecting to the database, '%v'", err))
	}

	defer db.Close()
} 

Upon running main, an error immediately gets thrown as follows: 
panic: Got an error when connecting to the database, 'Unable to open tcp connection with host 'localhost:1433': dial tcp 127.0.0.1:1433: connection refused'. 

Could someone tell me what I'm doing wrong?

**Comment by pedromorgan** [comment]
Seems your host=localhost=ipofdb

MsSql is probably not running on your server..

**Comment by ptarpan** [comment]
thanks for replying @pedromorgan. so, the db i'm connecting to is in the cloud (AWS). I can successfully connect to it using a sql client and the cli but I need to confirm the same using gorm/go. Here is what I mean: 

telnet ipofdb 1433
Trying ipofdb...
Connected to ipofdb.

does something in my config still appear incorrect?

**Comment by pedromorgan** [comment]
I cannot comment on the "config connection string" as I dont use mssql anymore..

But the error message gives a hint..
   'Unable to open tcp connection with host 'localhost:1433': dial tcp 127.0.0.1:1433: connection refused'.

So gorm is trying to connect to 127.0.0.1.. whether that is running on your local machine or "on remote server" is probably the problem

**Comment by ptarpan** [comment]
I'm going to use sql.Open() instead of gorm.Open() because for some odd reason the latter does not seem to work.
