### ISSUE TITLE
Transaction usage???

### ISSUE THREAD

**Issue by Yuhang** [jinzhu/gorm#935]
Hello, we use gorm in product env now, and I have some usage problem with transaction.

we init a db map like 
dbs map[string]*gorm.DB

so we can get dbs[tableName] for each tableName.
we do only once to set dbs[tableName] = gorm.Open(...)

Now we want to do some transaction operation, as we tested, if use dbs[tableName] directly, it looks like not a transaction.
So we have to use a new gorm.Open(...) to Begin Transaction.

Any further guide?  Thanks.

Or we should gorm.Open(...) every time when we need a gorm.DB instance?

**Comment by jinzhu** [comment]
why this `dbs[tableName] = gorm.Open(...)`?

just have one connection should be ok?

**Comment by Yuhang** [comment]
no, if only use one db instance, it's not transaction.
log like:

Begin
Begin
Commit
Commit.

but if use a new gorm.open(...),
it looks right:
Begin
Commit
Begin
Commit/Rollback

**Comment by Yuhang** [comment]
append some text to last reply.

I have to use gorm.Open(...) for every transaction.

**Comment by Yuhang** [comment]
different table on different db, so we use a map to encapsulate

**Comment by jinzhu** [comment]
refer: https://github.com/jinzhu/gorm/issues/307

different models on different dbs
