### ISSUE TITLE
feature require

### ISSUE THREAD

**Issue by Yuhang** [jinzhu/gorm#936]
last insert id required.
in scope.go

	// Exec perform generated SQL
	func (scope *Scope) Exec() *Scope {
		defer scope.trace(NowFunc())

		if !scope.HasError() {
			if result, err := scope.SQLDB().Exec(scope.SQL, scope.SQLVars...); scope.Err(err) == nil {
				if count, err := result.RowsAffected(); scope.Err(err) == nil {
					scope.db.RowsAffected = count
				}
			}
		}
		return scope
	}

**Comment by Yuhang** [comment]
or please tell me how to get it when use db.Exec("insert...")

**Comment by jinzhu** [comment]
Are you using Exec to run a `INSERT` SQL? You could use `Raw` with `Row` to get the result.
