### ISSUE TITLE
如何创建pg的gin索引?

### ISSUE THREAD

**Issue by fhbzyc** [jinzhu/gorm#937]
我有个字段是jsonb的 想要建表的时候 字段带上gin索引
有什么办法?

**Comment by fhbzyc** [comment]
另外  `gorm:"-"` 忽视字段不管用啊 试了好多次

**Comment by fhbzyc** [comment]
自问自答吧
索引的直接写SQL了
忽视字段文档有错 要用 `sql:"-"`

**Comment by jinzhu** [comment]
更新 gorm，可以用 gorm:"-"
