### ISSUE TITLE
Using non-int as primary key issues

### ISSUE THREAD

**Issue by yuklai** [jinzhu/gorm#943]
Hi there, 
I type def'd a string to UUID, i.e. 
```
type UUID string
```

Then I used the UUID type in model, i.e. 
```
type User struct {
    uuid UUID `sql:"type:varchar(36)" gorm:"primary_key"`
}
```

However, gorm doesn't like that: 
```
&errors.errorString{s:"sql: converting Exec argument #6's type: unsupported type models.UUID, a string"
```

Am I looking for trouble here? :)

**Comment by yuklai** [comment]
Also, even after I changed it into string, gorm doesn't seem to actually save a model if it doesn't have an int primary key...

**Comment by jinzhu** [comment]
Search history issues would help you ;)

Refer:  https://github.com/jinzhu/gorm/blob/master/CONTRIBUTING.md
