### ISSUE TITLE
CreateColumn function in migration

### ISSUE THREAD

**Issue by MohamedBassem** [jinzhu/gorm#944]
Hello,

I wonder why there isn't any `CreateColumn` in the migration section although there's `DropColumn` and `ModifyColumn`. I know that `AutoMigrate` will create it for me, but I'm building a migration system, and If it one step I auto migrated to the latest version, maybe later migrations will break. I'd love to have the ability to create the columns I want on my own not by AutoMigrate. Is this possible?

Thank you.

**Comment by jinzhu** [comment]
Hi @MohamedBassem 

Suggest you write raw SQL for this then, or use more advanced migration tool.

**Comment by pedromorgan** [comment]
I'm using RAW sql because there is no `CreateColumn()`

My columns are "dynamic" with dates as names eg "may_2016_123" (dont ask why)...

**Comment by jpascal** [comment]
`CreateColumn` - really needed for migrations.
