### ISSUE TITLE
model update doesn't set values 

### ISSUE THREAD

**Issue by rand99** [jinzhu/gorm#946]
it does with .Table but I think it should with .Model too

	DBcon.Debug().Table("users").Where("ID =?", test_user_id).Updates(map[string]interface{}{"notify_tkn": "shittytoken", "notify_via": "a"})
    [2016-04-04 00:36:07]  [0.39ms]  UPDATE `users` SET `notify_tkn` = 'shittytoken', `notify_via` = 'a'  WHERE (ID ='UserUserUserUserUser01')

	DBcon.Debug().Model(User{}).Where("ID =?", test_user_id).Updates(map[string]interface{}{"NotifyTkn": "shittytoken", "NotifyVia": "a"})
    [2016-04-04 00:36:07]  [0.37ms]  UPDATE `users` SET `notify_tkn` = '', `notify_via` = '', `updated_at` = '2016-04-04T00:36:07+02:00'  WHERE (ID ='UserUserUserUserUser01')

	DBcon.Debug().Model(User{}).Where("ID =?", test_user_id).Updates(User{NotifyTkn: "shittytoken", NotifyVia: "a"})
    [2016-04-04 00:36:07]  [0.37ms]  UPDATE `users` SET `notify_tkn` = '', `notify_via` = '', `updated_at` = '2016-04-04T00:36:07+02:00'  WHERE (ID ='UserUserUserUserUser01')

UPDATE:
I forgot to note, that this used to work.
I reverted back to, because I would have to change all the code to .Table to make my app work again.
 .Table has a disadvantage, when a models attribute is changed all queries need be refactored by hand, while attribute names in 

    DBcon.Debug().Model(User{}).Where("ID =?", test_user_id).Updates(User{NotifyTkn: "shittytoken", NotifyVia: "a"})

would change automatically.

working version for those who upgraded and have problems (getgb.io)

   			"importpath": "github.com/jinzhu/gorm",
			"repository": "https://github.com/jinzhu/gorm",
			"revision": "aa45da15421ddb1549a7060e5c189f8350a29166",
			"branch": "master"

**Comment by jinzhu** [comment]
Hi @rand99

The `User{}` should be addressable,  so you need to write code like this:

`db.Model(&User{}).Update(...)`, then it should works.

But anyway, I have pushed a commit to fix the issue, you should fine now, but still prefer you to make the change, especially when you are updating an existing record like this:

`db.Model(&user).Update(...)`, this will update the data in database, and update the record's value `user` as it is addressable

**Comment by rand99** [comment]
Thx! 

I feels nice to be able to use a pointer for a user-Instance that was loaded
and just the the model with a where(ID=1).updates(y)
