### ISSUE TITLE
RecordNotFound not working

### ISSUE THREAD

**Issue by pjebs** [jinzhu/gorm#950]
`cePivots := []m.CustomerEventPivot{}
	if err := gorm.Where("event_id = ?", eventId).Where("registered_time IS NOT NULL").Where("preferences IS NOT NULL").Find(&cePivots).Error; err != nil {

		if err == g.RecordNotFound {
`

I run a query which should return RecordNotFound error.
For some reason it doesn't, hence I must check if the len(cePivots) is 0.

is this a bug?

**Comment by jinzhu** [comment]
RecordNotFound error will only raise when find with struct, but not slice. it is an expected behaviour
