### ISSUE TITLE
Nested items aren't present in Before/AfterDelete

### ISSUE THREAD

**Issue by Salandar** [jinzhu/gorm#953]
Hello,

I have a struct within a nested struct.
My struct and nested ones are well filled.

When I call the Delete() function, my first level item is filled, however, all nested items are now empty.

Here is my code if you want to try : 
[gormSample.txt](https://github.com/jinzhu/gorm/files/206701/gormSample.txt)

Thanks for your great work !

Best regards

**Comment by pedromorgan** [comment]
Can u exmplain more with some code see

https://github.com/jinzhu/gorm/blob/master/CONTRIBUTING.md

If u suffer same problemm then please re-open

But for now I apoologise for closing this bug for TRFM reasons
