### ISSUE TITLE
batch update with Model got error sql

### ISSUE THREAD

**Issue by wxf4150** [jinzhu/gorm#954]
err=Orm.Debug().Model(jpman.JPApply{}).Updates(map[string]interface{}{"RejectDes":"test"} )
got next sql:
[2016-04-08 12:04:09]  [5.50ms]  UPDATE "MK_JiPinProductApply" SET "RejectDes" = ''  ;

and 
 Orm.Debug().Table("MK_JiPinProductApply")..Updates(map[string]interface{}{"RejectDes":"test"} )
got the right sql output

 i use sqlserver driver

**Comment by wxf4150** [comment]
Model(jpman.JPApply{RejectDes:"test1",Status:4}).Where(amode.Pids).Updates(map[string]interface{}{"RejectDes":"test","Status":14} 
go  next sql:
 [2016-04-08 13:20:58]  [40.09ms]  UPDATE "MK_JiPinProductApply" SET "RejectDes" = 'test1', "Status" = '4'  WHERE ("ProductId" IN ('328872','328871'))

the parameter value in the Model(**struct**)   is used.   the value in Updates(**map[string]interface**) not used

**Comment by pedromorgan** [comment]
Can u please supply a runnign example..
But for now I close this bug and reopen please...
