### ISSUE TITLE
 Scan error on column index 4: unsupported Scan

### ISSUE THREAD

**Issue by wyq756543431** [jinzhu/gorm#958]
![code](https://cloud.githubusercontent.com/assets/3364128/14423271/849ca8e6-000d-11e6-95c0-9e7b486dae0c.png)
-----------------------------------
![code1](https://cloud.githubusercontent.com/assets/3364128/14423325/d5025768-000d-11e6-8aae-493997943551.png)

2016/04/11 17:40:21 http: panic serving 127.0.0.1:56089: sql: Scan error on column index 4: unsupported Scan, storing driver.Value type []uint8 into type *time.Time

why? bug?

**Comment by lukanus** [comment]
I guess you need to add proper parameter to your connection string. (?parseTime=true)
https://github.com/Go-SQL-Driver/MySQL/issues/9

**Comment by pedromorgan** [comment]
Am closing this, if its still a bug then please re-open

**Comment by wyq756543431** [comment]
I  solved the problem with add ?parseTime=true，  thank you ！

**Comment by codepushr** [comment]
What about postgres?

**Comment by gueluelue** [comment]
This great article nicely explains the problem and offers solutions for MySQL and Postgres:  https://medium.com/aubergine-solutions/how-i-handled-null-possible-values-from-database-rows-in-golang-521fb0ee267

**Comment by Momo733** [comment]
![cw q 850 60 72 nz l](https://user-images.githubusercontent.com/25858316/40404688-b9370086-5e8b-11e8-9623-863747a006ee.png)
![y 2d66 d 5rv 1u zlx2_1](https://user-images.githubusercontent.com/25858316/40404689-b9690e5a-5e8b-11e8-9f9f-a9e44e0106a5.png)

I have set parseTime = true，but it does not work.why?

**Comment by zhguokai** [comment]
i have the same problem,but it doesn't work by add  ?parseTime=true to the mysql connection
