### ISSUE TITLE
'DB()' method panics on a started transaction

### ISSUE THREAD

**Issue by sevlyar** [jinzhu/gorm#960]
```go
func TestGorm(test *testing.T) {
	db := gorm.Open("postgres", os.Getenv("DATABASE_URL"))
	defer db.Close()
	tx := db.Begin()
	defer tx.Rollback()

	// This call panics with 
	// 'panic: interface conversion: gorm.sqlCommon is *sql.Tx, not *sql.DB'
	connection := tx.DB()

	connection.Ping()
}
```

**Comment by pedromorgan** [comment]
It should do an fulfils prupse.. IT panics on a test.. which is what we want init ??

**Comment by benguild** [comment]
Did you guys manage to work around this? I'm getting this error as well, from trying to call a raw SQL `.Exec()` on an open transaction, while getting access to `.LastInsertId()`?

**Comment by benguild** [comment]
Hmm, this seems to work:
`tx.CommonDB().Exec();`

... Can you verify that this is the correct approach?
