### ISSUE TITLE
feature: WHERE IN query support for composite keys

### ISSUE THREAD

**Issue by rand99** [jinzhu/gorm#964]
at the moment i'm getting this error

sql: converting Exec argument #0's type: unsupported type []string, a slice 

as composite keys generally are supported WHERE IN support would be nice

sample code:

```
composite_keys := [][]string{{"1","1","en"},{"1","2","en"}}
query := DBcon.Debug().Where("(id, version, lang) in (?)", composite_keys).Find(&objs)
```

**Comment by pedromorgan** [comment]
Guess we need a few "votes" to get this "dream in there"
