### ISSUE TITLE
cannot allocate memory

### ISSUE THREAD

**Issue by glenfordwilliams** [jinzhu/gorm#966]
not sure y but trying to build my project i keep getting this error
 ```
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory
```

removing  the following solves my issue but i need the import 
```
 import  _ github.com/jinzhu/gorm/dialects/sqlite"
```

**Comment by pedromorgan** [comment]
That is a stange error..

Maybe u are using custom install fo go and paths and 
PATH and GO_PATH etc are messed up 

Please open this if it still fail.. or say -1 to being closed
