### ISSUE TITLE
test failure: TestScannableSlices "cgo argument has Go pointer to Go pointer"

### ISSUE THREAD

**Issue by onlyjob** [jinzhu/gorm#967]
As reported in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819641
_TestScannableSlices_ fails on Golang 1.6:

```
--- FAIL: TestScannableSlices (0.00s) 
panic: runtime error: cgo argument has Go pointer to Go pointer [recovered] 
        panic: runtime error: cgo argument has Go pointer to Go pointer 
```

Apparently Go pointer to Go pointer is no longer allowed: https://github.com/golang/go/issues/12416

**Comment by onlyjob** [comment]
It would be great if this problem could get some attention please...

**Comment by yanxiaoliang** [comment]
It exists in Golang 1.7 too.

**Comment by yanxiaoliang** [comment]
Found a temp way,
Run **export GODEBUG=cgocheck=0** before you build it.
