### ISSUE TITLE
Structs as columns

### ISSUE THREAD

**Issue by ckedwards** [jinzhu/gorm#968]
I was wondering if there was a way that the items in a struct could be used as column names rather than a has one association?

Example:
type Content struct {
    ItemsStatus ItemsStatus
}

type ItemsStatus struct {
    ItemA string
    ItemB string
    ItemC string
}

I wanted to make ItemsStatus a separate struct so that the JSON I produced in my REST api looks JSON-like. In this case I would like to see columns like items_status_item_a etc in my "content" table rather then creating a whole new table/join for a small set of values. Is this possible?

**Comment by thomasmcgee** [comment]
I have the same question, I was hoping to see this case answered in the documentation. Also - fantastic library, thank you for the amazing work!

**Comment by tjmcgee** [comment]
I thought maybe something like this could work, but it doesn't seem to `gorm:"polymorphic:time.Time;type:timestamp;column:starts_at;"`

**Comment by thomasmcgee** [comment]
I'm going to look at the callbacks, seems hackneyed though.

**Comment by jinzhu** [comment]
It could be a `Scanner`, `Valuer` like `NullString`
