### ISSUE TITLE
Update call updates all fields but it should update only the changed ones

### ISSUE THREAD

**Issue by rghose** [jinzhu/gorm#969]
The problem we faced was:

We are running multiple reading and writing workers from a database and sometimes they tend to run into a race condition when 2 or more workers are trying to update the same row.

If thead1, 2 both read the same data and they then write, we have a race:

Read by thread 1
Read by thread 2
Write by thread <any>
Write by thread <other> => Data is corrupted here, since  it has stale data which it has read and effectively the data written by the earlier threads are lost.

**Comment by jinzhu** [comment]
Are you using latest gorm? refer: http://jinzhu.me/gorm/curd.html#update
