### ISSUE TITLE
Feature Request: Add support for DISTINCT when using Count() method

### ISSUE THREAD

**Issue by basco-johnkevin** [jinzhu/gorm#970]
Would be great if its possible to use DISTINCT when using the Count() method.

A use case is discussed here: https://github.com/jinzhu/gorm/issues/853

Since its currently not possible to use DISTINCT with Count(), we will be forced to rewrite the code using a raw query. We will lose the benefits of using GORM's features like Preload() etc...

**Comment by sungwoncho** [comment]
A possible solution: https://github.com/jinzhu/gorm/pull/1120#issuecomment-239659728

I ended up doing something like:

    db.Where("id = ?", id).Select("count(distinct(companies.id))").Count(&companyCount)

**Comment by Fyb3roptik** [comment]
Thank you for the above! That worked great. No idea why we cannot get this feature implemented!
