### ISSUE TITLE
UpdatedAt 更新时区问题

### ISSUE THREAD

**Issue by xiaoshengaimm** [jinzhu/gorm#971]
测试中发现model里定义的updated_at, created_at更新均是0时区，即使自定义NowFunc()函数一样出现该问题。求答：

```
gorm.NowFunc = func() time.Time {
        t := time.Now()
        return t
    }
```

在NowFunc中尝试打印 time.Now().String()，为北京时间，但是更新到数据库里为0时区时间。为何？

**Comment by webluoye** [comment]
&loc=Asia%2FChongqing 连接DB的参数有没有加这个

**Comment by LeSou** [comment]
连接字符串增加&loc=Local即可
