### ISSUE TITLE
about select for update in transactions

### ISSUE THREAD

**Issue by webluoye** [jinzhu/gorm#972]
tx := db.Begin()
for _,v:=range dns{
   go updateDb(v,tx)
}

func update(dn string,tx *gorm.DB){
    ok := []string{} 
    a:= abcTable{}
     tx.Find(&a)
    for _,v:=a range{
        ok=append(ok,v.name)
    }
}

but get error for packets.go  Busy buffer

**Comment by pedromorgan** [comment]
Please provide a full traceback etc.. and repopen please if still and issue
