### ISSUE TITLE
`SingularTable` not honored in Model().Updates() ?

### ISSUE THREAD

**Issue by randomandy** [jinzhu/gorm#975]
So let's assume I have something like this

```
type Foobar struct {
    gorm.Model
    Name string
}
```

....

```
var foo Foobar
db.SingularTable(true)
db.Model(&foo).Updates(Foobar{Name: "some_string"})
```

This will throw an error like:
`(pq: relation "foobars" does not exist)`

So my guess would be that currently `db.SingularTable(true)` is not being honored when calling `db.Model().Updates()`? Or maybe I just made a mistake here?

**Comment by pedromorgan** [comment]
Have u got test code..

**Comment by djkaty** [comment]
Can confirm I had this same problem today.

Code:

```
type Account struct {
	LastOnline    utils.NullTime
// other stuff elided
}


...
db, err := gorm.Open("sqlite3", dbFile)
db.SingularTable(true)
db.Model(Account{}).Where("last_online IS NULL").Updates(Account{ LastOnline: now })
```

Produces:

no such table: accounts

**Comment by vrparmar** [comment]
I have encounter same issue. Is there any resolution available?

**Comment by jinzhu** [comment]
Can't reproduce this on my local

```go
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

type Account struct {
	gorm.Model
	Name string
}

func main() {
	db, _ := gorm.Open("sqlite3", "/tmp/gorm.db")

	db.LogMode(true)
	db.SingularTable(true)

	db.DropTable(&Account{})
	db.AutoMigrate(&Account{})
	db.Model(Account{}).Updates(Account{Name: "hello"})
}
```

![image](https://cloud.githubusercontent.com/assets/6843/22532770/531c0d42-e924-11e6-9163-0e9f4bd90d36.png)

**Comment by djkaty** [comment]
You can't reproduce it so you close the issue? This was filed in April last year and still hasn't been fixed 9 months later.

**Comment by jinzhu** [comment]
> You can't reproduce it so you close the issue? 

So?

> This was filed in April last year and still hasn't been fixed 9 months later.

Most issues not following our guide https://github.com/jinzhu/gorm/blob/master/CONTRIBUTING.md, and most of them are misreported because they just don't read the document...

Please respect our time, if you try to proven your issue with a runnable script or create a PR, you will be appreciated.

**Comment by vrparmar** [comment]
It fails to honor SingularTable when the first call is Model().Updates(). Issue can be reproduce using the following code,

```
package main

import (
	"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

type Account struct {
	gorm.Model
	Name string
}

func main() {
	db, _ := gorm.Open("sqlite3", "/tmp/gorm2.db")

	db.LogMode(true)
	db.SingularTable(true)

	//db.DropTable(&Account{})
	//db.AutoMigrate(&Account{})
	db.Model(Account{}).Updates(Account{Name: "hello"})
}
```

**Comment by jinzhu** [comment]
Hi @vrparmar 

Thank you for your script, fixed that.

**Comment by vrparmar** [comment]
It works!!!

Thanks for quick response.
