### ISSUE TITLE
mysql 5.7版本，不支持单独的offset语句

### ISSUE THREAD

**Issue by guotie** [jinzhu/gorm#976]
例如 

```
 select * from users offset 10;
```

会报错：

```
 SQL错误（1064）：You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '10' at line 1
```

需要写成这样：

```
select * from users limit 10, 18446744073709551615;
```

参考：

http://dev.mysql.com/doc/refman/5.7/en/select.html

**Comment by guotie** [comment]
To retrieve all rows from a certain offset up to the end of the result set, you can use some large number for the second parameter. This statement retrieves all rows from the 96th row to the last:

**Comment by pedromorgan** [comment]
whats the situation with postgres, sqlite, m$sql ??

**Comment by guotie** [comment]
mysql

**Comment by jinzhu** [comment]
Should be fixed.
