### ISSUE TITLE
can we have a different table name other than pluralized version of struct name?

### ISSUE THREAD

**Issue by seaguest** [jinzhu/gorm#977]
Hello,

I would like to have a different table name other than pluralized version of struct name.
For example, I have a stuct:

type Person struct {
	Id      []byte `gorm:"primary_key;size:16"`
	Name    []byte `gorm:"size:16"`
}

but I don't want the table name to be persons, is it possible to map the table to Table_Person?

is this feature on schedule?

**Comment by pedromorgan** [comment]
This is a settings in gorm..

options are 
- use the TableName() function...

**Comment by pedromorgan** [comment]
http://jinzhu.me/gorm/models.html#model-definition

Look down for "plural version"...

This pissed me off also cos an "s" is not a plurar..."

eg 
my aircraft
the aircrafts i have
and aircraft in my fleet

vs
my aircraft
the aircraft
and aircraft in my fleet

dont even like extending the s anymore.. causes more pain that a singular..

**Comment by pedromorgan** [comment]
@seaguest The pains of using an ORM ;-)))

**Comment by DipinVasu** [comment]
@seaguest Disable table name's pluralization globally by following setup and create desired struct name 

db.SingularTable(true)
