### ISSUE TITLE
[Feature request] Set schema for request

### ISSUE THREAD

**Issue by alexroot-** [jinzhu/gorm#980]
Hi,
I'm working in a team on a project using Postgres. We need to set a Schema for a Request, using search path won't work cause setting the path withing one thread will screw any other request from other threads. Unfortunately we don't know how to implement that in a clean way. I'm pretty new to Go so please forgive that noobish request.

Kind regards

**Comment by ChaosLeader** [comment]
Would love that feature, too. Currently doing it via `set scema 'name'`, but it's not a very clean way and I already ran into some problems because of this.

Would really appreciate such a feature.

Greetz Chaos

**Comment by alexroot-** [comment]
nvm, added it myself. Was easy to do. Will make a pull request after more tests
greetz
