### ISSUE TITLE
Query First is not taking the id?

### ISSUE THREAD

**Issue by seaguest** [jinzhu/gorm#981]
Hello,

When I try to do a First query with PK id, it seems the id is not taken into account.

Here is my code:

```
type Model struct {
	Id  string `gorm:"primary_key;size:16"`
	Url string
}

// set User's table name to be `profiles
func (Model) TableName() string {
	return "TL_Model"
}

func (user *Model) BeforeCreate(scope *gorm.Scope) error {
	scope.SetColumn("ID", uuid.New())
	return nil
}

func initModel(db *gorm.DB) error {
	var err error

	if db.HasTable(&Model{}) {
		err = db.AutoMigrate(&Model{}).Error
	} else {
		err = db.CreateTable(&Model{}).Error
	}

	return err
}
```

Test code:
```
	sid := "abc"
	var dm Model
	if db.First(&dm, sid).Error != nil {
		fmt.Println(err)

	}
	fmt.Printf("%+v \n", dm.Url)
```

I have enabled the detailed log mode for gorm, I do get the following SQL query
`SELECT * FROM `TL_Model`  WHERE (abc) ORDER BY `TL_Model`.`id` ASC LIMIT 1`

Why it won't take the id?
it should be 
`SELECT * FROM `TL_Model`  WHERE (id in ('abc')) ORDER BY `TL_Model`.`id` ASC LIMIT 1;`

If I use where first then it works
`if db.Where("id = ?", sid).First(&dm).Error != nil `

Could anyone help?

**Comment by jinzhu** [comment]
you need to search like `db.First(&dm, "id = ?", sid)`

`db.First(&dm, sid)` only works for integer primary key
