### ISSUE TITLE
Ignore flag not working on model struct?

### ISSUE THREAD

**Issue by Gacnt** [jinzhu/gorm#983]
I have this model:

```
type User struct {
	gorm.Model

	// The Users username
	Username string `gorm:"size:255;unique;not null"`

	// The Users email address
	Email string `gorm:"size:255;unique;not null"`

	// The Users hashed password
	Password string `gorm:"size:255;not null"`

	// The Users password confirmation (only for forms)
	PasswordC string `gorm:"-"`

	// The Users FULL NAME (e.g. Burt Reynolds)
	Fullname string `gorm:"size:255; not null"`

	// The Users Karma level
	Karma int

	// Is the user banned?
	Banned bool
}
```

But `PasswordC` still shows up in my database using `db.AutoMigrate(User{})` I thought `gorm:"-"` made it be ignored, I wanted to have a `PasswordC` field for using with `Gorilla Schema`

**Comment by jinzhu** [comment]
Are you using an old version?

**Comment by Gacnt** [comment]
I am using the most latest version, my above struct is still creating a `PasswordC` field in the database:

http://imgur.com/2VxLPLa

I just deleted `gorm` and did a fresh `go get github.com/jinzhu/gorm` and I deleted the `users` table but it still comes back with the `passwordc` field

**Comment by Gacnt** [comment]
Seemed to fix it by adding `sql:"-"` to it but I thought that was the responsibility of the `gorm:"-"` flag

**Comment by Gacnt** [comment]
I don't know why this issue was so quick to close. It is clearly an issue that is still an issue, unless the documentation or the code needs to figure out which one is backwards

http://stackoverflow.com/questions/36963008/gorm-not-ignoring-field-with-gorm/36974118#36974118

**Comment by jinzhu** [comment]
Hi @Gacnt 

Sorry for this, I made a mistake, as there are some misusage about tags before caused by not upgrade to latest version, I thought this is same issue.

Just fixed this, sorry.

**Comment by Abramovic** [comment]
I'm having the same problems using the most recent version of gorm. 

```go
type User struct {
  gorm.Model
  Email string `json:"email" gorm:"column:email"`
  /*
  ...
  */
  UserData map[string]interface{} `json:"data" sql:"-" gorm:"-"`
```

```sql: Scan error on column index 9: unsupported driver -> Scan pair: []uint8 -> map[string]interface{}```

**Comment by raphaeljlps** [comment]
I'm also having this issue.

**Comment by mehdy** [comment]
I still have problem with this :/

**Comment by jinzhu** [comment]
@mehdy could you write a script and create a new issue to prove that?

**Comment by mehdy** [comment]
Oh, I think I found the problem. I was using glide and it selected the stable version of gorm which was released almost a year ago!

have you considered releasing new versions?

**Comment by zbintliff** [comment]
Please do this!

**Comment by eoinahern** [comment]
gorm: "-" still adds the column for me?
