### ISSUE TITLE
Are there validation flags for GORM?? 

### ISSUE THREAD

**Issue by Gacnt** [jinzhu/gorm#984]
Are there validation flags for GORM like maxlength minlength, looking through the docs I don't see any other than Unique or Not Null

**Comment by Tobiasartz** [comment]
I ended up using a library like this:
https://github.com/go-playground/validator

Validate yourself before persisting to a DB

Validation should be handled outside of GORM IMHO

**Comment by jinzhu** [comment]
No, but you could checkout this one. https://github.com/qor/validations

**Comment by kdbrian** [comment]
Is this still applicable now that github.com/jinzhu moved to gorm.io
