### ISSUE TITLE
Support for driver.Valuer?

### ISSUE THREAD

**Issue by arschles** [jinzhu/gorm#993]
If I create a struct that has a [`driver.Valuer`](https://godoc.org/database/sql/driver#Valuer) in it, will gorm call its `Value()` function before inserting the struct into the DB? For example, if I have the following:

``` go
import (
  "database/sql/driver"
)

// ...

type MyValuer struct {
  i int
}

func (v MyValuer) Value() (driver.Value, error) {
  return v.i + 1
}

type MyTable struct {
  V1 MyValuer `gorm:"column:v1"`
}

// ...

db.Create(&MyTable{V1:MyValuer{i:1}})
```

Will the `v1` column have the value `2` in it?

**Comment by jinzhu** [comment]
Yes, will use that value

**Comment by MohitKS5** [comment]
It works with custom types in general but if I use embedding to override a method it fails. Any suggestions ?
```go
type jsonb struct {
	postgres.Jsonb
}

func (j jsonb) Value() (driver.Value, error) {
	return "hello", nil
}
```
gorm still calling the value method of postgres,jsonb dialect.
