### ISSUE TITLE
Typo in code in query_test.go

### ISSUE THREAD

**Issue by dominikh** [jinzhu/gorm#996]
The following code compares user.Name with itself but meant to compare it with user1.Name:

```
DB.First(&user, User{Name: user1.Name})
if user.Id == 0 || user.Name != user.Name {
    t.Errorf("Search first record with inline struct")
}
```

```
/src/github.com/jinzhu/gorm/query_test.go:207:21: identical expressions on the left and right side of the '!=' operator
```

**Comment by dominikh** [comment]
Still not fixed: https://github.com/jinzhu/gorm/blob/master/query_test.go#L225

**Comment by jinzhu** [comment]
Sorry for this,I am using `go vet` haven't found this issue, I thought it was fixed, just fixed that.

Thank you for your report.
