### ISSUE TITLE
Order allows sql injection

### ISSUE THREAD

**Issue by RichardKnop** [jinzhu/gorm#997]
You can pass arbitrary SQL strings to Order, for example to drop a database.

This should be fixed asap.

**Comment by eazynow** [comment]
You beat me to it @RichardKnop!

**Comment by RichardKnop** [comment]
I would also check Limit as that seems like a candidate for sql injection too.

**Comment by theoneLee** [comment]
https://github.com/jinzhu/gorm/issues/152
